Tudat: tudat::shape_based_methods::CompositeFunctionSphericalShaping Class Reference
tudat::shape_based_methods::CompositeFunctionSphericalShaping Class Reference
#include <compositeFunctionSphericalShaping.h>
Public Member Functions
CompositeFunctionSphericalShaping ()
Constructor.
~CompositeFunctionSphericalShaping ()
Default destructor.
double evaluateCompositeFunction (const double independentVariable)
double evaluateCompositeFunctionFirstDerivative (const double independentVariable)
double evaluateCompositeFunctionSecondDerivative (const double independentVariable)
double evaluateCompositeFunctionThirdDerivative (const double independentVariable)
double getComponentFunctionCurrentValue (const int componentIndex, const double currentTime)
double getComponentFunctionFirstDerivative (const int componentIndex, const double currentTime)
double getComponentFunctionSecondDerivative (const int componentIndex, const double currentTime)
double getComponentFunctionThirdDerivative (const int componentIndex, const double currentTime)
std::shared_ptr< BaseFunctionSphericalShaping > getCompositeComponent (int indexComponent)
std::vector< std::shared_ptr< BaseFunctionSphericalShaping > > getCompositeComponents ()
Eigen::VectorXd getCompositeFunctionCoefficients ()
Return coefficients.
void resetCompositeFunctionCoefficients (const Eigen::VectorXd &compositeFunctionCoefficients)
Reset coefficients.
Private Attributes
Eigen::VectorXd compositeFunctionCoefficients_
Vector of coefficients.
std::vector< std::shared_ptr< BaseFunctionSphericalShaping > > compositeFunctionComponents_
Detailed Description
Definition at line 26 of file compositeFunctionSphericalShaping.h.
Constructor & Destructor Documentation
CompositeFunctionSphericalShaping()
tudat::shape_based_methods::CompositeFunctionSphericalShaping::CompositeFunctionSphericalShaping () inline
Definition at line 31 of file compositeFunctionSphericalShaping.h.
~CompositeFunctionSphericalShaping()
tudat::shape_based_methods::CompositeFunctionSphericalShaping::~CompositeFunctionSphericalShaping () inline
Default destructor.
Definition at line 37 of file compositeFunctionSphericalShaping.h.
Member Function Documentation
getCompositeFunctionCoefficients()
Eigen::VectorXd tudat::shape_based_methods::CompositeFunctionSphericalShaping::getCompositeFunctionCoefficients () inline
Returns coefficients of composite function.
Definition at line 43 of file compositeFunctionSphericalShaping.h.
References compositeFunctionCoefficients_.
getCompositeComponents()
std::vector< std::shared_ptr< BaseFunctionSphericalShaping > > tudat::shape_based_methods::CompositeFunctionSphericalShaping::getCompositeComponents () inline
Definition at line 48 of file compositeFunctionSphericalShaping.h.
References compositeFunctionComponents_.
getCompositeComponent()
std::shared_ptr< BaseFunctionSphericalShaping > tudat::shape_based_methods::CompositeFunctionSphericalShaping::getCompositeComponent (int indexComponent) inline
Definition at line 53 of file compositeFunctionSphericalShaping.h.
References compositeFunctionComponents_, evaluateCompositeFunction(), evaluateCompositeFunctionFirstDerivative(), evaluateCompositeFunctionSecondDerivative(), evaluateCompositeFunctionThirdDerivative(), getComponentFunctionCurrentValue(), getComponentFunctionFirstDerivative(), getComponentFunctionSecondDerivative(), getComponentFunctionThirdDerivative(), tudat::propagators::independentVariable, and resetCompositeFunctionCoefficients().
resetCompositeFunctionCoefficients()
void tudat::shape_based_methods::CompositeFunctionSphericalShaping::resetCompositeFunctionCoefficients (const Eigen::VectorXd & compositeFunctionCoefficients)
Resets the coefficients of the composite function.
Referenced by getCompositeComponent(), tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::getCompositeFunctionCoefficients(), and tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::getCompositeFunctionCoefficients().
evaluateCompositeFunction()
double tudat::shape_based_methods::CompositeFunctionSphericalShaping::evaluateCompositeFunction (const double independentVariable)
Referenced by getCompositeComponent(), tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::getCompositeFunctionCoefficients(), and tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::getCompositeFunctionCoefficients().
evaluateCompositeFunctionFirstDerivative()
double tudat::shape_based_methods::CompositeFunctionSphericalShaping::evaluateCompositeFunctionFirstDerivative (const double independentVariable)
Referenced by getCompositeComponent(), tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::getCompositeFunctionCoefficients(), and tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::getCompositeFunctionCoefficients().
evaluateCompositeFunctionSecondDerivative()
double tudat::shape_based_methods::CompositeFunctionSphericalShaping::evaluateCompositeFunctionSecondDerivative (const double independentVariable)
Referenced by getCompositeComponent(), tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::getCompositeFunctionCoefficients(), and tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::getCompositeFunctionCoefficients().
evaluateCompositeFunctionThirdDerivative()
double tudat::shape_based_methods::CompositeFunctionSphericalShaping::evaluateCompositeFunctionThirdDerivative (const double independentVariable)
Referenced by getCompositeComponent(), tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::getCompositeFunctionCoefficients(), and tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::getCompositeFunctionCoefficients().
getComponentFunctionCurrentValue()
double tudat::shape_based_methods::CompositeFunctionSphericalShaping::getComponentFunctionCurrentValue (const int componentIndex, const double currentTime)
Referenced by getCompositeComponent(), tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::getCompositeFunctionCoefficients(), and tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::getCompositeFunctionCoefficients().
getComponentFunctionFirstDerivative()
double tudat::shape_based_methods::CompositeFunctionSphericalShaping::getComponentFunctionFirstDerivative (const int componentIndex, const double currentTime)
Referenced by getCompositeComponent(), tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::getCompositeFunctionCoefficients(), and tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::getCompositeFunctionCoefficients().
getComponentFunctionSecondDerivative()
double tudat::shape_based_methods::CompositeFunctionSphericalShaping::getComponentFunctionSecondDerivative (const int componentIndex, const double currentTime)
Referenced by getCompositeComponent(), tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::getCompositeFunctionCoefficients(), and tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::getCompositeFunctionCoefficients().
getComponentFunctionThirdDerivative()
double tudat::shape_based_methods::CompositeFunctionSphericalShaping::getComponentFunctionThirdDerivative (const int componentIndex, const double currentTime)
Referenced by getCompositeComponent(), tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::getCompositeFunctionCoefficients(), and tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::getCompositeFunctionCoefficients().
Member Data Documentation
compositeFunctionComponents_
std::vector< std::shared_ptr< BaseFunctionSphericalShaping > > tudat::shape_based_methods::CompositeFunctionSphericalShaping::compositeFunctionComponents_ private
Definition at line 91 of file compositeFunctionSphericalShaping.h.
Referenced by tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::CompositeElevationFunctionSphericalShaping(), tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::CompositeRadialFunctionSphericalShaping(), getCompositeComponent(), and getCompositeComponents().
compositeFunctionCoefficients_
Eigen::VectorXd tudat::shape_based_methods::CompositeFunctionSphericalShaping::compositeFunctionCoefficients_ private
VectorXd containing coefficients corresponding to components of the composite function.
Definition at line 97 of file compositeFunctionSphericalShaping.h.
Referenced by tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::CompositeElevationFunctionSphericalShaping(), tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::CompositeRadialFunctionSphericalShaping(), getCompositeFunctionCoefficients(), tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::getCompositeFunctionCoefficients(), and tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::getCompositeFunctionCoefficients().
The documentation for this class was generated from the following file:
Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/compositeFunctionSphericalShaping.h