Tudat: tudat::shape_based_methods::SphericalShaping Class Reference
tudat::shape_based_methods::SphericalShaping Class Reference
#include <sphericalShaping.h>
Classes
struct TimeOfFlightFunction
Time of flight function for the root-finder.
Public Member Functions
SphericalShaping (const Eigen::Vector6d &initialState, const Eigen::Vector6d &finalState, const double requiredTimeOfFlight, const double centralBodyGravitationalParameter, const int numberOfRevolutions, const double initialValueFreeCoefficient, const std::shared_ptr< root_finders::RootFinderSettings > rootFinderSettings, const double lowerBoundFreeCoefficient=TUDAT_NAN, const double upperBoundFreeCoefficient=TUDAT_NAN, const double initialBodyMass=TUDAT_NAN)
Constructor for spherical shaping.
~SphericalShaping ()
Default destructor.
Eigen::Vector6d computeCurrentStateVector (const double currentAzimuthAngle)
Compute current cartesian state.
double computeDeltaV ()
Compute deltaV.
Eigen::Vector3d computeThrustAccelerationVector (const double currentAzimuthAngle)
Compute current thrust acceleration in cartesian coordinates.
double computeTimeOfFlight ()
Compute time of flight.
double convertIndependentVariableToTime (const double independentVariable)
Convert independent variable to time.
double convertTimeToIndependentVariable (const double time)
Convert time to independent variable.
double getFinalValueInpendentVariable ()
Returns final value of the independent variable.
double getInitialValueInpendentVariable ()
Returns initial value of the independent variable.
Public Member Functions inherited from tudat::shape_based_methods::ShapeBasedMethod
ShapeBasedMethod (const Eigen::Vector6d &stateAtDeparture, const Eigen::Vector6d &stateAtArrival, const double timeOfFlight, const double initialBodyMass=TUDAT_NAN)
Empty constructor.
virtual ~ShapeBasedMethod ()
Default destructor.
Eigen::Vector3d computeCurrentThrustForce (double time, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute current thrust vector.
std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > createLowThrustTranslationalStatePropagatorSettings (const std::string &bodyToPropagate, const std::string &centralBody, const basic_astrodynamics::AccelerationMap &accelerationModelMap, const std::shared_ptr< propagators::DependentVariableSaveSettings > dependentVariablesToSave)
Define appropriate translational state propagator settings for the full propagation.
void getThrustForceProfile (std::vector< double > &epochsVector, std::map< double, Eigen::VectorXd > &thrustProfile, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Return thrust profile.
void getTrajectory (std::vector< double > &epochsVector, std::map< double, Eigen::Vector6d > &propagatedTrajectory)
Returns state history.
basic_astrodynamics::AccelerationMap retrieveLowThrustAccelerationMap (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::string &centralBody, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Retrieve acceleration map (thrust and central gravity accelerations).
Public Member Functions inherited from tudat::low_thrust_trajectories::LowThrustLeg
LowThrustLeg (const Eigen::Vector6d &stateAtDeparture, const Eigen::Vector6d &stateAtArrival, const double timeOfFlight, const double initialMass, const bool legModelIsForceBased)
Constructor with immediate definition of parameters.
virtual ~LowThrustLeg ()
double computeCurrentMass (const double independentVariable, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute current mass of the spacecraft.
Eigen::Vector3d computeCurrentThrustAcceleration (double time, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute current thrust vector.
void computeSemiAnalyticalAndFullPropagation (const simulation_setup::NamedBodyMap &bodyMapTest, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const std::pair< std::shared_ptr< propagators::PropagatorSettings< double > >, std::shared_ptr< propagators::PropagatorSettings< double > > > &propagatorSettings, std::map< double, Eigen::VectorXd > &fullPropagationResults, std::map< double, Eigen::Vector6d > &semiAnalyticalResults, std::map< double, Eigen::VectorXd > &dependentVariablesHistory)
Full propagation.
std::pair< std::shared_ptr< propagators::PropagatorSettings< double > >, std::shared_ptr< propagators::PropagatorSettings< double > > > createLowThrustPropagatorSettings (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::string &centralBody, const std::function< double(const double) > specificImpulseFunction, const basic_astrodynamics::AccelerationMap perturbingAccelerationsMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > &integratorSettings, const std::shared_ptr< propagators::DependentVariableSaveSettings > &dependentVariablesToSave)
Define appropriate propagator settings for the full propagation.
std::shared_ptr< propulsion::ThrustAcceleration > getLowThrustAccelerationModel (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const double timeOffset=0.0)
Retrieve acceleration model (thrust).
std::shared_ptr< simulation_setup::ThrustAccelerationSettings > getLowThrustAccelerationSettings (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const double timeOffset=0.0)
Retrieve acceleration model (thrust).
void getMassProfile (const std::vector< double > &epochsVector, std::map< double, Eigen::VectorXd > &massProfile, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Return mass profile.
virtual void getThrustAccelerationProfile (std::vector< double > &epochsVector, std::map< double, Eigen::VectorXd > &thrustAccelerationProfile, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Return thrust acceleration profile.
Protected Member Functions
Eigen::Vector3d computeCurrentThrustAccelerationDirection (double currentTime, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute direction thrust acceleration in cartesian coordinates.
double computeCurrentThrustAccelerationMagnitude (double currentTime, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute magnitude thrust acceleration.
double computeCurrentTimeFromAzimuthAngle (const double currentAzimuthAngle)
Compute current time from azimuth angle.
double computeDerivativeScalarFunctionTimeEquation (double currentAzimuthAngle)
Compute second derivative of the scalar function D in the time equation (ADD REFERENCE AND EQUATION NUMBER) w.r.t. azimuth angle.
double computeFinalAlphaValue ()
Compute the final value of the variable alpha, as defined in ... (ADD REFERENCE) to express the boundary conditions.
double computeFinalValueBoundariesConstant ()
Compute the final value of the constant C, as defined in ... (ADD REFERENCE) to express the boundary conditions.
double computeFirstDerivativeAzimuthAngleWrtTime (const double currentAzimuthAngle)
Compute first derivative of the azimuth angle w.r.t. time.
double computeInitialAlphaValue ()
Compute the initial value of the variable alpha, as defined in ... (ADD REFERENCE) to express the boundary conditions.
double computeInitialValueBoundariesConstant ()
Compute the initial value of the constant C, as defined in ... (ADD REFERENCE) to express the boundary conditions.
Eigen::MatrixXd computeInverseMatrixBoundaryConditions ()
Compute the inverse of the boundary conditions matrix.
double computeNormalizedTimeOfFlight ()
Compute normalized time of flight.
double computeScalarFunctionTimeEquation (double currentAzimuthAngle)
Compute derivative of the scalar function D in the time equation (ADD REFERENCE AND EQUATION NUMBER) w.r.t. azimuth angle.
double computeSecondDerivativeAzimuthAngleWrtTime (const double currentAzimuthAngle)
Compute second derivative of the azimuth angle w.r.t. time.
Eigen::Vector6d computeStateVectorInSphericalCoordinates (const double currentAzimuthAngle)
Compute state vector in spherical coordinates.
Eigen::Vector3d computeThrustAccelerationVectorInSphericalCoordinates (const double currentAzimuthAngle)
Compute thrust acceleration vector in spherical coordinates.
Eigen::Vector3d computeThrustAccelerationVectorParametrizedByAzimuthAngle (const double currentAzimuthAngle)
Compute current acceleration in spherical coordinates parametrized by azimuth angle theta.
Eigen::Vector3d computeVelocityVectorParametrizedByAzimuthAngle (const double currentAzimuthAngle)
Compute current velocity in spherical coordinates parametrized by azimuth angle theta.
double getNormalizedRequiredTimeOfFlight ()
Return the required value for the time of flight (normalized w.r.t. julian year).
void iterateToMatchRequiredTimeOfFlight (std::shared_ptr< root_finders::RootFinderSettings > rootFinderSettings, const double lowerBound=TUDAT_NAN, const double upperBound=TUDAT_NAN, const double initialGuess=TUDAT_NAN)
Iterate to match the required time of flight, by updating the value of the free coefficient.
void resetValueFreeCoefficient (const double freeCoefficient)
Reset the value of the free coefficient, in order to match the required time of flight.
void satisfyBoundaryConditions ()
Ensure that the boundary conditions are respected.
Protected Member Functions inherited from tudat::low_thrust_trajectories::LowThrustLeg
double computeCurrentMass (const double timeInitialEpoch, const double timeFinalEpoch, const double massInitialEpoch, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute current mass of the spacecraft between two epochs.
Private Attributes
double centralBodyGravitationalParameter_
Central body gravitational parameter.
Eigen::VectorXd coefficientsElevationAngleFunction_
Coefficients for the elevation angle composite function.
Eigen::VectorXd coefficientsRadialDistanceFunction_
Coefficients for the radial distance composite function.
std::shared_ptr< CompositeElevationFunctionSphericalShaping > elevationAngleCompositeFunction_
Pointer to the spherical shaping elevation angle composite function.
double finalAzimuthAngle_
Final value azimuth angle.
Eigen::Vector6d finalStateParametrizedByAzimuthAngle_
Final state parametrised by the azimuth angle theta.
Eigen::Vector6d finalStateSphericalCoordinates_
Final state in spherical coordinates.
double initialAzimuthAngle_
Initial value azimuth angle.
Eigen::Vector6d initialStateParametrizedByAzimuthAngle_
Initial state parametrised by the azimuth angle theta.
Eigen::Vector6d initialStateSphericalCoordinates_
Initial state in spherical coordinates.
double initialValueFreeCoefficient_
Initial guess for the free coefficient (i.e. coefficient of the second order component of the radial inverse polynomial).
std::shared_ptr< interpolators::OneDimensionalInterpolator< double, double > > interpolator_
Eigen::MatrixXd inverseMatrixBoundaryConditions_
Inverse of matrix containing the boundary conditions.
const double lowerBoundFreeCoefficient_
Lower bound for the free coefficient, to be used when trying to match the required time of flight.
int numberOfRevolutions_
Number of revolutions.
std::shared_ptr< CompositeRadialFunctionSphericalShaping > radialDistanceCompositeFunction_
Pointer to the spherical shaping radial distance composite function.
std::shared_ptr< root_finders::RootFinderSettings > rootFinderSettings_
Root finder settings, to be used to find the free coefficient value that ensures the time of flight is correct.
std::map< double, Eigen::Vector3d > thrustAccelerationVectorCache_
const double upperBoundFreeCoefficient_
Upper bound for the free coefficient, to be used when trying to match the required time of flight.
Additional Inherited Members
Protected Attributes inherited from tudat::shape_based_methods::ShapeBasedMethod
std::shared_ptr< numerical_quadrature::QuadratureSettings< double > > quadratureSettings_
Numerical quadrature settings, required to compute the time of flight and total deltaV.
Protected Attributes inherited from tudat::low_thrust_trajectories::LowThrustLeg
double initialMass_
bool legModelIsForceBased_
Eigen::Vector6d stateAtArrival_
Cartesian state at arrival.
Eigen::Vector6d stateAtDeparture_
Cartesian state at departure.
double timeOfFlight_
Time of flight of the trajectory leg.
Detailed Description
Definition at line 32 of file sphericalShaping.h.
Constructor & Destructor Documentation
SphericalShaping()
tudat::shape_based_methods::SphericalShaping::SphericalShaping (const Eigen::Vector6d & initialState, const Eigen::Vector6d & finalState, const double requiredTimeOfFlight, const double centralBodyGravitationalParameter, const int numberOfRevolutions, const double initialValueFreeCoefficient, const std::shared_ptr< root_finders::RootFinderSettings > rootFinderSettings, const double lowerBoundFreeCoefficient = TUDAT_NAN, const double upperBoundFreeCoefficient = TUDAT_NAN, const double initialBodyMass = TUDAT_NAN)
Constructur for spherical shaping.
Definition at line 25 of file sphericalShaping.cpp.
References tudat::physical_constants::ASTRONOMICAL_UNIT, centralBodyGravitationalParameter_, coefficientsElevationAngleFunction_, coefficientsRadialDistanceFunction_, computeCurrentTimeFromAzimuthAngle(), computeNormalizedTimeOfFlight(), tudat::coordinate_conversions::convertCartesianToSphericalState(), tudat::interpolators::createOneDimensionalInterpolator(), elevationAngleCompositeFunction_, finalAzimuthAngle_, finalStateParametrizedByAzimuthAngle_, finalStateSphericalCoordinates_, initialAzimuthAngle_, initialStateParametrizedByAzimuthAngle_, initialStateSphericalCoordinates_, initialValueFreeCoefficient_, interpolator_, iterateToMatchRequiredTimeOfFlight(), tudat::physical_constants::JULIAN_YEAR, lowerBoundFreeCoefficient_, numberOfRevolutions_, tudat::mathematical_constants::PI, tudat::shape_based_methods::ShapeBasedMethod::quadratureSettings_, radialDistanceCompositeFunction_, rootFinderSettings_, tudat::low_thrust_trajectories::LowThrustLeg::stateAtArrival_, tudat::low_thrust_trajectories::LowThrustLeg::stateAtDeparture_, and upperBoundFreeCoefficient_.
~SphericalShaping()
tudat::shape_based_methods::SphericalShaping::~SphericalShaping () inline
Definition at line 49 of file sphericalShaping.h.
References convertIndependentVariableToTime(), convertTimeToIndependentVariable(), and tudat::propagators::independentVariable.
Member Function Documentation
convertTimeToIndependentVariable()
double tudat::shape_based_methods::SphericalShaping::convertTimeToIndependentVariable (const double time) virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 160 of file sphericalShaping.cpp.
References interpolator_.
Referenced by ~SphericalShaping().
convertIndependentVariableToTime()
double tudat::shape_based_methods::SphericalShaping::convertIndependentVariableToTime (const double independentVariable) virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 167 of file sphericalShaping.cpp.
References centralBodyGravitationalParameter_, computeScalarFunctionTimeEquation(), tudat::numerical_quadrature::createQuadrature(), tudat::shape_based_methods::ShapeBasedMethod::quadratureSettings_, and radialDistanceCompositeFunction_.
Referenced by ~SphericalShaping().
getInitialValueInpendentVariable()
double tudat::shape_based_methods::SphericalShaping::getInitialValueInpendentVariable () inline virtual
Implements tudat::shape_based_methods::ShapeBasedMethod.
Definition at line 58 of file sphericalShaping.h.
References initialAzimuthAngle_.
getFinalValueInpendentVariable()
double tudat::shape_based_methods::SphericalShaping::getFinalValueInpendentVariable () inline virtual
Implements tudat::shape_based_methods::ShapeBasedMethod.
Definition at line 64 of file sphericalShaping.h.
References finalAzimuthAngle_.
computeTimeOfFlight()
double tudat::shape_based_methods::SphericalShaping::computeTimeOfFlight () inline
Definition at line 70 of file sphericalShaping.h.
References computeCurrentStateVector(), computeDeltaV(), computeDerivativeScalarFunctionTimeEquation(), computeFinalAlphaValue(), computeFinalValueBoundariesConstant(), computeInitialAlphaValue(), computeInitialValueBoundariesConstant(), computeInverseMatrixBoundaryConditions(), computeNormalizedTimeOfFlight(), computeScalarFunctionTimeEquation(), computeThrustAccelerationVector(), iterateToMatchRequiredTimeOfFlight(), tudat::physical_constants::JULIAN_YEAR, satisfyBoundaryConditions(), and TUDAT_NAN.
computeCurrentStateVector()
Eigen::Vector6d tudat::shape_based_methods::SphericalShaping::computeCurrentStateVector (const double currentAzimuthAngle) virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 528 of file sphericalShaping.cpp.
References tudat::physical_constants::ASTRONOMICAL_UNIT, computeStateVectorInSphericalCoordinates(), tudat::coordinate_conversions::convertSphericalToCartesianState(), and tudat::physical_constants::JULIAN_YEAR.
Referenced by computeTimeOfFlight().
computeThrustAccelerationVector()
Eigen::Vector3d tudat::shape_based_methods::SphericalShaping::computeThrustAccelerationVector (const double currentAzimuthAngle)
Definition at line 608 of file sphericalShaping.cpp.
References tudat::physical_constants::ASTRONOMICAL_UNIT, computeThrustAccelerationVectorInSphericalCoordinates(), tudat::coordinate_conversions::convertSphericalToCartesianState(), elevationAngleCompositeFunction_, tudat::physical_constants::JULIAN_YEAR, radialDistanceCompositeFunction_, and thrustAccelerationVectorCache_.
Referenced by computeCurrentThrustAccelerationDirection(), computeCurrentThrustAccelerationMagnitude(), and computeTimeOfFlight().
computeDeltaV()
double tudat::shape_based_methods::SphericalShaping::computeDeltaV () virtual
Compute final deltaV.
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 646 of file sphericalShaping.cpp.
References tudat::physical_constants::ASTRONOMICAL_UNIT, centralBodyGravitationalParameter_, computeScalarFunctionTimeEquation(), computeThrustAccelerationVectorInSphericalCoordinates(), tudat::numerical_quadrature::createQuadrature(), finalAzimuthAngle_, tudat::physical_constants::JULIAN_YEAR, tudat::shape_based_methods::ShapeBasedMethod::quadratureSettings_, and radialDistanceCompositeFunction_.
Referenced by computeTimeOfFlight().
computeInverseMatrixBoundaryConditions()
Eigen::MatrixXd tudat::shape_based_methods::SphericalShaping::computeInverseMatrixBoundaryConditions () protected
Definition at line 197 of file sphericalShaping.cpp.
References computeFinalAlphaValue(), computeInitialAlphaValue(), elevationAngleCompositeFunction_, finalAzimuthAngle_, finalStateSphericalCoordinates_, initialAzimuthAngle_, initialStateSphericalCoordinates_, and radialDistanceCompositeFunction_.
Referenced by computeTimeOfFlight(), and satisfyBoundaryConditions().
computeInitialAlphaValue()
double tudat::shape_based_methods::SphericalShaping::computeInitialAlphaValue () protected
Definition at line 240 of file sphericalShaping.cpp.
References initialStateParametrizedByAzimuthAngle_.
Referenced by computeInverseMatrixBoundaryConditions(), and computeTimeOfFlight().
computeFinalAlphaValue()
double tudat::shape_based_methods::SphericalShaping::computeFinalAlphaValue () protected
Definition at line 247 of file sphericalShaping.cpp.
References finalStateParametrizedByAzimuthAngle_.
Referenced by computeInverseMatrixBoundaryConditions(), and computeTimeOfFlight().
computeInitialValueBoundariesConstant()
double tudat::shape_based_methods::SphericalShaping::computeInitialValueBoundariesConstant () protected
Definition at line 254 of file sphericalShaping.cpp.
References centralBodyGravitationalParameter_, initialStateParametrizedByAzimuthAngle_, and initialStateSphericalCoordinates_.
Referenced by computeTimeOfFlight(), and satisfyBoundaryConditions().
computeFinalValueBoundariesConstant()
double tudat::shape_based_methods::SphericalShaping::computeFinalValueBoundariesConstant () protected
Definition at line 270 of file sphericalShaping.cpp.
References centralBodyGravitationalParameter_, finalStateParametrizedByAzimuthAngle_, and finalStateSphericalCoordinates_.
Referenced by computeTimeOfFlight(), and satisfyBoundaryConditions().
satisfyBoundaryConditions()
void tudat::shape_based_methods::SphericalShaping::satisfyBoundaryConditions () protected
Definition at line 286 of file sphericalShaping.cpp.
References coefficientsElevationAngleFunction_, coefficientsRadialDistanceFunction_, computeFinalValueBoundariesConstant(), computeInitialValueBoundariesConstant(), computeInverseMatrixBoundaryConditions(), elevationAngleCompositeFunction_, finalAzimuthAngle_, finalStateParametrizedByAzimuthAngle_, initialAzimuthAngle_, initialStateParametrizedByAzimuthAngle_, initialValueFreeCoefficient_, inverseMatrixBoundaryConditions_, and radialDistanceCompositeFunction_.
Referenced by computeTimeOfFlight(), and iterateToMatchRequiredTimeOfFlight().
iterateToMatchRequiredTimeOfFlight()
void tudat::shape_based_methods::SphericalShaping::iterateToMatchRequiredTimeOfFlight (std::shared_ptr< root_finders::RootFinderSettings > rootFinderSettings, const double lowerBound = TUDAT_NAN, const double upperBound = TUDAT_NAN, const double initialGuess = TUDAT_NAN) protected
Iterate to match the required time of flight.
Definition at line 454 of file sphericalShaping.cpp.
References computeNormalizedTimeOfFlight(), tudat::root_finders::createRootFinder(), getNormalizedRequiredTimeOfFlight(), resetValueFreeCoefficient(), and satisfyBoundaryConditions().
Referenced by computeTimeOfFlight(), and SphericalShaping().
computeScalarFunctionTimeEquation()
double tudat::shape_based_methods::SphericalShaping::computeScalarFunctionTimeEquation (double currentAzimuthAngle) protected
Definition at line 351 of file sphericalShaping.cpp.
References elevationAngleCompositeFunction_, and radialDistanceCompositeFunction_.
Referenced by computeCurrentTimeFromAzimuthAngle(), computeDeltaV(), computeFirstDerivativeAzimuthAngleWrtTime(), computeNormalizedTimeOfFlight(), computeSecondDerivativeAzimuthAngleWrtTime(), computeTimeOfFlight(), and convertIndependentVariableToTime().
computeDerivativeScalarFunctionTimeEquation()
double tudat::shape_based_methods::SphericalShaping::computeDerivativeScalarFunctionTimeEquation (double currentAzimuthAngle) protected
Definition at line 368 of file sphericalShaping.cpp.
References elevationAngleCompositeFunction_, and radialDistanceCompositeFunction_.
Referenced by computeSecondDerivativeAzimuthAngleWrtTime(), and computeTimeOfFlight().
getNormalizedRequiredTimeOfFlight()
double tudat::shape_based_methods::SphericalShaping::getNormalizedRequiredTimeOfFlight () inline protected
Definition at line 120 of file sphericalShaping.h.
References computeCurrentTimeFromAzimuthAngle(), computeNormalizedTimeOfFlight(), tudat::physical_constants::JULIAN_YEAR, and tudat::low_thrust_trajectories::LowThrustLeg::timeOfFlight_.
Referenced by iterateToMatchRequiredTimeOfFlight().
computeNormalizedTimeOfFlight()
double tudat::shape_based_methods::SphericalShaping::computeNormalizedTimeOfFlight () protected
Definition at line 397 of file sphericalShaping.cpp.
References centralBodyGravitationalParameter_, computeScalarFunctionTimeEquation(), tudat::numerical_quadrature::createQuadrature(), finalAzimuthAngle_, tudat::shape_based_methods::ShapeBasedMethod::quadratureSettings_, and radialDistanceCompositeFunction_.
Referenced by computeTimeOfFlight(), getNormalizedRequiredTimeOfFlight(), iterateToMatchRequiredTimeOfFlight(), and SphericalShaping().
computeCurrentTimeFromAzimuthAngle()
double tudat::shape_based_methods::SphericalShaping::computeCurrentTimeFromAzimuthAngle (const double currentAzimuthAngle) protected
Definition at line 426 of file sphericalShaping.cpp.
References centralBodyGravitationalParameter_, computeScalarFunctionTimeEquation(), tudat::numerical_quadrature::createQuadrature(), tudat::shape_based_methods::ShapeBasedMethod::quadratureSettings_, and radialDistanceCompositeFunction_.
Referenced by getNormalizedRequiredTimeOfFlight(), and SphericalShaping().
resetValueFreeCoefficient()
void tudat::shape_based_methods::SphericalShaping::resetValueFreeCoefficient (const double freeCoefficient) inline protected
Definition at line 132 of file sphericalShaping.h.
References coefficientsRadialDistanceFunction_, computeCurrentThrustAccelerationDirection(), computeCurrentThrustAccelerationMagnitude(), computeFirstDerivativeAzimuthAngleWrtTime(), computeSecondDerivativeAzimuthAngleWrtTime(), computeStateVectorInSphericalCoordinates(), computeThrustAccelerationVectorInSphericalCoordinates(), computeThrustAccelerationVectorParametrizedByAzimuthAngle(), computeVelocityVectorParametrizedByAzimuthAngle(), and initialValueFreeCoefficient_.
Referenced by iterateToMatchRequiredTimeOfFlight().
computeFirstDerivativeAzimuthAngleWrtTime()
double tudat::shape_based_methods::SphericalShaping::computeFirstDerivativeAzimuthAngleWrtTime (const double currentAzimuthAngle) protected
Compute current derivative of the azimuth angle.
Definition at line 479 of file sphericalShaping.cpp.
References centralBodyGravitationalParameter_, computeScalarFunctionTimeEquation(), and radialDistanceCompositeFunction_.
Referenced by computeSecondDerivativeAzimuthAngleWrtTime(), computeStateVectorInSphericalCoordinates(), computeThrustAccelerationVectorInSphericalCoordinates(), and resetValueFreeCoefficient().
computeSecondDerivativeAzimuthAngleWrtTime()
double tudat::shape_based_methods::SphericalShaping::computeSecondDerivativeAzimuthAngleWrtTime (const double currentAzimuthAngle) protected
Compute second derivative of the azimuth angle.
Definition at line 492 of file sphericalShaping.cpp.
References computeDerivativeScalarFunctionTimeEquation(), computeFirstDerivativeAzimuthAngleWrtTime(), computeScalarFunctionTimeEquation(), and radialDistanceCompositeFunction_.
Referenced by computeThrustAccelerationVectorInSphericalCoordinates(), and resetValueFreeCoefficient().
computeVelocityVectorParametrizedByAzimuthAngle()
Eigen::Vector3d tudat::shape_based_methods::SphericalShaping::computeVelocityVectorParametrizedByAzimuthAngle (const double currentAzimuthAngle) protected
Definition at line 543 of file sphericalShaping.cpp.
References elevationAngleCompositeFunction_, and radialDistanceCompositeFunction_.
Referenced by computeStateVectorInSphericalCoordinates(), computeThrustAccelerationVectorInSphericalCoordinates(), and resetValueFreeCoefficient().
computeStateVectorInSphericalCoordinates()
Eigen::Vector6d tudat::shape_based_methods::SphericalShaping::computeStateVectorInSphericalCoordinates (const double currentAzimuthAngle) protected
Compute current state vector in spherical coordinates.
Definition at line 511 of file sphericalShaping.cpp.
References computeFirstDerivativeAzimuthAngleWrtTime(), computeVelocityVectorParametrizedByAzimuthAngle(), elevationAngleCompositeFunction_, and radialDistanceCompositeFunction_.
Referenced by computeCurrentStateVector(), and resetValueFreeCoefficient().
computeThrustAccelerationVectorParametrizedByAzimuthAngle()
Eigen::Vector3d tudat::shape_based_methods::SphericalShaping::computeThrustAccelerationVectorParametrizedByAzimuthAngle (const double currentAzimuthAngle) protected
Definition at line 560 of file sphericalShaping.cpp.
References elevationAngleCompositeFunction_, and radialDistanceCompositeFunction_.
Referenced by computeThrustAccelerationVectorInSphericalCoordinates(), and resetValueFreeCoefficient().
computeThrustAccelerationVectorInSphericalCoordinates()
Eigen::Vector3d tudat::shape_based_methods::SphericalShaping::computeThrustAccelerationVectorInSphericalCoordinates (const double currentAzimuthAngle) protected
Definition at line 584 of file sphericalShaping.cpp.
References centralBodyGravitationalParameter_, computeFirstDerivativeAzimuthAngleWrtTime(), computeSecondDerivativeAzimuthAngleWrtTime(), computeThrustAccelerationVectorParametrizedByAzimuthAngle(), computeVelocityVectorParametrizedByAzimuthAngle(), and radialDistanceCompositeFunction_.
Referenced by computeDeltaV(), computeThrustAccelerationVector(), and resetValueFreeCoefficient().
computeCurrentThrustAccelerationMagnitude()
double tudat::shape_based_methods::SphericalShaping::computeCurrentThrustAccelerationMagnitude (double currentTime, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings) protected virtual
Compute magnitude cartesian acceleration.
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 630 of file sphericalShaping.cpp.
References computeThrustAccelerationVector().
Referenced by resetValueFreeCoefficient().
computeCurrentThrustAccelerationDirection()
Eigen::Vector3d tudat::shape_based_methods::SphericalShaping::computeCurrentThrustAccelerationDirection (double currentTime, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings) protected virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 638 of file sphericalShaping.cpp.
References computeThrustAccelerationVector().
Referenced by resetValueFreeCoefficient().
Member Data Documentation
centralBodyGravitationalParameter_
double tudat::shape_based_methods::SphericalShaping::centralBodyGravitationalParameter_ private
Definition at line 235 of file sphericalShaping.h.
Referenced by computeCurrentTimeFromAzimuthAngle(), computeDeltaV(), computeFinalValueBoundariesConstant(), computeFirstDerivativeAzimuthAngleWrtTime(), computeInitialValueBoundariesConstant(), computeNormalizedTimeOfFlight(), computeThrustAccelerationVectorInSphericalCoordinates(), convertIndependentVariableToTime(), and SphericalShaping().
numberOfRevolutions_
int tudat::shape_based_methods::SphericalShaping::numberOfRevolutions_ private
Definition at line 238 of file sphericalShaping.h.
Referenced by SphericalShaping().
initialStateSphericalCoordinates_
Eigen::Vector6d tudat::shape_based_methods::SphericalShaping::initialStateSphericalCoordinates_ private
Definition at line 241 of file sphericalShaping.h.
Referenced by computeInitialValueBoundariesConstant(), computeInverseMatrixBoundaryConditions(), and SphericalShaping().
finalStateSphericalCoordinates_
Eigen::Vector6d tudat::shape_based_methods::SphericalShaping::finalStateSphericalCoordinates_ private
Definition at line 244 of file sphericalShaping.h.
Referenced by computeFinalValueBoundariesConstant(), computeInverseMatrixBoundaryConditions(), and SphericalShaping().
initialAzimuthAngle_
double tudat::shape_based_methods::SphericalShaping::initialAzimuthAngle_ private
Definition at line 247 of file sphericalShaping.h.
Referenced by computeInverseMatrixBoundaryConditions(), getInitialValueInpendentVariable(), satisfyBoundaryConditions(), and SphericalShaping().
finalAzimuthAngle_
double tudat::shape_based_methods::SphericalShaping::finalAzimuthAngle_ private
Definition at line 250 of file sphericalShaping.h.
Referenced by computeDeltaV(), computeInverseMatrixBoundaryConditions(), computeNormalizedTimeOfFlight(), getFinalValueInpendentVariable(), satisfyBoundaryConditions(), and SphericalShaping().
initialStateParametrizedByAzimuthAngle_
Eigen::Vector6d tudat::shape_based_methods::SphericalShaping::initialStateParametrizedByAzimuthAngle_ private
Definition at line 253 of file sphericalShaping.h.
Referenced by computeInitialAlphaValue(), computeInitialValueBoundariesConstant(), satisfyBoundaryConditions(), and SphericalShaping().
finalStateParametrizedByAzimuthAngle_
Eigen::Vector6d tudat::shape_based_methods::SphericalShaping::finalStateParametrizedByAzimuthAngle_ private
Definition at line 256 of file sphericalShaping.h.
Referenced by computeFinalAlphaValue(), computeFinalValueBoundariesConstant(), satisfyBoundaryConditions(), and SphericalShaping().
radialDistanceCompositeFunction_
std::shared_ptr< CompositeRadialFunctionSphericalShaping > tudat::shape_based_methods::SphericalShaping::radialDistanceCompositeFunction_ private
Definition at line 259 of file sphericalShaping.h.
Referenced by computeCurrentTimeFromAzimuthAngle(), computeDeltaV(), computeDerivativeScalarFunctionTimeEquation(), computeFirstDerivativeAzimuthAngleWrtTime(), computeInverseMatrixBoundaryConditions(), computeNormalizedTimeOfFlight(), computeScalarFunctionTimeEquation(), computeSecondDerivativeAzimuthAngleWrtTime(), computeStateVectorInSphericalCoordinates(), computeThrustAccelerationVector(), computeThrustAccelerationVectorInSphericalCoordinates(), computeThrustAccelerationVectorParametrizedByAzimuthAngle(), computeVelocityVectorParametrizedByAzimuthAngle(), convertIndependentVariableToTime(), satisfyBoundaryConditions(), and SphericalShaping().
elevationAngleCompositeFunction_
std::shared_ptr< CompositeElevationFunctionSphericalShaping > tudat::shape_based_methods::SphericalShaping::elevationAngleCompositeFunction_ private
Definition at line 262 of file sphericalShaping.h.
Referenced by computeDerivativeScalarFunctionTimeEquation(), computeInverseMatrixBoundaryConditions(), computeScalarFunctionTimeEquation(), computeStateVectorInSphericalCoordinates(), computeThrustAccelerationVector(), computeThrustAccelerationVectorParametrizedByAzimuthAngle(), computeVelocityVectorParametrizedByAzimuthAngle(), satisfyBoundaryConditions(), and SphericalShaping().
coefficientsRadialDistanceFunction_
Eigen::VectorXd tudat::shape_based_methods::SphericalShaping::coefficientsRadialDistanceFunction_ private
Definition at line 265 of file sphericalShaping.h.
Referenced by resetValueFreeCoefficient(), satisfyBoundaryConditions(), and SphericalShaping().
coefficientsElevationAngleFunction_
Eigen::VectorXd tudat::shape_based_methods::SphericalShaping::coefficientsElevationAngleFunction_ private
Definition at line 268 of file sphericalShaping.h.
Referenced by satisfyBoundaryConditions(), and SphericalShaping().
initialValueFreeCoefficient_
double tudat::shape_based_methods::SphericalShaping::initialValueFreeCoefficient_ private
Definition at line 271 of file sphericalShaping.h.
Referenced by resetValueFreeCoefficient(), satisfyBoundaryConditions(), and SphericalShaping().
rootFinderSettings_
std::shared_ptr< root_finders::RootFinderSettings > tudat::shape_based_methods::SphericalShaping::rootFinderSettings_ private
Definition at line 274 of file sphericalShaping.h.
Referenced by SphericalShaping().
lowerBoundFreeCoefficient_
const double tudat::shape_based_methods::SphericalShaping::lowerBoundFreeCoefficient_ private
Definition at line 277 of file sphericalShaping.h.
Referenced by SphericalShaping().
upperBoundFreeCoefficient_
const double tudat::shape_based_methods::SphericalShaping::upperBoundFreeCoefficient_ private
Definition at line 280 of file sphericalShaping.h.
Referenced by SphericalShaping().
inverseMatrixBoundaryConditions_
Eigen::MatrixXd tudat::shape_based_methods::SphericalShaping::inverseMatrixBoundaryConditions_ private
Definition at line 283 of file sphericalShaping.h.
Referenced by satisfyBoundaryConditions().
interpolator_
std::shared_ptr< interpolators::OneDimensionalInterpolator< double, double > > tudat::shape_based_methods::SphericalShaping::interpolator_ private
Definition at line 287 of file sphericalShaping.h.
Referenced by convertTimeToIndependentVariable(), and SphericalShaping().
thrustAccelerationVectorCache_
std::map< double, Eigen::Vector3d > tudat::shape_based_methods::SphericalShaping::thrustAccelerationVectorCache_ private
Definition at line 289 of file sphericalShaping.h.
Referenced by computeThrustAccelerationVector().
The documentation for this class was generated from the following files:
sphericalShaping.h
sphericalShaping.cpp