Tudat: tudat::low_thrust_trajectories::HybridMethod Class Reference
tudat::low_thrust_trajectories::HybridMethod Class Reference
#include <hybridMethod.h>
Public Member Functions
HybridMethod (const Eigen::Vector6d &stateAtDeparture, const Eigen::Vector6d &stateAtArrival, const double maximumThrust, const double specificImpulse, const double timeOfFlight, std::shared_ptr< simulation_setup::OptimisationSettings > optimisationSettings, const std::pair< double, double > initialAndFinalMEEcostatesBounds=std::make_pair(- 10.0, 10.0))
Constructor.
~HybridMethod ()
Default destructor.
Eigen::Vector6d computeCurrentStateVector (const double currentTime)
Compute current cartesian state.
Eigen::Vector3d computeCurrentThrustAccelerationDirection (double currentTime, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute direction thrust acceleration in cartesian coordinates.
double computeCurrentThrustAccelerationMagnitude (double currentTime, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute magnitude thrust acceleration.
Eigen::Vector3d computeCurrentThrustForce (double time, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute current thrust vector.
double computeDeltaV ()
Compute DeltaV.
double convertIndependentVariableToTime (const double independentVariable)
Convert independent variable to time.
double convertTimeToIndependentVariable (const double time)
Convert time to independent variable.
std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > createLowThrustTranslationalStatePropagatorSettings (basic_astrodynamics::AccelerationMap accelerationModelMap, std::shared_ptr< propagators::DependentVariableSaveSettings > dependentVariablesToSave)
Define appropriate translational state propagator settings for the full propagation.
std::vector< double > getBestIndividual ()
Return best individual.
std::vector< double > getBestIndividualFitness ()
Return fitness of best individual.
std::shared_ptr< HybridMethodModel > getOptimalHybridMethodModel ()
Return best hybrid method leg after optimisation.
void getThrustAccelerationProfile (std::vector< double > &epochsVector, std::map< double, Eigen::VectorXd > &thrustAccelerationProfile, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Return thrust acceleration profile.
void getThrustForceProfile (std::vector< double > &epochsVector, std::map< double, Eigen::VectorXd > &thrustProfile, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Return thrust profile.
void getTrajectory (std::vector< double > &epochsVector, std::map< double, Eigen::Vector6d > &propagatedTrajectory)
Compute state history.
std::pair< std::vector< double >, std::vector< double > > performOptimisation ()
Perform optimisation.
basic_astrodynamics::AccelerationMap retrieveLowThrustAccelerationMap (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::string &centralBody, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Retrieve acceleration map (thrust and central gravity accelerations).
Public Member Functions inherited from tudat::low_thrust_trajectories::LowThrustLeg
LowThrustLeg (const Eigen::Vector6d &stateAtDeparture, const Eigen::Vector6d &stateAtArrival, const double timeOfFlight, const double initialMass, const bool legModelIsForceBased)
Constructor with immediate definition of parameters.
virtual ~LowThrustLeg ()
double computeCurrentMass (const double independentVariable, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute current mass of the spacecraft.
Eigen::Vector3d computeCurrentThrustAcceleration (double time, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute current thrust vector.
void computeSemiAnalyticalAndFullPropagation (const simulation_setup::NamedBodyMap &bodyMapTest, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const std::pair< std::shared_ptr< propagators::PropagatorSettings< double > >, std::shared_ptr< propagators::PropagatorSettings< double > > > &propagatorSettings, std::map< double, Eigen::VectorXd > &fullPropagationResults, std::map< double, Eigen::Vector6d > &semiAnalyticalResults, std::map< double, Eigen::VectorXd > &dependentVariablesHistory)
Full propagation.
std::pair< std::shared_ptr< propagators::PropagatorSettings< double > >, std::shared_ptr< propagators::PropagatorSettings< double > > > createLowThrustPropagatorSettings (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::string &centralBody, const std::function< double(const double) > specificImpulseFunction, const basic_astrodynamics::AccelerationMap perturbingAccelerationsMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > &integratorSettings, const std::shared_ptr< propagators::DependentVariableSaveSettings > &dependentVariablesToSave)
Define appropriate propagator settings for the full propagation.
virtual std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > createLowThrustTranslationalStatePropagatorSettings (const std::string &bodyToPropagate, const std::string &centralBody, const basic_astrodynamics::AccelerationMap &accelerationModelMap, const std::shared_ptr< propagators::DependentVariableSaveSettings > dependentVariablesToSave)=0
Define appropriate propagator settings for the full propagation.
std::shared_ptr< propulsion::ThrustAcceleration > getLowThrustAccelerationModel (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const double timeOffset=0.0)
Retrieve acceleration model (thrust).
std::shared_ptr< simulation_setup::ThrustAccelerationSettings > getLowThrustAccelerationSettings (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const double timeOffset=0.0)
Retrieve acceleration model (thrust).
void getMassProfile (const std::vector< double > &epochsVector, std::map< double, Eigen::VectorXd > &massProfile, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Return mass profile.
Private Attributes
std::vector< double > championDesignVariables_
Design variables vector corresponding to the optimisation best individual.
std::vector< double > championFitness_
Fitness vector of the optimisation best individual.
std::shared_ptr< HybridMethodModel > hybridMethodModel_
Hybrid method leg corresponding to the best optimisation output.
std::pair< double, double > initialAndFinalMEEcostatesBounds_
Lower and upper bounds for the initial and final MEE costates.
std::pair< std::vector< double >, double > initialGuessThrustModel_
double initialSpacecraftMass_
Initial mass of the spacecraft.
double maximumThrust_
Maximum allowed thrust.
std::shared_ptr< simulation_setup::OptimisationSettings > optimisationSettings_
Optimisation settings.
double specificImpulse_
Specific impulse.
Additional Inherited Members
Protected Member Functions inherited from tudat::low_thrust_trajectories::LowThrustLeg
double computeCurrentMass (const double timeInitialEpoch, const double timeFinalEpoch, const double massInitialEpoch, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute current mass of the spacecraft between two epochs.
Protected Attributes inherited from tudat::low_thrust_trajectories::LowThrustLeg
double initialMass_
bool legModelIsForceBased_
Eigen::Vector6d stateAtArrival_
Cartesian state at arrival.
Eigen::Vector6d stateAtDeparture_
Cartesian state at departure.
double timeOfFlight_
Time of flight of the trajectory leg.
Detailed Description
Definition at line 28 of file hybridMethod.h.
Constructor & Destructor Documentation
HybridMethod()
tudat::low_thrust_trajectories::HybridMethod::HybridMethod (const Eigen::Vector6d & stateAtDeparture, const Eigen::Vector6d & stateAtArrival, const double maximumThrust, const double specificImpulse, const double timeOfFlight, std::shared_ptr< simulation_setup::OptimisationSettings > optimisationSettings, const std::pair< double, double > initialAndFinalMEEcostatesBounds = std::make_pair(- 10.0, 10.0)) inline
Definition at line 33 of file hybridMethod.h.
References championDesignVariables_, championFitness_, hybridMethodModel_, initialGuessThrustModel_, initialSpacecraftMass_, maximumThrust_, optimisationSettings_, performOptimisation(), specificImpulse_, tudat::low_thrust_trajectories::LowThrustLeg::stateAtArrival_, tudat::low_thrust_trajectories::LowThrustLeg::stateAtDeparture_, and tudat::low_thrust_trajectories::LowThrustLeg::timeOfFlight_.
~HybridMethod()
tudat::low_thrust_trajectories::HybridMethod::~HybridMethod () inline
Definition at line 94 of file hybridMethod.h.
Member Function Documentation
convertTimeToIndependentVariable()
double tudat::low_thrust_trajectories::HybridMethod::convertTimeToIndependentVariable (const double time) inline virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 97 of file hybridMethod.h.
convertIndependentVariableToTime()
double tudat::low_thrust_trajectories::HybridMethod::convertIndependentVariableToTime (const double independentVariable) inline virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 103 of file hybridMethod.h.
References tudat::propagators::independentVariable, and performOptimisation().
performOptimisation()
std::pair< std::vector< double >, std::vector< double > > tudat::low_thrust_trajectories::HybridMethod::performOptimisation ()
Definition at line 28 of file hybridMethod.cpp.
References championDesignVariables_, championFitness_, initialAndFinalMEEcostatesBounds_, initialGuessThrustModel_, maximumThrust_, optimisationSettings_, specificImpulse_, tudat::low_thrust_trajectories::LowThrustLeg::stateAtArrival_, tudat::low_thrust_trajectories::LowThrustLeg::stateAtDeparture_, and tudat::low_thrust_trajectories::LowThrustLeg::timeOfFlight_.
Referenced by convertIndependentVariableToTime(), and HybridMethod().
computeDeltaV()
double tudat::low_thrust_trajectories::HybridMethod::computeDeltaV () inline virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 112 of file hybridMethod.h.
References computeCurrentStateVector(), and hybridMethodModel_.
computeCurrentStateVector()
Eigen::Vector6d tudat::low_thrust_trajectories::HybridMethod::computeCurrentStateVector (const double currentTime) virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 246 of file hybridMethod.cpp.
References hybridMethodModel_, initialSpacecraftMass_, and tudat::low_thrust_trajectories::LowThrustLeg::stateAtDeparture_.
Referenced by computeCurrentThrustForce(), computeDeltaV(), and createLowThrustTranslationalStatePropagatorSettings().
getTrajectory()
void tudat::low_thrust_trajectories::HybridMethod::getTrajectory (std::vector< double > & epochsVector, std::map< double, Eigen::Vector6d > & propagatedTrajectory) inline virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 121 of file hybridMethod.h.
References computeCurrentThrustAccelerationDirection(), computeCurrentThrustAccelerationMagnitude(), computeCurrentThrustForce(), getThrustAccelerationProfile(), getThrustForceProfile(), and hybridMethodModel_.
Referenced by getThrustForceProfile().
computeCurrentThrustForce()
Eigen::Vector3d tudat::low_thrust_trajectories::HybridMethod::computeCurrentThrustForce (double time, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings) virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 77 of file hybridMethod.cpp.
References computeCurrentStateVector(), tudat::simulation_setup::getBodyFixedThrustDirection(), tudat::simulation_setup::Body::getBodyMass(), hybridMethodModel_, maximumThrust_, and tudat::propulsion::BodyFixedForceDirectionGuidance::updateCalculator().
Referenced by computeCurrentThrustAccelerationDirection(), computeCurrentThrustAccelerationMagnitude(), and getTrajectory().
getThrustForceProfile()
void tudat::low_thrust_trajectories::HybridMethod::getThrustForceProfile (std::vector< double > & epochsVector, std::map< double, Eigen::VectorXd > & thrustProfile, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings) virtual
Reimplemented from tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 123 of file hybridMethod.cpp.
References tudat::simulation_setup::getBodyFixedThrustDirection(), tudat::simulation_setup::Body::getBodyMass(), getTrajectory(), hybridMethodModel_, maximumThrust_, and tudat::propulsion::BodyFixedForceDirectionGuidance::updateCalculator().
Referenced by getThrustAccelerationProfile(), and getTrajectory().
computeCurrentThrustAccelerationDirection()
Eigen::Vector3d tudat::low_thrust_trajectories::HybridMethod::computeCurrentThrustAccelerationDirection (double currentTime, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings) virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 197 of file hybridMethod.cpp.
References computeCurrentThrustForce().
Referenced by getTrajectory().
computeCurrentThrustAccelerationMagnitude()
double tudat::low_thrust_trajectories::HybridMethod::computeCurrentThrustAccelerationMagnitude (double currentTime, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings) virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 183 of file hybridMethod.cpp.
References tudat::low_thrust_trajectories::LowThrustLeg::computeCurrentMass(), and computeCurrentThrustForce().
Referenced by getTrajectory().
getThrustAccelerationProfile()
void tudat::low_thrust_trajectories::HybridMethod::getThrustAccelerationProfile (std::vector< double > & epochsVector, std::map< double, Eigen::VectorXd > & thrustAccelerationProfile, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings) virtual
Reimplemented from tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 212 of file hybridMethod.cpp.
References tudat::low_thrust_trajectories::LowThrustLeg::getMassProfile(), and getThrustForceProfile().
Referenced by getTrajectory().
getBestIndividual()
std::vector< double > tudat::low_thrust_trajectories::HybridMethod::getBestIndividual () inline
Definition at line 158 of file hybridMethod.h.
References championDesignVariables_.
getBestIndividualFitness()
std::vector< double > tudat::low_thrust_trajectories::HybridMethod::getBestIndividualFitness () inline
Definition at line 164 of file hybridMethod.h.
References championFitness_.
getOptimalHybridMethodModel()
std::shared_ptr< HybridMethodModel > tudat::low_thrust_trajectories::HybridMethod::getOptimalHybridMethodModel () inline
Definition at line 170 of file hybridMethod.h.
References createLowThrustTranslationalStatePropagatorSettings(), hybridMethodModel_, and retrieveLowThrustAccelerationMap().
retrieveLowThrustAccelerationMap()
basic_astrodynamics::AccelerationMap tudat::low_thrust_trajectories::HybridMethod::retrieveLowThrustAccelerationMap (const simulation_setup::NamedBodyMap & bodyMapTest, const std::string & bodyToPropagate, const std::string & centralBody, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings) virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 264 of file hybridMethod.cpp.
References hybridMethodModel_.
Referenced by getOptimalHybridMethodModel().
createLowThrustTranslationalStatePropagatorSettings()
std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > tudat::low_thrust_trajectories::HybridMethod::createLowThrustTranslationalStatePropagatorSettings (basic_astrodynamics::AccelerationMap accelerationModelMap, std::shared_ptr< propagators::DependentVariableSaveSettings > dependentVariablesToSave)
Definition at line 278 of file hybridMethod.cpp.
References computeCurrentStateVector(), tudat::propagators::gauss_modified_equinoctial, and tudat::low_thrust_trajectories::LowThrustLeg::timeOfFlight_.
Referenced by getOptimalHybridMethodModel().
Member Data Documentation
maximumThrust_
double tudat::low_thrust_trajectories::HybridMethod::maximumThrust_ private
Definition at line 194 of file hybridMethod.h.
Referenced by computeCurrentThrustForce(), getThrustForceProfile(), HybridMethod(), and performOptimisation().
specificImpulse_
double tudat::low_thrust_trajectories::HybridMethod::specificImpulse_ private
Definition at line 197 of file hybridMethod.h.
Referenced by HybridMethod(), and performOptimisation().
optimisationSettings_
std::shared_ptr< simulation_setup::OptimisationSettings > tudat::low_thrust_trajectories::HybridMethod::optimisationSettings_ private
Definition at line 200 of file hybridMethod.h.
Referenced by HybridMethod(), and performOptimisation().
initialGuessThrustModel_
std::pair< std::vector< double >, double > tudat::low_thrust_trajectories::HybridMethod::initialGuessThrustModel_ private
Initial guess for the optimisation. The first element contains the thrust throttles corresponding to the initial guess for the thrust model. The second element defines the bounds around the initial time (in percentage).
Definition at line 205 of file hybridMethod.h.
Referenced by HybridMethod(), and performOptimisation().
championFitness_
std::vector< double > tudat::low_thrust_trajectories::HybridMethod::championFitness_ private
Definition at line 208 of file hybridMethod.h.
Referenced by getBestIndividualFitness(), HybridMethod(), and performOptimisation().
championDesignVariables_
std::vector< double > tudat::low_thrust_trajectories::HybridMethod::championDesignVariables_ private
Definition at line 211 of file hybridMethod.h.
Referenced by getBestIndividual(), HybridMethod(), and performOptimisation().
initialSpacecraftMass_
double tudat::low_thrust_trajectories::HybridMethod::initialSpacecraftMass_ private
Definition at line 214 of file hybridMethod.h.
Referenced by computeCurrentStateVector(), and HybridMethod().
hybridMethodModel_
std::shared_ptr< HybridMethodModel > tudat::low_thrust_trajectories::HybridMethod::hybridMethodModel_ private
Definition at line 217 of file hybridMethod.h.
Referenced by computeCurrentStateVector(), computeCurrentThrustForce(), computeDeltaV(), getOptimalHybridMethodModel(), getThrustForceProfile(), getTrajectory(), HybridMethod(), and retrieveLowThrustAccelerationMap().
initialAndFinalMEEcostatesBounds_
std::pair< double, double > tudat::low_thrust_trajectories::HybridMethod::initialAndFinalMEEcostatesBounds_ private
Definition at line 220 of file hybridMethod.h.
Referenced by performOptimisation().
The documentation for this class was generated from the following files:
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/hybridMethod.h
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/hybridMethod.cpp