Tudat: tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType > Class Template Reference
tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType > Class Template Reference
Container class for all parameters that are to be estimated.
#include <estimatableParameter.h>
Public Member Functions
EstimatableParameterSet (const std::vector< std::shared_ptr< EstimatableParameter< double > > > &estimatedDoubleParameters, const std::vector< std::shared_ptr< EstimatableParameter< Eigen::VectorXd > > > &estimatedVectorParameters, const std::vector< std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > &estimateInitialStateParameters=(std::vector< std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > >()))
Constructor of parameter set.
void getConstraints (Eigen::MatrixXd &constraintStateMultiplier, Eigen::VectorXd &constraintRightHandSide)
Function to retrieve total multiplier and right-hand side for parameter estimation linear constraint.
int getConstraintSize ()
Total size of linear constraint that is to be applied during estimation.
std::map< int, std::shared_ptr< EstimatableParameter< double > > > getDoubleParameters ()
Function to retrieve double parameter objects.
std::vector< std::shared_ptr< EstimatableParameter< double > > > getEstimatedDoubleParameters ()
std::vector< std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > getEstimatedInitialStateParameters ()
Function to get list of initial dynamical states that are to be estimated.
std::vector< std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > getEstimatedMultiArcInitialStateParameters ()
Function to get list of multi-arc initial dynamical states that are to be estimated.
int getEstimatedParameterSetSize ()
Function to return the total number of parameter values (excluding consider parameters).
std::vector< std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > getEstimatedSingleArcInitialStateParameters ()
Function to get list of single-arc initial dynamical states that are to be estimated.
std::vector< std::shared_ptr< EstimatableParameter< Eigen::VectorXd > > > getEstimatedVectorParameters ()
template<typename ParameterScalar >
Eigen::Matrix< ParameterScalar, Eigen::Dynamic, 1 > getFullParameterValues ()
Function that returns a vector containing all current parameter values.
std::vector< std::pair< int, int > > getIndicesForParameterType (const EstimatebleParameterIdentifier requiredParameterId)
Function to retrieve the start index and size of (a) parameters(s) with a given identifier.
int getInitialDynamicalMultiArcStateParameterSize ()
Function to return the total number of multi-arc initial state values that are estimated.
int getInitialDynamicalSingleArcStateParameterSize ()
Function to return the total number of single-arc initial state values that are estimated.
int getInitialDynamicalStateParameterSize ()
Function to return the total number of initial state values that are estimated.
std::map< int, std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > getInitialMultiArcStateParameters ()
Function to retrieve all multi-arc initial state parameter objects.
std::map< int, std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > getInitialSingleArcStateParameters ()
Function to retrieve all single-arc initial state parameter objects.
std::map< int, std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > getInitialStateParameters ()
int getParameterSetSize ()
Function to return the total number of parameter values (including consider parameters)
std::vector< std::pair< int, int > > getParametersIndices ()
Function to retrieve list of start indices and sizes (map keys) of estimated parameters.
std::map< int, std::shared_ptr< EstimatableParameter< Eigen::VectorXd > > > getVectorParameters ()
Function to retrieve vector parameter objects.
template<typename ParameterScalar >
void resetParameterValues (const Eigen::Matrix< ParameterScalar, Eigen::Dynamic, 1 > &newParameterValues)
Function to reset all parameter values.
Protected Attributes
std::map< int, std::shared_ptr< EstimatableParameter< double > > > doubleParameters_
Map of double parameters that are to be estimated, with start index in total parameter vector as key.
std::vector< std::shared_ptr< EstimatableParameter< double > > > estimatedDoubleParameters_
List of double parameters that are to be estimated.
int estimatedParameterSetSize_
Total number of estimated parameter values (excluding currently non yet implemented consider parameters).
std::vector< std::shared_ptr< EstimatableParameter< Eigen::VectorXd > > > estimatedVectorParameters_
List of vector parameters that are to be estimated.
std::vector< std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > estimateInitialStateParameters_
List of initial dynamical states that are to be estimated.
std::vector< std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > estimateMultiArcInitialStateParameters_
List of initial multi-arc dynamical states that are to be estimated.
std::vector< std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > estimateSingleArcInitialStateParameters_
List of initial single-arc dynamical states that are to be estimated.
int initialDynamicalMultiArcStateParameterSize_
Total size of all initial multi-arc dynamical states that are to be estimated.
int initialDynamicalSingleArcStateParameterSize_
Total size of all initial single-arc dynamical states that are to be estimated.
int initialDynamicalStateParameterSize_
Total size of all initial dynamical states that are to be estimated.
std::map< int, std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > initialMultiArcStateParameters_
Map containing all multi-arc initial state parameter objects, with map key start index of parameter in total vector.
std::map< int, std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > initialSingleArcStateParameters_
Map containing all single-arc initial state parameter objects, with map key start index of parameter in total vector.
std::map< int, std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > initialStateParameters_
Map of initial dynamical states that are to be estimated, with start index in total parameter vector as key.
std::vector< std::pair< int, int > > parameterIndices_
List of start indices and sizes (map keys) of estimated parameters.
int totalConstraintSize_
Size of linear constraint that is to be applied during estimation.
int totalParameterSetSize_
Total number of parameter values (including currently non yet implemented consider parameters).
std::map< int, std::shared_ptr< EstimatableParameter< Eigen::VectorXd > > > vectorParameters_
Map of vector parameters that are to be estimated, with start index in total parameter vector as key.
Detailed Description
template<typename InitialStateParameterType = double>
class tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >
Container class for all parameters that are to be estimated. Class is templated with the scalar type used for the estimation of any initial dynamical states that may be included
Definition at line 282 of file estimatableParameter.h.
Constructor & Destructor Documentation
EstimatableParameterSet()
template<typename InitialStateParameterType = double> tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::EstimatableParameterSet (const std::vector< std::shared_ptr< EstimatableParameter< double > > > & estimatedDoubleParameters, const std::vector< std::shared_ptr< EstimatableParameter< Eigen::VectorXd > > > & estimatedVectorParameters, const std::vector< std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > & estimateInitialStateParameters = (std::vector< std::shared_ptr< EstimatableParameter< Eigen::Matrix < InitialStateParameterType, Eigen::Dynamic, 1 > > > >())) inline
Constructor of parameter set.
Parameters
estimatedDoubleParameters List of double parameters that are estimated.
estimatedVectorParameters List of vector parameters that are estimated.
estimateInitialStateParameters List of initial dynamical states that are to be estimated.
Definition at line 293 of file estimatableParameter.h.
References tudat::estimatable_parameters::EstimatableParameter< ParameterType >::getParameterSize(), and tudat::estimatable_parameters::isDynamicalParameterSingleArc().
Member Function Documentation
getParameterSetSize()
template<typename InitialStateParameterType = double> int tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::getParameterSetSize () inline
Function to return the total number of parameter values (including consider parameters)
Returns
Size of parameter vector (including consider parameters)
Definition at line 385 of file estimatableParameter.h.
getEstimatedParameterSetSize()
template<typename InitialStateParameterType = double> int tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::getEstimatedParameterSetSize () inline
Function to return the total number of parameter values (excluding consider parameters)
Returns
Size of parameter vector (excluding consider parameters)
Definition at line 395 of file estimatableParameter.h.
getInitialDynamicalStateParameterSize()
template<typename InitialStateParameterType = double> int tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::getInitialDynamicalStateParameterSize () inline
Function to return the total number of initial state values that are estimated.
Returns
Function to return the total number of initial state values that are estimated.
Definition at line 405 of file estimatableParameter.h.
getInitialDynamicalSingleArcStateParameterSize()
template<typename InitialStateParameterType = double> int tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::getInitialDynamicalSingleArcStateParameterSize () inline
Function to return the total number of single-arc initial state values that are estimated.
Returns
Function to return the total number of initial state values that are estimated.
Definition at line 415 of file estimatableParameter.h.
getInitialDynamicalMultiArcStateParameterSize()
template<typename InitialStateParameterType = double> int tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::getInitialDynamicalMultiArcStateParameterSize () inline
Function to return the total number of multi-arc initial state values that are estimated.
Returns
Function to return the total number of initial state values that are estimated.
Definition at line 425 of file estimatableParameter.h.
getFullParameterValues()
template<typename InitialStateParameterType = double> template<typename ParameterScalar > Eigen::Matrix< ParameterScalar, Eigen::Dynamic, 1 > tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::getFullParameterValues () inline
Function that returns a vector containing all current parameter values. The total vector starts with the initial state parameters, followed by the double and vector parameters, respectively. Initial state, double and vector parameter values are concatenated in the order in which they are set in the estimateInitialStateParameters_, doubleParameters_ and vectorParameters_ members.
Returns
Vector containing all parameter values
Definition at line 439 of file estimatableParameter.h.
References tudat::estimatable_parameters::EstimatableParameter< ParameterType >::getParameterSize().
resetParameterValues()
template<typename InitialStateParameterType = double> template<typename ParameterScalar > void tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::resetParameterValues (const Eigen::Matrix< ParameterScalar, Eigen::Dynamic, 1 > & newParameterValues) inline
Function to reset all parameter values.
Parameters
newParameterValues New parameter values. Order of values in vector must be same order as return vector of getFullParameterValues
Definition at line 479 of file estimatableParameter.h.
getDoubleParameters()
template<typename InitialStateParameterType = double> std::map< int, std::shared_ptr< EstimatableParameter< double > > > tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::getDoubleParameters () inline
Function to retrieve double parameter objects.
Returns
Map containing all double parameter objects, with map key start index of parameter in total vector.
Definition at line 525 of file estimatableParameter.h.
getVectorParameters()
template<typename InitialStateParameterType = double> std::map< int, std::shared_ptr< EstimatableParameter< Eigen::VectorXd > > > tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::getVectorParameters () inline
Function to retrieve vector parameter objects.
Returns
Map containing all vector parameter objects, with map key start index of parameter in total vector.
Definition at line 535 of file estimatableParameter.h.
getInitialStateParameters()
template<typename InitialStateParameterType = double> std::map< int, std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::getInitialStateParameters () inline
Definition at line 540 of file estimatableParameter.h.
getInitialSingleArcStateParameters()
template<typename InitialStateParameterType = double> std::map< int, std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::getInitialSingleArcStateParameters () inline
Function to retrieve all single-arc initial state parameter objects.
Returns
Map containing all single-arc initial state parameter objects, with map key start index of parameter in total vector.
Definition at line 552 of file estimatableParameter.h.
getInitialMultiArcStateParameters()
template<typename InitialStateParameterType = double> std::map< int, std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::getInitialMultiArcStateParameters () inline
Function to retrieve all multi-arc initial state parameter objects.
Returns
Map containing all multi-arc initial state parameter objects, with map key start index of parameter in total vector.
Definition at line 563 of file estimatableParameter.h.
getEstimatedDoubleParameters()
template<typename InitialStateParameterType = double> std::vector< std::shared_ptr< EstimatableParameter< double > > > tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::getEstimatedDoubleParameters () inline
Definition at line 568 of file estimatableParameter.h.
getEstimatedVectorParameters()
template<typename InitialStateParameterType = double> std::vector< std::shared_ptr< EstimatableParameter< Eigen::VectorXd > > > tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::getEstimatedVectorParameters () inline
Definition at line 573 of file estimatableParameter.h.
getIndicesForParameterType()
template<typename InitialStateParameterType = double> std::vector< std::pair< int, int > > tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::getIndicesForParameterType (const EstimatebleParameterIdentifier requiredParameterId) inline
Function to retrieve the start index and size of (a) parameters(s) with a given identifier
Parameters
requiredParameterId Parameter identifier that is to be searched in full list of patameters
Returns
List of start indices and sizes of parameters corresponding to requiredParameterId
Definition at line 584 of file estimatableParameter.h.
getEstimatedInitialStateParameters()
template<typename InitialStateParameterType = double> std::vector< std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::getEstimatedInitialStateParameters () inline
Function to get list of initial dynamical states that are to be estimated.
Returns
List of initial dynamical states that are to be estimated.
Definition at line 631 of file estimatableParameter.h.
getEstimatedSingleArcInitialStateParameters()
template<typename InitialStateParameterType = double> std::vector< std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::getEstimatedSingleArcInitialStateParameters () inline
Function to get list of single-arc initial dynamical states that are to be estimated.
Returns
List of initial dynamical states that are to be estimated.
Definition at line 643 of file estimatableParameter.h.
getEstimatedMultiArcInitialStateParameters()
template<typename InitialStateParameterType = double> std::vector< std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::getEstimatedMultiArcInitialStateParameters () inline
Function to get list of multi-arc initial dynamical states that are to be estimated.
Returns
List of initial dynamical states that are to be estimated.
Definition at line 655 of file estimatableParameter.h.
getParametersIndices()
template<typename InitialStateParameterType = double> std::vector< std::pair< int, int > > tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::getParametersIndices () inline
Function to retrieve list of start indices and sizes (map keys) of estimated parameters.
Returns
List of start indices and sizes (map keys) of estimated parameters.
Definition at line 665 of file estimatableParameter.h.
getConstraints()
template<typename InitialStateParameterType = double> void tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::getConstraints (Eigen::MatrixXd & constraintStateMultiplier, Eigen::VectorXd & constraintRightHandSide) inline
Function to retrieve total multiplier and right-hand side for parameter estimation linear constraint
Parameters
constraintStateMultiplier Multiplier for parameter linear constraint
constraintRightHandSide Right-hand side for parameter linear constraint
Definition at line 676 of file estimatableParameter.h.
getConstraintSize()
template<typename InitialStateParameterType = double> int tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::getConstraintSize () inline
Total size of linear constraint that is to be applied during estimation
Returns
Size of linear constraint that is to be applied during estimation
Definition at line 748 of file estimatableParameter.h.
Member Data Documentation
initialDynamicalStateParameterSize_
template<typename InitialStateParameterType = double> int tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::initialDynamicalStateParameterSize_ protected
Definition at line 756 of file estimatableParameter.h.
initialDynamicalSingleArcStateParameterSize_
template<typename InitialStateParameterType = double> int tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::initialDynamicalSingleArcStateParameterSize_ protected
Definition at line 759 of file estimatableParameter.h.
initialDynamicalMultiArcStateParameterSize_
template<typename InitialStateParameterType = double> int tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::initialDynamicalMultiArcStateParameterSize_ protected
Definition at line 762 of file estimatableParameter.h.
totalParameterSetSize_
template<typename InitialStateParameterType = double> int tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::totalParameterSetSize_ protected
Definition at line 765 of file estimatableParameter.h.
estimatedParameterSetSize_
template<typename InitialStateParameterType = double> int tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::estimatedParameterSetSize_ protected
Definition at line 768 of file estimatableParameter.h.
parameterIndices_
template<typename InitialStateParameterType = double> std::vector< std::pair< int, int > > tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::parameterIndices_ protected
List of start indices and sizes (map keys) of estimated parameters, in order of vector estimateInitialStateParameters_, followed by estimatedDoubleParameters_, followed by estimatedVectorParameters_.
Definition at line 775 of file estimatableParameter.h.
estimatedDoubleParameters_
template<typename InitialStateParameterType = double> std::vector< std::shared_ptr< EstimatableParameter< double > > > tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::estimatedDoubleParameters_ protected
Definition at line 778 of file estimatableParameter.h.
estimatedVectorParameters_
template<typename InitialStateParameterType = double> std::vector< std::shared_ptr< EstimatableParameter< Eigen::VectorXd > > > tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::estimatedVectorParameters_ protected
Definition at line 781 of file estimatableParameter.h.
estimateInitialStateParameters_
template<typename InitialStateParameterType = double> std::vector< std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::estimateInitialStateParameters_ protected
Definition at line 785 of file estimatableParameter.h.
estimateSingleArcInitialStateParameters_
template<typename InitialStateParameterType = double> std::vector< std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::estimateSingleArcInitialStateParameters_ protected
Definition at line 789 of file estimatableParameter.h.
estimateMultiArcInitialStateParameters_
template<typename InitialStateParameterType = double> std::vector< std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::estimateMultiArcInitialStateParameters_ protected
Definition at line 793 of file estimatableParameter.h.
doubleParameters_
template<typename InitialStateParameterType = double> std::map< int, std::shared_ptr< EstimatableParameter< double > > > tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::doubleParameters_ protected
Definition at line 796 of file estimatableParameter.h.
vectorParameters_
template<typename InitialStateParameterType = double> std::map< int, std::shared_ptr< EstimatableParameter< Eigen::VectorXd > > > tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::vectorParameters_ protected
Definition at line 799 of file estimatableParameter.h.
initialStateParameters_
template<typename InitialStateParameterType = double> std::map< int, std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::initialStateParameters_ protected
Definition at line 803 of file estimatableParameter.h.
totalConstraintSize_
template<typename InitialStateParameterType = double> int tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::totalConstraintSize_ protected
Definition at line 806 of file estimatableParameter.h.
initialSingleArcStateParameters_
template<typename InitialStateParameterType = double> std::map< int, std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::initialSingleArcStateParameters_ protected
Definition at line 810 of file estimatableParameter.h.
initialMultiArcStateParameters_
template<typename InitialStateParameterType = double> std::map< int, std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::initialMultiArcStateParameters_ protected
Definition at line 814 of file estimatableParameter.h.
The documentation for this class was generated from the following file:
Astrodynamics/OrbitDetermination/EstimatableParameters/estimatableParameter.h