Tudat: tudat::estimatable_parameters Namespace Reference
tudat::estimatable_parameters Namespace Reference
Classes
class ArcWiseConstantDragCoefficient
Interface class for the estimation of an arc-wise (piecewise constant) drag coefficient.
class ArcWiseConstantObservationBiasEstimatableParameterSettings
Class to define settings for estimation of arc-wise constant observation biases (absolute or relative)
class ArcWiseDragCoefficientEstimatableParameterSettings
Class to define settings for estimating time-dependent (arcwise constant) drag coefficients.
class ArcWiseEmpiricalAccelerationCoefficientsParameter
Interface class for estimation of a body's time-dependent (arcwise constant) empirical accelerations.
class ArcWiseEmpiricalAccelerationEstimatableParameterSettings
Class to define settings for estimating time-dependent (arcwise constant) empirical acceleration components.
class ArcWiseInitialTranslationalStateEstimatableParameterSettings
Class to define settings for estimating an arcwise initial translational state.
class ArcWiseInitialTranslationalStateParameter
Interface class for the estimation of an arcwise initial translational state.
class ArcWiseObservationBiasParameter
Interface class for the estimation of an arc-wise constant absolute or relative observation bias.
class ArcWiseRadiationPressureCoefficient
Interface class for the estimation of an arc-wise (piecewise constant) radiation pressure coefficient.
class ArcWiseRadiationPressureCoefficientEstimatableParameterSettings
Class to define settings for estimating time-dependent (arcwise constant) empirical acceleration components.
class ConstantDragCoefficient
Interface class for the estimation of a constant body drag coefficient.
class ConstantObservationBiasEstimatableParameterSettings
Class to define settings for estimation of constant observation biases (absolute or relative)
class ConstantObservationBiasParameter
Interface class for the estimation of a constant absolute or relative observation bias.
class ConstantRotationalOrientation
Interface class for estimation of a body's constant pole position (right ascension and declination of north pole).
class CoreFactor
Interface class for estimation of a body's core factor (for a full planetary rotational model).
class DesaturationDeltaV
Interface class for estimation of a body's momentum wheel desaturation deltaVs.
class DirectTidalTimeLag
Interface class for estimation the tidal time lag in a direct tidal acceleration model.
class DirectTidalTimeLagEstimatableParameterSettings
Class to define settings for estimating the tidal time lag of a direct tidal acceleration model.
class EmpiricalAccelerationCoefficientsParameter
Interface class for estimation of a body's time-independent empirical accelerations.
class EmpiricalAccelerationEstimatableParameterSettings
Class to define settings for estimating time-independent empirical acceleration components.
class EquivalencePrincipleLpiViolationParameter
Class used to estimate equivalence principle LPI violation parameter, e.g. putative effect on observers proper time rate.
class EstimatableParameter
Base class for a parameter that is to be estimated.
class EstimatableParameterSet
Container class for all parameters that are to be estimated.
class EstimatableParameterSettings
Class for providing settings for parameters to estimate.
class FreeCoreNutationRate
Interface class for estimation of a body's free core nutation rate (for a full planetary rotational model).
class FullDegreeTidalLoveNumber
Class for estimating the tidal Love number k_{n} at a single degree that is constant for all orders.
class FullDegreeTidalLoveNumberEstimatableParameterSettings
Class to define settings for estimating a Tidal Love number (k_{n}) at a single degree that is constant for all orders.
class GravitationalParameter
Interface class for the estimation of a gravitational parameter.
class GroundStationPosition
Class for estimating constant position of a ground station.
class InitialRotationalStateEstimatableParameterSettings
Class to define settings for estimating an initial rotational state.
class InitialRotationalStateParameter
Interface class for the estimation of an initial rotational state.
class InitialTranslationalStateEstimatableParameterSettings
Class to define settings for estimating an initial translational state.
class InitialTranslationalStateParameter
Interface class for the estimation of an initial translational state.
class MeanMomentOfInertiaParameter
Interface class for the estimation of a mean moment of inertia parameter.
class PeriodicSpinVariation
Interface class for estimation of a body's periodic spin variation (for a full planetary rotational model).
class PolarMotionAmplitude
Interface class for estimation of a body's polar motion amplitude (for a full planetary rotational model).
class PPNParameterBeta
Class used to estimate PPN parameter beta.
class PPNParameterGamma
Class used to estimate PPN parameter gamma.
class RadiationPressureCoefficient
Interface class for the estimation of a radiation pressure coefficient.
class RotationRate
Interface class for estimation of a body's constant rotation rate parameter.
class SingleDegreeVariableTidalLoveNumber
Class for estimating the tidal Love numbers k_{n,m} at a single degree that may vary for different orders.
class SingleDegreeVariableTidalLoveNumberEstimatableParameterSettings
Class to define settings for estimating a set of Tidal Love number (k_{n,m}) at a single degree.
class SphericalHarmonicEstimatableParameterSettings
Class for providing settings spherical harmonic coefficient(s) parameter.
class SphericalHarmonicsCosineCoefficients
Interface class for estimation of spherical harmonic gravity field cosine coefficients.
class SphericalHarmonicsSineCoefficients
Interface class for estimation of spherical harmonic gravity field sine coefficients.
class TidalLoveNumber
Pure virtual base class for estimating tidal Love number properties.
Typedefs
typedef std::pair< EstimatebleParametersEnum, std::pair< std::string, std::string > > EstimatebleParameterIdentifier
Typedef for full parameter identifier.
Enumerations
enum EstimatebleParametersEnum {
arc_wise_initial_body_state, initial_body_state, initial_rotational_body_state, gravitational_parameter,
constant_drag_coefficient, radiation_pressure_coefficient, arc_wise_radiation_pressure_coefficient, spherical_harmonics_cosine_coefficient_block,
spherical_harmonics_sine_coefficient_block, constant_rotation_rate, rotation_pole_position, constant_additive_observation_bias,
arcwise_constant_additive_observation_bias, constant_relative_observation_bias, arcwise_constant_relative_observation_bias, ppn_parameter_gamma,
ppn_parameter_beta, ground_station_position, equivalence_principle_lpi_violation_parameter, empirical_acceleration_coefficients,
arc_wise_empirical_acceleration_coefficients, full_degree_tidal_love_number, single_degree_variable_tidal_love_number, direct_dissipation_tidal_time_lag,
mean_moment_of_inertia, arc_wise_constant_drag_coefficient, periodic_spin_variation, polar_motion_amplitude,
core_factor, free_core_nutation_rate, desaturation_delta_v_values
}
List of parameters that can be estimated by the orbit determination code.
Functions
template<typename StateScalarType >
std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > createEstimatableParameterSetArcSubSet (std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate, const bool getSingleArcParameters)
Function to create a subset of all estimated parameters, with either only single-arc or multi-arc initial state parameter.
void from_json (const nlohmann::json &jsonObject, EstimatebleParametersEnum &parameterType)
Convert json to PropagationDependentVariables.
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< EstimatableParameterSettings > &parameterSettings)
Create a shared pointer to a SingleDependentVariableSaveSettings object from a json object.
template<typename InitialStateParameterType = double>
Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > getInitialStateVectorOfBodiesToEstimate (const std::shared_ptr< EstimatableParameterSet< InitialStateParameterType > > estimatableParameters)
Function to get initial state vector of estimated dynamical states.
Eigen::VectorXd getKaulaConstraintVector (const std::vector< std::pair< int, int > > blockIndices, const double constraintMultiplier)
Function to get a list of Kaula constraint values for gravity field coefficients at given degrees and indices.
Eigen::VectorXd getKaulaConstraintVector (const std::shared_ptr< SphericalHarmonicsSineCoefficients > parameter, const double constraintMultiplier)
Function to get a list of Kaula constraint values for gravity field coefficients for given parameter.
Eigen::VectorXd getKaulaConstraintVector (const std::shared_ptr< SphericalHarmonicsCosineCoefficients > parameter, const double constraintMultiplier)
Function to get a list of Kaula constraint values for gravity field coefficients for given parameter.
template<typename InitialStateParameterType >
std::map< propagators::IntegratedStateType, std::vector< std::string > > getListOfBodiesToEstimate (const std::shared_ptr< EstimatableParameterSet< InitialStateParameterType > > estimatableParameters)
Function to retrieve the list of bodies for which an initial dynamical state is to be estimated.
template<typename InitialStateParameterType >
std::vector< std::string > getListOfBodiesWithRotationalStateToEstimate (const std::shared_ptr< EstimatableParameterSet< InitialStateParameterType > > estimatableParameters)
Function to get the list of names of bodies for which initial rotational dynamical state is estimated.
template<typename InitialStateParameterType >
std::map< std::string, std::shared_ptr< EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > getListOfBodiesWithTranslationalMultiArcStateToEstimate (const std::shared_ptr< EstimatableParameterSet< InitialStateParameterType > > estimatableParameters)
Function to retrieve the list of bodies for which the translational state is estimated in a multi-arc fashion.
template<typename InitialStateParameterType >
std::vector< std::string > getListOfBodiesWithTranslationalStateToEstimate (const std::shared_ptr< EstimatableParameterSet< InitialStateParameterType > > estimatableParameters)
Function to get the list of names of bodies for which initial translational dynamical state is estimated.
template<typename InitialStateParameterType >
std::map< propagators::IntegratedStateType, std::vector< std::pair< std::string, std::string > > > getListOfInitialDynamicalStateParametersEstimate (const std::shared_ptr< EstimatableParameterSet< InitialStateParameterType > > estimatableParameters)
Function to get the complete list of initial dynamical states that are to be estimated, sorted by dynamics type.
template<typename InitialStateParameterType >
std::vector< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > getListOfRotationalStateParametersToEstimate (const std::shared_ptr< EstimatableParameterSet< InitialStateParameterType > > estimatableParameters)
Function to retrieve the list of rotational state parameters from full parameter list.
template<typename InitialStateParameterType >
std::vector< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > getListOfTranslationalStateParametersToEstimate (const std::shared_ptr< EstimatableParameterSet< InitialStateParameterType > > estimatableParameters)
Function to retrieve the list of translational state parameters from full parameter list.
template<typename InitialStateParameterType >
std::vector< double > getMultiArcStateEstimationArcStartTimes (const std::shared_ptr< EstimatableParameterSet< InitialStateParameterType > > estimatableParameters, const bool throwErrorOnSingleArcDynamics=true)
Function to get arc start times from list of estimated parameters.
std::string getParameterTypeString (const EstimatebleParametersEnum parameterType)
template<typename InitialStateParameterType = double>
int getSingleArcInitialDynamicalStateParameterSetSize (std::shared_ptr< EstimatableParameterSet< InitialStateParameterType > > estimatableParameterSet)
Function to retrieve the size of the dynamical state.
template<typename InitialStateParameterType = double>
int getSingleArcParameterSetSize (std::shared_ptr< EstimatableParameterSet< InitialStateParameterType > > estimatableParameterSet)
Function to retrieve the size of the estimatable parameter set.
std::vector< std::pair< int, int > > getSphericalHarmonicBlockIndices (const int minimumDegree, const int minimumOrder, const int maximumDegree, const int maximumOrder)
Function to retrieve full list of degree/order of spherical harmonic coeficients for given range of degrees and orders.
bool isDoubleParameter (const EstimatebleParametersEnum parameterType)
Function to determine whether the given (non-dynamical) parameter is a double or vector parameter.
template<typename ParameterType >
bool isDynamicalParameterSingleArc (const std::shared_ptr< EstimatableParameter< Eigen::Matrix< ParameterType, Eigen::Dynamic, 1 > > > parameterToCheck)
Function to determine if an initial state parameter is a single- or multi-arc parameter.
bool isParameterDynamicalPropertyInitialState (const EstimatebleParametersEnum parameterType)
Function to determine whether the given parameter represents an initial dynamical state, or a static parameter.
bool isParameterObservationLinkProperty (const EstimatebleParametersEnum parameterType)
Function to determine whether the given parameter influences an observation link directly.
bool isParameterRotationMatrixProperty (const EstimatebleParametersEnum parameterType)
Function to determine whether the given (non-dynamical) parameter influences a body's orientation.
bool isParameterTidalProperty (const EstimatebleParametersEnum parameterType)
Function to determine whether the given parameter influences a body's tidal gravity field variations.
template<typename InitialStateParameterType >
void printEstimatableParameterEntries (const std::shared_ptr< EstimatableParameterSet< InitialStateParameterType > > estimatableParameters)
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< EstimatableParameterSettings > &parameterSettings)
Create a json object from a shared pointer to a SingleDependentVariableSaveSettings object.
void to_json (nlohmann::json &jsonObject, const EstimatebleParametersEnum &parameterType)
Convert PropagationDependentVariables to json.
Variables
static std::map< EstimatebleParametersEnum, std::string > estimatedParameterTypes
Map of PropagationDependentVariables string representations.
static const std::vector< std::vector< int > > fullDegreeOrders
List of all orders in a single degree (starting at 2)
Typedef Documentation
EstimatebleParameterIdentifier
typedef std::pair< EstimatebleParametersEnum, std::pair< std::string, std::string > > tudat::estimatable_parameters::EstimatebleParameterIdentifier
Definition at line 113 of file estimatableParameter.h.
Enumeration Type Documentation
EstimatebleParametersEnum
enum tudat::estimatable_parameters::EstimatebleParametersEnum
Enumerator
arc_wise_initial_body_state
initial_body_state
initial_rotational_body_state
gravitational_parameter
constant_drag_coefficient
radiation_pressure_coefficient
arc_wise_radiation_pressure_coefficient
spherical_harmonics_cosine_coefficient_block
spherical_harmonics_sine_coefficient_block
constant_rotation_rate
rotation_pole_position
constant_additive_observation_bias
arcwise_constant_additive_observation_bias
constant_relative_observation_bias
arcwise_constant_relative_observation_bias
ppn_parameter_gamma
ppn_parameter_beta
ground_station_position
equivalence_principle_lpi_violation_parameter
empirical_acceleration_coefficients
arc_wise_empirical_acceleration_coefficients
full_degree_tidal_love_number
single_degree_variable_tidal_love_number
direct_dissipation_tidal_time_lag
mean_moment_of_inertia
arc_wise_constant_drag_coefficient
periodic_spin_variation
polar_motion_amplitude
core_factor
free_core_nutation_rate
desaturation_delta_v_values
Definition at line 34 of file estimatableParameter.h.
Function Documentation
getParameterTypeString()
std::string tudat::estimatable_parameters::getParameterTypeString (const EstimatebleParametersEnum parameterType)
Definition at line 19 of file estimatableParameter.cpp.
References arc_wise_constant_drag_coefficient, arc_wise_empirical_acceleration_coefficients, arc_wise_initial_body_state, arc_wise_radiation_pressure_coefficient, arcwise_constant_additive_observation_bias, arcwise_constant_relative_observation_bias, constant_additive_observation_bias, constant_drag_coefficient, constant_relative_observation_bias, constant_rotation_rate, core_factor, desaturation_delta_v_values, direct_dissipation_tidal_time_lag, empirical_acceleration_coefficients, equivalence_principle_lpi_violation_parameter, free_core_nutation_rate, full_degree_tidal_love_number, gravitational_parameter, ground_station_position, initial_body_state, initial_rotational_body_state, mean_moment_of_inertia, periodic_spin_variation, polar_motion_amplitude, ppn_parameter_beta, ppn_parameter_gamma, radiation_pressure_coefficient, rotation_pole_position, single_degree_variable_tidal_love_number, spherical_harmonics_cosine_coefficient_block, and spherical_harmonics_sine_coefficient_block.
Referenced by tudat::estimatable_parameters::SphericalHarmonicsCosineCoefficients::getParameterDescription(), tudat::estimatable_parameters::SphericalHarmonicsSineCoefficients::getParameterDescription(), tudat::estimatable_parameters::ConstantObservationBiasParameter::getParameterDescription(), tudat::estimatable_parameters::EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > >::getParameterDescription(), and tudat::estimatable_parameters::ArcWiseObservationBiasParameter::getParameterDescription().
isParameterDynamicalPropertyInitialState()
bool tudat::estimatable_parameters::isParameterDynamicalPropertyInitialState (const EstimatebleParametersEnum parameterType)
Function to determine whether the given parameter represents an initial dynamical state, or a static parameter.
Parameters
parameterType Parameter identifier.
Returns
True if parameter is an initial dynamical state.
Definition at line 126 of file estimatableParameter.cpp.
References arc_wise_initial_body_state, initial_body_state, and initial_rotational_body_state.
Referenced by tudat::simulation_setup::createInitialDynamicalStateParameterToEstimate(), tudat::simulation_setup::createParametersToEstimate(), getInitialStateVectorOfBodiesToEstimate(), and tudat::simulation_setup::setInitialStateVectorFromParameterSet().
isDoubleParameter()
bool tudat::estimatable_parameters::isDoubleParameter (const EstimatebleParametersEnum parameterType)
Function to determine whether the given (non-dynamical) parameter is a double or vector parameter.
Parameters
parameterType Parameter identifier.
Returns
True if parameter is a double parameter.
Definition at line 148 of file estimatableParameter.cpp.
References arc_wise_constant_drag_coefficient, arc_wise_empirical_acceleration_coefficients, arc_wise_radiation_pressure_coefficient, arcwise_constant_additive_observation_bias, arcwise_constant_relative_observation_bias, constant_additive_observation_bias, constant_drag_coefficient, constant_relative_observation_bias, constant_rotation_rate, core_factor, desaturation_delta_v_values, direct_dissipation_tidal_time_lag, empirical_acceleration_coefficients, equivalence_principle_lpi_violation_parameter, free_core_nutation_rate, full_degree_tidal_love_number, gravitational_parameter, ground_station_position, mean_moment_of_inertia, periodic_spin_variation, polar_motion_amplitude, ppn_parameter_beta, ppn_parameter_gamma, radiation_pressure_coefficient, rotation_pole_position, single_degree_variable_tidal_love_number, spherical_harmonics_cosine_coefficient_block, and spherical_harmonics_sine_coefficient_block.
Referenced by tudat::simulation_setup::createDoubleParameterToEstimate(), tudat::simulation_setup::createParametersToEstimate(), and tudat::simulation_setup::createVectorParameterToEstimate().
isParameterRotationMatrixProperty()
bool tudat::estimatable_parameters::isParameterRotationMatrixProperty (const EstimatebleParametersEnum parameterType)
Function to determine whether the given (non-dynamical) parameter influences a body's orientation.
Parameters
parameterType Parameter identifier.
Returns
True if parameter is a property of rotation model
Definition at line 245 of file estimatableParameter.cpp.
References constant_rotation_rate, core_factor, free_core_nutation_rate, initial_rotational_body_state, periodic_spin_variation, polar_motion_amplitude, and rotation_pole_position.
Referenced by tudat::observation_partials::createCartesianStatePartialsWrtParameter(), tudat::observation_partials::createEulerAngleObservablePartials(), tudat::observation_partials::createRotationMatrixPartials(), tudat::acceleration_partials::SphericalHarmonicGravitationalTorquePartial::getParameterPartialFunction(), and tudat::acceleration_partials::SphericalHarmonicsGravityPartial::getParameterPartialFunction().
isParameterObservationLinkProperty()
bool tudat::estimatable_parameters::isParameterObservationLinkProperty (const EstimatebleParametersEnum parameterType)
Function to determine whether the given parameter influences an observation link directly, such as observation biases or clock parameters
Parameters
parameterType Parameter identifier.
Returns
True if parameter is a property of an observation link
Definition at line 279 of file estimatableParameter.cpp.
References arcwise_constant_additive_observation_bias, arcwise_constant_relative_observation_bias, constant_additive_observation_bias, and constant_relative_observation_bias.
Referenced by tudat::observation_partials::createAngularPositionPartials(), tudat::observation_partials::createNWayRangePartials(), tudat::observation_partials::createOneWayDopplerPartials(), tudat::observation_partials::createOneWayRangePartials(), tudat::observation_partials::createTwoWayDopplerPartials(), and tudat::observation_models::performObservationParameterEstimationClosure().
isParameterTidalProperty()
bool tudat::estimatable_parameters::isParameterTidalProperty (const EstimatebleParametersEnum parameterType)
Function to determine whether the given parameter influences a body's tidal gravity field variations.
Parameters
parameterType Parameter identifier.
Returns
True if parameter influences a body's tidal gravity field variations.
Definition at line 304 of file estimatableParameter.cpp.
References full_degree_tidal_love_number, and single_degree_variable_tidal_love_number.
Referenced by tudat::acceleration_partials::SphericalHarmonicsGravityPartial::getParameterPartialFunction().
isDynamicalParameterSingleArc()
template<typename ParameterType > bool tudat::estimatable_parameters::isDynamicalParameterSingleArc (const std::shared_ptr< EstimatableParameter< Eigen::Matrix< ParameterType, Eigen::Dynamic, 1 > > > parameterToCheck)
Function to determine if an initial state parameter is a single- or multi-arc parameter. Function throws an error, if input is not an initial state parameter
Parameters
parameterToCheck Parameter object for which the check is to be performed.
Returns
True of parameter is single-arc, false if multi-arc
Definition at line 241 of file estimatableParameter.h.
References arc_wise_initial_body_state, initial_body_state, and initial_rotational_body_state.
Referenced by tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::EstimatableParameterSet().
createEstimatableParameterSetArcSubSet()
template<typename StateScalarType > std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > tudat::estimatable_parameters::createEstimatableParameterSetArcSubSet (std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate, const bool getSingleArcParameters)
Function to create a subset of all estimated parameters, with either only single-arc or multi-arc initial state parameter. All non-dynamical state parameters are copied from the input to the output
Parameters
parametersToEstimate Total set of parameters
getSingleArcParameters Boolean denoting whether single- or multi-arc initial state parameters are to be kept
Returns
Subset of all estimated parameters, with either only single-arc or multi-arc initial state parameter
Definition at line 827 of file estimatableParameter.h.
Referenced by tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::setExtendedMultiArcParameters().
printEstimatableParameterEntries()
template<typename InitialStateParameterType > void tudat::estimatable_parameters::printEstimatableParameterEntries (const std::shared_ptr< EstimatableParameterSet< InitialStateParameterType > > estimatableParameters)
Definition at line 848 of file estimatableParameter.h.
References tudat::estimatable_parameters::EstimatableParameter< ParameterType >::getParameterDescription().
Referenced by tudat::unit_tests::executeEarthOrbiterBiasEstimation(), and tudat::unit_tests::executeEarthOrbiterParameterEstimation().
getListOfBodiesWithTranslationalStateToEstimate()
template<typename InitialStateParameterType > std::vector< std::string > tudat::estimatable_parameters::getListOfBodiesWithTranslationalStateToEstimate (const std::shared_ptr< EstimatableParameterSet< InitialStateParameterType > > estimatableParameters)
Function to get the list of names of bodies for which initial translational dynamical state is estimated.
Parameters
estimatableParameters Object containing all parameters that are to be estimated.
Returns
List of names of bodies for which initial state is estimated.
Definition at line 890 of file estimatableParameter.h.
References initial_body_state.
Referenced by tudat::propagators::checkPropagatorSettingsAndParameterEstimationConsistency().
getListOfBodiesWithRotationalStateToEstimate()
template<typename InitialStateParameterType > std::vector< std::string > tudat::estimatable_parameters::getListOfBodiesWithRotationalStateToEstimate (const std::shared_ptr< EstimatableParameterSet< InitialStateParameterType > > estimatableParameters)
Function to get the list of names of bodies for which initial rotational dynamical state is estimated.
Parameters
estimatableParameters Object containing all parameters that are to be estimated.
Returns
List of names of bodies for which initial rotational state is estimated.
Definition at line 919 of file estimatableParameter.h.
References initial_rotational_body_state.
Referenced by tudat::propagators::checkPropagatorSettingsAndParameterEstimationConsistency().
getListOfBodiesWithTranslationalMultiArcStateToEstimate()
template<typename InitialStateParameterType > std::map< std::string, std::shared_ptr< EstimatableParameter<Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > tudat::estimatable_parameters::getListOfBodiesWithTranslationalMultiArcStateToEstimate (const std::shared_ptr< EstimatableParameterSet< InitialStateParameterType > > estimatableParameters)
Function to retrieve the list of bodies for which the translational state is estimated in a multi-arc fashion
Parameters
estimatableParameters Full set of estimated parameters
Returns
List of parameters (with body names as keys) used for the multi-arc estimation of initial translational state
Definition at line 949 of file estimatableParameter.h.
References arc_wise_initial_body_state.
Referenced by tudat::propagators::checkMultiArcPropagatorSettingsAndParameterEstimationConsistency(), and tudat::propagators::setPropagatorSettingsMultiArcStatesInEstimatedDynamicalParameters().
getListOfBodiesToEstimate()
template<typename InitialStateParameterType > std::map< propagators::IntegratedStateType, std::vector< std::string > > tudat::estimatable_parameters::getListOfBodiesToEstimate (const std::shared_ptr< EstimatableParameterSet< InitialStateParameterType > > estimatableParameters)
Function to retrieve the list of bodies for which an initial dynamical state is to be estimated
Parameters
estimatableParameters Full set of estimated parameters
Returns
List of bodies for which an initial dynamical state is estimated.
Definition at line 980 of file estimatableParameter.h.
References arc_wise_initial_body_state, initial_body_state, initial_rotational_body_state, tudat::propagators::rotational_state, and tudat::propagators::translational_state.
getListOfTranslationalStateParametersToEstimate()
template<typename InitialStateParameterType > std::vector< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > tudat::estimatable_parameters::getListOfTranslationalStateParametersToEstimate (const std::shared_ptr< EstimatableParameterSet< InitialStateParameterType > > estimatableParameters)
Function to retrieve the list of translational state parameters from full parameter list
Parameters
estimatableParameters Full set of estimated parameters
Returns
List of translational state parameters
Definition at line 1014 of file estimatableParameter.h.
References arc_wise_initial_body_state, and initial_body_state.
Referenced by tudat::simulation_setup::createAccelerationPartialsMap().
getListOfRotationalStateParametersToEstimate()
template<typename InitialStateParameterType > std::vector< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > > tudat::estimatable_parameters::getListOfRotationalStateParametersToEstimate (const std::shared_ptr< EstimatableParameterSet< InitialStateParameterType > > estimatableParameters)
Function to retrieve the list of rotational state parameters from full parameter list
Parameters
estimatableParameters Full set of estimated parameters
Returns
List of rotational state parameters
Definition at line 1044 of file estimatableParameter.h.
References initial_rotational_body_state.
Referenced by tudat::simulation_setup::createTorquePartialsMap().
getListOfInitialDynamicalStateParametersEstimate()
template<typename InitialStateParameterType > std::map< propagators::IntegratedStateType, std::vector< std::pair< std::string, std::string > > > tudat::estimatable_parameters::getListOfInitialDynamicalStateParametersEstimate (const std::shared_ptr< EstimatableParameterSet< InitialStateParameterType > > estimatableParameters)
Function to get the complete list of initial dynamical states that are to be estimated, sorted by dynamics type.
Parameters
estimatableParameters Object containing all parameters that are to be estimated.
Returns
Map containing dynamics type (key) and vector of pairs: list of bodies (first in pair) with reference point identifier (second in pair; empty if not relevant) for which given dynamics type is estimated.
Definition at line 1074 of file estimatableParameter.h.
References arc_wise_initial_body_state, initial_body_state, initial_rotational_body_state, tudat::propagators::rotational_state, and tudat::propagators::translational_state.
getInitialStateVectorOfBodiesToEstimate()
template<typename InitialStateParameterType = double> Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > tudat::estimatable_parameters::getInitialStateVectorOfBodiesToEstimate (const std::shared_ptr< EstimatableParameterSet< InitialStateParameterType > > estimatableParameters)
Function to get initial state vector of estimated dynamical states (i.e. presently estimated state at propagation start time.
Parameters
estimatableParameters Object containing all parameters that are to be estimated.
Returns
State vector of estimated dynamics at propagation start time.
Definition at line 1110 of file estimatableParameter.h.
References tudat::estimatable_parameters::EstimatableParameter< ParameterType >::getParameterSize(), and isParameterDynamicalPropertyInitialState().
Referenced by tudat::unit_tests::executePlanetaryParameterEstimation(), and tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::resetParameterEstimate().
getSingleArcParameterSetSize()
template<typename InitialStateParameterType = double> int tudat::estimatable_parameters::getSingleArcParameterSetSize (std::shared_ptr< EstimatableParameterSet< InitialStateParameterType > > estimatableParameterSet)
Function to retrieve the size of the estimatable parameter set.
Parameters
estimatableParameterSet Set of estimatable parameters.
Returns
Size of parameter set.
Definition at line 276 of file initialTranslationalState.h.
References arc_wise_initial_body_state, initial_body_state, and initial_rotational_body_state.
Referenced by getSingleArcInitialDynamicalStateParameterSetSize(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::MultiArcVariationalEquationsSolver(), and tudat::propagators::VariationalEquations::VariationalEquations().
getSingleArcInitialDynamicalStateParameterSetSize()
template<typename InitialStateParameterType = double> int tudat::estimatable_parameters::getSingleArcInitialDynamicalStateParameterSetSize (std::shared_ptr< EstimatableParameterSet< InitialStateParameterType > > estimatableParameterSet)
Function to retrieve the size of the dynamical state.
Parameters
estimatableParameterSet Set of estimatable parameters.
Returns
Size of the initial dynamical state.
Definition at line 309 of file initialTranslationalState.h.
References getSingleArcParameterSetSize().
Referenced by tudat::propagators::VariationalEquations::setParameterPartialFunctionList().
getMultiArcStateEstimationArcStartTimes()
template<typename InitialStateParameterType > std::vector< double > tudat::estimatable_parameters::getMultiArcStateEstimationArcStartTimes (const std::shared_ptr< EstimatableParameterSet< InitialStateParameterType > > estimatableParameters, const bool throwErrorOnSingleArcDynamics = true)
Function to get arc start times from list of estimated parameters. Function throws an error if multiple arc-wise estimations are found, but arc times are not compatible
Parameters
estimatableParameters List of estimated parameters
throwErrorOnSingleArcDynamics Boolean denoting whether to throw an exception if single arc dynamics are used (default true)
Returns
Start times for estimation arcs
Definition at line 326 of file initialTranslationalState.h.
References arc_wise_initial_body_state.
Referenced by tudat::simulation_setup::createHybridArcVariationalEquationsSolver(), and tudat::simulation_setup::createMultiArcVariationalEquationsSolver().
getKaulaConstraintVector() [1/3]
Eigen::VectorXd tudat::estimatable_parameters::getKaulaConstraintVector (const std::vector< std::pair< int, int > > blockIndices, const double constraintMultiplier)
Function to get a list of Kaula constraint values for gravity field coefficients at given degrees and indices
Parameters
blockIndices List of indices (degree and order) of coefficients for which Kaula constraint is to be given
constraintMultiplier Multiplier A for Kaula constraint, obtained from A/l^{2}, which l the current coefficient's degree
Returns
Vector of Kaula constraint values on gravity field coefficients
Definition at line 47 of file sphericalHarmonicCosineCoefficients.cpp.
Referenced by getKaulaConstraintVector().
getKaulaConstraintVector() [2/3]
Eigen::VectorXd tudat::estimatable_parameters::getKaulaConstraintVector (const std::shared_ptr< SphericalHarmonicsCosineCoefficients > parameter, const double constraintMultiplier)
Function to get a list of Kaula constraint values for gravity field coefficients for given parameter
Parameters
parameter Parameter that defines the list of cosine spherical harmonic coefficients
constraintMultiplier Multiplier A for Kaula constraint, obtained from A/l^{2}, which l the current coefficient's degree
Returns
Vector of Kaula constraint values on gravity field coefficients
Definition at line 61 of file sphericalHarmonicCosineCoefficients.cpp.
References getKaulaConstraintVector().
getKaulaConstraintVector() [3/3]
Eigen::VectorXd tudat::estimatable_parameters::getKaulaConstraintVector (const std::shared_ptr< SphericalHarmonicsSineCoefficients > parameter, const double constraintMultiplier)
Function to get a list of Kaula constraint values for gravity field coefficients for given parameter
Parameters
parameter Parameter that defines the list of sine spherical harmonic coefficients
constraintMultiplier Multiplier A for Kaula constraint, obtained from A/l^{2}, which l the current coefficient's degree
Returns
Vector of Kaula constraint values on gravity field coefficients
Definition at line 48 of file sphericalHarmonicSineCoefficients.cpp.
References getKaulaConstraintVector().
to_json() [1/2]
void tudat::estimatable_parameters::to_json (nlohmann::json & jsonObject, const std::shared_ptr< EstimatableParameterSettings > & parameterSettings)
Create a json object from a shared pointer to a EstimatableParameterSettings object.
Definition at line 25 of file parameter.cpp.
References arc_wise_empirical_acceleration_coefficients, arc_wise_initial_body_state, arc_wise_radiation_pressure_coefficient, arcwise_constant_additive_observation_bias, arcwise_constant_relative_observation_bias, tudat::json_interface::assertNonnullptrPointer(), tudat::json_interface::assignIfNotEmpty(), constant_additive_observation_bias, constant_relative_observation_bias, direct_dissipation_tidal_time_lag, empirical_acceleration_coefficients, full_degree_tidal_love_number, initial_body_state, single_degree_variable_tidal_love_number, spherical_harmonics_cosine_coefficient_block, and spherical_harmonics_sine_coefficient_block.
Referenced by from_json().
from_json() [1/2]
void tudat::estimatable_parameters::from_json (const nlohmann::json & jsonObject, std::shared_ptr< EstimatableParameterSettings > & parameterSettings)
Create a shared pointer to a EstimatableParameterSettings object from a json object.
Definition at line 249 of file parameter.cpp.
References arc_wise_empirical_acceleration_coefficients, arc_wise_initial_body_state, arc_wise_radiation_pressure_coefficient, arcwise_constant_additive_observation_bias, arcwise_constant_relative_observation_bias, constant_additive_observation_bias, constant_relative_observation_bias, direct_dissipation_tidal_time_lag, empirical_acceleration_coefficients, full_degree_tidal_love_number, tudat::json_interface::getValue(), initial_body_state, single_degree_variable_tidal_love_number, spherical_harmonics_cosine_coefficient_block, spherical_harmonics_sine_coefficient_block, and TUDAT_NAN.
Referenced by from_json().
to_json() [2/2]
void tudat::estimatable_parameters::to_json (nlohmann::json & jsonObject, const EstimatebleParametersEnum & parameterType) inline
Definition at line 57 of file parameter.h.
References tudat::json_interface::stringFromEnum().
from_json() [2/2]
void tudat::estimatable_parameters::from_json (const nlohmann::json & jsonObject, EstimatebleParametersEnum & parameterType) inline
Definition at line 63 of file parameter.h.
References tudat::json_interface::enumFromString(), from_json(), and to_json().
getSphericalHarmonicBlockIndices()
std::vector< std::pair< int, int > > tudat::estimatable_parameters::getSphericalHarmonicBlockIndices (const int minimumDegree, const int minimumOrder, const int maximumDegree, const int maximumOrder) inline
Function to retrieve full list of degree/order of spherical harmonic coeficients for given range of degrees and orders
Parameters
minimumDegree Minimum degree of field
minimumOrder Minimum order of field
maximumDegree Maximum degree of field
maximumOrder Maximum order of field
Returns
List of paird containing (degree,order) of field.
Definition at line 72 of file estimatableParameterSettings.h.
Referenced by tudat::estimatable_parameters::SphericalHarmonicEstimatableParameterSettings::SphericalHarmonicEstimatableParameterSettings().
Variable Documentation
fullDegreeOrders
const std::vector< std::vector< int > > tudat::estimatable_parameters::fullDegreeOrders static
Initial value:
=
{ { 0, 1, 2 }, { 0, 1, 2, 3 }, { 0, 1, 2, 3, 4 }, { 0, 1, 2, 3, 4, 5 }, { 0, 1, 2, 3, 4, 5, 6 } }
List of all orders in a single degree (starting at 2), generated at compile time and used for tidal love number partial interface function calls over a full degree.
Definition at line 30 of file tidalLoveNumber.h.
Referenced by tudat::orbit_determination::TidalLoveNumberPartialInterface::calculateSphericalHarmonicCoefficientsPartialWrtComplexTidalLoveNumber(), and tudat::orbit_determination::TidalLoveNumberPartialInterface::calculateSphericalHarmonicCoefficientsPartialWrtRealTidalLoveNumber().
estimatedParameterTypes
std::map< EstimatebleParametersEnum, std::string > tudat::estimatable_parameters::estimatedParameterTypes static
Initial value:
=
{
    { arc_wise_initial_body_state, "arcWiseInitialBodyState" },
    { initial_body_state, "initialBodyState" },
    { gravitational_parameter, "gravitationalParameter" },
    { constant_drag_coefficient, "constantDragCoefficient" },
    { radiation_pressure_coefficient, "radiationPressureCoefficient" },
    { arc_wise_radiation_pressure_coefficient, "arcWiseRadiationPressureCoefficient" },
    { spherical_harmonics_cosine_coefficient_block, "sphericalHarmonicsCosineCoefficientBlock" },
    { spherical_harmonics_sine_coefficient_block, "sphericalHarmonicsSineCoefficientBlock" },
    { constant_rotation_rate, "constantRotationRate" },
    { rotation_pole_position, "rotationPolePosition" },
    { constant_additive_observation_bias, "constantAdditiveObservationBias" },
    { arcwise_constant_additive_observation_bias, "arcwiseConstantAdditiveObservationBias" },
    { constant_relative_observation_bias, "constantRelativeObservationBias" },
    { arcwise_constant_relative_observation_bias, "arcwiseConstantRelativeObservationBias" },
    { ppn_parameter_gamma, "ppnParameterGamma" },
    { ppn_parameter_beta, "ppnParameterBeta" },
    { ground_station_position, "groundStationPosition" },
    { equivalence_principle_lpi_violation_parameter, "equivalencePrincipleLpiViolationParameter" },
    { empirical_acceleration_coefficients, "empiricalAccelerationCoefficients" },
    { arc_wise_empirical_acceleration_coefficients, "arcWiseEmpiricalAccelerationCoefficients" },
    { full_degree_tidal_love_number, "fullDegreeTidalLoveNumber" },
    { single_degree_variable_tidal_love_number, "singleDegreeVariableTidalLoveNumber" },
    { direct_dissipation_tidal_time_lag, "directDissipationTidalTimeLag" }
}
Definition at line 28 of file parameter.h.