Tudat: tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType > Class Template Reference
tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType > Class Template Reference
#include <jsonInterfaceVariational.h>
Public Member Functions
JsonVariationalEquationsSimulationManager (const std::string &inputFilePath, const std::chrono::steady_clock::time_point initialClockTime=std::chrono::steady_clock::now())
JsonVariationalEquationsSimulationManager (const nlohmann::json &jsonObject, const std::chrono::steady_clock::time_point initialClockTime=std::chrono::steady_clock::now())
Constructor from JSON object.
virtual ~JsonVariationalEquationsSimulationManager ()
virtual void createSimulationObjects ()
virtual void exportResults ()
Export the results of the dynamics simulation according to the export settings.
std::shared_ptr< propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType > > getVariationalEquationsSolver () const
void resetParameterSettings ()
void resetVariationalEquationsSolver ()
virtual void runJsonSimulation ()
virtual void updateSettings ()
Public Member Functions inherited from tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >
JsonSimulationManager (const std::string &inputFilePath, const std::chrono::steady_clock::time_point initialClockTime=std::chrono::steady_clock::now())
Constructor from JSON file.
JsonSimulationManager (const nlohmann::json &jsonObject, const std::chrono::steady_clock::time_point initialClockTime=std::chrono::steady_clock::now())
Constructor from JSON object.
virtual ~JsonSimulationManager ()
void addBody (const std::string &bodyName)
Add a body named bodyName.
nlohmann::json at (const std::string &key) const
void exportAsJson (const boost::filesystem::path &exportPath, const unsigned int tabSize=2)
Export this as a json object to the file exportPath.
std::shared_ptr< ApplicationOptions > getApplicationOptions () const
Get application options.
nlohmann::json getAsJson ()
Export this as a json object.
std::shared_ptr< simulation_setup::Body > getBody (const std::string &bodyName) const
Get body named bodyName.
simulation_setup::NamedBodyMap getBodyMap () const
Get body map.
std::map< std::string, std::shared_ptr< simulation_setup::BodySettings > > getBodySettingsMap () const
Get map of body settings.
std::shared_ptr< propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType > > getDynamicsSimulator () const
Get dynamics simulator.
TimeType getEndEpoch () const
Get maximum simulation end epoch. Returns TUDAT_NAN if there is no time termination condition.
std::shared_ptr< ExportSettings > getExportSettings (const unsigned int index) const
Get export settings at index.
std::vector< std::shared_ptr< ExportSettings > > getExportSettingsVector () const
Get vector of export settings (each element corresponds to an output file).
std::string getGlobalFrameOrientation () const
Get global frame orientation.
std::string getGlobalFrameOrigin () const
Get global frame origin.
std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > getIntegratorSettings () const
Get integrator settings.
nlohmann::json getJsonObject () const
Get the JSON object.
nlohmann::json getOriginalJsonObject () const
Get original JSON object (defined at construction or last time setInputFile was called).
std::shared_ptr< propagators::MultiTypePropagatorSettings< StateScalarType > > getPropagatorSettings () const
Get propagator settings.
std::shared_ptr< SpiceSettings > getSpiceSettings () const
Get Spice settings (nullptr if Spice is not used).
TimeType getStartEpoch () const
Get simulation start epoch.
nlohmann::json & operator[] (const std::string &key)
void resetInputFile (const std::string &inputFilePath)
Reset the root JSON input file.
void resetJsonObject (const nlohmann::json &jsonObject)
Reset the json object.
virtual void runPropagation ()
Run the propagation.
Protected Attributes
std::vector< std::shared_ptr< estimatable_parameters::EstimatableParameterSettings > > parameterSettings_
std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate_
std::shared_ptr< propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType > > variationalEquationsSolver_
Protected Attributes inherited from tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >
std::shared_ptr< ApplicationOptions > applicationOptions_
Application options.
simulation_setup::NamedBodyMap bodyMap_
Body map.
std::map< std::string, std::shared_ptr< simulation_setup::BodySettings > > bodySettingsMap_
Map of body settings.
std::shared_ptr< propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType > > dynamicsSimulator_
Dynamics simulator.
std::vector< std::shared_ptr< ExportSettings > > exportSettingsVector_
Vector of export settings (each element corresponds to an output file).
std::string globalFrameOrientation_
Global frame orientation.
std::string globalFrameOrigin_
Global frame origin.
std::chrono::steady_clock::time_point initialClockTime_
Absolute path to the input file.
boost::filesystem::path inputFilePath_
Absolute path to the input file.
std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings_
Integrator settings.
nlohmann::json jsonObject_
JSON object with the current settings.
nlohmann::json originalJsonObject_
Original JSON object with all the settings read directly from the input file.
bool profiling = false
std::shared_ptr< propagators::MultiTypePropagatorSettings< StateScalarType > > propagatorSettings_
Propagation settings.
JsonSimulationTypes simulationType_
std::shared_ptr< SpiceSettings > spiceSettings_
Spice settings (nullptr if Spice is not used).
Additional Inherited Members
Protected Member Functions inherited from tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >
virtual void resetApplicationOptions ()
Reset applicationOptions_ from the current jsonObject_.
virtual void resetBodies ()
Reset bodySettingsMap_ and bodyMap_ from the current jsonObject_.
virtual void resetDynamicsSimulator ()
Reset dynamicsSimulator_ for the current bodyMap_, integratorSettings_ and propagatorSettings_.
virtual void resetExportSettings ()
Reset exportSettingsVector_ from the current jsonObject_.
virtual void resetIntegratorSettings ()
Reset integratorSettings_ from the current jsonObject_.
virtual void resetPropagatorSettings ()
Reset propagatorSettings_ from the current jsonObject_.
virtual void resetSpice ()
Reset spiceSettings_ from the current jsonObject_.
void updateJsonObjectFromSettings ()
Update the JSON object with all the data from the current settings (objests).
Detailed Description
template<typename TimeType = double, typename StateScalarType = double>
class tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >
Definition at line 26 of file jsonInterfaceVariational.h.
Constructor & Destructor Documentation
JsonVariationalEquationsSimulationManager() [1/2]
template<typename TimeType = double, typename StateScalarType = double> tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::JsonVariationalEquationsSimulationManager (const std::string & inputFilePath, const std::chrono::steady_clock::time_point initialClockTime = std::chrono::steady_clock::now()) inline
Definition at line 40 of file jsonInterfaceVariational.h.
JsonVariationalEquationsSimulationManager() [2/2]
template<typename TimeType = double, typename StateScalarType = double> tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::JsonVariationalEquationsSimulationManager (const nlohmann::json & jsonObject, const std::chrono::steady_clock::time_point initialClockTime = std::chrono::steady_clock::now()) inline
Constructor.
Parameters
jsonObject The root JSON object.
initialClockTime Initial clock time from which the cumulative CPU time during the propagation will be computed. Default is the moment at which the constructor was called.
Definition at line 52 of file jsonInterfaceVariational.h.
~JsonVariationalEquationsSimulationManager()
template<typename TimeType = double, typename StateScalarType = double> virtual tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::~JsonVariationalEquationsSimulationManager () inline virtual
Definition at line 57 of file jsonInterfaceVariational.h.
Member Function Documentation
getVariationalEquationsSolver()
template<typename TimeType = double, typename StateScalarType = double> std::shared_ptr< propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType > > tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::getVariationalEquationsSolver () const inline
Definition at line 59 of file jsonInterfaceVariational.h.
References tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::variationalEquationsSolver_.
resetVariationalEquationsSolver()
template<typename TimeType = double, typename StateScalarType = double> void tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::resetVariationalEquationsSolver () inline
Definition at line 64 of file jsonInterfaceVariational.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::bodyMap_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::dynamicsSimulator_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::initialClockTime_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::integratorSettings_, tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::parametersToEstimate_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::profiling, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::propagatorSettings_, and tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::variationalEquationsSolver_.
Referenced by tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::createSimulationObjects().
resetParameterSettings()
template<typename TimeType = double, typename StateScalarType = double> void tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::resetParameterSettings () inline
Definition at line 81 of file jsonInterfaceVariational.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::bodyMap_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::initialClockTime_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::jsonObject_, tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::parameterSettings_, tudat::json_interface::Keys::parametersToEstimate, tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::parametersToEstimate_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::profiling, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::propagatorSettings_, and tudat::json_interface::updateFromJSON().
Referenced by tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::updateSettings().
runJsonSimulation()
template<typename TimeType = double, typename StateScalarType = double> virtual void tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::runJsonSimulation () inline virtual
Reimplemented from tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >.
Reimplemented in tudat::json_interface::JsonEstimationManager< TimeType, StateScalarType >.
Definition at line 96 of file jsonInterfaceVariational.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::propagatorSettings_, and tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::variationalEquationsSolver_.
createSimulationObjects()
template<typename TimeType = double, typename StateScalarType = double> virtual void tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::createSimulationObjects () inline virtual
Reimplemented from tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >.
Reimplemented in tudat::json_interface::JsonEstimationManager< TimeType, StateScalarType >.
Definition at line 102 of file jsonInterfaceVariational.h.
References tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::resetVariationalEquationsSolver().
Referenced by tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::updateSettings().
updateSettings()
template<typename TimeType = double, typename StateScalarType = double> virtual void tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::updateSettings () inline virtual
Reimplemented from tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >.
Reimplemented in tudat::json_interface::JsonEstimationManager< TimeType, StateScalarType >.
Definition at line 108 of file jsonInterfaceVariational.h.
References tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::createSimulationObjects(), tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::resetParameterSettings(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::simulationType_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::updateSettings(), and tudat::json_interface::variational_equations_propagation.
Referenced by tudat::json_interface::JsonEstimationManager< TimeType, StateScalarType >::updateSettings().
exportResults()
template<typename TimeType = double, typename StateScalarType = double> virtual void tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::exportResults () inline virtual
Export the results of the dynamics simulation according to the export settings.
Reimplemented from tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >.
Definition at line 119 of file jsonInterfaceVariational.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::exportResults(), tudat::json_interface::exportResultsOfVariationalEquations(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::exportSettingsVector_, and tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::variationalEquationsSolver_.
Member Data Documentation
variationalEquationsSolver_
template<typename TimeType = double, typename StateScalarType = double> std::shared_ptr< propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType > > tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::variationalEquationsSolver_ protected
Definition at line 127 of file jsonInterfaceVariational.h.
Referenced by tudat::json_interface::JsonEstimationManager< TimeType, StateScalarType >::createSimulationObjects(), tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::exportResults(), tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::getVariationalEquationsSolver(), tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::resetVariationalEquationsSolver(), and tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::runJsonSimulation().
parameterSettings_
template<typename TimeType = double, typename StateScalarType = double> std::vector< std::shared_ptr< estimatable_parameters::EstimatableParameterSettings > > tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::parameterSettings_ protected
Definition at line 129 of file jsonInterfaceVariational.h.
Referenced by tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::resetParameterSettings().
parametersToEstimate_
template<typename TimeType = double, typename StateScalarType = double> std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::parametersToEstimate_ protected
Definition at line 131 of file jsonInterfaceVariational.h.
Referenced by tudat::json_interface::JsonEstimationManager< TimeType, StateScalarType >::createSimulationObjects(), tudat::json_interface::JsonEstimationManager< TimeType, StateScalarType >::resetEstimationSettings(), tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::resetParameterSettings(), and tudat::json_interface::JsonVariationalEquationsSimulationManager< TimeType, StateScalarType >::resetVariationalEquationsSolver().
The documentation for this class was generated from the following file:
JsonInterface/jsonInterfaceVariational.h