Tudat: tudat::shape_based_methods::ScaledExponentialSineFunctionHodographicShaping Class Reference
tudat::shape_based_methods::ScaledExponentialSineFunctionHodographicShaping Class Reference
Scaled exponential times sine function.
#include <baseFunctionsHodographicShaping.h>
Public Member Functions
ScaledExponentialSineFunctionHodographicShaping (double exponentExponentialFunction, double frequencySineFunction, double scaleFactor)
Constructor taking exponent of the exponential function, frequency of the sine function, and scaling factor as inputs.
~ScaledExponentialSineFunctionHodographicShaping ()
Default destructor.
double evaluateDerivative (const double independentVariable)
double evaluateFunction (const double independentVariable)
Function, derivative, and integral of scaled exponential times sine function.
double evaluateIntegral (const double independentVariable)
Public Member Functions inherited from tudat::shape_based_methods::BaseFunctionHodographicShaping
BaseFunctionHodographicShaping ()
Default constructor.
virtual ~BaseFunctionHodographicShaping ()
Default destructor.
Private Attributes
double exponentExponentialFunction_
double frequencySineFunction_
double scaleFactor_
Detailed Description
Definition at line 251 of file baseFunctionsHodographicShaping.h.
Constructor & Destructor Documentation
ScaledExponentialSineFunctionHodographicShaping()
tudat::shape_based_methods::ScaledExponentialSineFunctionHodographicShaping::ScaledExponentialSineFunctionHodographicShaping (double exponentExponentialFunction, double frequencySineFunction, double scaleFactor) inline
Definition at line 256 of file baseFunctionsHodographicShaping.h.
~ScaledExponentialSineFunctionHodographicShaping()
tudat::shape_based_methods::ScaledExponentialSineFunctionHodographicShaping::~ScaledExponentialSineFunctionHodographicShaping () inline
Definition at line 264 of file baseFunctionsHodographicShaping.h.
References tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateDerivative(), tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateFunction(), tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateIntegral(), and tudat::propagators::independentVariable.
Member Function Documentation
evaluateFunction()
double tudat::shape_based_methods::ScaledExponentialSineFunctionHodographicShaping::evaluateFunction (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 121 of file baseFunctionsHodographicShaping.cpp.
evaluateDerivative()
double tudat::shape_based_methods::ScaledExponentialSineFunctionHodographicShaping::evaluateDerivative (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 127 of file baseFunctionsHodographicShaping.cpp.
evaluateIntegral()
double tudat::shape_based_methods::ScaledExponentialSineFunctionHodographicShaping::evaluateIntegral (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 134 of file baseFunctionsHodographicShaping.cpp.
Member Data Documentation
exponentExponentialFunction_
double tudat::shape_based_methods::ScaledExponentialSineFunctionHodographicShaping::exponentExponentialFunction_ private
Definition at line 276 of file baseFunctionsHodographicShaping.h.
frequencySineFunction_
double tudat::shape_based_methods::ScaledExponentialSineFunctionHodographicShaping::frequencySineFunction_ private
Definition at line 277 of file baseFunctionsHodographicShaping.h.
scaleFactor_
double tudat::shape_based_methods::ScaledExponentialSineFunctionHodographicShaping::scaleFactor_ private
Definition at line 278 of file baseFunctionsHodographicShaping.h.
The documentation for this class was generated from the following files:
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/baseFunctionsHodographicShaping.h
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/baseFunctionsHodographicShaping.cpp