Tudat: tudat::low_thrust_trajectories::TrajectoryOptimisationProblem Struct Reference
tudat::low_thrust_trajectories::TrajectoryOptimisationProblem Struct Reference
Definition optimisation problem to minimise the total deltaV required by the trajectory.
#include <lowThrustOptimisationSetup.h>
Public Types
typedef Eigen::Matrix< double, 6, 1 > StateType
Public Member Functions
TrajectoryOptimisationProblem ()
Default constructor, required for Pagmo compatibility.
TrajectoryOptimisationProblem (std::function< Eigen::Vector6d(const double) > departureStateFunction, std::function< Eigen::Vector6d(const double) > arrivalStateFunction, std::pair< double, double > departureTimeBounds, std::pair< double, double > timeOfFlightBounds, const std::shared_ptr< low_thrust_trajectories::LowThrustLegSettings > &lowThrustLegSettings)
Constructor.
std::vector< double > fitness (const std::vector< double > &x) const
Calculate the fitness as a function of the parameter vector x.
std::pair< std::vector< double >, std::vector< double > > get_bounds () const
Retrieve the allowable limits of the parameter vector x: pair containing minima and maxima of parameter values.
std::string get_name () const
Retrieve the name of the problem.
vector_double::size_type get_nec () const
vector_double::size_type get_nic () const
vector_double::size_type get_nobj () const
Retrieve the number of objectives in problem, e.g. the size of the vector returned by the fitness function.
Private Attributes
std::function< Eigen::Vector6d(const double) > arrivalStateFunction_
Function returning the state at arrival as a function of the arrival time.
std::function< Eigen::Vector6d(const double) > departureStateFunction_
Function returning the state at departure as a function of the departure time.
std::pair< double, double > departureTimeBounds_
Bounds for departure time.
double initialSpacecraftMass_
Initial spacecraft mass.
std::shared_ptr< low_thrust_trajectories::LowThrustLegSettings > lowThrustLegSettings_
Pointer to settings for low-thrust trajectory leg.
std::pair< double, double > timeOfFlightBounds_
Bounds for time of flight.
Detailed Description
Definition at line 49 of file lowThrustOptimisationSetup.h.
Member Typedef Documentation
StateType
typedef Eigen::Matrix< double, 6, 1 > tudat::low_thrust_trajectories::TrajectoryOptimisationProblem::StateType
Definition at line 52 of file lowThrustOptimisationSetup.h.
Constructor & Destructor Documentation
TrajectoryOptimisationProblem() [1/2]
tudat::low_thrust_trajectories::TrajectoryOptimisationProblem::TrajectoryOptimisationProblem () inline
Definition at line 55 of file lowThrustOptimisationSetup.h.
TrajectoryOptimisationProblem() [2/2]
tudat::low_thrust_trajectories::TrajectoryOptimisationProblem::TrajectoryOptimisationProblem (std::function< Eigen::Vector6d(const double) > departureStateFunction, std::function< Eigen::Vector6d(const double) > arrivalStateFunction, std::pair< double, double > departureTimeBounds, std::pair< double, double > timeOfFlightBounds, const std::shared_ptr< low_thrust_trajectories::LowThrustLegSettings > & lowThrustLegSettings)
Definition at line 18 of file lowThrustOptimisationSetup.cpp.
References initialSpacecraftMass_.
Member Function Documentation
fitness()
std::vector< double > tudat::low_thrust_trajectories::TrajectoryOptimisationProblem::fitness (const std::vector< double > & x) const
Fitness function.
Definition at line 58 of file lowThrustOptimisationSetup.cpp.
References arrivalStateFunction_, tudat::low_thrust_trajectories::createLowThrustLeg(), departureStateFunction_, and lowThrustLegSettings_.
get_bounds()
std::pair< std::vector< double >, std::vector< double > > tudat::low_thrust_trajectories::TrajectoryOptimisationProblem::get_bounds () const
Get bounds.
Definition at line 41 of file lowThrustOptimisationSetup.cpp.
References departureTimeBounds_, and timeOfFlightBounds_.
get_name()
std::string tudat::low_thrust_trajectories::TrajectoryOptimisationProblem::get_name () const
Descriptive name of the problem.
Definition at line 36 of file lowThrustOptimisationSetup.cpp.
get_nobj()
vector_double::size_type tudat::low_thrust_trajectories::TrajectoryOptimisationProblem::get_nobj () const inline
Definition at line 75 of file lowThrustOptimisationSetup.h.
get_nic()
vector_double::size_type tudat::low_thrust_trajectories::TrajectoryOptimisationProblem::get_nic () const inline
Definition at line 80 of file lowThrustOptimisationSetup.h.
get_nec()
vector_double::size_type tudat::low_thrust_trajectories::TrajectoryOptimisationProblem::get_nec () const inline
Definition at line 85 of file lowThrustOptimisationSetup.h.
Member Data Documentation
departureStateFunction_
std::function< Eigen::Vector6d(const double) > tudat::low_thrust_trajectories::TrajectoryOptimisationProblem::departureStateFunction_ private
Definition at line 95 of file lowThrustOptimisationSetup.h.
Referenced by fitness().
arrivalStateFunction_
std::function< Eigen::Vector6d(const double) > tudat::low_thrust_trajectories::TrajectoryOptimisationProblem::arrivalStateFunction_ private
Definition at line 98 of file lowThrustOptimisationSetup.h.
Referenced by fitness().
initialSpacecraftMass_
double tudat::low_thrust_trajectories::TrajectoryOptimisationProblem::initialSpacecraftMass_ private
Definition at line 101 of file lowThrustOptimisationSetup.h.
Referenced by TrajectoryOptimisationProblem().
departureTimeBounds_
std::pair< double, double > tudat::low_thrust_trajectories::TrajectoryOptimisationProblem::departureTimeBounds_ private
Definition at line 104 of file lowThrustOptimisationSetup.h.
Referenced by get_bounds().
timeOfFlightBounds_
std::pair< double, double > tudat::low_thrust_trajectories::TrajectoryOptimisationProblem::timeOfFlightBounds_ private
Definition at line 107 of file lowThrustOptimisationSetup.h.
Referenced by get_bounds().
lowThrustLegSettings_
std::shared_ptr< low_thrust_trajectories::LowThrustLegSettings > tudat::low_thrust_trajectories::TrajectoryOptimisationProblem::lowThrustLegSettings_ private
Definition at line 110 of file lowThrustOptimisationSetup.h.
Referenced by fitness().
The documentation for this struct was generated from the following files:
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/lowThrustOptimisationSetup.h
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/lowThrustOptimisationSetup.cpp