Tudat: tudat::propagators Namespace Reference
tudat::propagators Namespace Reference
Classes
class AccelerationPartialWrtStateSaveSettings
Class to define .
class BodyAerodynamicAngleVariableSaveSettings
Class to define settings for saving an aerodynamics orientation angle from AerodynamicsReferenceFrameAngles list.
class BodyMassIntegratedStateProcessor
Class used for processing numerically integrated masses of bodies.
class BodyMassStateDerivative
Class for computing the derivative of the mass of a set of bodies.
class CentralBodyData
This class acts as a data container for properties of central bodies in a numerical integration.
class CombinedStateTransitionAndSensitivityMatrixInterface
Base class for interface object of interpolation of numerically propagated state transition and sensitivity matrices.
class CustomStateDerivative
class CustomStatePropagatorSettings
Class used to provide settings for a custom state derivative model.
class CustomTerminationCondition
Class for stopping the propagation with custom stopping function.
class DependentVariableSaveSettings
Container class for settings of all dependent variables that are to be saved.
class DynamicsSimulator
Base class for performing full numerical integration of a dynamical system.
class DynamicsStateDerivativeModel
Top-level class responsible for single complete function evaluation of dynamics state derivative.
class EnvironmentUpdater
Class used to update the environment during numerical integration.
class EquationIntegrationInterface
Interface class for integrating some state derivative function.
class EquationIntegrationInterface< StateType, double >
Interface class for integrating some state derivative function.
class EquationIntegrationInterface< StateType, Time >
Interface class for integrating some state derivative function.
class FixedCPUTimePropagationTerminationCondition
Class for stopping the propagation after a fixed amount of CPU time.
class FixedTimePropagationTerminationCondition
Class for stopping the propagation after a fixed amount of time (i.e. for certain independent variable value)
class HybridArcCombinedStateTransitionAndSensitivityMatrixInterface
Interface object of interpolation of numerically propagated state transition and sensitivity matrices for a hybrid of single-and multi-arc estimation (single order is put first in concatenation).
class HybridArcDynamicsSimulator
Class for performing full numerical integration of a dynamical system, with a compbination of single and multi-arc propagations.
class HybridArcPropagatorSettings
Class for defining setting of a propagator for a combination of single- and multi-arc dynamics.
class HybridArcVariationalEquationsSolver
Class to manage and execute the numerical integration of variational equations of a dynamical system, in addition to the dynamics itself, in a combination of single and multiple arcs.
class HybridPropagationTerminationCondition
Class for stopping the propagation when one or all of a given set of stopping conditions is reached.
class IntegratedStateProcessor
Base class for settings how numerically integrated states are processed.
class IntermediateAerodynamicRotationVariableSaveSettings
Class to define settings for saving a rotation matrix between two AerodynamicsReferenceFrames.
class MassPropagatorSettings
Class for defining settings for propagating the mass of a body.
class MultiArcCombinedStateTransitionAndSensitivityMatrixInterface
class MultiArcDynamicsSimulator
Class for performing full numerical integration of a dynamical system over multiple arcs.
class MultiArcPropagatorSettings
Class for defining setting of a propagator for multi-arc dynamics.
class MultiArcVariationalEquationsSolver
Class to manage and execute the numerical integration of variational equations of a dynamical system in multiple arcs.
class MultiTypePropagatorSettings
Class for defining settings for propagating multiple types of dynamics concurrently.
class NBodyCowellStateDerivative
Class for computing the state derivative of translational motion of N bodies, using a Cowell propagator.
class NBodyEnckeStateDerivative
Class for computing the state derivative of translational motion of N bodies, using an Encke propagator.
class NBodyGaussKeplerStateDerivative
Class for computing the state derivative of translational motion of N bodies, using a Gauss method with Kepler elements.
class NBodyGaussModifiedEquinictialStateDerivative
Class for computing the state derivative of translational motion of N bodies, using a Gauss method with MEE.
class NBodyStateDerivative
State derivative for the translational dynamics of N bodies.
class NBodyUnifiedStateModelExponentialMapStateDerivative
Class for computing the state derivative of translational motion of N bodies, using a Gauss method with unified state model with exponential map (USMEM).
class NBodyUnifiedStateModelModifiedRodriguesParametersStateDerivative
Class for computing the state derivative of translational motion of N bodies, using a Gauss method with unified state model with modified rodrigues parameters (USM6).
class NBodyUnifiedStateModelQuaternionsStateDerivative
Class for computing the state derivative of translational motion of N bodies, using a Gauss method with unified state model with quaternions (USM7).
class PropagationCPUTimeTerminationSettings
Class for propagation stopping conditions settings: stopping the propagation after a fixed amount of CPU time.
class PropagationCustomTerminationSettings
Class for propagation stopping conditions settings: stopping the propagation based on custom requirements.
class PropagationDependentVariableTerminationSettings
Class for propagation stopping conditions settings: stopping the propagation after a given dependent variable reaches a certain value.
class PropagationHybridTerminationSettings
Class for propagation stopping conditions settings: combination of other stopping conditions.
class PropagationTerminationCondition
Base class for checking whether the numerical propagation is to be stopped at current time step or not.
class PropagationTerminationDetails
Class for storing details on the propagation termination.
class PropagationTerminationDetailsFromHybridCondition
Class for storing details on the propagation termination when using hybrid termination conditions.
class PropagationTerminationSettings
Base class for defining propagation termination settings.
class PropagationTimeTerminationSettings
Class for propagation stopping conditions settings: stopping the propagation after a fixed amount of time.
class PropagatorSettings
Base class for defining propagation settings, derived classes split into settings for single- and multi-arc dynamics.
class RotationalMotionExponentialMapStateDerivative
Class for computing the state derivative for rotational dynamics of N bodies.
class RotationalMotionModifiedRodriguesParametersStateDerivative
Class for computing the state derivative for rotational dynamics of N bodies.
class RotationalMotionQuaternionsStateDerivative
Class for computing the state derivative for rotational dynamics of N bodies.
class RotationalMotionStateDerivative
Class for computing the state derivative for rotational dynamics of N bodies.
class RotationalStateIntegratedStateProcessor
Class used for processing numerically integrated rotational states.
class RotationalStatePropagatorSettings
Class for defining settings for propagating rotational dynamics.
class SingleAccelerationDependentVariableSaveSettings
Class to define settings for saving a single acceleration (norm or vector) during propagation.
class SingleArcCombinedStateTransitionAndSensitivityMatrixInterface
class SingleArcDynamicsSimulator
Class for performing full numerical integration of a dynamical system in a single arc.
class SingleArcPropagatorSettings
Base class for defining setting of a propagator for single-arc dynamics.
class SingleArcVariationalEquationsSolver
Class to manage and execute the numerical integration of variational equations of a dynamical system in a single arc.
class SingleDependentVariableSaveSettings
Functional base class for defining settings for dependent variables that are to be saved during propagation.
class SingleStateTypeDerivative
Base class for calculating the state derivative model for a single type of dynamics.
class SingleTorqueDependentVariableSaveSettings
Class to define settings for saving a single torque (norm or vector) during propagation.
class SingleVariableLimitPropagationTerminationCondition
Class for stopping the propagation when a dependent variable reaches a given value (either upper or lower bound)
class SingleVariationSingleTermSphericalHarmonicAccelerationSaveSettings
Class to define variations in spherical harmonic acceleration due to single gravity field variation at separate degrees/orders.
class SingleVariationSphericalHarmonicAccelerationSaveSettings
Class to define variations in spherical harmonic acceleration due to single gravity field variation.
class SphericalHarmonicAccelerationTermsDependentVariableSaveSettings
Class to define settings for saving contributions at separate degree/order to spherical harmonic acceleration.
class StateDerivativeCircularRestrictedThreeBodyProblem
State derivative model class for CRTBP.
class TranslationalStateIntegratedStateProcessor
Class used for processing numerically integrated translational states.
class TranslationalStatePropagatorSettings
Class for defining settings for propagating translational dynamics.
class VariableSettings
Functional base class for defining settings for variables.
class VariationalEquations
Class from which the variational equations can be evaluated.
class VariationalEquationsSolver
Base class to manage and execute the numerical integration of equations of motion and variational equations.
Typedefs
typedef std::shared_ptr< StateDerivativeCircularRestrictedThreeBodyProblem > StateDerivativeCircularRestrictedThreeBodyProblemPointer
Typedef for shared-pointer to StateDerivativeCircularRestrictedThreeBodyProblem object.
Enumerations
enum EnvironmentModelsToUpdate {
body_translational_state_update = 0, body_rotational_state_update = 1, body_mass_update = 2, spherical_harmonic_gravity_field_update = 3,
vehicle_flight_conditions_update = 4, radiation_pressure_interface_update = 5
}
Enum defining types of environment model updates that can be done.
enum IntegratedStateType {
hybrid = 0, translational_state = 1, rotational_state = 2, body_mass_state = 3,
custom_state = 4
}
Enum listing types of dynamics that can be numerically integrated.
enum OriginType { global_frame_origin, from_ephemeris, from_integration }
Types of integration origins that can be used in the simulations.
enum PropagationDependentVariables {
mach_number_dependent_variable = 0, altitude_dependent_variable = 1, airspeed_dependent_variable = 2, local_density_dependent_variable = 3,
relative_speed_dependent_variable = 4, relative_position_dependent_variable = 5, relative_distance_dependent_variable = 6, relative_velocity_dependent_variable = 7,
radiation_pressure_dependent_variable = 8, total_acceleration_norm_dependent_variable = 9, single_acceleration_norm_dependent_variable = 10, total_acceleration_dependent_variable = 11,
single_acceleration_dependent_variable = 12, aerodynamic_force_coefficients_dependent_variable = 13, aerodynamic_moment_coefficients_dependent_variable = 14, rotation_matrix_to_body_fixed_frame_variable = 15,
intermediate_aerodynamic_rotation_matrix_variable = 16, relative_body_aerodynamic_orientation_angle_variable = 17, body_fixed_airspeed_based_velocity_variable = 18, total_aerodynamic_g_load_variable = 19,
stagnation_point_heat_flux_dependent_variable = 20, local_temperature_dependent_variable = 21, geodetic_latitude_dependent_variable = 22, control_surface_deflection_dependent_variable = 23,
total_mass_rate_dependent_variables = 24, lvlh_to_inertial_frame_rotation_dependent_variable = 25, periapsis_altitude_dependent_variable = 26, total_torque_norm_dependent_variable = 27,
single_torque_norm_dependent_variable = 28, total_torque_dependent_variable = 29, single_torque_dependent_variable = 30, body_fixed_groundspeed_based_velocity_variable = 31,
keplerian_state_dependent_variable = 32, modified_equinocial_state_dependent_variable = 33, spherical_harmonic_acceleration_terms_dependent_variable = 34, spherical_harmonic_acceleration_norm_terms_dependent_variable = 35,
body_fixed_relative_cartesian_position = 36, body_fixed_relative_spherical_position = 37, total_gravity_field_variation_acceleration = 38, single_gravity_field_variation_acceleration = 39,
single_gravity_field_variation_acceleration_terms = 40, acceleration_partial_wrt_body_translational_state = 41, local_dynamic_pressure_dependent_variable = 42, local_aerodynamic_heat_rate_dependent_variable = 43,
euler_angles_to_body_fixed_313 = 44, current_body_mass_dependent_variable = 45, radiation_pressure_coefficient_dependent_variable = 46
}
Enum listing the dependent variables that can be saved during the propagation.
enum PropagationTerminationReason {
propagation_never_run, unknown_propagation_termination_reason, termination_condition_reached, runtime_error_caught_in_propagation,
nan_or_inf_detected_in_state
}
Possible events that can trigger the termination of a propagation.
enum PropagationTerminationTypes {
time_stopping_condition = 0, cpu_time_stopping_condition = 1, dependent_variable_stopping_condition = 2, hybrid_stopping_condition = 3,
custom_stopping_condition = 4
}
Enum listing the available types of propagation termination settings.
enum RotationalPropagatorType { undefined_rotational_propagator = -1, quaternions = 0, modified_rodrigues_parameters = 1, exponential_map = 2 }
Enum listing propagator types for rotational dynamics that can be used.
enum TranslationalPropagatorType {
undefined_translational_propagator = -1, cowell = 0, encke = 1, gauss_keplerian = 2,
gauss_modified_equinoctial = 3, unified_state_model_quaternions = 4, unified_state_model_modified_rodrigues_parameters = 5, unified_state_model_exponential_map = 6
}
Enum listing propagator types for translational dynamics that can be used.
enum VariableType {
independentVariable, cpuTimeVariable, stateVariable, dependentVariable,
stateTransitionMatrix, sensitivityMatrix
}
Enum listing the variables that can be exported or use in termination conditions during the propagation.
Functions
void addEnvironmentUpdates (std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > &environmentUpdateList, const std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > updatesToAdd)
Function to extend existing list of required environment update types.
template<typename StateScalarType = double>
StateScalarType calculateEnckeQFunction (const StateScalarType qValue)
Function to calculate Encke's function, to be used during propagation using Encke's method.
Eigen::Vector4d calculateExponentialMapDerivative (const Eigen::Vector4d &currentExponentialMapToBaseFrame, const Eigen::Vector3d &angularVelocityVectorInBodyFixedFrame)
Function to obtain the time derivative of exponantial map of body-fixed to inertial frame.
Eigen::Vector4d calculateModifiedRodriguesParametersDerivative (const Eigen::Vector4d &currentModifiedRodriguesParametersToBaseFrame, const Eigen::Vector3d &angularVelocityVectorInBodyFixedFrame)
Function to obtain the time derivative of modified Rodrigues parameters of body-fixed to inertial frame.
Eigen::Vector4d calculateQuaternionDerivative (const Eigen::Vector4d &currentQuaternionsToBaseFrame, const Eigen::Vector3d &angularVelocityVectorInBodyFixedFrame)
Function to obtain the time derivative of quaternions of body-fixed to inertial frame.
void checkAndModifyEnvironmentForDependentVariableSaving (const EnvironmentModelsToUpdate updateType, const std::shared_ptr< SingleDependentVariableSaveSettings > dependentVariableSaveSettings, const simulation_setup::NamedBodyMap &bodyMap)
Function to update environment to allow all required updates to be made.
template<typename StateScalarType = double, typename TimeType = double>
bool checkMultiArcPropagatorSettingsAndParameterEstimationConsistency (const std::shared_ptr< MultiArcPropagatorSettings< StateScalarType > > propagatorSettings, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate, const std::vector< double > arcStartTimes)
Function to check the consistency between multi-arc propagation settings of equations of motion, and estimated parameters.
template<typename StateScalarType = double, typename TimeType = double>
bool checkPropagatorSettingsAndParameterEstimationConsistency (const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate)
Function to check the consistency between propagation settings of equations of motion, and estimated parameters.
void checkTranslationalStatesFeasibility (const std::vector< std::string > &bodiesToIntegrate, const simulation_setup::NamedBodyMap &bodyMap)
Function checking feasibility of resetting the translational dynamics.
void checkValidityOfRequiredEnvironmentUpdates (const std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > &requestedUpdates, const simulation_setup::NamedBodyMap &bodyMap)
Function to check validity of existing environment.
Eigen::Vector6d computeCartesianStateFromKeplerianOrbit (const Eigen::Vector6d &initialState, const double finalPropagationTime, const double gravitationalParameter)
Function to determine the cartesian state at a given time for a keplerian orbit, based on the initial state.
double computeEquilibriumFayRiddellHeatFluxFromProperties (const std::shared_ptr< aerodynamics::AtmosphericFlightConditions > flightConditions, const std::shared_ptr< system_models::VehicleSystems > vehicleSystems)
Function to compute the Fay-Riddell equilibrium heat flux from body properties.
Eigen::Vector6d computeGaussPlanetaryEquationsForKeplerElements (const Eigen::Vector6d &currentOsculatingKeplerElements, const Eigen::Vector3d &accelerationsInRswFrame, const double semiLatusRectum, const double distance, const double meanMotion, const double orbitalAngularMomentum)
Function to evaluate the Gauss planetary equations for Kepler elements.
Eigen::Vector6d computeGaussPlanetaryEquationsForKeplerElements (const Eigen::Vector6d &currentOsculatingKeplerElements, const Eigen::Vector3d &accelerationsInRswFrame, const double centralBodyGravitationalParameter)
Function to evaluate the Gauss planetary equations for Kepler elements.
Eigen::Vector6d computeGaussPlanetaryEquationsForKeplerElements (const Eigen::Vector6d &currentOsculatingKeplerElements, const Eigen::Vector6d &currentCartesianState, const Eigen::Vector3d &accelerationsInInertialFrame, const double centralBodyGravitationalParameter)
Function to evaluate the Gauss planetary equations for Kepler elements.
Eigen::Vector6d computeGaussPlanetaryEquationsForModifiedEquinoctialElements (const Eigen::Vector6d &osculatingModifiedEquinoctialElements, const Eigen::Vector3d &accelerationsInRswFrame, const double centralBodyGravitationalParameter)
Function to evaluate the Gauss planetary equations for modified equinictial elements.
Eigen::Vector7d computeStateDerivativeForUnifiedStateModelExponentialMap (const Eigen::Vector7d &currentUnifiedStateModelElements, const Eigen::Vector3d &accelerationsInRswFrame, const double sineLambda, const double cosineLambda, const double gammaParameter, const Eigen::Vector3d &rotationalVelocityVector, const Eigen::Vector3d &pAuxiliaryVector)
Function to evaluate the state derivative for the unified state model with exponential map.
Eigen::Vector7d computeStateDerivativeForUnifiedStateModelExponentialMap (const Eigen::Vector7d &currentUnifiedStateModelElements, const Eigen::Vector3d &accelerationsInRswFrame, const double centralBodyGravitationalParameter)
Function to evaluate the state derivative for the unified state model with exponential map.
Eigen::Vector7d computeStateDerivativeForUnifiedStateModelExponentialMap (const Eigen::Vector7d &currentUnifiedStateModelElements, const Eigen::Vector6d &currentCartesianState, const Eigen::Vector3d &accelerationsInInertialFrame, const double centralBodyGravitationalParameter)
Function to evaluate the state derivative for the unified state model with exponential map.
Eigen::Vector7d computeStateDerivativeForUnifiedStateModelModifiedRodriguesParameters (const Eigen::Vector7d &currentUnifiedStateModelElements, const Eigen::Vector3d &accelerationsInRswFrame, const double sineLambda, const double cosineLambda, const double gammaParameter, const Eigen::Vector3d &rotationalVelocityVector, const Eigen::Vector3d &pAuxiliaryVector)
Function to evaluate the state derivative for the unified state model with modified rodrigues parameters.
Eigen::Vector7d computeStateDerivativeForUnifiedStateModelModifiedRodriguesParameters (const Eigen::Vector7d &currentUnifiedStateModelElements, const Eigen::Vector3d &accelerationsInRswFrame, const double centralBodyGravitationalParameter)
Function to evaluate the state derivative for the unified state model with modified rodrigues parameters.
Eigen::Vector7d computeStateDerivativeForUnifiedStateModelModifiedRodriguesParameters (const Eigen::Vector7d &currentUnifiedStateModelElements, const Eigen::Vector6d &currentCartesianState, const Eigen::Vector3d &accelerationsInInertialFrame, const double centralBodyGravitationalParameter)
Function to evaluate the state derivative for the unified state model with modified rodrigues parameters.
Eigen::Vector7d computeStateDerivativeForUnifiedStateModelQuaternions (const Eigen::Vector7d &currentUnifiedStateModelElements, const Eigen::Vector3d &accelerationsInRswFrame, const double sineLambda, const double cosineLambda, const double gammaParameter, const Eigen::Vector3d &rotationalVelocityVector, const Eigen::Vector3d &pAuxiliaryVector)
Function to evaluate the state derivative for the unified state model with quaternions.
Eigen::Vector7d computeStateDerivativeForUnifiedStateModelQuaternions (const Eigen::Vector7d &currentUnifiedStateModelElements, const Eigen::Vector3d &accelerationsInRswFrame, const double centralBodyGravitationalParameter)
Function to evaluate the state derivative for the unified state model with quaternions.
Eigen::Vector7d computeStateDerivativeForUnifiedStateModelQuaternions (const Eigen::Vector7d &currentUnifiedStateModelElements, const Eigen::Vector6d &currentCartesianState, const Eigen::Vector3d &accelerationsInInertialFrame, const double centralBodyGravitationalParameter)
Function to evaluate the state derivative for the unified state model with quaternions.
template<typename TimeType , typename StateScalarType >
void convertNumericalSolutionToEphemerisInput (const int bodyIndex, const int startIndex, const std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > &equationsOfMotionNumericalSolution, std::map< TimeType, Eigen::Matrix< StateScalarType, 6, 1 > > &ephemerisTable, const std::function< Eigen::Matrix< StateScalarType, 6, 1 >(const TimeType) > integrationToEphemerisFrameFunction=nullptr)
Function to convert output of translational motion to input for the ephemeris.
template<typename TimeType , typename StateScalarType >
void convertNumericalSolutionToRotationalEphemerisInput (const int startIndex, const int bodyIndex, std::map< TimeType, Eigen::Matrix< StateScalarType, 7, 1 > > &ephemerisTable, const std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > &equationsOfMotionNumericalSolution)
Function to convert output of rotational motion to input for the rotational ephemeris.
template<typename TimeType = double, typename StateScalarType = double, typename ConversionClassType = DynamicsStateDerivativeModel< TimeType, StateScalarType >>
void convertNumericalStateSolutionsToOutputSolutions (std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > &convertedSolution, const std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > &rawSolution, std::shared_ptr< ConversionClassType > converterClass)
template<typename StateScalarType = double, typename TimeType = double>
Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > convertScalarToVectorStateFunction (const std::function< StateScalarType(const TimeType, const StateScalarType) > stateDerivativeFunction, const TimeType currentTime, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &currentStateVector)
Function to evaluate a floating point state-derivative function as though it was a vector state function.
template<typename TimeType , typename StateScalarType >
void createAndSetInterpolatorsForEphemerides (const simulation_setup::NamedBodyMap &bodyMap, const std::vector< std::string > &bodiesToIntegrate, const int startIndex, const std::vector< std::string > &ephemerisUpdateOrder, const std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > &equationsOfMotionNumericalSolution, const std::map< std::string, std::function< Eigen::Matrix< StateScalarType, 6, 1 >(const TimeType) > > &integrationToEphemerisFrameFunctions=std::map< std::string, std::function< Eigen::Matrix< StateScalarType, 6, 1 >(const TimeType) > >())
Create and reset ephemerides interpolator.
template<typename TimeType , typename StateScalarType >
void createAndSetInterpolatorsForRotationalEphemerides (const simulation_setup::NamedBodyMap &bodyMap, const std::vector< std::string > &bodiesToIntegrate, const int startIndex, const std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > &equationsOfMotionNumericalSolution)
Function to reset the tabulated rotational ephemeris of a body.
template<typename StateScalarType = double, typename TimeType = double>
std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > createBodyMassStateDerivativeModel (const std::shared_ptr< MassPropagatorSettings< StateScalarType > > massPropagatorSettings, const simulation_setup::NamedBodyMap &bodyMap)
Function to create a mass state derivative model.
template<typename StateScalarType , typename TimeType >
std::shared_ptr< CentralBodyData< StateScalarType, TimeType > > createCentralBodyData (const std::vector< std::string > &centralBodies, const std::vector< std::string > &bodiesToIntegrate, const simulation_setup::NamedBodyMap &bodyMap)
Function to create object handling frame origin transformations during numerical integration.
template<typename StateScalarType >
Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > createCombinedInitialState (const std::map< IntegratedStateType, std::vector< std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > > > &propagatorSettingsList)
Function to retrieve the initial state for a list of propagator settings.
std::shared_ptr< numerical_integrators::NumericalIntegrator< double, Eigen::Vector6d > > createCR3BPIntegrator (const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const double massParameter, const Eigen::Vector6d &initialState)
Function to create an integrator to propagate the dynamics (in normalized units) in CR3BP.
template<typename TimeType = double, typename StateScalarType = double>
std::pair< std::function< Eigen::VectorXd() >, std::map< int, std::string > > createDependentVariableListFunction (const std::shared_ptr< DependentVariableSaveSettings > saveSettings, const simulation_setup::NamedBodyMap &bodyMap, const std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > > &stateDerivativeModels=std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > >())
Function to create a function that evaluates a list of dependent variables and concatenates the results.
template std::pair< std::function< Eigen::VectorXd() >, std::map< int, std::string > > createDependentVariableListFunction< double, double > (const std::shared_ptr< DependentVariableSaveSettings > saveSettings, const simulation_setup::NamedBodyMap &bodyMap, const std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< double, double > > > > &stateDerivativeModels)
template<typename StateScalarType , typename TimeType >
std::shared_ptr< propagators::EnvironmentUpdater< StateScalarType, TimeType > > createEnvironmentUpdaterForDynamicalEquations (const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings, const simulation_setup::NamedBodyMap &bodyMap)
Create environment updater from a list of propagation settings.
template std::shared_ptr< propagators::EnvironmentUpdater< double, double > > createEnvironmentUpdaterForDynamicalEquations< double, double > (const std::shared_ptr< SingleArcPropagatorSettings< double > > propagatorSettings, const simulation_setup::NamedBodyMap &bodyMap)
template<typename StateScalarType >
std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > createEnvironmentUpdaterSettings (const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings, const simulation_setup::NamedBodyMap &bodyMap, const bool isPartOfMultiTypePropagation=false)
Get list of required environment model update settings from a list of propagation settings.
std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > createEnvironmentUpdaterSettings (const std::shared_ptr< DependentVariableSaveSettings > dependentVariableSaveSettings, const simulation_setup::NamedBodyMap &bodyMap)
Create environment update settings for dependent variables.
std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > createEnvironmentUpdaterSettings (const std::shared_ptr< PropagationTerminationSettings > terminationSettings, const simulation_setup::NamedBodyMap &bodyMap)
Create environment update settings for termination settings.
template std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > createEnvironmentUpdaterSettings< double > (const std::shared_ptr< SingleArcPropagatorSettings< double > > propagatorSettings, const simulation_setup::NamedBodyMap &bodyMap, const bool isPartOfMultiTypePropagation)
std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > createEnvironmentUpdaterSettingsForDependentVariables (const std::shared_ptr< SingleDependentVariableSaveSettings > dependentVariableSaveSettings, const simulation_setup::NamedBodyMap &bodyMap)
Function to create environment update settings for a single dependent variable.
std::shared_ptr< ephemerides::ReferenceFrameManager > createFrameManager (const simulation_setup::NamedBodyMap &bodyMap)
std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > createFullEnvironmentUpdaterSettings (const simulation_setup::NamedBodyMap &bodyMap)
Function to create 'brute-force' update settings, in which each environment model is updated.
template<typename TimeType , typename StateScalarType >
std::map< IntegratedStateType, std::vector< std::shared_ptr< IntegratedStateProcessor< TimeType, StateScalarType > > > > createIntegratedStateProcessors (const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< ephemerides::ReferenceFrameManager > frameManager, const int startIndex=0)
Function to create list objects for processing numerically integrated results.
std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > createMassPropagationEnvironmentUpdaterSettings (const std::map< std::string, std::vector< std::shared_ptr< basic_astrodynamics::MassRateModel > > > massRateModels, const simulation_setup::NamedBodyMap &bodyMap)
Get list of required environment model update settings from mass rate models.
std::shared_ptr< PropagationTerminationCondition > createPropagationTerminationConditions (const std::shared_ptr< PropagationTerminationSettings > terminationSettings, const simulation_setup::NamedBodyMap &bodyMap, const double initialTimeStep)
Function to create propagation termination conditions from associated settings.
std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > createRotationalEquationsOfMotionEnvironmentUpdaterSettings (const basic_astrodynamics::TorqueModelMap &torqueModels, const simulation_setup::NamedBodyMap &bodyMap)
Get list of required environment model update settings from torque models.
template<typename StateScalarType = double, typename TimeType = double>
std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > createRotationalStateDerivativeModel (const std::shared_ptr< RotationalStatePropagatorSettings< StateScalarType > > rotationPropagatorSettings, const simulation_setup::NamedBodyMap &bodyMap, const TimeType startTime)
Function to create a rotational dynamics state derivative model.
template<>
std::shared_ptr< interpolators::OneDimensionalInterpolator< double, Eigen::Matrix< double, 7, 1 > > > createRotationalStateInterpolator (const std::map< double, Eigen::Matrix< double, 7, 1 > > &stateMap)
template<>
std::shared_ptr< interpolators::OneDimensionalInterpolator< double, Eigen::Matrix< long double, 7, 1 > > > createRotationalStateInterpolator (const std::map< double, Eigen::Matrix< long double, 7, 1 > > &stateMap)
template<>
std::shared_ptr< interpolators::OneDimensionalInterpolator< Time, Eigen::Matrix< double, 7, 1 > > > createRotationalStateInterpolator (const std::map< Time, Eigen::Matrix< double, 7, 1 > > &stateMap)
template<>
std::shared_ptr< interpolators::OneDimensionalInterpolator< Time, Eigen::Matrix< long double, 7, 1 > > > createRotationalStateInterpolator (const std::map< Time, Eigen::Matrix< long double, 7, 1 > > &stateMap)
template<typename TimeType , typename StateScalarType >
std::shared_ptr< interpolators::OneDimensionalInterpolator< TimeType, Eigen::Matrix< StateScalarType, 7, 1 > > > createRotationalStateInterpolator (const std::map< TimeType, Eigen::Matrix< StateScalarType, 7, 1 > > &stateMap)
Function to create an interpolator for the new rotational state of a body.
template<typename StateScalarType = double, typename TimeType = double>
std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > createStateDerivativeModel (const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings, const simulation_setup::NamedBodyMap &bodyMap, const TimeType propagationStartTime)
Function to create a state derivative model.
template<typename StateScalarType = double, typename TimeType = double>
std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > > createStateDerivativeModelMap (const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings, const simulation_setup::NamedBodyMap &bodyMap, const TimeType propagationStartTime)
Function to create a map of state derivative models.
template<typename StateScalarType = double, typename TimeType = double>
std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > createStateDerivativeModels (const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings, const simulation_setup::NamedBodyMap &bodyMap, const TimeType propagationStartTime)
Function to create a list of state derivative models.
template<typename TimeType , typename StateScalarType >
std::shared_ptr< interpolators::OneDimensionalInterpolator< TimeType, Eigen::Matrix< StateScalarType, 6, 1 > > > createStateInterpolator (const std::map< TimeType, Eigen::Matrix< StateScalarType, 6, 1 > > &stateMap)
Function to create an interpolator for the new translational state of a body.
template<>
std::shared_ptr< interpolators::OneDimensionalInterpolator< double, Eigen::Matrix< double, 6, 1 > > > createStateInterpolator (const std::map< double, Eigen::Matrix< double, 6, 1 > > &stateMap)
Function to create an interpolator for the new translational state of a body.
template<>
std::shared_ptr< interpolators::OneDimensionalInterpolator< double, Eigen::Matrix< long double, 6, 1 > > > createStateInterpolator (const std::map< double, Eigen::Matrix< long double, 6, 1 > > &stateMap)
Function to create an interpolator for the new translational state of a body.
template<>
std::shared_ptr< interpolators::OneDimensionalInterpolator< Time, Eigen::Matrix< long double, 6, 1 > > > createStateInterpolator (const std::map< Time, Eigen::Matrix< long double, 6, 1 > > &stateMap)
Function to create an interpolator for the new translational state of a body.
template<>
std::shared_ptr< interpolators::OneDimensionalInterpolator< Time, Eigen::Matrix< double, 6, 1 > > > createStateInterpolator (const std::map< Time, Eigen::Matrix< double, 6, 1 > > &stateMap)
Function to create an interpolator for the new translational state of a body.
void createStateTransitionAndSensitivityMatrixInterpolator (std::shared_ptr< interpolators::OneDimensionalInterpolator< double, Eigen::MatrixXd > > &stateTransitionMatrixInterpolator, std::shared_ptr< interpolators::OneDimensionalInterpolator< double, Eigen::MatrixXd > > &sensitivityMatrixInterpolator, std::vector< std::map< double, Eigen::MatrixXd > > &variationalEquationsSolution, const bool clearRawSolution)
Function to create interpolators for state transition and sensitivity matrices from numerical results.
transfer_trajectories::Trajectory createTransferTrajectoryObject (const simulation_setup::NamedBodyMap &bodyMap, const std::vector< std::string > &transferBodyOrder, const std::string &centralBody, const std::vector< transfer_trajectories::TransferLegType > &transferLegTypes, const std::vector< double > trajectoryIndependentVariables, const std::vector< double > minimumPericenterRadii, const bool includeDepartureDeltaV, const double departureSemiMajorAxis, const double departureEccentricity, const bool includeArrivalDeltaV, const double arrivalSemiMajorAxis, const double arrivalEccentricity)
Function to create the trajectory from the body map.
std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > createTranslationalEquationsOfMotionEnvironmentUpdaterSettings (const basic_astrodynamics::AccelerationMap &translationalAccelerationModels, const simulation_setup::NamedBodyMap &bodyMap)
Get list of required environment model update settings from translational acceleration models.
template<typename StateScalarType = double, typename TimeType = double>
std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > createTranslationalStateDerivativeModel (const std::shared_ptr< TranslationalStatePropagatorSettings< StateScalarType > > translationPropagatorSettings, const simulation_setup::NamedBodyMap &bodyMap, const TimeType propagationStartTime)
Function to create a translational state derivative model.
std::vector< std::string > determineEphemerisUpdateorder (std::vector< std::string > integratedBodies, std::vector< std::string > centralBodies, std::vector< std::string > ephemerisOrigins)
Function to determine in which order the ephemerides are to be updated.
double elementAtIndexFunction (const std::function< Eigen::VectorXd() > &vectorFunction, const int index)
Acces element at index function.
template<typename OutputType , typename InputType >
OutputType evaluateBivariateFunction (const std::function< OutputType(const InputType, const InputType) > functionToEvaluate, const std::function< InputType() > firstInput, const std::function< InputType() > secondInput)
Function to evaluate a function with two input variables from function pointers.
template<typename OutputType , typename InputType >
OutputType evaluateBivariateReferenceFunction (const std::function< OutputType(const InputType &, const InputType &) > functionToEvaluate, const std::function< InputType() > firstInput, const std::function< InputType() > secondInput)
Function to evaluate a function with two input variables (by reference) from function pointers.
Eigen::VectorXd evaluateListOfVectorFunctions (const std::vector< std::pair< std::function< Eigen::VectorXd() >, int > > vectorFunctionList, const int totalSize)
Function to evaluate a set of vector-returning functions and concatenate the results.
template<typename OutputType , typename InputType >
OutputType evaluateReferenceFunction (const std::function< OutputType(const InputType &) > functionToEvaluate, const std::function< InputType() > firstInput)
Eigen::Vector3d evaluateRotationalEquationsOfMotion (const Eigen::Matrix3d &inertiaTensor, const Eigen::Vector3d &totalTorque, const Eigen::Vector3d &angularVelocityVector, const Eigen::Matrix3d &inertiaTensorTimeDerivative)
Function to evaluated the classical rotational equations of motion (Euler equations)
template<typename OutputType , typename FirstInputType , typename SecondInputType , typename ThirdInputType >
OutputType evaluateTrivariateFunction (const std::function< OutputType(const FirstInputType &, const SecondInputType, const ThirdInputType) > functionToEvaluate, const std::function< FirstInputType() > firstInput, const std::function< SecondInputType() > secondInput, const std::function< ThirdInputType() > thirdInput)
Function to evaluate a function with three input variables from function pointers.
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< PropagationHybridTerminationSettings > &hybridTerminationSettings)
Create a shared pointer to a PropagationHybridTerminationSettings object from a json object.
void from_json (const nlohmann::json &jsonObject, VariableType &variableType)
Convert json to VariableType.
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< VariableSettings > &variableSettings)
Create a shared pointer to a VariableSettings object from a json object.
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< PropagationTerminationSettings > &terminationSettings)
Create a shared pointer to a PropagationTerminationSettings object from a json object.
void from_json (const nlohmann::json &jsonObject, PropagationDependentVariables &dependentVariable)
Convert json to PropagationDependentVariables.
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< SingleDependentVariableSaveSettings > &dependentVariableSettings)
Create a shared pointer to a SingleDependentVariableSaveSettings object from a json object.
void from_json (const nlohmann::json &jsonObject, IntegratedStateType &integratedStateType)
Convert json to IntegratedStateType.
void from_json (const nlohmann::json &jsonObject, TranslationalPropagatorType &translationalPropagatorType)
Convert json to TranslationalPropagatorType.
void from_json (const nlohmann::json &jsonObject, RotationalPropagatorType &rotationalPropagatorType)
Convert json to RotationalPropagatorType.
template<typename StateScalarType >
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< MultiTypePropagatorSettings< StateScalarType > > &multiTypePropagatorSettings)
Create a shared pointer to a MultiTypePropagatorSettings object from a json object.
template<typename StateScalarType >
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > &singleArcPropagatorSettings)
Create a shared pointer to a SingleArcPropagatorSettings object from a json object.
void fullPropagationPatchedConicsTrajectory (simulation_setup::NamedBodyMap &bodyMap, const std::vector< std::string > &transferBodyOrder, const std::string &patchedConicCentralBody, const std::vector< transfer_trajectories::TransferLegType > &legTypeVector, const std::vector< double > &trajectoryVariableVector, const std::vector< double > &minimumPericenterRadiiVector, const std::vector< double > &semiMajorAxesVector, const std::vector< double > &eccentricitiesVector, const std::vector< std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > > propagatorSettings, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > &integratorSettings, std::map< int, std::map< double, Eigen::Vector6d > > &patchedConicsResultForEachLeg, std::map< int, std::map< double, Eigen::Vector6d > > &fullProblemResultForEachLeg, std::map< int, std::map< double, Eigen::VectorXd > > &dependentVariableResultForEachLeg)
Function to calculate the patched conics trajectory and to propagate the corresponding full problem.
void fullPropagationPatchedConicsTrajectory (simulation_setup::NamedBodyMap &bodyMap, const std::vector< basic_astrodynamics::AccelerationMap > &accelerationMap, const std::vector< std::string > &transferBodyOrder, const std::string &centralBody, const std::string &bodyToPropagate, const std::vector< transfer_trajectories::TransferLegType > &legTypeVector, const std::vector< double > &trajectoryVariableVector, const std::vector< double > &minimumPericenterRadiiVector, const std::vector< double > &semiMajorAxesVector, const std::vector< double > &eccentricitiesVector, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > &integratorSettings, std::map< int, std::map< double, Eigen::Vector6d > > &patchedConicsResultForEachLeg, std::map< int, std::map< double, Eigen::Vector6d > > &fullProblemResultForEachLeg, std::map< int, std::map< double, Eigen::VectorXd > > &dependentVariableResultForEachLeg, const bool terminationSphereOfInfluence, const std::vector< std::shared_ptr< DependentVariableSaveSettings > > dependentVariablesToSave, const TranslationalPropagatorType propagator)
Function to calculate the patched conics trajectory and to propagate the corresponding full problem.
void fullPropagationPatchedConicsTrajectory (simulation_setup::NamedBodyMap &bodyMap, const basic_astrodynamics::AccelerationMap &accelerationMap, const std::vector< std::string > &transferBodyOrder, const std::string &centralBody, const std::string &bodyToPropagate, const std::vector< transfer_trajectories::TransferLegType > &legTypeVector, const std::vector< double > &trajectoryVariableVector, const std::vector< double > &minimumPericenterRadiiVector, const std::vector< double > &semiMajorAxesVector, const std::vector< double > &eccentricitiesVector, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > &integratorSettings, std::map< int, std::map< double, Eigen::Vector6d > > &patchedConicsResultForEachLeg, std::map< int, std::map< double, Eigen::Vector6d > > &fullProblemResultForEachLeg, std::map< int, std::map< double, Eigen::VectorXd > > &dependentVariableResultForEachLeg, const bool terminationSphereOfInfluence=false, const std::shared_ptr< DependentVariableSaveSettings > dependentVariablesToSave=std::shared_ptr< DependentVariableSaveSettings >(), const TranslationalPropagatorType propagator=cowell)
Function to calculate the patched conics trajectory and to propagate the corresponding full problem with the same acceleration map for every leg.
template<typename TimeType = double, typename StateScalarType = double>
std::vector< std::shared_ptr< basic_astrodynamics::AccelerationModel3d > > getAccelerationBetweenBodies (const std::string bodyUndergoingAcceleration, const std::string bodyExertingAcceleration, const std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > > &stateDerivativeModels, const basic_astrodynamics::AvailableAcceleration accelerationModelType)
Function to retrieve a single given acceleration model from a list of models.
template<typename StateScalarType = double>
basic_astrodynamics::AccelerationMap getAccelerationMapFromPropagatorSettings (const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > singleArcPropagatorSettings)
Function to retrieve list of accelerations from propagator settings.
Eigen::Matrix< double, 4, 3 > getAngularVelocityToQuaternionRateMatrix (const Eigen::Vector4d &quaternionVector)
Function to obtain the matrix by which an angular velocity vector of body (expressed in its body-fixed frame) is to be pre-multiplied to obtain the quaternion's time-derivative.
template<typename StateScalarType = double, typename TimeType = double>
Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > getArcInitialStateFromPreviousArcResult (const std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > &previousArcDynamicsSolution, const double currentArcInitialTime)
Function to get the initial state of a translational state arc from the previous state's numerical solution.
template<typename TimeType = double, typename StateScalarType = double>
std::shared_ptr< BodyMassStateDerivative< StateScalarType, TimeType > > getBodyMassStateDerivativeModelForBody (const std::string bodyWithMassDerivative, const std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > > &stateDerivativeModels)
Function to retrieve the state derivative models for body mass of given body.
template<typename StateScalarType = double>
Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > getConcatenatedInitialStates (const std::vector< std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > > &singleArcPropagatorSettings)
Function to concatenate the initial states for a list of single-arc propagations into a single list.
template<typename StateScalarType = double>
int getConcatenatedStateSize (const std::vector< std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > > &singleArcPropagatorSettings)
Function to get the total size of multi-arc initial state vector.
std::vector< double > getDefaultMinimumPericenterRadii (const std::vector< std::string > &bodyNames)
Function to get default minimum pericenter radii for a list of bodiess.
std::string getDependentVariableId (const std::shared_ptr< SingleDependentVariableSaveSettings > dependentVariableSettings)
Function to get a string representing a 'named identification' of a dependent variable.
std::string getDependentVariableName (const PropagationDependentVariables propagationDependentVariables)
Function to get a string representing a 'named identification' of a dependent variable type.
int getDependentVariableSaveSize (const std::shared_ptr< SingleDependentVariableSaveSettings > &singleDependentVariableSaveSettings)
Funtion to get the size of a dependent variable save settings.
int getDependentVariableSize (const std::shared_ptr< SingleDependentVariableSaveSettings > dependentVariableSettings)
Funtion to get the size of a dependent variable.
std::map< int, std::pair< Eigen::Vector6d, Eigen::Vector6d > > getDifferenceFullProblemWrtPatchedConicsTrajectory (simulation_setup::NamedBodyMap &bodyMap, const std::vector< basic_astrodynamics::AccelerationMap > &accelerationMap, const std::vector< std::string > &transferBodyOrder, const std::string &centralBody, const std::string &bodyToPropagate, const std::vector< transfer_trajectories::TransferLegType > &legTypeVector, const std::vector< double > &trajectoryVariableVector, const std::vector< double > &minimumPericenterRadiiVector, const std::vector< double > &semiMajorAxesVector, const std::vector< double > &eccentricitiesVector, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > &integratorSettings, const bool terminationSphereOfInfluence=false, const std::vector< std::shared_ptr< DependentVariableSaveSettings > > dependentVariablesToSave=std::vector< std::shared_ptr< DependentVariableSaveSettings > >(), const TranslationalPropagatorType propagator=cowell)
Function to compute the difference in cartesian state between patched conics trajectory and full dynamics problem, at both departure and arrival positions for each leg.
std::map< int, std::pair< Eigen::Vector6d, Eigen::Vector6d > > getDifferenceFullProblemWrtPatchedConicsTrajectory (simulation_setup::NamedBodyMap &bodyMap, const std::vector< std::string > &transferBodyOrder, const std::string &centralBody, const std::vector< transfer_trajectories::TransferLegType > &legTypeVector, const std::vector< double > &trajectoryVariableVector, const std::vector< double > &minimumPericenterRadiiVector, const std::vector< double > &semiMajorAxesVector, const std::vector< double > &eccentricitiesVector, const std::vector< std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > > propagatorSettings, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > &integratorSettings)
Function to compute the difference in cartesian state between patched conics trajectory and full dynamics problem, at both departure and arrival positions for each leg.
std::map< int, std::pair< Eigen::Vector6d, Eigen::Vector6d > > getDifferenceFullProblemWrtPatchedConicsTrajectory (simulation_setup::NamedBodyMap &bodyMap, const basic_astrodynamics::AccelerationMap &accelerationMap, const std::vector< std::string > &transferBodyOrder, const std::string &centralBody, const std::string &bodyToPropagate, const std::vector< transfer_trajectories::TransferLegType > &legTypeVector, const std::vector< double > &trajectoryVariableVector, const std::vector< double > &minimumPericenterRadiiVector, const std::vector< double > &semiMajorAxesVector, const std::vector< double > &eccentricitiesVector, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > &integratorSettings, const bool terminationSphereOfInfluence, const std::shared_ptr< DependentVariableSaveSettings > dependentVariablesToSave=std::shared_ptr< DependentVariableSaveSettings >(), const TranslationalPropagatorType propagator=cowell)
Function to compute the difference in cartesian state between patched conics trajectory and full dynamics problem, at both departure and arrival positions for each leg when using the same accelerations for each leg.
std::pair< Eigen::Vector6d, Eigen::Vector6d > getDifferenceFullPropagationWrtLambertTargeterAtDepartureAndArrival (const Eigen::Vector3d &cartesianPositionAtDeparture, const Eigen::Vector3d &cartesianPositionAtArrival, const double timeOfFlight, const double initialTime, const simulation_setup::NamedBodyMap &bodyMap, const basic_astrodynamics::AccelerationMap &accelerationModelMap, const std::string &bodyToPropagate, const std::string &centralBody, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const std::vector< std::string > &departureAndArrivalBodies, const bool terminationSphereOfInfluence, const std::shared_ptr< DependentVariableSaveSettings > dependentVariablesToSave=std::shared_ptr< DependentVariableSaveSettings >(), const TranslationalPropagatorType propagator=cowell)
Function to compute the difference in cartesian state between Lambert targeter solution and full dynamics problem, both at departure and at arrival.
Eigen::Matrix3d getDissipationMatrix (const double dampingTime, const Eigen::Matrix3d &inertiaTensor)
Function to obtain the synthetic dissipation matrix from the damping time.
template<typename TimeType = double, typename StateScalarType = double>
std::function< double() > getDoubleDependentVariableFunction (const std::shared_ptr< SingleDependentVariableSaveSettings > dependentVariableSettings, const simulation_setup::NamedBodyMap &bodyMap, const std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > > &stateDerivativeModels=std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > >(), const std::map< propagators::IntegratedStateType, orbit_determination::StateDerivativePartialsMap > &stateDerivativePartials=std::map< propagators::IntegratedStateType, orbit_determination::StateDerivativePartialsMap >())
Function to create a function returning a requested dependent variable value (of type double).
template<typename StateScalarType = double>
std::shared_ptr< MultiArcPropagatorSettings< StateScalarType > > getExtendedMultiPropagatorSettings (const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > singleArcSettings, const std::shared_ptr< MultiArcPropagatorSettings< StateScalarType > > multiArcSettings, const int numberofArcs)
Function to create multi-arc propagator settings by merging an existing multi-arc with single-arc settings.
Eigen::Vector6d getFinalStateDifferenceFullPropagationWrtCR3BP (const double initialTime, const double finalTime, const Eigen::Vector6d &initialState, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const basic_astrodynamics::AccelerationMap &accelerationModelMap, const std::vector< std::string > &bodiesToPropagate, const std::vector< std::string > &centralBodies, const simulation_setup::NamedBodyMap &bodyMap, const std::vector< std::string > &bodiesCR3BP)
Propagate the CR3BP and the full dynamics problem and compute the state difference at the end of the propagation.
template<typename StateType = Eigen::MatrixXd, typename TimeType = double, typename TimeStepType = TimeType>
void getFinalStateForExactDependentVariableTerminationCondition (const std::shared_ptr< numerical_integrators::NumericalIntegrator< TimeType, StateType, StateType, TimeStepType > > integrator, const std::shared_ptr< SingleVariableLimitPropagationTerminationCondition > dependentVariableTerminationCondition, const TimeType secondToLastTime, const TimeType lastTime, const StateType &secondToLastState, const StateType &lastState, TimeType &endTime, StateType &endState)
Function that propagates to an exact final condition (within tolerance) for dependent variable termination condition.
template<typename StateType = Eigen::MatrixXd, typename TimeType = double, typename TimeStepType = TimeType>
void getFinalStateForExactHybridVariableTerminationCondition (const std::shared_ptr< numerical_integrators::NumericalIntegrator< TimeType, StateType, StateType, TimeStepType > > integrator, const std::shared_ptr< HybridPropagationTerminationCondition > hyrbidTerminationCondition, const TimeType secondToLastTime, const TimeType lastTime, const StateType &secondToLastState, const StateType &lastState, TimeType &endTime, StateType &endState)
Function that propagates to an exact final condition (within tolerance) for hybrid termination condition.
template<typename StateType = Eigen::MatrixXd, typename TimeType = double, typename TimeStepType = TimeType>
void getFinalStateForExactTerminationCondition (const std::shared_ptr< numerical_integrators::NumericalIntegrator< TimeType, StateType, StateType, TimeStepType > > integrator, const std::shared_ptr< PropagationTerminationCondition > terminationCondition, const TimeType secondToLastTime, const TimeType lastTime, const StateType &secondToLastState, const StateType &lastState, TimeType &endTime, StateType &endState)
Function that propagates to an exact final condition (within tolerance) for arbitrary termination condition.
void getFullVariationalEquationsSolutionHistory (std::map< double, Eigen::MatrixXd > &fullVariationalEquationsSolutionHistory, const std::shared_ptr< CombinedStateTransitionAndSensitivityMatrixInterface > stateTransitionInterface, const std::vector< double > evaluationTimes)
Function to retrueve full state transition and sensitivity matrices at epochs.
void getFullVariationalEquationsSolutionHistory (std::map< double, Eigen::MatrixXd > &fullVariationalEquationsSolutionHistory, const std::shared_ptr< CombinedStateTransitionAndSensitivityMatrixInterface > stateTransitionInterface, const double timeStep, const double initialTime, const double finalTime)
Function to retrueve full state transition and sensitivity matrices at epochs.
int getGeneralizedAccelerationSize (const IntegratedStateType stateType)
Function to get the size of the generalized acceleration for a given state type.
template<typename TimeType = double, typename StateScalarType = double>
Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > getInitialArcWiseStateOfBody (const std::string &bodyToIntegrate, const std::vector< std::string > &centralBodies, const simulation_setup::NamedBodyMap &bodyMap, const std::vector< TimeType > arcStartTimes)
Function to get the state of single body, w.r.t. some central body, at a set of requested times, concatanated into one vector.
template<typename TimeType = double, typename StateScalarType = double>
Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > getInitialRotationalStateOfBody (const std::string &bodyToIntegrate, const std::string &baseOrientation, const simulation_setup::NamedBodyMap &bodyMap, const TimeType initialTime)
Function to get the rotational states state of a body, at the requested time.
template<typename TimeType = double, typename StateScalarType = double>
Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > getInitialRotationalStatesOfBodies (const std::vector< std::string > &bodiesToIntegrate, const std::vector< std::string > &baseOrientations, const simulation_setup::NamedBodyMap &bodyMap, const TimeType initialTime)
Function to get the rotational states states of a set of bodies, at the requested time.
template<typename TimeType = double, typename StateScalarType = double>
Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > getInitialStateOfBody (const std::string &bodyToIntegrate, const std::string &centralBody, const simulation_setup::NamedBodyMap &bodyMap, const TimeType initialTime)
Function to get the states of single body, w.r.t. some central body, at the requested time.
template<typename TimeType = double, typename StateScalarType = double>
Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > getInitialStatesOfBodies (const std::vector< std::string > &bodiesToIntegrate, const std::vector< std::string > &centralBodies, const simulation_setup::NamedBodyMap &bodyMap, const TimeType initialTime)
Function to get the states of a set of bodies, w.r.t. some set of central bodies, at the requested time.
template<typename TimeType = double, typename StateScalarType = double>
Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > getInitialStatesOfBodiesFromFrameManager (const std::vector< std::string > &bodiesToIntegrate, const std::vector< std::string > &centralBodies, const simulation_setup::NamedBodyMap &bodyMap, const TimeType initialTime, const std::shared_ptr< ephemerides::ReferenceFrameManager > frameManager)
Function to get the states of a set of bodies, w.r.t. some set of central bodies, at the requested time.
template<typename StateScalarType = double>
std::vector< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > getInitialStatesPerArc (const std::vector< std::shared_ptr< PropagatorSettings< StateScalarType > > > propagatorSettings)
Function to get a vector of initial states from a vector of propagator settings.
template<typename StateScalarType >
std::map< IntegratedStateType, std::vector< std::pair< std::string, std::string > > > getIntegratedTypeAndBodyList (const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings)
Function to retrieve the list of integrated state types and reference ids.
template std::map< IntegratedStateType, std::vector< std::pair< std::string, std::string > > > getIntegratedTypeAndBodyList< double > (const std::shared_ptr< SingleArcPropagatorSettings< double > > propagatorSettings)
Eigen::Matrix3d getMatrixFromVectorRotationRepresentation (const Eigen::VectorXd vectorRepresentation)
Get the 3x3 matrix representation from a vector with 9 entries.
void getMatrixInOutputVectorRepresentation (const Eigen::MatrixXd &matrix, Eigen::VectorXd &vector)
Function to convert a matrix to the format used to save dependent variables.
template<typename StateScalarType >
int getMultiTypePropagatorStateSize (const std::map< IntegratedStateType, std::vector< std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > > > &propagatorSettingsList)
Function to retrieve the state size for a list of propagator settings.
Eigen::VectorXd getNormsOfAccelerationDifferencesFromLists (const std::function< Eigen::VectorXd() > firstAccelerationFunction, const std::function< Eigen::VectorXd() > secondAccelerationFunction)
void getOutputVectorInMatrixRepresentation (const Eigen::VectorXd &vector, Eigen::MatrixXd &matrix, const int rows, const int columns)
Function to convert a vector dependent variable output to its original matrix representation.
std::vector< std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > > getPatchedConicPropagatorSettings (simulation_setup::NamedBodyMap &bodyMap, const std::vector< basic_astrodynamics::AccelerationMap > &accelerationMap, const std::vector< std::string > &transferBodyOrder, const std::string &centralBody, const std::string &bodyToPropagate, const std::vector< transfer_trajectories::TransferLegType > &legTypeVector, const std::vector< double > &trajectoryVariableVector, const std::vector< double > &minimumPericenterRadiiVector, const std::vector< double > &semiMajorAxesVector, const std::vector< double > &eccentricitiesVector, const std::vector< std::shared_ptr< DependentVariableSaveSettings > > dependentVariablesToSave, const TranslationalPropagatorType propagator, const bool terminationSphereOfInfluence, const double terminationDistanceScaler)
Function to calculate the patched conics trajectory and to propagate the corresponding full problem.
Eigen::Matrix4d getQuaterionToQuaternionRateMatrix (const Eigen::Vector3d &angularVelocityVectorInBodyFixedFrame)
Function to obtain the matrix by which a quaternion vector (representing body-fixed to inertial frame rotation) is to be pre-multiplied to obtain this quaternion's time-derivative.
Eigen::Quaterniond getQuaternionFromVectorRotationRepresentation (const Eigen::VectorXd vectorRepresentation)
et the quaternion formulation of an orthonormal matrix, from input of a vector with 9 entries corresponding to matrix entries.
template<typename TimeType = double, typename StateScalarType = double>
std::shared_ptr< RotationalMotionStateDerivative< StateScalarType, TimeType > > getRotationalStateDerivativeModelForBody (const std::string bodyUndergoingTorque, const std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > > &stateDerivativeModels)
template<typename TimeType , typename StateScalarType >
void getSingleBodyStateHistoryFromPropagationOutpiut (const std::vector< std::string > &bodiesToIntegrate, const int translationalStateStartIndex, const std::string &bodyForWhichToRetrieveState, const std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > &equationsOfMotionNumericalSolution, std::map< TimeType, Eigen::Matrix< StateScalarType, 6, 1 > > &ephemerisInput, int &bodyIndex, const std::map< std::string, std::function< Eigen::Matrix< StateScalarType, 6, 1 >(const TimeType) > > &integrationToEphemerisFrameFunctions=std::map< std::string, std::function< Eigen::Matrix< StateScalarType, 6, 1 >(const TimeType) > >())
Function to extract the numerical solution for the translational dynamics of a single body from full propagation history.
int getSingleIntegrationDifferentialEquationOrder (const IntegratedStateType stateType)
Get order of differential equation for governing equations of dynamics of given type.
int getSingleIntegrationSize (const IntegratedStateType stateType)
Get size of state for single propagated state of given type.
std::shared_ptr< propagators::PropagationTerminationSettings > getSingleLegPartSphereOfInfluenceTerminationSettings (simulation_setup::NamedBodyMap &bodyMap, const std::string &bodyToPropagate, const std::string &centralBody, const std::string &departureBody, const std::string &arrivalBody, const double initialTimeCurrentLeg, const double finalTimeCurrentLeg, const bool useBackwardLegToDepartureBody, const double terminationDistanceScaler)
std::pair< std::shared_ptr< propagators::PropagationTerminationSettings >, std::shared_ptr< propagators::PropagationTerminationSettings > > getSingleLegSphereOfInfluenceTerminationSettings (simulation_setup::NamedBodyMap &bodyMap, const std::string &bodyToPropagate, const std::string &centralBody, const std::string &departureBody, const std::string &arrivalBody, const double initialTimeCurrentLeg, const double finalTimeCurrentLeg, const double terminationDistanceScaler)
template<typename StateScalarType , typename TimeType >
std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > getSphericalHarmonicAccelerationForDependentVariables (const std::shared_ptr< SingleDependentVariableSaveSettings > dependentVariableSettings, const std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > > &stateDerivativeModels, const bool allowThirdBodyAcceleration=false)
Function to retrieve relevant spherical harmonic acceleration model for dependent variable setting.
template<typename StateScalarType = double, typename TimeType = double>
std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > > getStateDerivativeModelMapFromVector (const std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > &stateDerivativeModelList)
Function to convert a list of state derivative models to a map sorted by state type.
template<typename StateType = Eigen::MatrixXd, typename TimeType = double, typename TimeStepType = TimeType>
TimeStepType getTerminationDependentVariableErrorForGivenTimeStep (TimeStepType timeStep, const std::shared_ptr< numerical_integrators::NumericalIntegrator< TimeType, StateType, StateType, TimeStepType > > integrator, const std::shared_ptr< SingleVariableLimitPropagationTerminationCondition > dependentVariableTerminationCondition)
Function to determine, for a given time step of the numerical integrator, the error in termination dependent variable.
template<typename TimeType = double, typename StateScalarType = double>
std::vector< std::shared_ptr< basic_astrodynamics::TorqueModel > > getTorqueBetweenBodies (const std::string bodyUndergoingTorque, const std::string bodyExertingTorque, const std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > > &stateDerivativeModels, const basic_astrodynamics::AvailableTorque torqueModelType)
Function to retrieve a single given torque model from a list of models.
template<typename TimeType = double, typename StateScalarType = double>
std::shared_ptr< NBodyStateDerivative< StateScalarType, TimeType > > getTranslationalStateDerivativeModelForBody (const std::string bodyUndergoingAcceleration, const std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > > &stateDerivativeModels)
Function to retrieve the state derivative models for translational dynamics of given body.
std::string getVariableId (const std::shared_ptr< VariableSettings > variableSettings)
Function to get a string representing a 'named identification' of a variable.
std::string getVariableName (const VariableType variableType)
Function to get a string representing a 'named identification' of a variable type.
template<typename TimeType = double, typename StateScalarType = double>
std::pair< std::function< Eigen::VectorXd() >, int > getVectorDependentVariableFunction (const std::shared_ptr< SingleDependentVariableSaveSettings > dependentVariableSettings, const simulation_setup::NamedBodyMap &bodyMap, const std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > > &stateDerivativeModels=std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > >(), const std::map< propagators::IntegratedStateType, orbit_determination::StateDerivativePartialsMap > &stateDerivativePartials=std::map< propagators::IntegratedStateType, orbit_determination::StateDerivativePartialsMap >())
Function to create a function returning a requested dependent variable value (of type VectorXd).
Eigen::VectorXd getVectorFromDoubleFunction (const std::function< double() > &doubleFunction)
Function to return a vector containing only one value given by doubleFunction.
Eigen::VectorXd getVectorFunctionFromBlockFunction (const std::function< void(Eigen::Block< Eigen::MatrixXd >) > blockFunction, const int numberOfRows, const int numberOfColumns)
Function to retrieve matrix block function output in vector representation.
Eigen::VectorXd getVectorRepresentationForRotationMatrix (const Eigen::Matrix3d &currentRotationMatrix)
Get the vector representation of a rotation matrix.
Eigen::VectorXd getVectorRepresentationForRotationMatrixFunction (const std::function< Eigen::Matrix3d() > rotationFunction)
Get the vector representation of a rotation matrix.
Eigen::VectorXd getVectorRepresentationForRotationQuaternion (const std::function< Eigen::Quaterniond() > rotationFunction)
Get the vector representation of a quaternion.
template<typename TimeType , typename StateScalarType >
Eigen::VectorXd getZeroProperModeRotationalState (const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings, const double bodyMeanRotationRate, const std::vector< double > dissipationTimes, std::vector< std::pair< std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > >, std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > > > &propagatedStates, std::vector< std::pair< std::map< TimeType, Eigen::Matrix< double, Eigen::Dynamic, 1 > >, std::map< TimeType, Eigen::Matrix< double, Eigen::Dynamic, 1 > > > > &dependentVariables, const bool propagateNominal=true, const bool writeToFileInLoop=false, const std::string baseFileName="", const std::string outputFolder=input_output::getTudatRootPath())
Function to determine the initial rotational state for which the free mode is fully damped.
template<typename TimeType , typename StateScalarType >
Eigen::VectorXd getZeroProperModeRotationalState (const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings, const double bodyMeanRotationRate, const std::vector< double > dissipationTimes)
Function to determine the initial rotational state for which the free mode is fully damped.
template<typename StateType = Eigen::MatrixXd, typename TimeType = double, typename TimeStepType = TimeType>
std::shared_ptr< PropagationTerminationDetails > integrateEquationsFromIntegrator (const std::shared_ptr< numerical_integrators::NumericalIntegrator< TimeType, StateType, StateType, TimeStepType > > integrator, const TimeStepType initialTimeStep, const std::shared_ptr< PropagationTerminationCondition > propagationTerminationCondition, std::map< TimeType, StateType > &solutionHistory, std::map< TimeType, Eigen::VectorXd > &dependentVariableHistory, std::map< TimeType, double > &cumulativeComputationTimeHistory, const std::function< Eigen::VectorXd() > dependentVariableFunction=std::function< Eigen::VectorXd() >(), const std::function< void(StateType &) > statePostProcessingFunction=std::function< void(StateType &) >(), const int saveFrequency=TUDAT_NAN, const TimeType printInterval=TUDAT_NAN, const std::chrono::steady_clock::time_point initialClockTime=std::chrono::steady_clock::now())
Function to numerically integrate a given first order differential equation.
template std::shared_ptr< PropagationTerminationDetails > integrateEquationsFromIntegrator< Eigen::MatrixXd, double, double > (const std::shared_ptr< numerical_integrators::NumericalIntegrator< double, Eigen::MatrixXd, Eigen::MatrixXd, double > > integrator, const double initialTimeStep, const std::shared_ptr< PropagationTerminationCondition > propagationTerminationCondition, std::map< double, Eigen::MatrixXd > &solutionHistory, std::map< double, Eigen::VectorXd > &dependentVariableHistory, std::map< double, double > &cumulativeComputationTimeHistory, const std::function< Eigen::VectorXd() > dependentVariableFunction, const std::function< void(Eigen::MatrixXd &) > statePostProcessingFunction, const int saveFrequency, const double printInterval, const std::chrono::steady_clock::time_point initialClockTime)
template std::shared_ptr< PropagationTerminationDetails > integrateEquationsFromIntegrator< Eigen::VectorXd, double, double > (const std::shared_ptr< numerical_integrators::NumericalIntegrator< double, Eigen::VectorXd, Eigen::VectorXd, double > > integrator, const double initialTimeStep, const std::shared_ptr< PropagationTerminationCondition > propagationTerminationCondition, std::map< double, Eigen::VectorXd > &solutionHistory, std::map< double, Eigen::VectorXd > &dependentVariableHistory, std::map< double, double > &cumulativeComputationTimeHistory, const std::function< Eigen::VectorXd() > dependentVariableFunction, const std::function< void(Eigen::VectorXd &) > statePostProcessingFunction, const int saveFrequency, const double printInterval, const std::chrono::steady_clock::time_point initialClockTime)
template<typename StateScalarType = double, typename TimeType = double>
void integrateForwardWithDissipationAndBackwardsWithout (const std::shared_ptr< SingleArcDynamicsSimulator< StateScalarType, TimeType > > dynamicsSimulator, const std::shared_ptr< basic_astrodynamics::DissipativeTorqueModel > dissipativeTorque, std::pair< std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > >, std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > > &propagatedStates, std::pair< std::map< TimeType, Eigen::Matrix< double, Eigen::Dynamic, 1 > >, std::map< TimeType, Eigen::Matrix< double, Eigen::Dynamic, 1 > > > &dependentVariables)
Function to integrate forward in time with synthetic dissipation, and subsequently backwards without dissipation.
std::map< double, Eigen::Vector6d > performCR3BPIntegration (const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const double massParameter, const Eigen::Vector6d &initialState, const double finalTime, const bool propagateToExactFinalTime)
Function to propagate the dynamics (in normalized units) in CR3BP.
void propagateCovariance (std::map< double, Eigen::MatrixXd > &propagatedCovariance, const Eigen::MatrixXd &initialCovariance, const std::map< double, Eigen::MatrixXd > &fullVariationalEquationsSolutionHistory)
Function to propagate full covariance at the initial time to state covariance at later times.
void propagateCovariance (std::map< double, Eigen::MatrixXd > &propagatedCovariance, const Eigen::MatrixXd &initialCovariance, const std::shared_ptr< CombinedStateTransitionAndSensitivityMatrixInterface > stateTransitionInterface, const std::vector< double > evaluationTimes)
Function to propagate full covariance at the initial time to state covariance at later times.
void propagateCovariance (std::map< double, Eigen::MatrixXd > &propagatedCovariance, const Eigen::MatrixXd &initialCovariance, const std::shared_ptr< CombinedStateTransitionAndSensitivityMatrixInterface > stateTransitionInterface, const double timeStep, const double initialTime, const double finalTime)
Function to propagate full covariance at the initial time to state covariance at later times.
void propagateCR3BPAndFullDynamicsProblem (const double initialTime, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > propagatorSettings, const simulation_setup::NamedBodyMap &bodyMap, const std::vector< std::string > &bodiesCR3BP, std::map< double, Eigen::Vector6d > &directPropagationResult, std::map< double, Eigen::Vector6d > &cr3bpPropagationResult, std::map< double, Eigen::VectorXd > &dependentVariableValues)
void propagateCR3BPAndFullDynamicsProblem (const double initialTime, const double finalTime, const Eigen::Vector6d &initialState, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const basic_astrodynamics::AccelerationMap &accelerationModelMap, const std::vector< std::string > &bodiesToPropagate, const std::vector< std::string > &centralBodies, const simulation_setup::NamedBodyMap &bodyMap, const std::vector< std::string > &bodiesCR3BP, std::map< double, Eigen::Vector6d > &directPropagationResult, std::map< double, Eigen::Vector6d > &cr3bpPropagationResult)
Propagate the CR3BP and the full dynamics problem.
void propagateCR3BPFromEnvironment (const double initialTime, const double finalPropagationTime, const Eigen::Vector6d &initialState, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const simulation_setup::NamedBodyMap &bodyMap, const std::vector< std::string > &bodiesCR3BP, std::map< double, Eigen::Vector6d > &stateHistory, const bool outputInNormalizedCoordinates)
Propagate CR3BP from CR3BP environment.
void propagateFormalErrors (std::map< double, Eigen::VectorXd > &propagatedFormalErrors, const Eigen::MatrixXd &initialCovariance, const std::shared_ptr< CombinedStateTransitionAndSensitivityMatrixInterface > stateTransitionInterface, const std::vector< double > evaluationTimes)
Function to propagate full covariance at the initial time to state formal errors at later times.
void propagateFormalErrors (std::map< double, Eigen::VectorXd > &propagatedFormalErrors, const Eigen::MatrixXd &initialCovariance, const std::shared_ptr< CombinedStateTransitionAndSensitivityMatrixInterface > stateTransitionInterface, const double timeStep, const double initialTime, const double finalTime)
Function to propagate full covariance at the initial time to state formal errors at later times.
void propagateKeplerianOrbitLegAndFullProblem (const double timeOfFlight, const double initialTime, const simulation_setup::NamedBodyMap &bodyMap, const std::string &centralBody, const std::vector< std::string > &departureAndArrivalBodies, const Eigen::Vector3d &velocityAfterDeparture, const std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > propagatorSettings, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, std::map< double, Eigen::Vector6d > &keplerianOrbitResult, std::map< double, Eigen::Vector6d > &fullProblemResult, std::map< double, Eigen::VectorXd > &dependentVariables, const double centralBodyGravitationalParameter, const Eigen::Vector3d &cartesianPositionAtDeparture)
Function to propagate the motion of a body over a trajectory leg, both along a keplerian orbit and in a full dynamics problem.
void propagateLambertTargeterAndFullProblem (const double timeOfFlight, const double initialTime, const simulation_setup::NamedBodyMap &bodyMap, const std::string &centralBody, std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > propagatorSettings, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, std::map< double, Eigen::Vector6d > &lambertTargeterResult, std::map< double, Eigen::Vector6d > &fullProblemResult, std::map< double, Eigen::VectorXd > &dependentVariableResult, const std::vector< std::string > &departureAndArrivalBodies, const double centralBodyGravitationalParameter, const Eigen::Vector3d &cartesianPositionAtDeparture, const Eigen::Vector3d &cartesianPositionAtArrival)
Function to propagate the full dynamics problem and the Lambert targeter solution.
void propagateLambertTargeterAndFullProblem (const double timeOfFlight, const double initialTime, const simulation_setup::NamedBodyMap &bodyMap, const basic_astrodynamics::AccelerationMap &accelerationModelMap, const std::string &bodyToPropagate, const std::string &centralBody, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, std::map< double, Eigen::Vector6d > &lambertTargeterResult, std::map< double, Eigen::Vector6d > &fullProblemResult, std::map< double, Eigen::VectorXd > &dependentVariableResult, const std::vector< std::string > &departureAndArrivalBodies, const bool terminationSphereOfInfluence, const Eigen::Vector3d &cartesianPositionAtDeparture, const Eigen::Vector3d &cartesianPositionAtArrival, const double departureBodyGravitationalParameter, const double arrivalBodyGravitationalParameter, const double centralBodyGravitationalParameter, const std::shared_ptr< DependentVariableSaveSettings > dependentVariablesToSave=std::shared_ptr< DependentVariableSaveSettings >(), const TranslationalPropagatorType propagator=cowell)
Function to propagate the full dynamics problem and the Lambert targeter solution.
void propagateMga1DsmPositionAndFullProblem (simulation_setup::NamedBodyMap &bodyMap, const std::vector< std::string > departureAndArrivalBodies, const std::string &dsm, const std::string &centralBody, const Eigen::Vector3d cartesianPositionAtDeparture, const Eigen::Vector3d cartesianPositionDSM, const Eigen::Vector3d cartesianPositionAtArrival, const double initialTime, const double timeDsm, const double timeArrival, const transfer_trajectories::TransferLegType &legType, const std::vector< double > &trajectoryVariableVector, const double minimumPericenterRadius, const double semiMajorAxis, const double eccentricity, Eigen::Vector3d &velocityAfterDeparture, Eigen::Vector3d &velocityBeforeArrival, const std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > propagatorSettingsBeforeDsm, const std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > propagatorSettingsAfterDsm, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > &integratorSettings, std::map< double, Eigen::Vector6d > &patchedConicsResultFromDepartureToDsm, std::map< double, Eigen::Vector6d > &fullProblemResultFromDepartureToDsm, std::map< double, Eigen::VectorXd > &dependentVariablesFromDepartureToDsm, std::map< double, Eigen::Vector6d > &patchedConicsResultFromDsmToArrival, std::map< double, Eigen::Vector6d > &fullProblemResultFromDsmToArrival, std::map< double, Eigen::VectorXd > &dependentVariablesFromDsmToArrival)
Function to both calculate a patched conics leg including a DSM and propagate the corresponding full dynamics problem.
void propagateMga1DsmVelocityAndFullProblem (simulation_setup::NamedBodyMap &bodyMap, const std::vector< std::string > departureAndArrivalBodies, const std::string &dsm, const std::string &centralBody, const Eigen::Vector3d cartesianPositionAtDeparture, const Eigen::Vector3d cartesianPositionDSM, const Eigen::Vector3d cartesianPositionAtArrival, const double initialTime, const double timeDsm, const double timeArrival, const transfer_trajectories::TransferLegType &legType, const std::vector< double > &trajectoryVariableVector, const double semiMajorAxis, const double eccentricity, Eigen::Vector3d &velocityAfterDeparture, Eigen::Vector3d &velocityBeforeArrival, const std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > propagatorSettingsBeforeDsm, const std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > propagatorSettingsAfterDsm, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > &integratorSettings, std::map< double, Eigen::Vector6d > &patchedConicsResultFromDepartureToDsm, std::map< double, Eigen::Vector6d > &fullProblemResultFromDepartureToDsm, std::map< double, Eigen::VectorXd > &dependentVariablesFromDepartureToDsm, std::map< double, Eigen::Vector6d > &patchedConicsResultFromDsmToArrival, std::map< double, Eigen::Vector6d > &fullProblemResultFromDsmToArrival, std::map< double, Eigen::VectorXd > &dependentVariablesFromDsmToArrival)
Function to both calculate a patched conics leg including a DSM and propagate the corresponding full dynamics problem.
void propagateMgaWithoutDsmAndFullProblem (simulation_setup::NamedBodyMap &bodyMap, const std::vector< std::string > departureAndArrivalBodies, const std::string centralBody, const Eigen::Vector3d cartesianPositionAtDeparture, const Eigen::Vector3d cartesianPositionAtArrival, const double initialTime, const double timeOfFlight, const std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > propagatorSettings, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > &integratorSettings, std::map< double, Eigen::Vector6d > &patchedConicsResult, std::map< double, Eigen::Vector6d > &fullProblemResult, std::map< double, Eigen::VectorXd > &dependentVariableResultCurrentLeg)
Function to both calculate a patched conics leg without DSM and propagate the full dynamics problem.
template<typename StateType = Eigen::MatrixXd, typename TimeType = double, typename TimeStepType = TimeType>
void propagateToExactTerminationCondition (const std::shared_ptr< numerical_integrators::NumericalIntegrator< TimeType, StateType, StateType, TimeStepType > > integrator, const std::shared_ptr< PropagationTerminationCondition > propagationTerminationCondition, const TimeStepType timeStep, const std::function< Eigen::VectorXd() > dependentVariableFunction, std::map< TimeType, StateType > &solutionHistory, std::map< TimeType, Eigen::VectorXd > &dependentVariableHistory, const double currentCpuTime)
Function that propagates to an exact final condition (within tolerance) for arbitrary termination condition.
std::vector< std::function< double() > > removeCentralGravityAccelerations (const std::vector< std::string > &centralBodies, const std::vector< std::string > &bodiesToIntegrate, basic_astrodynamics::AccelerationMap &accelerationModelsPerBody)
Function to remove the central gravity acceleration from an AccelerationMap.
void removePropagatedStatesFomEnvironmentUpdates (std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > &environmentModelsToUpdate, const std::map< IntegratedStateType, std::vector< std::pair< std::string, std::string > > > &integratedStateList)
Function that removes propagated states from the updated environment variables.
template<typename TimeType , typename StateScalarType >
void resetIntegratedBodyMass (const simulation_setup::NamedBodyMap &bodyMap, const std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > &equationsOfMotionNumericalSolution, const std::vector< std::string > &bodiesToIntegrate, const std::pair< unsigned int, unsigned int > startIndexAndSize)
Resets the mass models of the integrated bodies from the numerical integration results.
template<typename TimeType , typename StateScalarType >
void resetIntegratedEphemerides (const simulation_setup::NamedBodyMap &bodyMap, const std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > &equationsOfMotionNumericalSolution, const std::vector< std::string > &bodiesToIntegrate, const std::pair< unsigned int, unsigned int > startIndexAndSize, std::vector< std::string > ephemerisUpdateOrder=std::vector< std::string >(), const std::map< std::string, std::function< Eigen::Matrix< StateScalarType, 6, 1 >(const TimeType) > > &integrationToEphemerisFrameFunctions=std::map< std::string, std::function< Eigen::Matrix< StateScalarType, 6, 1 >(const TimeType) > >())
Resets the ephemerides of the integrated bodies from the numerical integration results.
template<typename StateTimeType , typename StateScalarType , typename EphemerisTimeType , typename EphemerisScalarType >
void resetIntegratedEphemerisOfBody (const std::map< StateTimeType, Eigen::Matrix< StateScalarType, 6, 1 > > &ephemerisInput, const std::shared_ptr< ephemerides::TabulatedCartesianEphemeris< EphemerisScalarType, EphemerisTimeType > > tabulatedEphemeris)
Function to reset the tabulated ephemeris of a body.
template<typename TimeType , typename StateScalarType >
void resetIntegratedEphemerisOfBody (const simulation_setup::NamedBodyMap &bodyMap, const std::map< TimeType, Eigen::Matrix< StateScalarType, 6, 1 > > &ephemerisInput, const std::string &bodyToIntegrate)
Function to reset the tabulated ephemeris of a body.
template<typename TimeType , typename StateScalarType >
void resetIntegratedMultiArcStatesWithEqualArcDynamics (const std::vector< std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > > &equationsOfMotionNumericalSolution, const std::map< IntegratedStateType, std::vector< std::shared_ptr< IntegratedStateProcessor< TimeType, StateScalarType > > > > integratedStateProcessors, const std::vector< double > &arcStartTimes)
Function resetting dynamical properties of environment from numerical multi-arc dynamics solution.
template<typename TimeType , typename StateScalarType >
void resetIntegratedRotationalEphemerides (const simulation_setup::NamedBodyMap &bodyMap, const std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > &equationsOfMotionNumericalSolution, const std::vector< std::string > &bodiesToIntegrate, const std::pair< unsigned int, unsigned int > startIndexAndSize)
Resets the rotational ephemerides of a set of bodies from the numerical integration results.
template<typename TimeType , typename StateScalarType >
void resetIntegratedRotationalEphemerisOfBody (const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< interpolators::OneDimensionalInterpolator< TimeType, Eigen::Matrix< StateScalarType, 7, 1 > > > rotationalEphemerisInterpolator, const std::string bodyToIntegrate)
Function to reset the tabulated rotational ephemeris of a body.
template<typename TimeType , typename StateScalarType >
void resetIntegratedStates (const std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > &equationsOfMotionNumericalSolution, const std::map< IntegratedStateType, std::vector< std::shared_ptr< IntegratedStateProcessor< TimeType, StateScalarType > > > > integratedStateProcessors)
Function resetting dynamical properties of environment from numerical dynamics solution.
template<typename TimeType , typename StateScalarType >
void resetMultiArcIntegratedEphemerides (const simulation_setup::NamedBodyMap &bodyMap, const std::vector< std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > > &equationsOfMotionNumericalSolution, const std::vector< double > arcStartTimes, const std::vector< std::string > &bodiesToIntegrate, const std::pair< unsigned int, unsigned int > startIndexAndSize, std::vector< std::string > ephemerisUpdateOrder=std::vector< std::string >(), const std::map< std::string, std::function< Eigen::Matrix< StateScalarType, 6, 1 >(const TimeType) > > &integrationToEphemerisFrameFunctions=std::map< std::string, std::function< Eigen::Matrix< StateScalarType, 6, 1 >(const TimeType) > >())
Resets the ephemerides of the integrated bodies from the numerical multi-arc integration results.
template<typename StateScalarType >
void resetSingleArcInitialStates (const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings, const std::map< propagators::IntegratedStateType, std::map< std::pair< std::string, std::string >, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > > currentArcInitialStates)
template<typename StateScalarType = double>
void setMultiTypePropagationClosure (const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings, const simulation_setup::NamedBodyMap &bodyMap)
Function that finalized multi-type propagator creation by ensuring that any mutual dependencies are correctly set.
template<typename StateScalarType = double>
void setPropagatorSettingsMultiArcStatesInEstimatedDynamicalParameters (const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate, const std::shared_ptr< MultiArcPropagatorSettings< StateScalarType > > propagatorSettings)
Function to transfer the initial multi-arc states from propagator settings to associated initial state estimation parameters.
basic_astrodynamics::AccelerationMap setupAccelerationMapCR3BP (const std::string &namePrimaryBody, const std::string &nameSecondaryBody, const std::string &nameBodyToPropagate, const std::string &centralBody, const simulation_setup::NamedBodyMap &bodyMap)
Setup CR3BP acceleration map.
basic_astrodynamics::AccelerationMap setupAccelerationMapLambertTargeter (const std::string &nameCentralBody, const std::string &nameBodyToPropagate, const simulation_setup::NamedBodyMap &bodyMap)
Function to directly setup an acceleration map for the Lambert targeter.
std::vector< basic_astrodynamics::AccelerationMap > setupAccelerationMapPatchedConicsTrajectory (const double numberOfLegs, const std::string &nameCentralBody, const std::string &nameBodyToPropagate, const simulation_setup::NamedBodyMap &bodyMap)
Function to directly setup a vector of acceleration maps for a patched conics trajectory.
simulation_setup::NamedBodyMap setupBodyMapCR3BP (const double distancePrimarySecondary, const std::string &namePrimaryBody, const std::string &nameSecondaryBody, const std::string &nameBodyToPropagate, const std::string &frameOrientation, const double primaryGravitationalParameter, const double secondaryGravitationalParameter)
Function to directly setup CR3BP bodyMap.
simulation_setup::NamedBodyMap setupBodyMapFromEphemeridesForLambertTargeter (const std::string &nameCentralBody, const std::string &nameBodyToPropagate, const std::vector< std::string > &departureAndArrivalBodies)
Function to setup Lambert targeter map.
simulation_setup::NamedBodyMap setupBodyMapFromEphemeridesForPatchedConicsTrajectory (const std::string &nameCentralBody, const std::string &nameBodyToPropagate, const std::vector< std::string > &nameTransferBodies)
Function to setup a body map for the patched conics trajectory.
simulation_setup::NamedBodyMap setupBodyMapFromUserDefinedEphemeridesForLambertTargeter (const std::string &nameCentralBody, const std::string &nameBodyToPropagate, const std::vector< std::string > &departureAndArrivalBodies, const std::vector< ephemerides::EphemerisPointer > &ephemerisVectorDepartureAndArrivalBodies)
simulation_setup::NamedBodyMap setupBodyMapFromUserDefinedEphemeridesForPatchedConicsTrajectory (const std::string &nameCentralBody, const std::string &nameBodyToPropagate, const std::vector< std::string > &nameTransferBodies, const std::vector< ephemerides::EphemerisPointer > &ephemerisVectorTransferBodies, const std::vector< double > &gravitationalParametersTransferBodies, const std::string &frameOrientation="J2000")
Function to setup a body map for the patched conics trajectory.
simulation_setup::NamedBodyMap setupBodyMapFromUserDefinedStatesForLambertTargeter (const std::string &nameCentralBody, const std::string &nameBodyToPropagate, const std::vector< std::string > &departureAndArrivalBodies, const Eigen::Vector3d &cartesianPositionAtDeparture, const Eigen::Vector3d &cartesianPositionAtArrival)
Function to setup a Lambert targeter map.
std::map< std::string, std::shared_ptr< simulation_setup::BodySettings > > setupBodySettingsCR3BP (const double distancePrimarySecondary, const std::string &namePrimaryBody, const std::string &nameSecondaryBody, const std::string &frameOrientation, const double primaryGravitationalParameter, const double secondaryGravitationalParameter)
template<typename TimeType , typename StateScalarType >
void setVariationalEquationsSolution (std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > &numericalIntegrationResult, std::vector< std::map< double, Eigen::MatrixXd > > &variationalEquationsSolution, const std::pair< int, int > stateTransitionStartIndices, const std::pair< int, int > sensitivityStartIndices, const int stateTransitionMatrixSize, const int parameterSetSize)
Function to separate the time histories of the sensitivity and state transition matrices from a full numerical solution.
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< PropagationHybridTerminationSettings > &hybridTerminationSettings)
Create a json object from a shared pointer to a PropagationHybridTerminationSettings object.
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< VariableSettings > &variableSettings)
Create a json object from a shared pointer to a SingleDependentVariableSaveSettings object.
void to_json (nlohmann::json &jsonObject, const VariableType &variableType)
Convert VariableType to json.
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< PropagationTerminationSettings > &terminationSettings)
Create a json object from a shared pointer to a PropagationTerminationSettings object.
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< SingleDependentVariableSaveSettings > &dependentVariableSettings)
Create a json object from a shared pointer to a SingleDependentVariableSaveSettings object.
void to_json (nlohmann::json &jsonObject, const PropagationDependentVariables &dependentVariable)
Convert PropagationDependentVariables to json.
void to_json (nlohmann::json &jsonObject, const IntegratedStateType &integratedStateType)
Convert IntegratedStateType to json.
void to_json (nlohmann::json &jsonObject, const TranslationalPropagatorType &translationalPropagatorType)
Convert TranslationalPropagatorType to json.
void to_json (nlohmann::json &jsonObject, const RotationalPropagatorType &rotationalPropagatorType)
Convert RotationalPropagatorType to json.
template<typename StateScalarType >
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< MultiTypePropagatorSettings< StateScalarType > > &multiTypePropagatorSettings)
Create a json object from a shared pointer to a MultiTypePropagatorSettings object.
template<typename StateScalarType >
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > &singleArcPropagatorSettings)
Create a json object from a shared pointer to a SingleArcPropagatorSettings object.
Variables
static std::map< PropagationDependentVariables, std::string > dependentVariableTypes
Map of PropagationDependentVariables string representations.
static std::map< IntegratedStateType, std::string > integratedStateTypes
Map of IntegratedStateTypes string representations.
static std::map< RotationalPropagatorType, std::string > rotationalPropagatorTypes
Map of RotationalPropagatorTypes string representations.
static std::map< TranslationalPropagatorType, std::string > translationalPropagatorTypes
Map of TranslationalPropagatorTypes string representations.
static std::vector< PropagationDependentVariables > unsupportedDependentVariableTypes
PropagationDependentVariables not supported by json_interface.
static std::vector< IntegratedStateType > unsupportedIntegratedStateTypes
IntegratedStateTypes not supported by json_interface.
static std::vector< RotationalPropagatorType > unsupportedRotationalPropagatorTypes = { }
RotationalPropagatorTypes not supported by json_interface.
static std::vector< TranslationalPropagatorType > unsupportedTranslationalPropagatorTypes = { }
TranslationalPropagatorTypes not supported by json_interface.
static std::vector< VariableType > unsupportedVariableTypes = { }
VariableTypes not supported by json_interface.
static std::map< VariableType, std::string > variableTypes
Map of VariableTypes string representations.
Typedef Documentation
StateDerivativeCircularRestrictedThreeBodyProblemPointer
typedef std::shared_ptr< StateDerivativeCircularRestrictedThreeBodyProblem > tudat::propagators::StateDerivativeCircularRestrictedThreeBodyProblemPointer
Definition at line 68 of file stateDerivativeCircularRestrictedThreeBodyProblem.h.
Enumeration Type Documentation
OriginType
enum tudat::propagators::OriginType
Enumerator
global_frame_origin
from_ephemeris
from_integration
Definition at line 28 of file centralBodyData.h.
EnvironmentModelsToUpdate
enum tudat::propagators::EnvironmentModelsToUpdate
Enumerator
body_translational_state_update
body_rotational_state_update
body_mass_update
spherical_harmonic_gravity_field_update
vehicle_flight_conditions_update
radiation_pressure_interface_update
Definition at line 26 of file environmentUpdateTypes.h.
TranslationalPropagatorType
enum tudat::propagators::TranslationalPropagatorType
Enumerator
undefined_translational_propagator
cowell
encke
gauss_keplerian
gauss_modified_equinoctial
unified_state_model_quaternions
unified_state_model_modified_rodrigues_parameters
unified_state_model_exponential_map
Definition at line 34 of file nBodyStateDerivative.h.
RotationalPropagatorType
enum tudat::propagators::RotationalPropagatorType
Enumerator
undefined_rotational_propagator
quaternions
modified_rodrigues_parameters
exponential_map
Definition at line 34 of file rotationalMotionStateDerivative.h.
IntegratedStateType
enum tudat::propagators::IntegratedStateType
Enumerator
hybrid
translational_state
rotational_state
body_mass_state
custom_state
Definition at line 28 of file singleStateTypeDerivative.h.
VariableType
enum tudat::propagators::VariableType
Enumerator
independentVariable
cpuTimeVariable
stateVariable
dependentVariable
stateTransitionMatrix
sensitivityMatrix
Definition at line 31 of file propagationOutputSettings.h.
PropagationDependentVariables
enum tudat::propagators::PropagationDependentVariables
Enumerator
mach_number_dependent_variable
altitude_dependent_variable
airspeed_dependent_variable
local_density_dependent_variable
relative_speed_dependent_variable
relative_position_dependent_variable
relative_distance_dependent_variable
relative_velocity_dependent_variable
radiation_pressure_dependent_variable
total_acceleration_norm_dependent_variable
single_acceleration_norm_dependent_variable
total_acceleration_dependent_variable
single_acceleration_dependent_variable
aerodynamic_force_coefficients_dependent_variable
aerodynamic_moment_coefficients_dependent_variable
rotation_matrix_to_body_fixed_frame_variable
intermediate_aerodynamic_rotation_matrix_variable
relative_body_aerodynamic_orientation_angle_variable
body_fixed_airspeed_based_velocity_variable
total_aerodynamic_g_load_variable
stagnation_point_heat_flux_dependent_variable
local_temperature_dependent_variable
geodetic_latitude_dependent_variable
control_surface_deflection_dependent_variable
total_mass_rate_dependent_variables
lvlh_to_inertial_frame_rotation_dependent_variable
periapsis_altitude_dependent_variable
total_torque_norm_dependent_variable
single_torque_norm_dependent_variable
total_torque_dependent_variable
single_torque_dependent_variable
body_fixed_groundspeed_based_velocity_variable
keplerian_state_dependent_variable
modified_equinocial_state_dependent_variable
spherical_harmonic_acceleration_terms_dependent_variable
spherical_harmonic_acceleration_norm_terms_dependent_variable
body_fixed_relative_cartesian_position
body_fixed_relative_spherical_position
total_gravity_field_variation_acceleration
single_gravity_field_variation_acceleration
single_gravity_field_variation_acceleration_terms
acceleration_partial_wrt_body_translational_state
local_dynamic_pressure_dependent_variable
local_aerodynamic_heat_rate_dependent_variable
euler_angles_to_body_fixed_313
current_body_mass_dependent_variable
radiation_pressure_coefficient_dependent_variable
Definition at line 69 of file propagationOutputSettings.h.
PropagationTerminationReason
enum tudat::propagators::PropagationTerminationReason
Enumerator
propagation_never_run
unknown_propagation_termination_reason
termination_condition_reached
runtime_error_caught_in_propagation
nan_or_inf_detected_in_state
Definition at line 26 of file propagationTermination.h.
PropagationTerminationTypes
enum tudat::propagators::PropagationTerminationTypes
Enumerator
time_stopping_condition
cpu_time_stopping_condition
dependent_variable_stopping_condition
hybrid_stopping_condition
custom_stopping_condition
Definition at line 29 of file propagationTerminationSettings.h.
Function Documentation
getAccelerationBetweenBodies()
template<typename TimeType = double, typename StateScalarType = double> std::vector< std::shared_ptr< basic_astrodynamics::AccelerationModel3d > > tudat::propagators::getAccelerationBetweenBodies (const std::string bodyUndergoingAcceleration, const std::string bodyExertingAcceleration, const std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > > & stateDerivativeModels, const basic_astrodynamics::AvailableAcceleration accelerationModelType)
Function to retrieve a single given acceleration model, determined by the body exerting and undergoing the acceleration, as well as the acceleration type, from a list of state derivative models.
Parameters
bodyUndergoingAcceleration Name of body undergoing the acceleration.
bodyExertingAcceleration Name of body exerting the acceleration.
stateDerivativeModels Complete list of state derivativ models
accelerationModelType Type of acceleration model that is to be retrieved.
Definition at line 737 of file dynamicsStateDerivativeModel.h.
References tudat::basic_astrodynamics::getAccelerationModelsOfType(), and translational_state.
Referenced by getDoubleDependentVariableFunction(), getSphericalHarmonicAccelerationForDependentVariables(), and getVectorDependentVariableFunction().
getTorqueBetweenBodies()
template<typename TimeType = double, typename StateScalarType = double> std::vector< std::shared_ptr< basic_astrodynamics::TorqueModel > > tudat::propagators::getTorqueBetweenBodies (const std::string bodyUndergoingTorque, const std::string bodyExertingTorque, const std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > > & stateDerivativeModels, const basic_astrodynamics::AvailableTorque torqueModelType)
Function to retrieve a single given torque model, determined by the body exerting and undergoing the torque, as well as the torque type, from a list of state derivative models.
Parameters
bodyUndergoingTorque Name of body undergoing the torque.
bodyExertingTorque Name of body exerting the torque.
stateDerivativeModels Complete list of state derivativ models
torqueModelType Type of torque model that is to be retrieved.
Definition at line 797 of file dynamicsStateDerivativeModel.h.
References tudat::basic_astrodynamics::getTorqueModelsOfType(), and rotational_state.
Referenced by getDoubleDependentVariableFunction(), and getVectorDependentVariableFunction().
getTranslationalStateDerivativeModelForBody()
template<typename TimeType = double, typename StateScalarType = double> std::shared_ptr< NBodyStateDerivative< StateScalarType, TimeType > > tudat::propagators::getTranslationalStateDerivativeModelForBody (const std::string bodyUndergoingAcceleration, const std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > > & stateDerivativeModels)
Function to retrieve the state derivative models for translational dynamics (object of derived class from NBodyStateDerivative) of given body from full list of state derivative models
Parameters
bodyUndergoingAcceleration Name of body for which state derivative model is to be retrieved
stateDerivativeModels Complete list of state derivativ models
Returns
State derivative model computing derivative of translational state of requested body.
Definition at line 853 of file dynamicsStateDerivativeModel.h.
References tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::getBodiesToBeIntegratedNumerically(), and translational_state.
Referenced by getDoubleDependentVariableFunction(), and getVectorDependentVariableFunction().
getRotationalStateDerivativeModelForBody()
template<typename TimeType = double, typename StateScalarType = double> std::shared_ptr< RotationalMotionStateDerivative< StateScalarType, TimeType > > tudat::propagators::getRotationalStateDerivativeModelForBody (const std::string bodyUndergoingTorque, const std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > > & stateDerivativeModels)
Definition at line 900 of file dynamicsStateDerivativeModel.h.
References tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::getBodiesToBeIntegratedNumerically(), and rotational_state.
Referenced by getDoubleDependentVariableFunction(), and getVectorDependentVariableFunction().
getBodyMassStateDerivativeModelForBody()
template<typename TimeType = double, typename StateScalarType = double> std::shared_ptr< BodyMassStateDerivative< StateScalarType, TimeType > > tudat::propagators::getBodyMassStateDerivativeModelForBody (const std::string bodyWithMassDerivative, const std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > > & stateDerivativeModels)
Function to retrieve the state derivative models for body mass (object of class BodyMassStateDerivative) of given body from full list of state derivative models
Parameters
bodyWithMassDerivative Name of body for which mass derivative model is to be retrieved
stateDerivativeModels Complete list of state derivative models
Returns
State derivative model computing derivative of body mass of requested body.
Definition at line 955 of file dynamicsStateDerivativeModel.h.
References body_mass_state.
Referenced by getDoubleDependentVariableFunction().
convertNumericalStateSolutionsToOutputSolutions()
template<typename TimeType = double, typename StateScalarType = double, typename ConversionClassType = DynamicsStateDerivativeModel< TimeType, StateScalarType >> void tudat::propagators::convertNumericalStateSolutionsToOutputSolutions (std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > & convertedSolution, const std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > & rawSolution, std::shared_ptr< ConversionClassType > converterClass)
Definition at line 1029 of file dynamicsStateDerivativeModel.h.
Referenced by tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), and tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations().
addEnvironmentUpdates()
void tudat::propagators::addEnvironmentUpdates (std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > & environmentUpdateList, const std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > updatesToAdd)
Function to extend existing list of required environment update types
Parameters
environmentUpdateList List of environment updates to extend (passed by reference and modified by function)
updatesToAdd List of environment updates that are to be added to environmentUpdateList
Definition at line 21 of file environmentUpdateTypes.cpp.
Referenced by createEnvironmentUpdaterSettings(), createFullEnvironmentUpdaterSettings(), createMassPropagationEnvironmentUpdaterSettings(), createRotationalEquationsOfMotionEnvironmentUpdaterSettings(), tudat::simulation_setup::createThrustAcceleratioModel(), and createTranslationalEquationsOfMotionEnvironmentUpdaterSettings().
getDissipationMatrix()
Eigen::Matrix3d tudat::propagators::getDissipationMatrix (const double dampingTime, const Eigen::Matrix3d & inertiaTensor)
Function to obtain the synthetic dissipation matrix from the damping time
Parameters
dampingTime Damping time
inertiaTensor Inertia Tensor
Returns
Dissipation Matrix
Definition at line 33 of file getZeroProperModeRotationalInitialState.h.
Referenced by getZeroProperModeRotationalState().
integrateForwardWithDissipationAndBackwardsWithout()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::integrateForwardWithDissipationAndBackwardsWithout (const std::shared_ptr< SingleArcDynamicsSimulator< StateScalarType, TimeType > > dynamicsSimulator, const std::shared_ptr< basic_astrodynamics::DissipativeTorqueModel > dissipativeTorque, std::pair< std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > >, std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > > & propagatedStates, std::pair< std::map< TimeType, Eigen::Matrix< double, Eigen::Dynamic, 1 > >, std::map< TimeType, Eigen::Matrix< double, Eigen::Dynamic, 1 > > > & dependentVariables)
Function to integrate forward in time with synthetic dissipation, and subsequently backwards without dissipation. This function is used to find the initial rotational state with a damped free mode. integrateForwardWithDissipationAndBackwardsWithout
Parameters
dynamicsSimulator Object to numerically propagate the dynamics
dissipativeTorque Synthetic dissipative torque model
propagatedStates Pair of numerically propagated states (first: forward propagation; second: backwards propagation). Returned by reference.
dependentVariables Pair of numerically computed dependent variables (first: forward propagation; second: backwards propagation). Returned by reference.
Definition at line 53 of file getZeroProperModeRotationalInitialState.h.
getZeroProperModeRotationalState() [1/2]
template<typename TimeType , typename StateScalarType > Eigen::VectorXd tudat::propagators::getZeroProperModeRotationalState (const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings, const double bodyMeanRotationRate, const std::vector< double > dissipationTimes, std::vector< std::pair< std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > >, std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > > > & propagatedStates, std::vector< std::pair< std::map< TimeType, Eigen::Matrix< double, Eigen::Dynamic, 1 > >, std::map< TimeType, Eigen::Matrix< double, Eigen::Dynamic, 1 > > > > & dependentVariables, const bool propagateNominal = true, const bool writeToFileInLoop = false, const std::string baseFileName = "", const std::string outputFolder = input_output::getTudatRootPath())
Function to determine the initial rotational state for which the free mode is fully damped, using the approach of Rambaux et al. (2012). Using this method, the dynamics is propagated forward in time with an artificial damping, and backwards in time without this damping. The process is repeated for an ever increasing value of the dissipation time. Using this function, the numerical state and dependent variables at each of the iterations is returned (by reference) by the function. Additionally, the results can be written to files after each iteration.
Parameters
bodyMap Map of bodies in the propagation, with keys the names of the bodies.
integratorSettings Settings for the numerical integration scheme
propagatorSettings Settings for the propagator, must include rotational dynamics of only a single body, but may also include translational dynamics.
bodyMeanRotationRate Mean rotation rate of body for which the initial state is to be determined, used in the computation of the dissipation matrix.
dissipationTimes List of characteristic times for dissipation matrix (in order of which they will be used)
propagatedStates Numerical states for each iteration
dependentVariables Dependent variables for each iteration
propagateNominal Boolean designating whether the undamped dynamics is also to be propagated (saved in index 0)
writeToFileInLoop Boolean designating whether the results are written to files after each iteration. NOTE: setting this variable to true will result in propagatedStates and dependentVariables being returned empty (the data being stored in files instead)
baseFileName File name prefix used for files, if writeToFileInLoop is true
outputFolder Directory to which files will be written, if writeToFileInLoop is true
Definition at line 136 of file getZeroProperModeRotationalInitialState.h.
References tudat::simulation_setup::Body::getCurrentAngularVelocityVectorInLocalFrame(), getDissipationMatrix(), tudat::propagators::MultiTypePropagatorSettings< StateScalarType >::propagatorSettingsMap_, rotational_state, and tudat::input_output::writeDataMapToTextFile().
Referenced by getZeroProperModeRotationalState().
getZeroProperModeRotationalState() [2/2]
template<typename TimeType , typename StateScalarType > Eigen::VectorXd tudat::propagators::getZeroProperModeRotationalState (const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings, const double bodyMeanRotationRate, const std::vector< double > dissipationTimes)
Function to determine the initial rotational state for which the free mode is fully damped, using the approach of Rambaux et al. (2012). Using this method, the dynamics is propagated forward in time with an artificial damping, and backwards in time without this damping. The process is repeated for an ever increasing value of the dissipation time
Parameters
bodyMap Map of bodies in the propagation, with keys the names of the bodies.
integratorSettings Settings for the numerical integration scheme
propagatorSettings Settings for the propagator, must include rotational dynamics of only a single body, but may also include translational dynamics.
bodyMeanRotationRate Mean rotation rate of body for which the initial state is to be determined, used in the computation of the dissipation matrix.
dissipationTimes List of characteristic times for dissipation matrix (in order of which they will be used)
Definition at line 315 of file getZeroProperModeRotationalInitialState.h.
References getZeroProperModeRotationalState().
integrateEquationsFromIntegrator< Eigen::MatrixXd, double, double >()
template std::shared_ptr< PropagationTerminationDetails > tudat::propagators::integrateEquationsFromIntegrator< Eigen::MatrixXd, double, double > (const std::shared_ptr< numerical_integrators::NumericalIntegrator< double, Eigen::MatrixXd, Eigen::MatrixXd, double > > integrator, const double initialTimeStep, const std::shared_ptr< PropagationTerminationCondition > propagationTerminationCondition, std::map< double, Eigen::MatrixXd > & solutionHistory, std::map< double, Eigen::VectorXd > & dependentVariableHistory, std::map< double, double > & cumulativeComputationTimeHistory, const std::function< Eigen::VectorXd() > dependentVariableFunction, const std::function< void(Eigen::MatrixXd &) > statePostProcessingFunction, const int saveFrequency, const double printInterval, const std::chrono::steady_clock::time_point initialClockTime)
integrateEquationsFromIntegrator< Eigen::VectorXd, double, double >()
template std::shared_ptr< PropagationTerminationDetails > tudat::propagators::integrateEquationsFromIntegrator< Eigen::VectorXd, double, double > (const std::shared_ptr< numerical_integrators::NumericalIntegrator< double, Eigen::VectorXd, Eigen::VectorXd, double > > integrator, const double initialTimeStep, const std::shared_ptr< PropagationTerminationCondition > propagationTerminationCondition, std::map< double, Eigen::VectorXd > & solutionHistory, std::map< double, Eigen::VectorXd > & dependentVariableHistory, std::map< double, double > & cumulativeComputationTimeHistory, const std::function< Eigen::VectorXd() > dependentVariableFunction, const std::function< void(Eigen::VectorXd &) > statePostProcessingFunction, const int saveFrequency, const double printInterval, const std::chrono::steady_clock::time_point initialClockTime)
getTerminationDependentVariableErrorForGivenTimeStep()
template<typename StateType = Eigen::MatrixXd, typename TimeType = double, typename TimeStepType = TimeType> TimeStepType tudat::propagators::getTerminationDependentVariableErrorForGivenTimeStep (TimeStepType timeStep, const std::shared_ptr< numerical_integrators::NumericalIntegrator< TimeType, StateType, StateType, TimeStepType > > integrator, const std::shared_ptr< SingleVariableLimitPropagationTerminationCondition > dependentVariableTerminationCondition)
Function to determine, for a given time step of the numerical integrator, the error in termination dependent variable. This function is used as input for the root finder when the propagation must terminate exactly on a dependent variable value
Parameters
timeStep Time step to take with the numerical integrator
integrator Numerical integrator used for propagation
dependentVariableTerminationCondition Settings used to determine value/type of dependent variable at which propagation is to terminate
Returns
The difference between the reached and required value of the termination dependent variable
Definition at line 48 of file integrateEquations.h.
getFinalStateForExactDependentVariableTerminationCondition()
template<typename StateType = Eigen::MatrixXd, typename TimeType = double, typename TimeStepType = TimeType> void tudat::propagators::getFinalStateForExactDependentVariableTerminationCondition (const std::shared_ptr< numerical_integrators::NumericalIntegrator< TimeType, StateType, StateType, TimeStepType > > integrator, const std::shared_ptr< SingleVariableLimitPropagationTerminationCondition > dependentVariableTerminationCondition, const TimeType secondToLastTime, const TimeType lastTime, const StateType & secondToLastState, const StateType & lastState, TimeType & endTime, StateType & endState)
Function that propagates to an exact final condition (within tolerance) for dependent variable termination condition. Determines the time step that is to be taken by using a root finder, and returns (by reference) the converged final time and state.
Parameters
integrator Numerical integrator that is used for propagation. Upon input to this function, the integrator is rolled back to the secondToLastTime/secondToLastState
dependentVariableTerminationCondition Termination condition that is to be used
secondToLastTime Second to last time (e.g. last time at which integration did not exceed termination condition)
lastTime Time at which integration first exceeded termination condition
secondToLastState Second to last state (e.g. state at last time where integration did not exceed termination condition)
lastState State at time where integration first exceeded termination condition
endTime Time at which exact termination condition is met (returned by reference).
endState State at time where exact termination condition is met (returned by reference).
Definition at line 85 of file integrateEquations.h.
References TUDAT_NAN, and TUDAT_UNUSED_PARAMETER.
Referenced by getFinalStateForExactTerminationCondition().
getFinalStateForExactHybridVariableTerminationCondition()
template<typename StateType = Eigen::MatrixXd, typename TimeType = double, typename TimeStepType = TimeType> void tudat::propagators::getFinalStateForExactHybridVariableTerminationCondition (const std::shared_ptr< numerical_integrators::NumericalIntegrator< TimeType, StateType, StateType, TimeStepType > > integrator, const std::shared_ptr< HybridPropagationTerminationCondition > hyrbidTerminationCondition, const TimeType secondToLastTime, const TimeType lastTime, const StateType & secondToLastState, const StateType & lastState, TimeType & endTime, StateType & endState)
Function that propagates to an exact final condition (within tolerance) for hybrid termination condition. Determines the termination time/state for each of the constituent termination condition, and chooses the hybrid termiantion time/state accordingly
Parameters
integrator Numerical integrator that is used for propagation. Upon input to this function, the integrator is rolled back to the secondToLastTime/secondToLastState
hyrbidTerminationCondition Termination condition that is to be used
secondToLastTime Second to last time (e.g. last time at which integration did not exceed termination condition)
lastTime Time at which integration first exceeded termination condition
secondToLastState Second to last state (e.g. state at last time where integration did not exceed termination condition)
lastState State at time where integration first exceeded termination condition
endTime Time at which exact termination condition is met (returned by reference).
endState State at time where exact termination condition is met (returned by reference).
Definition at line 162 of file integrateEquations.h.
References getFinalStateForExactTerminationCondition().
Referenced by getFinalStateForExactTerminationCondition().
getFinalStateForExactTerminationCondition()
template<typename StateType = Eigen::MatrixXd, typename TimeType = double, typename TimeStepType = TimeType> void tudat::propagators::getFinalStateForExactTerminationCondition (const std::shared_ptr< numerical_integrators::NumericalIntegrator< TimeType, StateType, StateType, TimeStepType > > integrator, const std::shared_ptr< PropagationTerminationCondition > terminationCondition, const TimeType secondToLastTime, const TimeType lastTime, const StateType & secondToLastState, const StateType & lastState, TimeType & endTime, StateType & endState)
Function that propagates to an exact final condition (within tolerance) for arbitrary termination condition.
Parameters
integrator Numerical integrator that is used for propagation. Upon input to this function, the integrator is at the lastTime/lastState
terminationCondition Termination condition that is to be used
secondToLastTime Second to last time (e.g. last time at which integration did not exceed termination condition)
lastTime Time at which integration first exceeded termination condition
secondToLastState Second to last state (e.g. state at last time where integration did not exceed termination condition)
lastState State at time where integration first exceeded termination condition
endTime Time at which exact termination condition is met (returned by reference).
endState State at time where exact termination condition is met (returned by reference).
Definition at line 265 of file integrateEquations.h.
References cpu_time_stopping_condition, custom_stopping_condition, dependent_variable_stopping_condition, getFinalStateForExactDependentVariableTerminationCondition(), getFinalStateForExactHybridVariableTerminationCondition(), tudat::propagators::FixedTimePropagationTerminationCondition::getStopTime(), hybrid_stopping_condition, and time_stopping_condition.
Referenced by getFinalStateForExactHybridVariableTerminationCondition(), and propagateToExactTerminationCondition().
propagateToExactTerminationCondition()
template<typename StateType = Eigen::MatrixXd, typename TimeType = double, typename TimeStepType = TimeType> void tudat::propagators::propagateToExactTerminationCondition (const std::shared_ptr< numerical_integrators::NumericalIntegrator< TimeType, StateType, StateType, TimeStepType > > integrator, const std::shared_ptr< PropagationTerminationCondition > propagationTerminationCondition, const TimeStepType timeStep, const std::function< Eigen::VectorXd() > dependentVariableFunction, std::map< TimeType, StateType > & solutionHistory, std::map< TimeType, Eigen::VectorXd > & dependentVariableHistory, const double currentCpuTime)
Function that propagates to an exact final condition (within tolerance) for arbitrary termination condition.
Parameters
integrator Numerical integrator that is used for propagation. Upon input to this function, the integrator is at the final time/state encountered by the propagation
propagationTerminationCondition Termination condition that is to be used
timeStep Last time step taken by integrator.
dependentVariableFunction Function returning dependent variables (obtained from environment and state derivative model).
solutionHistory History of state variables that are to be saved given as map (time as key; returned by reference)
dependentVariableHistory History of dependent variables that are to be saved given as map (time as key; returned by reference)
currentCpuTime Current run time of propagation.
Definition at line 354 of file integrateEquations.h.
References getFinalStateForExactTerminationCondition().
Referenced by integrateEquationsFromIntegrator().
integrateEquationsFromIntegrator()
template<typename StateType = Eigen::MatrixXd, typename TimeType = double, typename TimeStepType = TimeType> std::shared_ptr< PropagationTerminationDetails > tudat::propagators::integrateEquationsFromIntegrator (const std::shared_ptr< numerical_integrators::NumericalIntegrator< TimeType, StateType, StateType, TimeStepType > > integrator, const TimeStepType initialTimeStep, const std::shared_ptr< PropagationTerminationCondition > propagationTerminationCondition, std::map< TimeType, StateType > & solutionHistory, std::map< TimeType, Eigen::VectorXd > & dependentVariableHistory, std::map< TimeType, double > & cumulativeComputationTimeHistory, const std::function< Eigen::VectorXd() > dependentVariableFunction = std::function< Eigen::VectorXd() >(), const std::function< void(StateType &) > statePostProcessingFunction = std::function< void(StateType&) >(), const int saveFrequency = TUDAT_NAN, const TimeType printInterval = TUDAT_NAN, const std::chrono::steady_clock::time_point initialClockTime = std::chrono::steady_clock::now())
Function to numerically integrate a given first order differential equation, with the state derivative a function of a single independent variable and the current state
Parameters
integrator Numerical integrator used for propagation
initialTimeStep Time step to use for first step of numerical integration
propagationTerminationCondition Object to determine when/how the propagation is to be stopped at the current time.
solutionHistory History of state variables that are to be saved given as map (time as key; returned by reference)
dependentVariableHistory History of dependent variables that are to be saved given as map (time as key; returned by reference)
cumulativeComputationTimeHistory History of cumulative computation times that are to be saved given as map (time as key; returned by reference)
dependentVariableFunction Function returning dependent variables (obtained from environment and state derivative model).
statePostProcessingFunction Function to post-process state after numerical integration (obtained from state derivative model).
saveFrequency Frequency at which to save the numerical integrated states (in units of i.e. per n integration time steps, with n = saveFrequency).
printInterval Frequency with which to print progress to console (nan = never).
initialClockTime Initial clock time from which to determine cumulative computation time. By default now(), i.e. the moment at which this function is called.
Returns
Event that triggered the termination of the propagation
Definition at line 445 of file integrateEquations.h.
References hybrid_stopping_condition, nan_or_inf_detected_in_state, propagateToExactTerminationCondition(), runtime_error_caught_in_propagation, termination_condition_reached, TUDAT_NAN, and unknown_propagation_termination_reason.
calculateEnckeQFunction()
template<typename StateScalarType = double> StateScalarType tudat::propagators::calculateEnckeQFunction (const StateScalarType qValue)
Function to calculate Encke's function, to be used during propagation using Encke's method
Parameters
qValue Value of free parameter in Encke's function (typically denoted as q)
Returns
value of Encke's function for given free parameter.
Definition at line 36 of file nBodyEnckeStateDerivative.h.
Referenced by tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative().
computeGaussPlanetaryEquationsForKeplerElements() [1/3]
Eigen::Vector6d tudat::propagators::computeGaussPlanetaryEquationsForKeplerElements (const Eigen::Vector6d & currentOsculatingKeplerElements, const Eigen::Vector3d & accelerationsInRswFrame, const double semiLatusRectum, const double distance, const double meanMotion, const double orbitalAngularMomentum)
Function to evaluate the Gauss planetary equations for Kepler elements, providing the time-derivatives of the Kepler elements from the accelerations expressed in an RSW frame (see Vallado, 2001). This function takes a number of precomputed quantities as input, to reduce computational burden
Parameters
currentOsculatingKeplerElements Current osculating Kepler elements of the body for which the Gauss equations are to be evaluated
accelerationsInRswFrame Accelerations acting on body, expressed in RSW frame
semiLatusRectum Semi-latus rectum of osculating orbit
distance Distance from propagated body to its central body
meanMotion Instantaneous mean motion of body w.r.t. its central body
orbitalAngularMomentum Norm of orbital angular momentum vector of body, w.r.t. its central body
Returns
Time derivatives of osculating Kepler elements.
Definition at line 20 of file nBodyGaussKeplerStateDerivative.cpp.
References tudat::input_output::field_types::state::eccentricity, tudat::input_output::field_types::state::inclination, and tudat::input_output::field_types::state::semiMajorAxis.
Referenced by tudat::propagators::NBodyGaussKeplerStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), and computeGaussPlanetaryEquationsForKeplerElements().
computeGaussPlanetaryEquationsForKeplerElements() [2/3]
Eigen::Vector6d tudat::propagators::computeGaussPlanetaryEquationsForKeplerElements (const Eigen::Vector6d & currentOsculatingKeplerElements, const Eigen::Vector3d & accelerationsInRswFrame, const double centralBodyGravitationalParameter)
Function to evaluate the Gauss planetary equations for Kepler elements, providing the time-derivatives of the Kepler elements from the accelerations expressed in an RSW frame (see Vallado, 2001).
Parameters
currentOsculatingKeplerElements Current osculating Kepler elements of the body for which the Gauss equations are to be evaluated
accelerationsInRswFrame Accelerations acting on body, expressed in RSW frame
centralBodyGravitationalParameter Gravitational parameter of sum of central body and body for which orbit is propagated.
Returns
Time derivatives of osculating Kepler elements.
Definition at line 76 of file nBodyGaussKeplerStateDerivative.cpp.
References computeGaussPlanetaryEquationsForKeplerElements(), tudat::basic_astrodynamics::computeKeplerMeanMotion(), tudat::orbital_element_conversions::computeOrbitalAngularMomentumPerUnitMass(), tudat::orbital_element_conversions::computeSemiLatusRectum(), and tudat::input_output::field_types::state::meanMotion.
computeGaussPlanetaryEquationsForKeplerElements() [3/3]
Eigen::Vector6d tudat::propagators::computeGaussPlanetaryEquationsForKeplerElements (const Eigen::Vector6d & currentOsculatingKeplerElements, const Eigen::Vector6d & currentCartesianState, const Eigen::Vector3d & accelerationsInInertialFrame, const double centralBodyGravitationalParameter)
Function to evaluate the Gauss planetary equations for Kepler elements, providing the time-derivatives of the Kepler elements from the accelerations expressed in an RSW frame (see Vallado, 2001). This function takes the accelerations in the inertial frame, as well as the Cartesian inertial state, and converts the accelerations to the RSW frame.
Parameters
currentOsculatingKeplerElements Current osculating Kepler elements of the body for which the Gauss equations are to be evaluated
currentCartesianState Current Cartesian state of the body for which the Gauss equations are to be evaluated
accelerationsInInertialFrame Accelerations acting on body, expressed in inertial frame
centralBodyGravitationalParameter Gravitational parameter of sum of central body and body for which orbit is propagated.
Returns
Time derivatives of osculating Kepler elements.
Definition at line 100 of file nBodyGaussKeplerStateDerivative.cpp.
References computeGaussPlanetaryEquationsForKeplerElements(), and tudat::reference_frames::getInertialToRswSatelliteCenteredFrameRotationMatrix().
computeGaussPlanetaryEquationsForModifiedEquinoctialElements()
Eigen::Vector6d tudat::propagators::computeGaussPlanetaryEquationsForModifiedEquinoctialElements (const Eigen::Vector6d & osculatingModifiedEquinoctialElements, const Eigen::Vector3d & accelerationsInRswFrame, const double centralBodyGravitationalParameter)
Function to evaluate the Gauss planetary equations for modified equinictial elements, providing the time-derivatives of the modified equinictial elements from the accelerations expressed in an RSW frame (see Vallado, 2001).
Parameters
osculatingModifiedEquinoctialElements Current osculating modified equinoctial elements of the body for which the Gauss equations are to be evaluated
accelerationsInRswFrame Accelerations acting on body, expressed in RSW frame
centralBodyGravitationalParameter Gravitational parameter of sum of central body and body for which orbit is propagated.
Returns
Time derivatives of osculating dified equinictial elements.
Definition at line 20 of file nBodyGaussModifiedEquinoctialStateDerivative.cpp.
References tudat::orbital_element_conversions::fElementIndex, tudat::orbital_element_conversions::gElementIndex, tudat::orbital_element_conversions::hElementIndex, tudat::orbital_element_conversions::kElementIndex, tudat::orbital_element_conversions::semiParameterIndex, and tudat::orbital_element_conversions::trueLongitudeIndex.
Referenced by tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative().
removeCentralGravityAccelerations()
std::vector< std::function< double() > > tudat::propagators::removeCentralGravityAccelerations (const std::vector< std::string > & centralBodies, const std::vector< std::string > & bodiesToIntegrate, basic_astrodynamics::AccelerationMap & accelerationModelsPerBody)
Function to remove the central gravity acceleration from an AccelerationMap. This is crucial for propagation methods in which the deviation from a reference Kepler orbit is propagated. If the central gravity is a spherical harmonic acceleration, the point mass term is removed by setting the C(0,0) coefficnet to 0
Parameters
bodiesToIntegrate List of names of bodies that are to be integrated numerically.
centralBodies List of names of bodies of which the central terms are to be removed (per entry of bodiesToIntegrate)
accelerationModelsPerBody A map containing the list of accelerations acting on each body, identifying the body being acted on and the body acted on by an acceleration. The map has as key a string denoting the name of the body the list of accelerations, provided as the value corresponding to a key, is acting on. This map-value is again a map with string as key, denoting the body exerting the acceleration, and as value a pointer to an acceleration model.
Returns
Functions returning the gravitational parameters of the central terms that were removed.
Definition at line 20 of file nBodyStateDerivative.cpp.
References tudat::basic_astrodynamics::central_gravity, tudat::basic_astrodynamics::getAccelerationModelType(), tudat::basic_astrodynamics::spherical_harmonic_gravity, tudat::basic_astrodynamics::third_body_central_gravity, and tudat::basic_astrodynamics::third_body_spherical_harmonic_gravity.
Referenced by tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::NBodyEnckeStateDerivative(), tudat::propagators::NBodyGaussKeplerStateDerivative< StateScalarType, TimeType >::NBodyGaussKeplerStateDerivative(), tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::NBodyGaussModifiedEquinictialStateDerivative(), tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::NBodyUnifiedStateModelExponentialMapStateDerivative(), tudat::propagators::NBodyUnifiedStateModelModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >::NBodyUnifiedStateModelModifiedRodriguesParametersStateDerivative(), and tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::NBodyUnifiedStateModelQuaternionsStateDerivative().
determineEphemerisUpdateorder()
std::vector< std::string > tudat::propagators::determineEphemerisUpdateorder (std::vector< std::string > integratedBodies, std::vector< std::string > centralBodies, std::vector< std::string > ephemerisOrigins)
Function to determine in which order the ephemerides are to be updated. The order depends on the dependencies between the ephemeris/integration origins.
Parameters
integratedBodies List of bodies that are numerically integrated.
centralBodies List of origins w.r.t. the integratedBodies' translational dynamics is propagated.
ephemerisOrigins Origin of the Ephemeris objects of the integratedBodies.
Returns
Definition at line 135 of file nBodyStateDerivative.cpp.
Referenced by tudat::propagators::VariationalEquations::setTranslationalStatePartialFrameScalingFunctions(), and tudat::propagators::TranslationalStateIntegratedStateProcessor< TimeType, StateScalarType >::TranslationalStateIntegratedStateProcessor().
computeStateDerivativeForUnifiedStateModelExponentialMap() [1/3]
Eigen::Vector7d tudat::propagators::computeStateDerivativeForUnifiedStateModelExponentialMap (const Eigen::Vector7d & currentUnifiedStateModelElements, const Eigen::Vector3d & accelerationsInRswFrame, const double sineLambdaParameter, const double cosineLambdaParameter, const double gammaParameter, const Eigen::Vector3d & rotationalVelocityVector, const Eigen::Vector3d & pParameterVector)
Function to evaluate the equations of motion for the unifies state model with exponential map (USMEM)
Function to evaluate the equations of motion for the unifies state model with exponential map (USMEM), providing the time-derivatives of USMEM elements from the accelerations expressed in an RSW frame (see Vallado, 2001). This function takes a number of precomputed quantities as input, to reduce computational burden
Parameters
currentUnifiedStateModelElements Current USMEM elements of the body for which the equations of motion are to be evaluated
accelerationsInRswFrame Accelerations acting on body, expressed in RSW frame
sineLambdaParameter Sine of the right ascension of latitude
cosineLambdaParameter Cosine of the right ascension of latitude
gammaParameter Value of the parameter gamma (see Vittaldev, 2010)
rotationalVelocityVector Rotational velocity of the local orbital frame w.r.t. the inertial frame (see Vittaldev, 2010)
pParameterVector Value of the vector gamma (see Vittaldev, 2010)
Returns
Time derivatives of USMEM elements.
Definition at line 27 of file nBodyUnifiedStateModelExponentialMapStateDerivative.cpp.
References calculateExponentialMapDerivative().
Referenced by tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), and computeStateDerivativeForUnifiedStateModelExponentialMap().
computeStateDerivativeForUnifiedStateModelExponentialMap() [2/3]
Eigen::Vector7d tudat::propagators::computeStateDerivativeForUnifiedStateModelExponentialMap (const Eigen::Vector7d & currentUnifiedStateModelElements, const Eigen::Vector3d & accelerationsInRswFrame, const double centralBodyGravitationalParameter)
Function to evaluate the equations of motion for the unifies state model with exponential map (USMEM)
Function to evaluate the equations of motion for the unifies state model with exponential map (USMEM), providing the time-derivatives of USMEM elements from the accelerations expressed in an RSW frame (see Vallado, 2001).
Parameters
currentUnifiedStateModelElements Current USMEM elements of the body for which the equations of motion are to be evaluated
accelerationsInRswFrame Accelerations acting on body, expressed in RSW frame
centralBodyGravitationalParameter Gravitational parameter of sum of central body and body for which orbit is propagated.
Returns
Time derivatives of USMEM elements.
Definition at line 57 of file nBodyUnifiedStateModelExponentialMapStateDerivative.cpp.
References tudat::orbital_element_conversions::CHodographUSMEMIndex, computeStateDerivativeForUnifiedStateModelExponentialMap(), tudat::orbital_element_conversions::convertExponentialMapToQuaternionElements(), tudat::orbital_element_conversions::e1USMEMIndex, tudat::orbital_element_conversions::epsilon1QuaternionIndex, tudat::orbital_element_conversions::etaQuaternionIndex, tudat::orbital_element_conversions::Rf1HodographUSMEMIndex, and tudat::orbital_element_conversions::Rf2HodographUSMEMIndex.
computeStateDerivativeForUnifiedStateModelExponentialMap() [3/3]
Eigen::Vector7d tudat::propagators::computeStateDerivativeForUnifiedStateModelExponentialMap (const Eigen::Vector7d & currentUnifiedStateModelElements, const Eigen::Vector6d & currentCartesianState, const Eigen::Vector3d & accelerationsInInertialFrame, const double centralBodyGravitationalParameter)
Function to evaluate the equations of motion for the unifies state model with exponential map (USMEM)
Function to evaluate the equations of motion for the unifies state model with exponential map (USMEM), providing the time-derivatives of USMEM elements from the accelerations expressed in an RSW frame (see Vallado, 2001). This function takes the accelerations in the inertial frame, as well as the Cartesian inertial state, and converts the accelerations to the RSW frame.
Parameters
currentUnifiedStateModelElements Current USMEM elements of the body for which the equations of motion are to be evaluated
currentCartesianState Current Cartesian state of the body for which the equations of motion are to be evaluated
accelerationsInInertialFrame Accelerations acting on body, expressed in inertial frame
centralBodyGravitationalParameter Gravitational parameter of sum of central body and body for which orbit is propagated.
Returns
Time derivatives of USMEM elements.
Definition at line 98 of file nBodyUnifiedStateModelExponentialMapStateDerivative.cpp.
References computeStateDerivativeForUnifiedStateModelExponentialMap(), and tudat::reference_frames::getInertialToRswSatelliteCenteredFrameRotationMatrix().
computeStateDerivativeForUnifiedStateModelModifiedRodriguesParameters() [1/3]
Eigen::Vector7d tudat::propagators::computeStateDerivativeForUnifiedStateModelModifiedRodriguesParameters (const Eigen::Vector7d & currentUnifiedStateModelElements, const Eigen::Vector3d & accelerationsInRswFrame, const double sineLambdaParameter, const double cosineLambdaParameter, const double gammaParameter, const Eigen::Vector3d & rotationalVelocityVector, const Eigen::Vector3d & pParameterVector)
Function to evaluate the equations of motion for the unifies state model with modified rodrigues parameters (USM6)
Function to evaluate the equations of motion for the unifies state model with modified rodrigues parameters (USM6), providing the time-derivatives of USM6 elements from the accelerations expressed in an RSW frame (see Vallado, 2001). This function takes a number of precomputed quantities as input, to reduce computational burden
Parameters
currentUnifiedStateModelElements Current USM6 elements of the body for which the equations of motion are to be evaluated
accelerationsInRswFrame Accelerations acting on body, expressed in RSW frame
sineLambdaParameter Sine of the right ascension of latitude
cosineLambdaParameter Cosine of the right ascension of latitude
gammaParameter Value of the parameter gamma (see Vittaldev, 2010)
rotationalVelocityVector Rotational velocity of the local orbital frame w.r.t. the inertial frame (see Vittaldev, 2010)
pParameterVector Value of the vector gamma (see Vittaldev, 2010)
Returns
Time derivatives of USM6 elements.
Definition at line 22 of file nBodyUnifiedStateModelModifiedRodriguesParametersStateDerivative.cpp.
References calculateModifiedRodriguesParametersDerivative().
Referenced by tudat::propagators::NBodyUnifiedStateModelModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), and computeStateDerivativeForUnifiedStateModelModifiedRodriguesParameters().
computeStateDerivativeForUnifiedStateModelModifiedRodriguesParameters() [2/3]
Eigen::Vector7d tudat::propagators::computeStateDerivativeForUnifiedStateModelModifiedRodriguesParameters (const Eigen::Vector7d & currentUnifiedStateModelElements, const Eigen::Vector3d & accelerationsInRswFrame, const double centralBodyGravitationalParameter)
Function to evaluate the equations of motion for the unifies state model with modified rodrigues parameters (USM6)
Function to evaluate the equations of motion for the unifies state model with modified rodrigues parameters (USM6), providing the time-derivatives of USM6 elements from the accelerations expressed in an RSW frame (see Vallado, 2001).
Parameters
currentUnifiedStateModelElements Current USM6 elements of the body for which the equations of motion are to be evaluated
accelerationsInRswFrame Accelerations acting on body, expressed in RSW frame
centralBodyGravitationalParameter Gravitational parameter of sum of central body and body for which orbit is propagated.
Returns
Time derivatives of USM6 elements.
Definition at line 52 of file nBodyUnifiedStateModelModifiedRodriguesParametersStateDerivative.cpp.
References tudat::orbital_element_conversions::CHodographUSM6Index, computeStateDerivativeForUnifiedStateModelModifiedRodriguesParameters(), tudat::orbital_element_conversions::Rf1HodographUSM6Index, tudat::orbital_element_conversions::Rf2HodographUSM6Index, and tudat::orbital_element_conversions::sigma1USM6Index.
computeStateDerivativeForUnifiedStateModelModifiedRodriguesParameters() [3/3]
Eigen::Vector7d tudat::propagators::computeStateDerivativeForUnifiedStateModelModifiedRodriguesParameters (const Eigen::Vector7d & currentUnifiedStateModelElements, const Eigen::Vector6d & currentCartesianState, const Eigen::Vector3d & accelerationsInInertialFrame, const double centralBodyGravitationalParameter)
Function to evaluate the equations of motion for the unifies state model with modified rodrigues parameters (USM6)
Function to evaluate the equations of motion for the unifies state model with modified rodrigues parameters (USM6), providing the time-derivatives of USM6 elements from the accelerations expressed in an RSW frame (see Vallado, 2001). This function takes the accelerations in the inertial frame, as well as the Cartesian inertial state, and converts the accelerations to the RSW frame.
Parameters
currentUnifiedStateModelElements Current USM6 elements of the body for which the equations of motion are to be evaluated
currentCartesianState Current Cartesian state of the body for which the equations of motion are to be evaluated
accelerationsInInertialFrame Accelerations acting on body, expressed in inertial frame
centralBodyGravitationalParameter Gravitational parameter of sum of central body and body for which orbit is propagated.
Returns
Time derivatives of USM6 elements.
Definition at line 111 of file nBodyUnifiedStateModelModifiedRodriguesParametersStateDerivative.cpp.
References computeStateDerivativeForUnifiedStateModelModifiedRodriguesParameters(), and tudat::reference_frames::getInertialToRswSatelliteCenteredFrameRotationMatrix().
computeStateDerivativeForUnifiedStateModelQuaternions() [1/3]
Eigen::Vector7d tudat::propagators::computeStateDerivativeForUnifiedStateModelQuaternions (const Eigen::Vector7d & currentUnifiedStateModelElements, const Eigen::Vector3d & accelerationsInRswFrame, const double sineLambdaParameter, const double cosineLambdaParameter, const double gammaParameter, const Eigen::Vector3d & rotationalVelocityVector, const Eigen::Vector3d & pParameterVector)
Function to evaluate the equations of motion for the unifies state model with quaternions (USM7)
Function to evaluate the equations of motion for the unifies state model with quaternions (USM7), providing the time-derivatives of USM7 elements from the accelerations expressed in an RSW frame (see Vallado, 2001). This function takes a number of precomputed quantities as input, to reduce computational burden
Parameters
currentUnifiedStateModelElements Current USM7 elements of the body for which the equations of motion are to be evaluated
accelerationsInRswFrame Accelerations acting on body, expressed in RSW frame
sineLambdaParameter Sine of the right ascension of latitude
cosineLambdaParameter Cosine of the right ascension of latitude
gammaParameter Value of the parameter gamma (see Vittaldev, 2010)
rotationalVelocityVector Rotational velocity of the local orbital frame w.r.t. the inertial frame (see Vittaldev, 2010)
pParameterVector Value of the vector gamma (see Vittaldev, 2010)
Returns
Time derivatives of USM7 elements.
Definition at line 22 of file nBodyUnifiedStateModelQuaternionsStateDerivative.cpp.
References calculateQuaternionDerivative().
Referenced by tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), and computeStateDerivativeForUnifiedStateModelQuaternions().
computeStateDerivativeForUnifiedStateModelQuaternions() [2/3]
Eigen::Vector7d tudat::propagators::computeStateDerivativeForUnifiedStateModelQuaternions (const Eigen::Vector7d & currentUnifiedStateModelElements, const Eigen::Vector3d & accelerationsInRswFrame, const double centralBodyGravitationalParameter)
Function to evaluate the equations of motion for the unifies state model with quaternions (USM7)
Function to evaluate the equations of motion for the unifies state model with quaternions (USM7), providing the time-derivatives of USM7 elements from the accelerations expressed in an RSW frame (see Vallado, 2001).
Parameters
currentUnifiedStateModelElements Current USM7 elements of the body for which the equations of motion are to be evaluated
accelerationsInRswFrame Accelerations acting on body, expressed in RSW frame
centralBodyGravitationalParameter Gravitational parameter of sum of central body and body for which orbit is propagated.
Returns
Time derivatives of USM7 elements.
Definition at line 52 of file nBodyUnifiedStateModelQuaternionsStateDerivative.cpp.
References tudat::orbital_element_conversions::CHodographUSM7Index, computeStateDerivativeForUnifiedStateModelQuaternions(), tudat::orbital_element_conversions::epsilon1USM7Index, tudat::orbital_element_conversions::epsilon2USM7Index, tudat::orbital_element_conversions::epsilon3USM7Index, tudat::orbital_element_conversions::etaUSM7Index, tudat::orbital_element_conversions::Rf1HodographUSM7Index, and tudat::orbital_element_conversions::Rf2HodographUSM7Index.
computeStateDerivativeForUnifiedStateModelQuaternions() [3/3]
Eigen::Vector7d tudat::propagators::computeStateDerivativeForUnifiedStateModelQuaternions (const Eigen::Vector7d & currentUnifiedStateModelElements, const Eigen::Vector6d & currentCartesianState, const Eigen::Vector3d & accelerationsInInertialFrame, const double centralBodyGravitationalParameter)
Function to evaluate the equations of motion for the unifies state model with quaternions (USM7)
Function to evaluate the equations of motion for the unifies state model with quaternions (USM7), providing the time-derivatives of USM7 elements from the accelerations expressed in an RSW frame (see Vallado, 2001). This function takes the accelerations in the inertial frame, as well as the Cartesian inertial state, and converts the accelerations to the RSW frame.
Parameters
currentUnifiedStateModelElements Current USM7 elements of the body for which the equations of motion are to be evaluated
currentCartesianState Current Cartesian state of the body for which the equations of motion are to be evaluated
accelerationsInInertialFrame Accelerations acting on body, expressed in inertial frame
centralBodyGravitationalParameter Gravitational parameter of sum of central body and body for which orbit is propagated.
Returns
Time derivatives of USM7 elements.
Definition at line 93 of file nBodyUnifiedStateModelQuaternionsStateDerivative.cpp.
References computeStateDerivativeForUnifiedStateModelQuaternions(), and tudat::reference_frames::getInertialToRswSatelliteCenteredFrameRotationMatrix().
getFullVariationalEquationsSolutionHistory() [1/2]
void tudat::propagators::getFullVariationalEquationsSolutionHistory (std::map< double, Eigen::MatrixXd > & fullVariationalEquationsSolutionHistory, const std::shared_ptr< CombinedStateTransitionAndSensitivityMatrixInterface > stateTransitionInterface, const std::vector< double > evaluationTimes)
Function to retrueve full state transition and sensitivity matrices at epochs from associated interface object
Parameters
fullVariationalEquationsSolutionHistory List of combined state transition and sensitivity matrices, given at the epochs where the state covariance is to be computed
stateTransitionInterface Object that is used to obtain state transition and sensitivity matrices
evaluationTimes Times at which the variational equations are to be evaluated
Definition at line 11 of file propagateCovariance.cpp.
Referenced by getFullVariationalEquationsSolutionHistory(), and propagateCovariance().
getFullVariationalEquationsSolutionHistory() [2/2]
void tudat::propagators::getFullVariationalEquationsSolutionHistory (std::map< double, Eigen::MatrixXd > & fullVariationalEquationsSolutionHistory, const std::shared_ptr< CombinedStateTransitionAndSensitivityMatrixInterface > stateTransitionInterface, const double timeStep, const double initialTime, const double finalTime)
Function to retrueve full state transition and sensitivity matrices at epochs from associated interface object
Parameters
fullVariationalEquationsSolutionHistory List of combined state transition and sensitivity matrices, given at the epochs where the state covariance is to be computed
stateTransitionInterface Object that is used to obtain state transition and sensitivity matrices
timeStep Time step with which full state transition and sensitivity matrices is to be provided
initialTime Initial time at which full state transition and sensitivity matrices is to be provided
finalTime Final time at which full state transition and sensitivity matrices is to be provided
Definition at line 24 of file propagateCovariance.cpp.
References getFullVariationalEquationsSolutionHistory().
propagateCovariance() [1/3]
void tudat::propagators::propagateCovariance (std::map< double, Eigen::MatrixXd > & propagatedCovariance, const Eigen::MatrixXd & initialCovariance, const std::map< double, Eigen::MatrixXd > & fullVariationalEquationsSolutionHistory)
Function to propagate full covariance at the initial time to state covariance at later times
Parameters
propagatedCovariance List of state covariances at epochs (returned by reference)
initialCovariance Full covariance at initial time
fullVariationalEquationsSolutionHistory List of combined state transition and sensitivity matrices, given at the epochs where the state covariance is to be computed
Definition at line 44 of file propagateCovariance.cpp.
Referenced by propagateCovariance(), and propagateFormalErrors().
propagateCovariance() [2/3]
void tudat::propagators::propagateCovariance (std::map< double, Eigen::MatrixXd > & propagatedCovariance, const Eigen::MatrixXd & initialCovariance, const std::shared_ptr< CombinedStateTransitionAndSensitivityMatrixInterface > stateTransitionInterface, const std::vector< double > evaluationTimes)
Function to propagate full covariance at the initial time to state covariance at later times
Parameters
propagatedCovariance List of state covariances at epochs (returned by reference)
initialCovariance Full covariance at initial time
stateTransitionInterface Object that is used to obtain state transition and sensitivity matrices
evaluationTimes Times at which the covariance is to be evaluated
Definition at line 58 of file propagateCovariance.cpp.
References getFullVariationalEquationsSolutionHistory(), and propagateCovariance().
propagateCovariance() [3/3]
void tudat::propagators::propagateCovariance (std::map< double, Eigen::MatrixXd > & propagatedCovariance, const Eigen::MatrixXd & initialCovariance, const std::shared_ptr< CombinedStateTransitionAndSensitivityMatrixInterface > stateTransitionInterface, const double timeStep, const double initialTime, const double finalTime)
Function to propagate full covariance at the initial time to state covariance at later times
Parameters
propagatedCovariance List of state covariances at epochs (returned by reference)
initialCovariance Full covariance at initial time
stateTransitionInterface Object that is used to obtain state transition and sensitivity matrices
timeStep Time step with which covariance is to be provided
initialTime Initial time at which covariance is to be provided
finalTime Final time at which covariance is to be provided
Definition at line 77 of file propagateCovariance.cpp.
References propagateCovariance().
propagateFormalErrors() [1/2]
void tudat::propagators::propagateFormalErrors (std::map< double, Eigen::VectorXd > & propagatedFormalErrors, const Eigen::MatrixXd & initialCovariance, const std::shared_ptr< CombinedStateTransitionAndSensitivityMatrixInterface > stateTransitionInterface, const std::vector< double > evaluationTimes)
Function to propagate full covariance at the initial time to state formal errors at later times
Parameters
propagatedFormalErrors List of state formal errors at epochs (returned by reference)
initialCovariance Full covariance at initial time
stateTransitionInterface Object that is used to obtain state transition and sensitivity matrices
evaluationTimes Times at which the covariance is to be evaluated
Definition at line 98 of file propagateCovariance.cpp.
References propagateCovariance().
propagateFormalErrors() [2/2]
void tudat::propagators::propagateFormalErrors (std::map< double, Eigen::VectorXd > & propagatedFormalErrors, const Eigen::MatrixXd & initialCovariance, const std::shared_ptr< CombinedStateTransitionAndSensitivityMatrixInterface > stateTransitionInterface, const double timeStep, const double initialTime, const double finalTime)
Function to propagate full covariance at the initial time to state formal errors at later times
Parameters
propagatedFormalErrors List of state formal errors at epochs (returned by reference)
initialCovariance Full covariance at initial time
stateTransitionInterface Object that is used to obtain state transition and sensitivity matrices
timeStep Time step with which formal errors is to be provided
initialTime Initial time at which formal errors is to be provided
finalTime Final time at which formal errors is to be provided
Definition at line 116 of file propagateCovariance.cpp.
References propagateCovariance().
calculateExponentialMapDerivative()
Eigen::Vector4d tudat::propagators::calculateExponentialMapDerivative (const Eigen::Vector4d & currentExponentialMapToBaseFrame, const Eigen::Vector3d & angularVelocityVectorInBodyFixedFrame)
Function to obtain the time derivative of an exponential map (in vector representation) of body-fixed to inertial frame.
Function to obtain the time derivative of an exponential map (in vector representation) of body-fixed to inertial frame
Parameters
currentExponentialMapToBaseFrame ExponentialMap (in vector representation) that define the rotation from body-fixed to inertial frame.
angularVelocityVectorInBodyFixedFrame Current angular velocity vector of body, expressed in its body-fixed frame
Returns
Time derivative of an exponential map (in vector representation) of body-fixed to inertial frame
Definition at line 21 of file rotationalMotionExponentialMapStateDerivative.cpp.
Referenced by tudat::propagators::RotationalMotionExponentialMapStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), and computeStateDerivativeForUnifiedStateModelExponentialMap().
calculateModifiedRodriguesParametersDerivative()
Eigen::Vector4d tudat::propagators::calculateModifiedRodriguesParametersDerivative (const Eigen::Vector4d & currentModiefiedRodriguesParametersToBaseFrame, const Eigen::Vector3d & angularVelocityVectorInBodyFixedFrame)
Function to obtain the time derivative of modified Rodrigues parameters (in vector representation) of body-fixed to inertial frame.
Function to obtain the time derivative of modified Rodrigues parameters (in vector representation) of body-fixed to inertial frame.
Parameters
currentModiefiedRodriguesParametersToBaseFrame Modified Rodrigues parameters (in vector representation) that define the rotation from body-fixed to inertial frame.
angularVelocityVectorInBodyFixedFrame Current angular velocity vector of body, expressed in its body-fixed frame
Returns
Time derivative of modified Rodrigues parameters (in vector representation) of body-fixed to inertial frame
Definition at line 21 of file rotationalMotionModifiedRodriguesParametersStateDerivative.cpp.
References tudat::linear_algebra::getCrossProductMatrix().
Referenced by tudat::propagators::RotationalMotionModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), and computeStateDerivativeForUnifiedStateModelModifiedRodriguesParameters().
getQuaterionToQuaternionRateMatrix()
Eigen::Matrix4d tudat::propagators::getQuaterionToQuaternionRateMatrix (const Eigen::Vector3d & angularVelocityVectorInBodyFixedFrame)
Function to obtain the matrix by which a quaternion vector is to be pre-multiplied to obtain this quaternion's time-derivative.
Function to obtain the matrix by which a quaternion vector is to be pre-multiplied to obtain this quaternion's time-derivative.
Parameters
angularVelocityVectorInBodyFixedFrame Current angular velocity vector of body, expressed in its body-fixed frame.
Returns
Matrix by which a quaternion vector (representing body-fixed to inertial frame rotation) is to be pre-multiplied to obtain this quaternion's time-derivative.
Definition at line 22 of file rotationalMotionQuaternionsStateDerivative.cpp.
Referenced by calculateQuaternionDerivative(), and tudat::propagators::VariationalEquations::setBodyStatePartialMatrix().
getAngularVelocityToQuaternionRateMatrix()
Eigen::Matrix< double, 4, 3 > tudat::propagators::getAngularVelocityToQuaternionRateMatrix (const Eigen::Vector4d & quaternionVector)
Function to obtain the matrix by which an angular velocity vector is to be pre-multiplied to obtain the quaternion's time-derivative.
Function to obtain the matrix by which an angular velocity vector is to be pre-multiplied to obtain the quaternion's time-derivative.
Parameters
quaternionVector Current quaternion vector, representing body-fixed to inertial frame rotation.
Returns
Matrix by which an angular velocity vector of body (expressed in its body-fixed frame) is to be pre-multiplied to obtain the quaternion's time-derivative.
Definition at line 48 of file rotationalMotionQuaternionsStateDerivative.cpp.
Referenced by tudat::propagators::VariationalEquations::setBodyStatePartialMatrix().
calculateQuaternionDerivative()
Eigen::Vector4d tudat::propagators::calculateQuaternionDerivative (const Eigen::Vector4d & currentQuaternionsToBaseFrame, const Eigen::Vector3d & angularVelocityVectorInBodyFixedFrame)
Function to obtain the time derivative of a quaternion (in vector representation) of body-fixed to inertial frame.
Function to obtain the time derivative of a quaternion (in vector representation) of body-fixed to inertial frame
Parameters
currentQuaternionsToBaseFrame Quaternions (in vector representation) that define the rotation from body-fixed to inertial frame.
angularVelocityVectorInBodyFixedFrame Current angular velocity vector of body, expressed in its body-fixed frame
Returns
Time derivative of a quaternion (in vector representation) of body-fixed to inertial frame
Definition at line 72 of file rotationalMotionQuaternionsStateDerivative.cpp.
References getQuaterionToQuaternionRateMatrix().
Referenced by tudat::propagators::RotationalMotionQuaternionsStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), and computeStateDerivativeForUnifiedStateModelQuaternions().
evaluateRotationalEquationsOfMotion()
Eigen::Vector3d tudat::propagators::evaluateRotationalEquationsOfMotion (const Eigen::Matrix3d & inertiaTensor, const Eigen::Vector3d & totalTorque, const Eigen::Vector3d & angularVelocityVector, const Eigen::Matrix3d & inertiaTensorTimeDerivative = Eigen::Matrix3d::Zero())
Function to evaluated the classical rotational equations of motion (Euler equations). The function returns the time-derivative of a body's angular velocity vector, expressed in its body-fixed frame
Parameters
inertiaTensor Inertia tensor of body, expressed in its body-fixed frame
totalTorque Total torque acting on body, expressed in its body-fixed frame
angularVelocityVector Current angular velocity vector of body, expressed in its body-fixed frame
inertiaTensorTimeDerivative Time derivative of inertiaTensor (default zero)
Returns
Time-derivative of a body's angular velocity vector, expressed in its body-fixed frame
Definition at line 20 of file rotationalMotionStateDerivative.cpp.
Referenced by tudat::propagators::RotationalMotionModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), tudat::propagators::RotationalMotionExponentialMapStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), and tudat::propagators::RotationalMotionQuaternionsStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative().
getSingleIntegrationSize()
int tudat::propagators::getSingleIntegrationSize (const IntegratedStateType stateType)
Get size of state for single propagated state of given type (i.e. 6 for translational state).
Parameters
stateType Type of state
Returns
Size of single state.
Definition at line 19 of file singleStateTypeDerivative.cpp.
References body_mass_state, rotational_state, and translational_state.
Referenced by tudat::json_interface::determineInitialStates(), tudat::propagators::VariationalEquations::getParameterPartialMatrix(), tudat::propagators::VariationalEquations::setBodyStatePartialMatrix(), tudat::propagators::VariationalEquations::setStatePartialFunctionList(), tudat::propagators::VariationalEquations::setTranslationalStatePartialFrameScalingFunctions(), tudat::propagators::VariationalEquations::VariationalEquations(), and tudat::orbit_determination::StateDerivativePartial::wrtParameter().
getSingleIntegrationDifferentialEquationOrder()
int tudat::propagators::getSingleIntegrationDifferentialEquationOrder (const IntegratedStateType stateType)
Get order of differential equation for governing equations of dynamics of given type (i.e. 2 for translational state).
Parameters
stateType Type of state
Returns
Order of differential equations.
Definition at line 42 of file singleStateTypeDerivative.cpp.
References body_mass_state, rotational_state, and translational_state.
getGeneralizedAccelerationSize()
int tudat::propagators::getGeneralizedAccelerationSize (const IntegratedStateType stateType)
Function to get the size of the generalized acceleration (e.g. acceleration for translational dynamics, torque for rotational dynamics, mass rate for mass) for a given state type
Parameters
stateType State type for which generalized acceleration size is to be determined
Returns
Generalized acceleration size
Definition at line 65 of file singleStateTypeDerivative.cpp.
References body_mass_state, rotational_state, and translational_state.
Referenced by tudat::propagators::VariationalEquations::getParameterPartialMatrix(), tudat::propagators::VariationalEquations::setBodyStatePartialMatrix(), tudat::orbit_determination::StateDerivativePartial::StateDerivativePartial(), and tudat::orbit_determination::StateDerivativePartial::wrtParameter().
to_json() [1/11]
void tudat::propagators::to_json (nlohmann::json & jsonObject, const IntegratedStateType & integratedStateType) inline
Definition at line 279 of file propagator.h.
References tudat::json_interface::stringFromEnum().
Referenced by from_json(), and tudat::json_interface::to_json().
from_json() [1/11]
void tudat::propagators::from_json (const nlohmann::json & jsonObject, IntegratedStateType & integratedStateType) inline
Definition at line 285 of file propagator.h.
References tudat::json_interface::enumFromString().
Referenced by from_json().
to_json() [2/11]
void tudat::propagators::to_json (nlohmann::json & jsonObject, const TranslationalPropagatorType & translationalPropagatorType) inline
Definition at line 309 of file propagator.h.
References tudat::json_interface::stringFromEnum().
from_json() [2/11]
void tudat::propagators::from_json (const nlohmann::json & jsonObject, TranslationalPropagatorType & translationalPropagatorType) inline
Definition at line 315 of file propagator.h.
References tudat::json_interface::enumFromString().
to_json() [3/11]
void tudat::propagators::to_json (nlohmann::json & jsonObject, const RotationalPropagatorType & rotationalPropagatorType) inline
Definition at line 335 of file propagator.h.
References tudat::json_interface::stringFromEnum().
from_json() [3/11]
void tudat::propagators::from_json (const nlohmann::json & jsonObject, RotationalPropagatorType & rotationalPropagatorType) inline
Definition at line 341 of file propagator.h.
References tudat::json_interface::enumFromString().
to_json() [4/11]
template<typename StateScalarType > void tudat::propagators::to_json (nlohmann::json & jsonObject, const std::shared_ptr< MultiTypePropagatorSettings< StateScalarType > > & multiTypePropagatorSettings)
Definition at line 351 of file propagator.h.
References tudat::json_interface::getFlattenedMapValues(), tudat::json_interface::isNaN(), tudat::json_interface::Keys::options, tudat::json_interface::Keys::Options::printInterval, tudat::json_interface::Keys::propagators, and tudat::json_interface::Keys::termination.
from_json() [4/11]
template<typename StateScalarType > void tudat::propagators::from_json (const nlohmann::json & jsonObject, std::shared_ptr< MultiTypePropagatorSettings< StateScalarType > > & multiTypePropagatorSettings)
Definition at line 374 of file propagator.h.
References tudat::json_interface::Keys::finalEpoch, tudat::json_interface::isDefined(), tudat::json_interface::Keys::options, tudat::json_interface::Keys::Options::printInterval, tudat::json_interface::Keys::propagators, tudat::json_interface::Keys::termination, and TUDAT_NAN.
to_json() [5/11]
template<typename StateScalarType > void tudat::propagators::to_json (nlohmann::json & jsonObject, const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > & singleArcPropagatorSettings)
Definition at line 448 of file propagator.h.
References tudat::json_interface::assertNonnullptrPointer(), body_mass_state, tudat::json_interface::getFlattenedMapValues(), tudat::json_interface::handleUnimplementedEnumValue(), hybrid, tudat::json_interface::isNaN(), tudat::json_interface::Keys::options, tudat::json_interface::Keys::Options::printInterval, tudat::json_interface::Keys::propagators, rotational_state, tudat::json_interface::Keys::termination, and translational_state.
from_json() [5/11]
template<typename StateScalarType > void tudat::propagators::from_json (const nlohmann::json & jsonObject, std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > & singleArcPropagatorSettings)
Definition at line 539 of file propagator.h.
References body_mass_state, tudat::json_interface::getValue(), tudat::json_interface::handleUnimplementedEnumValue(), hybrid, tudat::propagators::RotationalStatePropagatorSettings< StateScalarType >::propagator_, rotational_state, translational_state, and TUDAT_NAN.
to_json() [6/11]
void tudat::propagators::to_json (nlohmann::json & jsonObject, const std::shared_ptr< PropagationHybridTerminationSettings > & hybridTerminationSettings)
Definition at line 25 of file termination.cpp.
from_json() [6/11]
void tudat::propagators::from_json (const nlohmann::json & jsonObject, std::shared_ptr< PropagationHybridTerminationSettings > & hybridTerminationSettings)
Definition at line 40 of file termination.cpp.
References tudat::json_interface::isDefined().
to_json() [7/11]
void tudat::propagators::to_json (nlohmann::json & jsonObject, const std::shared_ptr< PropagationTerminationSettings > & terminationSettings)
Definition at line 66 of file termination.cpp.
References tudat::json_interface::assertNonnullptrPointer(), tudat::propagators::PropagationCPUTimeTerminationSettings::cpuTerminationTime_, cpuTimeVariable, independentVariable, and tudat::propagators::PropagationTimeTerminationSettings::terminationTime_.
from_json() [7/11]
void tudat::propagators::from_json (const nlohmann::json & jsonObject, std::shared_ptr< PropagationTerminationSettings > & terminationSettings)
Definition at line 116 of file termination.cpp.
References tudat::json_interface::assertNonnullptrPointer(), cpuTimeVariable, dependentVariable, getVariableId(), independentVariable, and tudat::json_interface::isDefined().
to_json() [8/11]
void tudat::propagators::to_json (nlohmann::json & jsonObject, const std::shared_ptr< VariableSettings > & variableSettings)
Create a json object from a shared pointer to a VariableSettings object.
Definition at line 28 of file variable.cpp.
References cpuTimeVariable, dependentVariable, tudat::json_interface::handleUnimplementedEnumValue(), independentVariable, sensitivityMatrix, stateTransitionMatrix, stateVariable, unsupportedVariableTypes, and variableTypes.
from_json() [8/11]
void tudat::propagators::from_json (const nlohmann::json & jsonObject, std::shared_ptr< VariableSettings > & variableSettings)
Definition at line 69 of file variable.cpp.
References cpuTimeVariable, dependentVariable, tudat::json_interface::handleUnimplementedEnumValue(), independentVariable, sensitivityMatrix, stateTransitionMatrix, stateVariable, unsupportedVariableTypes, and variableTypes.
to_json() [9/11]
void tudat::propagators::to_json (nlohmann::json & jsonObject, const std::shared_ptr< SingleDependentVariableSaveSettings > & dependentVariableSettings)
Definition at line 111 of file variable.cpp.
References acceleration_partial_wrt_body_translational_state, tudat::json_interface::assertNonnullptrPointer(), tudat::json_interface::assignIfNotEmpty(), intermediate_aerodynamic_rotation_matrix_variable, relative_body_aerodynamic_orientation_angle_variable, single_acceleration_dependent_variable, single_acceleration_norm_dependent_variable, single_gravity_field_variation_acceleration, single_gravity_field_variation_acceleration_terms, single_torque_dependent_variable, single_torque_norm_dependent_variable, spherical_harmonic_acceleration_norm_terms_dependent_variable, and spherical_harmonic_acceleration_terms_dependent_variable.
from_json() [9/11]
void tudat::propagators::from_json (const nlohmann::json & jsonObject, std::shared_ptr< SingleDependentVariableSaveSettings > & dependentVariableSettings)
Definition at line 228 of file variable.cpp.
References acceleration_partial_wrt_body_translational_state, intermediate_aerodynamic_rotation_matrix_variable, relative_body_aerodynamic_orientation_angle_variable, single_acceleration_dependent_variable, single_acceleration_norm_dependent_variable, single_gravity_field_variation_acceleration, single_gravity_field_variation_acceleration_terms, single_torque_dependent_variable, single_torque_norm_dependent_variable, spherical_harmonic_acceleration_norm_terms_dependent_variable, and spherical_harmonic_acceleration_terms_dependent_variable.
to_json() [10/11]
void tudat::propagators::to_json (nlohmann::json & jsonObject, const VariableType & variableType) inline
Definition at line 41 of file variable.h.
References tudat::json_interface::stringFromEnum().
from_json() [10/11]
void tudat::propagators::from_json (const nlohmann::json & jsonObject, VariableType & variableType) inline
Definition at line 47 of file variable.h.
References tudat::json_interface::enumFromString().
to_json() [11/11]
void tudat::propagators::to_json (nlohmann::json & jsonObject, const PropagationDependentVariables & dependentVariable) inline
Definition at line 111 of file variable.h.
References tudat::json_interface::stringFromEnum().
from_json() [11/11]
void tudat::propagators::from_json (const nlohmann::json & jsonObject, PropagationDependentVariables & dependentVariable) inline
Definition at line 117 of file variable.h.
References tudat::json_interface::enumFromString(), from_json(), and to_json().
createStateTransitionAndSensitivityMatrixInterpolator()
void tudat::propagators::createStateTransitionAndSensitivityMatrixInterpolator (std::shared_ptr< interpolators::OneDimensionalInterpolator< double, Eigen::MatrixXd > > & stateTransitionMatrixInterpolator, std::shared_ptr< interpolators::OneDimensionalInterpolator< double, Eigen::MatrixXd > > & sensitivityMatrixInterpolator, std::vector< std::map< double, Eigen::MatrixXd > > & variationalEquationsSolution, const bool clearRawSolution = 1)
Function to create interpolators for state transition and sensitivity matrices from numerical results.
Parameters
stateTransitionMatrixInterpolator Interpolator object for state transition matrix (returned by reference).
sensitivityMatrixInterpolator Interpolator object for sensitivity matrix (returned by reference).
variationalEquationsSolution Vector of two matrix histories. First vector entry is state transition matrix history, second entry is sensitivity matrix history.
clearRawSolution Boolean denoting whether to clear entries of variationalEquationsSolution after creation of interpolators.
Definition at line 35 of file variationalEquationsSolver.cpp.
Referenced by tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::resetVariationalEquationsInterpolators(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::resetVariationalEquationsInterpolators(), and setVariationalEquationsSolution().
setVariationalEquationsSolution()
template<typename TimeType , typename StateScalarType > void tudat::propagators::setVariationalEquationsSolution (std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > & numericalIntegrationResult, std::vector< std::map< double, Eigen::MatrixXd > > & variationalEquationsSolution, const std::pair< int, int > stateTransitionStartIndices, const std::pair< int, int > sensitivityStartIndices, const int stateTransitionMatrixSize, const int parameterSetSize)
Function to separate the time histories of the sensitivity and state transition matrices from a full numerical solution, in which the solution is represented as a single matrix block per time value. NOTE: numericalIntegrationResult contents are deleted by this function (all information is conserved in variationalEquationsSolution.
Parameters
numericalIntegrationResult Full time history from which separate matrix histories are to be retrieved.
variationalEquationsSolution Vector of two matrix histories (returned by reference). First vector entry is state transition matrix history, second entry is sensitivity matrix history.
stateTransitionStartIndices First row and column (first and second) of state transition matrix in entries of numericalIntegrationResult.
sensitivityStartIndices First row and column (first and second) of sensitivity matrix in entries of numericalIntegrationResult.
stateTransitionMatrixSize Size (rows and columns are equal) of state transition matrix.
parameterSetSize Number of rows in sensitivity matrix
Definition at line 231 of file variationalEquationsSolver.h.
References createStateTransitionAndSensitivityMatrixInterpolator().
Referenced by tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations().
checkPropagatorSettingsAndParameterEstimationConsistency()
template<typename StateScalarType = double, typename TimeType = double> bool tudat::propagators::checkPropagatorSettingsAndParameterEstimationConsistency (const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate)
Function to check the consistency between propagation settings of equations of motion, and estimated parameters. In particular, it is presently required that the set of propagated states is equal to the set of estimated states.
Parameters
propagatorSettings Settings for propagation of equations of motion.
parametersToEstimate Object containing all parameters that are to be estimated and their current settings and values.
Returns
True if settings are consistent
Definition at line 291 of file variationalEquationsSolver.h.
References tudat::propagators::TranslationalStatePropagatorSettings< StateScalarType >::bodiesToIntegrate_, tudat::propagators::RotationalStatePropagatorSettings< StateScalarType >::bodiesToIntegrate_, tudat::estimatable_parameters::getListOfBodiesWithRotationalStateToEstimate(), tudat::estimatable_parameters::getListOfBodiesWithTranslationalStateToEstimate(), hybrid, rotational_state, and translational_state.
checkMultiArcPropagatorSettingsAndParameterEstimationConsistency()
template<typename StateScalarType = double, typename TimeType = double> bool tudat::propagators::checkMultiArcPropagatorSettingsAndParameterEstimationConsistency (const std::shared_ptr< MultiArcPropagatorSettings< StateScalarType > > propagatorSettings, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate, const std::vector< double > arcStartTimes)
Function to check the consistency between multi-arc propagation settings of equations of motion, and estimated parameters. In particular, it is presently required that the set of propagated states is equal to the set of estimated states.
Parameters
propagatorSettings Settings for propagation of equations of motion.
parametersToEstimate Object containing all parameters that are to be estimated and their current settings and values.
arcStartTimes Times at which the dynamics arcs start
Returns
True if settings are consistent
Definition at line 430 of file variationalEquationsSolver.h.
References tudat::propagators::TranslationalStatePropagatorSettings< StateScalarType >::bodiesToIntegrate_, tudat::estimatable_parameters::getListOfBodiesWithTranslationalMultiArcStateToEstimate(), and translational_state.
Referenced by tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::MultiArcVariationalEquationsSolver().
setPropagatorSettingsMultiArcStatesInEstimatedDynamicalParameters()
template<typename StateScalarType = double> void tudat::propagators::setPropagatorSettingsMultiArcStatesInEstimatedDynamicalParameters (const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate, const std::shared_ptr< MultiArcPropagatorSettings< StateScalarType > > propagatorSettings)
Function to transfer the initial multi-arc states from propagator settings to associated initial state estimation parameters.
Parameters
parametersToEstimate Full set of estimated parameters to which the initial states are to be transferred
propagatorSettings Multi-arc propagator settings from which the initial states are to be taken
Definition at line 952 of file variationalEquationsSolver.h.
References tudat::utilities::createVectorFromMapKeys(), tudat::estimatable_parameters::getListOfBodiesWithTranslationalMultiArcStateToEstimate(), and translational_state.
Referenced by tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations().
checkValidityOfRequiredEnvironmentUpdates()
void tudat::propagators::checkValidityOfRequiredEnvironmentUpdates (const std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > & requestedUpdates, const simulation_setup::NamedBodyMap & bodyMap)
Function to check whether the requested environment updates are possible with the existing environment.
Function to check whether the requested environment updates are possible with the existing environment, i.e. if all environment models that are to be updated exist in the bodyMap. The function throws an error if environment cannot be updated as requested.,
Parameters
requestedUpdates List of environment updates that are required
bodyMap List of body objects used in the simulations.
Definition at line 23 of file createEnvironmentUpdater.cpp.
References body_mass_update, body_rotational_state_update, body_translational_state_update, radiation_pressure_interface_update, spherical_harmonic_gravity_field_update, and vehicle_flight_conditions_update.
Referenced by createEnvironmentUpdaterSettings(), and createFullEnvironmentUpdaterSettings().
removePropagatedStatesFomEnvironmentUpdates()
void tudat::propagators::removePropagatedStatesFomEnvironmentUpdates (std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > & environmentModelsToUpdate, const std::map< IntegratedStateType, std::vector< std::pair< std::string, std::string > > > & integratedStateList)
Function that removes propagated states from the updated environment variables
Parameters
environmentModelsToUpdate List of environment models to be updated, this data structure is modified by this function and returned by reference
integratedStateList List of states that are numerically integrated.
Definition at line 129 of file createEnvironmentUpdater.cpp.
References body_mass_state, body_mass_update, body_rotational_state_update, body_translational_state_update, custom_state, rotational_state, and translational_state.
Referenced by createEnvironmentUpdaterSettings().
createRotationalEquationsOfMotionEnvironmentUpdaterSettings()
std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > tudat::propagators::createRotationalEquationsOfMotionEnvironmentUpdaterSettings (const basic_astrodynamics::TorqueModelMap & torqueModels, const simulation_setup::NamedBodyMap & bodyMap)
Get list of required environment model update settings from torque models.
Parameters
torqueModels List of torque models used in simulation.
bodyMap List of body objects used in the simulations.
Returns
List of required environment model update settings.
Definition at line 201 of file createEnvironmentUpdater.cpp.
References addEnvironmentUpdates(), tudat::basic_astrodynamics::aerodynamic_torque, body_rotational_state_update, body_translational_state_update, tudat::basic_astrodynamics::getTorqueModelType(), tudat::basic_astrodynamics::inertial_torque, tudat::basic_astrodynamics::second_order_gravitational_torque, tudat::basic_astrodynamics::spherical_harmonic_gravitational_torque, spherical_harmonic_gravity_field_update, and vehicle_flight_conditions_update.
Referenced by createEnvironmentUpdaterSettings().
createTranslationalEquationsOfMotionEnvironmentUpdaterSettings()
std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > tudat::propagators::createTranslationalEquationsOfMotionEnvironmentUpdaterSettings (const basic_astrodynamics::AccelerationMap & translationalAccelerationModels, const simulation_setup::NamedBodyMap & bodyMap)
Get list of required environment model update settings from translational acceleration models.
Parameters
translationalAccelerationModels List of acceleration models used in simulation.
bodyMap List of body objects used in the simulations.
Returns
List of required environment model update settings.
Definition at line 268 of file createEnvironmentUpdater.cpp.
References addEnvironmentUpdates(), tudat::basic_astrodynamics::aerodynamic, body_mass_update, body_rotational_state_update, body_translational_state_update, tudat::basic_astrodynamics::cannon_ball_radiation_pressure, tudat::basic_astrodynamics::central_gravity, tudat::basic_astrodynamics::direct_tidal_dissipation_in_central_body_acceleration, tudat::basic_astrodynamics::direct_tidal_dissipation_in_orbiting_body_acceleration, tudat::basic_astrodynamics::empirical_acceleration, tudat::basic_astrodynamics::getAccelerationModelType(), tudat::relativity::RelativisticAccelerationCorrection::getPrimaryBodyName(), tudat::basic_astrodynamics::momentum_wheel_desaturation_acceleration, tudat::basic_astrodynamics::mutual_spherical_harmonic_gravity, tudat::basic_astrodynamics::panelled_radiation_pressure_acceleration, radiation_pressure_interface_update, tudat::basic_astrodynamics::relativistic_correction_acceleration, tudat::basic_astrodynamics::solar_sail_acceleration, tudat::basic_astrodynamics::spherical_harmonic_gravity, spherical_harmonic_gravity_field_update, tudat::basic_astrodynamics::third_body_central_gravity, tudat::basic_astrodynamics::third_body_mutual_spherical_harmonic_gravity, tudat::basic_astrodynamics::third_body_spherical_harmonic_gravity, tudat::basic_astrodynamics::thrust_acceleration, and vehicle_flight_conditions_update.
Referenced by createEnvironmentUpdaterSettings().
createMassPropagationEnvironmentUpdaterSettings()
std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > tudat::propagators::createMassPropagationEnvironmentUpdaterSettings (const std::map< std::string, std::vector< std::shared_ptr< basic_astrodynamics::MassRateModel > > > massRateModels, const simulation_setup::NamedBodyMap & bodyMap)
Get list of required environment model update settings from mass rate models.
Parameters
massRateModels List of mass rate models used in simulation.
bodyMap List of body objects used in the simulations.
Returns
List of required environment model update settings.
Definition at line 499 of file createEnvironmentUpdater.cpp.
References addEnvironmentUpdates(), tudat::basic_astrodynamics::custom_mass_rate_model, tudat::basic_astrodynamics::from_thrust_mass_rate_model, and tudat::basic_astrodynamics::getMassRateModelType().
Referenced by createEnvironmentUpdaterSettings().
checkAndModifyEnvironmentForDependentVariableSaving()
void tudat::propagators::checkAndModifyEnvironmentForDependentVariableSaving (const EnvironmentModelsToUpdate updateType, const std::shared_ptr< SingleDependentVariableSaveSettings > dependentVariableSaveSettings, const simulation_setup::NamedBodyMap & bodyMap)
Function to update environment to allow all required updates to be made. It checks whether a flight conditions object needs to be updated, and creates a FlightConditions object for the associated body if it is not.
Parameters
updateType List of environment models that are to be updated
dependentVariableSaveSettings Dependent variables that are to be saved
bodyMap List of body objects that comprises the environment (updated by function if needed).
Definition at line 544 of file createEnvironmentUpdater.cpp.
References tudat::simulation_setup::createAtmosphericFlightConditions(), tudat::simulation_setup::createFlightConditions(), and vehicle_flight_conditions_update.
Referenced by createEnvironmentUpdaterSettingsForDependentVariables().
createEnvironmentUpdaterSettingsForDependentVariables()
std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > tudat::propagators::createEnvironmentUpdaterSettingsForDependentVariables (const std::shared_ptr< SingleDependentVariableSaveSettings > dependentVariableSaveSettings, const simulation_setup::NamedBodyMap & bodyMap)
Function to create environment update settings for a single dependent variable
Parameters
dependentVariableSaveSettings Settings for single dependent variable
bodyMap List of body objects that comprises the environment
Returns
List of required environment model updates.
Definition at line 582 of file createEnvironmentUpdater.cpp.
References acceleration_partial_wrt_body_translational_state, aerodynamic_force_coefficients_dependent_variable, aerodynamic_moment_coefficients_dependent_variable, airspeed_dependent_variable, altitude_dependent_variable, body_fixed_airspeed_based_velocity_variable, body_fixed_groundspeed_based_velocity_variable, body_fixed_relative_cartesian_position, body_fixed_relative_spherical_position, body_mass_update, body_rotational_state_update, body_translational_state_update, checkAndModifyEnvironmentForDependentVariableSaving(), control_surface_deflection_dependent_variable, current_body_mass_dependent_variable, euler_angles_to_body_fixed_313, geodetic_latitude_dependent_variable, intermediate_aerodynamic_rotation_matrix_variable, keplerian_state_dependent_variable, local_aerodynamic_heat_rate_dependent_variable, local_density_dependent_variable, local_dynamic_pressure_dependent_variable, local_temperature_dependent_variable, lvlh_to_inertial_frame_rotation_dependent_variable, mach_number_dependent_variable, modified_equinocial_state_dependent_variable, periapsis_altitude_dependent_variable, radiation_pressure_coefficient_dependent_variable, radiation_pressure_dependent_variable, radiation_pressure_interface_update, relative_body_aerodynamic_orientation_angle_variable, relative_distance_dependent_variable, relative_position_dependent_variable, relative_speed_dependent_variable, relative_velocity_dependent_variable, rotation_matrix_to_body_fixed_frame_variable, single_acceleration_dependent_variable, single_acceleration_norm_dependent_variable, single_gravity_field_variation_acceleration, single_gravity_field_variation_acceleration_terms, single_torque_dependent_variable, single_torque_norm_dependent_variable, spherical_harmonic_acceleration_norm_terms_dependent_variable, spherical_harmonic_acceleration_terms_dependent_variable, stagnation_point_heat_flux_dependent_variable, total_acceleration_dependent_variable, total_acceleration_norm_dependent_variable, total_aerodynamic_g_load_variable, total_gravity_field_variation_acceleration, total_mass_rate_dependent_variables, total_torque_dependent_variable, total_torque_norm_dependent_variable, and vehicle_flight_conditions_update.
Referenced by createEnvironmentUpdaterSettings().
createEnvironmentUpdaterSettings() [1/3]
std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > tudat::propagators::createEnvironmentUpdaterSettings (const std::shared_ptr< DependentVariableSaveSettings > dependentVariableSaveSettings, const simulation_setup::NamedBodyMap & bodyMap)
Create environment update settings for dependent variables
Parameters
dependentVariableSaveSettings Settings for dependent variables
bodyMap List of body objects that comprises the environment
Returns
List of required environment model updates.
Definition at line 815 of file createEnvironmentUpdater.cpp.
References addEnvironmentUpdates(), and createEnvironmentUpdaterSettingsForDependentVariables().
Referenced by createEnvironmentUpdaterSettings().
createEnvironmentUpdaterSettings() [2/3]
std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > tudat::propagators::createEnvironmentUpdaterSettings (const std::shared_ptr< PropagationTerminationSettings > terminationSettings, const simulation_setup::NamedBodyMap & bodyMap)
Create environment update settings for termination settings
Parameters
terminationSettings Settings for propagation termination
bodyMap List of body objects that comprises the environment
Returns
List of required environment model updates.
Definition at line 836 of file createEnvironmentUpdater.cpp.
References addEnvironmentUpdates(), cpu_time_stopping_condition, createEnvironmentUpdaterSettings(), createEnvironmentUpdaterSettingsForDependentVariables(), custom_stopping_condition, dependent_variable_stopping_condition, hybrid_stopping_condition, and time_stopping_condition.
createFullEnvironmentUpdaterSettings()
std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > tudat::propagators::createFullEnvironmentUpdaterSettings (const simulation_setup::NamedBodyMap & bodyMap)
Function to create 'brute-force' update settings, in which each environment model (i.e. each member of the Body objects that can be updated) is updated.
Parameters
bodyMap List of body objects used in the simulations.
Returns
List of environment model updates, so that each updatable model is updated.
Definition at line 882 of file createEnvironmentUpdater.cpp.
References addEnvironmentUpdates(), body_mass_update, body_rotational_state_update, checkValidityOfRequiredEnvironmentUpdates(), createEnvironmentUpdaterForDynamicalEquations< double, double >(), createEnvironmentUpdaterSettings< double >(), radiation_pressure_interface_update, spherical_harmonic_gravity_field_update, and vehicle_flight_conditions_update.
Referenced by createEnvironmentUpdaterSettings().
createEnvironmentUpdaterForDynamicalEquations< double, double >()
template std::shared_ptr< propagators::EnvironmentUpdater< double, double > > tudat::propagators::createEnvironmentUpdaterForDynamicalEquations< double, double > (const std::shared_ptr< SingleArcPropagatorSettings< double > > propagatorSettings, const simulation_setup::NamedBodyMap & bodyMap)
Referenced by createEnvironmentUpdaterForDynamicalEquations(), and createFullEnvironmentUpdaterSettings().
createEnvironmentUpdaterSettings< double >()
template std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > tudat::propagators::createEnvironmentUpdaterSettings< double > (const std::shared_ptr< SingleArcPropagatorSettings< double > > propagatorSettings, const simulation_setup::NamedBodyMap & bodyMap, const bool isPartOfMultiTypePropagation)
Referenced by createEnvironmentUpdaterForDynamicalEquations(), and createFullEnvironmentUpdaterSettings().
createEnvironmentUpdaterSettings() [3/3]
template<typename StateScalarType > std::map< propagators::EnvironmentModelsToUpdate,std::vector< std::string > > tudat::propagators::createEnvironmentUpdaterSettings (const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings, const simulation_setup::NamedBodyMap & bodyMap, const bool isPartOfMultiTypePropagation = false)
Get list of required environment model update settings from a list of propagation settings.
Parameters
propagatorSettings Object providing the full settings for the dynamics that are to be propagated.
bodyMap List of body objects used in the simulations.
isPartOfMultiTypePropagation Boolean denoting whether propagation uses multiple types of dynamics
Returns
List of updates required when propagating dynamics defined by propagatorSettings.
Definition at line 147 of file createEnvironmentUpdater.h.
References addEnvironmentUpdates(), body_mass_state, checkValidityOfRequiredEnvironmentUpdates(), createEnvironmentUpdaterSettings(), createFullEnvironmentUpdaterSettings(), createMassPropagationEnvironmentUpdaterSettings(), createRotationalEquationsOfMotionEnvironmentUpdaterSettings(), createTranslationalEquationsOfMotionEnvironmentUpdaterSettings(), custom_state, getIntegratedTypeAndBodyList(), hybrid, removePropagatedStatesFomEnvironmentUpdates(), rotational_state, and translational_state.
createEnvironmentUpdaterForDynamicalEquations()
template<typename StateScalarType , typename TimeType > std::shared_ptr< propagators::EnvironmentUpdater< StateScalarType, TimeType > > tudat::propagators::createEnvironmentUpdaterForDynamicalEquations (const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings, const simulation_setup::NamedBodyMap & bodyMap)
Get environment updater from a list of propagation settings.
Parameters
propagatorSettings Object providing the full settings for the dynamics that are to be propagated.
bodyMap List of body objects used in the simulations.
Returns
Object that updates the environment in bodyMap, as per thhe requirements set by propagatorSettings.
Definition at line 275 of file createEnvironmentUpdater.h.
References createEnvironmentUpdaterForDynamicalEquations< double, double >(), and createEnvironmentUpdaterSettings< double >().
createCR3BPIntegrator()
std::shared_ptr< numerical_integrators::NumericalIntegrator< double, Eigen::Vector6d > > tudat::propagators::createCR3BPIntegrator (const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const double massParameter, const Eigen::Vector6d & initialState)
Function to create an integrator to propagate the dynamics (in normalized units) in Circularly Restricted Three-Body Problem.
Parameters
integratorSettings Settings for the numerical integration
massParameter Normalized mass parameter
initialState Initial normalized state
Returns
Integrator object for propagation of CR3BP with requested settings
Definition at line 29 of file createStateDerivativeModel.cpp.
References tudat::propagators::StateDerivativeCircularRestrictedThreeBodyProblem::computeStateDerivative().
Referenced by createStateDerivativeModelMap(), and performCR3BPIntegration().
performCR3BPIntegration()
std::map< double, Eigen::Vector6d > tudat::propagators::performCR3BPIntegration (const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const double massParameter, const Eigen::Vector6d & initialState, const double finalTime, const bool propagateToExactFinalTime = false)
Function to propagate the dynamics (in normalized units) in Circularly Restricted Three-Body Problem.
Parameters
integratorSettings Settings for the numerical integration
massParameter Normalized mass parameter
initialState Initial normalized state
finalTime End time for the numerical integration
propagateToExactFinalTime Boolean denoting whether to terminate exactly on the final time (if true), or on the first step that exceeds the final time
Returns
Propagated state history of normalized dynamics in CR3BP.
Definition at line 47 of file createStateDerivativeModel.cpp.
References createCR3BPIntegrator().
Referenced by createStateDerivativeModelMap(), and propagateCR3BPFromEnvironment().
createCentralBodyData()
template<typename StateScalarType , typename TimeType > std::shared_ptr< CentralBodyData< StateScalarType, TimeType > > tudat::propagators::createCentralBodyData (const std::vector< std::string > & centralBodies, const std::vector< std::string > & bodiesToIntegrate, const simulation_setup::NamedBodyMap & bodyMap)
Function to create object handling frame origin transformations during numerical integration (needed by NBodyStateDerivative).
Parameters
centralBodies Names of central bodies, belonging to the entries in the bodiesToIntegrate vector of same index.
bodiesToIntegrate Names of bodies that are to be integrated numerically.
bodyMap List of body objects used in simulation.
Returns
Object handling frame origin transformations during numerical integration
Definition at line 55 of file createStateDerivativeModel.h.
References tudat::simulation_setup::getGlobalFrameOrigin(), and tudat::simulation_setup::Body::getStateInBaseFrameFromEphemeris().
createTranslationalStateDerivativeModel()
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > tudat::propagators::createTranslationalStateDerivativeModel (const std::shared_ptr< TranslationalStatePropagatorSettings< StateScalarType > > translationPropagatorSettings, const simulation_setup::NamedBodyMap & bodyMap, const TimeType propagationStartTime)
Function to create a translational state derivative model from propagation settings and environment.
Parameters
translationPropagatorSettings Settings for the translational dynamics model.
bodyMap List of body objects in the environment
propagationStartTime Time from which numerical propagation starts.
Returns
Translational state derivative model (instance of derived class of NBodyStateDerivative)
Definition at line 138 of file createStateDerivativeModel.h.
References cowell, encke, gauss_keplerian, gauss_modified_equinoctial, unified_state_model_exponential_map, unified_state_model_modified_rodrigues_parameters, and unified_state_model_quaternions.
createRotationalStateDerivativeModel()
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > tudat::propagators::createRotationalStateDerivativeModel (const std::shared_ptr< RotationalStatePropagatorSettings< StateScalarType > > rotationPropagatorSettings, const simulation_setup::NamedBodyMap & bodyMap, const TimeType startTime)
Function to create a rotational dynamics state derivative model from propagation settings and environment.
Parameters
rotationPropagatorSettings Settings for the rotational dynamics model.
bodyMap List of body objects in the environment
startTime Propagation start time
Returns
Rotational dynamics state derivative model.
Definition at line 263 of file createStateDerivativeModel.h.
References exponential_map, tudat::simulation_setup::Body::getBodyInertiaTensor(), modified_rodrigues_parameters, and quaternions.
createBodyMassStateDerivativeModel()
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > tudat::propagators::createBodyMassStateDerivativeModel (const std::shared_ptr< MassPropagatorSettings< StateScalarType > > massPropagatorSettings, const simulation_setup::NamedBodyMap & bodyMap)
Function to create a mass state derivative model from propagation settings and environment.
Parameters
massPropagatorSettings Settings for the mass dynamics model.
bodyMap List of body objects in the environment
Returns
Mass state derivative model.
Definition at line 316 of file createStateDerivativeModel.h.
createStateDerivativeModel()
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > tudat::propagators::createStateDerivativeModel (const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings, const simulation_setup::NamedBodyMap & bodyMap, const TimeType propagationStartTime)
Function to create a state derivative model from propagation settings and the environment.
Parameters
propagatorSettings Settings for the dynamical model.
bodyMap List of body objects in the environment
propagationStartTime Time from which numerical propagation starts.
Returns
State derivative model (instance of required derived class of SingleStateTypeDerivative)
Definition at line 335 of file createStateDerivativeModel.h.
References body_mass_state, custom_state, rotational_state, and translational_state.
setMultiTypePropagationClosure()
template<typename StateScalarType = double> void tudat::propagators::setMultiTypePropagationClosure (const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings, const simulation_setup::NamedBodyMap & bodyMap)
Function that finalized multi-type propagator creation by ensuring that any mutual dependencies are correctly set
Parameters
propagatorSettings Settings for the numerical propagation
bodyMap List of body objects that comprises the environment
Definition at line 432 of file createStateDerivativeModel.h.
References tudat::basic_astrodynamics::aerodynamic, tudat::propagators::RotationalStatePropagatorSettings< StateScalarType >::bodiesToIntegrate_, tudat::basic_astrodynamics::getAccelerationModelType(), tudat::propagators::TranslationalStatePropagatorSettings< StateScalarType >::getAccelerationsMap(), tudat::simulation_setup::Body::getCurrentRotationToLocalFrame(), tudat::propagators::MultiTypePropagatorSettings< StateScalarType >::propagatorSettingsMap_, rotational_state, tudat::reference_frames::setAerodynamicDependentOrientationCalculatorClosure(), and translational_state.
Referenced by createStateDerivativeModels().
createStateDerivativeModels()
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > tudat::propagators::createStateDerivativeModels (const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings, const simulation_setup::NamedBodyMap & bodyMap, const TimeType propagationStartTime)
Function to create a list of state derivative models from propagation settings and the environment.
Parameters
propagatorSettings Settings for the dynamical model.
bodyMap List of body objects in the environment.
propagationStartTime Time from which numerical propagation starts.
Returns
List of state derivative models (instances of required derived class of SingleStateTypeDerivative)
Definition at line 539 of file createStateDerivativeModel.h.
References hybrid, and setMultiTypePropagationClosure().
Referenced by createStateDerivativeModelMap(), and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::SingleArcVariationalEquationsSolver().
getStateDerivativeModelMapFromVector()
template<typename StateScalarType = double, typename TimeType = double> std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr<SingleStateTypeDerivative< StateScalarType, TimeType > > > > tudat::propagators::getStateDerivativeModelMapFromVector (const std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > & stateDerivativeModelList)
Function to convert a list of state derivative models to a map sorted by state type
Parameters
stateDerivativeModelList List of state derivative models
Returns
Map of state derivative models
Definition at line 635 of file createStateDerivativeModel.h.
Referenced by createStateDerivativeModelMap(), and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::SingleArcVariationalEquationsSolver().
createStateDerivativeModelMap()
template<typename StateScalarType = double, typename TimeType = double> std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr<SingleStateTypeDerivative< StateScalarType, TimeType > > > > tudat::propagators::createStateDerivativeModelMap (const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings, const simulation_setup::NamedBodyMap & bodyMap, const TimeType propagationStartTime)
Function to create a map of state derivative models from propagation settings and the environment.
Parameters
propagatorSettings Settings for the dynamical model.
bodyMap List of body objects in the environment.
propagationStartTime Time from which numerical propagation starts.
Returns
Map of state derivative models (instances of required derived class of SingleStateTypeDerivative)
Definition at line 661 of file createStateDerivativeModel.h.
References createCR3BPIntegrator(), createStateDerivativeModels(), getStateDerivativeModelMapFromVector(), and performCR3BPIntegration().
createFrameManager()
std::shared_ptr< ephemerides::ReferenceFrameManager > tudat::propagators::createFrameManager (const simulation_setup::NamedBodyMap & bodyMap)
Definition at line 21 of file dynamicsSimulator.cpp.
Referenced by getInitialRotationalStatesOfBodies(), getInitialStatesOfBodies(), tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::initializeHybridArcVariationalEquationsSolver(), tudat::simulation_setup::setGlobalFrameBodyEphemerides(), and tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::SingleArcDynamicsSimulator().
getInitialStatesOfBodiesFromFrameManager()
template<typename TimeType = double, typename StateScalarType = double> Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > tudat::propagators::getInitialStatesOfBodiesFromFrameManager (const std::vector< std::string > & bodiesToIntegrate, const std::vector< std::string > & centralBodies, const simulation_setup::NamedBodyMap & bodyMap, const TimeType initialTime, const std::shared_ptr< ephemerides::ReferenceFrameManager > frameManager)
Function to get the states of a set of bodies, w.r.t. some set of central bodies, at the requested time.
Parameters
bodiesToIntegrate List of bodies for which to retrieve state.
centralBodies Origins w.r.t. which to retrieve states of bodiesToIntegrate.
bodyMap List of bodies to use in simulations.
initialTime Time at which to retrieve states.
frameManager OBject with which to calculate frame origin translations.
Returns
Initial state vector (with 6 Cartesian elements per body, in order of bodiesToIntegrate vector).
Definition at line 50 of file dynamicsSimulator.h.
getInitialRotationalStatesOfBodies()
template<typename TimeType = double, typename StateScalarType = double> Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > tudat::propagators::getInitialRotationalStatesOfBodies (const std::vector< std::string > & bodiesToIntegrate, const std::vector< std::string > & baseOrientations, const simulation_setup::NamedBodyMap & bodyMap, const TimeType initialTime)
Function to get the rotational states states of a set of bodies, at the requested time.
Parameters
bodiesToIntegrate List of bodies for which to retrieve rotational state.
baseOrientations Reference base frame orientation
bodyMap List of bodies to use in simulations.
initialTime Time at which to retrieve states.
Returns
Initial rotational state vector (with 7 elements: 4 for quaternion; 3 for angular velocity) per body, in order of bodiesToIntegrate vector).
Definition at line 100 of file dynamicsSimulator.h.
References createFrameManager().
getInitialStatesOfBodies()
template<typename TimeType = double, typename StateScalarType = double> Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > tudat::propagators::getInitialStatesOfBodies (const std::vector< std::string > & bodiesToIntegrate, const std::vector< std::string > & centralBodies, const simulation_setup::NamedBodyMap & bodyMap, const TimeType initialTime)
Function to get the states of a set of bodies, w.r.t. some set of central bodies, at the requested time, creates frameManager from input data.
Parameters
bodiesToIntegrate List of bodies for which to retrieve state.
centralBodies Origins w.r.t. which to retrieve states of bodiesToIntegrate.
bodyMap List of bodies to use in simulations.
initialTime Time at which to retrieve states.
Returns
Initial state vector (with 6 Cartesian elements per body, in order of bodiesToIntegrate vector).
Definition at line 150 of file dynamicsSimulator.h.
References createFrameManager().
getInitialStateOfBody()
template<typename TimeType = double, typename StateScalarType = double> Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > tudat::propagators::getInitialStateOfBody (const std::string & bodyToIntegrate, const std::string & centralBody, const simulation_setup::NamedBodyMap & bodyMap, const TimeType initialTime)
Function to get the states of single body, w.r.t. some central body, at the requested time. This function creates frameManager from input data to perform all required conversions.
Parameters
bodyToIntegrate Body for which to retrieve state
centralBody Origin w.r.t. which to retrieve state of bodyToIntegrate.
bodyMap List of bodies to use in simulations.
initialTime Time at which to retrieve state.
Returns
Initial state vector of bodyToIntegrate
Definition at line 173 of file dynamicsSimulator.h.
Referenced by tudat::simulation_setup::createInitialDynamicalStateParameterToEstimate().
getInitialRotationalStateOfBody()
template<typename TimeType = double, typename StateScalarType = double> Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > tudat::propagators::getInitialRotationalStateOfBody (const std::string & bodyToIntegrate, const std::string & baseOrientation, const simulation_setup::NamedBodyMap & bodyMap, const TimeType initialTime)
Function to get the rotational states state of a body, at the requested time..
Parameters
bodyToIntegrate Body for which to retrieve rotational state.
baseOrientation Reference base frame orientation
bodyMap List of bodies to use in simulations.
initialTime Time at which to retrieve states.
Returns
Initial rotational state vector (with 7 elements: 4 for quaternion; 3 for angular velocity)
Definition at line 193 of file dynamicsSimulator.h.
Referenced by tudat::simulation_setup::createInitialDynamicalStateParameterToEstimate().
getInitialArcWiseStateOfBody()
template<typename TimeType = double, typename StateScalarType = double> Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > tudat::propagators::getInitialArcWiseStateOfBody (const std::string & bodyToIntegrate, const std::vector< std::string > & centralBodies, const simulation_setup::NamedBodyMap & bodyMap, const std::vector< TimeType > arcStartTimes)
Function to get the states of single body, w.r.t. some central body, at a set of requested times, concatanated into one vector. This function creates frameManager from input data to perform all required conversions.
Parameters
bodyToIntegrate Body for which to retrieve state
centralBodies Origins w.r.t. which to retrieve state of bodyToIntegrate (per arc).
bodyMap List of bodies to use in simulations.
arcStartTimes List of times at which to retrieve states.
Returns
Initial state vectosr of bodyToIntegrate at requested times.
Definition at line 215 of file dynamicsSimulator.h.
getInitialStatesPerArc()
template<typename StateScalarType = double> std::vector< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > tudat::propagators::getInitialStatesPerArc (const std::vector< std::shared_ptr< PropagatorSettings< StateScalarType > > > propagatorSettings)
Function to get a vector of initial states from a vector of propagator settings.
Parameters
propagatorSettings List of propagator settings
Returns
List of initial states, as retrieved from propagatorSettings list.
Definition at line 949 of file dynamicsSimulator.h.
getArcInitialStateFromPreviousArcResult()
template<typename StateScalarType = double, typename TimeType = double> Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > tudat::propagators::getArcInitialStateFromPreviousArcResult (const std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > & previousArcDynamicsSolution, const double currentArcInitialTime)
Function to get the initial state of a translational state arc from the previous state's numerical solution
Parameters
previousArcDynamicsSolution Numerical solution of previous arc
currentArcInitialTime Start time of current arc
Returns
Interpolated initial state of current arc
Definition at line 969 of file dynamicsSimulator.h.
Referenced by tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::integrateEquationsOfMotion(), and tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations().
setupBodySettingsCR3BP()
std::map< std::string, std::shared_ptr< simulation_setup::BodySettings > > tudat::propagators::setupBodySettingsCR3BP (const double distancePrimarySecondary, const std::string & namePrimaryBody, const std::string & nameSecondaryBody, const std::string & frameOrientation, const double primaryGravitationalParameter, const double secondaryGravitationalParameter)
Definition at line 23 of file propagationCR3BPFullProblem.cpp.
References tudat::circular_restricted_three_body_problem::computeMassParameter(), tudat::simulation_setup::createGravityFieldModel(), tudat::simulation_setup::getDefaultBodySettings(), tudat::simulation_setup::getDefaultGravityFieldSettings(), tudat::spice_interface::loadStandardSpiceKernels(), tudat::mathematical_constants::PI, tudat::orbital_element_conversions::semiMajorAxisIndex, tudat::orbital_element_conversions::trueAnomalyIndex, and TUDAT_NAN.
Referenced by setupBodyMapCR3BP().
setupBodyMapCR3BP()
simulation_setup::NamedBodyMap tudat::propagators::setupBodyMapCR3BP (const double distancePrimarySecondary, const std::string & namePrimaryBody, const std::string & nameSecondaryBody, const std::string & nameBodyToPropagate, const std::string & frameOrientation = "ECLIPJ2000", const double primaryGravitationalParameter = TUDAT_NAN, const double secondaryGravitationalParameter = TUDAT_NAN)
Setup CR3BP body map.
Setup CR3BP body map. The two primaries, as well as the third, smaller body to be propagated are defined in the body map. The two primaries are in circular orbit about their barycenter, orbiting it with the same mean motion, so that they stay aligned during propagation.
Parameters
distancePrimarySecondary Distance between primaries [m].
namePrimaryBody Name of the primary body.
nameSecondaryBody Name of the secondary body.
nameBodyToPropagate Name of the third, smaller body to be propagated.
frameOrientation Orientation of frame in which to propagate
primaryGravitationalParameter Gravitational parameter of primary
secondaryGravitationalParameter Gravitational parameter of secondary
Returns
Body Map modelling the CR3BP.
Definition at line 93 of file propagationCR3BPFullProblem.cpp.
References tudat::simulation_setup::createBodies(), tudat::simulation_setup::setGlobalFrameBodyEphemerides(), and setupBodySettingsCR3BP().
setupAccelerationMapCR3BP()
basic_astrodynamics::AccelerationMap tudat::propagators::setupAccelerationMapCR3BP (const std::string & namePrimaryBody, const std::string & nameSecondaryBody, const std::string & nameBodyToPropagate, const std::string & centralBody, const simulation_setup::NamedBodyMap & bodyMap)
Setup CR3BP acceleration map. Define the acceleration map for the CR3BP, from the corresponding body map. The only accelerations acting on the system are point-mass gravity from the two primaries.
Parameters
namePrimaryBody Name of the primary body.
nameSecondaryBody Name of the secondary body.
nameBodyToPropagate Name of the third, smaller body to be propagated.
centralBody Central bodys for the propagation.
bodyMap CR3BP body map.
Returns
Acceleration map for the CR3BP.
Definition at line 118 of file propagationCR3BPFullProblem.cpp.
References tudat::basic_astrodynamics::central_gravity, and tudat::simulation_setup::createAccelerationModelsMap().
propagateCR3BPFromEnvironment()
void tudat::propagators::propagateCR3BPFromEnvironment (const double initialTime, const double finalPropagationTime, const Eigen::Vector6d & initialState, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const simulation_setup::NamedBodyMap & bodyMap, const std::vector< std::string > & bodiesCR3BP, std::map< double, Eigen::Vector6d > & stateHistory, const bool outputInNormalizedCoordinates = false)
Propagate CR3BP from CR3BP environment.
Parameters
initialTime Initial time for the propagation [s].
finalPropagationTime Final time at which the propagation ends [s].
initialState Initial state of the third, smaller body to be propagated (Cartesian position in velocity in m and m/s)
integratorSettings Integrator settings for the propagation (the initial time and time-step have to be defined as dimensional times, their conversion to adimensional times is implemented within the function).
bodyMap Body map for the CR3BP.
bodiesCR3BP Name of the two primaries defining the CR3BP.
stateHistory Propagated states of the CR3BP (returned by reference)
outputInNormalizedCoordinates Boolean denoting whether output is to be in dimensionless quantities (if true)
Definition at line 144 of file propagationCR3BPFullProblem.cpp.
References tudat::circular_restricted_three_body_problem::computeMassParameter(), tudat::circular_restricted_three_body_problem::convertCartesianToCorotatingNormalizedCoordinates(), tudat::circular_restricted_three_body_problem::convertCorotatingNormalizedToCartesianCoordinates(), tudat::circular_restricted_three_body_problem::convertDimensionalTimeToDimensionlessTime(), tudat::circular_restricted_three_body_problem::convertDimensionlessTimeToDimensionalTime(), and performCR3BPIntegration().
Referenced by propagateCR3BPAndFullDynamicsProblem().
propagateCR3BPAndFullDynamicsProblem() [1/2]
void tudat::propagators::propagateCR3BPAndFullDynamicsProblem (const double initialTime, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > propagatorSettings, const simulation_setup::NamedBodyMap & bodyMap, const std::vector< std::string > & bodiesCR3BP, std::map< double, Eigen::Vector6d > & directPropagationResult, std::map< double, Eigen::Vector6d > & cr3bpPropagationResult, std::map< double, Eigen::VectorXd > & dependentVariableValues)
Definition at line 225 of file propagationCR3BPFullProblem.cpp.
References tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getDependentVariableHistory(), tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getEquationsOfMotionNumericalSolution(), and propagateCR3BPFromEnvironment().
Referenced by getFinalStateDifferenceFullPropagationWrtCR3BP(), and propagateCR3BPAndFullDynamicsProblem().
propagateCR3BPAndFullDynamicsProblem() [2/2]
void tudat::propagators::propagateCR3BPAndFullDynamicsProblem (const double initialTime, const double finalTime, const Eigen::Vector6d & initialState, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const basic_astrodynamics::AccelerationMap & accelerationModelMap, const std::vector< std::string > & bodiesToPropagate, const std::vector< std::string > & centralBodies, const simulation_setup::NamedBodyMap & bodyMap, const std::vector< std::string > & bodiesCR3BP, std::map< double, Eigen::Vector6d > & directPropagation, std::map< double, Eigen::Vector6d > & cr3bpPropagation)
Propagate the CR3BP and the full dynamics problem
Parameters
initialTime Initial time for the propagation [s].
finalTime Final time at which the propagation ends [s].
initialState Initial state of the third, smaller body to be propagated (Cartesian position in velocity in m and m/s)
integratorSettings Integrator settings for the propagation (the initial time and time-step have to be defined as dimensional times, their conversion to adimensional times is implemented within the function).
accelerationModelMap Acceleration map for the CR3BP.
bodiesToPropagate Bodies to be propagated.
centralBodies Central bodies for the propagation.
bodyMap Body Map for the CR3BP.
bodiesCR3BP Name of the two primaries defining the CR3BP.
directPropagation Propagated states of the full dynamics problem (returned by reference)
cr3bpPropagation Propagated states of the CR3BP, converted to dimensional coordinates (returned by reference)
Definition at line 253 of file propagationCR3BPFullProblem.cpp.
References propagateCR3BPAndFullDynamicsProblem().
getFinalStateDifferenceFullPropagationWrtCR3BP()
Eigen::Vector6d tudat::propagators::getFinalStateDifferenceFullPropagationWrtCR3BP (const double initialTime, const double finalTime, const Eigen::Vector6d & initialState, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const basic_astrodynamics::AccelerationMap & accelerationModelMap, const std::vector< std::string > & bodiesToPropagate, const std::vector< std::string > & centralBodies, const simulation_setup::NamedBodyMap & bodyMap, const std::vector< std::string > & bodiesCR3BP)
Propagate the CR3BP and the full dynamics problem and compute the state difference at the end of the propagation.
Parameters
initialTime Initial time for the propagation [s].
finalTime Final time at which the propagation ends [s].
initialState Initial state of the third, smaller body to be propagated (Cartesian position in velocity in m and m/s)
integratorSettings Integrator settings for the propagation (the initial time and time-step have to be defined as dimensional times, their conversion to adimensional times is implemented within the function).
accelerationModelMap Acceleration map for the CR3BP.
bodiesToPropagate Bodies to be propagated.
centralBodies Central bodies for the propagation.
bodyMap Body Map for the CR3BP.
bodiesCR3BP Name of the two primaries defining the CR3BP.
Returns
State difference between the full dynamics problem and the CR3BP at the final propagation time (expressed in inertial cartesian coordinates).
Definition at line 279 of file propagationCR3BPFullProblem.cpp.
References propagateCR3BPAndFullDynamicsProblem().
setupBodyMapFromEphemeridesForLambertTargeter()
simulation_setup::NamedBodyMap tudat::propagators::setupBodyMapFromEphemeridesForLambertTargeter (const std::string & nameCentralBody, const std::string & nameBodyToPropagate, const std::vector< std::string > & departureAndArrivalBodies)
Function to setup a body map corresponding to the assumptions of the Lambert targeter, using default ephemerides for the central, departure and arrival bodies.
Function to setup a body map corresponding to the assumptions of the Lambert targeter, using default ephemerides for the central, departure and arrival bodies.
The body map contains the central body, the body to be propagated and the departure and arrival bodies. The positions of the departure and arrival bodies are directly retrived from ephemerides.
Parameters
nameCentralBody Name of the central body.
nameBodyToPropagate Name of the body to be propagated.
departureAndArrivalBodies Vector containing the names of the departure and arrival bodies.
Returns
Body map for the Lambert targeter
Definition at line 37 of file propagationLambertTargeterFullProblem.cpp.
References tudat::simulation_setup::createBodies(), tudat::simulation_setup::getDefaultBodySettings(), tudat::spice_interface::loadStandardSpiceKernels(), and tudat::simulation_setup::setGlobalFrameBodyEphemerides().
setupBodyMapFromUserDefinedEphemeridesForLambertTargeter()
simulation_setup::NamedBodyMap tudat::propagators::setupBodyMapFromUserDefinedEphemeridesForLambertTargeter (const std::string & nameCentralBody, const std::string & nameBodyToPropagate, const std::vector< std::string > & departureAndArrivalBodies, const std::vector< ephemerides::EphemerisPointer > & ephemerisVectorDepartureAndArrivalBodies)
Function to setup a body map corresponding to the assumptions of the patched conics trajectory, the ephemerides of the transfer bodies being provided as inputs.
Definition at line 86 of file propagationLambertTargeterFullProblem.cpp.
References tudat::simulation_setup::createBodies(), tudat::simulation_setup::getDefaultBodySettings(), tudat::spice_interface::loadStandardSpiceKernels(), and tudat::simulation_setup::setGlobalFrameBodyEphemerides().
Referenced by setupBodyMapFromUserDefinedStatesForLambertTargeter().
setupBodyMapFromUserDefinedStatesForLambertTargeter()
simulation_setup::NamedBodyMap tudat::propagators::setupBodyMapFromUserDefinedStatesForLambertTargeter (const std::string & nameCentralBody, const std::string & nameBodyToPropagate, const std::vector< std::string > & departureAndArrivalBodies, const Eigen::Vector3d & cartesianPositionAtDeparture, const Eigen::Vector3d & cartesianPositionAtArrival)
Function to setup a body map corresponding to the assumptions of the Lambert targeter, using default ephemerides for the central body only, while the positions of departure and arrival bodies are provided as inputs.
Function to setup a body map corresponding to the assumptions of the Lambert targeter, using default ephemerides for the central body only, while the positions of departure and arrival bodies are provided as inputs.
The body map contains the central, departure and arrival bodies and the body to be propagated. The positions of the departure and arrival bodies are defined by the user and provided as inputs.
Parameters
nameCentralBody Name of the central body.
nameBodyToPropagate Name of the body to be propagated.
departureAndArrivalBodies Vector containing the names of the departure and arrival bodies.
cartesianPositionAtDeparture Vector containing the position coordinates of the departure body [m].
cartesianPositionAtArrival Vector containing the position coordinates of the arrival body [m].
Returns
Body map for the Lambert targeter.
Definition at line 144 of file propagationLambertTargeterFullProblem.cpp.
References tudat::spice_interface::loadStandardSpiceKernels(), and setupBodyMapFromUserDefinedEphemeridesForLambertTargeter().
setupAccelerationMapLambertTargeter()
basic_astrodynamics::AccelerationMap tudat::propagators::setupAccelerationMapLambertTargeter (const std::string & nameCentralBody, const std::string & nameBodyToPropagate, const simulation_setup::NamedBodyMap & bodyMap)
Function to directly setup an acceleration map for the Lambert targeter. Only the central body exerts a point-mass gravity acceleration on the body to be propagated.
Parameters
nameCentralBody Name of the central body.
nameBodyToPropagate Name of the body to be propagated.
bodyMap Body map for the Lambert targeter.
Returns
Acceleration map for the Lambert targeter.
Definition at line 184 of file propagationLambertTargeterFullProblem.cpp.
References tudat::basic_astrodynamics::central_gravity, and tudat::simulation_setup::createAccelerationModelsMap().
Referenced by setupAccelerationMapPatchedConicsTrajectory().
computeCartesianStateFromKeplerianOrbit()
Eigen::Vector6d tudat::propagators::computeCartesianStateFromKeplerianOrbit (const Eigen::Vector6d & initialState, const double finalPropagationTime, const double gravitationalParameter)
Function to determine the cartesian state at a given time for a keplerian orbit, based on the initial state.
Parameters
initialState Initial cartesian state on this orbit (x-position coordinate [m], y-position coordinate [m], z-position coordinate [m], x-velocity coordinate [m/s], y-velocity coordinate [m/s], z-velocity coordinate [m/s]).
finalPropagationTime Final time at which the cartesian state has to be calculated [s].
gravitationalParameter Gravitation parameter defining the keplerian orbit [m^3 s^-2].
Returns
Vector containing the cartesian state at a given time for a keplerian orbit.
Definition at line 217 of file propagationLambertTargeterFullProblem.cpp.
References tudat::orbital_element_conversions::convertCartesianToKeplerianElements(), tudat::orbital_element_conversions::convertEccentricAnomalyToMeanAnomaly(), tudat::orbital_element_conversions::convertEccentricAnomalyToTrueAnomaly(), tudat::orbital_element_conversions::convertElapsedTimeToMeanAnomalyChange(), tudat::orbital_element_conversions::convertHyperbolicEccentricAnomalyToMeanAnomaly(), tudat::orbital_element_conversions::convertHyperbolicEccentricAnomalyToTrueAnomaly(), tudat::orbital_element_conversions::convertKeplerianToCartesianElements(), tudat::orbital_element_conversions::convertMeanAnomalyToEccentricAnomaly(), tudat::orbital_element_conversions::convertMeanAnomalyToHyperbolicEccentricAnomaly(), tudat::orbital_element_conversions::convertTrueAnomalyToEccentricAnomaly(), tudat::orbital_element_conversions::convertTrueAnomalyToHyperbolicEccentricAnomaly(), tudat::input_output::field_types::state::eccentricity, tudat::orbital_element_conversions::eccentricityIndex, tudat::input_output::field_types::state::semiMajorAxis, tudat::orbital_element_conversions::semiMajorAxisIndex, and tudat::orbital_element_conversions::trueAnomalyIndex.
Referenced by propagateLambertTargeterAndFullProblem().
propagateLambertTargeterAndFullProblem() [1/2]
void tudat::propagators::propagateLambertTargeterAndFullProblem (const double timeOfFlight, const double initialTime, const simulation_setup::NamedBodyMap & bodyMap, const std::string & centralBody, std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > propagatorSettings, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, std::map< double, Eigen::Vector6d > & lambertTargeterResult, std::map< double, Eigen::Vector6d > & fullProblemResult, std::map< double, Eigen::VectorXd > & dependentVariableResult, const std::vector< std::string > & departureAndArrivalBodies, const double centralBodyGravitationalParameter, const Eigen::Vector3d & cartesianPositionAtDeparture, const Eigen::Vector3d & cartesianPositionAtArrival)
Function to propagate the full dynamics problem and the Lambert targeter solution. The function computes the cartesian state as a function of time in two different ways: from the Lambert targeter and from the propagation of the full dynamics problem. The propagator settings for the full problem propagation are directly provided as inputs.
Parameters
timeOfFlight Time of flight [s].
initialTime Initial time of the propagation [s].
bodyMap Body map.
centralBody Name of the central body for the Lambert targeter.
propagatorSettings Propagator settings for the full problem.
integratorSettings Integrator settings for the propagation.
lambertTargeterResult Map of the cartesian state obtained with the Lambert targeter as a function of time (modified within the function).
fullProblemResult Map of the cartesian state obtained after propagation of the full dynamics problem as a function of time (modified within the function).
cartesianPositionAtDeparture Cartesian position of the body to be propagated at departure [m].
cartesianPositionAtArrival Cartesian position of the body to be propagated at arrival [m].
centralBodyGravitationalParameter Gravitational parameter of the central body [m^3 s^-2]. If not provided as input, it is retrieved from the body map.
Definition at line 278 of file propagationLambertTargeterFullProblem.cpp.
References computeCartesianStateFromKeplerianOrbit(), tudat::orbital_element_conversions::convertCartesianToKeplerianElements(), tudat::orbital_element_conversions::convertKeplerianToCartesianElements(), tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getDependentVariableHistory(), tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getEquationsOfMotionNumericalSolution(), tudat::mission_segments::LambertTargeter::getInertialVelocityAtDeparture(), and tudat::orbital_element_conversions::propagateKeplerOrbit().
Referenced by getDifferenceFullPropagationWrtLambertTargeterAtDepartureAndArrival(), propagateLambertTargeterAndFullProblem(), propagateMga1DsmPositionAndFullProblem(), propagateMga1DsmVelocityAndFullProblem(), and propagateMgaWithoutDsmAndFullProblem().
propagateLambertTargeterAndFullProblem() [2/2]
void tudat::propagators::propagateLambertTargeterAndFullProblem (const double timeOfFlight, const double initialTime, const simulation_setup::NamedBodyMap & bodyMap, const basic_astrodynamics::AccelerationMap & accelerationModelMap, const std::string & bodyToPropagate, const std::string & centralBody, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, std::map< double, Eigen::Vector6d > & lambertTargeterResult, std::map< double, Eigen::Vector6d > & fullProblemResult, std::map< double, Eigen::VectorXd > & dependentVariableResult, const std::vector< std::string > & departureAndArrivalBodies, const bool terminationSphereOfInfluence, const Eigen::Vector3d & cartesianPositionAtDeparture, const Eigen::Vector3d & cartesianPositionAtArrival, const double departureBodyGravitationalParameter, const double arrivalBodyGravitationalParameter, const double centralBodyGravitationalParameter, const std::shared_ptr< DependentVariableSaveSettings > dependentVariablesToSave = std::shared_ptr< DependentVariableSaveSettings >(), const TranslationalPropagatorType propagator = cowell)
Function to propagate the full dynamics problem and the Lambert targeter solution. The function computes the cartesian state as a function of time in two different ways: from the Lambert targeter and from the propagation of the full dynamics problem. The propagator settings are defined inside the function from the propagator type and dependent variables to save provided as inputs.
Parameters
timeOfFlight Time of flight [s].
initialTime Initial time of the propagation [s].
bodyMap Body map.
accelerationModelMap Acceleration map.
bodyToPropagate Name of the body to be propagated.
centralBody Name of the central body for the Lambert targeter.
integratorSettings Integrator settings for the propagation.
lambertTargeterResult Map of the cartesian state obtained with the Lambert targeter as a function of time (modified within the function).
fullProblemResult Map of the cartesian state obtained after propagation of the full dynamics problem as a function of time (modified within the function).
terminationSphereOfInfluence Boolean denoting whether the propagation stops at the position of the departure and arrival body (false) or at the sphere of influence of the departure and arrival body (true).
cartesianPositionAtDeparture Cartesian position of the body to be propagated at departure [m].
cartesianPositionAtArrival Cartesian position of the body to be propagated at arrival [m].
departureBodyGravitationalParameter Gravitational parameter of the departure body [m^3 s^-2]. If not provided as input, it is retrieved from the body map.
arrivalBodyGravitationalParameter Gravitational parameter of the arrival body [m^3 s^-2]. If not provided as input, it is retrieved from the body map.
centralBodyGravitationalParameter Gravitational parameter of the central body [m^3 s^-2]. If not provided as input, it is retrieved from the body map.
dependentVariablesToSave List of dependent variables to be saved during the full problem propagation.
propagator Type of propagator to be used for the propagation of the full dynamics problem.
Definition at line 452 of file propagationLambertTargeterFullProblem.cpp.
References tudat::basic_astrodynamics::computeKeplerOrbitalPeriod(), tudat::mission_geometry::computeSphereOfInfluence(), tudat::basic_astrodynamics::computeSynodicPeriod(), tudat::orbital_element_conversions::convertCartesianToKeplerianElements(), propagateLambertTargeterAndFullProblem(), relative_distance_dependent_variable, and tudat::orbital_element_conversions::semiMajorAxisIndex.
getDifferenceFullPropagationWrtLambertTargeterAtDepartureAndArrival()
std::pair< Eigen::Vector6d, Eigen::Vector6d > tudat::propagators::getDifferenceFullPropagationWrtLambertTargeterAtDepartureAndArrival (const Eigen::Vector3d & cartesianPositionAtDeparture, const Eigen::Vector3d & cartesianPositionAtArrival, const double timeOfFlight, const double initialTime, const simulation_setup::NamedBodyMap & bodyMap, const basic_astrodynamics::AccelerationMap & accelerationModelMap, const std::string & bodyToPropagate, const std::string & centralBody, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const std::vector< std::string > & departureAndArrivalBodies, const bool terminationSphereOfInfluence, const std::shared_ptr< DependentVariableSaveSettings > dependentVariablesToSave = std::shared_ptr< DependentVariableSaveSettings >(), const TranslationalPropagatorType propagator = cowell)
Function to compute the difference in cartesian state between Lambert targeter solution and full dynamics problem, both at departure and at arrival.
Function to compute the difference in cartesian state between Lambert targeter solution and full dynamics problem, both at departure and at arrival.
The function returns a pair of vectors, the first one being the difference in state at departure and the second one the difference in state at arrival.
Parameters
cartesianPositionAtDeparture Cartesian position of the body to be propagated at departure [m].
cartesianPositionAtArrival Cartesian position of the body to be propagated at arrival [m].
timeOfFlight Time of flight [s].
initialTime Initial time of the propagation [s].
bodyMap Body map.
accelerationModelMap Acceleration map.
bodyToPropagate Names of the body to be propagated.
centralBody Names of the central body of propagation
integratorSettings Integrator settings for the propagation.
terminationSphereOfInfluence Boolean denoting whether the propagation stops at the position of the departure and arrival body (false) or at the sphere of influence of the departure and arrival body (true).
Returns
Pair of vectors containing the difference between the Lambert targeter and the full problem cartesian states (at departure and at arrival respectively).
Definition at line 638 of file propagationLambertTargeterFullProblem.cpp.
References propagateLambertTargeterAndFullProblem(), and TUDAT_NAN.
getVectorRepresentationForRotationMatrix()
Eigen::VectorXd tudat::propagators::getVectorRepresentationForRotationMatrix (const Eigen::Matrix3d & currentRotationMatrix)
Get the vector representation of a rotation matrix.
Parameters
currentRotationMatrix Rotation matrix that is to be put into vector rerpesentation
Returns
Column vector consisting of transpose of concatenated rows of currentRotationMatrix input.
Definition at line 21 of file propagationOutput.cpp.
Referenced by evaluateTrivariateFunction(), getVectorRepresentationForRotationMatrixFunction(), and getVectorRepresentationForRotationQuaternion().
getVectorRepresentationForRotationMatrixFunction()
Eigen::VectorXd tudat::propagators::getVectorRepresentationForRotationMatrixFunction (const std::function< Eigen::Matrix3d() > rotationFunction)
Get the vector representation of a rotation matrix.
Parameters
rotationFunction Function returning the rotation matrix that is to be put into vector rerpesentation
Returns
Column vector consisting of transpose of concatenated rows of rotationFunction input.
Definition at line 36 of file propagationOutput.cpp.
References getVectorRepresentationForRotationMatrix().
Referenced by evaluateTrivariateFunction().
getVectorRepresentationForRotationQuaternion()
Eigen::VectorXd tudat::propagators::getVectorRepresentationForRotationQuaternion (const std::function< Eigen::Quaterniond() > rotationFunction)
Get the vector representation of a quaternion. Quaternion is converted to a rotation matrix, which is then put into a vector representation.
Parameters
rotationFunction Function returning the quaternion that is to be put inot vector rerpesentation
Returns
Column vector consisting of transpose of concatenated rows of matrix representation of rotationFunction input.
Definition at line 43 of file propagationOutput.cpp.
References getVectorRepresentationForRotationMatrix().
Referenced by evaluateTrivariateFunction().
getMatrixFromVectorRotationRepresentation()
Eigen::Matrix3d tudat::propagators::getMatrixFromVectorRotationRepresentation (const Eigen::VectorXd vectorRepresentation)
Get the matrix representation from a vector with 9 entries. The vector is the transpose of the concatenated rows of the associated matrix.
Parameters
vectorRepresentation Vector representation of 3x3 matrix (transpose of the concatenated rows of the associated matrix)
Returns
Matrix from 3x3 vector representation.
Definition at line 50 of file propagationOutput.cpp.
Referenced by evaluateTrivariateFunction(), and getQuaternionFromVectorRotationRepresentation().
getQuaternionFromVectorRotationRepresentation()
Eigen::Quaterniond tudat::propagators::getQuaternionFromVectorRotationRepresentation (const Eigen::VectorXd vectorRepresentation)
Get the quaternion formulation of an orthonormal matrix, from input of a vector with 9 entries corresponding to matrix entries.
Get the quaternion formulation of an orthonormal matrix, from input of a vector with 9 entries corresponding to matrix entries.
The input vector is the transpose of the concatenated rows of the associated (orthonormal) matrix.
Parameters
vectorRepresentation Vector representation of 3x3 matrix (transpose of the concatenated rows of the associated matrix)
Returns
Quaternion representation of orthonormal matrix obtained from 3x3 vector representation.
Definition at line 71 of file propagationOutput.cpp.
References getMatrixFromVectorRotationRepresentation().
Referenced by evaluateTrivariateFunction().
getMatrixInOutputVectorRepresentation()
void tudat::propagators::getMatrixInOutputVectorRepresentation (const Eigen::MatrixXd & matrix, Eigen::VectorXd & vector)
Function to convert a matrix to the format used to save dependent variables
Parameters
matrix Matrix that is to be converted
vector Vector storage format of matrix
Definition at line 78 of file propagationOutput.cpp.
Referenced by evaluateTrivariateFunction(), and getVectorFunctionFromBlockFunction().
getOutputVectorInMatrixRepresentation()
void tudat::propagators::getOutputVectorInMatrixRepresentation (const Eigen::VectorXd & vector, Eigen::MatrixXd & matrix, const int rows, const int columns)
Function to convert a vector dependent variable output to its original matrix representation
Parameters
vector Vector dependent variable output
matrix Original matrix representation
rows Number of rows in matrix output
columns Number of columns in matrix output
Definition at line 90 of file propagationOutput.cpp.
Referenced by evaluateTrivariateFunction().
getVectorFunctionFromBlockFunction()
Eigen::VectorXd tudat::propagators::getVectorFunctionFromBlockFunction (const std::function< void(Eigen::Block< Eigen::MatrixXd >) > blockFunction, const int numberOfRows, const int numberOfColumns)
Function to retrieve matrix block function output in vector representation
Parameters
blockFunction Function that returns (by reference) a matrix block
numberOfRows Number of rows in matrix output
numberOfColumns Number of columns in matrix output
Returns
Block-matrix in vector representation
Definition at line 106 of file propagationOutput.cpp.
References getMatrixInOutputVectorRepresentation().
Referenced by evaluateTrivariateFunction().
computeEquilibriumFayRiddellHeatFluxFromProperties()
double tudat::propagators::computeEquilibriumFayRiddellHeatFluxFromProperties (const std::shared_ptr< aerodynamics::AtmosphericFlightConditions > flightConditions, const std::shared_ptr< system_models::VehicleSystems > vehicleSystems)
Function to compute the Fay-Riddell equilibrium heat flux from body properties
Parameters
flightConditions Object describing the current atmospheric flight conditions of the vehicle
vehicleSystems Object describing the physical properties of the vehicle
Returns
Equilibrium heat flux according to Fay-Riddell model
Definition at line 120 of file propagationOutput.cpp.
References tudat::aerodynamics::computeEquilibriumFayRiddellHeatFlux().
Referenced by evaluateTrivariateFunction().
getVectorFromDoubleFunction()
Eigen::VectorXd tudat::propagators::getVectorFromDoubleFunction (const std::function< double() > & doubleFunction)
Parameters
doubleFunction Function returning the double value
Returns
The vector containing only one element
Definition at line 132 of file propagationOutput.cpp.
Referenced by getDoubleDependentVariableFunction().
evaluateListOfVectorFunctions()
Eigen::VectorXd tudat::propagators::evaluateListOfVectorFunctions (const std::vector< std::pair< std::function< Eigen::VectorXd() >, int > > vectorFunctionList, const int totalSize)
Function to evaluate a set of vector-returning functions and concatenate the results.
Parameters
vectorFunctionList List of functions returning vector variables (pairs denote function and return vector size)
totalSize Total size of concatenated vector (used as input for efficiency.
Returns
Concatenated results from input functions.
Definition at line 140 of file propagationOutput.cpp.
Referenced by getDoubleDependentVariableFunction().
getNormsOfAccelerationDifferencesFromLists()
Eigen::VectorXd tudat::propagators::getNormsOfAccelerationDifferencesFromLists (const std::function< Eigen::VectorXd() > firstAccelerationFunction, const std::function< Eigen::VectorXd() > secondAccelerationFunction)
Definition at line 165 of file propagationOutput.cpp.
Referenced by evaluateTrivariateFunction().
getDependentVariableSaveSize()
int tudat::propagators::getDependentVariableSaveSize (const std::shared_ptr< SingleDependentVariableSaveSettings > & singleDependentVariableSaveSettings)
Funtion to get the size of a dependent variable save settings.
Parameters
singleDependentVariableSaveSettings Save settings for a dependent variable.
Returns
Size of requested dependent variable to save (equal to the size of the associated dependent variable, or equal to 1 if the property component_ is set).
Definition at line 194 of file propagationOutput.cpp.
References getDependentVariableSize().
Referenced by createDependentVariableListFunction(), createPropagationTerminationConditions(), evaluateTrivariateFunction(), and tudat::json_interface::exportResultsOfDynamicsSimulator().
getDependentVariableSize()
int tudat::propagators::getDependentVariableSize (const std::shared_ptr< SingleDependentVariableSaveSettings > dependentVariableSettings)
Funtion to get the size (i.e. number of values in variable: one for altitude, three for position, etc.) of a dependent variable
Parameters
dependentVariableSettings Dependent variable type for which size is to be determined.
Returns
Size of requested dependent variable.
Definition at line 208 of file propagationOutput.cpp.
References acceleration_partial_wrt_body_translational_state, aerodynamic_force_coefficients_dependent_variable, aerodynamic_moment_coefficients_dependent_variable, airspeed_dependent_variable, altitude_dependent_variable, body_fixed_airspeed_based_velocity_variable, body_fixed_groundspeed_based_velocity_variable, body_fixed_relative_cartesian_position, body_fixed_relative_spherical_position, control_surface_deflection_dependent_variable, createDependentVariableListFunction< double, double >(), current_body_mass_dependent_variable, euler_angles_to_body_fixed_313, geodetic_latitude_dependent_variable, intermediate_aerodynamic_rotation_matrix_variable, keplerian_state_dependent_variable, local_aerodynamic_heat_rate_dependent_variable, local_density_dependent_variable, local_dynamic_pressure_dependent_variable, local_temperature_dependent_variable, lvlh_to_inertial_frame_rotation_dependent_variable, mach_number_dependent_variable, modified_equinocial_state_dependent_variable, periapsis_altitude_dependent_variable, radiation_pressure_coefficient_dependent_variable, radiation_pressure_dependent_variable, relative_body_aerodynamic_orientation_angle_variable, relative_distance_dependent_variable, relative_position_dependent_variable, relative_speed_dependent_variable, relative_velocity_dependent_variable, rotation_matrix_to_body_fixed_frame_variable, single_acceleration_dependent_variable, single_acceleration_norm_dependent_variable, single_gravity_field_variation_acceleration, single_gravity_field_variation_acceleration_terms, single_torque_dependent_variable, single_torque_norm_dependent_variable, spherical_harmonic_acceleration_norm_terms_dependent_variable, spherical_harmonic_acceleration_terms_dependent_variable, stagnation_point_heat_flux_dependent_variable, total_acceleration_dependent_variable, total_acceleration_norm_dependent_variable, total_aerodynamic_g_load_variable, total_gravity_field_variation_acceleration, total_mass_rate_dependent_variables, total_torque_dependent_variable, and total_torque_norm_dependent_variable.
Referenced by evaluateTrivariateFunction(), getDependentVariableSaveSize(), and getDoubleDependentVariableFunction().
createDependentVariableListFunction< double, double >()
template std::pair< std::function< Eigen::VectorXd() >, std::map< int, std::string > > tudat::propagators::createDependentVariableListFunction< double, double > (const std::shared_ptr< DependentVariableSaveSettings > saveSettings, const simulation_setup::NamedBodyMap & bodyMap, const std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< double, double > > > > & stateDerivativeModels)
Referenced by createDependentVariableListFunction(), and getDependentVariableSize().
evaluateBivariateReferenceFunction()
template<typename OutputType , typename InputType > OutputType tudat::propagators::evaluateBivariateReferenceFunction (const std::function< OutputType(const InputType &, const InputType &) > functionToEvaluate, const std::function< InputType() > firstInput, const std::function< InputType() > secondInput)
Function to evaluate a function with two input variables (by reference) from function pointers that return these two input variables.
Parameters
functionToEvaluate Function that is to be evaluated with input from function pointers.
firstInput Function returning first input to functionToEvaluate.
secondInput Function returning second input to functionToEvaluate.
Returns
Output from functionToEvaluate, using functions firstInput and secondInput as input.
Definition at line 43 of file propagationOutput.h.
evaluateReferenceFunction()
template<typename OutputType , typename InputType > OutputType tudat::propagators::evaluateReferenceFunction (const std::function< OutputType(const InputType &) > functionToEvaluate, const std::function< InputType() > firstInput)
Definition at line 52 of file propagationOutput.h.
evaluateBivariateFunction()
template<typename OutputType , typename InputType > OutputType tudat::propagators::evaluateBivariateFunction (const std::function< OutputType(const InputType, const InputType) > functionToEvaluate, const std::function< InputType() > firstInput, const std::function< InputType() > secondInput)
Function to evaluate a function with two input variables from function pointers that return these two input variables.
Parameters
functionToEvaluate Function that is to be evaluated with input from function pointers.
firstInput Function returning first input to functionToEvaluate.
secondInput Function returning second input to functionToEvaluate.
Returns
Output from functionToEvaluate, using functions firstInput and secondInput as input.
Definition at line 69 of file propagationOutput.h.
evaluateTrivariateFunction()
template<typename OutputType , typename FirstInputType , typename SecondInputType , typename ThirdInputType > OutputType tudat::propagators::evaluateTrivariateFunction (const std::function< OutputType(const FirstInputType &, const SecondInputType, const ThirdInputType) > functionToEvaluate, const std::function< FirstInputType() > firstInput, const std::function< SecondInputType() > secondInput, const std::function< ThirdInputType() > thirdInput)
Function to evaluate a function with three input variables from function pointers that return these three input variables.
Parameters
functionToEvaluate Function that is to be evaluated with input from function pointers.
firstInput Function returning first input to functionToEvaluate.
secondInput Function returning second input to functionToEvaluate.
thirdInput Function returning third input to functionToEvaluate.
Returns
Output from functionToEvaluate, using functions firstInput, secondInput and thirdInput as input.
Definition at line 88 of file propagationOutput.h.
References computeEquilibriumFayRiddellHeatFluxFromProperties(), getDependentVariableSaveSize(), getDependentVariableSize(), getMatrixFromVectorRotationRepresentation(), getMatrixInOutputVectorRepresentation(), getNormsOfAccelerationDifferencesFromLists(), getOutputVectorInMatrixRepresentation(), getQuaternionFromVectorRotationRepresentation(), getVectorFunctionFromBlockFunction(), getVectorRepresentationForRotationMatrix(), getVectorRepresentationForRotationMatrixFunction(), and getVectorRepresentationForRotationQuaternion().
getSphericalHarmonicAccelerationForDependentVariables()
template<typename StateScalarType , typename TimeType > std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > tudat::propagators::getSphericalHarmonicAccelerationForDependentVariables (const std::shared_ptr< SingleDependentVariableSaveSettings > dependentVariableSettings, const std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > > & stateDerivativeModels, const bool allowThirdBodyAcceleration = false)
Function to retrieve relevant spherical harmonic acceleration model for dependent variable setting
Parameters
dependentVariableSettings Settings for dependent variable, associatedBody_ defines body undergoing acceleration, secondaryBody_ body exerting acceleration
stateDerivativeModels List of state derivative models from which acceleration is to be retrieved
Returns
Relevant spherical harmonic acceleration model for dependent variable setting
Definition at line 229 of file propagationOutput.h.
References getAccelerationBetweenBodies(), tudat::basic_astrodynamics::getAssociatedThirdBodyAcceleration(), and tudat::basic_astrodynamics::spherical_harmonic_gravity.
Referenced by getVectorDependentVariableFunction().
getVectorDependentVariableFunction()
template<typename TimeType = double, typename StateScalarType = double> std::pair< std::function< Eigen::VectorXd() >, int > tudat::propagators::getVectorDependentVariableFunction (const std::shared_ptr< SingleDependentVariableSaveSettings > dependentVariableSettings, const simulation_setup::NamedBodyMap & bodyMap, const std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > > & stateDerivativeModels = std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > >(), const std::map< propagators::IntegratedStateType, orbit_determination::StateDerivativePartialsMap > & stateDerivativePartials = std::map< propagators::IntegratedStateType, orbit_determination::StateDerivativePartialsMap >())
Function to create a function returning a requested dependent variable value (of type VectorXd), retrieved from environment and/or state derivative models.
Parameters
dependentVariableSettings Settings for dependent variable that is to be returned by function created here.
bodyMap List of bodies to use in simulations (containing full environment).
stateDerivativeModels List of state derivative models used in simulations (sorted by dynamics type as key).
stateDerivativePartials List of state derivative partials used in simulations (sorted by dynamics type as key).
Returns
Function returning requested dependent variable. NOTE: The environment and state derivative models need to be updated to current state and independent variable before computation is performed.
Definition at line 320 of file propagationOutput.h.
References acceleration_partial_wrt_body_translational_state, aerodynamic_force_coefficients_dependent_variable, aerodynamic_moment_coefficients_dependent_variable, body_fixed_airspeed_based_velocity_variable, body_fixed_groundspeed_based_velocity_variable, body_fixed_relative_cartesian_position, body_fixed_relative_spherical_position, dependentVariable, euler_angles_to_body_fixed_313, tudat::basic_mathematics::get313EulerAnglesFromQuaternion(), tudat::basic_astrodynamics::AccelerationModel< AccelerationDataType >::getAcceleration(), getAccelerationBetweenBodies(), tudat::gravitation::ThirdBodyAcceleration< DirectAccelerationModelType, type >::getAccelerationModelForBodyUndergoingAcceleration(), tudat::gravitation::SphericalHarmonicsGravitationalAccelerationModel::getAccelerationWithAlternativeCoefficients(), tudat::basic_astrodynamics::getAssociatedThirdBodyAcceleration(), tudat::reference_frames::getBodyFixedCartesianPosition(), tudat::reference_frames::getBodyFixedSphericalPosition(), tudat::gravitation::SphericalHarmonicsGravitationalAccelerationModel::getConcatenatedAccelerationComponentNorms(), tudat::gravitation::SphericalHarmonicsGravitationalAccelerationModel::getConcatenatedAccelerationComponents(), tudat::aerodynamics::AtmosphericFlightConditions::getCurrentAirspeedBasedVelocity(), tudat::aerodynamics::AerodynamicCoefficientInterface::getCurrentForceCoefficients(), tudat::reference_frames::AerodynamicAngleCalculator::getCurrentGroundspeedBasedBodyFixedVelocity(), tudat::aerodynamics::AerodynamicCoefficientInterface::getCurrentMomentCoefficients(), tudat::simulation_setup::Body::getCurrentRotationToLocalFrame(), tudat::simulation_setup::getGlobalFrameOrigin(), tudat::gravitation::GravityFieldModel::getGravitationalParameter(), tudat::gravitation::GravityFieldVariations::getLastCosineCorrection(), tudat::gravitation::GravityFieldVariations::getLastSineCorrection(), tudat::simulation_setup::Body::getPosition(), getRotationalStateDerivativeModelForBody(), tudat::reference_frames::AerodynamicAngleCalculator::getRotationQuaternionBetweenFrames(), getSphericalHarmonicAccelerationForDependentVariables(), tudat::simulation_setup::Body::getState(), tudat::basic_astrodynamics::TorqueModel::getTorque(), getTorqueBetweenBodies(), tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::getTotalCosineCoefficientCorrection(), tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::getTotalSineCoefficientCorrection(), getTranslationalStateDerivativeModelForBody(), tudat::simulation_setup::Body::getVelocity(), tudat::reference_frames::getVelocityBasedLvlhToInertialRotationFromFunctions(), intermediate_aerodynamic_rotation_matrix_variable, tudat::basic_astrodynamics::isAccelerationDirectGravitational(), tudat::ephemerides::isFrameInertial(), keplerian_state_dependent_variable, lvlh_to_inertial_frame_rotation_dependent_variable, modified_equinocial_state_dependent_variable, relative_position_dependent_variable, relative_velocity_dependent_variable, rotation_matrix_to_body_fixed_frame_variable, tudat::gravitation::SphericalHarmonicsGravitationalAccelerationModel::setSaveSphericalHarmonicTermsSeparately(), single_acceleration_dependent_variable, single_gravity_field_variation_acceleration, single_gravity_field_variation_acceleration_terms, single_torque_dependent_variable, spherical_harmonic_acceleration_norm_terms_dependent_variable, spherical_harmonic_acceleration_terms_dependent_variable, total_acceleration_dependent_variable, total_gravity_field_variation_acceleration, total_torque_dependent_variable, and translational_state.
Referenced by createDependentVariableListFunction(), and getDoubleDependentVariableFunction().
elementAtIndexFunction()
double tudat::propagators::elementAtIndexFunction (const std::function< Eigen::VectorXd() > & vectorFunction, const int index) inline
Acces element at index function
Parameters
vectorFunction The function returning an Eigen vector
index The index to be accessed
Returns
The value of vector at index
Definition at line 1141 of file propagationOutput.h.
Referenced by getDoubleDependentVariableFunction().
getDoubleDependentVariableFunction()
template<typename TimeType = double, typename StateScalarType = double> std::function< double() > tudat::propagators::getDoubleDependentVariableFunction (const std::shared_ptr< SingleDependentVariableSaveSettings > dependentVariableSettings, const simulation_setup::NamedBodyMap & bodyMap, const std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > > & stateDerivativeModels = std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > >(), const std::map< propagators::IntegratedStateType, orbit_determination::StateDerivativePartialsMap > & stateDerivativePartials = std::map< propagators::IntegratedStateType, orbit_determination::StateDerivativePartialsMap >())
Function to create a function returning a requested dependent variable value (of type double), retrieved from environment and/or state derivative models.
Parameters
dependentVariableSettings Settings for dependent variable that is to be returned by function created here.
bodyMap List of bodies to use in simulations (containing full environment).
stateDerivativeModels List of state derivative models used in simulations (sorted by dynamics type as key).
stateDerivativePartials List of state derivative partials used in simulations (sorted by dynamics type as key).
Returns
Function returning requested dependent variable. NOTE: The environment and state derivative models need to be updated to current state and independent variable before computation is performed.
Definition at line 1158 of file propagationOutput.h.
References tudat::basic_astrodynamics::aerodynamic, airspeed_dependent_variable, altitude_dependent_variable, tudat::aerodynamics::computeAerodynamicLoadFromAcceleration(), tudat::aerodynamics::computeMachNumber(), tudat::linear_algebra::computeNormOfVectorDifference(), tudat::basic_astrodynamics::computePeriapsisAltitudeFromCartesianState(), control_surface_deflection_dependent_variable, current_body_mass_dependent_variable, dependentVariable, elementAtIndexFunction(), evaluateListOfVectorFunctions(), geodetic_latitude_dependent_variable, tudat::basic_astrodynamics::AccelerationModel< AccelerationDataType >::getAcceleration(), getAccelerationBetweenBodies(), tudat::reference_frames::AerodynamicAngleCalculator::getAerodynamicAngle(), tudat::basic_astrodynamics::getAssociatedThirdBodyAcceleration(), tudat::basic_astrodynamics::BodyShapeModel::getAverageRadius(), tudat::simulation_setup::Body::getBodyMass(), getBodyMassStateDerivativeModelForBody(), tudat::aerodynamics::AtmosphericFlightConditions::getCurrentAerodynamicHeatRate(), tudat::aerodynamics::AtmosphericFlightConditions::getCurrentAirspeed(), tudat::aerodynamics::FlightConditions::getCurrentAltitude(), tudat::system_models::VehicleSystems::getCurrentControlSurfaceDeflection(), tudat::aerodynamics::AtmosphericFlightConditions::getCurrentDensity(), tudat::aerodynamics::AtmosphericFlightConditions::getCurrentDynamicPressure(), tudat::aerodynamics::AtmosphericFlightConditions::getCurrentFreestreamTemperature(), tudat::aerodynamics::FlightConditions::getCurrentGeodeticLatitude(), tudat::electro_magnetism::RadiationPressureInterface::getCurrentRadiationPressure(), tudat::aerodynamics::AtmosphericFlightConditions::getCurrentSpeedOfSound(), getDependentVariableSize(), tudat::simulation_setup::getGlobalFrameOrigin(), tudat::gravitation::GravityFieldModel::getGravitationalParameter(), tudat::simulation_setup::Body::getPosition(), tudat::electro_magnetism::RadiationPressureInterface::getRadiationPressureCoefficient(), getRotationalStateDerivativeModelForBody(), tudat::simulation_setup::Body::getState(), tudat::basic_astrodynamics::TorqueModel::getTorque(), getTorqueBetweenBodies(), getTranslationalStateDerivativeModelForBody(), getVectorDependentVariableFunction(), getVectorFromDoubleFunction(), tudat::linear_algebra::getVectorNormFromFunction(), tudat::simulation_setup::Body::getVelocity(), tudat::basic_astrodynamics::isAccelerationDirectGravitational(), local_aerodynamic_heat_rate_dependent_variable, local_density_dependent_variable, local_dynamic_pressure_dependent_variable, local_temperature_dependent_variable, mach_number_dependent_variable, periapsis_altitude_dependent_variable, radiation_pressure_coefficient_dependent_variable, radiation_pressure_dependent_variable, relative_body_aerodynamic_orientation_angle_variable, relative_distance_dependent_variable, relative_speed_dependent_variable, single_acceleration_norm_dependent_variable, single_torque_norm_dependent_variable, stagnation_point_heat_flux_dependent_variable, total_acceleration_norm_dependent_variable, total_aerodynamic_g_load_variable, total_mass_rate_dependent_variables, and total_torque_norm_dependent_variable.
Referenced by createDependentVariableListFunction(), and createPropagationTerminationConditions().
createDependentVariableListFunction()
template<typename TimeType = double, typename StateScalarType = double> std::pair< std::function< Eigen::VectorXd() >, std::map< int, std::string > > tudat::propagators::createDependentVariableListFunction (const std::shared_ptr< DependentVariableSaveSettings > saveSettings, const simulation_setup::NamedBodyMap & bodyMap, const std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > > & stateDerivativeModels = std::unordered_map< IntegratedStateType, std::vector< std::shared_ptr< SingleStateTypeDerivative< StateScalarType, TimeType > > > >())
Function to create a function that evaluates a list of dependent variables and concatenates the results. Dependent variables functions are created inside this function from a list of settings on their required types/properties.
Parameters
saveSettings Object containing types and other properties of dependent variables.
bodyMap List of bodies to use in simulations (containing full environment).
stateDerivativeModels List of state derivative models used in simulations (sorted by dynamics type as key)
Returns
Pair with function returning requested dependent variable values, and list variable names with start entries. NOTE: The environment and state derivative models need to be updated to current state and independent variable before computation is performed.
Definition at line 1696 of file propagationOutput.h.
References createDependentVariableListFunction< double, double >(), getDependentVariableId(), getDependentVariableSaveSize(), getDoubleDependentVariableFunction(), and getVectorDependentVariableFunction().
getVariableName()
std::string tudat::propagators::getVariableName (const VariableType variableType)
Function to get a string representing a 'named identification' of a variable type.
Parameters
variableType Variable type.
Returns
String with variable type id.
Definition at line 20 of file propagationOutputSettings.cpp.
References cpuTimeVariable, dependentVariable, independentVariable, sensitivityMatrix, stateTransitionMatrix, and stateVariable.
Referenced by getVariableId().
getVariableId()
std::string tudat::propagators::getVariableId (const std::shared_ptr< VariableSettings > variableSettings)
Function to get a string representing a 'named identification' of a variable.
Parameters
variableSettings Variable.
Returns
String with variable id.
Definition at line 44 of file propagationOutputSettings.cpp.
References getDependentVariableId(), and getVariableName().
Referenced by tudat::json_interface::exportResultsOfDynamicsSimulator(), from_json(), and tudat::json_interface::resetDependentVariableSaveSettings().
getDependentVariableName()
std::string tudat::propagators::getDependentVariableName (const PropagationDependentVariables propagationDependentVariables)
Function to get a string representing a 'named identification' of a dependent variable type.
Parameters
propagationDependentVariables Dependent variable type.
Returns
String with dependent variable type id.
Definition at line 60 of file propagationOutputSettings.cpp.
References acceleration_partial_wrt_body_translational_state, aerodynamic_force_coefficients_dependent_variable, aerodynamic_moment_coefficients_dependent_variable, airspeed_dependent_variable, altitude_dependent_variable, body_fixed_airspeed_based_velocity_variable, body_fixed_groundspeed_based_velocity_variable, body_fixed_relative_cartesian_position, body_fixed_relative_spherical_position, control_surface_deflection_dependent_variable, current_body_mass_dependent_variable, euler_angles_to_body_fixed_313, geodetic_latitude_dependent_variable, intermediate_aerodynamic_rotation_matrix_variable, keplerian_state_dependent_variable, local_aerodynamic_heat_rate_dependent_variable, local_density_dependent_variable, local_dynamic_pressure_dependent_variable, local_temperature_dependent_variable, lvlh_to_inertial_frame_rotation_dependent_variable, mach_number_dependent_variable, modified_equinocial_state_dependent_variable, periapsis_altitude_dependent_variable, radiation_pressure_coefficient_dependent_variable, radiation_pressure_dependent_variable, relative_body_aerodynamic_orientation_angle_variable, relative_distance_dependent_variable, relative_position_dependent_variable, relative_speed_dependent_variable, relative_velocity_dependent_variable, rotation_matrix_to_body_fixed_frame_variable, single_acceleration_dependent_variable, single_acceleration_norm_dependent_variable, single_gravity_field_variation_acceleration, single_gravity_field_variation_acceleration_terms, single_torque_dependent_variable, single_torque_norm_dependent_variable, spherical_harmonic_acceleration_norm_terms_dependent_variable, spherical_harmonic_acceleration_terms_dependent_variable, stagnation_point_heat_flux_dependent_variable, total_acceleration_dependent_variable, total_acceleration_norm_dependent_variable, total_aerodynamic_g_load_variable, total_gravity_field_variation_acceleration, total_mass_rate_dependent_variables, total_torque_dependent_variable, and total_torque_norm_dependent_variable.
Referenced by getDependentVariableId().
getDependentVariableId()
std::string tudat::propagators::getDependentVariableId (const std::shared_ptr< SingleDependentVariableSaveSettings > dependentVariableSettings)
Function to get a string representing a 'named identification' of a dependent variable.
Parameters
dependentVariableSettings Dependent variable.
Returns
String with dependent variable id.
Definition at line 217 of file propagationOutputSettings.cpp.
References tudat::basic_astrodynamics::getAccelerationModelName(), tudat::reference_frames::getAerodynamicAngleName(), tudat::reference_frames::getAerodynamicFrameName(), getDependentVariableName(), tudat::basic_astrodynamics::getTorqueModelName(), intermediate_aerodynamic_rotation_matrix_variable, relative_body_aerodynamic_orientation_angle_variable, single_acceleration_dependent_variable, single_acceleration_norm_dependent_variable, single_torque_dependent_variable, single_torque_norm_dependent_variable, spherical_harmonic_acceleration_norm_terms_dependent_variable, and spherical_harmonic_acceleration_terms_dependent_variable.
Referenced by createDependentVariableListFunction(), tudat::json_interface::exportResultsOfDynamicsSimulator(), and getVariableId().
getDefaultMinimumPericenterRadii()
std::vector< double > tudat::propagators::getDefaultMinimumPericenterRadii (const std::vector< std::string > & bodyNames)
Function to get default minimum pericenter radii for a list of bodies.
Function to get default minimum pericenter radii for a list of bodies
Parameters
bodyNames List of names of bodies for which periapsis radii are to be returned (only the eight planets + Pluto supported)
Returns
List of minimum pericenter radii
Definition at line 38 of file propagationPatchedConicFullProblem.cpp.
setupBodyMapFromEphemeridesForPatchedConicsTrajectory()
simulation_setup::NamedBodyMap tudat::propagators::setupBodyMapFromEphemeridesForPatchedConicsTrajectory (const std::string & nameCentralBody, const std::string & nameBodyToPropagate, const std::vector< std::string > & nameTransferBodies)
Function to setup a body map corresponding to the assumptions of a patched conics trajectory, using default ephemerides for the central and transfer bodies.
Function to setup a body map corresponding to the assumptions of a patched conics trajectory, using default ephemerides for the central and transfer bodies.
The body map contains the central body, the transfer bodies and the body to be propagated. The positions of the central and transfer bodies are directly retrieved from ephemerides.
Parameters
nameCentralBody Name of the central body.
nameBodyToPropagate Name of the body to be propagated.
nameTransferBodies Vector containing the names of the transfer bodies.
Returns
Body map for the patched conics trajectory.
Definition at line 91 of file propagationPatchedConicFullProblem.cpp.
References tudat::simulation_setup::createBodies(), tudat::simulation_setup::getDefaultBodySettings(), tudat::spice_interface::loadStandardSpiceKernels(), and tudat::simulation_setup::setGlobalFrameBodyEphemerides().
setupBodyMapFromUserDefinedEphemeridesForPatchedConicsTrajectory()
simulation_setup::NamedBodyMap tudat::propagators::setupBodyMapFromUserDefinedEphemeridesForPatchedConicsTrajectory (const std::string & nameCentralBody, const std::string & nameBodyToPropagate, const std::vector< std::string > & nameTransferBodies, const std::vector< ephemerides::EphemerisPointer > & ephemerisVectorTransferBodies, const std::vector< double > & gravitationalParametersTransferBodies, const std::string & frameOrientation)
Function to setup a body map corresponding to the assumptions of the patched conics trajectory, the ephemerides of the transfer bodies being provided as inputs.
Function to setup a body map corresponding to the assumptions of the patched conics trajectory, the ephemerides of the transfer bodies being provided as inputs.
The body map contains the central body, the transfer bodies and the body to be propagated. Default ephemeris is used for the central body but the ephemerides of the transfer bodies need to be provided as inputs.
Parameters
nameCentralBody Name of the central body.
nameBodyToPropagate Name of the body to be propagated.
nameTransferBodies Vector containing the names of the transfer bodies.
ephemerisVectorTransferBodies Vector containing the ephemeris pointers of the different transfer bodies.
gravitationalParametersTransferBodies Vector containing the gravitational parameters of the transfer bodies [m^3 s^-2].
Returns
Body map for the patched conics trajectory.
Definition at line 143 of file propagationPatchedConicFullProblem.cpp.
References tudat::simulation_setup::createBodies(), tudat::simulation_setup::createGravityFieldModel(), tudat::simulation_setup::getDefaultBodySettings(), tudat::spice_interface::loadStandardSpiceKernels(), and tudat::simulation_setup::setGlobalFrameBodyEphemerides().
setupAccelerationMapPatchedConicsTrajectory()
std::vector< basic_astrodynamics::AccelerationMap > tudat::propagators::setupAccelerationMapPatchedConicsTrajectory (const double numberOfLegs, const std::string & nameCentralBody, const std::string & nameBodyToPropagate, const simulation_setup::NamedBodyMap & bodyMap)
Function to directly setup a vector of acceleration maps for a patched conics trajectory. For each leg, only the central body exerts a point-mass gravity acceleration on the body to be propagated.
Parameters
numberOfLegs Number of legs of the patched conics trajectory.
nameCentralBody Name of the central body.
nameBodyToPropagate Name of the body to be propagated.
bodyMap Body map for the patched conics trajectory.
Returns
Acceleration map for the patched conics trajectory.
Definition at line 201 of file propagationPatchedConicFullProblem.cpp.
References setupAccelerationMapLambertTargeter().
createTransferTrajectoryObject()
transfer_trajectories::Trajectory tudat::propagators::createTransferTrajectoryObject (const simulation_setup::NamedBodyMap & bodyMap, const std::vector< std::string > & transferBodyOrder, const std::string & centralBody, const std::vector< transfer_trajectories::TransferLegType > & transferLegTypes, const std::vector< double > trajectoryIndependentVariables, const std::vector< double > minimumPericenterRadii, const bool includeDepartureDeltaV, const double departureSemiMajorAxis, const double departureEccentricity, const bool includeArrivalDeltaV, const double arrivalSemiMajorAxis, const double arrivalEccentricity)
Function to create the trajectory from the body map.
Parameters
bodyMap Body map from which the trajectory is to be defined.
transferBodyOrder Vector containing the names of the transfer bodies involved in the trajectory.
centralBody Name of the central body of the patched conics trajectory.
transferLegTypes Vector containing the leg types.
trajectoryIndependentVariables Vector containing all the defining variables for the whole trajectory.
minimumPericenterRadii Vector containing the minimum distance between the spacecraft and the body.
includeDepartureDeltaV Boolean denoting whether to include the Delta V at departure.
departureSemiMajorAxis Semi-major axis of the departure leg.
departureEccentricity Eccentricity of the departure leg.
includeArrivalDeltaV Boolean denoting whether to include the Delta V at arrival.
arrivalSemiMajorAxis Semi-major axis of the arrival leg.
arrivalEccentricity Eccentricity of the arrival leg.
Returns
Trajectory defined from the body map.
Definition at line 220 of file propagationPatchedConicFullProblem.cpp.
References tudat::utilities::convertStlVectorToEigenVector(), and TUDAT_NAN.
Referenced by fullPropagationPatchedConicsTrajectory(), and getPatchedConicPropagatorSettings().
propagateMgaWithoutDsmAndFullProblem()
void tudat::propagators::propagateMgaWithoutDsmAndFullProblem (simulation_setup::NamedBodyMap & bodyMap, const std::vector< std::string > departureAndArrivalBodies, const std::string centralBody, const Eigen::Vector3d cartesianPositionAtDeparture, const Eigen::Vector3d cartesianPositionAtArrival, const double initialTime, const double timeOfFlight, const std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > propagatorSettings, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > & integratorSettings, std::map< double, Eigen::Vector6d > & patchedConicsResult, std::map< double, Eigen::Vector6d > & fullProblemResult, std::map< double, Eigen::VectorXd > & dependentVariableResultCurrentLeg)
Function to both calculate a patched conics leg without DSM and propagate the full dynamics problem.
Parameters
bodyMap Body map for the patched conics leg.
departureAndArrivalBodies Vector containing the names of the departure and arrival bodies of the leg.
centralBody Name of the central body of the patched conics trajectory.
cartesianPositionAtDeparture Cartesian position of the body to be propagated at the leg departure [m].
cartesianPositionAtArrival Cartesian position of the body to be propagated at the leg arrival [m].
initialTime Time at departure [s].
timeOfFlight Time of flight for the leg [s].
propagatorSettings Propagator settings for the propagation of the full dynamics problem.
integratorSettings Integration settings for the full problem propagation.
patchedConicsResult Patched conics solution for the leg.
fullProblemResult Propagation results of the full problem over the leg.
Definition at line 274 of file propagationPatchedConicFullProblem.cpp.
References propagateLambertTargeterAndFullProblem().
Referenced by fullPropagationPatchedConicsTrajectory().
propagateMga1DsmVelocityAndFullProblem()
void tudat::propagators::propagateMga1DsmVelocityAndFullProblem (simulation_setup::NamedBodyMap & bodyMap, const std::vector< std::string > departureAndArrivalBodies, const std::string & dsm, const std::string & centralBody, const Eigen::Vector3d cartesianPositionAtDeparture, const Eigen::Vector3d cartesianPositionDSM, const Eigen::Vector3d cartesianPositionAtArrival, const double initialTime, const double timeDsm, const double timeArrival, const transfer_trajectories::TransferLegType & legType, const std::vector< double > & trajectoryVariableVector, const double semiMajorAxis, const double eccentricity, Eigen::Vector3d & velocityAfterDeparture, Eigen::Vector3d & velocityBeforeArrival, const std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > propagatorSettingsBeforeDsm, const std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > propagatorSettingsAfterDsm, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > & integratorSettings, std::map< double, Eigen::Vector6d > & patchedConicsResultFromDepartureToDsm, std::map< double, Eigen::Vector6d > & fullProblemResultFromDepartureToDsm, std::map< double, Eigen::VectorXd > & dependentVariablesFromDepartureToDsm, std::map< double, Eigen::Vector6d > & patchedConicsResultFromDsmToArrival, std::map< double, Eigen::Vector6d > & fullProblemResultFromDsmToArrival, std::map< double, Eigen::VectorXd > & dependentVariablesFromDsmToArrival)
Function to both calculate a patched conics leg including a DSM and propagate the corresponding full dynamics problem. The patched conics leg with DSM is calculated using the velocity formulation.
Parameters
bodyMap Body map for the patched conics leg.
departureAndArrivalBodies Vector containing the names of the departure and arrival bodies of the leg.
dsm Name of the DSM.
centralBody Name of the central body of the patched conics trajectory.
cartesianPositionAtDeparture Cartesian position of the body to be propagated at the leg departure [m].
cartesianPositionDSM Cartesian position of the body to be propagated at the DSM location [m].
cartesianPositionAtArrival Cartesian position of the body to be propagated at the leg arrival [m].
initialTime Time at departure [s].
timeDsm Time at which the DSM is to be performed [s].
timeArrival Time at arrival [s].
legType Type of the leg.
trajectoryVariableVector Trajectory variable vector characterising the leg.
semiMajorAxis Semi-major axis at trajectory departure (only used for a departure leg and not a swing-by one) [m].
eccentricity Eccentricity at trajectory departure (only used for a departure leg and not a swing-by one).
velocityAfterDeparture Velocity coordinates of the body to be propagated just after the swing-by it has performed about the departure body of the leg [m/s].
velocityBeforeArrival Velocity coordinates of the body to be propagated just before it reaches the arrival body of the leg [m/s].
propagatorSettingsBeforeDsm Propagator settings for the full problem propagation from the departure body to the DSM location.
propagatorSettingsAfterDsm Propagators settings for the full problem propagation from the DSM location to the arrival body.
integratorSettings Integrator settings for the propagation of the full dynamics problem.
patchedConicsResultFromDepartureToDsm Patched conics solution for the first part of the leg (from departure body to DSM).
fullProblemResultFromDepartureToDsm Propagation results of the full dynamics problem for the first part of the leg (from departure body to DSM).
patchedConicsResultFromDsmToArrival Patched conics solution for the second part of the leg (from DSM to arrival body).
fullProblemResultFromDsmToArrival Propagation results of the full dynamics problem for the second part of the leg (from DSM to arrival body).
Definition at line 303 of file propagationPatchedConicFullProblem.cpp.
References tudat::input_output::field_types::state::eccentricity, tudat::transfer_trajectories::mga1DsmVelocity_Departure, tudat::transfer_trajectories::mga1DsmVelocity_Swingby, propagateKeplerianOrbitLegAndFullProblem(), propagateLambertTargeterAndFullProblem(), and tudat::input_output::field_types::state::semiMajorAxis.
Referenced by fullPropagationPatchedConicsTrajectory().
propagateMga1DsmPositionAndFullProblem()
void tudat::propagators::propagateMga1DsmPositionAndFullProblem (simulation_setup::NamedBodyMap & bodyMap, const std::vector< std::string > departureAndArrivalBodies, const std::string & dsm, const std::string & centralBody, const Eigen::Vector3d cartesianPositionAtDeparture, const Eigen::Vector3d cartesianPositionDSM, const Eigen::Vector3d cartesianPositionAtArrival, const double initialTime, const double timeDsm, const double timeArrival, const transfer_trajectories::TransferLegType & legType, const std::vector< double > & trajectoryVariableVector, const double minimumPericenterRadius, const double semiMajorAxis, const double eccentricity, Eigen::Vector3d & velocityAfterDeparture, Eigen::Vector3d & velocityBeforeArrival, const std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > propagatorSettingsBeforeDsm, const std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > propagatorSettingsAfterDsm, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > & integratorSettings, std::map< double, Eigen::Vector6d > & patchedConicsResultFromDepartureToDsm, std::map< double, Eigen::Vector6d > & fullProblemResultFromDepartureToDsm, std::map< double, Eigen::VectorXd > & dependentVariablesFromDepartureToDsm, std::map< double, Eigen::Vector6d > & patchedConicsResultFromDsmToArrival, std::map< double, Eigen::Vector6d > & fullProblemResultFromDsmToArrival, std::map< double, Eigen::VectorXd > & dependentVariablesFromDsmToArrival)
Function to both calculate a patched conics leg including a DSM and propagate the corresponding full dynamics problem. The patched conics leg with DSM is calculated using the position formulation.
Parameters
bodyMap bodyMap Body map for the patched conics leg.
departureAndArrivalBodies Vector containing the names of the departure and arrival bodies of the leg.
dsm Name of the DSM.
centralBody Name of the central body of the patched conics trajectory.
cartesianPositionAtDeparture Cartesian position of the body to be propagated at the leg departure [m].
cartesianPositionDSM Cartesian position of the body to be propagated at the DSM location [m].
cartesianPositionAtArrival Cartesian position of the body to be propagated at the leg arrival [m].
initialTime Time at departure [s].
timeDsm Time at which the DSM is to be performed [s].
timeArrival Time at arrival [s].
legType Type of the leg.
trajectoryVariableVector Trajectory variable vector characterising the leg.
minimumPericenterRadius Minimum pericenter radius (only used for a swing-by leg and not a trajectory departure one).
semiMajorAxis Semi-major axis at trajectory departure (only used for a departure leg and not a swing-by one) [m].
eccentricity Eccentricity at trajectory departure (only used for a departure leg and not a swing-by one).
velocityAfterDeparture Velocity coordinates of the body to be propagated just after the swing-by it has performed about the departure body of the leg [m/s].
velocityBeforeArrival Velocity coordinates of the body to be propagated just before it reaches the arrival body of the leg [m/s].
propagatorSettingsBeforeDsm Propagator settings for the full problem propagation from the departure body to the DSM location.
propagatorSettingsAfterDsm Propagators settings for the full problem propagation from the DSM location to the arrival body.
integratorSettings Integrator settings for the propagation of the full dynamics problem.
patchedConicsResultFromDepartureToDsm Patched conics solution for the first part of the leg (from departure body to DSM).
fullProblemResultFromDepartureToDsm Propagation results of the full dynamics problem for the first part of the leg (from departure body to DSM).
patchedConicsResultFromDsmToArrival Patched conics solution for the second part of the leg (from DSM to arrival body).
fullProblemResultFromDsmToArrival Propagation results of the full dynamics problem for the second part of the leg (from DSM to arrival body).
Definition at line 418 of file propagationPatchedConicFullProblem.cpp.
References tudat::input_output::field_types::state::eccentricity, tudat::transfer_trajectories::mga1DsmPosition_Departure, tudat::transfer_trajectories::mga1DsmPosition_Swingby, propagateLambertTargeterAndFullProblem(), and tudat::input_output::field_types::state::semiMajorAxis.
Referenced by fullPropagationPatchedConicsTrajectory().
propagateKeplerianOrbitLegAndFullProblem()
void tudat::propagators::propagateKeplerianOrbitLegAndFullProblem (const double timeOfFlight, const double initialTime, const simulation_setup::NamedBodyMap & bodyMap, const std::string & centralBody, const std::vector< std::string > & departureAndArrivalBodies, const Eigen::Vector3d & velocityAfterDeparture, const std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > propagatorSettings, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, std::map< double, Eigen::Vector6d > & keplerianOrbitResult, std::map< double, Eigen::Vector6d > & fullProblemResult, std::map< double, Eigen::VectorXd > & dependentVariables, const double centralBodyGravitationalParameter, const Eigen::Vector3d & cartesianPositionAtDeparture)
Function to propagate the motion of a body over a trajectory leg, both along a keplerian orbit and in a full dynamics problem.
Parameters
timeOfFlight Time of flight during which the body has to be propagated [s]
initialTime Initial time [s].
bodyMap Body map defining the problem.
centralBody Name of the central body of the keplerian trajectory.
departureAndArrivalBodies Name of the departure and arrival bodies of the leg.
velocityAfterDeparture Velocity coordinates of the body to be propagated just after the swing-by it has performed about the departure body of the leg [m/s].
propagatorSettings Propagator settings for the propagation of the full dynamics problem.
integratorSettings Integrator settings for the propagation of the full dynamics problem.
keplerianOrbitResult Keplerian orbit solution.
fullProblemResult Propagation results of the full problem.
centralBodyGravitationalParameter Gravitational parameter of the central body [m^3 s^-2]. If not provided as input, it is retrieved from the body map.
cartesianPositionAtDeparture Cartesian position of the body to the propagated at the leg departure [m]. If not provided as input, it is retrieved from the ephemerides.
Definition at line 542 of file propagationPatchedConicFullProblem.cpp.
References tudat::orbital_element_conversions::convertCartesianToKeplerianElements(), tudat::orbital_element_conversions::convertKeplerianToCartesianElements(), tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getDependentVariableHistory(), tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getEquationsOfMotionNumericalSolution(), and tudat::orbital_element_conversions::propagateKeplerOrbit().
Referenced by propagateMga1DsmVelocityAndFullProblem().
getSingleLegPartSphereOfInfluenceTerminationSettings()
std::shared_ptr< propagators::PropagationTerminationSettings > tudat::propagators::getSingleLegPartSphereOfInfluenceTerminationSettings (simulation_setup::NamedBodyMap & bodyMap, const std::string & bodyToPropagate, const std::string & centralBody, const std::string & departureBody, const std::string & arrivalBody, const double initialTimeCurrentLeg, const double finalTimeCurrentLeg, const bool useBackwardLegToDepartureBody, const double terminationDistanceScaler)
Definition at line 690 of file propagationPatchedConicFullProblem.cpp.
References tudat::basic_astrodynamics::computeKeplerOrbitalPeriod(), tudat::mission_geometry::computeSphereOfInfluence(), tudat::basic_astrodynamics::computeSynodicPeriod(), tudat::orbital_element_conversions::convertCartesianToKeplerianElements(), relative_distance_dependent_variable, and tudat::orbital_element_conversions::semiMajorAxisIndex.
Referenced by getPatchedConicPropagatorSettings(), and getSingleLegSphereOfInfluenceTerminationSettings().
getSingleLegSphereOfInfluenceTerminationSettings()
std::pair< std::shared_ptr< propagators::PropagationTerminationSettings >, std::shared_ptr< propagators::PropagationTerminationSettings > > tudat::propagators::getSingleLegSphereOfInfluenceTerminationSettings (simulation_setup::NamedBodyMap & bodyMap, const std::string & bodyToPropagate, const std::string & centralBody, const std::string & departureBody, const std::string & arrivalBody, const double initialTimeCurrentLeg, const double finalTimeCurrentLeg, const double terminationDistanceScaler)
Definition at line 821 of file propagationPatchedConicFullProblem.cpp.
References getSingleLegPartSphereOfInfluenceTerminationSettings().
Referenced by getPatchedConicPropagatorSettings().
getPatchedConicPropagatorSettings()
std::vector< std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > > tudat::propagators::getPatchedConicPropagatorSettings (simulation_setup::NamedBodyMap & bodyMap, const std::vector< basic_astrodynamics::AccelerationMap > & accelerationMap, const std::vector< std::string > & transferBodyOrder, const std::string & centralBody, const std::string & bodyToPropagate, const std::vector< transfer_trajectories::TransferLegType > & legTypeVector, const std::vector< double > & trajectoryVariableVector, const std::vector< double > & minimumPericenterRadiiVector, const std::vector< double > & semiMajorAxesVector, const std::vector< double > & eccentricitiesVector, const std::vector< std::shared_ptr< DependentVariableSaveSettings > > dependentVariablesToSave, const TranslationalPropagatorType propagator, const bool terminationSphereOfInfluence, const double terminationDistanceScaler)
Definition at line 844 of file propagationPatchedConicFullProblem.cpp.
References tudat::transfer_trajectories::Trajectory::calculateTrajectory(), createTransferTrajectoryObject(), getSingleLegPartSphereOfInfluenceTerminationSettings(), getSingleLegSphereOfInfluenceTerminationSettings(), tudat::transfer_trajectories::Trajectory::maneuvers(), tudat::transfer_trajectories::mga_Departure, and tudat::transfer_trajectories::mga_Swingby.
Referenced by fullPropagationPatchedConicsTrajectory().
fullPropagationPatchedConicsTrajectory() [1/3]
void tudat::propagators::fullPropagationPatchedConicsTrajectory (simulation_setup::NamedBodyMap & bodyMap, const std::vector< std::string > & transferBodyOrder, const std::string & patchedConicCentralBody, const std::vector< transfer_trajectories::TransferLegType > & legTypeVector, const std::vector< double > & trajectoryVariableVector, const std::vector< double > & minimumPericenterRadiiVector, const std::vector< double > & semiMajorAxesVector, const std::vector< double > & eccentricitiesVector, const std::vector< std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > > propagatorSettings, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > & integratorSettings, std::map< int, std::map< double, Eigen::Vector6d > > & patchedConicsResultForEachLeg, std::map< int, std::map< double, Eigen::Vector6d > > & fullProblemResultForEachLeg, std::map< int, std::map< double, Eigen::VectorXd > > & dependentVariableResultForEachLeg)
Function to calculate the patched conics trajectory and to propagate the corresponding full problem. The propagator settings to be used for the propagation of the full dynamics problem are directly provided as inputs.
Parameters
bodyMap Body map for the patched conics trajectory.
transferBodyOrder Vector containing the names of the transfer bodies involved in the trajectory.
patchedConicCentralBody Name of the central body of the patched conics trajectory.
legTypeVector Vector containing the leg types.
trajectoryVariableVector Vector containing all the defining variables for the whole trajectory.
minimumPericenterRadiiVector Vector containing the minimum distance between the spacecraft and the body.
semiMajorAxesVector Vector containing the semi-major axes of the departure and arrival legs.
eccentricitiesVector Vector containing the eccentricities of the departure and arrival legs.
propagatorSettings Vector containing a pair of propagator settings for each leg (one for the backward and the other for the forward propagation)
integratorSettings Integrator settings for the propagation of the full problem.
patchedConicsResultForEachLeg Patched conics solution along each leg.
fullProblemResultForEachLeg Full problem propagation results along each leg.
Definition at line 1023 of file propagationPatchedConicFullProblem.cpp.
References tudat::transfer_trajectories::Trajectory::calculateTrajectory(), createTransferTrajectoryObject(), tudat::transfer_trajectories::Trajectory::maneuvers(), tudat::transfer_trajectories::mga1DsmPosition_Departure, tudat::transfer_trajectories::mga1DsmPosition_Swingby, tudat::transfer_trajectories::mga1DsmVelocity_Departure, tudat::transfer_trajectories::mga1DsmVelocity_Swingby, tudat::transfer_trajectories::mga_Departure, tudat::transfer_trajectories::mga_Swingby, propagateMga1DsmPositionAndFullProblem(), propagateMga1DsmVelocityAndFullProblem(), and propagateMgaWithoutDsmAndFullProblem().
Referenced by fullPropagationPatchedConicsTrajectory(), and getDifferenceFullProblemWrtPatchedConicsTrajectory().
fullPropagationPatchedConicsTrajectory() [2/3]
void tudat::propagators::fullPropagationPatchedConicsTrajectory (simulation_setup::NamedBodyMap & bodyMap, const std::vector< basic_astrodynamics::AccelerationMap > & accelerationMap, const std::vector< std::string > & transferBodyOrder, const std::string & centralBody, const std::string & bodyToPropagate, const std::vector< transfer_trajectories::TransferLegType > & legTypeVector, const std::vector< double > & trajectoryVariableVector, const std::vector< double > & minimumPericenterRadiiVector, const std::vector< double > & semiMajorAxesVector, const std::vector< double > & eccentricitiesVector, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > & integratorSettings, std::map< int, std::map< double, Eigen::Vector6d > > & patchedConicsResultForEachLeg, std::map< int, std::map< double, Eigen::Vector6d > > & fullProblemResultForEachLeg, std::map< int, std::map< double, Eigen::VectorXd > > & dependentVariableResultForEachLeg, const bool terminationSphereOfInfluence = false, const std::vector< std::shared_ptr< DependentVariableSaveSettings > > dependentVariablesToSave = std::vector< std::shared_ptr< DependentVariableSaveSettings > >(), const TranslationalPropagatorType propagator = cowell)
Function to calculate the patched conics trajectory and to propagate the corresponding full problem. The propagator settings for the full problem propagation are defined inside the function from the propagator type and dependent variables to save which are provided as inputs.
Parameters
bodyMap Body map for the patched conics trajectory.
accelerationMap Vector of acceleration maps for each leg to propagate the full problem.
transferBodyOrder Vector containing the names of the transfer bodies involved in the trajectory.
centralBody Name of the central body of the patched conics trajectory.
bodyToPropagate Name of the body to be propagated.
legTypeVector Vector containing the leg types.
trajectoryVariableVector Vector containing all the defining variables for the whole trajectory.
minimumPericenterRadiiVector Vector containing the minimum distance between the spacecraft and the body.
semiMajorAxesVector Vector containing the semi-major axes of the departure and arrival legs.
eccentricitiesVector Vector containing the eccentricities of the departure and arrival legs.
integratorSettings Integrator settings for the propagation of the full problem.
patchedConicsResultForEachLeg Patched conics solution along each leg.
fullProblemResultForEachLeg Full problem propagation results along each leg.
terminationSphereOfInfluence Boolean denoting whether the propagation stops at the exact position (false) or at the sphere of influence (true) of the departure and arrival body of each leg of the trajectory. The default value is false.
dependentVariablesToSave Vector containing the dependent variables to be saved during the full problem propagation for each leg.
propagator Type of propagator to be used for the full problem propagation.
Definition at line 1207 of file propagationPatchedConicFullProblem.cpp.
References fullPropagationPatchedConicsTrajectory(), and getPatchedConicPropagatorSettings().
fullPropagationPatchedConicsTrajectory() [3/3]
void tudat::propagators::fullPropagationPatchedConicsTrajectory (simulation_setup::NamedBodyMap & bodyMap, const basic_astrodynamics::AccelerationMap & accelerationMap, const std::vector< std::string > & transferBodyOrder, const std::string & centralBody, const std::string & bodyToPropagate, const std::vector< transfer_trajectories::TransferLegType > & legTypeVector, const std::vector< double > & trajectoryVariableVector, const std::vector< double > & minimumPericenterRadiiVector, const std::vector< double > & semiMajorAxesVector, const std::vector< double > & eccentricitiesVector, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > & integratorSettings, std::map< int, std::map< double, Eigen::Vector6d > > & patchedConicsResultForEachLeg, std::map< int, std::map< double, Eigen::Vector6d > > & fullProblemResultForEachLeg, std::map< int, std::map< double, Eigen::VectorXd > > & dependentVariableResultForEachLeg, const bool terminationSphereOfInfluence, const std::shared_ptr< DependentVariableSaveSettings > dependentVariablesToSave, const TranslationalPropagatorType propagator)
Function to calculate the patched conics trajectory and to propagate the corresponding full problem with the same acceleration map for every leg.
Function to calculate the patched conics trajectory and to propagate the corresponding full problem with the same acceleration map for every leg.
The propagator settings for the full problem propagation are defined inside the function from the propagator type and dependent variables to save provided as inputs.
Parameters
bodyMap Body map for the patched conics trajectory.
accelerationMap Acceleration map (to be used for every leg) to propagate the full problem.
transferBodyOrder Vector containing the names of the transfer bodies involved in the trajectory.
centralBody Name of the central body of the patched conics trajectory.
bodyToPropagate Name of the body to be propagated.
legTypeVector Vector containing the leg types.
trajectoryVariableVector Vector containing all the defining variables for the whole trajectory.
minimumPericenterRadiiVector Vector containing the minimum distance between the spacecraft and the body.
semiMajorAxesVector Vector containing the semi-major axes of the departure and arrival legs.
eccentricitiesVector Vector containing the eccentricities of the departure and arrival legs.
integratorSettings Integrator settings for the propagation of the full problem.
patchedConicsResultForEachLeg Patched conics solution along each leg.
fullProblemResultForEachLeg Full problem propagation results along each leg.
terminationSphereOfInfluence Boolean denoting whether the propagation stops at the exact position (false) or at the sphere of influence (true) of the departure and arrival body of each leg of the trajectory. The default value is false.
dependentVariablesToSave Vector containing the dependent variables to be saved during the full problem propagation for each leg.
propagator Type of propagator to be used for the full problem propagation.
Definition at line 1245 of file propagationPatchedConicFullProblem.cpp.
References fullPropagationPatchedConicsTrajectory().
getDifferenceFullProblemWrtPatchedConicsTrajectory() [1/3]
std::map< int, std::pair< Eigen::Vector6d, Eigen::Vector6d > > tudat::propagators::getDifferenceFullProblemWrtPatchedConicsTrajectory (simulation_setup::NamedBodyMap & bodyMap, const std::vector< basic_astrodynamics::AccelerationMap > & accelerationMap, const std::vector< std::string > & transferBodyOrder, const std::string & centralBody, const std::string & bodyToPropagate, const std::vector< transfer_trajectories::TransferLegType > & legTypeVector, const std::vector< double > & trajectoryVariableVector, const std::vector< double > & minimumPericenterRadiiVector, const std::vector< double > & semiMajorAxesVector, const std::vector< double > & eccentricitiesVector, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > & integratorSettings, const bool terminationSphereOfInfluence, const std::vector< std::shared_ptr< DependentVariableSaveSettings > > dependentVariablesToSave, const TranslationalPropagatorType propagator)
Function to compute the difference in cartesian state between patched conics trajectory and full dynamics problem, at both departure and arrival positions for each leg.
Function to compute the difference in cartesian state between patched conics trajectory and full dynamics problem, at both departure and arrival positions for each leg.
The propagator settings for the full problem propagation are defined inside the function from the propagator type and dependent variables to save provided as inputs.
Parameters
bodyMap Body map for the patched conics trajectory.
accelerationMap Vector of acceleration maps for each leg, to be used to propagate the full problem.
transferBodyOrder Vector containing the names of the transfer bodies involved in the trajectory.
centralBody Name of the central body of the patched conics trajectory.
bodyToPropagate Name of the body to be propagated.
legTypeVector Vector containing the leg types.
trajectoryVariableVector Vector containing all the defining variables for the whole trajectory.
minimumPericenterRadiiVector Vector containing the minimum distance between the spacecraft and the body.
semiMajorAxesVector Vector containing the semi-major axes of the departure and arrival legs.
eccentricitiesVector Vector containing the eccentricities of the departure and arrival legs.
integratorSettings Integrator settings for the propagation of the full problem.
terminationSphereOfInfluence Boolean denoting whether the propagation stops at the exact position (false) or at the sphere of influence (true) of the departure and arrival body of each leg of the trajectory. The default value is false.
dependentVariablesToSave Vector containing the dependent variables to be saved during the full problem propagation for each leg.
propagator Type of propagator to be used for the full problem propagation.
Returns
Map of vector pairs. Each vector pair contains the difference in cartesian state between patched conics trajectory and full problem for a given leg, at departure and arrival respectively.
Definition at line 1289 of file propagationPatchedConicFullProblem.cpp.
References fullPropagationPatchedConicsTrajectory().
Referenced by getDifferenceFullProblemWrtPatchedConicsTrajectory().
getDifferenceFullProblemWrtPatchedConicsTrajectory() [2/3]
std::map< int, std::pair< Eigen::Vector6d, Eigen::Vector6d > > tudat::propagators::getDifferenceFullProblemWrtPatchedConicsTrajectory (simulation_setup::NamedBodyMap & bodyMap, const std::vector< std::string > & transferBodyOrder, const std::string & centralBody, const std::vector< transfer_trajectories::TransferLegType > & legTypeVector, const std::vector< double > & trajectoryVariableVector, const std::vector< double > & minimumPericenterRadiiVector, const std::vector< double > & semiMajorAxesVector, const std::vector< double > & eccentricitiesVector, const std::vector< std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > > propagatorSettings, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > & integratorSettings)
Function to compute the difference in cartesian state between patched conics trajectory and full dynamics problem, at both departure and arrival positions for each leg.
Function to compute the difference in cartesian state between patched conics trajectory and full dynamics problem, at both departure and arrival positions for each leg.
The propagator settings to be used for the propagation of the full dynamics problem are directly provided as inputs.
Parameters
bodyMap Body map for the patched conics trajectory.
transferBodyOrder Vector containing the names of the transfer bodies involved in the trajectory.
centralBody Name of the central body of the patched conics trajectory.
legTypeVector Vector containing the leg types.
trajectoryVariableVector Vector containing all the defining variables for the whole trajectory.
minimumPericenterRadiiVector Vector containing the minimum distance between the spacecraft and the body.
semiMajorAxesVector Vector containing the semi-major axes of the departure and arrival legs.
eccentricitiesVector Vector containing the eccentricities of the departure and arrival legs.
propagatorSettings Vector containing a pair of propagator settings for each leg (one for the backward and the other for the forward propagation)
integratorSettings Integrator settings for the propagation of the full problem.
Returns
Map of vector pairs. Each vector pair contains the difference in cartesian state between patched conics trajectory and full problem for a given leg, at departure and arrival respectively.
Definition at line 1345 of file propagationPatchedConicFullProblem.cpp.
References fullPropagationPatchedConicsTrajectory().
getDifferenceFullProblemWrtPatchedConicsTrajectory() [3/3]
std::map< int, std::pair< Eigen::Vector6d, Eigen::Vector6d > > tudat::propagators::getDifferenceFullProblemWrtPatchedConicsTrajectory (simulation_setup::NamedBodyMap & bodyMap, const basic_astrodynamics::AccelerationMap & accelerationMap, const std::vector< std::string > & transferBodyOrder, const std::string & centralBody, const std::string & bodyToPropagate, const std::vector< transfer_trajectories::TransferLegType > & legTypeVector, const std::vector< double > & trajectoryVariableVector, const std::vector< double > & minimumPericenterRadiiVector, const std::vector< double > & semiMajorAxesVector, const std::vector< double > & eccentricitiesVector, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > & integratorSettings, const bool terminationSphereOfInfluence, const std::shared_ptr< DependentVariableSaveSettings > dependentVariablesToSave, const TranslationalPropagatorType propagator)
Function to compute the difference in cartesian state between patched conics trajectory and full dynamics problem, at both departure and arrival positions for each leg, using the same accelerations for each leg.
Function to compute the difference in cartesian state between patched conics trajectory and full dynamics problem, at both departure and arrival positions for each leg, using the same accelerations for each leg.
The propagator settings for the full problem propagation are defined inside the function from the propagator type and dependent variables to save provided as inputs.
Parameters
bodyMap Body map for the patched conics trajectory.
accelerationMap Acceleration map (to be used for every leg) to propagate the full problem.
transferBodyOrder Vector containing the names of the transfer bodies involved in the trajectory.
centralBody Name of the central body of the patched conics trajectory.
bodyToPropagate Name of the body to be propagated.
legTypeVector Vector containing the leg types.
trajectoryVariableVector Vector containing all the defining variables for the whole trajectory.
minimumPericenterRadiiVector Vector containing the minimum distance between the spacecraft and the body.
semiMajorAxesVector Vector containing the semi-major axes of the departure and arrival legs.
eccentricitiesVector Vector containing the eccentricities of the departure and arrival legs.
integratorSettings Integrator settings for the propagation of the full problem.
terminationSphereOfInfluence Boolean denoting whether the propagation stops at the exact position (false) or at the sphere of influence (true) of the departure and arrival body of each leg of the trajectory. The default value is false.
dependentVariablesToSave Vector containing the dependent variables to be saved during the full problem propagation for each leg.
propagator Type of propagator to be used for the full problem propagation.
Returns
Map of vector pairs. Each vector pair contains the difference in cartesian state between patched conics trajectory and full problem for a given leg, at departure and arrival respectively.
Definition at line 1397 of file propagationPatchedConicFullProblem.cpp.
References getDifferenceFullProblemWrtPatchedConicsTrajectory().
getIntegratedTypeAndBodyList< double >()
template std::map< IntegratedStateType, std::vector< std::pair< std::string, std::string > > > tudat::propagators::getIntegratedTypeAndBodyList< double > (const std::shared_ptr< SingleArcPropagatorSettings< double > > propagatorSettings)
Referenced by resetSingleArcInitialStates().
getConcatenatedStateSize()
template<typename StateScalarType = double> int tudat::propagators::getConcatenatedStateSize (const std::vector< std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > > & singleArcPropagatorSettings)
Function to get the total size of multi-arc initial state vector, e.g. the size of the single-arc initial states, concatenated into a single vector
Parameters
singleArcPropagatorSettings ist of single-arc propagation settings for which the concatenated initial state size is to be determined.
Returns
Total size of multi-arc initial state vector
Definition at line 269 of file propagationSettings.h.
Referenced by getConcatenatedInitialStates().
getConcatenatedInitialStates()
template<typename StateScalarType = double> Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > tudat::propagators::getConcatenatedInitialStates (const std::vector< std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > > & singleArcPropagatorSettings)
Function to concatenate the initial states for a list of single-arc propagations into a single list.
Parameters
singleArcPropagatorSettings List of single-arc propagation settings for which the initial states are to be concatenated into a single vector.
Returns
Vector with concatenated initial states from singleArcPropagatorSettings.
Definition at line 290 of file propagationSettings.h.
References getConcatenatedStateSize().
Referenced by tudat::propagators::MultiArcPropagatorSettings< StateScalarType >::MultiArcPropagatorSettings().
convertScalarToVectorStateFunction()
template<typename StateScalarType = double, typename TimeType = double> Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > tudat::propagators::convertScalarToVectorStateFunction (const std::function< StateScalarType(const TimeType, const StateScalarType) > stateDerivativeFunction, const TimeType currentTime, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > & currentStateVector)
Function to evaluate a floating point state-derivative function as though it was a vector state function.
Parameters
stateDerivativeFunction Function to compute the state derivative, as a function of current time and state.
currentTime Time at which to evaluate the state derivative function
currentStateVector Vector of size 1 containing the current state
Returns
Current state derivative (as vector of size 1).
Definition at line 1097 of file propagationSettings.h.
getExtendedMultiPropagatorSettings()
template<typename StateScalarType = double> std::shared_ptr< MultiArcPropagatorSettings< StateScalarType > > tudat::propagators::getExtendedMultiPropagatorSettings (const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > singleArcSettings, const std::shared_ptr< MultiArcPropagatorSettings< StateScalarType > > multiArcSettings, const int numberofArcs)
Function to create multi-arc propagator settings by merging an existing multi-arc with single-arc settings. The single-arc settings are converted to multi-arc, and the single-arc propagated bodies are appended at the beginning of the vector of propagated bodies. Currently, only translational dynamics is supported.
Parameters
singleArcSettings Single-arc settings that are to be added (to the head of the list of propagated bodies) of the input multi-arc settings.
multiArcSettings Multi-arc settings that are to be extended
numberofArcs Number of arcs in which the single-arc dynamics is to be split
Returns
Multi-arc propagator settings by merging an existing multi-arc with single-arc settings
Definition at line 1204 of file propagationSettings.h.
References translational_state, and TUDAT_NAN.
Referenced by tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::initializeHybridArcVariationalEquationsSolver().
getMultiTypePropagatorStateSize()
template<typename StateScalarType > int tudat::propagators::getMultiTypePropagatorStateSize (const std::map< IntegratedStateType, std::vector< std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > > > & propagatorSettingsList)
Function to retrieve the initial state for a list of propagator settings.
Parameters
propagatorSettingsList List of propagator settings (sorted by type as key). Map value provides list of propagator settings for given type.
Returns
Vector of initial states, sorted in order of IntegratedStateType, and then in the order of the vector of SingleArcPropagatorSettings of given type.
Definition at line 1328 of file propagationSettings.h.
Referenced by createCombinedInitialState(), and tudat::propagators::MultiTypePropagatorSettings< StateScalarType >::MultiTypePropagatorSettings().
createCombinedInitialState()
template<typename StateScalarType > Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > tudat::propagators::createCombinedInitialState (const std::map< IntegratedStateType, std::vector< std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > > > & propagatorSettingsList)
Function to retrieve the initial state for a list of propagator settings.
Parameters
propagatorSettingsList List of propagator settings (sorted by type as key). Map value provides list of propagator settings for given type.
Returns
Vector of initial states, sorted in order of IntegratedStateType, and then in the order of the vector of SingleArcPropagatorSettings of given type.
Definition at line 1356 of file propagationSettings.h.
References getMultiTypePropagatorStateSize().
getAccelerationMapFromPropagatorSettings()
template<typename StateScalarType = double> basic_astrodynamics::AccelerationMap tudat::propagators::getAccelerationMapFromPropagatorSettings (const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > singleArcPropagatorSettings)
Function to retrieve list of accelerations from propagator settings. Extracts the translational dynamics elements, and the associated acceleration models
Parameters
singleArcPropagatorSettings Propagator settings
Returns
List of acceleration models
Definition at line 1594 of file propagationSettings.h.
References hybrid, and translational_state.
Referenced by tudat::simulation_setup::getAccelerationModelsListForParameters().
getIntegratedTypeAndBodyList()
template<typename StateScalarType > std::map< IntegratedStateType, std::vector< std::pair< std::string, std::string > > > tudat::propagators::getIntegratedTypeAndBodyList (const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings)
Function to retrieve the list of integrated state types and reference ids. For translational and rotational dynamics, the id refers only to the body being propagated (and the second entry of the pair is empty: ""). For proper time propagation, a body and a reference point may be provided, resulting in non-empty first and second pair entries.
Parameters
propagatorSettings Settings that are to be used for the propagation.
Returns
List of integrated state types and reference ids
Definition at line 1643 of file propagationSettings.h.
References body_mass_state, custom_state, hybrid, rotational_state, and translational_state.
Referenced by createEnvironmentUpdaterSettings().
resetSingleArcInitialStates()
template<typename StateScalarType > void tudat::propagators::resetSingleArcInitialStates (const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings, const std::map< propagators::IntegratedStateType, std::map< std::pair< std::string, std::string >, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > > currentArcInitialStates)
Definition at line 1772 of file propagationSettings.h.
References tudat::propagators::TranslationalStatePropagatorSettings< StateScalarType >::bodiesToIntegrate_, getIntegratedTypeAndBodyList< double >(), and translational_state.
Referenced by tudat::simulation_setup::setInitialStateVectorFromParameterSet().
createPropagationTerminationConditions()
std::shared_ptr< PropagationTerminationCondition > tudat::propagators::createPropagationTerminationConditions (const std::shared_ptr< PropagationTerminationSettings > terminationSettings, const simulation_setup::NamedBodyMap & bodyMap, const double initialTimeStep)
Function to create propagation termination conditions from associated settings
Parameters
terminationSettings Settings for propagation termination conditions
bodyMap List of body objects that contains all environment models
initialTimeStep Time step at first call of numerical integration.
Returns
Object used to check whether propagation is to be stopped or not.
Definition at line 118 of file propagationTermination.cpp.
References cpu_time_stopping_condition, custom_stopping_condition, dependent_variable_stopping_condition, getDependentVariableSaveSize(), getDoubleDependentVariableFunction(), hybrid_stopping_condition, and time_stopping_condition.
Referenced by tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::resetPropagationTerminationConditions(), and tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::SingleArcDynamicsSimulator().
checkTranslationalStatesFeasibility()
void tudat::propagators::checkTranslationalStatesFeasibility (const std::vector< std::string > & bodiesToIntegrate, const simulation_setup::NamedBodyMap & bodyMap)
Function to check the feasibility of resetting the translational dynamics of a set of bodies. Function throws error if not feasible.
Parameters
bodiesToIntegrate List of bodies to integrate.
bodyMap List of bodies used in simulations.
Definition at line 22 of file setNumericallyIntegratedStates.cpp.
Referenced by createIntegratedStateProcessors().
createStateInterpolator() [1/5]
template<> std::shared_ptr< interpolators::OneDimensionalInterpolator< double, Eigen::Matrix< double, 6, 1 > > > tudat::propagators::createStateInterpolator (const std::map< double, Eigen::Matrix< double, 6, 1 > > & stateMap)
Definition at line 72 of file setNumericallyIntegratedStates.cpp.
Referenced by convertNumericalSolutionToRotationalEphemerisInput(), resetIntegratedEphemerisOfBody(), and resetMultiArcIntegratedEphemerides().
createStateInterpolator() [2/5]
template<> std::shared_ptr< interpolators::OneDimensionalInterpolator< double, Eigen::Matrix< long double, 6, 1 > > > tudat::propagators::createStateInterpolator (const std::map< double, Eigen::Matrix< long double, 6, 1 > > & stateMap)
Definition at line 82 of file setNumericallyIntegratedStates.cpp.
createStateInterpolator() [3/5]
template<> std::shared_ptr< interpolators::OneDimensionalInterpolator< Time, Eigen::Matrix< long double, 6, 1 > > > tudat::propagators::createStateInterpolator (const std::map< Time, Eigen::Matrix< long double, 6, 1 > > & stateMap)
Definition at line 91 of file setNumericallyIntegratedStates.cpp.
createStateInterpolator() [4/5]
template<> std::shared_ptr< interpolators::OneDimensionalInterpolator< Time, Eigen::Matrix< double, 6, 1 > > > tudat::propagators::createStateInterpolator (const std::map< Time, Eigen::Matrix< double, 6, 1 > > & stateMap)
Definition at line 101 of file setNumericallyIntegratedStates.cpp.
createRotationalStateInterpolator() [1/5]
template<> std::shared_ptr< interpolators::OneDimensionalInterpolator< double, Eigen::Matrix< double, 7, 1 > > > tudat::propagators::createRotationalStateInterpolator (const std::map< double, Eigen::Matrix< double, 7, 1 > > & stateMap)
Definition at line 110 of file setNumericallyIntegratedStates.cpp.
Referenced by convertNumericalSolutionToRotationalEphemerisInput(), and createAndSetInterpolatorsForRotationalEphemerides().
createRotationalStateInterpolator() [2/5]
template<> std::shared_ptr< interpolators::OneDimensionalInterpolator< double, Eigen::Matrix< long double, 7, 1 > > > tudat::propagators::createRotationalStateInterpolator (const std::map< double, Eigen::Matrix< long double, 7, 1 > > & stateMap)
Definition at line 117 of file setNumericallyIntegratedStates.cpp.
createRotationalStateInterpolator() [3/5]
template<> std::shared_ptr< interpolators::OneDimensionalInterpolator< Time, Eigen::Matrix< double, 7, 1 > > > tudat::propagators::createRotationalStateInterpolator (const std::map< Time, Eigen::Matrix< double, 7, 1 > > & stateMap)
Definition at line 124 of file setNumericallyIntegratedStates.cpp.
createRotationalStateInterpolator() [4/5]
template<> std::shared_ptr< interpolators::OneDimensionalInterpolator< Time, Eigen::Matrix< long double, 7, 1 > > > tudat::propagators::createRotationalStateInterpolator (const std::map< Time, Eigen::Matrix< long double, 7, 1 > > & stateMap)
Definition at line 131 of file setNumericallyIntegratedStates.cpp.
createStateInterpolator() [5/5]
template<typename TimeType , typename StateScalarType > std::shared_ptr< interpolators::OneDimensionalInterpolator< TimeType, Eigen::Matrix< StateScalarType, 6, 1 > > > tudat::propagators::createStateInterpolator (const std::map< TimeType, Eigen::Matrix< StateScalarType, 6, 1 > > & stateMap)
Function to create an interpolator for the new translational state of a body.
Parameters
stateMap New state history, w.r.t. the required ephemeris origin.
Returns
Lagrange interpolator (order 6) that produces the required continuous state.
resetIntegratedEphemerisOfBody() [1/2]
template<typename StateTimeType , typename StateScalarType , typename EphemerisTimeType , typename EphemerisScalarType > void tudat::propagators::resetIntegratedEphemerisOfBody (const std::map< StateTimeType, Eigen::Matrix< StateScalarType, 6, 1 > > & ephemerisInput, const std::shared_ptr< ephemerides::TabulatedCartesianEphemeris< EphemerisScalarType, EphemerisTimeType > > tabulatedEphemeris)
Function to reset the tabulated ephemeris of a body
Parameters
ephemerisInput New state history that is to be set
tabulatedEphemeris Ephemeris in which the ephemerisInput is to be set.
Definition at line 48 of file setNumericallyIntegratedStates.h.
References createStateInterpolator().
Referenced by createAndSetInterpolatorsForEphemerides(), and resetIntegratedEphemerisOfBody().
resetIntegratedEphemerisOfBody() [2/2]
template<typename TimeType , typename StateScalarType > void tudat::propagators::resetIntegratedEphemerisOfBody (const simulation_setup::NamedBodyMap & bodyMap, const std::map< TimeType, Eigen::Matrix< StateScalarType, 6, 1 > > & ephemerisInput, const std::string & bodyToIntegrate)
Function to reset the tabulated ephemeris of a body, this requires the requested body to possess an ephemeris of type TabulatedCartesianEphemeris< StateScalarType, TimeType >
Parameters
bodyMap List of bodies used in simulations.
ephemerisInput New state history of the body
bodyToIntegrate Name of body for which the ephemeris is to be reset.
Definition at line 70 of file setNumericallyIntegratedStates.h.
References createStateInterpolator(), tudat::ephemerides::isTabulatedEphemeris(), resetIntegratedEphemerisOfBody(), and tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >::resetInterpolator().
convertNumericalSolutionToEphemerisInput()
template<typename TimeType , typename StateScalarType > void tudat::propagators::convertNumericalSolutionToEphemerisInput (const int bodyIndex, const int startIndex, const std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > & equationsOfMotionNumericalSolution, std::map< TimeType, Eigen::Matrix< StateScalarType, 6, 1 > > & ephemerisTable, const std::function< Eigen::Matrix< StateScalarType, 6, 1 >(const TimeType) > integrationToEphemerisFrameFunction = nullptr)
Function to convert output of translational motion from the numerical integrator to the required input for the ephemeris. It extracts the state history of a single body from the full list of integrated states Additionally, it changes the origin of the reference frame in which the states are given, by using the integrationToEphemerisFrameFunction input variable.
Parameters
bodyIndex Index of integrated body for which the state is to be retrieved
startIndex Index in entries of equationsOfMotionNumericalSolution where the translational states start.
equationsOfMotionNumericalSolution Full numerical solution of numerical integrator, already converted to Cartesian states (w.r.t. the integration origin of the body of bodyIndex)
ephemerisTable State history of body bodyIndex w.r.t. the origin with which its ephemeris is defined (returned by reference).
integrationToEphemerisFrameFunction Function to provide the state of the ephemeris origin of the current body w.r.t. its integration origin.
Definition at line 160 of file setNumericallyIntegratedStates.h.
Referenced by getSingleBodyStateHistoryFromPropagationOutpiut(), and resetMultiArcIntegratedEphemerides().
getSingleBodyStateHistoryFromPropagationOutpiut()
template<typename TimeType , typename StateScalarType > void tudat::propagators::getSingleBodyStateHistoryFromPropagationOutpiut (const std::vector< std::string > & bodiesToIntegrate, const int translationalStateStartIndex, const std::string & bodyForWhichToRetrieveState, const std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > & equationsOfMotionNumericalSolution, std::map< TimeType, Eigen::Matrix< StateScalarType, 6, 1 > > & ephemerisInput, int & bodyIndex, const std::map< std::string, std::function< Eigen::Matrix< StateScalarType, 6, 1 >(const TimeType) > > & integrationToEphemerisFrameFunctions = std::map< std::string, std::function< Eigen::Matrix< StateScalarType, 6, 1 >(const TimeType) > >())
Function to extract the numerical solution for the translational dynamics of a single body from full propagation history. Function can perform frame translation if required.
Parameters
bodiesToIntegrate List of names of bodies which are numericall integrated (in the order in which they are in the equationsOfMotionNumericalSolution map.
translationalStateStartIndex Index in entries of equationsOfMotionNumericalSolution where the translational states start
bodyForWhichToRetrieveState Name of body for which the states are to be extracted
equationsOfMotionNumericalSolution Numerical solution of dynamics, with translational results in Cartesian elements w.r.t. integratation origins.
ephemerisInput State history of requested body (returned by reference)
bodyIndex Index of bodyForWhichToRetrieveState in bodiesToIntegrate (returned by reference)
integrationToEphemerisFrameFunctions Function to provide the states of the ephemeris origins of each body w.r.t. their respective integration origins.
Definition at line 210 of file setNumericallyIntegratedStates.h.
References convertNumericalSolutionToEphemerisInput().
Referenced by createAndSetInterpolatorsForEphemerides().
createAndSetInterpolatorsForEphemerides()
template<typename TimeType , typename StateScalarType > void tudat::propagators::createAndSetInterpolatorsForEphemerides (const simulation_setup::NamedBodyMap & bodyMap, const std::vector< std::string > & bodiesToIntegrate, const int startIndex, const std::vector< std::string > & ephemerisUpdateOrder, const std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > & equationsOfMotionNumericalSolution, const std::map< std::string, std::function< Eigen::Matrix< StateScalarType, 6, 1 >(const TimeType) > > & integrationToEphemerisFrameFunctions = std::map< std::string, std::function< Eigen::Matrix< StateScalarType, 6, 1 >(const TimeType) > >())
Creates and resets the interpolator for the ephemerides of the integrated bodies from the numerical integration results.
Parameters
bodyMap List of bodies used in simulations.
bodiesToIntegrate List of names of bodies which are numericall integrated (in the order in which they are in the equationsOfMotionNumericalSolution map.
startIndex Index in entries of equationsOfMotionNumericalSolution where the translational states start.
ephemerisUpdateOrder Order in which to update the ephemeris objects.
equationsOfMotionNumericalSolution Numerical solution of translational equations of motion, in Cartesian elements w.r.t. integratation origins.
integrationToEphemerisFrameFunctions Function to provide the states of the ephemeris origins of each body w.r.t. their respective integration origins.
Definition at line 259 of file setNumericallyIntegratedStates.h.
References getSingleBodyStateHistoryFromPropagationOutpiut(), and resetIntegratedEphemerisOfBody().
Referenced by resetIntegratedEphemerides().
resetIntegratedEphemerides()
template<typename TimeType , typename StateScalarType > void tudat::propagators::resetIntegratedEphemerides (const simulation_setup::NamedBodyMap & bodyMap, const std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > & equationsOfMotionNumericalSolution, const std::vector< std::string > & bodiesToIntegrate, const std::pair< unsigned int, unsigned int > startIndexAndSize, std::vector< std::string > ephemerisUpdateOrder = std::vector< std::string >(), const std::map< std::string, std::function< Eigen::Matrix< StateScalarType, 6, 1 >(const TimeType) > > & integrationToEphemerisFrameFunctions = std::map< std::string, std::function< Eigen::Matrix< StateScalarType, 6, 1 >(const TimeType) > >())
Resets the ephemerides of the integrated bodies from the numerical integration results, and performs associated computation for ephemeris-dependent environment variables.
Parameters
bodyMap List of bodies used in simulations.
bodiesToIntegrate List of names of bodies which are numerically integrated (in the order in which they are in the equationsOfMotionNumericalSolution map.
startIndexAndSize Pair with start index and total (contiguous) size of integrated states in entries of equationsOfMotionNumericalSolution
ephemerisUpdateOrder Order in which to update the ephemeris objects (empty if arbitrary).
equationsOfMotionNumericalSolution Numerical solution of translational equations of motion, in Cartesian elements w.r.t. integratation origins.
integrationToEphemerisFrameFunctions Function to provide the states of the ephemeris origins of each body w.r.t. their respective integration origins.
Definition at line 302 of file setNumericallyIntegratedStates.h.
References createAndSetInterpolatorsForEphemerides().
resetMultiArcIntegratedEphemerides()
template<typename TimeType , typename StateScalarType > void tudat::propagators::resetMultiArcIntegratedEphemerides (const simulation_setup::NamedBodyMap & bodyMap, const std::vector< std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > > & equationsOfMotionNumericalSolution, const std::vector< double > arcStartTimes, const std::vector< std::string > & bodiesToIntegrate, const std::pair< unsigned int, unsigned int > startIndexAndSize, std::vector< std::string > ephemerisUpdateOrder = std::vector< std::string >(), const std::map< std::string, std::function< Eigen::Matrix< StateScalarType, 6, 1 >(const TimeType) > > & integrationToEphemerisFrameFunctions = std::map< std::string, std::function< Eigen::Matrix< StateScalarType, 6, 1 >(const TimeType) > >())
Resets the ephemerides of the integrated bodies from the numerical multi-arc integration results, and performs associated computation for ephemeris-dependent environment variables.
Parameters
bodyMap List of bodies used in simulations.
equationsOfMotionNumericalSolution Numerical multi-arc solution of translational equations of motion, in Cartesian elements w.r.t. integratation origins (one vector entry represents one arc).
arcStartTimes List of start times of the propagation arcs.
bodiesToIntegrate List of names of bodies which are numerically integrated (in the order in which they are in the equationsOfMotionNumericalSolution map.
startIndexAndSize Pair with start index and total (contiguous) size of integrated states in entries of equationsOfMotionNumericalSolution
ephemerisUpdateOrder Order in which to update the ephemeris objects (empty if arbitrary).
integrationToEphemerisFrameFunctions Function to provide the states of the ephemeris origins of each body w.r.t. their respective integration origins.
Definition at line 358 of file setNumericallyIntegratedStates.h.
References convertNumericalSolutionToEphemerisInput(), and createStateInterpolator().
resetIntegratedRotationalEphemerisOfBody()
template<typename TimeType , typename StateScalarType > void tudat::propagators::resetIntegratedRotationalEphemerisOfBody (const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< interpolators::OneDimensionalInterpolator< TimeType, Eigen::Matrix< StateScalarType, 7, 1 > > > rotationalEphemerisInterpolator, const std::string bodyToIntegrate)
Function to reset the tabulatedrotational ephemeris of a body, this requires the requested body to possess a rotational ephemeris of type TabulatedRotationalEphemeris< StateScalarType, TimeType >
Parameters
bodyMap List of bodies used in simulations.
rotationalEphemerisInterpolator New rotational state history of the body
bodyToIntegrate Name of body for which the rotational ephemeris is to be reset.
Definition at line 444 of file setNumericallyIntegratedStates.h.
References tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::reset().
Referenced by createAndSetInterpolatorsForRotationalEphemerides().
convertNumericalSolutionToRotationalEphemerisInput()
template<typename TimeType , typename StateScalarType > void tudat::propagators::convertNumericalSolutionToRotationalEphemerisInput (const int startIndex, const int bodyIndex, std::map< TimeType, Eigen::Matrix< StateScalarType, 7, 1 > > & ephemerisTable, const std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > & equationsOfMotionNumericalSolution)
Function to convert output of rotational motion from the numerical integrator to the required input for the rotational ephemeris. It extracts the state history of a single body from the full list of integrated states.
Parameters
startIndex Index in entries of equationsOfMotionNumericalSolution where the rotational states start.
bodyIndex Index of integrated body for which the state is to be retrieved
ephemerisTable State history of body bodyIndex w.r.t. the origin with which its ephemeris is defined (returned by reference).
equationsOfMotionNumericalSolution Full numerical solution of numerical integrator, already converted to Cartesian states (w.r.t. the integration origin of the body of bodyIndex)
Definition at line 488 of file setNumericallyIntegratedStates.h.
References createRotationalStateInterpolator(), and createStateInterpolator().
Referenced by createAndSetInterpolatorsForRotationalEphemerides().
createRotationalStateInterpolator() [5/5]
template<typename TimeType , typename StateScalarType > std::shared_ptr< interpolators::OneDimensionalInterpolator< TimeType, Eigen::Matrix< StateScalarType, 7, 1 > > > tudat::propagators::createRotationalStateInterpolator (const std::map< TimeType, Eigen::Matrix< StateScalarType, 7, 1 > > & stateMap)
Function to create an interpolator for the new rotational state of a body.
Parameters
stateMap New rotational state history.
Returns
Lagrange interpolator (order 6) that produces the required continuous rotational state.
createAndSetInterpolatorsForRotationalEphemerides()
template<typename TimeType , typename StateScalarType > void tudat::propagators::createAndSetInterpolatorsForRotationalEphemerides (const simulation_setup::NamedBodyMap & bodyMap, const std::vector< std::string > & bodiesToIntegrate, const int startIndex, const std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > & equationsOfMotionNumericalSolution)
Function to reset the tabulated rotational ephemeris of a body
Parameters
bodyMap List of bodies used in simulations.
bodiesToIntegrate List of names of bodies for which rotational state is numerically integrated
startIndex Index in the state vector where the rotational state starts.
equationsOfMotionNumericalSolution New rotational state history that is to be set
Definition at line 532 of file setNumericallyIntegratedStates.h.
References convertNumericalSolutionToRotationalEphemerisInput(), createRotationalStateInterpolator(), and resetIntegratedRotationalEphemerisOfBody().
Referenced by resetIntegratedRotationalEphemerides().
resetIntegratedRotationalEphemerides()
template<typename TimeType , typename StateScalarType > void tudat::propagators::resetIntegratedRotationalEphemerides (const simulation_setup::NamedBodyMap & bodyMap, const std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > & equationsOfMotionNumericalSolution, const std::vector< std::string > & bodiesToIntegrate, const std::pair< unsigned int, unsigned int > startIndexAndSize)
Resets the rotational ephemerides of a set of bodies from the numerical integration results, and performs associated computation for ephemeris-dependent environment variables.
Parameters
bodyMap List of bodies used in simulations.
equationsOfMotionNumericalSolution Numerical solution of rotational equations of motion
bodiesToIntegrate List of names of bodies which are numerically integrated
startIndexAndSize Pair with start index and total (contiguous) size of integrated states in entries of equationsOfMotionNumericalSolution
Definition at line 567 of file setNumericallyIntegratedStates.h.
References createAndSetInterpolatorsForRotationalEphemerides().
resetIntegratedBodyMass()
template<typename TimeType , typename StateScalarType > void tudat::propagators::resetIntegratedBodyMass (const simulation_setup::NamedBodyMap & bodyMap, const std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > & equationsOfMotionNumericalSolution, const std::vector< std::string > & bodiesToIntegrate, const std::pair< unsigned int, unsigned int > startIndexAndSize)
Resets the mass models of the integrated bodies from the numerical integration results.
Parameters
bodyMap List of bodies used in simulations.
equationsOfMotionNumericalSolution Numerical solution of the body masses.
bodiesToIntegrate List of names of bodies for which mass is numerically integrated (in the order in which they are in the equationsOfMotionNumericalSolution map.
startIndexAndSize Pair with start index and total (contiguous) size of integrated states in entries of equationsOfMotionNumericalSolution
Definition at line 597 of file setNumericallyIntegratedStates.h.
Referenced by tudat::propagators::BodyMassIntegratedStateProcessor< TimeType, StateScalarType >::processIntegratedStates().
createIntegratedStateProcessors()
template<typename TimeType , typename StateScalarType > std::map< IntegratedStateType,std::vector< std::shared_ptr< IntegratedStateProcessor< TimeType, StateScalarType > > > > tudat::propagators::createIntegratedStateProcessors (const std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< ephemerides::ReferenceFrameManager > frameManager, const int startIndex = 0)
Function to create list objects for processing numerically integrated results, so that all results are set in the environment models (i.e. resetting tabulated ephemeris for translational dynamics).
Parameters
propagatorSettings Settings for the propagation that is used
bodyMap List of body objects that represents the environemnt
frameManager Object for providinf conversion functions between different ephemeris origins.
startIndex Index of state vector where the state entries handled with propagatorSettings starts.
Returns
List objects for processing numerically integrated results.
Definition at line 944 of file setNumericallyIntegratedStates.h.
References body_mass_state, checkTranslationalStatesFeasibility(), custom_state, hybrid, rotational_state, and translational_state.
resetIntegratedStates()
template<typename TimeType , typename StateScalarType > void tudat::propagators::resetIntegratedStates (const std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > & equationsOfMotionNumericalSolution, const std::map< IntegratedStateType, std::vector< std::shared_ptr< IntegratedStateProcessor< TimeType, StateScalarType > > > > integratedStateProcessors)
Function to reset the dynamical properties of the environment from the numerically integrated dynamics solution
Parameters
equationsOfMotionNumericalSolution Solution produced by the numerical integration, in the 'conventional form'
See also
SingleStateTypeDerivative::convertToOutputSolution
Parameters
integratedStateProcessors List of objects (per dynamics type) used to process integrated results into environment
Definition at line 1094 of file setNumericallyIntegratedStates.h.
Referenced by tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::processNumericalEquationsOfMotionSolution().
resetIntegratedMultiArcStatesWithEqualArcDynamics()
template<typename TimeType , typename StateScalarType > void tudat::propagators::resetIntegratedMultiArcStatesWithEqualArcDynamics (const std::vector< std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > > & equationsOfMotionNumericalSolution, const std::map< IntegratedStateType, std::vector< std::shared_ptr< IntegratedStateProcessor< TimeType, StateScalarType > > > > integratedStateProcessors, const std::vector< double > & arcStartTimes)
Function to reset the dynamical properties of the environment from the numerically integrated multi-arc dynamics solution
Parameters
equationsOfMotionNumericalSolution Solution produced by the numerical integration, in the 'conventional form'. One vector entry contains the data for one arc
See also
SingleStateTypeDerivative::convertToOutputSolution
Parameters
integratedStateProcessors List of objects (per dynamics type) used to process integrated results into environment
arcStartTimes List of start times of the propagation arcs.
Definition at line 1123 of file setNumericallyIntegratedStates.h.
Referenced by tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::processNumericalEquationsOfMotionSolution().
Variable Documentation
integratedStateTypes
std::map< IntegratedStateType, std::string > tudat::propagators::integratedStateTypes static
Initial value:
=
{
    { hybrid, "hybrid" },
    { translational_state, "translational" },
    { rotational_state, "rotational" },
    { body_mass_state, "mass" },
    { custom_state, "custom" }
}
Definition at line 262 of file propagator.h.
unsupportedIntegratedStateTypes
std::vector< IntegratedStateType > tudat::propagators::unsupportedIntegratedStateTypes static
Initial value:
=
{
    hybrid,
    custom_state
}
Definition at line 272 of file propagator.h.
translationalPropagatorTypes
std::map< TranslationalPropagatorType, std::string > tudat::propagators::translationalPropagatorTypes static
Initial value:
=
{
    { cowell, "cowell" },
    { encke, "encke" },
    { gauss_keplerian, "gaussKeplerian" },
    { gauss_modified_equinoctial, "gaussModifiedEquinoctial" },
    { unified_state_model_quaternions, "unifiedStateModelQuaternions" },
    { unified_state_model_modified_rodrigues_parameters, "unifiedStateModelModifiedRodriguesParameters" },
    { unified_state_model_exponential_map, "unifiedStateModelExponentialMap" }
}
Definition at line 294 of file propagator.h.
unsupportedTranslationalPropagatorTypes
std::vector< TranslationalPropagatorType > tudat::propagators::unsupportedTranslationalPropagatorTypes = { } static
Definition at line 306 of file propagator.h.
rotationalPropagatorTypes
std::map< RotationalPropagatorType, std::string > tudat::propagators::rotationalPropagatorTypes static
Initial value:
=
{
    { quaternions, "quaternions" },
    { modified_rodrigues_parameters, "modifiedRodriguesParameters" },
    { exponential_map, "exponentialMap" }
}
Definition at line 324 of file propagator.h.
unsupportedRotationalPropagatorTypes
std::vector< RotationalPropagatorType > tudat::propagators::unsupportedRotationalPropagatorTypes = { } static
Definition at line 332 of file propagator.h.
variableTypes
std::map< VariableType, std::string > tudat::propagators::variableTypes static
Initial value:
=
{
    { independentVariable, "independent" },
    { cpuTimeVariable, "cpuTime" },
    { stateVariable, "state" },
    { dependentVariable, "dependent" },
    { stateTransitionMatrix, "stateTransitionMatrix" },
    { sensitivityMatrix, "sensitivityMatrix" }
}
Definition at line 27 of file variable.h.
Referenced by from_json(), and to_json().
unsupportedVariableTypes
std::vector< VariableType > tudat::propagators::unsupportedVariableTypes = { } static
Definition at line 38 of file variable.h.
Referenced by from_json(), and to_json().
dependentVariableTypes
std::map< PropagationDependentVariables, std::string > tudat::propagators::dependentVariableTypes static
Definition at line 56 of file variable.h.
unsupportedDependentVariableTypes
std::vector< PropagationDependentVariables > tudat::propagators::unsupportedDependentVariableTypes static
Initial value:
=
{
}
Definition at line 105 of file variable.h.