var searchData=
[
  ['jsonestimationmanager',['JsonEstimationManager',['../dc/dc4/classtudat_1_1json__interface_1_1_json_estimation_manager.html#a6d8b20c2148465343530460981e0b2a1',1,'tudat::json_interface::JsonEstimationManager::JsonEstimationManager(const std::string &amp;inputFilePath, const std::chrono::steady_clock::time_point initialClockTime=std::chrono::steady_clock::now())'],['../dc/dc4/classtudat_1_1json__interface_1_1_json_estimation_manager.html#adc417df29c5849a0dc7953866a945868',1,'tudat::json_interface::JsonEstimationManager::JsonEstimationManager(const nlohmann::json &amp;jsonObject, const std::chrono::steady_clock::time_point initialClockTime=std::chrono::steady_clock::now())']]],
  ['jsonfrommap',['jsonFromMap',['../d8/d24/namespacetudat_1_1json__interface.html#af96f1fb9252424a733d7e8dd1e260174',1,'tudat::json_interface']]],
  ['jsonfromvector',['jsonFromVector',['../d8/d24/namespacetudat_1_1json__interface.html#accda62b9b0dec814ebf4ffa529775906',1,'tudat::json_interface']]],
  ['jsonsimulationmanager',['JsonSimulationManager',['../d2/dce/classtudat_1_1json__interface_1_1_json_simulation_manager.html#aaa3ab5a9e7c7bd3f6bc3fbb4a07e9ccd',1,'tudat::json_interface::JsonSimulationManager::JsonSimulationManager(const std::string &amp;inputFilePath, const std::chrono::steady_clock::time_point initialClockTime=std::chrono::steady_clock::now())'],['../d2/dce/classtudat_1_1json__interface_1_1_json_simulation_manager.html#a5cba88036054d7644f4a95759f4b4216',1,'tudat::json_interface::JsonSimulationManager::JsonSimulationManager(const nlohmann::json &amp;jsonObject, const std::chrono::steady_clock::time_point initialClockTime=std::chrono::steady_clock::now())']]],
  ['jsonvariationalequationssimulationmanager',['JsonVariationalEquationsSimulationManager',['../dd/d49/classtudat_1_1json__interface_1_1_json_variational_equations_simulation_manager.html#a09044a7bca91da55b9fdb1dd29d7ec70',1,'tudat::json_interface::JsonVariationalEquationsSimulationManager::JsonVariationalEquationsSimulationManager(const std::string &amp;inputFilePath, const std::chrono::steady_clock::time_point initialClockTime=std::chrono::steady_clock::now())'],['../dd/d49/classtudat_1_1json__interface_1_1_json_variational_equations_simulation_manager.html#a9183c67476403a1e354ae073f887395e',1,'tudat::json_interface::JsonVariationalEquationsSimulationManager::JsonVariationalEquationsSimulationManager(const nlohmann::json &amp;jsonObject, const std::chrono::steady_clock::time_point initialClockTime=std::chrono::steady_clock::now())']]],
  ['jumpdatalinearinterpolator',['JumpDataLinearInterpolator',['../db/d00/classtudat_1_1interpolators_1_1_jump_data_linear_interpolator.html#af061ce6dac16328da237a8fe71124a39',1,'tudat::interpolators::JumpDataLinearInterpolator::JumpDataLinearInterpolator(const std::map&lt; IndependentVariableType, DependentVariableType &gt; &amp;dataMap, const DependentVariableType maximumAllowableVariation, const DependentVariableType jumpSize, const AvailableLookupScheme selectedLookupScheme=huntingAlgorithm, const BoundaryInterpolationType boundaryHandling=extrapolate_at_boundary, const DependentVariableType &amp;defaultExtrapolationValue=IdentityElement::getAdditionIdentity&lt; DependentVariableType &gt;())'],['../db/d00/classtudat_1_1interpolators_1_1_jump_data_linear_interpolator.html#a61fa1960f32ed56ec62587c2deeb82d7',1,'tudat::interpolators::JumpDataLinearInterpolator::JumpDataLinearInterpolator(const std::vector&lt; IndependentVariableType &gt; independentValues, const std::vector&lt; DependentVariableType &gt; dependentValues, const DependentVariableType maximumAllowableVariation, const DependentVariableType jumpSize, const AvailableLookupScheme selectedLookupScheme=huntingAlgorithm, const BoundaryInterpolationType boundaryHandling=extrapolate_at_boundary, const DependentVariableType &amp;defaultExtrapolationValue=IdentityElement::getAdditionIdentity&lt; DependentVariableType &gt;())']]]
];
