Tudat: tudat::shape_based_methods::HodographicShaping Class Reference
tudat::shape_based_methods::HodographicShaping Class Reference
#include <hodographicShaping.h>
Public Member Functions
HodographicShaping (const Eigen::Vector6d &initialState, const Eigen::Vector6d &finalState, const double timeOfFlight, const double centralBodyGravitationalParameter, const int numberOfRevolutions, const std::vector< std::shared_ptr< shape_based_methods::BaseFunctionHodographicShaping > > &radialVelocityFunctionComponents, const std::vector< std::shared_ptr< shape_based_methods::BaseFunctionHodographicShaping > > &normalVelocityFunctionComponents, const std::vector< std::shared_ptr< shape_based_methods::BaseFunctionHodographicShaping > > &axialVelocityFunctionComponents, const Eigen::VectorXd &freeCoefficientsRadialVelocityFunction, const Eigen::VectorXd &freeCoefficientsNormalVelocityFunction, const Eigen::VectorXd &freeCoefficientsAxialVelocityFunction, const double initialBodyMass=TUDAT_NAN)
Constructor which sets radial, normal and axial velocity functions and boundary conditions.
~HodographicShaping ()
Default destructor.
double computeCurrentAxialDistance (const double currentTime)
Compute axial distance from central body.
double computeCurrentPolarAngle (double currentTime)
Compute polar angle.
double computeCurrentRadialDistance (const double currentTime)
Compute radial distance from the central body.
Eigen::Vector6d computeCurrentStateVector (const double currentTime)
Compute current cartesian state.
double computeCurrentThrustAccelerationMagnitude (const double currentTime, std::function< double(const double) > specificImpulseFunction=[](const double){ return TUDAT_NAN;}, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings=nullptr)
Compute magnitude thrust acceleration.
double computeDeltaV ()
Compute DeltaV.
Eigen::Vector3d computeThrustAccelerationVector (double currentTime)
Compute thrust acceleration in cartesian coordinates.
double convertIndependentVariableToTime (const double independentVariable)
Convert independent variable to time.
double convertTimeToIndependentVariable (const double time)
Convert time to independent variable.
void getCylindricalThrustAccelerationProfile (std::vector< double > &epochsVector, std::map< double, Eigen::VectorXd > &thrustAccelerationProfile)
Return thrust acceleration profile.
double getFinalValueInpendentVariable ()
Returns final value of the independent variable.
double getInitialValueInpendentVariable ()
Returns initial value of the independent variable.
Public Member Functions inherited from tudat::shape_based_methods::ShapeBasedMethod
ShapeBasedMethod (const Eigen::Vector6d &stateAtDeparture, const Eigen::Vector6d &stateAtArrival, const double timeOfFlight, const double initialBodyMass=TUDAT_NAN)
Empty constructor.
virtual ~ShapeBasedMethod ()
Default destructor.
Eigen::Vector3d computeCurrentThrustForce (double time, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute current thrust vector.
std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > createLowThrustTranslationalStatePropagatorSettings (const std::string &bodyToPropagate, const std::string &centralBody, const basic_astrodynamics::AccelerationMap &accelerationModelMap, const std::shared_ptr< propagators::DependentVariableSaveSettings > dependentVariablesToSave)
Define appropriate translational state propagator settings for the full propagation.
void getThrustForceProfile (std::vector< double > &epochsVector, std::map< double, Eigen::VectorXd > &thrustProfile, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Return thrust profile.
void getTrajectory (std::vector< double > &epochsVector, std::map< double, Eigen::Vector6d > &propagatedTrajectory)
Returns state history.
basic_astrodynamics::AccelerationMap retrieveLowThrustAccelerationMap (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::string &centralBody, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Retrieve acceleration map (thrust and central gravity accelerations).
Public Member Functions inherited from tudat::low_thrust_trajectories::LowThrustLeg
LowThrustLeg (const Eigen::Vector6d &stateAtDeparture, const Eigen::Vector6d &stateAtArrival, const double timeOfFlight, const double initialMass, const bool legModelIsForceBased)
Constructor with immediate definition of parameters.
virtual ~LowThrustLeg ()
double computeCurrentMass (const double independentVariable, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute current mass of the spacecraft.
Eigen::Vector3d computeCurrentThrustAcceleration (double time, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute current thrust vector.
void computeSemiAnalyticalAndFullPropagation (const simulation_setup::NamedBodyMap &bodyMapTest, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const std::pair< std::shared_ptr< propagators::PropagatorSettings< double > >, std::shared_ptr< propagators::PropagatorSettings< double > > > &propagatorSettings, std::map< double, Eigen::VectorXd > &fullPropagationResults, std::map< double, Eigen::Vector6d > &semiAnalyticalResults, std::map< double, Eigen::VectorXd > &dependentVariablesHistory)
Full propagation.
std::pair< std::shared_ptr< propagators::PropagatorSettings< double > >, std::shared_ptr< propagators::PropagatorSettings< double > > > createLowThrustPropagatorSettings (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::string &centralBody, const std::function< double(const double) > specificImpulseFunction, const basic_astrodynamics::AccelerationMap perturbingAccelerationsMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > &integratorSettings, const std::shared_ptr< propagators::DependentVariableSaveSettings > &dependentVariablesToSave)
Define appropriate propagator settings for the full propagation.
std::shared_ptr< propulsion::ThrustAcceleration > getLowThrustAccelerationModel (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const double timeOffset=0.0)
Retrieve acceleration model (thrust).
std::shared_ptr< simulation_setup::ThrustAccelerationSettings > getLowThrustAccelerationSettings (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const double timeOffset=0.0)
Retrieve acceleration model (thrust).
void getMassProfile (const std::vector< double > &epochsVector, std::map< double, Eigen::VectorXd > &massProfile, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Return mass profile.
virtual void getThrustAccelerationProfile (std::vector< double > &epochsVector, std::map< double, Eigen::VectorXd > &thrustAccelerationProfile, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Return thrust acceleration profile.
Protected Member Functions
Eigen::Vector3d computeCurrentThrustAccelerationDirection (double currentTime, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute direction thrust acceleration in cartesian coordinates.
Eigen::Matrix2d computeInverseMatrixNormalBoundaries (std::shared_ptr< CompositeFunctionHodographicShaping > velocityFunction)
Compute inverse of matrix filled with boundary conditions in normal direction.
Eigen::Matrix3d computeInverseMatrixRadialOrAxialBoundaries (std::shared_ptr< CompositeFunctionHodographicShaping > velocityFunction)
Compute inverse of matrix filled with boundary conditions in radial or axial direction.
Eigen::Vector6d computeStateVectorInCylindricalCoordinates (const double currentTime)
Compute state vector in cylindrical coordinates.
double computeThirdFixedCoefficientAxialVelocityFromFinalPolarAngle (Eigen::VectorXd freeCoefficients)
Eigen::Vector3d computeThrustAccelerationInCylindricalCoordinates (double currentTime)
Compute thrust acceleration vector in cylindrical coordinates.
Eigen::Vector3d computeVelocityVectorInCylindricalCoordinates (double currentTime)
Compute velocity vector in cylindrical coordinates.
double evaluateDerivativePolarAngleWrtTime (const double currentTime)
Compute angular velocity.
void satisfyAxialBoundaryConditions (Eigen::VectorXd freeCoefficients)
Satisfy boundary conditions in axial direction.
void satisfyNormalBoundaryConditions (Eigen::VectorXd freeCoefficients)
Satisfy boundary conditions in normal direction.
void satisfyRadialBoundaryConditions (Eigen::VectorXd freeCoefficients)
Satisfy boundary conditions in radial direction.
Protected Member Functions inherited from tudat::low_thrust_trajectories::LowThrustLeg
double computeCurrentMass (const double timeInitialEpoch, const double timeFinalEpoch, const double massInitialEpoch, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute current mass of the spacecraft between two epochs.
Private Attributes
std::vector< double > axialBoundaryConditions_
Axial boundary conditions.
std::shared_ptr< CompositeFunctionHodographicShaping > axialVelocityFunction_
Axial velocity function.
double centralBodyGravitationalParameter_
Central body gravitational parameter.
Eigen::VectorXd freeCoefficientsAxialVelocityFunction_
Vector containing the coefficients of the axial function.
Eigen::VectorXd freeCoefficientsNormalVelocityFunction_
Vector containing the coefficients of the normal function.
Eigen::VectorXd freeCoefficientsRadialVelocityFunction_
Vector containing the coefficients of the radial function.
Eigen::MatrixXd inverseAxialMatrixBoundaryValues_
Inverse of matrix containing the boundary values of the terms in the axial velocity function which are used to satisfy the normal boundary conditions.
Eigen::MatrixXd inverseMatrixNormalBoundaryValues_
Inverse of matrix containing the boundary values of the terms in the normal velocity function which are used to satisfy the normal boundary conditions.
Eigen::MatrixXd inverseMatrixRadialBoundaryValues_
Inverse of matrix containing the boundary values of the terms in the radial velocity function which are used to satisfy the radial boundary conditions.
std::vector< double > normalBoundaryConditions_
Normal boundary conditions.
std::shared_ptr< CompositeFunctionHodographicShaping > normalVelocityFunction_
Normal velocity function.
int numberOfFreeCoefficientsAxialVelocityFunction
Number of free coefficients for the axial velocity function.
int numberOfFreeCoefficientsNormalVelocityFunction_
Number of free coefficients for the normal velocity function.
int numberOfFreeCoefficientsRadialVelocityFunction_
Number of free coefficients for the radial velocity function.
int numberOfRevolutions_
Number of revolutions.
std::vector< double > radialBoundaryConditions_
Radial boundary conditions.
std::shared_ptr< CompositeFunctionHodographicShaping > radialVelocityFunction_
Radial velocity function.
std::map< double, Eigen::Vector3d > thrustAccelerationVectorCache_
Additional Inherited Members
Protected Attributes inherited from tudat::shape_based_methods::ShapeBasedMethod
std::shared_ptr< numerical_quadrature::QuadratureSettings< double > > quadratureSettings_
Numerical quadrature settings, required to compute the time of flight and total deltaV.
Protected Attributes inherited from tudat::low_thrust_trajectories::LowThrustLeg
double initialMass_
bool legModelIsForceBased_
Eigen::Vector6d stateAtArrival_
Cartesian state at arrival.
Eigen::Vector6d stateAtDeparture_
Cartesian state at departure.
double timeOfFlight_
Time of flight of the trajectory leg.
Detailed Description
Definition at line 32 of file hodographicShaping.h.
Constructor & Destructor Documentation
HodographicShaping()
tudat::shape_based_methods::HodographicShaping::HodographicShaping (const Eigen::Vector6d & initialState, const Eigen::Vector6d & finalState, const double timeOfFlight, const double centralBodyGravitationalParameter, const int numberOfRevolutions, const std::vector< std::shared_ptr< shape_based_methods::BaseFunctionHodographicShaping > > & radialVelocityFunctionComponents, const std::vector< std::shared_ptr< shape_based_methods::BaseFunctionHodographicShaping > > & normalVelocityFunctionComponents, const std::vector< std::shared_ptr< shape_based_methods::BaseFunctionHodographicShaping > > & axialVelocityFunctionComponents, const Eigen::VectorXd & freeCoefficientsRadialVelocityFunction, const Eigen::VectorXd & freeCoefficientsNormalVelocityFunction, const Eigen::VectorXd & freeCoefficientsAxialVelocityFunction, const double initialBodyMass = TUDAT_NAN)
Definition at line 30 of file hodographicShaping.cpp.
References axialBoundaryConditions_, axialVelocityFunction_, computeInverseMatrixNormalBoundaries(), computeInverseMatrixRadialOrAxialBoundaries(), tudat::basic_mathematics::computeModulo(), tudat::coordinate_conversions::convertCartesianToCylindricalState(), freeCoefficientsAxialVelocityFunction_, freeCoefficientsNormalVelocityFunction_, freeCoefficientsRadialVelocityFunction_, inverseAxialMatrixBoundaryValues_, inverseMatrixNormalBoundaryValues_, inverseMatrixRadialBoundaryValues_, normalBoundaryConditions_, normalVelocityFunction_, numberOfFreeCoefficientsAxialVelocityFunction, numberOfFreeCoefficientsNormalVelocityFunction_, numberOfFreeCoefficientsRadialVelocityFunction_, numberOfRevolutions_, tudat::mathematical_constants::PI, tudat::shape_based_methods::ShapeBasedMethod::quadratureSettings_, radialBoundaryConditions_, radialVelocityFunction_, satisfyAxialBoundaryConditions(), satisfyNormalBoundaryConditions(), satisfyRadialBoundaryConditions(), tudat::low_thrust_trajectories::LowThrustLeg::stateAtArrival_, and tudat::low_thrust_trajectories::LowThrustLeg::stateAtDeparture_.
~HodographicShaping()
tudat::shape_based_methods::HodographicShaping::~HodographicShaping () inline
Definition at line 52 of file hodographicShaping.h.
Member Function Documentation
convertTimeToIndependentVariable()
double tudat::shape_based_methods::HodographicShaping::convertTimeToIndependentVariable (const double time) inline virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 55 of file hodographicShaping.h.
convertIndependentVariableToTime()
double tudat::shape_based_methods::HodographicShaping::convertIndependentVariableToTime (const double independentVariable) inline virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 61 of file hodographicShaping.h.
References tudat::propagators::independentVariable.
getInitialValueInpendentVariable()
double tudat::shape_based_methods::HodographicShaping::getInitialValueInpendentVariable () inline virtual
Implements tudat::shape_based_methods::ShapeBasedMethod.
Definition at line 67 of file hodographicShaping.h.
getFinalValueInpendentVariable()
double tudat::shape_based_methods::HodographicShaping::getFinalValueInpendentVariable () inline virtual
Implements tudat::shape_based_methods::ShapeBasedMethod.
Definition at line 73 of file hodographicShaping.h.
References computeCurrentAxialDistance(), computeCurrentPolarAngle(), computeCurrentRadialDistance(), computeCurrentStateVector(), computeDeltaV(), computeThrustAccelerationVector(), and tudat::low_thrust_trajectories::LowThrustLeg::timeOfFlight_.
computeCurrentRadialDistance()
double tudat::shape_based_methods::HodographicShaping::computeCurrentRadialDistance (const double currentTime)
Compute radial distance.
Definition at line 422 of file hodographicShaping.cpp.
References radialBoundaryConditions_, and radialVelocityFunction_.
Referenced by computeStateVectorInCylindricalCoordinates(), computeThirdFixedCoefficientAxialVelocityFromFinalPolarAngle(), and getFinalValueInpendentVariable().
computeCurrentPolarAngle()
double tudat::shape_based_methods::HodographicShaping::computeCurrentPolarAngle (double currentTime)
Compute current polar angle.
Definition at line 430 of file hodographicShaping.cpp.
References tudat::coordinate_conversions::convertCartesianToCylindricalState(), tudat::numerical_quadrature::createQuadrature(), evaluateDerivativePolarAngleWrtTime(), tudat::shape_based_methods::ShapeBasedMethod::quadratureSettings_, and tudat::low_thrust_trajectories::LowThrustLeg::stateAtDeparture_.
Referenced by computeStateVectorInCylindricalCoordinates(), and getFinalValueInpendentVariable().
computeCurrentAxialDistance()
double tudat::shape_based_methods::HodographicShaping::computeCurrentAxialDistance (const double currentTime)
Definition at line 448 of file hodographicShaping.cpp.
References axialBoundaryConditions_, and axialVelocityFunction_.
Referenced by computeStateVectorInCylindricalCoordinates(), and getFinalValueInpendentVariable().
computeCurrentStateVector()
Eigen::Vector6d tudat::shape_based_methods::HodographicShaping::computeCurrentStateVector (const double currentTime) virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 473 of file hodographicShaping.cpp.
References computeStateVectorInCylindricalCoordinates(), and tudat::coordinate_conversions::convertCylindricalToCartesianState().
Referenced by computeThrustAccelerationVector(), and getFinalValueInpendentVariable().
computeThrustAccelerationVector()
Eigen::Vector3d tudat::shape_based_methods::HodographicShaping::computeThrustAccelerationVector (double currentTime)
Compute cartesian acceleration.
Definition at line 530 of file hodographicShaping.cpp.
References computeCurrentStateVector(), computeStateVectorInCylindricalCoordinates(), computeThrustAccelerationInCylindricalCoordinates(), and thrustAccelerationVectorCache_.
Referenced by computeCurrentThrustAccelerationDirection(), and getFinalValueInpendentVariable().
computeDeltaV()
double tudat::shape_based_methods::HodographicShaping::computeDeltaV () virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 564 of file hodographicShaping.cpp.
References computeThrustAccelerationInCylindricalCoordinates(), tudat::numerical_quadrature::createQuadrature(), tudat::shape_based_methods::ShapeBasedMethod::quadratureSettings_, and tudat::low_thrust_trajectories::LowThrustLeg::timeOfFlight_.
Referenced by tudat::shape_based_methods::FixedTimeHodographicShapingOptimisationProblem::fitness(), tudat::shape_based_methods::HodographicShapingOptimisationProblem::fitness(), and getFinalValueInpendentVariable().
getCylindricalThrustAccelerationProfile()
void tudat::shape_based_methods::HodographicShaping::getCylindricalThrustAccelerationProfile (std::vector< double > & epochsVector, std::map< double, Eigen::VectorXd > & thrustAccelerationProfile) inline
Definition at line 97 of file hodographicShaping.h.
References computeCurrentThrustAccelerationDirection(), computeCurrentThrustAccelerationMagnitude(), computeInverseMatrixNormalBoundaries(), computeInverseMatrixRadialOrAxialBoundaries(), computeStateVectorInCylindricalCoordinates(), computeThirdFixedCoefficientAxialVelocityFromFinalPolarAngle(), computeThrustAccelerationInCylindricalCoordinates(), computeVelocityVectorInCylindricalCoordinates(), evaluateDerivativePolarAngleWrtTime(), satisfyAxialBoundaryConditions(), satisfyNormalBoundaryConditions(), satisfyRadialBoundaryConditions(), and TUDAT_NAN.
computeCurrentThrustAccelerationMagnitude()
double tudat::shape_based_methods::HodographicShaping::computeCurrentThrustAccelerationMagnitude (const double currentTime, std::function< double(const double) > specificImpulseFunction = [ ](const double){ return TUDAT_NAN; }, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings = nullptr) virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 520 of file hodographicShaping.cpp.
References computeThrustAccelerationInCylindricalCoordinates().
Referenced by tudat::shape_based_methods::HodographicShapingOptimisationProblem::fitness(), and getCylindricalThrustAccelerationProfile().
computeInverseMatrixNormalBoundaries()
Eigen::Matrix2d tudat::shape_based_methods::HodographicShaping::computeInverseMatrixNormalBoundaries (std::shared_ptr< CompositeFunctionHodographicShaping > velocityFunction) protected
Definition at line 163 of file hodographicShaping.cpp.
References tudat::low_thrust_trajectories::LowThrustLeg::timeOfFlight_.
Referenced by getCylindricalThrustAccelerationProfile(), and HodographicShaping().
computeInverseMatrixRadialOrAxialBoundaries()
Eigen::Matrix3d tudat::shape_based_methods::HodographicShaping::computeInverseMatrixRadialOrAxialBoundaries (std::shared_ptr< CompositeFunctionHodographicShaping > velocityFunction) protected
Definition at line 137 of file hodographicShaping.cpp.
References tudat::low_thrust_trajectories::LowThrustLeg::timeOfFlight_.
Referenced by getCylindricalThrustAccelerationProfile(), and HodographicShaping().
satisfyRadialBoundaryConditions()
void tudat::shape_based_methods::HodographicShaping::satisfyRadialBoundaryConditions (Eigen::VectorXd freeCoefficients) protected
Definition at line 182 of file hodographicShaping.cpp.
References inverseMatrixRadialBoundaryValues_, numberOfFreeCoefficientsRadialVelocityFunction_, radialBoundaryConditions_, radialVelocityFunction_, and tudat::low_thrust_trajectories::LowThrustLeg::timeOfFlight_.
Referenced by getCylindricalThrustAccelerationProfile(), and HodographicShaping().
satisfyAxialBoundaryConditions()
void tudat::shape_based_methods::HodographicShaping::satisfyAxialBoundaryConditions (Eigen::VectorXd freeCoefficients) protected
Definition at line 225 of file hodographicShaping.cpp.
References axialBoundaryConditions_, axialVelocityFunction_, inverseAxialMatrixBoundaryValues_, numberOfFreeCoefficientsAxialVelocityFunction, and tudat::low_thrust_trajectories::LowThrustLeg::timeOfFlight_.
Referenced by getCylindricalThrustAccelerationProfile(), and HodographicShaping().
satisfyNormalBoundaryConditions()
void tudat::shape_based_methods::HodographicShaping::satisfyNormalBoundaryConditions (Eigen::VectorXd freeCoefficients) protected
Definition at line 267 of file hodographicShaping.cpp.
References computeThirdFixedCoefficientAxialVelocityFromFinalPolarAngle(), inverseMatrixNormalBoundaryValues_, normalBoundaryConditions_, normalVelocityFunction_, numberOfFreeCoefficientsNormalVelocityFunction_, and tudat::low_thrust_trajectories::LowThrustLeg::timeOfFlight_.
Referenced by getCylindricalThrustAccelerationProfile(), and HodographicShaping().
computeThirdFixedCoefficientAxialVelocityFromFinalPolarAngle()
double tudat::shape_based_methods::HodographicShaping::computeThirdFixedCoefficientAxialVelocityFromFinalPolarAngle (Eigen::VectorXd freeCoefficients) protected
Compute third fixed coefficient of the normal velocity composite function, so that the condition on the final polar angle is fulfilled.
Definition at line 313 of file hodographicShaping.cpp.
References computeCurrentRadialDistance(), tudat::numerical_quadrature::createQuadrature(), inverseMatrixNormalBoundaryValues_, normalBoundaryConditions_, normalVelocityFunction_, numberOfFreeCoefficientsNormalVelocityFunction_, tudat::shape_based_methods::ShapeBasedMethod::quadratureSettings_, and tudat::low_thrust_trajectories::LowThrustLeg::timeOfFlight_.
Referenced by getCylindricalThrustAccelerationProfile(), and satisfyNormalBoundaryConditions().
computeVelocityVectorInCylindricalCoordinates()
Eigen::Vector3d tudat::shape_based_methods::HodographicShaping::computeVelocityVectorInCylindricalCoordinates (double currentTime) protected
Compute velocity components.
Definition at line 394 of file hodographicShaping.cpp.
References axialVelocityFunction_, normalVelocityFunction_, and radialVelocityFunction_.
Referenced by computeStateVectorInCylindricalCoordinates(), and getCylindricalThrustAccelerationProfile().
evaluateDerivativePolarAngleWrtTime()
double tudat::shape_based_methods::HodographicShaping::evaluateDerivativePolarAngleWrtTime (const double currentTime) protected
Definition at line 412 of file hodographicShaping.cpp.
References normalVelocityFunction_, radialBoundaryConditions_, and radialVelocityFunction_.
Referenced by computeCurrentPolarAngle(), and getCylindricalThrustAccelerationProfile().
computeStateVectorInCylindricalCoordinates()
Eigen::Vector6d tudat::shape_based_methods::HodographicShaping::computeStateVectorInCylindricalCoordinates (const double currentTime) protected
Compute current cylindrical state.
Definition at line 456 of file hodographicShaping.cpp.
References computeCurrentAxialDistance(), computeCurrentPolarAngle(), computeCurrentRadialDistance(), and computeVelocityVectorInCylindricalCoordinates().
Referenced by computeCurrentStateVector(), computeThrustAccelerationVector(), and getCylindricalThrustAccelerationProfile().
computeThrustAccelerationInCylindricalCoordinates()
Eigen::Vector3d tudat::shape_based_methods::HodographicShaping::computeThrustAccelerationInCylindricalCoordinates (double currentTime) protected
Compute thrust acceleration components.
Definition at line 481 of file hodographicShaping.cpp.
References axialBoundaryConditions_, axialVelocityFunction_, centralBodyGravitationalParameter_, normalVelocityFunction_, radialBoundaryConditions_, and radialVelocityFunction_.
Referenced by computeCurrentThrustAccelerationMagnitude(), computeDeltaV(), computeThrustAccelerationVector(), and getCylindricalThrustAccelerationProfile().
computeCurrentThrustAccelerationDirection()
Eigen::Vector3d tudat::shape_based_methods::HodographicShaping::computeCurrentThrustAccelerationDirection (double currentTime, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings) protected virtual
Compute direction cartesian acceleration.
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 555 of file hodographicShaping.cpp.
References computeThrustAccelerationVector().
Referenced by getCylindricalThrustAccelerationProfile().
Member Data Documentation
centralBodyGravitationalParameter_
double tudat::shape_based_methods::HodographicShaping::centralBodyGravitationalParameter_ private
Definition at line 157 of file hodographicShaping.h.
Referenced by computeThrustAccelerationInCylindricalCoordinates().
numberOfRevolutions_
int tudat::shape_based_methods::HodographicShaping::numberOfRevolutions_ private
Definition at line 160 of file hodographicShaping.h.
Referenced by HodographicShaping().
radialVelocityFunction_
std::shared_ptr< CompositeFunctionHodographicShaping > tudat::shape_based_methods::HodographicShaping::radialVelocityFunction_ private
Definition at line 163 of file hodographicShaping.h.
Referenced by computeCurrentRadialDistance(), computeThrustAccelerationInCylindricalCoordinates(), computeVelocityVectorInCylindricalCoordinates(), evaluateDerivativePolarAngleWrtTime(), HodographicShaping(), and satisfyRadialBoundaryConditions().
normalVelocityFunction_
std::shared_ptr< CompositeFunctionHodographicShaping > tudat::shape_based_methods::HodographicShaping::normalVelocityFunction_ private
Definition at line 166 of file hodographicShaping.h.
Referenced by computeThirdFixedCoefficientAxialVelocityFromFinalPolarAngle(), computeThrustAccelerationInCylindricalCoordinates(), computeVelocityVectorInCylindricalCoordinates(), evaluateDerivativePolarAngleWrtTime(), HodographicShaping(), and satisfyNormalBoundaryConditions().
axialVelocityFunction_
std::shared_ptr< CompositeFunctionHodographicShaping > tudat::shape_based_methods::HodographicShaping::axialVelocityFunction_ private
Definition at line 169 of file hodographicShaping.h.
Referenced by computeCurrentAxialDistance(), computeThrustAccelerationInCylindricalCoordinates(), computeVelocityVectorInCylindricalCoordinates(), HodographicShaping(), and satisfyAxialBoundaryConditions().
freeCoefficientsRadialVelocityFunction_
Eigen::VectorXd tudat::shape_based_methods::HodographicShaping::freeCoefficientsRadialVelocityFunction_ private
Definition at line 172 of file hodographicShaping.h.
Referenced by HodographicShaping().
freeCoefficientsNormalVelocityFunction_
Eigen::VectorXd tudat::shape_based_methods::HodographicShaping::freeCoefficientsNormalVelocityFunction_ private
Definition at line 175 of file hodographicShaping.h.
Referenced by HodographicShaping().
freeCoefficientsAxialVelocityFunction_
Eigen::VectorXd tudat::shape_based_methods::HodographicShaping::freeCoefficientsAxialVelocityFunction_ private
Definition at line 178 of file hodographicShaping.h.
Referenced by HodographicShaping().
numberOfFreeCoefficientsRadialVelocityFunction_
int tudat::shape_based_methods::HodographicShaping::numberOfFreeCoefficientsRadialVelocityFunction_ private
Definition at line 181 of file hodographicShaping.h.
Referenced by HodographicShaping(), and satisfyRadialBoundaryConditions().
numberOfFreeCoefficientsNormalVelocityFunction_
int tudat::shape_based_methods::HodographicShaping::numberOfFreeCoefficientsNormalVelocityFunction_ private
Definition at line 184 of file hodographicShaping.h.
Referenced by computeThirdFixedCoefficientAxialVelocityFromFinalPolarAngle(), HodographicShaping(), and satisfyNormalBoundaryConditions().
numberOfFreeCoefficientsAxialVelocityFunction
int tudat::shape_based_methods::HodographicShaping::numberOfFreeCoefficientsAxialVelocityFunction private
Definition at line 187 of file hodographicShaping.h.
Referenced by HodographicShaping(), and satisfyAxialBoundaryConditions().
radialBoundaryConditions_
std::vector< double > tudat::shape_based_methods::HodographicShaping::radialBoundaryConditions_ private
Definition at line 190 of file hodographicShaping.h.
Referenced by computeCurrentRadialDistance(), computeThrustAccelerationInCylindricalCoordinates(), evaluateDerivativePolarAngleWrtTime(), HodographicShaping(), and satisfyRadialBoundaryConditions().
normalBoundaryConditions_
std::vector< double > tudat::shape_based_methods::HodographicShaping::normalBoundaryConditions_ private
Definition at line 193 of file hodographicShaping.h.
Referenced by computeThirdFixedCoefficientAxialVelocityFromFinalPolarAngle(), HodographicShaping(), and satisfyNormalBoundaryConditions().
axialBoundaryConditions_
std::vector< double > tudat::shape_based_methods::HodographicShaping::axialBoundaryConditions_ private
Definition at line 196 of file hodographicShaping.h.
Referenced by computeCurrentAxialDistance(), computeThrustAccelerationInCylindricalCoordinates(), HodographicShaping(), and satisfyAxialBoundaryConditions().
inverseMatrixRadialBoundaryValues_
Eigen::MatrixXd tudat::shape_based_methods::HodographicShaping::inverseMatrixRadialBoundaryValues_ private
Definition at line 201 of file hodographicShaping.h.
Referenced by HodographicShaping(), and satisfyRadialBoundaryConditions().
inverseMatrixNormalBoundaryValues_
Eigen::MatrixXd tudat::shape_based_methods::HodographicShaping::inverseMatrixNormalBoundaryValues_ private
Definition at line 206 of file hodographicShaping.h.
Referenced by computeThirdFixedCoefficientAxialVelocityFromFinalPolarAngle(), HodographicShaping(), and satisfyNormalBoundaryConditions().
inverseAxialMatrixBoundaryValues_
Eigen::MatrixXd tudat::shape_based_methods::HodographicShaping::inverseAxialMatrixBoundaryValues_ private
Definition at line 211 of file hodographicShaping.h.
Referenced by HodographicShaping(), and satisfyAxialBoundaryConditions().
thrustAccelerationVectorCache_
std::map< double, Eigen::Vector3d > tudat::shape_based_methods::HodographicShaping::thrustAccelerationVectorCache_ private
Definition at line 213 of file hodographicShaping.h.
Referenced by computeThrustAccelerationVector().
The documentation for this class was generated from the following files:
Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/hodographicShaping.h
Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/hodographicShaping.cpp