Tudat: tudat::shape_based_methods::SphericalShaping::TimeOfFlightFunction Struct Reference
tudat::shape_based_methods::SphericalShaping::TimeOfFlightFunction Struct Reference
Time of flight function for the root-finder.
#include <sphericalShaping.h>
Public Member Functions
TimeOfFlightFunction (std::function< void(const double) > resetFreeCoefficientFunction, std::function< void() > satisfyBoundaryConditionsFunction, std::function< double() > computeTimeOfFlightFunction, std::function< double() > getRequiredTimeOfFlightfunction)
Create a function that returns the time of flight associated with the current trajectory.
double computeDefiniteIntegral (unsigned int order, double lowerBound, double upperbound)
Integral function (not provided).
double computeDerivative (const unsigned int order, const double inputValue)
Derivative function (not provided).
double evaluate (const double inputValue)
Evaluate the difference between the current and required time of flight values, from the current value of the free coefficient.
double getInitialGuess ()
Get a reasonable initial guess of the root location (not implemented).
double getLowerBound ()
Get a reasonable lower boundary for the root location (not implemented).
double getTrueRootAccuracy ()
Get the accuracy of the true location of the root (not implemented).
double getTrueRootLocation ()
Get the expected true location of the root (not implemented).
double getUpperBound ()
Get a reasonable upper boundary for the root location (not implemented).
Public Member Functions inherited from tudat::basic_mathematics::BasicFunction< double, double >
BasicFunction (unsigned int numberOfIntegrationSteps=1000)
Constructor with definition of the number of steps.
virtual ~BasicFunction ()
Default destructor.
double computeDefiniteIntegralMock (const unsigned int order, const double lowerBound, const double upperbound, const double placeHolder)
Alias for computeDefiniteIntegral, but with an extra variable. Should not be used!
Public Member Functions inherited from tudat::basic_mathematics::Function< double, double >
virtual ~Function ()
Default destructor.
double operator() (const double inputValue)
Alias for evaluate(double).
Private Attributes
std::function< double() > computeTimeOfFlightFunction_
std::function< double() > getRequiredTimeOfFlightfunction_
std::function< void(const double) > resetFreeCoefficientFunction_
std::function< void() > satisfyBoundaryConditionsFunction_
Additional Inherited Members
Public Attributes inherited from tudat::basic_mathematics::BasicFunction< double, double >
unsigned int integrationSteps
Number of steps to take when performing numerical integration.
Static Protected Attributes inherited from tudat::basic_mathematics::BasicFunction< double, double >
static const double sqrt_epsilon_double
Square root of double precision, used to scale the step size.
Detailed Description
Definition at line 170 of file sphericalShaping.h.
Constructor & Destructor Documentation
TimeOfFlightFunction()
tudat::shape_based_methods::SphericalShaping::TimeOfFlightFunction::TimeOfFlightFunction (std::function< void(const double) > resetFreeCoefficientFunction, std::function< void() > satisfyBoundaryConditionsFunction, std::function< double() > computeTimeOfFlightFunction, std::function< double() > getRequiredTimeOfFlightfunction) inline
Definition at line 174 of file sphericalShaping.h.
Member Function Documentation
evaluate()
double tudat::shape_based_methods::SphericalShaping::TimeOfFlightFunction::evaluate (const double inputValue) inline virtual
Implements tudat::basic_mathematics::Function< double, double >.
Definition at line 184 of file sphericalShaping.h.
References computeTimeOfFlightFunction_, getRequiredTimeOfFlightfunction_, resetFreeCoefficientFunction_, and satisfyBoundaryConditionsFunction_.
computeDerivative()
double tudat::shape_based_methods::SphericalShaping::TimeOfFlightFunction::computeDerivative (const unsigned int order, const double inputValue) inline virtual
Reimplemented from tudat::basic_mathematics::BasicFunction< double, double >.
Definition at line 194 of file sphericalShaping.h.
computeDefiniteIntegral()
double tudat::shape_based_methods::SphericalShaping::TimeOfFlightFunction::computeDefiniteIntegral (unsigned int order, double lowerBound, double upperbound) inline virtual
Reimplemented from tudat::basic_mathematics::BasicFunction< double, double >.
Definition at line 200 of file sphericalShaping.h.
getTrueRootLocation()
double tudat::shape_based_methods::SphericalShaping::TimeOfFlightFunction::getTrueRootLocation () inline
Definition at line 206 of file sphericalShaping.h.
References TUDAT_NAN.
getTrueRootAccuracy()
double tudat::shape_based_methods::SphericalShaping::TimeOfFlightFunction::getTrueRootAccuracy () inline
Definition at line 209 of file sphericalShaping.h.
References TUDAT_NAN.
getInitialGuess()
double tudat::shape_based_methods::SphericalShaping::TimeOfFlightFunction::getInitialGuess () inline
Definition at line 212 of file sphericalShaping.h.
References TUDAT_NAN.
getLowerBound()
double tudat::shape_based_methods::SphericalShaping::TimeOfFlightFunction::getLowerBound () inline
Definition at line 215 of file sphericalShaping.h.
References TUDAT_NAN.
getUpperBound()
double tudat::shape_based_methods::SphericalShaping::TimeOfFlightFunction::getUpperBound () inline
Definition at line 218 of file sphericalShaping.h.
References TUDAT_NAN.
Member Data Documentation
resetFreeCoefficientFunction_
std::function< void (const double) > tudat::shape_based_methods::SphericalShaping::TimeOfFlightFunction::resetFreeCoefficientFunction_ private
Definition at line 224 of file sphericalShaping.h.
Referenced by evaluate().
satisfyBoundaryConditionsFunction_
std::function< void () > tudat::shape_based_methods::SphericalShaping::TimeOfFlightFunction::satisfyBoundaryConditionsFunction_ private
Definition at line 225 of file sphericalShaping.h.
Referenced by evaluate().
computeTimeOfFlightFunction_
std::function< double () > tudat::shape_based_methods::SphericalShaping::TimeOfFlightFunction::computeTimeOfFlightFunction_ private
Definition at line 226 of file sphericalShaping.h.
Referenced by evaluate().
getRequiredTimeOfFlightfunction_
std::function< double () > tudat::shape_based_methods::SphericalShaping::TimeOfFlightFunction::getRequiredTimeOfFlightfunction_ private
Definition at line 227 of file sphericalShaping.h.
Referenced by evaluate().
The documentation for this struct was generated from the following file:
Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/sphericalShaping.h