Tudat: tudat::electro_magnetism::PanelledRadiationPressureInterface Class Reference
tudat::electro_magnetism::PanelledRadiationPressureInterface Class Reference
Class in which the properties of a panelled radiation pressure acceleration model are stored.
#include <radiationPressureInterface.h>
Public Member Functions
PanelledRadiationPressureInterface (const std::function< double() > sourcePower, const std::function< Eigen::Vector3d() > sourcePositionFunction, const std::function< Eigen::Vector3d() > targetPositionFunction, const std::vector< std::function< Eigen::Vector3d(const double) > > localFrameSurfaceNormals, const std::vector< double > emissivities, const std::vector< double > areas, const std::vector< double > diffusionCoefficients, const std::function< Eigen::Quaterniond() > rotationFromLocalToPropagationFrame, const std::vector< std::function< Eigen::Vector3d() > > occultingBodyPositions=std::vector< std::function< Eigen::Vector3d() > >(), const std::vector< double > occultingBodyRadii=std::vector< double >(), const double sourceRadius=0.0)
Constructor.
double getArea (const int index) const
Function to return the area of a given panel.
std::vector< double > getAreas ()
Function to return the panels area vector.
Eigen::Vector3d getCurrentSurfaceNormal (const int index) const
Function to return the current surface normal for a given panel.
double getDiffuseReflectionCoefficient (const int index) const
Function to return the diffuse reflection coefficient of a given panel.
std::vector< double > getDiffusionCoefficients ()
Function to return the panels diffuse reflection coefficients vector.
std::vector< double > getEmissivities ()
Function to return the panels emissivity vector.
double getEmissivity (const int index) const
Function to return the emissivity of a given panel.
int getNumberOfPanels ()
Function to return the total number of panels.
std::vector< Eigen::Vector3d > getSurfaceNormalsInPropagationFrame ()
Function to return a vector containing the surface normal expressed in propagation frame for each panel.
void updateInterface (const double currentTime=TUDAT_NAN)
Base class function to update the current properties of the panelled radiation pressure acceleration model.
Public Member Functions inherited from tudat::electro_magnetism::RadiationPressureInterface
RadiationPressureInterface (const std::function< double() > sourcePower, const std::function< Eigen::Vector3d() > sourcePositionFunction, const std::function< Eigen::Vector3d() > targetPositionFunction, const double radiationPressureCoefficient, const double area, const std::vector< std::function< Eigen::Vector3d() > > occultingBodyPositions=std::vector< std::function< Eigen::Vector3d() > >(), const std::vector< double > occultingBodyRadii=std::vector< double >(), const double sourceRadius=0.0)
Constructor.
virtual ~RadiationPressureInterface ()
Destructor.
double getArea () const
Function to return the reflecting area of the target body.
double getCurrentRadiationPressure () const
Function to return the current radiation pressure due to source at target (in N/m^2).
Eigen::Vector3d getCurrentSolarVector () const
Function to return the current vector from the target to the source.
double getCurrentTime ()
Function to return the current time of interface (i.e. time of last updateInterface call).
std::vector< std::function< Eigen::Vector3d() > > getOccultingBodyPositions ()
Function to return the list of functions returning the positions of the bodies causing occultations.
std::vector< double > getOccultingBodyRadii ()
Function to return the list of radii of the bodies causing occultations.
double getRadiationPressureCoefficient () const
Function to return the radiation pressure coefficient of the target body.
std::function< Eigen::Vector3d() > getSourcePositionFunction () const
Function to return the function returning the current position of the source body.
std::function< double() > getSourcePowerFunction () const
Function to return the function returning the current total power (in W) emitted by the source body.
double getSourceRadius ()
Function to return the radius of the source body.
std::function< Eigen::Vector3d() > getTargetPositionFunction () const
Function to return the function returning the current position of the target body.
void resetRadiationPressureCoefficient (const double radiationPressureCoefficient)
Function to reset a constant radiation pressure coefficient of the target body.
void resetRadiationPressureCoefficientFunction (const std::function< double(const double) > radiationPressureCoefficientFunction)
Function to reset the function to obtain the radiation pressure coefficient of the target body.
void updateInterfaceBase (const double currentTime)
Base class function to update the current properties of radiation pressure.
Private Attributes
std::vector< double > areas_
Vector containing the area for all panels.
std::vector< double > diffusionCoefficients_
Vector containing the diffuse reflection coefficient for all panels.
std::vector< double > emissivities_
Vector containing the emissivitie for all panels.
std::vector< std::function< Eigen::Vector3d(const double) > > localFrameSurfaceNormals_
std::function< Eigen::Quaterniond() > rotationFromLocalToPropagationFrame_
Function returning the rotation from local to propagation frame.
std::vector< Eigen::Vector3d > surfaceNormalsInPropagationFrame_
Vector containing the surface normal expressed in propagation frame for each panel.
Additional Inherited Members
Protected Attributes inherited from tudat::electro_magnetism::RadiationPressureInterface
double area_
Reflecting area of the target body.
double currentRadiationPressure_
Current radiation pressure due to source at target (in N/m^2).
Eigen::Vector3d currentSolarVector_
Current vector from the target to the source.
double currentTime_
Current time of interface (i.e. time of last updateInterface call).
std::vector< std::function< Eigen::Vector3d() > > occultingBodyPositions_
List of functions returning the positions of the bodies causing occultations.
std::vector< double > occultingBodyRadii_
List of radii of the bodies causing occultations.
double radiationPressureCoefficient_
Radiation pressure coefficient of the target body.
std::function< double(const double) > radiationPressureCoefficientFunction_
Function to reset a constant radiation pressure coefficient of the target body.
std::function< Eigen::Vector3d() > sourcePositionFunction_
Function returning the current position of the source body.
std::function< double() > sourcePower_
Function returning the current total power (in W) emitted by the source body.
double sourceRadius_
Radius of the source body.
std::function< Eigen::Vector3d() > targetPositionFunction_
Function returning the current position of the target body.
Detailed Description
Class in which the properties of a panelled radiation pressure acceleration model are stored and in which the current radiation pressure is calculated based on the source power and geometry, as well as from the boxes-and-wings model used to describe the vehicle undergoing the acceleration.
Definition at line 294 of file radiationPressureInterface.h.
Constructor & Destructor Documentation
PanelledRadiationPressureInterface()
tudat::electro_magnetism::PanelledRadiationPressureInterface::PanelledRadiationPressureInterface (const std::function< double() > sourcePower, const std::function< Eigen::Vector3d() > sourcePositionFunction, const std::function< Eigen::Vector3d() > targetPositionFunction, const std::vector< std::function< Eigen::Vector3d(const double) > > localFrameSurfaceNormals, const std::vector< double > emissivities, const std::vector< double > areas, const std::vector< double > diffusionCoefficients, const std::function< Eigen::Quaterniond() > rotationFromLocalToPropagationFrame, const std::vector< std::function< Eigen::Vector3d() > > occultingBodyPositions = std::vector< std::function< Eigen::Vector3d() > >(), const std::vector< double > occultingBodyRadii = std::vector< double > (), const double sourceRadius = 0.0) inline
Class construtor for panelled radiation pressure interface.
Parameters
sourcePower Function returning the current total power (in W) emitted by the source body.
sourcePositionFunction Function returning the current position of the source body.
targetPositionFunction Function returning the current position of the target body.
localFrameSurfaceNormals Vector containing the functions returning the surface normal in body-fixed frame for each panel.
emissivities Vector containing the emissivity for each panel.
areas Vector containing the area for each panel.
diffusionCoefficients Vector containing the diffuse reflection coefficient for each panel.
rotationFromLocalToPropagationFrame Vector containing the functions that return the rotation from body-fixed to propagation frame for each panel.
occultingBodyPositions List of functions returning the positions of the bodies causing occultations (default none) NOTE: Multiple concurrent occultations may currently result in slighlty underestimted radiation pressure.
occultingBodyRadii List of radii of the bodies causing occultations (default none).
sourceRadius Radius of the source body (used for occultation calculations) (default 0).
Definition at line 319 of file radiationPressureInterface.h.
Member Function Documentation
updateInterface()
void tudat::electro_magnetism::PanelledRadiationPressureInterface::updateInterface (const double currentTime = TUDAT_NAN) inline virtual
Base class function to update the current properties of the panelled radiation pressure acceleration model. This function is nominally called by the updateInterface function, which may be overridden by derived classes.
Parameters
currentTime Time at which acceleration model is to be updated.
Reimplemented from tudat::electro_magnetism::RadiationPressureInterface.
Definition at line 350 of file radiationPressureInterface.h.
References tudat::electro_magnetism::RadiationPressureInterface::updateInterfaceBase().
getEmissivities()
std::vector< double > tudat::electro_magnetism::PanelledRadiationPressureInterface::getEmissivities () inline
Function to return the panels emissivity vector.
Returns
Vector containing the panels emissivities.
Definition at line 368 of file radiationPressureInterface.h.
getAreas()
std::vector< double > tudat::electro_magnetism::PanelledRadiationPressureInterface::getAreas () inline
Function to return the panels area vector.
Returns
Vector containing the panels areas.
Definition at line 378 of file radiationPressureInterface.h.
getDiffusionCoefficients()
std::vector< double > tudat::electro_magnetism::PanelledRadiationPressureInterface::getDiffusionCoefficients () inline
Function to return the panels diffuse reflection coefficients vector.
Returns
Vector containing the panels diffuse reflection coefficients.
Definition at line 388 of file radiationPressureInterface.h.
getArea()
double tudat::electro_magnetism::PanelledRadiationPressureInterface::getArea (const int index) const inline
Function to return the area of a given panel.
Parameters
index Index of the panel whose area is to be returned.
Returns
Panel area
Definition at line 399 of file radiationPressureInterface.h.
getEmissivity()
double tudat::electro_magnetism::PanelledRadiationPressureInterface::getEmissivity (const int index) const inline
Function to return the emissivity coefficient of a given panel.
Parameters
index Index of the panel whose emissivity is to be returned.
Returns
Panel emissivity
Definition at line 410 of file radiationPressureInterface.h.
Referenced by tudat::electro_magnetism::PanelledRadiationPressureAcceleration::PanelledRadiationPressureAcceleration().
getDiffuseReflectionCoefficient()
double tudat::electro_magnetism::PanelledRadiationPressureInterface::getDiffuseReflectionCoefficient (const int index) const inline
Function to return the diffuse reflection coefficient of a given panel.
Parameters
index Index of the panel whose diffuse reflection coefficient is to be returned.
Returns
Panel diffuse reflection coefficient
Definition at line 421 of file radiationPressureInterface.h.
Referenced by tudat::electro_magnetism::PanelledRadiationPressureAcceleration::PanelledRadiationPressureAcceleration().
getCurrentSurfaceNormal()
Eigen::Vector3d tudat::electro_magnetism::PanelledRadiationPressureInterface::getCurrentSurfaceNormal (const int index) const inline
Function to return the current surface normal for a given panel.
Parameters
index Index of the panel whose surface normal is to be returned.
Returns
Panel current surface normal
Definition at line 432 of file radiationPressureInterface.h.
Referenced by tudat::electro_magnetism::PanelledRadiationPressureAcceleration::PanelledRadiationPressureAcceleration().
getSurfaceNormalsInPropagationFrame()
std::vector< Eigen::Vector3d > tudat::electro_magnetism::PanelledRadiationPressureInterface::getSurfaceNormalsInPropagationFrame () inline
Function to return a vector containing the surface normal expressed in propagation frame for each panel.
Returns
Vector of surface normals in propagation frame
Definition at line 444 of file radiationPressureInterface.h.
getNumberOfPanels()
int tudat::electro_magnetism::PanelledRadiationPressureInterface::getNumberOfPanels () inline
Function to return the total number of panels.
Returns
Number of panels
Definition at line 454 of file radiationPressureInterface.h.
Member Data Documentation
localFrameSurfaceNormals_
std::vector< std::function< Eigen::Vector3d(const double) > > tudat::electro_magnetism::PanelledRadiationPressureInterface::localFrameSurfaceNormals_ private
Vector containing the time-dependent functions that return the surface normal for each panel, in body-fixed frame.
Definition at line 464 of file radiationPressureInterface.h.
emissivities_
std::vector< double > tudat::electro_magnetism::PanelledRadiationPressureInterface::emissivities_ private
Definition at line 467 of file radiationPressureInterface.h.
areas_
std::vector< double > tudat::electro_magnetism::PanelledRadiationPressureInterface::areas_ private
Definition at line 470 of file radiationPressureInterface.h.
diffusionCoefficients_
std::vector< double > tudat::electro_magnetism::PanelledRadiationPressureInterface::diffusionCoefficients_ private
Definition at line 473 of file radiationPressureInterface.h.
rotationFromLocalToPropagationFrame_
std::function< Eigen::Quaterniond() > tudat::electro_magnetism::PanelledRadiationPressureInterface::rotationFromLocalToPropagationFrame_ private
Definition at line 476 of file radiationPressureInterface.h.
surfaceNormalsInPropagationFrame_
std::vector< Eigen::Vector3d > tudat::electro_magnetism::PanelledRadiationPressureInterface::surfaceNormalsInPropagationFrame_ private
Definition at line 479 of file radiationPressureInterface.h.
The documentation for this class was generated from the following file:
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/ElectroMagnetism/radiationPressureInterface.h