Tudat: tudat::shape_based_methods::ExponentialCosineFunctionHodographicShaping Class Reference
tudat::shape_based_methods::ExponentialCosineFunctionHodographicShaping Class Reference
Exponential times cosine function.
#include <baseFunctionsHodographicShaping.h>
Public Member Functions
ExponentialCosineFunctionHodographicShaping (double exponentExponentialFunction, double frequencyCosineFunction)
Constructor taking exponent of the exponential function and frequency of the cosine function as inputs.
~ExponentialCosineFunctionHodographicShaping ()
Default destructor.
double evaluateDerivative (const double independentVariable)
double evaluateFunction (const double independentVariable)
Function, derivative, and integral of exponential times cosine function.
double evaluateIntegral (const double independentVariable)
Public Member Functions inherited from tudat::shape_based_methods::BaseFunctionHodographicShaping
BaseFunctionHodographicShaping ()
Default constructor.
virtual ~BaseFunctionHodographicShaping ()
Default destructor.
Private Attributes
double exponentExponentialFunction_
double frequencyCosineFunction_
Detailed Description
Definition at line 282 of file baseFunctionsHodographicShaping.h.
Constructor & Destructor Documentation
ExponentialCosineFunctionHodographicShaping()
tudat::shape_based_methods::ExponentialCosineFunctionHodographicShaping::ExponentialCosineFunctionHodographicShaping (double exponentExponentialFunction, double frequencyCosineFunction) inline
Definition at line 287 of file baseFunctionsHodographicShaping.h.
~ExponentialCosineFunctionHodographicShaping()
tudat::shape_based_methods::ExponentialCosineFunctionHodographicShaping::~ExponentialCosineFunctionHodographicShaping () inline
Definition at line 294 of file baseFunctionsHodographicShaping.h.
References tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateDerivative(), tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateFunction(), tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateIntegral(), and tudat::propagators::independentVariable.
Member Function Documentation
evaluateFunction()
double tudat::shape_based_methods::ExponentialCosineFunctionHodographicShaping::evaluateFunction (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 145 of file baseFunctionsHodographicShaping.cpp.
evaluateDerivative()
double tudat::shape_based_methods::ExponentialCosineFunctionHodographicShaping::evaluateDerivative (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 151 of file baseFunctionsHodographicShaping.cpp.
evaluateIntegral()
double tudat::shape_based_methods::ExponentialCosineFunctionHodographicShaping::evaluateIntegral (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 158 of file baseFunctionsHodographicShaping.cpp.
Member Data Documentation
exponentExponentialFunction_
double tudat::shape_based_methods::ExponentialCosineFunctionHodographicShaping::exponentExponentialFunction_ private
Definition at line 307 of file baseFunctionsHodographicShaping.h.
frequencyCosineFunction_
double tudat::shape_based_methods::ExponentialCosineFunctionHodographicShaping::frequencyCosineFunction_ private
Definition at line 308 of file baseFunctionsHodographicShaping.h.
The documentation for this class was generated from the following files:
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/baseFunctionsHodographicShaping.h
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/baseFunctionsHodographicShaping.cpp