Tudat: tudat::propagators::HybridArcCombinedStateTransitionAndSensitivityMatrixInterface Class Reference
tudat::propagators::HybridArcCombinedStateTransitionAndSensitivityMatrixInterface Class Reference
Interface object of interpolation of numerically propagated state transition and sensitivity matrices for a hybrid of single-and multi-arc estimation (single order is put first in concatenation).
#include <stateTransitionMatrixInterface.h>
Public Member Functions
HybridArcCombinedStateTransitionAndSensitivityMatrixInterface (const std::shared_ptr< SingleArcCombinedStateTransitionAndSensitivityMatrixInterface > singleArcInterface, const std::shared_ptr< MultiArcCombinedStateTransitionAndSensitivityMatrixInterface > multiArcInterface)
Constructor.
~HybridArcCombinedStateTransitionAndSensitivityMatrixInterface ()
Destructor.
Eigen::MatrixXd getCombinedStateTransitionAndSensitivityMatrix (const double evaluationTime)
Function to get the concatenated state transition and sensitivity matrix at a given time.
Eigen::MatrixXd getFullCombinedStateTransitionAndSensitivityMatrix (const double evaluationTime)
Function to get the full concatenated state transition and sensitivity matrix at a given time.
int getFullParameterVectorSize ()
Function to get the size of the total parameter vector.
Public Member Functions inherited from tudat::propagators::CombinedStateTransitionAndSensitivityMatrixInterface
CombinedStateTransitionAndSensitivityMatrixInterface (const int numberOfInitialDynamicalParameters, const int numberOfParameters)
Constructor.
virtual ~CombinedStateTransitionAndSensitivityMatrixInterface ()
Destructor.
int getSensitivityMatrixSize ()
Function to get the number of columns of sensitivity matrix.
int getStateTransitionMatrixSize ()
Function to get the size of state transition matrix.
Private Attributes
std::shared_ptr< MultiArcCombinedStateTransitionAndSensitivityMatrixInterface > multiArcInterface_
Object to retrieve state transition/sensitivity matrices for multi arc component.
int multiArcStateSize_
Full state size of single arc in multi-arc model.
int numberOfMultiArcs_
Number of arcs in multi-arc model.
int originalMultiArcStateSize_
Full state size of single arc in original multi-arc model (full multi-arc size minus single-arc size).
std::shared_ptr< SingleArcCombinedStateTransitionAndSensitivityMatrixInterface > singleArcInterface_
Object to retrieve state transition/sensitivity matrices for single arc component.
int singleArcStateSize_
Size of single-arc state.
Additional Inherited Members
Protected Attributes inherited from tudat::propagators::CombinedStateTransitionAndSensitivityMatrixInterface
int sensitivityMatrixSize_
Number of columns of sensitivity matrix.
int stateTransitionMatrixSize_
Size of state transition matrix.
Detailed Description
Interface object of interpolation of numerically propagated state transition and sensitivity matrices for a hybrid of single-and multi-arc estimation (single order is put first in concatenation)
The single- anf multi-arc given as input must be consistent: the single arc bodies/states must also be included in the multi-arc model, in order to properly generate the coupling terms between single and multi-arc states (see HybridArcVariationalEquationsSolver).
Definition at line 407 of file stateTransitionMatrixInterface.h.
Constructor & Destructor Documentation
HybridArcCombinedStateTransitionAndSensitivityMatrixInterface()
tudat::propagators::HybridArcCombinedStateTransitionAndSensitivityMatrixInterface::HybridArcCombinedStateTransitionAndSensitivityMatrixInterface (const std::shared_ptr< SingleArcCombinedStateTransitionAndSensitivityMatrixInterface > singleArcInterface, const std::shared_ptr< MultiArcCombinedStateTransitionAndSensitivityMatrixInterface > multiArcInterface) inline
Constructor
Parameters
singleArcInterface Object to retrieve state transition/sensitivity matrices for single arc component
multiArcInterface Object to retrieve state transition/sensitivity matrices for multi arc component
Definition at line 417 of file stateTransitionMatrixInterface.h.
~HybridArcCombinedStateTransitionAndSensitivityMatrixInterface()
tudat::propagators::HybridArcCombinedStateTransitionAndSensitivityMatrixInterface::~HybridArcCombinedStateTransitionAndSensitivityMatrixInterface () inline
Definition at line 441 of file stateTransitionMatrixInterface.h.
Member Function Documentation
getFullParameterVectorSize()
int tudat::propagators::HybridArcCombinedStateTransitionAndSensitivityMatrixInterface::getFullParameterVectorSize () inline virtual
Function to get the size of the total parameter vector.
Returns
Size of the total parameter vector.
Implements tudat::propagators::CombinedStateTransitionAndSensitivityMatrixInterface.
Definition at line 448 of file stateTransitionMatrixInterface.h.
References tudat::propagators::CombinedStateTransitionAndSensitivityMatrixInterface::getCombinedStateTransitionAndSensitivityMatrix(), tudat::propagators::CombinedStateTransitionAndSensitivityMatrixInterface::getFullCombinedStateTransitionAndSensitivityMatrix(), and tudat::propagators::CombinedStateTransitionAndSensitivityMatrixInterface::sensitivityMatrixSize_.
getCombinedStateTransitionAndSensitivityMatrix()
Eigen::MatrixXd tudat::propagators::HybridArcCombinedStateTransitionAndSensitivityMatrixInterface::getCombinedStateTransitionAndSensitivityMatrix (const double evaluationTime) virtual
Function to get the concatenated state transition and sensitivity matrix at a given time. Only the state transition matrix for the current are is included in the concatenation.
Parameters
evaluationTime Time at which to evaluate matrix interpolators
Returns
Concatenated state transition and sensitivity matrices.
Implements tudat::propagators::CombinedStateTransitionAndSensitivityMatrixInterface.
Definition at line 216 of file stateTransitionMatrixInterface.cpp.
References tudat::propagators::CombinedStateTransitionAndSensitivityMatrixInterface::sensitivityMatrixSize_, and tudat::propagators::CombinedStateTransitionAndSensitivityMatrixInterface::stateTransitionMatrixSize_.
getFullCombinedStateTransitionAndSensitivityMatrix()
Eigen::MatrixXd tudat::propagators::HybridArcCombinedStateTransitionAndSensitivityMatrixInterface::getFullCombinedStateTransitionAndSensitivityMatrix (const double evaluationTime) virtual
Function to get the concatenated state transition matrices for each arc and sensitivity matrix at a given time.
Function to get the full concatenated state transition and sensitivity matrix at a given time. The state transition matrix for each arc is included (which equals zero for each multi-arc initial state sensitivity outside of teh current arc)
Parameters
evaluationTime Time at which to evaluate matrix interpolators
Returns
Full concatenated state transition and sensitivity matrices.
Implements tudat::propagators::CombinedStateTransitionAndSensitivityMatrixInterface.
Definition at line 285 of file stateTransitionMatrixInterface.cpp.
References tudat::propagators::MultiArcCombinedStateTransitionAndSensitivityMatrixInterface::getCombinedStateTransitionAndSensitivityMatrix(), tudat::propagators::CombinedStateTransitionAndSensitivityMatrixInterface::sensitivityMatrixSize_, and tudat::propagators::CombinedStateTransitionAndSensitivityMatrixInterface::stateTransitionMatrixSize_.
Member Data Documentation
singleArcInterface_
std::shared_ptr< SingleArcCombinedStateTransitionAndSensitivityMatrixInterface > tudat::propagators::HybridArcCombinedStateTransitionAndSensitivityMatrixInterface::singleArcInterface_ private
Definition at line 475 of file stateTransitionMatrixInterface.h.
multiArcInterface_
std::shared_ptr< MultiArcCombinedStateTransitionAndSensitivityMatrixInterface > tudat::propagators::HybridArcCombinedStateTransitionAndSensitivityMatrixInterface::multiArcInterface_ private
Definition at line 478 of file stateTransitionMatrixInterface.h.
singleArcStateSize_
int tudat::propagators::HybridArcCombinedStateTransitionAndSensitivityMatrixInterface::singleArcStateSize_ private
Definition at line 481 of file stateTransitionMatrixInterface.h.
multiArcStateSize_
int tudat::propagators::HybridArcCombinedStateTransitionAndSensitivityMatrixInterface::multiArcStateSize_ private
Definition at line 484 of file stateTransitionMatrixInterface.h.
originalMultiArcStateSize_
int tudat::propagators::HybridArcCombinedStateTransitionAndSensitivityMatrixInterface::originalMultiArcStateSize_ private
Definition at line 487 of file stateTransitionMatrixInterface.h.
numberOfMultiArcs_
int tudat::propagators::HybridArcCombinedStateTransitionAndSensitivityMatrixInterface::numberOfMultiArcs_ private
Definition at line 490 of file stateTransitionMatrixInterface.h.
The documentation for this class was generated from the following files:
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/Propagators/stateTransitionMatrixInterface.h
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/Propagators/stateTransitionMatrixInterface.cpp