Tudat: tudat::acceleration_partials Namespace Reference
tudat::acceleration_partials Namespace Reference
Classes
class AccelerationPartial
Base class for objects calculating partial derivatives of accelerations w.r.t. states, model parameters.
class AerodynamicAccelerationPartial
Class to calculate the partials of the aerodynamic acceleration w.r.t. parameters and states.
class CannonBallRadiationPressurePartial
Class to calculate the partials of the cannnonball radiation pressure acceleration w.r.t. parameters and states.
class CentralGravitationPartial
Class to calculate the partials of the central gravitational acceleration w.r.t. parameters and states.
class ConstantTorquePartial
Class to calculate the partials of the effective torque (if all constituent torques are constant) w.r.t. parameters and states.
class DirectTidalDissipationAccelerationPartial
Class to calculate the partials of the direct tidal acceleration model (e.g. Lainey et al. 2007) w.r.t. parameters and states.
class EmpiricalAccelerationPartial
class InertialTorquePartial
Class to compute the partial derivatives of the inertial torque w.r.t. states and parameters.
class MomentumWheelDesaturationPartial
Class to calculate the partials of the momentum wheel desaturation acceleration w.r.t. parameters and states.
class MutualSphericalHarmonicsGravityPartial
Class for calculating partial derivatives of a mutual spherical harmonic gravitational acceleration.
class PanelledRadiationPressurePartial
Class to calculate the partials of the panelled radiation pressure acceleration w.r.t. parameters and states.
class RelativisticAccelerationPartial
Class to calculate the partials of the relativistic acceleration correction w.r.t. parameters and states.
class SecondDegreeGravitationalTorquePartial
Class to calculate the partials of the central gravitational acceleration w.r.t. parameters and states.
class SphericalHarmonicGravitationalTorquePartial
Class to calculate the partials of the central gravitational torque w.r.t. parameters and states.
class SphericalHarmonicsGravityPartial
Class for calculating partial derivatives of a spherical harmonic gravitational acceleration.
class ThirdBodyGravityPartial
Class to calculate the partials of a third-body gravitational acceleration w.r.t. parameters and states.
class TorquePartial
Base class for objects calculating partial derivatives of torques w.r.t. states, model parameters.
Functions
Eigen::MatrixXd calculateAccelerationDeviationDueToOrientationChange (const std::function< void(Eigen::Vector7d) > setBodyRotationalState, std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > accelerationModel, const Eigen::Vector7d &originalRotationalState, const Eigen::Vector4d &commandedQuaternionPerturbation, std::vector< Eigen::Vector4d > &appliedQuaternionPerturbation, std::function< void() > updateFunction, const double evaluationTime)
Function to numerical compute the partial derivative of a acceleration w.r.t. a body rotational quaternion.
Eigen::Vector3d calculateAccelerationWrtParameterPartials (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > accelerationModel, double parameterPerturbation, std::function< void() > updateDependentVariables, const double currentTime, std::function< void(const double) > timeDependentUpdateDependentVariables)
Function to numerical compute the partial derivative of an acceleration w.r.t. a double parameter.
Eigen::Matrix< double, 3, Eigen::Dynamic > calculateAccelerationWrtParameterPartials (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > accelerationModel, Eigen::VectorXd parameterPerturbation, std::function< void() > updateDependentVariables, const double currentTime, std::function< void(const double) > timeDependentUpdateDependentVariables)
Function to numerical compute the partial derivative of an acceleration w.r.t. a vector parameter.
Eigen::Matrix3d calculateAccelerationWrtStatePartials (std::function< void(Eigen::Vector6d) > setBodyState, std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > accelerationModel, Eigen::Vector6d originalState, Eigen::Vector3d statePerturbation, int startIndex, std::function< void() > updateFunction, const double evaluationTime)
Function to numerical compute the partial derivative of an acceleration w.r.t. a body state.
Eigen::Matrix< double, 1, 6 > calculateNumericalPartialOfTrueAnomalyWrtState (const Eigen::Vector6d &cartesianElements, const double gravitationalParameter, const Eigen::Vector6d &cartesianStateElementPerturbations)
Function determine the numerical partial derivative of the true anomaly wrt the elements of the Cartesian state.
Eigen::Matrix3d calculatePartialOfPointMassGravityWrtPositionOfAcceleratedBody (const Eigen::Vector3d &acceleratedBodyPosition, const Eigen::Vector3d &acceleratingBodyPositions, double gravitationalParameter)
Calculates partial derivative of point mass gravitational acceleration wrt the position of body undergoing acceleration.
void calculateSphericalHarmonicGravityWrtCCoefficients (const Eigen::Vector3d &sphericalPosition, const double referenceRadius, const double gravitionalParameter, const std::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache, const std::vector< std::pair< int, int > > &blockIndices, const Eigen::Matrix3d &sphericalToCartesianGradientMatrix, const Eigen::Matrix3d &bodyFixedToIntegrationFrame, Eigen::MatrixXd &partialsMatrix, const int maximumAccelerationDegree, const int maximumAccelerationOrder)
Calculate partial of spherical harmonic acceleration w.r.t. a set of cosine coefficients.
void calculateSphericalHarmonicGravityWrtSCoefficients (const Eigen::Vector3d &sphericalPosition, const double referenceRadius, const double gravitionalParameter, const std::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache, const std::vector< std::pair< int, int > > &blockIndices, const Eigen::Matrix3d &sphericalToCartesianGradientMatrix, const Eigen::Matrix3d &bodyFixedToIntegrationFrame, Eigen::MatrixXd &partialsMatrix, const int maximumAccelerationDegree, const int maximumAccelerationOrder)
Calculate partial of spherical harmonic acceleration w.r.t. a set of sine coefficients.
Eigen::MatrixXd calculateTorqueDeviationDueToOrientationChange (const std::function< void(Eigen::Vector7d) > setBodyRotationalState, const std::shared_ptr< basic_astrodynamics::TorqueModel > torqueModel, const Eigen::Vector7d &originalRotationalState, const Eigen::Vector4d &commandedQuaternionPerturbation, std::vector< Eigen::Vector4d > &appliedQuaternionPerturbation, std::function< void() > updateFunction, const double evaluationTime)
Function to numerical compute the partial derivative of a torque w.r.t. a body rotational quaternion.
Eigen::Vector3d calculateTorqueWrtParameterPartials (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, std::shared_ptr< basic_astrodynamics::TorqueModel > torqueModel, double parameterPerturbation, std::function< void() > updateDependentVariables, const double currentTime, std::function< void(const double) > timeDependentUpdateDependentVariables)
Function to numerical compute the partial derivative of an torque w.r.t. a double parameter.
Eigen::Matrix< double, 3, Eigen::Dynamic > calculateTorqueWrtParameterPartials (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, std::shared_ptr< basic_astrodynamics::TorqueModel > torqueModel, Eigen::VectorXd parameterPerturbation, std::function< void() > updateDependentVariables, const double currentTime, std::function< void(const double) > timeDependentUpdateDependentVariables)
Function to numerical compute the partial derivative of an torque w.r.t. a vector parameter.
Eigen::MatrixXd calculateTorqueWrtRotationalStatePartials (std::function< void(Eigen::Vector7d) > setBodyRotationalState, std::shared_ptr< basic_astrodynamics::TorqueModel > torqueModel, Eigen::Vector7d originalRotationalState, Eigen::VectorXd statePerturbations, int startIndex, int numberOfEntries, std::function< void() > updateFunction, const double evaluationTime)
Function to numerical compute the partial derivative of a torque w.r.t. a body rotational state.
Eigen::MatrixXd calculateTorqueWrtTranslationalStatePartials (std::function< void(Eigen::Vector6d) > setBodyState, std::shared_ptr< basic_astrodynamics::TorqueModel > torqueModel, Eigen::Vector6d originalState, Eigen::Vector3d statePerturbation, int startIndex, std::function< void() > updateFunction, const double evaluationTime)
Function to numerical compute the partial derivative of a torque w.r.t. a body translational state.
Eigen::Matrix3d computeCumulativeSphericalHessian (const Eigen::Vector3d &sphericalPosition, const double referenceRadius, const double gravitionalParameter, const Eigen::MatrixXd cosineHarmonicCoefficients, const Eigen::MatrixXd sineHarmonicCoefficients, const std::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache)
Function to compute the spherical Hessian of a full spherical harmonic potential.
Eigen::Matrix3d computeDirectTidalAccelerationDueToTideOnPlanetWrtPosition (const Eigen::Vector6d relativeStateOfBodyExertingTide, const Eigen::Vector3d planetAngularVelocityVector, const double currentTidalAccelerationMultiplier, const double timeLag, const bool includeDirectRadialComponent)
Function to compute partial derivative of direct tidal acceleration due to tide on planet w.r.t. position of satellite.
Eigen::Matrix3d computeDirectTidalAccelerationDueToTideOnPlanetWrtVelocity (const Eigen::Vector6d relativeStateOfBodyExertingTide, const double currentTidalAccelerationMultiplier, const double timeLag)
Function to compute partial derivative of direct tidal acceleration due to tide on planet w.r.t. velocity of satellite/.
Eigen::Matrix3d computeDirectTidalAccelerationDueToTideOnSatelliteWrtPosition (const Eigen::Vector6d relativeStateOfBodyExertingTide, const double currentTidalAccelerationMultiplier, const double timeLag, const bool includeDirectRadialComponent)
Function to compute partial derivative of direct tidal acceleration due to tide on satellite w.r.t. position of satellite.
Eigen::Matrix3d computeDirectTidalAccelerationDueToTideOnSatelliteWrtVelocity (const Eigen::Vector6d relativeStateOfBodyExertingTide, const double currentTidalAccelerationMultiplier, const double timeLag)
Function to compute partial derivative of direct tidal acceleration due to tide on satellite w.r.t. velocity of satellite.
Eigen::Matrix3d computePartialDerivativeOfBodyFixedSphericalHarmonicAcceleration (const Eigen::Vector3d &cartesianPosition, const Eigen::Vector3d &sphericalPosition, const double referenceRadius, const double gravitionalParameter, const Eigen::MatrixXd cosineHarmonicCoefficients, const Eigen::MatrixXd sineHarmonicCoefficients, const std::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache, const Eigen::Vector3d &sphericalPotentialGradient, const Eigen::Matrix3d &sphericalToCartesianGradientMatrix)
Calculate partial of spherical harmonic acceleration w.r.t.
Eigen::Matrix3d computePartialDerivativeOfBodyFixedSphericalHarmonicAcceleration (const Eigen::Vector3d &cartesianPosition, const double referenceRadius, const double gravitionalParameter, const Eigen::MatrixXd cosineHarmonicCoefficients, const Eigen::MatrixXd sineHarmonicCoefficients, const std::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache)
Calculate partial of spherical harmonic acceleration w.r.t.
Eigen::Vector3d computePartialOfCannonBallRadiationPressureAccelerationWrtRadiationPressureCoefficient (const double radiationPressure, const double area, const double bodyMass, const Eigen::Vector3d &vectorToSource)
Calculates partial derivative of cannon ball radiation pressure acceleration wrt radiation pressure coefficient.
Eigen::Vector3d computePartialOfCentralGravityWrtGravitationalParameter (const Eigen::Vector3d &acceleratedBodyPosition, const Eigen::Vector3d &acceleratingBodyPosition)
Calculates partial derivative of point mass gravitational acceleration wrt gravitational parameter of the central body.
Eigen::Vector3d computePartialOfCentralGravityWrtGravitationalParameter (const Eigen::Vector3d &gravitationalAcceleration, const double gravitationalParameter)
Calculates partial derivative of point mass gravitational acceleration wrt gravitational parameter of the central body.
void computePartialOfSchwarzschildAccelerationCorrectionWrtGravitationalParameter (const Eigen::Vector6d &relativeState, const double gravitationalParameter, Eigen::MatrixXd &partialMatrix, const double ppnParameterGamma, const double ppnParameterBeta)
Function to compute partial derivative of Schwarzschild acceleration correction w.r.t. central body gravitational patameter.
void computePartialOfSchwarzschildAccelerationCorrectionWrtPosition (const Eigen::Vector6d &relativeState, Eigen::Vector3d &currentAcceleration, Eigen::Matrix3d &partialMatrix, const double gravitationalParameter, const double ppnParameterGamma, const double ppnParameterBeta)
Function to compute partial of Schwarzschild acceleration correction w.r.t. position of body undergoing acceleration.
void computePartialOfSchwarzschildAccelerationCorrectionWrtPpnParameterBeta (const Eigen::Vector6d &relativeState, const double gravitationalParameter, Eigen::MatrixXd &partialMatrix)
Function to compute the partial derivative of Schwarzschild acceleration correction w.r.t. PPN parameter beta.
void computePartialOfSchwarzschildAccelerationCorrectionWrtPpnParameterGamma (const Eigen::Vector6d &relativeState, const double gravitationalParameter, Eigen::MatrixXd &partialMatrix)
Function to compute the partial derivative of Schwarzschild acceleration correction w.r.t. PPN parameter gamma.
void computePartialOfSchwarzschildAccelerationCorrectionWrtVelocity (const Eigen::Vector6d &relativeState, Eigen::Matrix3d &partialMatrix, const double gravitationalParameter, const double ppnParameterGamma)
Function to compute partial of Schwarzschild acceleration correction w.r.t. velocity of body undergoing acceleration.
void computePotentialSphericalHessian (const double distance, const double radiusPowerTerm, const double cosineOfOrderLongitude, const double sineOfOrderLongitude, const double cosineOfLatitude, const double sineOfLatitude, const double preMultiplier, const int degree, const int order, const double cosineHarmonicCoefficient, const double sineHarmonicCoefficient, const double legendrePolynomial, const double legendrePolynomialDerivative, const double legendrePolynomialSecondDerivative, Eigen::Matrix3d &sphericalHessian)
Function to compute the spherical Hessian of a single term of a spherical harmonic potential.
void computePotentialSphericalHessian (const Eigen::Vector3d &sphericalPosition, const double referenceRadius, const double preMultiplier, const int degree, const int order, const double cosineHarmonicCoefficient, const double sineHarmonicCoefficient, const double legendrePolynomial, const double legendrePolynomialDerivative, const double legendrePolynomialSecondDerivative, Eigen::Matrix3d &sphericalHessian)
Function to compute the spherical Hessian of a single term of a spherical harmonic potential.
void computePotentialSphericalHessian (const Eigen::Vector3d &sphericalPosition, const double preMultiplier, const int degree, const int order, const double cosineHarmonicCoefficient, const double sineHarmonicCoefficient, const std::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache, Eigen::Matrix3d &sphericalHessian)
Function to compute the spherical Hessian of a single term of a spherical harmonic potential.
void emptyFunction ()
Dummy function used for update, performs no calculations.
void emptyTimeFunction (const double time)
Dummy function used for update, performs no calculations.
template<typename DirectGravityPartial >
basic_astrodynamics::AvailableAcceleration getAccelerationTypeOfThirdBodyGravity (const std::shared_ptr< DirectGravityPartial > directGravityPartial)
Function to get the third body acceleration type from the direct acceleration partial object.
std::string getCentralBodyNameFromThirdBodyAccelerationPartial (const std::shared_ptr< AccelerationPartial > accelerationPartial)
Function to retrieve name of central body of third-body acceleration partial.
Eigen::Matrix< double, 3, 4 > getPartialDerivativeOfSecondDegreeGravitationalTorqueWrtQuaternion (const double premultiplier, const Eigen::Matrix3d &inertiaTensor, const Eigen::Vector3d &bodyFixedRelativePosition, const Eigen::Vector3d &inertialRelativePosition, const std::vector< Eigen::Matrix3d > derivativeOfRotationMatrixWrtQuaternions)
Function that computes the partial of degree 2 torque w.r.t. the current quaternion elements.
Eigen::Matrix< double, 3, 4 > getPartialDerivativeOfSphericalHarmonicGravitationalTorqueWrtQuaternion (const Eigen::Matrix3d &bodyFixedRelativePositionCrossProductMatrix, const Eigen::Matrix3d &bodyFixedPotentialGradientPositionPartial, const Eigen::Matrix3d &bodyFixedPotentialGradientCrossProductMatrix, const Eigen::Vector3d &inertialRelativePosition, const std::vector< Eigen::Matrix3d > derivativeOfRotationMatrixWrtQuaternions)
Function to compute partial derivative of spherical harmonic torque w.r.t. quaternion elements.
Variables
static const Eigen::Matrix3d UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_C20
static const Eigen::Matrix3d UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_C21
static const Eigen::Matrix3d UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_C22
static const Eigen::Matrix3d UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_MEAN_MOMENT
static const Eigen::Matrix3d UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_S21
static const Eigen::Matrix3d UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_S22
Function Documentation
calculatePartialOfPointMassGravityWrtPositionOfAcceleratedBody()
Eigen::Matrix3d tudat::acceleration_partials::calculatePartialOfPointMassGravityWrtPositionOfAcceleratedBody (const Eigen::Vector3d & acceleratedBodyPosition, const Eigen::Vector3d & acceleratingBodyPosition, const double gravitationalParameter)
Calculates partial derivative of point mass gravitational acceleration wrt the position of body undergoing acceleration.
Parameters
acceleratedBodyPosition Cartesian state of body being accelerated.
acceleratingBodyPosition Cartesian state of body exerting acceleration.
gravitationalParameter Gravitational parameter of gravitating body.
Returns
Matrix with the Jacobian of the acceleration vector w.r.t. the position vector.
Definition at line 21 of file centralGravityAccelerationPartial.cpp.
Referenced by tudat::acceleration_partials::CentralGravitationPartial::update(), and tudat::acceleration_partials::SphericalHarmonicsGravityPartial::update().
computePartialOfCentralGravityWrtGravitationalParameter() [1/2]
Eigen::Vector3d tudat::acceleration_partials::computePartialOfCentralGravityWrtGravitationalParameter (const Eigen::Vector3d & acceleratedBodyPosition, const Eigen::Vector3d & acceleratingBodyPosition)
Calculates partial derivative of point mass gravitational acceleration wrt gravitational parameter of the central body.
Parameters
acceleratedBodyPosition Cartesian state of body being accelerated.
acceleratingBodyPosition Cartesian state of body exerting acceleration.
Returns
Vector with the partial of the acceleration vector w.r.t. ational parameter of the central body.
Definition at line 41 of file centralGravityAccelerationPartial.cpp.
Referenced by tudat::acceleration_partials::CentralGravitationPartial::wrtGravitationalParameterOfCentralBody().
computePartialOfCentralGravityWrtGravitationalParameter() [2/2]
Eigen::Vector3d tudat::acceleration_partials::computePartialOfCentralGravityWrtGravitationalParameter (const Eigen::Vector3d & gravitationalAcceleration, const double gravitationalParameter)
Calculates partial derivative of point mass gravitational acceleration wrt gravitational parameter of the central body.
Parameters
gravitationalAcceleration Gravitational acceleration vector for which partial is to be computed.
gravitationalParameter Gravitational parameter of gravitating body.
Returns
Vector with the partial of the acceleration vector w.r.t. ational parameter of the central body.
Definition at line 54 of file centralGravityAccelerationPartial.cpp.
computeDirectTidalAccelerationDueToTideOnPlanetWrtPosition()
Eigen::Matrix3d tudat::acceleration_partials::computeDirectTidalAccelerationDueToTideOnPlanetWrtPosition (const Eigen::Vector6d relativeStateOfBodyExertingTide, const Eigen::Vector3d planetAngularVelocityVector, const double currentTidalAccelerationMultiplier, const double timeLag, const bool includeDirectRadialComponent)
Function to compute partial derivative of direct tidal acceleration due to tide on planet w.r.t. position of satellite (equal to -1 * partial w.r.t. position of planet)
Parameters
relativeStateOfBodyExertingTide State of satellite w.r.t. host planet.
planetAngularVelocityVector Angular velocity vector ogf host planet
currentTidalAccelerationMultiplier Scalar multiplier that is common to all vector terms (term outside of brackets in Eq. (3) of Lainey et al. (2007)).
timeLag Time lag of tidal bulge
includeDirectRadialComponent True if term independent of time lag is to be included, false otherwise
Returns
Partial derivative of direct tidal acceleration due to tide on planet w.r.t. position of satellite
Definition at line 22 of file directTidalDissipationAccelerationPartial.cpp.
References tudat::linear_algebra::getCrossProductMatrix().
Referenced by tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::update().
computeDirectTidalAccelerationDueToTideOnPlanetWrtVelocity()
Eigen::Matrix3d tudat::acceleration_partials::computeDirectTidalAccelerationDueToTideOnPlanetWrtVelocity (const Eigen::Vector6d relativeStateOfBodyExertingTide, const double currentTidalAccelerationMultiplier, const double timeLag)
Function to compute partial derivative of direct tidal acceleration due to tide on planet w.r.t. velocity of satellite.
Function to compute partial derivative of direct tidal acceleration due to tide on planet w.r.t. velocity of satellite (equal to -1 * partial w.r.t. velocity of planet)
Parameters
relativeStateOfBodyExertingTide State of satellite w.r.t. host planet.
currentTidalAccelerationMultiplier Scalar multiplier that is common to all vector terms (term outside of brackets in Eq. (3) of Lainey et al. (2007)).
timeLag Time lag of tidal bulge
Returns
Partial derivative of direct tidal acceleration due to tide on planet w.r.t. velocity of satellite
Definition at line 49 of file directTidalDissipationAccelerationPartial.cpp.
Referenced by tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::update().
computeDirectTidalAccelerationDueToTideOnSatelliteWrtPosition()
Eigen::Matrix3d tudat::acceleration_partials::computeDirectTidalAccelerationDueToTideOnSatelliteWrtPosition (const Eigen::Vector6d relativeStateOfBodyExertingTide, const double currentTidalAccelerationMultiplier, const double timeLag, const bool includeDirectRadialComponent)
Function to compute partial derivative of direct tidal acceleration due to tide on satellite w.r.t. position of satellite (equal to -1 * partial w.r.t. position of planet)
Parameters
relativeStateOfBodyExertingTide State of satellite w.r.t. host planet.
currentTidalAccelerationMultiplier Scalar multiplier that is common to all vector terms (term outside of brackets in Eq. (3) of Lainey et al. (2007)).
timeLag Time lag of tidal bulge
includeDirectRadialComponent True if term independent of time lag is to be included, false otherwise
Returns
Partial derivative of direct tidal acceleration due to tide on satellite w.r.t. position of satellite
Definition at line 62 of file directTidalDissipationAccelerationPartial.cpp.
Referenced by tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::update().
computeDirectTidalAccelerationDueToTideOnSatelliteWrtVelocity()
Eigen::Matrix3d tudat::acceleration_partials::computeDirectTidalAccelerationDueToTideOnSatelliteWrtVelocity (const Eigen::Vector6d relativeStateOfBodyExertingTide, const double currentTidalAccelerationMultiplier, const double timeLag)
Function to compute partial derivative of direct tidal acceleration due to tide on satellite w.r.t. velocity of satellite (equal to -1 * partial w.r.t. velocity of planet)
Parameters
relativeStateOfBodyExertingTide State of satellite w.r.t. host planet.
currentTidalAccelerationMultiplier Scalar multiplier that is common to all vector terms (term outside of brackets in Eq. (3) of Lainey et al. (2007)).
timeLag Time lag of tidal bulge
Returns
Partial derivative of direct tidal acceleration due to tide on satellite w.r.t. velocity of satellite
Definition at line 85 of file directTidalDissipationAccelerationPartial.cpp.
Referenced by tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::update().
calculateNumericalPartialOfTrueAnomalyWrtState()
Eigen::Matrix< double, 1, 6 > tudat::acceleration_partials::calculateNumericalPartialOfTrueAnomalyWrtState (const Eigen::Vector6d & cartesianElements, const double gravitationalParameter, const Eigen::Vector6d & cartesianStateElementPerturbations)
unction determine the numerical partial derivative of the true anomaly wrt the elements of the Cartesian state, from the Cartesian state as input. A first-order central difference with a user-defined Cartesian state perturbation vector is used.
Parameters
cartesianElements Nominal Cartesian elements at which the partials are to be computed
gravitationalParameter Gravitational parameter of central body around which Keplerian orbit is given
cartesianStateElementPerturbations Numerical perturbations of Cartesian state that are to be used
Returns
Partial of Cartesian state wrt true anomaly of orbit.
Definition at line 23 of file empiricalAccelerationPartial.cpp.
References tudat::json_interface::cartesianElements, tudat::orbital_element_conversions::convertCartesianToKeplerianElements(), and tudat::orbital_element_conversions::trueAnomalyIndex.
Referenced by tudat::acceleration_partials::EmpiricalAccelerationPartial::update().
emptyFunction()
void tudat::acceleration_partials::emptyFunction ()
Dummy function used for update, performs no calculations.
Definition at line 20 of file numericalAccelerationPartial.cpp.
emptyTimeFunction()
void tudat::acceleration_partials::emptyTimeFunction (const double time)
Dummy function used for update, performs no calculations.
Parameters
time Input parameter, not used by function.
Definition at line 23 of file numericalAccelerationPartial.cpp.
calculateAccelerationWrtStatePartials()
Eigen::Matrix3d tudat::acceleration_partials::calculateAccelerationWrtStatePartials (std::function< void(Eigen::Vector6d) > setBodyState, std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > accelerationModel, Eigen::Vector6d originalState, Eigen::Vector3d statePerturbation, int startIndex, std::function< void() > updateFunction = emptyFunction, const double evaluationTime = TUDAT_NAN)
Function to numerical compute the partial derivative of an acceleration w.r.t. a body state (position or velocity), using a first-order central difference method.
Parameters
setBodyState Function to reset the current state w.r.t. which the partial is to be computed.
accelerationModel Acceleration model for which the partial derivative is to be computed.
originalState Nominal state at which the partial derivative is to be computed.
statePerturbation Perturbation to the position or velocity that is to be used
startIndex Start index in the state vector from where the statePerturbation is to be added (i.e. 0 if function is to compute partial w.r.t. position, 3 if w.r.t velocity).
updateFunction Function to update the required environment models following the change of the body state.
evaluationTime Time at which partial is to be evaluated (default NaN).
Returns
Numerical partial of the acceleration w.r.t. position or velocity (depending on function input).
Definition at line 26 of file numericalAccelerationPartial.cpp.
References TUDAT_NAN.
calculateTorqueWrtTranslationalStatePartials()
Eigen::MatrixXd tudat::acceleration_partials::calculateTorqueWrtTranslationalStatePartials (std::function< void(Eigen::Vector6d) > setBodyState, std::shared_ptr< basic_astrodynamics::TorqueModel > torqueModel, Eigen::Vector6d originalState, Eigen::Vector3d statePerturbation, int startIndex, std::function< void() > updateFunction = emptyFunction, const double evaluationTime = TUDAT_NAN)
Function to numerical compute the partial derivative of an torque w.r.t. a body translational state elements using a first-order central difference method.
Parameters
setBodyState Function to reset the current translational state w.r.t. which the partial is to be computed.
torqueModel Torque model for which the partial derivative is to be computed.
originalState Nominal translational state at which the partial derivative is to be computed.
statePerturbation Perturbation to the states that is to be used
startIndex Start index in the state vector from where the statePerturbation is to be added (i.e. 0 if function is to compute partial w.r.t. position, 3 if w.r.t velocity).
updateFunction Function to update the required environment models following the change of the body state.
evaluationTime Time at which partial is to be evaluated (default NaN).
Returns
Numerical partial of the torque w.r.t. body translational state elements
Definition at line 85 of file numericalAccelerationPartial.cpp.
References TUDAT_NAN, and tudat::basic_astrodynamics::updateAndGetTorque().
calculateTorqueWrtRotationalStatePartials()
Eigen::MatrixXd tudat::acceleration_partials::calculateTorqueWrtRotationalStatePartials (std::function< void(Eigen::Vector7d) > setBodyRotationalState, std::shared_ptr< basic_astrodynamics::TorqueModel > torqueModel, Eigen::Vector7d originalRotationalState, Eigen::VectorXd statePerturbations, int startIndex, int numberOfEntries, std::function< void() > updateFunction = emptyFunction, const double evaluationTime = TUDAT_NAN)
Function to numerical compute the partial derivative of an torque w.r.t. a body rotational state elements using a first-order central difference method.
Parameters
setBodyRotationalState Function to reset the current rotational state w.r.t. which the partial is to be computed.
torqueModel Torque model for which the partial derivative is to be computed.
originalRotationalState Nominal rotational state at which the partial derivative is to be computed.
statePerturbations Perturbation to the states that is to be used
startIndex Start index in the state vector from where the statePerturbation is to be added (i.e. 0 if function is to compute partial w.r.t. quaternion, 4 if w.r.t angular velocity).
numberOfEntries Integer denoting the number of entries.
updateFunction Function to update the required environment models following the change of the body state.
evaluationTime Time at which partial is to be evaluated (default NaN).
Returns
Numerical partial of the torque w.r.t. body rotational state elements
Definition at line 143 of file numericalAccelerationPartial.cpp.
References TUDAT_NAN, and tudat::basic_astrodynamics::updateAndGetTorque().
calculateAccelerationDeviationDueToOrientationChange()
Eigen::MatrixXd tudat::acceleration_partials::calculateAccelerationDeviationDueToOrientationChange (const std::function< void(Eigen::Vector7d) > setBodyRotationalState, std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > accelerationModel, const Eigen::Vector7d & originalRotationalState, const Eigen::Vector4d & commandedQuaternionPerturbation, std::vector< Eigen::Vector4d > & appliedQuaternionPerturbation, std::function< void() > updateFunction = emptyFunction, const double evaluationTime = TUDAT_NAN)
Function to numerical compute the partial derivative of an acceleration w.r.t. a body rotational quaternion elements using a first-order central difference method.
Parameters
setBodyRotationalState Function to reset the current rotational state w.r.t. which the partial is to be computed.
accelerationModel Acceleration model for which the partial derivative is to be computed.
originalRotationalState Nominal rotational state at which the partial derivative is to be computed.
commandedQuaternionPerturbation Perturbation to the quaternion that is to be used
appliedQuaternionPerturbation Quaternion perturbations that were actually applied (after manifold correction)
updateFunction Function to update the required environment models following the change of the body state.
evaluationTime Time at which partial is to be evaluated (default NaN).
Returns
Numerical partial of the acceleration w.r.t. body rotational quaternion elements
Definition at line 203 of file numericalAccelerationPartial.cpp.
References TUDAT_NAN, and tudat::basic_astrodynamics::updateAndGetAcceleration().
calculateTorqueDeviationDueToOrientationChange()
Eigen::MatrixXd tudat::acceleration_partials::calculateTorqueDeviationDueToOrientationChange (const std::function< void(Eigen::Vector7d) > setBodyRotationalState, const std::shared_ptr< basic_astrodynamics::TorqueModel > torqueModel, const Eigen::Vector7d & originalRotationalState, const Eigen::Vector4d & commandedQuaternionPerturbation, std::vector< Eigen::Vector4d > & appliedQuaternionPerturbation, std::function< void() > updateFunction = emptyFunction, const double evaluationTime = TUDAT_NAN)
Function to numerical compute the partial derivative of an torque w.r.t. a body rotational quaternion elements using a first-order central difference method.
Parameters
setBodyRotationalState Function to reset the current rotational state w.r.t. which the partial is to be computed.
torqueModel Torque model for which the partial derivative is to be computed.
originalRotationalState Nominal rotational state at which the partial derivative is to be computed.
commandedQuaternionPerturbation Perturbation to the quaternion that is to be used
appliedQuaternionPerturbation Quaternion perturbations that were actually applied (after manifold correction)
updateFunction Function to update the required environment models following the change of the body state.
evaluationTime Time at which partial is to be evaluated (default NaN).
Returns
Numerical partial of the torque w.r.t. body rotational quaternion elements
Definition at line 250 of file numericalAccelerationPartial.cpp.
References TUDAT_NAN, and tudat::basic_astrodynamics::updateAndGetTorque().
calculateAccelerationWrtParameterPartials() [1/2]
Eigen::Vector3d tudat::acceleration_partials::calculateAccelerationWrtParameterPartials (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > accelerationModel, double parameterPerturbation, std::function< void() > updateDependentVariables = emptyFunction, const double currentTime = 0.0, std::function< void(const double) > timeDependentUpdateDependentVariables = emptyTimeFunction)
Function to numerical compute the partial derivative of an acceleration w.r.t. a double parameter, using a first-order central difference method.
Parameters
parameter Object describing the parameter w.r.t. which the partial is to be taken.
accelerationModel Acceleration model for which the partial derivative is to be computed.
parameterPerturbation Perturbation to be used for parameter value.
updateDependentVariables Function to update the required environment models following the change in parameter, for models that do not explicitly depend on the current time.
currentTime Time at which partial is to be computed.
timeDependentUpdateDependentVariables Function to update the required environment models following the change in parameters for models that do explicitly depend on the current time.
Returns
Numerical partial of the acceleration w.r.t. given parameter.
Definition at line 294 of file numericalAccelerationPartial.cpp.
References TUDAT_NAN.
calculateTorqueWrtParameterPartials() [1/2]
Eigen::Vector3d tudat::acceleration_partials::calculateTorqueWrtParameterPartials (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, std::shared_ptr< basic_astrodynamics::TorqueModel > torqueModel, double parameterPerturbation, std::function< void() > updateDependentVariables = emptyFunction, const double currentTime = 0.0, std::function< void(const double) > timeDependentUpdateDependentVariables = emptyTimeFunction)
Function to numerical compute the partial derivative of an torque w.r.t. a double parameter, using a first-order central difference method.
Parameters
parameter Object describing the parameter w.r.t. which the partial is to be taken.
torqueModel Torque model for which the partial derivative is to be computed.
parameterPerturbation Perturbation to be used for parameter value.
updateDependentVariables Function to update the required environment models following the change in parameter, for models that do not explicitly depend on the current time.
currentTime Time at which partial is to be computed.
timeDependentUpdateDependentVariables Function to update the required environment models following the change in parameters for models that do explicitly depend on the current time.
Returns
Numerical partial of the torque w.r.t. given parameter.
Definition at line 342 of file numericalAccelerationPartial.cpp.
References TUDAT_NAN, and tudat::basic_astrodynamics::updateAndGetTorque().
calculateAccelerationWrtParameterPartials() [2/2]
Eigen::Matrix< double, 3, Eigen::Dynamic > tudat::acceleration_partials::calculateAccelerationWrtParameterPartials (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > accelerationModel, Eigen::VectorXd parameterPerturbation, std::function< void() > updateDependentVariables = emptyFunction, const double currentTime = 0.0, std::function< void(const double) > timeDependentUpdateDependentVariables = emptyTimeFunction)
Function to numerical compute the partial derivative of an acceleration w.r.t. a vector parameter, using a first-order central difference method.
Parameters
parameter Object describing the parameter w.r.t. which the partial is to be taken.
accelerationModel Acceleration model for which the partial derivative is to be computed.
parameterPerturbation Perturbations to be used for parameter value.
updateDependentVariables Function to update the required environment models following the change in parameter, for models that do not explicitly depend on the current time.
currentTime Time at which partial is to be computed.
timeDependentUpdateDependentVariables Function to update the required environment models following the change in parameters for models that do explicitly depend on the current time.
Returns
Numerical partial of the acceleration w.r.t. given parameter.
Definition at line 391 of file numericalAccelerationPartial.cpp.
References TUDAT_NAN.
calculateTorqueWrtParameterPartials() [2/2]
Eigen::Matrix< double, 3, Eigen::Dynamic > tudat::acceleration_partials::calculateTorqueWrtParameterPartials (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, std::shared_ptr< basic_astrodynamics::TorqueModel > torqueModel, Eigen::VectorXd parameterPerturbation, std::function< void() > updateDependentVariables = emptyFunction, const double currentTime = 0.0, std::function< void(const double) > timeDependentUpdateDependentVariables = emptyTimeFunction)
Function to numerical compute the partial derivative of an torque w.r.t. a vector parameter, using a first-order central difference method.
Parameters
parameter Object describing the parameter w.r.t. which the partial is to be taken.
torqueModel Torque model for which the partial derivative is to be computed.
parameterPerturbation Perturbation to be used for parameter value.
updateDependentVariables Function to update the required environment models following the change in parameter, for models that do not explicitly depend on the current time.
currentTime Time at which partial is to be computed.
timeDependentUpdateDependentVariables Function to update the required environment models following the change in parameters for models that do explicitly depend on the current time.
Returns
Numerical partial of the torque w.r.t. given parameter.
Definition at line 458 of file numericalAccelerationPartial.cpp.
References TUDAT_NAN, and tudat::basic_astrodynamics::updateAndGetTorque().
computePartialOfCannonBallRadiationPressureAccelerationWrtRadiationPressureCoefficient()
Eigen::Vector3d tudat::acceleration_partials::computePartialOfCannonBallRadiationPressureAccelerationWrtRadiationPressureCoefficient (const double radiationPressure, const double area, const double bodyMass, const Eigen::Vector3d & vectorToSource)
Calculates partial derivative of cannon ball radiation pressure acceleration wrt radiation pressure coefficient.
Parameters
radiationPressure Current radiation pressure (in N/m^2)
area (Reference) area for radiation pressure acceleration.
bodyMass Mass of body undergoing acceleration.
vectorToSource Vector from body undergoing acceleration to source of radiation.
Returns
Partial derivative of cannon ball radiation pressure acceleration wrt radiation pressure coefficient.
Definition at line 21 of file radiationPressureAccelerationPartial.cpp.
Referenced by tudat::acceleration_partials::CannonBallRadiationPressurePartial::wrtRadiationPressureCoefficient().
computePartialOfSchwarzschildAccelerationCorrectionWrtPosition()
void tudat::acceleration_partials::computePartialOfSchwarzschildAccelerationCorrectionWrtPosition (const Eigen::Vector6d & relativeState, Eigen::Vector3d & currentAcceleration, Eigen::Matrix3d & partialMatrix, const double gravitationalParameter, const double ppnParameterGamma = 1.0, const double ppnParameterBeta = 1.0)
Function to compute partial of Schwarzschild acceleration correction w.r.t. position of body undergoing acceleration
Parameters
relativeState Cartesian state of body undergoing, w.r.t. body exerting, acceleration.
currentAcceleration Current Schwarzschild acceleration correction
partialMatrix Requested (returnd by reference)
gravitationalParameter Gravitational parameter of body exerting acceleration.
ppnParameterGamma PPN parameter gamma
ppnParameterBeta PPN parameter beta
Definition at line 20 of file relativisticAccelerationPartial.cpp.
References tudat::physical_constants::INVERSE_SQUARE_SPEED_OF_LIGHT.
Referenced by tudat::acceleration_partials::RelativisticAccelerationPartial::update().
computePartialOfSchwarzschildAccelerationCorrectionWrtVelocity()
void tudat::acceleration_partials::computePartialOfSchwarzschildAccelerationCorrectionWrtVelocity (const Eigen::Vector6d & relativeState, Eigen::Matrix3d & partialMatrix, const double gravitationalParameter, const double ppnParameterGamma = 1.0)
Function to compute partial of Schwarzschild acceleration correction w.r.t. velocity of body undergoing acceleration
Parameters
relativeState Cartesian state of body undergoing, w.r.t. body exerting, acceleration.
partialMatrix Requested (returnd by reference)
gravitationalParameter Gravitational parameter of body exerting acceleration.
ppnParameterGamma PPN parameter gamma
Definition at line 37 of file relativisticAccelerationPartial.cpp.
References tudat::physical_constants::INVERSE_SQUARE_SPEED_OF_LIGHT.
Referenced by tudat::acceleration_partials::RelativisticAccelerationPartial::update().
computePartialOfSchwarzschildAccelerationCorrectionWrtGravitationalParameter()
void tudat::acceleration_partials::computePartialOfSchwarzschildAccelerationCorrectionWrtGravitationalParameter (const Eigen::Vector6d & relativeState, const double gravitationalParameter, Eigen::MatrixXd & partialMatrix, const double ppnParameterGamma = 1.0, const double ppnParameterBeta = 1.0)
Function to compute partial derivative of Schwarzschild acceleration correction w.r.t. central body gravitational patameter.
Parameters
relativeState Cartesian state of body undergoing, w.r.t. body exerting, acceleration.
gravitationalParameter Gravitational parameter of body exerting acceleration.
partialMatrix Requested (returnd by reference)
ppnParameterGamma PPN parameter gamma
ppnParameterBeta PPN parameter bet
Definition at line 53 of file relativisticAccelerationPartial.cpp.
References tudat::physical_constants::INVERSE_SQUARE_SPEED_OF_LIGHT.
Referenced by tudat::acceleration_partials::RelativisticAccelerationPartial::wrtGravitationalParameterOfCentralBody().
computePartialOfSchwarzschildAccelerationCorrectionWrtPpnParameterGamma()
void tudat::acceleration_partials::computePartialOfSchwarzschildAccelerationCorrectionWrtPpnParameterGamma (const Eigen::Vector6d & relativeState, const double gravitationalParameter, Eigen::MatrixXd & partialMatrix)
Function to compute the partial derivative of Schwarzschild acceleration correction w.r.t. PPN parameter gamma
Parameters
relativeState Cartesian state of body undergoing, w.r.t. body exerting, acceleration.
gravitationalParameter Gravitational parameter of body exerting acceleration.
partialMatrix Requested (returnd by reference)
Definition at line 71 of file relativisticAccelerationPartial.cpp.
References tudat::physical_constants::INVERSE_SQUARE_SPEED_OF_LIGHT.
Referenced by tudat::acceleration_partials::RelativisticAccelerationPartial::wrtPpnParameterGamma().
computePartialOfSchwarzschildAccelerationCorrectionWrtPpnParameterBeta()
void tudat::acceleration_partials::computePartialOfSchwarzschildAccelerationCorrectionWrtPpnParameterBeta (const Eigen::Vector6d & relativeState, const double gravitationalParameter, Eigen::MatrixXd & partialMatrix)
Function to compute the partial derivative of Schwarzschild acceleration correction w.r.t. PPN parameter beta
Parameters
relativeState Position of body undergoing, w.r.t. body exerting, acceleration.
gravitationalParameter Gravitational parameter of body exerting acceleration.
partialMatrix Requested (returnd by reference)
Definition at line 85 of file relativisticAccelerationPartial.cpp.
References tudat::physical_constants::INVERSE_SQUARE_SPEED_OF_LIGHT.
Referenced by tudat::acceleration_partials::RelativisticAccelerationPartial::wrtPpnParameterBeta().
computePotentialSphericalHessian() [1/3]
void tudat::acceleration_partials::computePotentialSphericalHessian (const double distance, const double radiusPowerTerm, const double cosineOfOrderLongitude, const double sineOfOrderLongitude, const double cosineOfLatitude, const double sineOfLatitude, const double preMultiplier, const int degree, const int order, const double cosineHarmonicCoefficient, const double sineHarmonicCoefficient, const double legendrePolynomial, const double legendrePolynomialDerivative, const double legendrePolynomialSecondDerivative, Eigen::Matrix3d & sphericalHessian)
Function to compute the spherical Hessian (i.e. matrix of second derivatives w.r.t. spherical components radius, latitude and longitude) of a single term of a spherical harmonic potential.
Parameters
distance Distance to center of body with gravity field at which the partials are to be calculated
radiusPowerTerm Distance divided by the reference radius of the gravity field, to the power (degree + 1)
cosineOfOrderLongitude Cosine of order times the longitude at which the potential is to be calculated
sineOfOrderLongitude Sine of order times the longitude at which the potential is to be calculated
cosineOfLatitude Cosine of the latitude at which the potential is to be calculated
sineOfLatitude Sine of the latitude at which the potential is to be calculated
preMultiplier Pre-multiplier of potential (gravitational parametere divided by reference radius in normal representation)
degree Degree of the harmonic for which the gradient is to be computed.
order Order of the harmonic for which the gradient is to be computed.
cosineHarmonicCoefficient Coefficient which characterizes relative strengh of a harmonic term.
sineHarmonicCoefficient Coefficient which characterizes relative strengh of a harmonic term.
legendrePolynomial Value of associated Legendre polynomial with the same degree and order as the to be computed harmonic, and with the sine of the latitude coordinate as polynomial parameter.
legendrePolynomialDerivative Value of the derivative of parameter 'legendrePolynomial' with respect to the sine of the latitude angle.
legendrePolynomialSecondDerivative Value of second derivative of parameter 'legendrePolynomial' with respect to the sine of the latitude angle.
sphericalHessian Hessian of potential term in spherical coordinates (returned by reference).
Definition at line 29 of file sphericalHarmonicPartialFunctions.cpp.
Referenced by computeCumulativeSphericalHessian(), and computePotentialSphericalHessian().
computePotentialSphericalHessian() [2/3]
void tudat::acceleration_partials::computePotentialSphericalHessian (const Eigen::Vector3d & sphericalPosition, const double referenceRadius, const double preMultiplier, const int degree, const int order, const double cosineHarmonicCoefficient, const double sineHarmonicCoefficient, const double legendrePolynomial, const double legendrePolynomialDerivative, const double legendrePolynomialSecondDerivative, Eigen::Matrix3d & sphericalHessian)
Function to compute the spherical Hessian (i.e. matrix of second derivatives w.r.t. spherical components radius, latitude and longitude) of a single term of a spherical harmonic potential.
Parameters
sphericalPosition Spherical position (radius, ,latitude, longitude) at which potential partials are to be evaluated
referenceRadius Reference radius of spherical harmonic potential.
preMultiplier Pre-multiplier of potential (gravitational parametere divided by reference radius in normal representation)
degree Degree of the harmonic for which the gradient is to be computed.
order Order of the harmonic for which the gradient is to be computed.
cosineHarmonicCoefficient Coefficient which characterizes relative strengh of a harmonic term.
sineHarmonicCoefficient Coefficient which characterizes relative strengh of a harmonic term.
legendrePolynomial Value of associated Legendre polynomial with the same degree and order as the to be computed harmonic, and with the sine of the latitude coordinate as polynomial parameter.
legendrePolynomialDerivative Value of the derivative of parameter 'legendrePolynomial' with respect to the sine of the latitude angle.
legendrePolynomialSecondDerivative Value of second derivative of parameter 'legendrePolynomial' with respect to the sine of the latitude angle.
sphericalHessian Hessian of potential term in spherical coordinates (returned by reference).
Definition at line 73 of file sphericalHarmonicPartialFunctions.cpp.
References computePotentialSphericalHessian(), tudat::orbital_element_conversions::latitudeIndex, tudat::orbital_element_conversions::longitudeIndex, tudat::orbital_element_conversions::radiusIndex, and tudat::basic_mathematics::raiseToIntegerPower().
computePotentialSphericalHessian() [3/3]
void tudat::acceleration_partials::computePotentialSphericalHessian (const Eigen::Vector3d & sphericalPosition, const double preMultiplier, const int degree, const int order, const double cosineHarmonicCoefficient, const double sineHarmonicCoefficient, const std::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache, Eigen::Matrix3d & sphericalHessian)
Function to compute the spherical Hessian (i.e. matrix of second derivatives w.r.t. spherical components radius, latitude and longitude) of a single term of a spherical harmonic potential.
Parameters
sphericalPosition Spherical position (radius, ,latitude, longitude) at which potential partials are to be evaluated
preMultiplier Pre-multiplier of potential (gravitational parametere divided by reference radius in normal representation)
degree Degree of the harmonic for which the gradient is to be computed.
order Order of the harmonic for which the gradient is to be computed.
cosineHarmonicCoefficient Coefficient which characterizes relative strengh of a harmonic term.
sineHarmonicCoefficient Coefficient which characterizes relative strengh of a harmonic term.
sphericalHarmonicsCache Cache object containing precomputed spherical harmonics terms.
sphericalHessian Hessian of potential term in spherical coordinates (returned by reference).
Definition at line 98 of file sphericalHarmonicPartialFunctions.cpp.
References computePotentialSphericalHessian().
computeCumulativeSphericalHessian()
Eigen::Matrix3d tudat::acceleration_partials::computeCumulativeSphericalHessian (const Eigen::Vector3d & sphericalPosition, const double referenceRadius, const double gravitionalParameter, const Eigen::MatrixXd cosineHarmonicCoefficients, const Eigen::MatrixXd sineHarmonicCoefficients, const std::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache)
Function to compute the spherical Hessian (i.e. matrix of second derivatives w.r.t. spherical components radius, latitude and longitude) of a full spherical harmonic potential.
Parameters
sphericalPosition Spherical position (radius, ,latitude, longitude) at which potential partials are to be evaluated
referenceRadius Reference radius of spherical harmonic potential.
gravitionalParameter Gravitational parameter used for spherical harmonic expansion
cosineHarmonicCoefficients Matrix of coefficient which characterize the relative strengh of cosine harmonic terms.
sineHarmonicCoefficients Matrix of coefficient which characterize the relative strengh of sine harmonic terms.
sphericalHarmonicsCache Cache object containing precomputed spherical harmonics terms.
Returns
Hessian of potential in spherical coordinates (returned by reference).
Definition at line 123 of file sphericalHarmonicPartialFunctions.cpp.
References computePotentialSphericalHessian().
Referenced by computePartialDerivativeOfBodyFixedSphericalHarmonicAcceleration().
computePartialDerivativeOfBodyFixedSphericalHarmonicAcceleration() [1/2]
Eigen::Matrix3d tudat::acceleration_partials::computePartialDerivativeOfBodyFixedSphericalHarmonicAcceleration (const Eigen::Vector3d & cartesianPosition, const Eigen::Vector3d & sphericalPosition, const double referenceRadius, const double gravitionalParameter, const Eigen::MatrixXd cosineHarmonicCoefficients, const Eigen::MatrixXd sineHarmonicCoefficients, const std::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache, const Eigen::Vector3d & sphericalPotentialGradient, const Eigen::Matrix3d & sphericalToCartesianGradientMatrix)
Calculate partial of spherical harmonic acceleration w.r.t. position of body undergoing acceleration (in the body-fixed frame)
Calculate partial of spherical harmonic acceleration w.r.t. position of body undergoing acceleration (in the body-fixed frame)
position of body undergoing acceleration (in the body-fixed frame)
Parameters
cartesianPosition Cartesian position at which potential partials are to be evaluated
sphericalPosition Spherical position (radius, ,latitude, longitude) at which potential partials are to be evaluated
referenceRadius Reference radius of spherical harmonic potential.
gravitionalParameter Gravitational parameter used for spherical harmonic expansion
cosineHarmonicCoefficients Cosine spherical harmonic coefficients.
sineHarmonicCoefficients Sine spherical harmonic coefficients
sphericalHarmonicsCache Cache object containing precomputed spherical harmonics terms.
sphericalPotentialGradient Potential gradient in spherical coordinates
sphericalToCartesianGradientMatrix Matrix to convert (by premultiplication) a spherical gradient to a Cartesian gradient
Returns
Partial of spherical harmonic acceleration w.r.t. position of body undergoinng acceleration (equals minus partial of spherical harmonic acceleration w.r.t. position of body exerting acceleration) with both acceleration and position in body-fixed frame.
Definition at line 152 of file sphericalHarmonicPartialFunctions.cpp.
References computeCumulativeSphericalHessian(), and tudat::coordinate_conversions::getDerivativeOfSphericalToCartesianGradient().
Referenced by computePartialDerivativeOfBodyFixedSphericalHarmonicAcceleration(), and tudat::acceleration_partials::SphericalHarmonicsGravityPartial::update().
computePartialDerivativeOfBodyFixedSphericalHarmonicAcceleration() [2/2]
Eigen::Matrix3d tudat::acceleration_partials::computePartialDerivativeOfBodyFixedSphericalHarmonicAcceleration (const Eigen::Vector3d & cartesianPosition, const double referenceRadius, const double gravitionalParameter, const Eigen::MatrixXd cosineHarmonicCoefficients, const Eigen::MatrixXd sineHarmonicCoefficients, const std::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache)
Calculate partial of spherical harmonic acceleration w.r.t. position of body undergoing acceleration (in the body-fixed frame)
Calculate partial of spherical harmonic acceleration w.r.t. position of body undergoing acceleration (in the body-fixed frame)
position of body undergoing acceleration (in the body-fixed frame)
Parameters
cartesianPosition Cartesian position at which potential partials are to be evaluated
referenceRadius Reference radius of spherical harmonic potential.
gravitionalParameter Gravitational parameter used for spherical harmonic expansion
cosineHarmonicCoefficients Cosine spherical harmonic coefficients.
sineHarmonicCoefficients Sine spherical harmonic coefficients
sphericalHarmonicsCache Cache object containing precomputed spherical harmonics terms.
Returns
Partial of spherical harmonic acceleration w.r.t. position of body undergoinng acceleration (equals minus partial of spherical harmonic acceleration w.r.t. position of body exerting acceleration) with both acceleration and position in body-fixed frame.
Definition at line 181 of file sphericalHarmonicPartialFunctions.cpp.
References tudat::gravitation::computeGeodesyNormalizedGravitationalAccelerationSum(), computePartialDerivativeOfBodyFixedSphericalHarmonicAcceleration(), tudat::coordinate_conversions::convertCartesianToSpherical(), tudat::coordinate_conversions::getSphericalToCartesianGradientMatrix(), and tudat::mathematical_constants::PI.
calculateSphericalHarmonicGravityWrtCCoefficients()
void tudat::acceleration_partials::calculateSphericalHarmonicGravityWrtCCoefficients (const Eigen::Vector3d & sphericalPosition, const double referenceRadius, const double gravitionalParameter, const std::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache, const std::vector< std::pair< int, int > > & blockIndices, const Eigen::Matrix3d & sphericalToCartesianGradientMatrix, const Eigen::Matrix3d & bodyFixedToIntegrationFrame, Eigen::MatrixXd & partialsMatrix, const int maximumAccelerationDegree, const int maximumAccelerationOrder)
Calculate partial of spherical harmonic acceleration w.r.t. a set of cosine coefficients
Parameters
sphericalPosition Spherical coordinate of body undergoing acceleration in frame fixed to body exerting acceleration, as radius, latitude, longitude.
referenceRadius Reference radius of spherical harmonic potential.
gravitionalParameter Gravitational parameter used for spherical harmonic expansion
sphericalHarmonicsCache Cache object containing precomputed spherical harmonics terms.
blockIndices List of cosine coefficient indices wrt which the partials are to be taken (first and second are degree and order for each vector entry).
sphericalToCartesianGradientMatrix Matrix to convert (by premultiplication) a spherical gradient to a Cartesian gradient
bodyFixedToIntegrationFrame Matrix to rotate from body-fixed to integration frame.
partialsMatrix Partials of spherical harmonic acceleration w.r.t. to requested set of cosine coefficients (returned by reference).
maximumAccelerationDegree Maximum degree of acceleration for which partial is to be computed
maximumAccelerationOrder Maximum degree of acceleration for which partial is to be computed
Definition at line 212 of file sphericalHarmonicPartialFunctions.cpp.
References tudat::basic_mathematics::computePotentialGradient(), and tudat::orbital_element_conversions::radiusIndex.
Referenced by tudat::acceleration_partials::SphericalHarmonicsGravityPartial::wrtCosineCoefficientBlock(), and tudat::acceleration_partials::SphericalHarmonicsGravityPartial::wrtTidalModelParameter().
calculateSphericalHarmonicGravityWrtSCoefficients()
void tudat::acceleration_partials::calculateSphericalHarmonicGravityWrtSCoefficients (const Eigen::Vector3d & sphericalPosition, const double referenceRadius, const double gravitionalParameter, const std::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache, const std::vector< std::pair< int, int > > & blockIndices, const Eigen::Matrix3d & sphericalToCartesianGradientMatrix, const Eigen::Matrix3d & bodyFixedToIntegrationFrame, Eigen::MatrixXd & partialsMatrix, const int maximumAccelerationDegree, const int maximumAccelerationOrder)
Calculate partial of spherical harmonic acceleration w.r.t. a set of sine coefficients
Parameters
sphericalPosition Spherical coordinate of body undergoing acceleration in frame fixed to body exerting acceleration, as radius, latitude, longitude.
referenceRadius Reference radius of spherical harmonic potential.
gravitionalParameter Gravitational parameter used for spherical harmonic expansion
sphericalHarmonicsCache Cache object containing precomputed spherical harmonics terms.
blockIndices List of cosine coefficient indices wrt which the partials are to be taken (first and second are degree and order for each vector entry).
sphericalToCartesianGradientMatrix Matrix to convert (by premultiplication) a spherical gradient to a Cartesian gradient
bodyFixedToIntegrationFrame Matrix to rotate from body-fixed to integration frame.
partialsMatrix Partials of spherical harmonic acceleration w.r.t. to requested set of sine coefficients (returned by reference).
maximumAccelerationDegree Maximum degree of acceleration for which partial is to be computed
maximumAccelerationOrder Maximum degree of acceleration for which partial is to be computed
Definition at line 259 of file sphericalHarmonicPartialFunctions.cpp.
References tudat::basic_mathematics::computePotentialGradient(), and tudat::orbital_element_conversions::radiusIndex.
Referenced by tudat::acceleration_partials::SphericalHarmonicsGravityPartial::wrtSineCoefficientBlock(), and tudat::acceleration_partials::SphericalHarmonicsGravityPartial::wrtTidalModelParameter().
getAccelerationTypeOfThirdBodyGravity()
template<typename DirectGravityPartial > basic_astrodynamics::AvailableAcceleration tudat::acceleration_partials::getAccelerationTypeOfThirdBodyGravity (const std::shared_ptr< DirectGravityPartial > directGravityPartial)
Function to get the third body acceleration type from the direct acceleration partial object.
Parameters
directGravityPartial Partial derivative of direct acceleration.
Returns
Type of acceleration for third body acceleration for which direct acceleration partial is given by directGravityPartial (i.e. third_body_central_gravity if input is of type CentralGravitationPartial).
Definition at line 38 of file thirdBodyGravityPartial.h.
References tudat::basic_astrodynamics::third_body_central_gravity, tudat::basic_astrodynamics::third_body_mutual_spherical_harmonic_gravity, and tudat::basic_astrodynamics::third_body_spherical_harmonic_gravity.
getCentralBodyNameFromThirdBodyAccelerationPartial()
std::string tudat::acceleration_partials::getCentralBodyNameFromThirdBodyAccelerationPartial (const std::shared_ptr< AccelerationPartial > accelerationPartial) inline
Function to retrieve name of central body of third-body acceleration partial, from AccelerationPartial base class object input
Parameters
accelerationPartial Acceleration partial model from which central body name is to be retrieved (must be of derived class ThirdBodyGravityPartial< T >
Returns
Name of central body of third-body acceleration partial
Definition at line 519 of file thirdBodyGravityPartial.h.
References tudat::basic_astrodynamics::isAccelerationFromThirdBody(), tudat::basic_astrodynamics::third_body_mutual_spherical_harmonic_gravity, tudat::basic_astrodynamics::third_body_point_mass_gravity, and tudat::basic_astrodynamics::third_body_spherical_harmonic_gravity.
getPartialDerivativeOfSecondDegreeGravitationalTorqueWrtQuaternion()
Eigen::Matrix< double, 3, 4 > tudat::acceleration_partials::getPartialDerivativeOfSecondDegreeGravitationalTorqueWrtQuaternion (const double premultiplier, const Eigen::Matrix3d & inertiaTensor, const Eigen::Vector3d & bodyFixedRelativePosition, const Eigen::Vector3d & intertialRelativePosition, const std::vector< Eigen::Matrix3d > derivativeOfRotationMatrixWrtQuaternions)
Function that computes the partial of degree 2 torque w.r.t. the current quaternion elements
Parameters
premultiplier Model premultiplier
inertiaTensor Body inertial tensor
bodyFixedRelativePosition Position of body exerting torque, w.r.t. body undergoing torque, expressed in frame fixed to body undergoing torque
intertialRelativePosition Position of body exerting torque, w.r.t. body undergoing torque, expressed in inertial frame
derivativeOfRotationMatrixWrtQuaternions Current partial derivative of rotation matrix from body-fixed to base frame w.r.t. quaternion
Returns
Partial derivative of degree 2 torque w.r.t. the current quaternion elements
Definition at line 22 of file secondDegreeGravitationalTorquePartial.cpp.
References tudat::linear_algebra::getCrossProductMatrix().
Referenced by tudat::acceleration_partials::SecondDegreeGravitationalTorquePartial::update().
getPartialDerivativeOfSphericalHarmonicGravitationalTorqueWrtQuaternion()
Eigen::Matrix< double, 3, 4 > tudat::acceleration_partials::getPartialDerivativeOfSphericalHarmonicGravitationalTorqueWrtQuaternion (const Eigen::Matrix3d & bodyFixedRelativePositionCrossProductMatrix, const Eigen::Matrix3d & bodyFixedPotentialGradientPositionPartial, const Eigen::Matrix3d & bodyFixedPotentialGradientCrossProductMatrix, const Eigen::Vector3d & inertialRelativePosition, const std::vector< Eigen::Matrix3d > derivativeOfRotationMatrixWrtQuaternions)
Function to compute partial derivative of spherical harmonic torque w.r.t. quaternion elements
Parameters
bodyFixedRelativePositionCrossProductMatrix Cross-product matrix for body-fixed relative position of body undergoing torque (w.r.t. body exerting torque)
bodyFixedPotentialGradientPositionPartial Gradient of spherical harmonic potential, in body-fixed coordinates
bodyFixedPotentialGradientCrossProductMatrix Cross-product matrix of body-fixed potential gradient
inertialRelativePosition Inertial relative position of body undergoing torque (w.r.t. body exerting torque)
derivativeOfRotationMatrixWrtQuaternions Current partial derivative of rotation matrix from body-fixed to base frame w.r.t. quaternion
Returns
Partial derivative of spherical harmonic torque w.r.t. the current quaternion elements
Definition at line 22 of file sphericalHarmonicGravitationalTorquePartial.cpp.
Referenced by tudat::acceleration_partials::SphericalHarmonicGravitationalTorquePartial::update().
Variable Documentation
UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_C20
const Eigen::Matrix3d tudat::acceleration_partials::UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_C20 static
Initial value:
=
        ( Eigen::Matrix3d( ) << 1.0 / 3.0, 0.0, 0.0,
          0.0, 1.0 / 3.0, 0.0,
          0.0, 0.0, -2.0 / 3.0 ).finished( )
Definition at line 26 of file inertiaTensorPartial.h.
Referenced by tudat::acceleration_partials::InertialTorquePartial::wrtCosineSphericalHarmonicCoefficientsOfCentralBody(), tudat::acceleration_partials::ConstantTorquePartial::wrtCosineSphericalHarmonicCoefficientsOfCentralBody(), and tudat::acceleration_partials::SecondDegreeGravitationalTorquePartial::wrtCosineSphericalHarmonicCoefficientsOfCentralBody().
UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_C21
const Eigen::Matrix3d tudat::acceleration_partials::UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_C21 static
Initial value:
=
        ( Eigen::Matrix3d( ) << 0.0, 0.0, -1.0,
          0.0, 0.0, 0.0,
          -1.0, 0.0, 0.0 ).finished( )
Definition at line 32 of file inertiaTensorPartial.h.
Referenced by tudat::acceleration_partials::InertialTorquePartial::wrtCosineSphericalHarmonicCoefficientsOfCentralBody(), tudat::acceleration_partials::ConstantTorquePartial::wrtCosineSphericalHarmonicCoefficientsOfCentralBody(), and tudat::acceleration_partials::SecondDegreeGravitationalTorquePartial::wrtCosineSphericalHarmonicCoefficientsOfCentralBody().
UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_C22
const Eigen::Matrix3d tudat::acceleration_partials::UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_C22 static
Initial value:
=
        ( Eigen::Matrix3d( ) << -2.0, 0.0, 0.0,
          0.0, 2.0, 0.0,
          0.0, 0.0, 0.0 ).finished( )
Definition at line 37 of file inertiaTensorPartial.h.
Referenced by tudat::acceleration_partials::InertialTorquePartial::wrtCosineSphericalHarmonicCoefficientsOfCentralBody(), tudat::acceleration_partials::ConstantTorquePartial::wrtCosineSphericalHarmonicCoefficientsOfCentralBody(), and tudat::acceleration_partials::SecondDegreeGravitationalTorquePartial::wrtCosineSphericalHarmonicCoefficientsOfCentralBody().
UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_S21
const Eigen::Matrix3d tudat::acceleration_partials::UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_S21 static
Initial value:
=
        ( Eigen::Matrix3d( ) << 0.0, 0.0, 0.0,
          0.0, 0.0, -1.0,
          0.0, -1.0, 0.0 ).finished( )
Definition at line 42 of file inertiaTensorPartial.h.
Referenced by tudat::acceleration_partials::InertialTorquePartial::wrtSineSphericalHarmonicCoefficientsOfCentralBody(), tudat::acceleration_partials::ConstantTorquePartial::wrtSineSphericalHarmonicCoefficientsOfCentralBody(), and tudat::acceleration_partials::SecondDegreeGravitationalTorquePartial::wrtSineSphericalHarmonicCoefficientsOfCentralBody().
UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_S22
const Eigen::Matrix3d tudat::acceleration_partials::UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_S22 static
Initial value:
=
        ( Eigen::Matrix3d( ) << 0.0, -2.0, 0.0,
          -2.0, 0.0, 0.0,
          0.0, 0.0, 0.0 ).finished( )
Definition at line 47 of file inertiaTensorPartial.h.
Referenced by tudat::acceleration_partials::InertialTorquePartial::wrtSineSphericalHarmonicCoefficientsOfCentralBody(), tudat::acceleration_partials::ConstantTorquePartial::wrtSineSphericalHarmonicCoefficientsOfCentralBody(), and tudat::acceleration_partials::SecondDegreeGravitationalTorquePartial::wrtSineSphericalHarmonicCoefficientsOfCentralBody().
UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_MEAN_MOMENT
const Eigen::Matrix3d tudat::acceleration_partials::UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_MEAN_MOMENT static
Initial value:
=
        Eigen::Matrix3d::Identity( )
Definition at line 52 of file inertiaTensorPartial.h.
Referenced by tudat::acceleration_partials::InertialTorquePartial::wrtMeanMomentOfInertia(), and tudat::acceleration_partials::ConstantTorquePartial::wrtMeanMomentOfInertia().