Tudat: tudat::electro_magnetism Namespace Reference
tudat::electro_magnetism Namespace Reference
Classes
class CannonBallRadiationPressureAcceleration
Cannon-ball Radiation pressure acceleration model class.
class PanelledRadiationPressureAcceleration
Class for calculating the radiation pressure acceleration on a panelled body.
class PanelledRadiationPressureInterface
Class in which the properties of a panelled radiation pressure acceleration model are stored.
class RadiationPressureInterface
Class in which the properties of a solar radiation pressure acceleration model are stored.
class SolarSailAcceleration
Solar sail acceleration model class.
class SolarSailingRadiationPressureInterface
Class in which the properties of a solar sailing radiation pressure acceleration model are stored.
Typedefs
typedef std::shared_ptr< CannonBallRadiationPressureAcceleration > CannonBallRadiationPressurePointer
Typedef for shared-pointer to CannonBallRadiationPressureAcceleration.
typedef std::shared_ptr< SolarSailAcceleration > SolarSailAccelerationPointer
Typedef for shared-pointer to SolarSailAcceleration.
Functions
double calculateRadiationPressure (const double sourcePower, const double distanceFromSource)
Calculate radiation pressure at certain distance from a source.
double computeBlackbodyRadiationIntensity (const double bodyTemperature)
Function to compute the blackbody radiation intensity at a given body temperature.
Eigen::Vector3d computeCannonBallRadiationPressureAcceleration (const double radiationPressure, const Eigen::Vector3d &vectorToSource, const double area, const double radiationPressureCoefficient, const double mass)
Compute radiation pressure acceleration using a cannon-ball model.
Eigen::Vector3d computeCannonBallRadiationPressureForce (const double radiationPressure, const Eigen::Vector3d &vectorToSource, const double area, const double radiationPressureCoefficient)
Compute radiation pressure force using a cannon-ball model.
Eigen::Vector3d computeLorentzAccelerationDueToStaticMagneticField (const Eigen::Vector3d &velocityOfBodySubjectToAcceleration, const Eigen::Vector3d &localMagneticField, const double chargeOfBodySubjectToAcceleration, const double massOfBodySubjectToAcceleration)
Compute acceleration due to static magnetic field.
Eigen::Vector3d computeLorentzForceDueToStaticMagneticField (const Eigen::Vector3d &velocityOfBodySubjectToAcceleration, const Eigen::Vector3d &localMagneticField, const double chargeOfBodySubjectToAcceleration)
Compute Lorentz Force due to static magnetic field.
Eigen::Vector3d computeSinglePanelNormalizedRadiationPressureForce (const Eigen::Vector3d &normalizedVectorToSource, const Eigen::Vector3d &panelSurfaceNormal, const double panelArea, const double panelEmissivitty, const double panelDiffuseReflectionCoefficient)
Function to calculate radiation pressure force on a single partially reflecting panel.
Eigen::Vector3d computeSolarSailAcceleration (const double frontEmissivityCoefficient, const double backEmissivityCoefficient, const double frontLambertianCoefficient, const double backLambertianCoefficient, const double reflectivityCoefficient, const double specularReflectionCoefficient, const Eigen::Vector3d &normalisedVectorToSource, const Eigen::Vector3d &normalisedVelocityVector, const double radiationPressure, const double area, const double coneAngle, const double clockAngle, const double mass)
Compute solar sail acceleration with a non-ideal reflective model.
Eigen::Vector3d computeSolarSailForce (const double frontEmissivityCoefficient, const double backEmissivityCoefficient, const double frontLambertianCoefficient, const double backLambertianCoefficient, const double reflectivityCoefficient, const double specularReflectionCoefficient, const Eigen::Vector3d &normalisedVectorToSource, const Eigen::Vector3d &normalisedVelocityVector, const double radiationPressure, const double area, const double coneAngle, const double clockAngle)
Compute solar sail force using a non-ideal reflective model.
Typedef Documentation
CannonBallRadiationPressurePointer
typedef std::shared_ptr< CannonBallRadiationPressureAcceleration > tudat::electro_magnetism::CannonBallRadiationPressurePointer
Definition at line 258 of file cannonBallRadiationPressureAcceleration.h.
SolarSailAccelerationPointer
typedef std::shared_ptr< SolarSailAcceleration > tudat::electro_magnetism::SolarSailAccelerationPointer
Definition at line 570 of file solarSailAcceleration.h.
Function Documentation
computeBlackbodyRadiationIntensity()
double tudat::electro_magnetism::computeBlackbodyRadiationIntensity (const double bodyTemperature) inline
Function to compute the blackbody radiation intensity (W/m^2) at a given body temperature.
Parameters
bodyTemperature Temperature of black body emitting radiation.
Returns
Blackbodt radiation intensity at given temperature.
Definition at line 27 of file basicElectroMagnetism.h.
References tudat::physical_constants::STEFAN_BOLTZMANN_CONSTANT.
Referenced by tudat::aerodynamics::EquilibriumTemperatureFunction::evaluate().
computeCannonBallRadiationPressureAcceleration()
Eigen::Vector3d tudat::electro_magnetism::computeCannonBallRadiationPressureAcceleration (const double radiationPressure, const Eigen::Vector3d & vectorToSource, const double area, const double radiationPressureCoefficient, const double mass)
Computes radiation pressure acceleration using a cannon-ball model, i.e. assuming force to be in opposite direction of the vector to the source. This function is essentially a wrapper for the function that computes the force. opposite direction of the vector to the source.
Parameters
radiationPressure Radiation pressure at target. N.B: the usual way of computing the radiation pressure at the target, in case the source is the Sun, is to take the radiation presssure at 1 AU and scale it based on the distance from the Sun [N/m^2]
vectorToSource Vector pointing from target to source. N.B: this must be a unit vector! To compute the unit vector based on a given position vector, you can use the .normalize() or .normalized() member functions of an Eigen::Vector3d object. [-]
area Area on which radiation pressure is assumed to act. [m^2]
radiationPressureCoefficient Coefficient to scale effective force. Equal to 1 + emissivitty, assuming no diffuse reflection. [-]
mass Mass of accelerated body. [kg]
Returns
Acceleration due to radiation pressure. [m/s^2]
See also
computeCannonBallRadiationPressureForce().
Definition at line 23 of file cannonBallRadiationPressureAcceleration.cpp.
References computeCannonBallRadiationPressureForce().
Referenced by tudat::electro_magnetism::CannonBallRadiationPressureAcceleration::getAcceleration().
computeCannonBallRadiationPressureForce()
Eigen::Vector3d tudat::electro_magnetism::computeCannonBallRadiationPressureForce (const double radiationPressure, const Eigen::Vector3d & vectorToSource, const double area, const double radiationPressureCoefficient)
Computes radiation pressure force using a cannon-ball model, i.e., assuming force to be in opposite direction of the vector to the source.
Parameters
radiationPressure Radiation pressure at target. N.B: the usual way of computing the radiation pressure at the target, in case the source is the Sun, is to take the radiation presssure at 1 AU and scale it based on the distance from the Sun [N/m^2]
vectorToSource Vector pointing from target to source. N.B: this must be a unit vector! To compute the unit vector based on a given position vector, you can use the .normalize() or .normalized() member functions of an Eigen::Vector3d object. [-]
area Area on which radiation pressure is assumed to act. [m^2]
radiationPressureCoefficient Coefficient to scale effective force. Equal to 1 + emissivitty, assuming no diffuse reflection. [-]
Returns
Force due to radiation pressure. [N]
Definition at line 20 of file cannonBallRadiationPressureForce.cpp.
Referenced by computeCannonBallRadiationPressureAcceleration().
computeLorentzAccelerationDueToStaticMagneticField()
Eigen::Vector3d tudat::electro_magnetism::computeLorentzAccelerationDueToStaticMagneticField (const Eigen::Vector3d & velocityOfBodySubjectToAcceleration, const Eigen::Vector3d & localMagneticField, const double chargeOfBodySubjectToAcceleration, const double massOfBodySubjectToAcceleration)
Compute Lorentz acceleration due to static magnetic field.
Computes Lorentz acceleration due to static magnetic field on a particle in an inertial reference frame. Assumes the particle is point-like. Note: This function does not take into account any the Coulomb force between the particle and the source.
Parameters
velocityOfBodySubjectToAcceleration Velocity of body which is being accelerated by the Lorentz force. [m/s]
localMagneticField local magnetic field at position of body subject to acceleration [Tm]
chargeOfBodySubjectToAcceleration Charge of body which is being accelerated by Lorentz force. [C]
massOfBodySubjectToAcceleration Mass of body which is being accelerated by Lorentz force [kg]
Returns
Lorentz acceleration due to static magnetic field. [N]
See also
computeLorentzForceDueToStaticMagneticField.
Definition at line 22 of file lorentzStaticMagneticAcceleration.cpp.
References computeLorentzForceDueToStaticMagneticField().
computeLorentzForceDueToStaticMagneticField()
Eigen::Vector3d tudat::electro_magnetism::computeLorentzForceDueToStaticMagneticField (const Eigen::Vector3d & velocityOfBodySubjectToAcceleration, const Eigen::Vector3d & localMagneticField, const double chargeOfBodySubjectToAcceleration)
Compute Lorentz force due to static magnetic field.
Computes Lorentz force due to static magnetic field on a particle in an inertial reference frame. Assumes the particle is point-like.The following equation is used to calculate the force:
where is the force on the particle, is the charge of the accelerating particle, is the velocity of the accelerating particle, and is the local magnetic field. Note: This force does not take into account the Coulomb force between the particle and the source.
Parameters
velocityOfBodySubjectToAcceleration Velocity of body which is being accelerated by the Lorentz force. [m/s]
chargeOfBodySubjectToAcceleration Charge of body which is being accelerated by Lorentz force. [C]
localMagneticField local magnetic field at position of body subject to acceleration [Tm]
Returns
Lorentz force due to static magnetic field [N]
Definition at line 22 of file lorentzStaticMagneticForce.cpp.
Referenced by computeLorentzAccelerationDueToStaticMagneticField().
computeSinglePanelNormalizedRadiationPressureForce()
Eigen::Vector3d tudat::electro_magnetism::computeSinglePanelNormalizedRadiationPressureForce (const Eigen::Vector3d & normalizedVectorToSource, const Eigen::Vector3d & panelSurfaceNormal, const double panelArea, const double panelEmissivitty, const double panelDiffuseReflectionCoefficient)
Function to calculate radiation pressure force on a single partially reflecting panel. Model for calculation is according to Eq. (3.72) of Montenbruck and Gill (2000)
Parameters
normalizedVectorToSource Current normalized vector from accelerated body to source
panelSurfaceNormal Panel surface normal vector, in the same frame as the normalizedVectorToSource vector
panelArea Area of panel that is considered
panelEmissivitty Emissivity of panel that is considered
panelDiffuseReflectionCoefficient Diffuse reflection coefficient of panel that is considered
Returns
The radiation pressure force on a single partially reflecting panel
Definition at line 12 of file panelledRadiationPressure.cpp.
Referenced by tudat::electro_magnetism::PanelledRadiationPressureAcceleration::updateMembers().
calculateRadiationPressure()
double tudat::electro_magnetism::calculateRadiationPressure (const double sourcePower, const double distanceFromSource)
Calculate radiation pressure at certain distance from a source, in N/m^2.
Parameters
sourcePower Total power radiated by the source (isotropically) in W.
distanceFromSource Distance from center of (spherical) source where radiation pressure is to be calculated.
Returns
Radiation pressure at given distance from the source.
Definition at line 25 of file radiationPressureInterface.cpp.
References tudat::mathematical_constants::PI, and tudat::physical_constants::SPEED_OF_LIGHT.
Referenced by tudat::electro_magnetism::RadiationPressureInterface::updateInterfaceBase().
computeSolarSailAcceleration()
Eigen::Vector3d tudat::electro_magnetism::computeSolarSailAcceleration (const double frontEmissivityCoefficient, const double backEmissivityCoefficient, const double frontLambertianCoefficient, const double backLambertianCoefficient, const double reflectivityCoefficient, const double specularReflectionCoefficient, const Eigen::Vector3d & normalisedVectorToSource, const Eigen::Vector3d & normalisedVelocityVector, const double radiationPressure, const double area, const double coneAngle, const double clockAngle, const double mass)
Compute solar sail acceleration with a non-ideal reflective model. The acceleration is computed from the force derived from the solar sailing radiation pressure model, which is itself a function of the source power and geometry, as well as of the solar sailing model.
Parameters
frontEmissivityCoefficient Emissivity coefficient of the front of the sail. [-]
backEmissivityCoefficient Emissivity coefficient of the back of the sail. [-]
frontLambertianCoefficient Lambertian coefficient of the front of the sail. [-]
backLambertianCoefficient Lambertian coefficient of the back of the sail. [-]
reflectivityCoefficient Reflectivity coefficient of the sail. [-]
specularReflectionCoefficient Specular reflection coefficient of the sail. [-]
normalisedVectorToSource Normalised vector pointing from target to source. N.B: this must be a unit vector! To compute the unit vector based on a given position vector, you can use the .normalize() or .normalized() member functions of an Eigen::Vector3d object. [-]
normalisedVelocityVector Normalised velocity vector of the spacecraft w.r.t. central body. [-]
radiationPressure Radiation pressure at target. [N/m^2]
area Area on which radiation pressure is assumed to act. [m^2]
coneAngle Sail cone angle. [rad]
clockAngle Sail clock angle. [rad]
mass Mass of accelerated body. [kg]
Returns
Acceleration due to radiation pressure. [m/s^2]
Definition at line 24 of file solarSailAcceleration.cpp.
References computeSolarSailForce().
Referenced by tudat::electro_magnetism::SolarSailAcceleration::getAcceleration().
computeSolarSailForce()
Eigen::Vector3d tudat::electro_magnetism::computeSolarSailForce (const double frontEmissivityCoefficient, const double backEmissivityCoefficient, const double frontLambertianCoefficient, const double backLambertianCoefficient, const double reflectivityCoefficient, const double specularReflectionCoefficient, const Eigen::Vector3d & normalisedVectorToSource, const Eigen::Vector3d & normalisedVelocityVector, const double radiationPressure, const double area, const double coneAngle, const double clockAngle)
Computes solar sail force using a non-ideal reflective model.
Parameters
frontEmissivityCoefficient Emissivity coefficient of the front of the sail. [-]
backEmissivityCoefficient Emissivity coefficient of the back of the sail. [-]
frontLambertianCoefficient Lambertian coefficient of the front of the sail. [-]
backLambertianCoefficient Lambertian coefficient of the back of the sail. [-]
reflectivityCoefficient Reflectivity coefficient of the sail. [-]
specularReflectionCoefficient Specular reflection coefficient. [-]
normalisedVectorToSource Normalised vector pointing from target to source. N.B: this must be a unit vector! To compute the unit vector based on a given position vector, you can use the .normalize() or .normalized() member functions of an Eigen::Vector3d object. [-]
normalisedVelocityVector Normalised velocity vector of the target w.r.t. central body. [-]
radiationPressure Radiation pressure at target. [N/m^2]
area Area on which radiation pressure is assumed to act. [m^2]
coneAngle Sail cone angle. [rad]
clockAngle Sail clock angle. [rad]
Returns
Solar sail force. [N]
Definition at line 24 of file solarSailForce.cpp.
Referenced by computeSolarSailAcceleration().