Tudat: tudat::low_thrust_trajectories::HybridMethodModel Class Reference
tudat::low_thrust_trajectories::HybridMethodModel Class Reference
#include <hybridMethodModel.h>
Public Member Functions
HybridMethodModel (const Eigen::Vector6d &stateAtDeparture, const Eigen::Vector6d &stateAtArrival, const Eigen::VectorXd &initialCoStates, const Eigen::VectorXd &finalCoStates, const double centralBodyGravitationalParameter, const double maximumThrust, const double specificImpulse, const double timeOfFlight)
Constructor.
~HybridMethodModel ()
Default destructor.
double computeDeltaV ()
Return the deltaV associated with the thrust profile of the trajectory.
std::function< Eigen::VectorXd(const double) > getCostatesFunction_ ()
Return the current MEE co-states.
basic_astrodynamics::AccelerationMap getLowThrustTrajectoryAccelerationMap ()
Retrieve hybrid method acceleration model (including thrust and central gravity acceleration)
double getMassAtTimeOfFlight ()
Returns propagated mass when the time of flight is reached.
double getMaximumThrustValue ()
Returns maximum allowed thrust.
std::shared_ptr< simulation_setup::AccelerationSettings > getMEEcostatesBasedThrustAccelerationSettings ()
Retrieve MEE costates-based thrust acceleration.
std::shared_ptr< simulation_setup::ThrustDirectionGuidanceSettings > getMEEcostatesBasedThrustDirectionSettings ()
std::shared_ptr< simulation_setup::ThrustMagnitudeSettings > getMEEcostatesBasedThrustMagnitudeSettings ()
Eigen::VectorXd getStateAtLegArrival ()
Returns final state at leg arrival.
Eigen::VectorXd getStateAtLegDeparture ()
Returns initial state at leg departure.
double getTimeOfFlight ()
Returns time of flight.
double getTotalDeltaV ()
Return total deltaV required by the trajectory.
Eigen::Vector6d propagateTrajectory ()
Propagate the spacecraft trajectory to time of flight.
Eigen::Vector6d propagateTrajectory (double initialTime, double finalTime, Eigen::Vector6d initialState, double initialMass)
Propagate the spacecraft trajectory to a given time.
std::map< double, Eigen::Vector6d > propagateTrajectory (std::vector< double > epochs, std::map< double, Eigen::Vector6d > &propagatedTrajectory)
Propagate the trajectory to set of epochs.
Private Attributes
double centralBodyGravitationalParameter_
Gravitational parameter of the central body of the 2-body problem.
std::function< Eigen::VectorXd(const double) > costatesFunction_
Function returning the current MEE co-states.
Eigen::Vector6d finalCoStates_
Final co-states vector.
Eigen::Vector6d initialCoStates_
Modified equinoctial elements.
double initialSpacecraftMass_
Initial mass of the spacecraft.
double massAtTimeOfFlight_
Mass of the spacecraft at the end of the propagation.
double maximumThrust_
Maximum allowed thrust.
double specificImpulse_
Specific impulse.
Eigen::Vector6d stateAtArrival_
State vector of the vehicle at the leg arrival.
Eigen::Vector6d stateAtDeparture_
State vector of the vehicle at the leg departure.
double timeOfFlight_
Time of flight for the leg.
double totalDeltaV_
Total deltaV.
Detailed Description
Definition at line 25 of file hybridMethodModel.h.
Constructor & Destructor Documentation
HybridMethodModel()
tudat::low_thrust_trajectories::HybridMethodModel::HybridMethodModel (const Eigen::Vector6d & stateAtDeparture, const Eigen::Vector6d & stateAtArrival, const Eigen::VectorXd & initialCoStates, const Eigen::VectorXd & finalCoStates, const double centralBodyGravitationalParameter, const double maximumThrust, const double specificImpulse, const double timeOfFlight) inline
Definition at line 30 of file hybridMethodModel.h.
References costatesFunction_, finalCoStates_, initialCoStates_, initialSpacecraftMass_, propagateTrajectory(), timeOfFlight_, and totalDeltaV_.
~HybridMethodModel()
tudat::low_thrust_trajectories::HybridMethodModel::~HybridMethodModel () inline
Definition at line 70 of file hybridMethodModel.h.
References computeDeltaV(), getLowThrustTrajectoryAccelerationMap(), getMEEcostatesBasedThrustAccelerationSettings(), getMEEcostatesBasedThrustDirectionSettings(), getMEEcostatesBasedThrustMagnitudeSettings(), and propagateTrajectory().
Member Function Documentation
getMEEcostatesBasedThrustAccelerationSettings()
std::shared_ptr< simulation_setup::AccelerationSettings > tudat::low_thrust_trajectories::HybridMethodModel::getMEEcostatesBasedThrustAccelerationSettings ()
Definition at line 26 of file hybridMethodModel.cpp.
Referenced by ~HybridMethodModel().
getMEEcostatesBasedThrustMagnitudeSettings()
std::shared_ptr< simulation_setup::ThrustMagnitudeSettings > tudat::low_thrust_trajectories::HybridMethodModel::getMEEcostatesBasedThrustMagnitudeSettings ()
Definition at line 53 of file hybridMethodModel.cpp.
Referenced by ~HybridMethodModel().
getMEEcostatesBasedThrustDirectionSettings()
std::shared_ptr< simulation_setup::ThrustDirectionGuidanceSettings > tudat::low_thrust_trajectories::HybridMethodModel::getMEEcostatesBasedThrustDirectionSettings ()
Definition at line 65 of file hybridMethodModel.cpp.
Referenced by ~HybridMethodModel().
getLowThrustTrajectoryAccelerationMap()
basic_astrodynamics::AccelerationMap tudat::low_thrust_trajectories::HybridMethodModel::getLowThrustTrajectoryAccelerationMap ()
Definition at line 73 of file hybridMethodModel.cpp.
References tudat::basic_astrodynamics::central_gravity, and tudat::simulation_setup::createAccelerationModelsMap().
Referenced by ~HybridMethodModel().
propagateTrajectory() [1/3]
Eigen::Vector6d tudat::low_thrust_trajectories::HybridMethodModel::propagateTrajectory ()
Propagate the spacecraft trajectory to time-of-flight.
Definition at line 93 of file hybridMethodModel.cpp.
Referenced by tudat::low_thrust_trajectories::HybridMethodProblem::fitness(), HybridMethodModel(), and ~HybridMethodModel().
propagateTrajectory() [2/3]
Eigen::Vector6d tudat::low_thrust_trajectories::HybridMethodModel::propagateTrajectory (double initialTime, double finalTime, Eigen::Vector6d initialState, double initialMass)
Definition at line 102 of file hybridMethodModel.cpp.
References tudat::basic_astrodynamics::central_gravity, tudat::simulation_setup::createAccelerationModelsMap(), tudat::simulation_setup::createMassRateModel(), tudat::propagators::gauss_modified_equinoctial, and tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getEquationsOfMotionNumericalSolution().
propagateTrajectory() [3/3]
std::map< double, Eigen::Vector6d > tudat::low_thrust_trajectories::HybridMethodModel::propagateTrajectory (std::vector< double > epochs, std::map< double, Eigen::Vector6d > & propagatedTrajectory)
Definition at line 175 of file hybridMethodModel.cpp.
computeDeltaV()
double tudat::low_thrust_trajectories::HybridMethodModel::computeDeltaV ()
Definition at line 229 of file hybridMethodModel.cpp.
References tudat::numerical_quadrature::createQuadrature(), and tudat::physical_constants::SEA_LEVEL_GRAVITATIONAL_ACCELERATION.
Referenced by getTotalDeltaV(), and ~HybridMethodModel().
getStateAtLegDeparture()
Eigen::VectorXd tudat::low_thrust_trajectories::HybridMethodModel::getStateAtLegDeparture () inline
Definition at line 95 of file hybridMethodModel.h.
References stateAtDeparture_.
getStateAtLegArrival()
Eigen::VectorXd tudat::low_thrust_trajectories::HybridMethodModel::getStateAtLegArrival () inline
Definition at line 101 of file hybridMethodModel.h.
References stateAtArrival_.
getMassAtTimeOfFlight()
double tudat::low_thrust_trajectories::HybridMethodModel::getMassAtTimeOfFlight () inline
Definition at line 107 of file hybridMethodModel.h.
References massAtTimeOfFlight_.
getMaximumThrustValue()
double tudat::low_thrust_trajectories::HybridMethodModel::getMaximumThrustValue () inline
Definition at line 113 of file hybridMethodModel.h.
References maximumThrust_.
getTimeOfFlight()
double tudat::low_thrust_trajectories::HybridMethodModel::getTimeOfFlight () inline
Definition at line 119 of file hybridMethodModel.h.
References timeOfFlight_.
getTotalDeltaV()
double tudat::low_thrust_trajectories::HybridMethodModel::getTotalDeltaV () inline
Definition at line 125 of file hybridMethodModel.h.
References computeDeltaV().
Referenced by tudat::low_thrust_trajectories::HybridMethodProblem::fitness().
getCostatesFunction_()
std::function< Eigen::VectorXd(const double) > tudat::low_thrust_trajectories::HybridMethodModel::getCostatesFunction_ () inline
Definition at line 131 of file hybridMethodModel.h.
References costatesFunction_.
Member Data Documentation
stateAtDeparture_
Eigen::Vector6d tudat::low_thrust_trajectories::HybridMethodModel::stateAtDeparture_ private
Definition at line 141 of file hybridMethodModel.h.
Referenced by getStateAtLegDeparture().
stateAtArrival_
Eigen::Vector6d tudat::low_thrust_trajectories::HybridMethodModel::stateAtArrival_ private
Definition at line 144 of file hybridMethodModel.h.
Referenced by getStateAtLegArrival().
initialCoStates_
Eigen::Vector6d tudat::low_thrust_trajectories::HybridMethodModel::initialCoStates_ private
Initial co-states vector.
Definition at line 149 of file hybridMethodModel.h.
Referenced by HybridMethodModel().
finalCoStates_
Eigen::Vector6d tudat::low_thrust_trajectories::HybridMethodModel::finalCoStates_ private
Definition at line 152 of file hybridMethodModel.h.
Referenced by HybridMethodModel().
costatesFunction_
std::function< Eigen::VectorXd(const double) > tudat::low_thrust_trajectories::HybridMethodModel::costatesFunction_ private
Definition at line 155 of file hybridMethodModel.h.
Referenced by getCostatesFunction_(), and HybridMethodModel().
maximumThrust_
double tudat::low_thrust_trajectories::HybridMethodModel::maximumThrust_ private
Definition at line 158 of file hybridMethodModel.h.
Referenced by getMaximumThrustValue().
specificImpulse_
double tudat::low_thrust_trajectories::HybridMethodModel::specificImpulse_ private
Definition at line 161 of file hybridMethodModel.h.
timeOfFlight_
double tudat::low_thrust_trajectories::HybridMethodModel::timeOfFlight_ private
Definition at line 164 of file hybridMethodModel.h.
Referenced by getTimeOfFlight(), and HybridMethodModel().
centralBodyGravitationalParameter_
double tudat::low_thrust_trajectories::HybridMethodModel::centralBodyGravitationalParameter_ private
Definition at line 167 of file hybridMethodModel.h.
totalDeltaV_
double tudat::low_thrust_trajectories::HybridMethodModel::totalDeltaV_ private
Definition at line 170 of file hybridMethodModel.h.
Referenced by HybridMethodModel().
initialSpacecraftMass_
double tudat::low_thrust_trajectories::HybridMethodModel::initialSpacecraftMass_ private
Definition at line 173 of file hybridMethodModel.h.
Referenced by HybridMethodModel().
massAtTimeOfFlight_
double tudat::low_thrust_trajectories::HybridMethodModel::massAtTimeOfFlight_ private
Definition at line 176 of file hybridMethodModel.h.
Referenced by getMassAtTimeOfFlight().
The documentation for this class was generated from the following files:
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/hybridMethodModel.h
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/hybridMethodModel.cpp