Tudat: tudat::gravitation::SecondDegreeGravitationalTorqueModel Class Reference
tudat::gravitation::SecondDegreeGravitationalTorqueModel Class Reference
Class to compute the second degree gravitational torque.
#include <secondDegreeGravitationalTorque.h>
Public Member Functions
SecondDegreeGravitationalTorqueModel (const std::function< Eigen::Vector3d() > positionOfBodySubjectToTorqueFunction, const std::function< double() > gravitationalParameterOfAttractingBodyFunction, const std::function< Eigen::Matrix3d() > inertiaTensorOfRotatingBodyFunction, const std::function< Eigen::Vector3d() > positionOfBodyExertingTorqueFunction=[](){ return Eigen::Vector3d::Zero();}, const std::function< Eigen::Quaterniond() > rotationToBodyFixedFrameFunction=[](){ return Eigen::Quaterniond(Eigen::Matrix3d::Identity());})
Constructor.
double getCurrentGravitationalParameterOfAttractingBody ()
Function to retrieve current gravitational parameter of the body that is exerting the torque,.
Eigen::Matrix3d & getCurrentInertiaTensorOfRotatingBody ()
Function to retrieve current inertia tensor of the body that is subject to the torque, in the frame fixed to that body.
Eigen::Vector3d & getCurrentInertiaTensorTimesRelativePositionOfBody ()
Function to retrieve The current inertia tensor of the body undergoing the torque, premultiplied by state.
Eigen::Vector3d & getCurrentRelativeBodyFixedPositionOfBodySubjectToTorque ()
Function to retrieve current position of body exerting torque, w.r.t. body undergoing torque in frame fixed to body.
Eigen::Vector3d & getCurrentRelativePositionOfBodySubjectToTorque ()
Function to retrieve current position of body exerting torque, w.r.t. body undergoing torque in inertial frame.
Eigen::Quaterniond & getCurrentRotationToBodyFixedFrame ()
Function to retrieve current rotation from inertial to body-fixed frame.
double getCurrentTorqueMagnitudePremultiplier ()
Function to retrieve current torque pre-multipler.
Eigen::Vector3d getTorque ()
Get gravitational torque.
void updateMembers (const double currentTime)
Update member variables used by the gravitational torque model.
Public Member Functions inherited from tudat::basic_astrodynamics::TorqueModel
TorqueModel ()
Constructor.
virtual ~TorqueModel ()
Destructor.
virtual void resetTime (const double currentTime=TUDAT_NAN)
Function to reset the current time.
Private Attributes
double currentGravitationalParameterOfAttractingBody_
Current gravitational parameter of the body that is exerting the torque, as set by updateMembers function.
Eigen::Matrix3d currentInertiaTensorOfRotatingBody_
Eigen::Vector3d currentInertiaTensorTimesRelativePositionOfBody_
Eigen::Vector3d currentRelativeBodyFixedPositionOfBodySubjectToTorque_
Eigen::Vector3d currentRelativePositionOfBodySubjectToTorque_
Eigen::Quaterniond currentRotationToBodyFixedFrame_
Current rotation from inertial to body-fixed frame.
Eigen::Quaterniond currentRotationToBodyFixedFrameFunction_
Rotation from inertial frame to frame fixed to body undergoing torque, as set by updateMembers function.
Eigen::Vector3d currentTorque_
Current gravitational torque, as set by updateMembers function.
double currentTorqueMagnitudePremultiplier_
Current torque pre-multipler (3*mu/r^5).
std::function< double() > gravitationalParameterOfAttractingBodyFunction_
Function returning the gravitational parameter of the body that is exerting the torque.
std::function< Eigen::Matrix3d() > inertiaTensorOfRotatingBodyFunction_
Function returning the inertia tensor of the body that is subject to the torque, in the frame fixed to that body.
std::function< Eigen::Vector3d() > positionOfBodyExertingTorqueFunction_
Function returning the position of the body that is exerting to the torque, in inertial frame.
std::function< Eigen::Vector3d() > positionOfBodySubjectToTorqueFunction_
Function returning the position of the body that is subject to the torque, in inertial frame.
std::function< Eigen::Quaterniond() > rotationToBodyFixedFrameFunction_
Function returning the rotation from inertial frame to frame fixed to body undergoing torque.
Additional Inherited Members
Protected Attributes inherited from tudat::basic_astrodynamics::TorqueModel
double currentTime_
Last time at which the updateMembers was evaluated (or NaN if next call is to recompute torque).
Detailed Description
Class to compute the second degree gravitational torque: the gravitational torque exerted by a point mass on a body with degree two gravity field (parameterized by inertia tensor).
Definition at line 65 of file secondDegreeGravitationalTorque.h.
Constructor & Destructor Documentation
SecondDegreeGravitationalTorqueModel()
tudat::gravitation::SecondDegreeGravitationalTorqueModel::SecondDegreeGravitationalTorqueModel (const std::function< Eigen::Vector3d() > positionOfBodySubjectToTorqueFunction, const std::function< double() > gravitationalParameterOfAttractingBodyFunction, const std::function< Eigen::Matrix3d() > inertiaTensorOfRotatingBodyFunction, const std::function< Eigen::Vector3d() > positionOfBodyExertingTorqueFunction = [ ](){ return Eigen::Vector3d::Zero(); }, const std::function< Eigen::Quaterniond() > rotationToBodyFixedFrameFunction = [ ](){ return Eigen::Quaterniond(Eigen::Matrix3d::Identity()); }) inline
Constructor
Parameters
positionOfBodySubjectToTorqueFunction Function returning the position of the body that is subject to the torque, in inertial frame.
gravitationalParameterOfAttractingBodyFunction Function returning the gravitational parameter of the body that is exerting the torque.
inertiaTensorOfRotatingBodyFunction Function returning the inertia tensor of the body that is subject to the torque, in the frame fixed to that body.
positionOfBodyExertingTorqueFunction Function returning the position of the body that is exerting to the torque, in inertial frame.
rotationToBodyFixedFrameFunction Function returning the rotation from inertial frame to frame fixed to body undergoing torque.
Definition at line 83 of file secondDegreeGravitationalTorque.h.
References gravitationalParameterOfAttractingBodyFunction_, inertiaTensorOfRotatingBodyFunction_, positionOfBodyExertingTorqueFunction_, positionOfBodySubjectToTorqueFunction_, and rotationToBodyFixedFrameFunction_.
Member Function Documentation
getTorque()
Eigen::Vector3d tudat::gravitation::SecondDegreeGravitationalTorqueModel::getTorque () inline virtual
Returns the gravitational torque. All data required for the computation is taken from member variables, which are set to their latest values by the last call of the updateMembers function.
Returns
Gravitational torque.
See also
updateMembers().
Implements tudat::basic_astrodynamics::TorqueModel.
Definition at line 105 of file secondDegreeGravitationalTorque.h.
References currentTorque_.
updateMembers()
void tudat::gravitation::SecondDegreeGravitationalTorqueModel::updateMembers (const double currentTime) inline virtual
Updates member variables used by the gravitational accfeleration model. Function pointers to retrieve the current values of quantities from which the torque is to be calculated are set by constructor. This function calls them to update the associated variables to their current state.
Parameters
currentTime Time at which torque model is to be updated.
Implements tudat::basic_astrodynamics::TorqueModel.
Definition at line 118 of file secondDegreeGravitationalTorque.h.
References tudat::gravitation::calculateSecondDegreeGravitationalTorque(), currentGravitationalParameterOfAttractingBody_, currentInertiaTensorOfRotatingBody_, currentInertiaTensorTimesRelativePositionOfBody_, currentRelativeBodyFixedPositionOfBodySubjectToTorque_, currentRelativePositionOfBodySubjectToTorque_, currentRotationToBodyFixedFrame_, currentRotationToBodyFixedFrameFunction_, currentTorque_, currentTorqueMagnitudePremultiplier_, gravitationalParameterOfAttractingBodyFunction_, inertiaTensorOfRotatingBodyFunction_, positionOfBodyExertingTorqueFunction_, positionOfBodySubjectToTorqueFunction_, and rotationToBodyFixedFrameFunction_.
getCurrentRotationToBodyFixedFrame()
Eigen::Quaterniond& tudat::gravitation::SecondDegreeGravitationalTorqueModel::getCurrentRotationToBodyFixedFrame () inline
Function to retrieve current rotation from inertial to body-fixed frame
Returns
Current rotation from inertial to body-fixed frame
Definition at line 147 of file secondDegreeGravitationalTorque.h.
References currentRotationToBodyFixedFrame_.
getCurrentRelativePositionOfBodySubjectToTorque()
Eigen::Vector3d& tudat::gravitation::SecondDegreeGravitationalTorqueModel::getCurrentRelativePositionOfBodySubjectToTorque () inline
Function to retrieve current position of body exerting torque, w.r.t. body undergoing torque in inertial frame
Returns
Current position of body exerting torque, w.r.t. body undergoing torque in inertial frame
Definition at line 157 of file secondDegreeGravitationalTorque.h.
References currentRelativePositionOfBodySubjectToTorque_.
getCurrentRelativeBodyFixedPositionOfBodySubjectToTorque()
Eigen::Vector3d& tudat::gravitation::SecondDegreeGravitationalTorqueModel::getCurrentRelativeBodyFixedPositionOfBodySubjectToTorque () inline
Function to retrieve current position of body exerting torque, w.r.t. body undergoing torque in frame fixed to body undergoing torque,
Returns
Current position of body exerting torque, w.r.t. body undergoing torque in frame fixed to body undergoing torque,
Definition at line 168 of file secondDegreeGravitationalTorque.h.
References currentRelativeBodyFixedPositionOfBodySubjectToTorque_.
getCurrentInertiaTensorOfRotatingBody()
Eigen::Matrix3d& tudat::gravitation::SecondDegreeGravitationalTorqueModel::getCurrentInertiaTensorOfRotatingBody () inline
Function to retrieve current inertia tensor of the body that is subject to the torque, in the frame fixed to that body
Returns
Current inertia tensor of the body that is subject to the torque, in the frame fixed to that body
Definition at line 178 of file secondDegreeGravitationalTorque.h.
References currentInertiaTensorOfRotatingBody_.
getCurrentTorqueMagnitudePremultiplier()
double tudat::gravitation::SecondDegreeGravitationalTorqueModel::getCurrentTorqueMagnitudePremultiplier () inline
Function to retrieve current torque pre-multipler
Returns
Current torque pre-multipler
Definition at line 188 of file secondDegreeGravitationalTorque.h.
References currentTorqueMagnitudePremultiplier_.
getCurrentGravitationalParameterOfAttractingBody()
double tudat::gravitation::SecondDegreeGravitationalTorqueModel::getCurrentGravitationalParameterOfAttractingBody () inline
Function to retrieve current gravitational parameter of the body that is exerting the torque,
Returns
Current gravitational parameter of the body that is exerting the torque,
Definition at line 198 of file secondDegreeGravitationalTorque.h.
References currentGravitationalParameterOfAttractingBody_.
getCurrentInertiaTensorTimesRelativePositionOfBody()
Eigen::Vector3d& tudat::gravitation::SecondDegreeGravitationalTorqueModel::getCurrentInertiaTensorTimesRelativePositionOfBody () inline
Function to retrieve The current inertia tensor of the body undergoing the torque, multiplied by relative currentRelativeBodyFixedPositionOfBodySubjectToTorque_
Returns
The current inertia tensor of the body undergoing the torque, multiplied by relative currentRelativeBodyFixedPositionOfBodySubjectToTorque_
Definition at line 210 of file secondDegreeGravitationalTorque.h.
References currentInertiaTensorTimesRelativePositionOfBody_.
Member Data Documentation
positionOfBodySubjectToTorqueFunction_
std::function< Eigen::Vector3d() > tudat::gravitation::SecondDegreeGravitationalTorqueModel::positionOfBodySubjectToTorqueFunction_ private
Definition at line 220 of file secondDegreeGravitationalTorque.h.
Referenced by SecondDegreeGravitationalTorqueModel(), and updateMembers().
gravitationalParameterOfAttractingBodyFunction_
std::function< double() > tudat::gravitation::SecondDegreeGravitationalTorqueModel::gravitationalParameterOfAttractingBodyFunction_ private
Definition at line 223 of file secondDegreeGravitationalTorque.h.
Referenced by SecondDegreeGravitationalTorqueModel(), and updateMembers().
inertiaTensorOfRotatingBodyFunction_
std::function< Eigen::Matrix3d() > tudat::gravitation::SecondDegreeGravitationalTorqueModel::inertiaTensorOfRotatingBodyFunction_ private
Definition at line 226 of file secondDegreeGravitationalTorque.h.
Referenced by SecondDegreeGravitationalTorqueModel(), and updateMembers().
positionOfBodyExertingTorqueFunction_
std::function< Eigen::Vector3d() > tudat::gravitation::SecondDegreeGravitationalTorqueModel::positionOfBodyExertingTorqueFunction_ private
Definition at line 229 of file secondDegreeGravitationalTorque.h.
Referenced by SecondDegreeGravitationalTorqueModel(), and updateMembers().
rotationToBodyFixedFrameFunction_
std::function< Eigen::Quaterniond() > tudat::gravitation::SecondDegreeGravitationalTorqueModel::rotationToBodyFixedFrameFunction_ private
Definition at line 232 of file secondDegreeGravitationalTorque.h.
Referenced by SecondDegreeGravitationalTorqueModel(), and updateMembers().
currentRotationToBodyFixedFrame_
Eigen::Quaterniond tudat::gravitation::SecondDegreeGravitationalTorqueModel::currentRotationToBodyFixedFrame_ private
Definition at line 235 of file secondDegreeGravitationalTorque.h.
Referenced by getCurrentRotationToBodyFixedFrame(), and updateMembers().
currentRelativePositionOfBodySubjectToTorque_
Eigen::Vector3d tudat::gravitation::SecondDegreeGravitationalTorqueModel::currentRelativePositionOfBodySubjectToTorque_ private
Current position of body exerting torque, w.r.t. body undergoing torque in inertial frame, as set by updateMembers function.
Definition at line 239 of file secondDegreeGravitationalTorque.h.
Referenced by getCurrentRelativePositionOfBodySubjectToTorque(), and updateMembers().
currentRelativeBodyFixedPositionOfBodySubjectToTorque_
Eigen::Vector3d tudat::gravitation::SecondDegreeGravitationalTorqueModel::currentRelativeBodyFixedPositionOfBodySubjectToTorque_ private
Current position of body exerting torque, w.r.t. body undergoing torque in frame fixed to body undergoing torque, as set by updateMembers function.
Definition at line 243 of file secondDegreeGravitationalTorque.h.
Referenced by getCurrentRelativeBodyFixedPositionOfBodySubjectToTorque(), and updateMembers().
currentGravitationalParameterOfAttractingBody_
double tudat::gravitation::SecondDegreeGravitationalTorqueModel::currentGravitationalParameterOfAttractingBody_ private
Definition at line 246 of file secondDegreeGravitationalTorque.h.
Referenced by getCurrentGravitationalParameterOfAttractingBody(), and updateMembers().
currentInertiaTensorOfRotatingBody_
Eigen::Matrix3d tudat::gravitation::SecondDegreeGravitationalTorqueModel::currentInertiaTensorOfRotatingBody_ private
Current inertia tensor of the body that is subject to the torque, in the frame fixed to that body, as set by updateMembers function.
Definition at line 250 of file secondDegreeGravitationalTorque.h.
Referenced by getCurrentInertiaTensorOfRotatingBody(), and updateMembers().
currentRotationToBodyFixedFrameFunction_
Eigen::Quaterniond tudat::gravitation::SecondDegreeGravitationalTorqueModel::currentRotationToBodyFixedFrameFunction_ private
Definition at line 253 of file secondDegreeGravitationalTorque.h.
Referenced by updateMembers().
currentInertiaTensorTimesRelativePositionOfBody_
Eigen::Vector3d tudat::gravitation::SecondDegreeGravitationalTorqueModel::currentInertiaTensorTimesRelativePositionOfBody_ private
The current inertia tensor of the body undergoing the torque, multiplied by relative currentRelativeBodyFixedPositionOfBodySubjectToTorque_
Definition at line 257 of file secondDegreeGravitationalTorque.h.
Referenced by getCurrentInertiaTensorTimesRelativePositionOfBody(), and updateMembers().
currentTorqueMagnitudePremultiplier_
double tudat::gravitation::SecondDegreeGravitationalTorqueModel::currentTorqueMagnitudePremultiplier_ private
Definition at line 260 of file secondDegreeGravitationalTorque.h.
Referenced by getCurrentTorqueMagnitudePremultiplier(), and updateMembers().
currentTorque_
Eigen::Vector3d tudat::gravitation::SecondDegreeGravitationalTorqueModel::currentTorque_ private
Definition at line 263 of file secondDegreeGravitationalTorque.h.
Referenced by getTorque(), and updateMembers().
The documentation for this class was generated from the following file:
Astrodynamics/Gravitation/secondDegreeGravitationalTorque.h