Tudat: tudat::acceleration_partials::SphericalHarmonicGravitationalTorquePartial Class Reference
tudat::acceleration_partials::SphericalHarmonicGravitationalTorquePartial Class Reference
Class to calculate the partials of the central gravitational torque w.r.t. parameters and states.
#include <sphericalHarmonicGravitationalTorquePartial.h>
Public Member Functions
SphericalHarmonicGravitationalTorquePartial (const std::shared_ptr< gravitation::SphericalHarmonicGravitationalTorqueModel > torqueModel, const std::shared_ptr< acceleration_partials::SphericalHarmonicsGravityPartial > accelerationPartial, const std::string acceleratedBody, const std::string acceleratingBody)
~SphericalHarmonicGravitationalTorquePartial ()
std::pair< std::function< void(Eigen::MatrixXd &) >, int > getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function for setting up and retrieving a function returning a partial w.r.t. a double parameter.
std::pair< std::function< void(Eigen::MatrixXd &) >, int > getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function for setting up and retrieving a function returning a partial w.r.t. a vector parameter.
bool isStateDerivativeDependentOnIntegratedAdditionalStateTypes (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function for determining if the torque is dependent on a non-rotational integrated state.
void update (const double currentTime=TUDAT_NAN)
Update partial model to current time.
void wrtNonRotationalStateOfAdditionalBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function for calculating the partial of the torque w.r.t. a non-rotational integrated state.
virtual void wrtOrientationOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the torque w.r.t. the orientation of the accelerated body.
Public Member Functions inherited from tudat::acceleration_partials::TorquePartial
TorquePartial (const std::string &bodyUndergoingTorque, const std::string &bodyExertingTorque, const basic_astrodynamics::AvailableTorque torqueType)
Base class constructor.
virtual ~TorquePartial ()
Virtual destructor.
std::string getBodyExertingTorque ()
Function to retrieve the name of the body exerting torque.
std::string getBodyUndergoingTorque ()
Function to retrieve the name of the body undergoing torque.
std::pair< std::function< void(Eigen::Block< Eigen::MatrixXd >) >, int > getDerivativeFunctionWrtStateOfIntegratedBody (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function to retrieve the function that returns the partial derivative w.r.t. a propagated state.
basic_astrodynamics::AvailableTorque getTorqueType ()
Function to retrieve the type of torque w.r.t. which partial is taken..
virtual bool isStateDerivativeDependentOnIntegratedAdditionalStateTypes (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function for determining if the torque is dependent on a non-rotational integrated state.
virtual bool isTorquePartialWrtAdditionalBodyNonNull (const std::string &bodyName)
Function to check whether the partial derivative w.r.t. the rotational state of a third body is non-zero.
virtual void wrtNonRotationalStateOfAdditionalBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function for calculating the partial of the torque w.r.t. a non-rotational integrated state.
virtual void wrtOrientationOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Pure virtual function for calculating the partial of the torque w.r.t. the orientation of the body exerting torque.
virtual void wrtOrientationOfAdditionalBody (const std::string &bodyName, Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the torque w.r.t. the orientation of the third body.
void wrtRotationalStateOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function for calculating the partial of the torque w.r.t. the rotational state of the body undergoing torque.
void wrtRotationalStateOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function for calculating the partial of the torque w.r.t. the Cartesian state of the body exerting torque.
void wrtRotationalStateOfAdditionalBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const std::string &bodyName)
Function for calculating the partial of the torque w.r.t. the Cartesian state of the third body.
virtual void wrtRotationalVelocityOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=3)
Function for calculating the partial of the torque w.r.t. the angular velocity of the accelerated body.
virtual void wrtRotationalVelocityOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=3)
Function for calculating the partial of the torque w.r.t. the angular velocity of the body exerting torque.
virtual void wrtRotationalVelocityOfAdditionalBody (const std::string &bodyName, Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=3)
Function for calculating the partial of the torque w.r.t. the angular velocity of the third body.
Public Member Functions inherited from tudat::orbit_determination::StateDerivativePartial
StateDerivativePartial (const propagators::IntegratedStateType integratedStateType, const std::pair< std::string, std::string > &integrationReferencePoint)
Constructor.
virtual ~StateDerivativePartial ()
Destructor.
void getCurrentDoubleParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, Eigen::MatrixXd &parameterPartial)
Function to retrieve a partial w.r.t. a double parameter.
void getCurrentParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function to retrieve a partial w.r.t. a double parameter.
void getCurrentParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function to retrieve a partial w.r.t. a vector parameter.
void getCurrentVectorParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, Eigen::MatrixXd &parameterPartial)
Function to retrieve a partial w.r.t. a vector parameter.
propagators::IntegratedStateType getIntegratedStateType ()
Function to get the type of state for which partials are to be computed.
std::pair< std::string, std::string > getIntegrationReferencePoint ()
Function to get the identifier for body/reference point for which propagation is performed.
void resetTime (const double currentTime=TUDAT_NAN)
Function to reset the object to the current time.
virtual int setParameterPartialUpdateFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function to set a dependency of this partial object w.r.t. a given double parameter.
virtual int setParameterPartialUpdateFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function to set a dependency of this partial object w.r.t. a given vector parameter.
void updateParameterPartials ()
Function to update the values partial derivatives to current state and time.
Eigen::MatrixXd wrtParameter (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function to directly compute the partial of the state derivative w.r.t. a double parameter.
Eigen::MatrixXd wrtParameter (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function to directly compute the partial of the state derivative w.r.t. a vector parameter.
Protected Member Functions
void getParameterPartialFromAccelerationPartialFunction (Eigen::MatrixXd &partialMatrix, const std::pair< std::function< void(Eigen::MatrixXd &) >, int > &accelerationPartialFunction)
Function to compute torque partial from constituent spherical harmonic acceleration partial.
Protected Member Functions inherited from tudat::orbit_determination::StateDerivativePartial
void resetCurrentParameterValues ()
Function to define all current parameter partials as 'not computed'.
virtual void resetTimeOfMemberObjects ()
Function to reset the member object to the current time.
virtual void updateParameterPartialsOfMemberObjects ()
Function to compute parameter partials of member objects.
Protected Attributes
const std::shared_ptr< acceleration_partials::SphericalHarmonicsGravityPartial > accelerationPartial_
Partial for associated spherical harmonic acceleration.
Eigen::Vector3d currentBodyFixedPotentialGradient_
Current gradient of spherical harmonic potential, in body-fixed coordinates.
Eigen::Matrix3d currentBodyFixedPotentialGradientCrossProductMatrix_
Cross-product matrix of body-fixed potential gradient.
Eigen::Vector3d currentBodyFixedRelativePosition_
Current body-fixed relative position of body undergoing torque (w.r.t. body exerting torque)
Eigen::Matrix3d currentBodyFixedRelativePositionCrossProductMatrix_
Cross-product matrix for body-fixed relative position of body undergoing torque (w.r.t. body exerting torque)
Eigen::Matrix3d currentParameterPartialPreMultiplier_
Current matrix by which to pre-multiply acceleration partial to obtain torque partial.
Eigen::Matrix< double, 3, 4 > currentPartialDerivativeWrtQuaternion_
Current partial derivative of torque w.r.t. quaternion.
Eigen::Vector4d currentQuaternionVector_
Current quaternion elements.
std::vector< Eigen::Matrix3d > currentRotationMatrixDerivativesWrtQuaternion_
Current partial derivative of rotation matrix from body-fixed to base frame w.r.t. quaternion.
Eigen::Matrix3d currentRotationToBodyFixedFrame_
Current rotation matrix from inertial to body-fixed frame.
std::shared_ptr< gravitation::SphericalHarmonicGravitationalTorqueModel > torqueModel_
Torque model for which to compute partials.
Protected Attributes inherited from tudat::acceleration_partials::TorquePartial
std::string bodyExertingTorque_
Name of the body exerting torque.
std::string bodyUndergoingTorque_
Name of the body undergoing torque.
basic_astrodynamics::AvailableTorque torqueType_
Type of torque w.r.t. which partial is taken..
Protected Attributes inherited from tudat::orbit_determination::StateDerivativePartial
int accelerationSize_
Size of the single order state derivative model (i.e. 3 for translational dynamics).
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, Eigen::MatrixXd > currentDoubleParameterPartials_
List of current values of partials w.r.t. double parameter values (emptied at beginning of every time step).
double currentTime_
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, Eigen::MatrixXd > currentVectorParameterPartials_
List of current values of partials w.r.t. double parameter values (emptied at beginning of every time step).
propagators::IntegratedStateType integratedStateType_
Type of state for which partials are to be computed.
std::pair< std::string, std::string > integrationReferencePoint_
Identifier for body/reference point for which propagation is performed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, bool > isCurrentDoubleParameterPartialSet_
List of booleans defining whether the partial w.r.t. the current double parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, bool >::iterator isCurrentDoubleParameterPartialSetIterator_
Iterator for list defining whether the partial w.r.t. the current double parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, bool > isCurrentVectorParameterPartialSet_
List of booleans defining whether the partial w.r.t. the current vector parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, bool >::iterator isCurrentVectorParameterPartialSetIterator_
Iterator for list defining whether the partial w.r.t. the current vector parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::function< void(Eigen::MatrixXd &) > >::iterator parameterDoublePartialFunctionIterator_
Iterator over list of functions to compute values of partials w.r.t. double parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::function< void(Eigen::MatrixXd &) > > parameterDoublePartialFunctions_
List of functions to compute (return by reference) values of partials w.r.t. doule parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::function< void(Eigen::MatrixXd &) > >::iterator parameterVectorPartialFunctionIterator_
Iterator over list of functions to compute values of partials w.r.t. vector parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::function< void(Eigen::MatrixXd &) > > parameterVectorPartialFunctions_
List of functions to compute (return by reference) values of partials w.r.t. vector parameter partials.
Detailed Description
Definition at line 46 of file sphericalHarmonicGravitationalTorquePartial.h.
Constructor & Destructor Documentation
SphericalHarmonicGravitationalTorquePartial()
tudat::acceleration_partials::SphericalHarmonicGravitationalTorquePartial::SphericalHarmonicGravitationalTorquePartial (const std::shared_ptr< gravitation::SphericalHarmonicGravitationalTorqueModel > torqueModel, const std::shared_ptr< acceleration_partials::SphericalHarmonicsGravityPartial > accelerationPartial, const std::string acceleratedBody, const std::string acceleratingBody) inline
Definition at line 50 of file sphericalHarmonicGravitationalTorquePartial.h.
References currentRotationMatrixDerivativesWrtQuaternion_.
~SphericalHarmonicGravitationalTorquePartial()
tudat::acceleration_partials::SphericalHarmonicGravitationalTorquePartial::~SphericalHarmonicGravitationalTorquePartial () inline
Definition at line 61 of file sphericalHarmonicGravitationalTorquePartial.h.
References getParameterPartialFunction().
Member Function Documentation
getParameterPartialFunction() [1/2]
std::pair< std::function< void(Eigen::MatrixXd &) >, int > tudat::acceleration_partials::SphericalHarmonicGravitationalTorquePartial::getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter) virtual
Function for setting up and retrieving a function returning a partial w.r.t. a double parameter. Function returns empty function and zero size indicator for parameters with no dependency for current torque.
Parameters
parameter Parameter w.r.t. which partial is to be taken.
Returns
Pair of parameter partial function and number of columns in partial (0 for no dependency, 1 otherwise).
Reimplemented from tudat::orbit_determination::StateDerivativePartial.
Definition at line 41 of file sphericalHarmonicGravitationalTorquePartial.cpp.
References accelerationPartial_, getParameterPartialFromAccelerationPartialFunction(), and tudat::estimatable_parameters::isParameterRotationMatrixProperty().
Referenced by ~SphericalHarmonicGravitationalTorquePartial().
getParameterPartialFunction() [2/2]
std::pair< std::function< void(Eigen::MatrixXd &) >, int > tudat::acceleration_partials::SphericalHarmonicGravitationalTorquePartial::getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter) virtual
Function for setting up and retrieving a function returning a partial w.r.t. a vector parameter. Function returns empty function and zero size indicator for parameters with no dependency for current torque.
Parameters
parameter Parameter w.r.t. which partial is to be taken.
Returns
Pair of parameter partial function and number of columns in partial (0 for no dependency).
Reimplemented from tudat::orbit_determination::StateDerivativePartial.
Definition at line 63 of file sphericalHarmonicGravitationalTorquePartial.cpp.
References accelerationPartial_, getParameterPartialFromAccelerationPartialFunction(), and tudat::estimatable_parameters::isParameterRotationMatrixProperty().
wrtOrientationOfAcceleratedBody()
virtual void tudat::acceleration_partials::SphericalHarmonicGravitationalTorquePartial::wrtOrientationOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 0) inline virtual
Function for calculating the partial of the torque w.r.t. the orientation of the accelerated body and adding it to the existing partial block.
Parameters
partialMatrix Block of partial derivatives of torque w.r.t. Orientation of body undergoing torque where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Implements tudat::acceleration_partials::TorquePartial.
Definition at line 93 of file sphericalHarmonicGravitationalTorquePartial.h.
References currentPartialDerivativeWrtQuaternion_.
isStateDerivativeDependentOnIntegratedAdditionalStateTypes()
bool tudat::acceleration_partials::SphericalHarmonicGravitationalTorquePartial::isStateDerivativeDependentOnIntegratedAdditionalStateTypes (const std::pair< std::string, std::string > & stateReferencePoint, const propagators::IntegratedStateType integratedStateType) inline
Function for determining if the torque is dependent on a non-rotational integrated state.
Parameters
stateReferencePoint Reference point id of propagated state
integratedStateType Type of propagated state for which dependency is to be determined.
Returns
True if dependency exists (non-zero partial), false otherwise.
Definition at line 114 of file sphericalHarmonicGravitationalTorquePartial.h.
References tudat::propagators::body_mass_state, tudat::acceleration_partials::TorquePartial::bodyExertingTorque_, tudat::acceleration_partials::TorquePartial::bodyUndergoingTorque_, getParameterPartialFromAccelerationPartialFunction(), tudat::propagators::translational_state, TUDAT_NAN, update(), and wrtNonRotationalStateOfAdditionalBody().
wrtNonRotationalStateOfAdditionalBody()
void tudat::acceleration_partials::SphericalHarmonicGravitationalTorquePartial::wrtNonRotationalStateOfAdditionalBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const std::pair< std::string, std::string > & stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function for calculating the partial of the torque w.r.t. a non-rotational integrated state and adding it to the existing partial block.
Parameters
partialMatrix Block of partial derivatives of where current partial is to be added.
stateReferencePoint Reference point id of propagated state
integratedStateType Type of propagated state for which partial is to be computed.
Definition at line 85 of file sphericalHarmonicGravitationalTorquePartial.cpp.
References accelerationPartial_, tudat::acceleration_partials::TorquePartial::bodyExertingTorque_, tudat::acceleration_partials::TorquePartial::bodyUndergoingTorque_, currentBodyFixedPotentialGradientCrossProductMatrix_, currentBodyFixedRelativePositionCrossProductMatrix_, currentRotationToBodyFixedFrame_, and tudat::propagators::translational_state.
Referenced by isStateDerivativeDependentOnIntegratedAdditionalStateTypes().
update()
void tudat::acceleration_partials::SphericalHarmonicGravitationalTorquePartial::update (const double currentTime = TUDAT_NAN) virtual
Update partial model to current time, retrieving information from consituent functions
Parameters
currentTime Time to which partial is to be updated
Implements tudat::orbit_determination::StateDerivativePartial.
Definition at line 102 of file sphericalHarmonicGravitationalTorquePartial.cpp.
References accelerationPartial_, tudat::linear_algebra::computePartialDerivativeOfRotationMatrixWrtQuaternion(), tudat::linear_algebra::convertQuaternionToVectorFormat(), currentBodyFixedPotentialGradient_, currentBodyFixedPotentialGradientCrossProductMatrix_, currentBodyFixedRelativePosition_, currentBodyFixedRelativePositionCrossProductMatrix_, currentParameterPartialPreMultiplier_, currentPartialDerivativeWrtQuaternion_, currentQuaternionVector_, currentRotationMatrixDerivativesWrtQuaternion_, currentRotationToBodyFixedFrame_, tudat::orbit_determination::StateDerivativePartial::currentTime_, tudat::linear_algebra::getCrossProductMatrix(), tudat::acceleration_partials::getPartialDerivativeOfSphericalHarmonicGravitationalTorqueWrtQuaternion(), and torqueModel_.
Referenced by isStateDerivativeDependentOnIntegratedAdditionalStateTypes().
getParameterPartialFromAccelerationPartialFunction()
void tudat::acceleration_partials::SphericalHarmonicGravitationalTorquePartial::getParameterPartialFromAccelerationPartialFunction (Eigen::MatrixXd & partialMatrix, const std::pair< std::function< void(Eigen::MatrixXd &) >, int > & accelerationPartialFunction) protected
Function to compute torque partial from constituent spherical harmonic acceleration partial
Parameters
partialMatrix Matrux with partial derivative (returned by reference)
accelerationPartialFunction Pair with (first: function returning partial by reference; second: number of columns in partial derivative).
Definition at line 137 of file sphericalHarmonicGravitationalTorquePartial.cpp.
References currentParameterPartialPreMultiplier_.
Referenced by getParameterPartialFunction(), and isStateDerivativeDependentOnIntegratedAdditionalStateTypes().
Member Data Documentation
currentQuaternionVector_
Eigen::Vector4d tudat::acceleration_partials::SphericalHarmonicGravitationalTorquePartial::currentQuaternionVector_ protected
Definition at line 166 of file sphericalHarmonicGravitationalTorquePartial.h.
Referenced by update().
currentRotationToBodyFixedFrame_
Eigen::Matrix3d tudat::acceleration_partials::SphericalHarmonicGravitationalTorquePartial::currentRotationToBodyFixedFrame_ protected
Definition at line 169 of file sphericalHarmonicGravitationalTorquePartial.h.
Referenced by update(), and wrtNonRotationalStateOfAdditionalBody().
currentBodyFixedRelativePosition_
Eigen::Vector3d tudat::acceleration_partials::SphericalHarmonicGravitationalTorquePartial::currentBodyFixedRelativePosition_ protected
Definition at line 172 of file sphericalHarmonicGravitationalTorquePartial.h.
Referenced by update().
currentBodyFixedPotentialGradient_
Eigen::Vector3d tudat::acceleration_partials::SphericalHarmonicGravitationalTorquePartial::currentBodyFixedPotentialGradient_ protected
Definition at line 175 of file sphericalHarmonicGravitationalTorquePartial.h.
Referenced by update().
currentBodyFixedRelativePositionCrossProductMatrix_
Eigen::Matrix3d tudat::acceleration_partials::SphericalHarmonicGravitationalTorquePartial::currentBodyFixedRelativePositionCrossProductMatrix_ protected
Definition at line 178 of file sphericalHarmonicGravitationalTorquePartial.h.
Referenced by update(), and wrtNonRotationalStateOfAdditionalBody().
currentBodyFixedPotentialGradientCrossProductMatrix_
Eigen::Matrix3d tudat::acceleration_partials::SphericalHarmonicGravitationalTorquePartial::currentBodyFixedPotentialGradientCrossProductMatrix_ protected
Definition at line 181 of file sphericalHarmonicGravitationalTorquePartial.h.
Referenced by update(), and wrtNonRotationalStateOfAdditionalBody().
currentParameterPartialPreMultiplier_
Eigen::Matrix3d tudat::acceleration_partials::SphericalHarmonicGravitationalTorquePartial::currentParameterPartialPreMultiplier_ protected
Definition at line 184 of file sphericalHarmonicGravitationalTorquePartial.h.
Referenced by getParameterPartialFromAccelerationPartialFunction(), and update().
currentPartialDerivativeWrtQuaternion_
Eigen::Matrix< double, 3, 4 > tudat::acceleration_partials::SphericalHarmonicGravitationalTorquePartial::currentPartialDerivativeWrtQuaternion_ protected
Definition at line 187 of file sphericalHarmonicGravitationalTorquePartial.h.
Referenced by update(), and wrtOrientationOfAcceleratedBody().
currentRotationMatrixDerivativesWrtQuaternion_
std::vector< Eigen::Matrix3d > tudat::acceleration_partials::SphericalHarmonicGravitationalTorquePartial::currentRotationMatrixDerivativesWrtQuaternion_ protected
Definition at line 190 of file sphericalHarmonicGravitationalTorquePartial.h.
Referenced by SphericalHarmonicGravitationalTorquePartial(), and update().
torqueModel_
std::shared_ptr< gravitation::SphericalHarmonicGravitationalTorqueModel > tudat::acceleration_partials::SphericalHarmonicGravitationalTorquePartial::torqueModel_ protected
Definition at line 193 of file sphericalHarmonicGravitationalTorquePartial.h.
Referenced by update().
accelerationPartial_
const std::shared_ptr< acceleration_partials::SphericalHarmonicsGravityPartial > tudat::acceleration_partials::SphericalHarmonicGravitationalTorquePartial::accelerationPartial_ protected
Definition at line 196 of file sphericalHarmonicGravitationalTorquePartial.h.
Referenced by getParameterPartialFunction(), update(), and wrtNonRotationalStateOfAdditionalBody().
The documentation for this class was generated from the following files:
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/OrbitDetermination/RotationalDynamicsPartials/sphericalHarmonicGravitationalTorquePartial.h
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/OrbitDetermination/RotationalDynamicsPartials/sphericalHarmonicGravitationalTorquePartial.cpp