Tudat: tudat::electro_magnetism::RadiationPressureInterface Class Reference
tudat::electro_magnetism::RadiationPressureInterface Class Reference
Class in which the properties of a solar radiation pressure acceleration model are stored.
#include <radiationPressureInterface.h>
Public Member Functions
RadiationPressureInterface (const std::function< double() > sourcePower, const std::function< Eigen::Vector3d() > sourcePositionFunction, const std::function< Eigen::Vector3d() > targetPositionFunction, const double radiationPressureCoefficient, const double area, const std::vector< std::function< Eigen::Vector3d() > > occultingBodyPositions=std::vector< std::function< Eigen::Vector3d() > >(), const std::vector< double > occultingBodyRadii=std::vector< double >(), const double sourceRadius=0.0)
Constructor.
virtual ~RadiationPressureInterface ()
Destructor.
double getArea () const
Function to return the reflecting area of the target body.
double getCurrentRadiationPressure () const
Function to return the current radiation pressure due to source at target (in N/m^2).
Eigen::Vector3d getCurrentSolarVector () const
Function to return the current vector from the target to the source.
double getCurrentTime ()
Function to return the current time of interface (i.e. time of last updateInterface call).
std::vector< std::function< Eigen::Vector3d() > > getOccultingBodyPositions ()
Function to return the list of functions returning the positions of the bodies causing occultations.
std::vector< double > getOccultingBodyRadii ()
Function to return the list of radii of the bodies causing occultations.
double getRadiationPressureCoefficient () const
Function to return the radiation pressure coefficient of the target body.
std::function< Eigen::Vector3d() > getSourcePositionFunction () const
Function to return the function returning the current position of the source body.
std::function< double() > getSourcePowerFunction () const
Function to return the function returning the current total power (in W) emitted by the source body.
double getSourceRadius ()
Function to return the radius of the source body.
std::function< Eigen::Vector3d() > getTargetPositionFunction () const
Function to return the function returning the current position of the target body.
void resetRadiationPressureCoefficient (const double radiationPressureCoefficient)
Function to reset a constant radiation pressure coefficient of the target body.
void resetRadiationPressureCoefficientFunction (const std::function< double(const double) > radiationPressureCoefficientFunction)
Function to reset the function to obtain the radiation pressure coefficient of the target body.
virtual void updateInterface (const double currentTime=TUDAT_NAN)
Function to update the current value of the radiation pressure.
void updateInterfaceBase (const double currentTime)
Base class function to update the current properties of radiation pressure.
Protected Attributes
double area_
Reflecting area of the target body.
double currentRadiationPressure_
Current radiation pressure due to source at target (in N/m^2).
Eigen::Vector3d currentSolarVector_
Current vector from the target to the source.
double currentTime_
Current time of interface (i.e. time of last updateInterface call).
std::vector< std::function< Eigen::Vector3d() > > occultingBodyPositions_
List of functions returning the positions of the bodies causing occultations.
std::vector< double > occultingBodyRadii_
List of radii of the bodies causing occultations.
double radiationPressureCoefficient_
Radiation pressure coefficient of the target body.
std::function< double(const double) > radiationPressureCoefficientFunction_
Function to reset a constant radiation pressure coefficient of the target body.
std::function< Eigen::Vector3d() > sourcePositionFunction_
Function returning the current position of the source body.
std::function< double() > sourcePower_
Function returning the current total power (in W) emitted by the source body.
double sourceRadius_
Radius of the source body.
std::function< Eigen::Vector3d() > targetPositionFunction_
Function returning the current position of the target body.
Detailed Description
Class in which the properties of a solar radiation pressure acceleration model are stored and the current radiation pressure is calculated based on the source power and geometry. The current implementation is limited to a cannonball model.
Definition at line 49 of file radiationPressureInterface.h.
Constructor & Destructor Documentation
RadiationPressureInterface()
tudat::electro_magnetism::RadiationPressureInterface::RadiationPressureInterface (const std::function< double() > sourcePower, const std::function< Eigen::Vector3d() > sourcePositionFunction, const std::function< Eigen::Vector3d() > targetPositionFunction, const double radiationPressureCoefficient, const double area, const std::vector< std::function< Eigen::Vector3d() > > occultingBodyPositions = std::vector< std::function< Eigen::Vector3d() > >(), const std::vector< double > occultingBodyRadii = std::vector< double > (), const double sourceRadius = 0.0) inline
Class construtor for radiation pressure interface.
Parameters
sourcePower Function returning the current total power (in W) emitted by the source body.
sourcePositionFunction Function returning the current position of the source body.
targetPositionFunction Function returning the current position of the target body.
radiationPressureCoefficient Reflectivity coefficient of the target body.
area Reflecting area of the target body.
occultingBodyPositions List of functions returning the positions of the bodies causing occultations (default none) NOTE: Multiple concurrent occultations may currently result in slighlty underestimted radiation pressure.
occultingBodyRadii List of radii of the bodies causing occultations (default none).
sourceRadius Radius of the source body (used for occultation calculations) (default 0).
Definition at line 67 of file radiationPressureInterface.h.
References area_, currentRadiationPressure_, currentSolarVector_, currentTime_, occultingBodyPositions_, occultingBodyRadii_, sourceRadius_, and TUDAT_NAN.
~RadiationPressureInterface()
virtual tudat::electro_magnetism::RadiationPressureInterface::~RadiationPressureInterface () inline virtual
Definition at line 90 of file radiationPressureInterface.h.
References TUDAT_NAN, updateInterface(), and updateInterfaceBase().
Member Function Documentation
updateInterfaceBase()
void tudat::electro_magnetism::RadiationPressureInterface::updateInterfaceBase (const double currentTime)
Base class function to update the current properties of radiation pressure. This function is nominally called by the updateInterface function, which may be overridden by derived classes.
Parameters
currentTime Time at which acceleration model is to be updated.
Definition at line 31 of file radiationPressureInterface.cpp.
References tudat::electro_magnetism::calculateRadiationPressure(), tudat::mission_geometry::computeShadowFunction(), currentRadiationPressure_, currentSolarVector_, currentTime_, occultingBodyPositions_, occultingBodyRadii_, sourcePositionFunction_, sourcePower_, sourceRadius_, and targetPositionFunction_.
Referenced by updateInterface(), tudat::electro_magnetism::PanelledRadiationPressureInterface::updateInterface(), tudat::electro_magnetism::SolarSailingRadiationPressureInterface::updateInterface(), and ~RadiationPressureInterface().
updateInterface()
void tudat::electro_magnetism::RadiationPressureInterface::updateInterface (const double currentTime = TUDAT_NAN) virtual
Function to update the current value of the radiation pressure, based on functions returning the positions of the bodies involved and the source power.
Parameters
currentTime Time at which acceleration model is to be updated.
Reimplemented in tudat::electro_magnetism::SolarSailingRadiationPressureInterface, and tudat::electro_magnetism::PanelledRadiationPressureInterface.
Definition at line 64 of file radiationPressureInterface.cpp.
References radiationPressureCoefficient_, radiationPressureCoefficientFunction_, and updateInterfaceBase().
Referenced by ~RadiationPressureInterface().
getCurrentRadiationPressure()
double tudat::electro_magnetism::RadiationPressureInterface::getCurrentRadiationPressure () const inline
Function to return the current radiation pressure due to source at target (in N/m^2).
Returns
Current radiation pressure due to source at target (in N/m^2).
Definition at line 114 of file radiationPressureInterface.h.
References currentRadiationPressure_.
Referenced by tudat::simulation_setup::createCannonballRadiationPressureAcceleratioModel(), tudat::simulation_setup::createSolarSailAccelerationModel(), tudat::propagators::getDoubleDependentVariableFunction(), and tudat::electro_magnetism::PanelledRadiationPressureAcceleration::PanelledRadiationPressureAcceleration().
getCurrentSolarVector()
Eigen::Vector3d tudat::electro_magnetism::RadiationPressureInterface::getCurrentSolarVector () const inline
Function to return the current vector from the target to the source.
Returns
Current vector from the target to the source.
Definition at line 124 of file radiationPressureInterface.h.
References currentSolarVector_.
Referenced by tudat::electro_magnetism::PanelledRadiationPressureAcceleration::PanelledRadiationPressureAcceleration().
getSourcePositionFunction()
std::function< Eigen::Vector3d() > tudat::electro_magnetism::RadiationPressureInterface::getSourcePositionFunction () const inline
Function to return the function returning the current position of the source body.
Returns
The function returning the current position of the source body.
Definition at line 134 of file radiationPressureInterface.h.
References sourcePositionFunction_.
getTargetPositionFunction()
std::function< Eigen::Vector3d() > tudat::electro_magnetism::RadiationPressureInterface::getTargetPositionFunction () const inline
Function to return the function returning the current position of the target body.
Returns
The function returning the current position of the target body.
Definition at line 144 of file radiationPressureInterface.h.
References targetPositionFunction_.
getArea()
double tudat::electro_magnetism::RadiationPressureInterface::getArea () const inline
Function to return the reflecting area of the target body.
Returns
The reflecting area of the target body.
Definition at line 154 of file radiationPressureInterface.h.
References area_.
Referenced by tudat::simulation_setup::createCannonballRadiationPressureAcceleratioModel(), tudat::simulation_setup::createSolarSailAccelerationModel(), and tudat::electro_magnetism::PanelledRadiationPressureAcceleration::PanelledRadiationPressureAcceleration().
getRadiationPressureCoefficient()
double tudat::electro_magnetism::RadiationPressureInterface::getRadiationPressureCoefficient () const inline
Function to return the radiation pressure coefficient of the target body.
Returns
The radiation pressure coefficient of the target body.
Definition at line 164 of file radiationPressureInterface.h.
References radiationPressureCoefficient_.
Referenced by tudat::simulation_setup::createCannonballRadiationPressureAcceleratioModel(), and tudat::propagators::getDoubleDependentVariableFunction().
resetRadiationPressureCoefficient()
void tudat::electro_magnetism::RadiationPressureInterface::resetRadiationPressureCoefficient (const double radiationPressureCoefficient) inline
Function to reset a constant radiation pressure coefficient of the target body.
Parameters
radiationPressureCoefficient The new radiation pressure coefficient of the target body.
Definition at line 174 of file radiationPressureInterface.h.
References radiationPressureCoefficient_, and radiationPressureCoefficientFunction_.
resetRadiationPressureCoefficientFunction()
void tudat::electro_magnetism::RadiationPressureInterface::resetRadiationPressureCoefficientFunction (const std::function< double(const double) > radiationPressureCoefficientFunction) inline
Function to reset the function to obtain the radiation pressure coefficient of the target body.
Parameters
radiationPressureCoefficientFunction New function to obtain the radiation pressure coefficient of the target body.
Definition at line 185 of file radiationPressureInterface.h.
References radiationPressureCoefficientFunction_.
getSourcePowerFunction()
std::function< double() > tudat::electro_magnetism::RadiationPressureInterface::getSourcePowerFunction () const inline
Function to return the function returning the current total power (in W) emitted by the source body.
Returns
The function returning the current total power emitted by the source body.
Definition at line 198 of file radiationPressureInterface.h.
References sourcePower_.
getCurrentTime()
double tudat::electro_magnetism::RadiationPressureInterface::getCurrentTime () inline
Function to return the current time of interface (i.e. time of last updateInterface call).
Returns
Current time of interface (i.e. time of last updateInterface call).
Definition at line 208 of file radiationPressureInterface.h.
References currentTime_.
getOccultingBodyPositions()
std::vector< std::function< Eigen::Vector3d() > > tudat::electro_magnetism::RadiationPressureInterface::getOccultingBodyPositions () inline
Function to return the list of functions returning the positions of the bodies causing occultations
Returns
List of functions returning the positions of the bodies causing occultations
Definition at line 221 of file radiationPressureInterface.h.
References occultingBodyPositions_.
getOccultingBodyRadii()
std::vector< double > tudat::electro_magnetism::RadiationPressureInterface::getOccultingBodyRadii () inline
Function to return the list of radii of the bodies causing occultations
Returns
List of radii of the bodies causing occultations
Definition at line 231 of file radiationPressureInterface.h.
References occultingBodyRadii_.
getSourceRadius()
double tudat::electro_magnetism::RadiationPressureInterface::getSourceRadius () inline
Function to return the source radius of the target body.
Returns
The source radius of the target body.
Definition at line 241 of file radiationPressureInterface.h.
References sourceRadius_.
Member Data Documentation
sourcePower_
std::function< double() > tudat::electro_magnetism::RadiationPressureInterface::sourcePower_ protected
Definition at line 250 of file radiationPressureInterface.h.
Referenced by getSourcePowerFunction(), and updateInterfaceBase().
sourcePositionFunction_
std::function< Eigen::Vector3d() > tudat::electro_magnetism::RadiationPressureInterface::sourcePositionFunction_ protected
Definition at line 253 of file radiationPressureInterface.h.
Referenced by getSourcePositionFunction(), and updateInterfaceBase().
targetPositionFunction_
std::function< Eigen::Vector3d() > tudat::electro_magnetism::RadiationPressureInterface::targetPositionFunction_ protected
Definition at line 256 of file radiationPressureInterface.h.
Referenced by getTargetPositionFunction(), and updateInterfaceBase().
radiationPressureCoefficient_
double tudat::electro_magnetism::RadiationPressureInterface::radiationPressureCoefficient_ protected
Definition at line 259 of file radiationPressureInterface.h.
Referenced by getRadiationPressureCoefficient(), resetRadiationPressureCoefficient(), and updateInterface().
radiationPressureCoefficientFunction_
std::function< double(const double) > tudat::electro_magnetism::RadiationPressureInterface::radiationPressureCoefficientFunction_ protected
Definition at line 262 of file radiationPressureInterface.h.
Referenced by resetRadiationPressureCoefficient(), resetRadiationPressureCoefficientFunction(), and updateInterface().
area_
double tudat::electro_magnetism::RadiationPressureInterface::area_ protected
Definition at line 265 of file radiationPressureInterface.h.
Referenced by getArea(), and RadiationPressureInterface().
occultingBodyPositions_
std::vector< std::function< Eigen::Vector3d() > > tudat::electro_magnetism::RadiationPressureInterface::occultingBodyPositions_ protected
Definition at line 268 of file radiationPressureInterface.h.
Referenced by getOccultingBodyPositions(), RadiationPressureInterface(), and updateInterfaceBase().
occultingBodyRadii_
std::vector< double > tudat::electro_magnetism::RadiationPressureInterface::occultingBodyRadii_ protected
Definition at line 271 of file radiationPressureInterface.h.
Referenced by getOccultingBodyRadii(), RadiationPressureInterface(), and updateInterfaceBase().
sourceRadius_
double tudat::electro_magnetism::RadiationPressureInterface::sourceRadius_ protected
Definition at line 274 of file radiationPressureInterface.h.
Referenced by getSourceRadius(), RadiationPressureInterface(), and updateInterfaceBase().
currentRadiationPressure_
double tudat::electro_magnetism::RadiationPressureInterface::currentRadiationPressure_ protected
Definition at line 277 of file radiationPressureInterface.h.
Referenced by getCurrentRadiationPressure(), RadiationPressureInterface(), and updateInterfaceBase().
currentSolarVector_
Eigen::Vector3d tudat::electro_magnetism::RadiationPressureInterface::currentSolarVector_ protected
Definition at line 280 of file radiationPressureInterface.h.
Referenced by getCurrentSolarVector(), RadiationPressureInterface(), and updateInterfaceBase().
currentTime_
double tudat::electro_magnetism::RadiationPressureInterface::currentTime_ protected
Definition at line 283 of file radiationPressureInterface.h.
Referenced by getCurrentTime(), RadiationPressureInterface(), and updateInterfaceBase().
The documentation for this class was generated from the following files:
Astrodynamics/ElectroMagnetism/radiationPressureInterface.h
Astrodynamics/ElectroMagnetism/radiationPressureInterface.cpp