Tudat: tudat::shape_based_methods::SineFunctionHodographicShaping Class Reference
tudat::shape_based_methods::SineFunctionHodographicShaping Class Reference
Sine function.
#include <baseFunctionsHodographicShaping.h>
Public Member Functions
SineFunctionHodographicShaping (double frequency)
Constructor taking the frequency of the sine function as input.
~SineFunctionHodographicShaping ()
Default destructor.
double evaluateDerivative (const double independentVariable)
double evaluateFunction (const double independentVariable)
Function, derivative, and integral of the sine function.
double evaluateIntegral (const double independentVariable)
Public Member Functions inherited from tudat::shape_based_methods::BaseFunctionHodographicShaping
BaseFunctionHodographicShaping ()
Default constructor.
virtual ~BaseFunctionHodographicShaping ()
Default destructor.
Private Attributes
double frequency_
Detailed Description
Definition at line 106 of file baseFunctionsHodographicShaping.h.
Constructor & Destructor Documentation
SineFunctionHodographicShaping()
tudat::shape_based_methods::SineFunctionHodographicShaping::SineFunctionHodographicShaping (double frequency) inline
Definition at line 111 of file baseFunctionsHodographicShaping.h.
~SineFunctionHodographicShaping()
tudat::shape_based_methods::SineFunctionHodographicShaping::~SineFunctionHodographicShaping () inline
Definition at line 117 of file baseFunctionsHodographicShaping.h.
References tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateDerivative(), tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateFunction(), tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateIntegral(), and tudat::propagators::independentVariable.
Member Function Documentation
evaluateFunction()
double tudat::shape_based_methods::SineFunctionHodographicShaping::evaluateFunction (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 26 of file baseFunctionsHodographicShaping.cpp.
References frequency_.
evaluateDerivative()
double tudat::shape_based_methods::SineFunctionHodographicShaping::evaluateDerivative (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 31 of file baseFunctionsHodographicShaping.cpp.
References frequency_.
evaluateIntegral()
double tudat::shape_based_methods::SineFunctionHodographicShaping::evaluateIntegral (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 36 of file baseFunctionsHodographicShaping.cpp.
References frequency_.
Member Data Documentation
frequency_
double tudat::shape_based_methods::SineFunctionHodographicShaping::frequency_ private
Definition at line 130 of file baseFunctionsHodographicShaping.h.
Referenced by evaluateDerivative(), tudat::shape_based_methods::CosineFunctionHodographicShaping::evaluateDerivative(), evaluateFunction(), tudat::shape_based_methods::CosineFunctionHodographicShaping::evaluateFunction(), evaluateIntegral(), and tudat::shape_based_methods::CosineFunctionHodographicShaping::evaluateIntegral().
The documentation for this class was generated from the following files:
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/baseFunctionsHodographicShaping.h
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/baseFunctionsHodographicShaping.cpp