Tudat: tudat::observation_partials::SynchronousRotationMatrixPartialWrtTranslationalState Class Reference
tudat::observation_partials::SynchronousRotationMatrixPartialWrtTranslationalState Class Reference
Class to calculate a rotation matrix from a body-fixed to inertial frame w.r.t. the translational state for synchronous rotation.
#include <rotationMatrixPartial.h>
Public Member Functions
SynchronousRotationMatrixPartialWrtTranslationalState (const std::shared_ptr< ephemerides::SynchronousRotationalEphemeris > synchronousRotationaModel)
Constructor.
~SynchronousRotationMatrixPartialWrtTranslationalState ()
Destructor.
std::vector< Eigen::Matrix3d > calculatePartialOfRotationMatrixDerivativeToBaseFrameWrParameter (const double time)
Function to compute the required partial derivative of rotation matrix derivative.
std::vector< Eigen::Matrix3d > calculatePartialOfRotationMatrixToBaseFrameWrParameter (const double time)
Function to compute the required partial derivative of rotation matrix.
Public Member Functions inherited from tudat::observation_partials::RotationMatrixPartial
RotationMatrixPartial (const std::shared_ptr< ephemerides::RotationalEphemeris > rotationModel)
virtual ~RotationMatrixPartial ()
Virtual destructor.
Eigen::Matrix< double, 3, Eigen::Dynamic > calculatePartialOfInertialPositionWrtParameter (const double time, const Eigen::Vector3d vectorInLocalFrame)
Function to calculate the partial of the position of a vector, which is given in a body-fixed frame, in the inertial frame wrt a parameter denoting a property of the rotation between a body-fixed and an inertial frame.
Eigen::Matrix< double, 3, Eigen::Dynamic > calculatePartialOfInertialVelocityWrtParameter (const double time, const Eigen::Vector3d vectorInLocalFrame)
Function to calculate the partial of the velocity of a vector, which is given in a body-fixed frame, in the inertial frame wrt a parameter denoting a property of the rotation between a body-fixed and an inertial frame.
virtual std::string getSecondaryIdentifier ()
Function to return the secondary identifier of the estimated parameter.
Private Attributes
std::shared_ptr< ephemerides::SynchronousRotationalEphemeris > synchronousRotationaModel_
Rotation model that defines the synchronous rotation.
Additional Inherited Members
Protected Attributes inherited from tudat::observation_partials::RotationMatrixPartial
std::shared_ptr< ephemerides::RotationalEphemeris > rotationModel_
Detailed Description
Class to calculate a rotation matrix from a body-fixed to inertial frame w.r.t. the translational state for a synchronous rotation model
Definition at line 839 of file rotationMatrixPartial.h.
Constructor & Destructor Documentation
SynchronousRotationMatrixPartialWrtTranslationalState()
tudat::observation_partials::SynchronousRotationMatrixPartialWrtTranslationalState::SynchronousRotationMatrixPartialWrtTranslationalState (const std::shared_ptr< ephemerides::SynchronousRotationalEphemeris > synchronousRotationaModel) inline
Constructor
Parameters
synchronousRotationaModel Rotation model that defines the synchronous rotation
Definition at line 848 of file rotationMatrixPartial.h.
~SynchronousRotationMatrixPartialWrtTranslationalState()
tudat::observation_partials::SynchronousRotationMatrixPartialWrtTranslationalState::~SynchronousRotationMatrixPartialWrtTranslationalState () inline
Definition at line 857 of file rotationMatrixPartial.h.
References tudat::observation_partials::RotationMatrixPartial::calculatePartialOfRotationMatrixToBaseFrameWrParameter().
Member Function Documentation
calculatePartialOfRotationMatrixToBaseFrameWrParameter()
std::vector< Eigen::Matrix3d > tudat::observation_partials::SynchronousRotationMatrixPartialWrtTranslationalState::calculatePartialOfRotationMatrixToBaseFrameWrParameter (const double time) virtual
Function to compute the partial derivative of rotation matrix from a body-fixed to inertial frame w.r.t. the translational state
Parameters
time Time at which partials are to be computed
Returns
Vector of size 6 containing partials of rotation matrix from body-fixed to inertial frame w.r.t. the six inertial Cartesian translational state elements.
Implements tudat::observation_partials::RotationMatrixPartial.
Definition at line 1124 of file rotationMatrixPartial.cpp.
References tudat::linear_algebra::getCrossProductMatrix().
Referenced by tudat::observation_partials::RotationMatrixPartial::calculatePartialOfInertialVelocityWrtParameter().
calculatePartialOfRotationMatrixDerivativeToBaseFrameWrParameter()
std::vector< Eigen::Matrix3d > tudat::observation_partials::SynchronousRotationMatrixPartialWrtTranslationalState::calculatePartialOfRotationMatrixDerivativeToBaseFrameWrParameter (const double time) inline virtual
Function to compute the partial derivative of derivative of rotation matrix from a body-fixed to inertial frame w.r.t. the rotational state vector. NOTE: function not yet implemented
Parameters
time Time at which partials are to be computed
Returns
Vector of size 7 containing partials of rotation matrix derivative from body-fixed to inertial frame w.r.t. the rotational state vector
Implements tudat::observation_partials::RotationMatrixPartial.
Definition at line 877 of file rotationMatrixPartial.h.
Member Data Documentation
synchronousRotationaModel_
std::shared_ptr< ephemerides::SynchronousRotationalEphemeris > tudat::observation_partials::SynchronousRotationMatrixPartialWrtTranslationalState::synchronousRotationaModel_ private
Definition at line 888 of file rotationMatrixPartial.h.
The documentation for this class was generated from the following files:
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/OrbitDetermination/ObservationPartials/rotationMatrixPartial.h
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/OrbitDetermination/ObservationPartials/rotationMatrixPartial.cpp