Tudat: tudat::shape_based_methods::ScaledExponentialFunctionHodographicShaping Class Reference
tudat::shape_based_methods::ScaledExponentialFunctionHodographicShaping Class Reference
Scaled exponential function.
#include <baseFunctionsHodographicShaping.h>
Public Member Functions
ScaledExponentialFunctionHodographicShaping (double exponent, double scaleFactor)
Constructor taking the exponent and scaling factor as inputs.
~ScaledExponentialFunctionHodographicShaping ()
Default destructor.
double evaluateDerivative (const double independentVariable)
double evaluateFunction (const double independentVariable)
Function, derivative, and integral of the scaled exponential function.
double evaluateIntegral (const double independentVariable)
Public Member Functions inherited from tudat::shape_based_methods::BaseFunctionHodographicShaping
BaseFunctionHodographicShaping ()
Default constructor.
virtual ~BaseFunctionHodographicShaping ()
Default destructor.
Private Attributes
double exponent_
double scaleFactor_
Detailed Description
Definition at line 192 of file baseFunctionsHodographicShaping.h.
Constructor & Destructor Documentation
ScaledExponentialFunctionHodographicShaping()
tudat::shape_based_methods::ScaledExponentialFunctionHodographicShaping::ScaledExponentialFunctionHodographicShaping (double exponent, double scaleFactor) inline
Definition at line 197 of file baseFunctionsHodographicShaping.h.
~ScaledExponentialFunctionHodographicShaping()
tudat::shape_based_methods::ScaledExponentialFunctionHodographicShaping::~ScaledExponentialFunctionHodographicShaping () inline
Definition at line 204 of file baseFunctionsHodographicShaping.h.
References tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateDerivative(), tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateFunction(), tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateIntegral(), and tudat::propagators::independentVariable.
Member Function Documentation
evaluateFunction()
double tudat::shape_based_methods::ScaledExponentialFunctionHodographicShaping::evaluateFunction (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 79 of file baseFunctionsHodographicShaping.cpp.
evaluateDerivative()
double tudat::shape_based_methods::ScaledExponentialFunctionHodographicShaping::evaluateDerivative (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 84 of file baseFunctionsHodographicShaping.cpp.
evaluateIntegral()
double tudat::shape_based_methods::ScaledExponentialFunctionHodographicShaping::evaluateIntegral (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 89 of file baseFunctionsHodographicShaping.cpp.
Member Data Documentation
exponent_
double tudat::shape_based_methods::ScaledExponentialFunctionHodographicShaping::exponent_ private
Definition at line 216 of file baseFunctionsHodographicShaping.h.
scaleFactor_
double tudat::shape_based_methods::ScaledExponentialFunctionHodographicShaping::scaleFactor_ private
Definition at line 217 of file baseFunctionsHodographicShaping.h.
The documentation for this class was generated from the following files:
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/baseFunctionsHodographicShaping.h
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/baseFunctionsHodographicShaping.cpp