Tudat: tudat::shape_based_methods::BaseFunctionSphericalShaping Class Reference
tudat::shape_based_methods::BaseFunctionSphericalShaping Class Reference abstract
Base class for shaping functions to be used in the spherical shaping method.
#include <baseFunctionsSphericalShaping.h>
Public Member Functions
BaseFunctionSphericalShaping ()
Default constructor.
virtual ~BaseFunctionSphericalShaping ()
Default destructor.
virtual double evaluateFirstDerivative (const double independentVariable)=0
virtual double evaluateFunction (const double independentVariable)=0
virtual double evaluateSecondDerivative (const double independentVariable)=0
virtual double evaluateThirdDerivative (const double independentVariable)=0
Detailed Description
Definition at line 35 of file baseFunctionsSphericalShaping.h.
Constructor & Destructor Documentation
BaseFunctionSphericalShaping()
tudat::shape_based_methods::BaseFunctionSphericalShaping::BaseFunctionSphericalShaping () inline
Default constructor.
Definition at line 43 of file baseFunctionsSphericalShaping.h.
~BaseFunctionSphericalShaping()
virtual tudat::shape_based_methods::BaseFunctionSphericalShaping::~BaseFunctionSphericalShaping () inline virtual
Default destructor.
Definition at line 49 of file baseFunctionsSphericalShaping.h.
References evaluateFirstDerivative(), evaluateFunction(), evaluateSecondDerivative(), evaluateThirdDerivative(), and tudat::propagators::independentVariable.
Member Function Documentation
evaluateFunction()
virtual double tudat::shape_based_methods::BaseFunctionSphericalShaping::evaluateFunction (const double independentVariable) pure virtual
Implemented in tudat::shape_based_methods::PowerSineFunctionSphericalShaping, tudat::shape_based_methods::SineFunctionSphericalShaping, tudat::shape_based_methods::PowerCosineFunctionSphericalShaping, tudat::shape_based_methods::CosineFunctionSphericalShaping, tudat::shape_based_methods::SquaredFunctionSphericalShaping, tudat::shape_based_methods::LinearFunctionSphericalShaping, and tudat::shape_based_methods::ConstantFunctionSphericalShaping.
Referenced by ~BaseFunctionSphericalShaping().
evaluateFirstDerivative()
virtual double tudat::shape_based_methods::BaseFunctionSphericalShaping::evaluateFirstDerivative (const double independentVariable) pure virtual
Implemented in tudat::shape_based_methods::PowerSineFunctionSphericalShaping, tudat::shape_based_methods::SineFunctionSphericalShaping, tudat::shape_based_methods::PowerCosineFunctionSphericalShaping, tudat::shape_based_methods::CosineFunctionSphericalShaping, tudat::shape_based_methods::SquaredFunctionSphericalShaping, tudat::shape_based_methods::LinearFunctionSphericalShaping, and tudat::shape_based_methods::ConstantFunctionSphericalShaping.
Referenced by ~BaseFunctionSphericalShaping().
evaluateSecondDerivative()
virtual double tudat::shape_based_methods::BaseFunctionSphericalShaping::evaluateSecondDerivative (const double independentVariable) pure virtual
Implemented in tudat::shape_based_methods::PowerSineFunctionSphericalShaping, tudat::shape_based_methods::SineFunctionSphericalShaping, tudat::shape_based_methods::PowerCosineFunctionSphericalShaping, tudat::shape_based_methods::CosineFunctionSphericalShaping, tudat::shape_based_methods::SquaredFunctionSphericalShaping, tudat::shape_based_methods::LinearFunctionSphericalShaping, and tudat::shape_based_methods::ConstantFunctionSphericalShaping.
Referenced by ~BaseFunctionSphericalShaping().
evaluateThirdDerivative()
virtual double tudat::shape_based_methods::BaseFunctionSphericalShaping::evaluateThirdDerivative (const double independentVariable) pure virtual
Implemented in tudat::shape_based_methods::PowerSineFunctionSphericalShaping, tudat::shape_based_methods::SineFunctionSphericalShaping, tudat::shape_based_methods::PowerCosineFunctionSphericalShaping, tudat::shape_based_methods::CosineFunctionSphericalShaping, tudat::shape_based_methods::SquaredFunctionSphericalShaping, tudat::shape_based_methods::LinearFunctionSphericalShaping, and tudat::shape_based_methods::ConstantFunctionSphericalShaping.
Referenced by ~BaseFunctionSphericalShaping().
The documentation for this class was generated from the following file:
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/baseFunctionsSphericalShaping.h