Tudat: tudat::propagators::VariationalEquations Class Reference
tudat::propagators::VariationalEquations Class Reference
Class from which the variational equations can be evaluated.
#include <variationalEquations.h>
Public Member Functions
template<typename ParameterType >
VariationalEquations (const std::map< IntegratedStateType, orbit_determination::StateDerivativePartialsMap > stateDerivativePartialList, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const std::map< IntegratedStateType, int > &stateTypeStartIndices, const int currentArcIndex=-1)
Constructor of variation equations class.
void clearPartials ()
Function to clear reference/cached values of state derivative partials.
template<typename StateScalarType >
void evaluateVariationalEquations (const double time, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &stateTransitionAndSensitivityMatrices, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > currentMatrixDerivative)
Evaluates the complete variational equations.
template<typename StateScalarType >
void getBodyInitialStatePartialMatrix (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &stateTransitionAndSensitivityMatrices, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > currentMatrixDerivative)
Function to compute the contribution of the derivatives w.r.t. current states in the variational equations.
double getNumberOfParameterValues ()
Returns the number of parameter values.
template<typename StateScalarType >
void getParameterPartialMatrix (Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > currentMatrixDerivative)
Calculates matrix containing partial derivatives of state derivatives w.r.t. parameters.
std::vector< std::pair< int, int > > getStatePartialAdditionIndices ()
void setBodyStatePartialMatrix ()
Calculates matrix containing partial derivatives of state derivatives w.r.t. body state.
void suppressParameterCoupling (const int couplingEntriesToSuppress)
template<typename StateScalarType >
void updatePartials (const double currentTime, const std::unordered_map< IntegratedStateType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentStatesPerTypeInConventionalRepresentation)
This function updates all state derivative models to the current time and state.
Private Member Functions
template<typename CurrentParameterType >
void addParameterPartialToList (const std::map< int, std::shared_ptr< estimatable_parameters::EstimatableParameter< CurrentParameterType > > > &parameterList, const std::shared_ptr< orbit_determination::StateDerivativePartial > partialObject, std::multimap< std::pair< int, int >, std::function< void(Eigen::Block< Eigen::MatrixXd >) > > &functionListOfBody, const int totalParameterVectorIndicesToSubtract=0)
Function to add parameter partial functions for single state derivative model, and set of parameter objects.
template<typename ParameterType >
void setParameterPartialFunctionList (const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate)
This function creates the list of partial derivatives of the state w.r.t. parameter values.
template<typename ParameterType >
void setRotationalStatePartialScalingFunctions (const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate)
Function that sets the pre-multipliers for angular acceleration partial derivatives.
void setStatePartialFunctionList ()
Function (called by constructor) to set up the statePartialList_ member from the state derivative partials.
template<typename ParameterType >
void setTranslationalStatePartialFrameScalingFunctions (const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const int currentArcIndex=-1)
Function called by constructor to handle estimation of hierarchical translational dynamics.
Private Attributes
int couplingEntriesToSuppress_
std::unordered_map< IntegratedStateType, Eigen::VectorXd > currentStatesPerTypeInConventionalRepresentation_
Current states, in conventional representation (e.g. transformed from specific propagator) sorted per state type.
std::map< propagators::IntegratedStateType, std::vector< std::pair< std::string, std::string > > > dynamicalStatesToEstimate_
List of identifiers for points/bodies for which initial dynamical state is to be estimated.
std::multimap< std::pair< int, int >, std::function< void(Eigen::Block< Eigen::MatrixXd >) > >::iterator functionIterator
Pre-declared iterator over all parameter partial functions.
std::vector< std::pair< int, std::function< Eigen::Matrix3d() > > > inertiaTensorsForMultiplication_
Functions returning inertia tensors of bodies, to be used for rotational variational equations.
int numberOfParameterValues_
Number of parameter values in estimation (i.e. number of columns in sensitivity matrix)
std::map< IntegratedStateType, std::vector< std::multimap< std::pair< int, int >, std::function< void(Eigen::Block< Eigen::MatrixXd >) > > > > parameterPartialList_
List of all functions returning current partial derivative w.r.t. a parameter.
std::map< propagators::IntegratedStateType, orbit_determination::StateDerivativePartialsMap > stateDerivativePartialList_
Map with list of StateDerivativePartialsMaps, with state type as key.
std::map< propagators::IntegratedStateType, orbit_determination::StateDerivativePartialsMap >::iterator stateDerivativeTypeIterator_
Pre-declared iterator over all state types.
std::vector< std::pair< int, int > > statePartialAdditionIndices_
Vector of pair providing indices of column blocks of variational equations to add to other column blocks.
std::multimap< std::pair< int, int >, std::function< void(Eigen::Block< Eigen::MatrixXd >) > >::iterator statePartialIterator_
Pre-defined iterator for efficiency.
std::map< IntegratedStateType, std::vector< std::multimap< std::pair< int, int >, std::function< void(Eigen::Block< Eigen::MatrixXd >) > > > > statePartialList_
List of all functions returning current partial derivative w.r.t. a current dynamical state.
std::map< IntegratedStateType, int > stateTypeStartIndices_
Map of start entry in sensitivity matrix of each type of estimated dynamics.
int totalDynamicalStateSize_
Total size of (single-arc) state vector of dynamics that is to be estimated.
Eigen::MatrixXd variationalMatrix_
Total matrix of partial derivatives of state derivatives w.r.t. current states.
Eigen::MatrixXd variationalParameterMatrix_
Total matrix of partial derivatives of state derivatives w.r.t. parameter vectors.
Detailed Description
Class from which the variational equations can be evaluated. The time derivative of the state transition and sensitivity matrices are computed from a set of state derivative partials objects, at the current time and state. This class performs all required bookkeeping to update, evaluate and combine these state derivative partials into the variational equations. The VariationalEquationsSolver object is used to manage and execute the full numerical integration of these variational equations and equations of motion.
Definition at line 43 of file variationalEquations.h.
Constructor & Destructor Documentation
VariationalEquations()
template<typename ParameterType > tudat::propagators::VariationalEquations::VariationalEquations (const std::map< IntegratedStateType, orbit_determination::StateDerivativePartialsMap > stateDerivativePartialList, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const std::map< IntegratedStateType, int > & stateTypeStartIndices, const int currentArcIndex = -1) inline
Constructor of variation equations class. Since the vehicle state must be integrated along with the variational equations, an object calculating the state derivative is required.
Parameters
stateDerivativePartialList List partials of state derivative models from which the variational equations are set up. The key is the type of dynamics for which partials are taken, the values are StateDerivativePartialsMap (see StateDerivativePartialsMap definition for details)
parametersToEstimate Object containing all parameters that are to be estimated and their current settings and values.
stateTypeStartIndices Start index (value) in vector of propagated state for each type of state (key)
currentArcIndex Index of current arc (-1 if not multi-arc)
Definition at line 61 of file variationalEquations.h.
References dynamicalStatesToEstimate_, getBodyInitialStatePartialMatrix(), tudat::estimatable_parameters::getSingleArcParameterSetSize(), tudat::propagators::getSingleIntegrationSize(), numberOfParameterValues_, setBodyStatePartialMatrix(), setParameterPartialFunctionList(), setRotationalStatePartialScalingFunctions(), setStatePartialFunctionList(), setTranslationalStatePartialFrameScalingFunctions(), stateDerivativePartialList_, totalDynamicalStateSize_, variationalMatrix_, and variationalParameterMatrix_.
Member Function Documentation
setBodyStatePartialMatrix()
void tudat::propagators::VariationalEquations::setBodyStatePartialMatrix ()
Calculates matrix containing partial derivatives of state derivatives w.r.t. body state, i.e. first matrix in right hand side of Eq. (7.45) in (Montenbruck & Gill, 2000).
Returns
Matrix containing partial derivatives of state derivative w.r.t. body state
Definition at line 55 of file variationalEquations.cpp.
References currentStatesPerTypeInConventionalRepresentation_, dynamicalStatesToEstimate_, tudat::propagators::getAngularVelocityToQuaternionRateMatrix(), tudat::propagators::getGeneralizedAccelerationSize(), tudat::propagators::getQuaterionToQuaternionRateMatrix(), tudat::propagators::getSingleIntegrationSize(), inertiaTensorsForMultiplication_, tudat::propagators::rotational_state, statePartialAdditionIndices_, statePartialIterator_, statePartialList_, stateTypeStartIndices_, totalDynamicalStateSize_, tudat::propagators::translational_state, and variationalMatrix_.
Referenced by getBodyInitialStatePartialMatrix(), and VariationalEquations().
getBodyInitialStatePartialMatrix()
template<typename StateScalarType > template void tudat::propagators::VariationalEquations::getBodyInitialStatePartialMatrix< long double > (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > & stateTransitionAndSensitivityMatrices, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > currentMatrixDerivative)
Function to compute the contribution of the derivatives w.r.t. current states in the variational equations, e.g. first term in Eq. (7.45) in (Montenbruck & Gill, 2000).
Parameters
stateTransitionAndSensitivityMatrices Current combined state transition and sensitivity matric
currentMatrixDerivative Matrix block which is to return (by reference) the given contribution to the variational equations.
Definition at line 30 of file variationalEquations.cpp.
References couplingEntriesToSuppress_, numberOfParameterValues_, setBodyStatePartialMatrix(), totalDynamicalStateSize_, and variationalMatrix_.
Referenced by VariationalEquations().
getParameterPartialMatrix()
template<typename StateScalarType > void tudat::propagators::VariationalEquations::getParameterPartialMatrix (Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > currentMatrixDerivative) inline
Calculates matrix containing partial derivatives of state derivatives w.r.t. parameters, i.e. second matrix in rhs of Eq. (7.45) in (Montenbruck & Gill, 2000).
Parameters
currentMatrixDerivative Matrix block containing partial derivatives of accelerarion w.r.t. parameters (returned by reference).
Definition at line 141 of file variationalEquations.h.
References functionIterator, tudat::propagators::getGeneralizedAccelerationSize(), tudat::propagators::getSingleIntegrationSize(), inertiaTensorsForMultiplication_, numberOfParameterValues_, parameterPartialList_, stateTypeStartIndices_, totalDynamicalStateSize_, and variationalParameterMatrix_.
evaluateVariationalEquations()
template<typename StateScalarType > void tudat::propagators::VariationalEquations::evaluateVariationalEquations (const double time, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > & stateTransitionAndSensitivityMatrices, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > currentMatrixDerivative) inline
Evaluates the complete variational equations at a given time and state transition matrix, sensitivity matrix and state (accessed indirectly). This function evaluates the complete Eq. (7.45) from (Montenbruck & Gill, 2000).
Parameters
time Current time
stateTransitionAndSensitivityMatrices Combined state transition and sensitivity matrix.
currentMatrixDerivative Variation equations result (returned by reference).
Definition at line 202 of file variationalEquations.h.
References clearPartials(), numberOfParameterValues_, and totalDynamicalStateSize_.
clearPartials()
void tudat::propagators::VariationalEquations::clearPartials ()
Function to clear reference/cached values of state derivative partials, to ensure that they are all recalculated.
Definition at line 125 of file variationalEquations.cpp.
References stateDerivativePartialList_, stateDerivativeTypeIterator_, and TUDAT_NAN.
Referenced by evaluateVariationalEquations().
updatePartials()
template<typename StateScalarType > void tudat::propagators::VariationalEquations::updatePartials (const double currentTime, const std::unordered_map< IntegratedStateType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentStatesPerTypeInConventionalRepresentation) inline
This function updates all state derivative models to the current time and state.
Parameters
currentTime Time to which the system is to be updated.
currentStatesPerTypeInConventionalRepresentation Current states, in conventional representation (e.g. transformed from specific propagator) sorted per state type.
Definition at line 234 of file variationalEquations.h.
References currentStatesPerTypeInConventionalRepresentation_, stateDerivativePartialList_, and stateDerivativeTypeIterator_.
getNumberOfParameterValues()
double tudat::propagators::VariationalEquations::getNumberOfParameterValues () inline
Returns the number of parameter values (i.e. number of columns in state transition matrix).
Returns
Number of parameter values.
Definition at line 282 of file variationalEquations.h.
References numberOfParameterValues_.
getStatePartialAdditionIndices()
std::vector< std::pair< int, int > > tudat::propagators::VariationalEquations::getStatePartialAdditionIndices () inline
Definition at line 287 of file variationalEquations.h.
References statePartialAdditionIndices_.
suppressParameterCoupling()
void tudat::propagators::VariationalEquations::suppressParameterCoupling (const int couplingEntriesToSuppress) inline
Definition at line 292 of file variationalEquations.h.
References couplingEntriesToSuppress_, and setStatePartialFunctionList().
setStatePartialFunctionList()
void tudat::propagators::VariationalEquations::setStatePartialFunctionList () private
Function (called by constructor) to set up the functions to evaluate the partial derivatives of the state derivatives w.r.t. a current state (stored in the statePartialList_ member) from the state derivative partials.
Definition at line 143 of file variationalEquations.cpp.
References dynamicalStatesToEstimate_, tudat::propagators::getSingleIntegrationSize(), stateDerivativePartialList_, stateDerivativeTypeIterator_, statePartialList_, and stateTypeStartIndices_.
Referenced by suppressParameterCoupling(), and VariationalEquations().
addParameterPartialToList()
template<typename CurrentParameterType > void tudat::propagators::VariationalEquations::addParameterPartialToList (const std::map< int, std::shared_ptr< estimatable_parameters::EstimatableParameter< CurrentParameterType > > > & parameterList, const std::shared_ptr< orbit_determination::StateDerivativePartial > partialObject, std::multimap< std::pair< int, int >, std::function< void(Eigen::Block< Eigen::MatrixXd >) > > & functionListOfBody, const int totalParameterVectorIndicesToSubtract = 0) inline private
Function to add parameter partial functions for single state derivative model, and set of parameter objects. Partial derivative functions that are not-empty are added to the functionListOfBody input (returned by reference). A list of parameters of a single type (double or vector) are handled a single function call.
Parameters
parameterList Map of parameters for which partial functions are to checked and created. Map keys are start entry of parameter in total parameter vector.
partialObject State derivative partial object from which partial functions are to be retrieved.
functionListOfBody Multimap of partial derivative functions to which entries are to be added by this function. Map key is start index and size of given parameter in sensitivity matrix. Map value is partial function.
totalParameterVectorIndicesToSubtract Number of entries by which to shift start index in sensitivity matrix from entry in parameter vector (used for multi-arc estimation).
Definition at line 322 of file variationalEquations.h.
References tudat::orbit_determination::StateDerivativePartial::getCurrentParameterPartial().
setParameterPartialFunctionList()
template<typename ParameterType > void tudat::propagators::VariationalEquations::setParameterPartialFunctionList (const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate) inline private
This function creates the list of partial derivatives of the state w.r.t. parameter values. The function is called once by the constructor and the resulting functions are set as member variables. This prevents having to check whether an acceleration model depends on every parameter during every time step.
Parameters
parametersToEstimate Object containing all parameters that are to be estimated and their current settings and values.
Definition at line 372 of file variationalEquations.h.
References tudat::estimatable_parameters::getSingleArcInitialDynamicalStateParameterSetSize(), parameterPartialList_, and stateDerivativePartialList_.
Referenced by VariationalEquations().
setTranslationalStatePartialFrameScalingFunctions()
template<typename ParameterType > void tudat::propagators::VariationalEquations::setTranslationalStatePartialFrameScalingFunctions (const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const int currentArcIndex = -1) inline private
Function called by constructor to handle estimation of hierarchical translational dynamics, i.e. where the state of body A is estimated w.r.t. body B, and body B is itself estimated w.r.t. to some third body (or inertial point) C.
Parameters
parametersToEstimate Total list of parameters to estimate.
currentArcIndex Index of current arc (-1 if not multi-arc)
Definition at line 433 of file variationalEquations.h.
References tudat::estimatable_parameters::arc_wise_initial_body_state, tudat::propagators::determineEphemerisUpdateorder(), tudat::propagators::getSingleIntegrationSize(), tudat::estimatable_parameters::initial_body_state, statePartialAdditionIndices_, stateTypeStartIndices_, and tudat::propagators::translational_state.
Referenced by VariationalEquations().
setRotationalStatePartialScalingFunctions()
template<typename ParameterType > void tudat::propagators::VariationalEquations::setRotationalStatePartialScalingFunctions (const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate) inline private
Function that sets the pre-multipliers for angular acceleration partial derivatives
Parameters
parametersToEstimate Total list of parameters to estimate.
Definition at line 503 of file variationalEquations.h.
References inertiaTensorsForMultiplication_, tudat::estimatable_parameters::initial_rotational_body_state, tudat::propagators::rotational_state, and stateTypeStartIndices_.
Referenced by VariationalEquations().
Member Data Documentation
stateDerivativePartialList_
std::map< propagators::IntegratedStateType, orbit_determination::StateDerivativePartialsMap > tudat::propagators::VariationalEquations::stateDerivativePartialList_ private
List partials of state derivative models from which the variational equations are set up. The key is the type of dynamics for which partials are taken, the values are StateDerivativePartialsMap (see StateDerivativePartialsMap definition for details)
Definition at line 534 of file variationalEquations.h.
Referenced by clearPartials(), setParameterPartialFunctionList(), setStatePartialFunctionList(), updatePartials(), and VariationalEquations().
stateTypeStartIndices_
std::map< IntegratedStateType, int > tudat::propagators::VariationalEquations::stateTypeStartIndices_ private
Definition at line 537 of file variationalEquations.h.
Referenced by getParameterPartialMatrix(), setBodyStatePartialMatrix(), setRotationalStatePartialScalingFunctions(), setStatePartialFunctionList(), and setTranslationalStatePartialFrameScalingFunctions().
statePartialList_
std::map< IntegratedStateType, std::vector< std::multimap< std::pair< int, int >, std::function< void(Eigen::Block< Eigen::MatrixXd >) > > > > tudat::propagators::VariationalEquations::statePartialList_ private
List of all functions returning current partial derivative w.r.t. a current dynamical state (map key). The vector entries correspond to the entries in the outer vector of StateDerivativePartialsMaps in stateDerivativePartialList_. The multimaps inside the vector provide the functions (as values) adding the partials to a given matrix block and the start column and number of columns in matrix partial (as keys).
Definition at line 548 of file variationalEquations.h.
Referenced by setBodyStatePartialMatrix(), and setStatePartialFunctionList().
statePartialIterator_
std::multimap< std::pair< int, int >, std::function< void(Eigen::Block< Eigen::MatrixXd >) > >::iterator tudat::propagators::VariationalEquations::statePartialIterator_ private
Definition at line 552 of file variationalEquations.h.
Referenced by setBodyStatePartialMatrix().
statePartialAdditionIndices_
std::vector< std::pair< int, int > > tudat::propagators::VariationalEquations::statePartialAdditionIndices_ private
Vector of pair providing indices of column blocks of variational equations to add to other column blocks, which is needed by the hierarchical estimation fo dynamics. The second pair entry is the start of the column block (of size 3) to where it should be copied. The first entry denotes from where it should be copied.
See also
setTranslationalStatePartialFrameScalingFunctions
Definition at line 561 of file variationalEquations.h.
Referenced by getStatePartialAdditionIndices(), setBodyStatePartialMatrix(), and setTranslationalStatePartialFrameScalingFunctions().
inertiaTensorsForMultiplication_
std::vector< std::pair< int, std::function< Eigen::Matrix3d() > > > tudat::propagators::VariationalEquations::inertiaTensorsForMultiplication_ private
Definition at line 564 of file variationalEquations.h.
Referenced by getParameterPartialMatrix(), setBodyStatePartialMatrix(), and setRotationalStatePartialScalingFunctions().
parameterPartialList_
std::map< IntegratedStateType, std::vector< std::multimap< std::pair< int, int >, std::function< void(Eigen::Block< Eigen::MatrixXd >) > > > > tudat::propagators::VariationalEquations::parameterPartialList_ private
List of all functions returning current partial derivative w.r.t. a parameter. Map key denotes associated dynamics type w.r.t which partial is taken. The vector entries correspond to the entries in the outer vector of StateDerivativePartialsMaps in stateDerivativePartialList_. The multimaps inside the vector provide the functions (as values) adding the partials to a given matrix block and the start column and number of columns in matrix partial (as keys).
Definition at line 575 of file variationalEquations.h.
Referenced by getParameterPartialMatrix(), and setParameterPartialFunctionList().
functionIterator
std::multimap< std::pair< int, int >, std::function< void(Eigen::Block< Eigen::MatrixXd >) > >::iterator tudat::propagators::VariationalEquations::functionIterator private
Definition at line 579 of file variationalEquations.h.
Referenced by getParameterPartialMatrix().
stateDerivativeTypeIterator_
std::map< propagators::IntegratedStateType, orbit_determination::StateDerivativePartialsMap >::iterator tudat::propagators::VariationalEquations::stateDerivativeTypeIterator_ private
Definition at line 583 of file variationalEquations.h.
Referenced by clearPartials(), setStatePartialFunctionList(), and updatePartials().
dynamicalStatesToEstimate_
std::map< propagators::IntegratedStateType, std::vector< std::pair< std::string, std::string > > > tudat::propagators::VariationalEquations::dynamicalStatesToEstimate_ private
Definition at line 587 of file variationalEquations.h.
Referenced by setBodyStatePartialMatrix(), setStatePartialFunctionList(), and VariationalEquations().
numberOfParameterValues_
int tudat::propagators::VariationalEquations::numberOfParameterValues_ private
Definition at line 591 of file variationalEquations.h.
Referenced by evaluateVariationalEquations(), getBodyInitialStatePartialMatrix(), getNumberOfParameterValues(), getParameterPartialMatrix(), and VariationalEquations().
totalDynamicalStateSize_
int tudat::propagators::VariationalEquations::totalDynamicalStateSize_ private
Definition at line 594 of file variationalEquations.h.
Referenced by evaluateVariationalEquations(), getBodyInitialStatePartialMatrix(), getParameterPartialMatrix(), setBodyStatePartialMatrix(), and VariationalEquations().
couplingEntriesToSuppress_
int tudat::propagators::VariationalEquations::couplingEntriesToSuppress_ private
Definition at line 596 of file variationalEquations.h.
Referenced by getBodyInitialStatePartialMatrix(), and suppressParameterCoupling().
variationalMatrix_
Eigen::MatrixXd tudat::propagators::VariationalEquations::variationalMatrix_ private
Definition at line 599 of file variationalEquations.h.
Referenced by getBodyInitialStatePartialMatrix(), setBodyStatePartialMatrix(), and VariationalEquations().
variationalParameterMatrix_
Eigen::MatrixXd tudat::propagators::VariationalEquations::variationalParameterMatrix_ private
Definition at line 602 of file variationalEquations.h.
Referenced by getParameterPartialMatrix(), and VariationalEquations().
currentStatesPerTypeInConventionalRepresentation_
std::unordered_map< IntegratedStateType, Eigen::VectorXd > tudat::propagators::VariationalEquations::currentStatesPerTypeInConventionalRepresentation_ private
Definition at line 605 of file variationalEquations.h.
Referenced by setBodyStatePartialMatrix(), and updatePartials().
The documentation for this class was generated from the following files:
Astrodynamics/Propagators/variationalEquations.h
Astrodynamics/Propagators/variationalEquations.cpp