Tudat: tudat::shape_based_methods::BaseFunctionHodographicShaping Class Reference
tudat::shape_based_methods::BaseFunctionHodographicShaping Class Reference abstract
Base class for shaping functions to be used in the hodographic shaping method.
#include <baseFunctionsHodographicShaping.h>
Public Member Functions
BaseFunctionHodographicShaping ()
Default constructor.
virtual ~BaseFunctionHodographicShaping ()
Default destructor.
virtual double evaluateDerivative (const double independentVariable)=0
virtual double evaluateFunction (const double independentVariable)=0
virtual double evaluateIntegral (const double independentVariable)=0
Detailed Description
Definition at line 43 of file baseFunctionsHodographicShaping.h.
Constructor & Destructor Documentation
BaseFunctionHodographicShaping()
tudat::shape_based_methods::BaseFunctionHodographicShaping::BaseFunctionHodographicShaping () inline
Default constructor.
Definition at line 51 of file baseFunctionsHodographicShaping.h.
~BaseFunctionHodographicShaping()
virtual tudat::shape_based_methods::BaseFunctionHodographicShaping::~BaseFunctionHodographicShaping () inline virtual
Default destructor.
Definition at line 57 of file baseFunctionsHodographicShaping.h.
References evaluateDerivative(), evaluateFunction(), evaluateIntegral(), and tudat::propagators::independentVariable.
Member Function Documentation
evaluateFunction()
virtual double tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateFunction (const double independentVariable) pure virtual
Implemented in tudat::shape_based_methods::ScaledPowerCosineFunctionHodographicShaping, tudat::shape_based_methods::PowerCosineFunctionHodographicShaping, tudat::shape_based_methods::ScaledPowerSineFunctionHodographicShaping, tudat::shape_based_methods::PowerSineFunctionHodographicShaping, tudat::shape_based_methods::ScaledPowerFunctionHodographicShaping, tudat::shape_based_methods::PowerFunctionHodographicShaping, tudat::shape_based_methods::ScaledExponentialCosineFunctionHodographicShaping, tudat::shape_based_methods::ExponentialCosineFunctionHodographicShaping, tudat::shape_based_methods::ScaledExponentialSineFunctionHodographicShaping, tudat::shape_based_methods::ExponentialSineFunctionHodographicShaping, tudat::shape_based_methods::ScaledExponentialFunctionHodographicShaping, tudat::shape_based_methods::ExponentialFunctionHodographicShaping, tudat::shape_based_methods::CosineFunctionHodographicShaping, tudat::shape_based_methods::SineFunctionHodographicShaping, and tudat::shape_based_methods::ConstantFunctionHodographicShaping.
Referenced by ~BaseFunctionHodographicShaping(), tudat::shape_based_methods::CosineFunctionHodographicShaping::~CosineFunctionHodographicShaping(), tudat::shape_based_methods::ExponentialCosineFunctionHodographicShaping::~ExponentialCosineFunctionHodographicShaping(), tudat::shape_based_methods::ExponentialFunctionHodographicShaping::~ExponentialFunctionHodographicShaping(), tudat::shape_based_methods::ExponentialSineFunctionHodographicShaping::~ExponentialSineFunctionHodographicShaping(), tudat::shape_based_methods::PowerCosineFunctionHodographicShaping::~PowerCosineFunctionHodographicShaping(), tudat::shape_based_methods::PowerFunctionHodographicShaping::~PowerFunctionHodographicShaping(), tudat::shape_based_methods::PowerSineFunctionHodographicShaping::~PowerSineFunctionHodographicShaping(), tudat::shape_based_methods::ScaledExponentialCosineFunctionHodographicShaping::~ScaledExponentialCosineFunctionHodographicShaping(), tudat::shape_based_methods::ScaledExponentialFunctionHodographicShaping::~ScaledExponentialFunctionHodographicShaping(), tudat::shape_based_methods::ScaledExponentialSineFunctionHodographicShaping::~ScaledExponentialSineFunctionHodographicShaping(), tudat::shape_based_methods::ScaledPowerCosineFunctionHodographicShaping::~ScaledPowerCosineFunctionHodographicShaping(), tudat::shape_based_methods::ScaledPowerFunctionHodographicShaping::~ScaledPowerFunctionHodographicShaping(), tudat::shape_based_methods::ScaledPowerSineFunctionHodographicShaping::~ScaledPowerSineFunctionHodographicShaping(), and tudat::shape_based_methods::SineFunctionHodographicShaping::~SineFunctionHodographicShaping().
evaluateDerivative()
virtual double tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateDerivative (const double independentVariable) pure virtual
Implemented in tudat::shape_based_methods::ScaledPowerCosineFunctionHodographicShaping, tudat::shape_based_methods::PowerCosineFunctionHodographicShaping, tudat::shape_based_methods::ScaledPowerSineFunctionHodographicShaping, tudat::shape_based_methods::PowerSineFunctionHodographicShaping, tudat::shape_based_methods::ScaledPowerFunctionHodographicShaping, tudat::shape_based_methods::PowerFunctionHodographicShaping, tudat::shape_based_methods::ScaledExponentialCosineFunctionHodographicShaping, tudat::shape_based_methods::ExponentialCosineFunctionHodographicShaping, tudat::shape_based_methods::ScaledExponentialSineFunctionHodographicShaping, tudat::shape_based_methods::ExponentialSineFunctionHodographicShaping, tudat::shape_based_methods::ScaledExponentialFunctionHodographicShaping, tudat::shape_based_methods::ExponentialFunctionHodographicShaping, tudat::shape_based_methods::CosineFunctionHodographicShaping, tudat::shape_based_methods::SineFunctionHodographicShaping, and tudat::shape_based_methods::ConstantFunctionHodographicShaping.
Referenced by ~BaseFunctionHodographicShaping(), tudat::shape_based_methods::CosineFunctionHodographicShaping::~CosineFunctionHodographicShaping(), tudat::shape_based_methods::ExponentialCosineFunctionHodographicShaping::~ExponentialCosineFunctionHodographicShaping(), tudat::shape_based_methods::ExponentialFunctionHodographicShaping::~ExponentialFunctionHodographicShaping(), tudat::shape_based_methods::ExponentialSineFunctionHodographicShaping::~ExponentialSineFunctionHodographicShaping(), tudat::shape_based_methods::PowerCosineFunctionHodographicShaping::~PowerCosineFunctionHodographicShaping(), tudat::shape_based_methods::PowerFunctionHodographicShaping::~PowerFunctionHodographicShaping(), tudat::shape_based_methods::PowerSineFunctionHodographicShaping::~PowerSineFunctionHodographicShaping(), tudat::shape_based_methods::ScaledExponentialCosineFunctionHodographicShaping::~ScaledExponentialCosineFunctionHodographicShaping(), tudat::shape_based_methods::ScaledExponentialFunctionHodographicShaping::~ScaledExponentialFunctionHodographicShaping(), tudat::shape_based_methods::ScaledExponentialSineFunctionHodographicShaping::~ScaledExponentialSineFunctionHodographicShaping(), tudat::shape_based_methods::ScaledPowerCosineFunctionHodographicShaping::~ScaledPowerCosineFunctionHodographicShaping(), tudat::shape_based_methods::ScaledPowerFunctionHodographicShaping::~ScaledPowerFunctionHodographicShaping(), tudat::shape_based_methods::ScaledPowerSineFunctionHodographicShaping::~ScaledPowerSineFunctionHodographicShaping(), and tudat::shape_based_methods::SineFunctionHodographicShaping::~SineFunctionHodographicShaping().
evaluateIntegral()
virtual double tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateIntegral (const double independentVariable) pure virtual
Implemented in tudat::shape_based_methods::ScaledPowerCosineFunctionHodographicShaping, tudat::shape_based_methods::PowerCosineFunctionHodographicShaping, tudat::shape_based_methods::ScaledPowerSineFunctionHodographicShaping, tudat::shape_based_methods::PowerSineFunctionHodographicShaping, tudat::shape_based_methods::ScaledPowerFunctionHodographicShaping, tudat::shape_based_methods::PowerFunctionHodographicShaping, tudat::shape_based_methods::ScaledExponentialCosineFunctionHodographicShaping, tudat::shape_based_methods::ExponentialCosineFunctionHodographicShaping, tudat::shape_based_methods::ScaledExponentialSineFunctionHodographicShaping, tudat::shape_based_methods::ExponentialSineFunctionHodographicShaping, tudat::shape_based_methods::ScaledExponentialFunctionHodographicShaping, tudat::shape_based_methods::ExponentialFunctionHodographicShaping, tudat::shape_based_methods::CosineFunctionHodographicShaping, tudat::shape_based_methods::SineFunctionHodographicShaping, and tudat::shape_based_methods::ConstantFunctionHodographicShaping.
Referenced by ~BaseFunctionHodographicShaping(), tudat::shape_based_methods::CosineFunctionHodographicShaping::~CosineFunctionHodographicShaping(), tudat::shape_based_methods::ExponentialCosineFunctionHodographicShaping::~ExponentialCosineFunctionHodographicShaping(), tudat::shape_based_methods::ExponentialFunctionHodographicShaping::~ExponentialFunctionHodographicShaping(), tudat::shape_based_methods::ExponentialSineFunctionHodographicShaping::~ExponentialSineFunctionHodographicShaping(), tudat::shape_based_methods::PowerCosineFunctionHodographicShaping::~PowerCosineFunctionHodographicShaping(), tudat::shape_based_methods::PowerFunctionHodographicShaping::~PowerFunctionHodographicShaping(), tudat::shape_based_methods::PowerSineFunctionHodographicShaping::~PowerSineFunctionHodographicShaping(), tudat::shape_based_methods::ScaledExponentialCosineFunctionHodographicShaping::~ScaledExponentialCosineFunctionHodographicShaping(), tudat::shape_based_methods::ScaledExponentialFunctionHodographicShaping::~ScaledExponentialFunctionHodographicShaping(), tudat::shape_based_methods::ScaledExponentialSineFunctionHodographicShaping::~ScaledExponentialSineFunctionHodographicShaping(), tudat::shape_based_methods::ScaledPowerCosineFunctionHodographicShaping::~ScaledPowerCosineFunctionHodographicShaping(), tudat::shape_based_methods::ScaledPowerFunctionHodographicShaping::~ScaledPowerFunctionHodographicShaping(), tudat::shape_based_methods::ScaledPowerSineFunctionHodographicShaping::~ScaledPowerSineFunctionHodographicShaping(), and tudat::shape_based_methods::SineFunctionHodographicShaping::~SineFunctionHodographicShaping().
The documentation for this class was generated from the following file:
Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/baseFunctionsHodographicShaping.h