Tudat: tudat::shape_based_methods::PowerFunctionHodographicShaping Class Reference
tudat::shape_based_methods::PowerFunctionHodographicShaping Class Reference
Power function.
#include <baseFunctionsHodographicShaping.h>
Public Member Functions
PowerFunctionHodographicShaping (double exponent)
Constructor with the order of the power function as input.
~PowerFunctionHodographicShaping ()
Default destructor.
double evaluateDerivative (const double independentVariable)
double evaluateFunction (const double independentVariable)
Function, derivative, and integral of the power function.
double evaluateIntegral (const double independentVariable)
Public Member Functions inherited from tudat::shape_based_methods::BaseFunctionHodographicShaping
BaseFunctionHodographicShaping ()
Default constructor.
virtual ~BaseFunctionHodographicShaping ()
Default destructor.
Private Attributes
double exponent_
Detailed Description
Definition at line 345 of file baseFunctionsHodographicShaping.h.
Constructor & Destructor Documentation
PowerFunctionHodographicShaping()
tudat::shape_based_methods::PowerFunctionHodographicShaping::PowerFunctionHodographicShaping (double exponent) inline
Definition at line 350 of file baseFunctionsHodographicShaping.h.
~PowerFunctionHodographicShaping()
tudat::shape_based_methods::PowerFunctionHodographicShaping::~PowerFunctionHodographicShaping () inline
Definition at line 356 of file baseFunctionsHodographicShaping.h.
References tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateDerivative(), tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateFunction(), tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateIntegral(), and tudat::propagators::independentVariable.
Member Function Documentation
evaluateFunction()
double tudat::shape_based_methods::PowerFunctionHodographicShaping::evaluateFunction (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 193 of file baseFunctionsHodographicShaping.cpp.
evaluateDerivative()
double tudat::shape_based_methods::PowerFunctionHodographicShaping::evaluateDerivative (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 198 of file baseFunctionsHodographicShaping.cpp.
evaluateIntegral()
double tudat::shape_based_methods::PowerFunctionHodographicShaping::evaluateIntegral (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 203 of file baseFunctionsHodographicShaping.cpp.
Member Data Documentation
exponent_
double tudat::shape_based_methods::PowerFunctionHodographicShaping::exponent_ private
Definition at line 369 of file baseFunctionsHodographicShaping.h.
The documentation for this class was generated from the following files:
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/baseFunctionsHodographicShaping.h
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/baseFunctionsHodographicShaping.cpp