Tudat: tudat::shape_based_methods::CompositeFunctionHodographicShaping Class Reference
tudat::shape_based_methods::CompositeFunctionHodographicShaping Class Reference
#include <compositeFunctionHodographicShaping.h>
Public Member Functions
CompositeFunctionHodographicShaping (const std::vector< std::shared_ptr< BaseFunctionHodographicShaping > > &compositeFunctionComponents, const Eigen::VectorXd &compositeFunctionCoefficients)
Constructor.
~CompositeFunctionHodographicShaping ()
Default destructor.
double evaluateCompositeFunctionCurrentTime (const double independentVariable)
double evaluateCompositeFunctionDerivativeCurrentTime (const double independentVariable)
double evaluateCompositeFunctionIntegralCurrentTime (const double independentVariable)
double getComponentFunctionCurrentValue (const int componentIndex, const double currentTime)
double getComponentFunctionDerivativeCurrentTime (const int componentIndex, const double currentTime)
double getComponentFunctionIntegralCurrentTime (const int componentIndex, const double currentTime)
Eigen::VectorXd getCompositeFunctionCoefficients ()
Return coefficients.
int getNumberOfCompositeFunctionComponents ()
Returns number of composite function components.
void resetCompositeFunctionCoefficients (const Eigen::VectorXd &compositeFunctionCoefficients)
Reset coefficients.
Private Attributes
Eigen::VectorXd compositeFunctionCoefficients_
Vector of coefficients.
std::vector< std::shared_ptr< BaseFunctionHodographicShaping > > compositeFunctionComponents_
Detailed Description
Definition at line 25 of file compositeFunctionHodographicShaping.h.
Constructor & Destructor Documentation
CompositeFunctionHodographicShaping()
tudat::shape_based_methods::CompositeFunctionHodographicShaping::CompositeFunctionHodographicShaping (const std::vector< std::shared_ptr< BaseFunctionHodographicShaping > > & compositeFunctionComponents, const Eigen::VectorXd & compositeFunctionCoefficients) inline
Definition at line 30 of file compositeFunctionHodographicShaping.h.
~CompositeFunctionHodographicShaping()
tudat::shape_based_methods::CompositeFunctionHodographicShaping::~CompositeFunctionHodographicShaping () inline
Default destructor.
Definition at line 41 of file compositeFunctionHodographicShaping.h.
Member Function Documentation
getCompositeFunctionCoefficients()
Eigen::VectorXd tudat::shape_based_methods::CompositeFunctionHodographicShaping::getCompositeFunctionCoefficients () inline
Returns coefficients of composite function.
Definition at line 47 of file compositeFunctionHodographicShaping.h.
References compositeFunctionCoefficients_, and resetCompositeFunctionCoefficients().
resetCompositeFunctionCoefficients()
void tudat::shape_based_methods::CompositeFunctionHodographicShaping::resetCompositeFunctionCoefficients (const Eigen::VectorXd & compositeFunctionCoefficients)
Resets the coefficients of the composite function.
Definition at line 23 of file compositeFunctionHodographicShaping.cpp.
References compositeFunctionCoefficients_, and compositeFunctionComponents_.
Referenced by getCompositeFunctionCoefficients().
getNumberOfCompositeFunctionComponents()
int tudat::shape_based_methods::CompositeFunctionHodographicShaping::getNumberOfCompositeFunctionComponents () inline
Returns number of composite function components.
Definition at line 62 of file compositeFunctionHodographicShaping.h.
References compositeFunctionComponents_, evaluateCompositeFunctionCurrentTime(), evaluateCompositeFunctionDerivativeCurrentTime(), evaluateCompositeFunctionIntegralCurrentTime(), getComponentFunctionCurrentValue(), getComponentFunctionDerivativeCurrentTime(), getComponentFunctionIntegralCurrentTime(), and tudat::propagators::independentVariable.
evaluateCompositeFunctionCurrentTime()
double tudat::shape_based_methods::CompositeFunctionHodographicShaping::evaluateCompositeFunctionCurrentTime (const double independentVariable)
Definition at line 40 of file compositeFunctionHodographicShaping.cpp.
References compositeFunctionCoefficients_, and compositeFunctionComponents_.
Referenced by getNumberOfCompositeFunctionComponents().
evaluateCompositeFunctionDerivativeCurrentTime()
double tudat::shape_based_methods::CompositeFunctionHodographicShaping::evaluateCompositeFunctionDerivativeCurrentTime (const double independentVariable)
Definition at line 51 of file compositeFunctionHodographicShaping.cpp.
References compositeFunctionCoefficients_, and compositeFunctionComponents_.
Referenced by getNumberOfCompositeFunctionComponents().
evaluateCompositeFunctionIntegralCurrentTime()
double tudat::shape_based_methods::CompositeFunctionHodographicShaping::evaluateCompositeFunctionIntegralCurrentTime (const double independentVariable)
Definition at line 62 of file compositeFunctionHodographicShaping.cpp.
References compositeFunctionCoefficients_, and compositeFunctionComponents_.
Referenced by getNumberOfCompositeFunctionComponents().
getComponentFunctionCurrentValue()
double tudat::shape_based_methods::CompositeFunctionHodographicShaping::getComponentFunctionCurrentValue (const int componentIndex, const double currentTime)
Definition at line 80 of file compositeFunctionHodographicShaping.cpp.
References compositeFunctionComponents_.
Referenced by getNumberOfCompositeFunctionComponents().
getComponentFunctionDerivativeCurrentTime()
double tudat::shape_based_methods::CompositeFunctionHodographicShaping::getComponentFunctionDerivativeCurrentTime (const int componentIndex, const double currentTime)
Definition at line 73 of file compositeFunctionHodographicShaping.cpp.
References compositeFunctionComponents_.
Referenced by getNumberOfCompositeFunctionComponents().
getComponentFunctionIntegralCurrentTime()
double tudat::shape_based_methods::CompositeFunctionHodographicShaping::getComponentFunctionIntegralCurrentTime (const int componentIndex, const double currentTime)
Definition at line 87 of file compositeFunctionHodographicShaping.cpp.
References compositeFunctionComponents_.
Referenced by getNumberOfCompositeFunctionComponents().
Member Data Documentation
compositeFunctionComponents_
std::vector< std::shared_ptr< BaseFunctionHodographicShaping > > tudat::shape_based_methods::CompositeFunctionHodographicShaping::compositeFunctionComponents_ private
Definition at line 87 of file compositeFunctionHodographicShaping.h.
Referenced by evaluateCompositeFunctionCurrentTime(), evaluateCompositeFunctionDerivativeCurrentTime(), evaluateCompositeFunctionIntegralCurrentTime(), getComponentFunctionCurrentValue(), getComponentFunctionDerivativeCurrentTime(), getComponentFunctionIntegralCurrentTime(), getNumberOfCompositeFunctionComponents(), and resetCompositeFunctionCoefficients().
compositeFunctionCoefficients_
Eigen::VectorXd tudat::shape_based_methods::CompositeFunctionHodographicShaping::compositeFunctionCoefficients_ private
VectorXd containing coefficients corresponding to components of the composite function.
Definition at line 93 of file compositeFunctionHodographicShaping.h.
Referenced by evaluateCompositeFunctionCurrentTime(), evaluateCompositeFunctionDerivativeCurrentTime(), evaluateCompositeFunctionIntegralCurrentTime(), getCompositeFunctionCoefficients(), and resetCompositeFunctionCoefficients().
The documentation for this class was generated from the following files:
Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/compositeFunctionHodographicShaping.h
Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/compositeFunctionHodographicShaping.cpp