Tudat: tudat::low_thrust_trajectories::LowThrustLeg Class Reference
tudat::low_thrust_trajectories::LowThrustLeg Class Reference abstract
Low-thrust leg base class.
#include <lowThrustLeg.h>
Public Member Functions
LowThrustLeg (const Eigen::Vector6d &stateAtDeparture, const Eigen::Vector6d &stateAtArrival, const double timeOfFlight, const double initialMass, const bool legModelIsForceBased)
Constructor with immediate definition of parameters.
virtual ~LowThrustLeg ()
double computeCurrentMass (const double independentVariable, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute current mass of the spacecraft.
virtual Eigen::Vector6d computeCurrentStateVector (const double currentTime)=0
Compute current cartesian state.
Eigen::Vector3d computeCurrentThrustAcceleration (double time, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute current thrust vector.
virtual Eigen::Vector3d computeCurrentThrustAccelerationDirection (double currentTime, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)=0
Compute direction thrust acceleration in cartesian coordinates.
virtual double computeCurrentThrustAccelerationMagnitude (double currentTime, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)=0
Compute magnitude thrust acceleration.
virtual Eigen::Vector3d computeCurrentThrustForce (double time, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)=0
Compute current thrust vector.
virtual double computeDeltaV ()=0
Compute total deltaV.
void computeSemiAnalyticalAndFullPropagation (const simulation_setup::NamedBodyMap &bodyMapTest, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const std::pair< std::shared_ptr< propagators::PropagatorSettings< double > >, std::shared_ptr< propagators::PropagatorSettings< double > > > &propagatorSettings, std::map< double, Eigen::VectorXd > &fullPropagationResults, std::map< double, Eigen::Vector6d > &semiAnalyticalResults, std::map< double, Eigen::VectorXd > &dependentVariablesHistory)
Full propagation.
virtual double convertIndependentVariableToTime (const double independentVariable)=0
Convert independent variable to time.
virtual double convertTimeToIndependentVariable (const double time)=0
Convert time to independent variable.
std::pair< std::shared_ptr< propagators::PropagatorSettings< double > >, std::shared_ptr< propagators::PropagatorSettings< double > > > createLowThrustPropagatorSettings (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::string &centralBody, const std::function< double(const double) > specificImpulseFunction, const basic_astrodynamics::AccelerationMap perturbingAccelerationsMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > &integratorSettings, const std::shared_ptr< propagators::DependentVariableSaveSettings > &dependentVariablesToSave)
Define appropriate propagator settings for the full propagation.
virtual std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > createLowThrustTranslationalStatePropagatorSettings (const std::string &bodyToPropagate, const std::string &centralBody, const basic_astrodynamics::AccelerationMap &accelerationModelMap, const std::shared_ptr< propagators::DependentVariableSaveSettings > dependentVariablesToSave)=0
Define appropriate propagator settings for the full propagation.
std::shared_ptr< propulsion::ThrustAcceleration > getLowThrustAccelerationModel (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const double timeOffset=0.0)
Retrieve acceleration model (thrust).
std::shared_ptr< simulation_setup::ThrustAccelerationSettings > getLowThrustAccelerationSettings (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const double timeOffset=0.0)
Retrieve acceleration model (thrust).
void getMassProfile (const std::vector< double > &epochsVector, std::map< double, Eigen::VectorXd > &massProfile, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Return mass profile.
virtual void getThrustAccelerationProfile (std::vector< double > &epochsVector, std::map< double, Eigen::VectorXd > &thrustAccelerationProfile, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Return thrust acceleration profile.
virtual void getThrustForceProfile (std::vector< double > &epochsVector, std::map< double, Eigen::VectorXd > &thrustProfile, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Return thrust profile.
virtual void getTrajectory (std::vector< double > &epochsVector, std::map< double, Eigen::Vector6d > &propagatedTrajectory)=0
Compute state history.
virtual basic_astrodynamics::AccelerationMap retrieveLowThrustAccelerationMap (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::string &centralBody, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)=0
Retrieve acceleration map (thrust and central gravity accelerations).
Protected Member Functions
double computeCurrentMass (const double timeInitialEpoch, const double timeFinalEpoch, const double massInitialEpoch, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute current mass of the spacecraft between two epochs.
Protected Attributes
double initialMass_
bool legModelIsForceBased_
Eigen::Vector6d stateAtArrival_
Cartesian state at arrival.
Eigen::Vector6d stateAtDeparture_
Cartesian state at departure.
double timeOfFlight_
Time of flight of the trajectory leg.
Detailed Description
Definition at line 31 of file lowThrustLeg.h.
Constructor & Destructor Documentation
LowThrustLeg()
tudat::low_thrust_trajectories::LowThrustLeg::LowThrustLeg (const Eigen::Vector6d & stateAtDeparture, const Eigen::Vector6d & stateAtArrival, const double timeOfFlight, const double initialMass, const bool legModelIsForceBased) inline
Constructor, sets objects and functions from which relevant environment and state variables are retrieved.
Parameters
departureBodyPosition location of the departure body.
arrivalBodyPosition position of the target body.
timeOfFlight Length of the leg.
departureBodyVelocity velocity of the departure body.
centralBodyGravitationalParameter gravitational parameter of the central body (most cases the Sun).
Definition at line 44 of file lowThrustLeg.h.
~LowThrustLeg()
virtual tudat::low_thrust_trajectories::LowThrustLeg::~LowThrustLeg () inline virtual
Definition at line 52 of file lowThrustLeg.h.
References computeCurrentMass(), computeCurrentStateVector(), computeCurrentThrustAcceleration(), computeCurrentThrustAccelerationDirection(), computeCurrentThrustAccelerationMagnitude(), computeCurrentThrustForce(), computeDeltaV(), computeSemiAnalyticalAndFullPropagation(), convertIndependentVariableToTime(), convertTimeToIndependentVariable(), createLowThrustPropagatorSettings(), createLowThrustTranslationalStatePropagatorSettings(), getLowThrustAccelerationModel(), getLowThrustAccelerationSettings(), getMassProfile(), getThrustAccelerationProfile(), getThrustForceProfile(), getTrajectory(), tudat::propagators::independentVariable, and retrieveLowThrustAccelerationMap().
Member Function Documentation
convertTimeToIndependentVariable()
virtual double tudat::low_thrust_trajectories::LowThrustLeg::convertTimeToIndependentVariable (const double time) pure virtual
Implemented in tudat::low_thrust_trajectories::SimsFlanagan, tudat::low_thrust_trajectories::HybridMethod, tudat::shape_based_methods::HodographicShaping, and tudat::shape_based_methods::SphericalShaping.
Referenced by computeCurrentThrustAcceleration(), tudat::shape_based_methods::ShapeBasedMethod::computeCurrentThrustForce(), tudat::shape_based_methods::ShapeBasedMethod::createLowThrustTranslationalStatePropagatorSettings(), getLowThrustAccelerationSettings(), tudat::shape_based_methods::ShapeBasedMethod::getThrustForceProfile(), tudat::shape_based_methods::ShapeBasedMethod::getTrajectory(), and ~LowThrustLeg().
convertIndependentVariableToTime()
virtual double tudat::low_thrust_trajectories::LowThrustLeg::convertIndependentVariableToTime (const double independentVariable) pure virtual
Implemented in tudat::low_thrust_trajectories::SimsFlanagan, tudat::low_thrust_trajectories::HybridMethod, tudat::shape_based_methods::HodographicShaping, and tudat::shape_based_methods::SphericalShaping.
Referenced by ~LowThrustLeg().
computeCurrentThrustAccelerationDirection()
virtual Eigen::Vector3d tudat::low_thrust_trajectories::LowThrustLeg::computeCurrentThrustAccelerationDirection (double currentTime, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings) pure virtual
Implemented in tudat::shape_based_methods::SphericalShaping, tudat::low_thrust_trajectories::SimsFlanagan, tudat::shape_based_methods::HodographicShaping, and tudat::low_thrust_trajectories::HybridMethod.
Referenced by computeCurrentThrustAcceleration(), tudat::shape_based_methods::ShapeBasedMethod::computeCurrentThrustForce(), getLowThrustAccelerationSettings(), tudat::shape_based_methods::ShapeBasedMethod::getThrustForceProfile(), and ~LowThrustLeg().
computeCurrentThrustAccelerationMagnitude()
virtual double tudat::low_thrust_trajectories::LowThrustLeg::computeCurrentThrustAccelerationMagnitude (double currentTime, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings) pure virtual
Implemented in tudat::low_thrust_trajectories::SimsFlanagan, tudat::shape_based_methods::SphericalShaping, tudat::low_thrust_trajectories::HybridMethod, and tudat::shape_based_methods::HodographicShaping.
Referenced by computeCurrentThrustAcceleration(), tudat::shape_based_methods::ShapeBasedMethod::computeCurrentThrustForce(), getLowThrustAccelerationSettings(), tudat::shape_based_methods::ShapeBasedMethod::getThrustForceProfile(), and ~LowThrustLeg().
computeCurrentStateVector()
virtual Eigen::Vector6d tudat::low_thrust_trajectories::LowThrustLeg::computeCurrentStateVector (const double currentTime) pure virtual
Implemented in tudat::low_thrust_trajectories::SimsFlanagan, tudat::low_thrust_trajectories::HybridMethod, tudat::shape_based_methods::HodographicShaping, and tudat::shape_based_methods::SphericalShaping.
Referenced by tudat::shape_based_methods::ShapeBasedMethod::createLowThrustTranslationalStatePropagatorSettings(), tudat::shape_based_methods::ShapeBasedMethod::getTrajectory(), and ~LowThrustLeg().
getTrajectory()
virtual void tudat::low_thrust_trajectories::LowThrustLeg::getTrajectory (std::vector< double > & epochsVector, std::map< double, Eigen::Vector6d > & propagatedTrajectory) pure virtual
Implemented in tudat::low_thrust_trajectories::SimsFlanagan, tudat::low_thrust_trajectories::HybridMethod, and tudat::shape_based_methods::ShapeBasedMethod.
Referenced by computeSemiAnalyticalAndFullPropagation(), and ~LowThrustLeg().
computeCurrentMass() [1/2]
double tudat::low_thrust_trajectories::LowThrustLeg::computeCurrentMass (const double independentVariable, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Definition at line 153 of file lowThrustLeg.cpp.
References initialMass_.
Referenced by tudat::low_thrust_trajectories::HybridMethod::computeCurrentThrustAccelerationMagnitude(), tudat::shape_based_methods::ShapeBasedMethod::computeCurrentThrustForce(), createLowThrustPropagatorSettings(), getMassProfile(), and ~LowThrustLeg().
getMassProfile()
void tudat::low_thrust_trajectories::LowThrustLeg::getMassProfile (const std::vector< double > & epochsVector, std::map< double, Eigen::VectorXd > & massProfile, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Definition at line 161 of file lowThrustLeg.cpp.
References computeCurrentMass(), and initialMass_.
Referenced by tudat::low_thrust_trajectories::SimsFlanagan::computeCurrentThrustAccelerationMagnitude(), tudat::low_thrust_trajectories::HybridMethod::getThrustAccelerationProfile(), tudat::low_thrust_trajectories::SimsFlanagan::getThrustAccelerationProfile(), tudat::shape_based_methods::ShapeBasedMethod::getThrustForceProfile(), and ~LowThrustLeg().
getLowThrustAccelerationSettings()
std::shared_ptr< simulation_setup::ThrustAccelerationSettings > tudat::low_thrust_trajectories::LowThrustLeg::getLowThrustAccelerationSettings (const simulation_setup::NamedBodyMap & bodyMapTest, const std::string & bodyToPropagate, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const double timeOffset = 0.0)
Definition at line 20 of file lowThrustLeg.cpp.
References computeCurrentThrustAccelerationDirection(), computeCurrentThrustAccelerationMagnitude(), computeCurrentThrustForce(), convertTimeToIndependentVariable(), and legModelIsForceBased_.
Referenced by getLowThrustAccelerationModel(), and ~LowThrustLeg().
getLowThrustAccelerationModel()
std::shared_ptr< propulsion::ThrustAcceleration > tudat::low_thrust_trajectories::LowThrustLeg::getLowThrustAccelerationModel (const simulation_setup::NamedBodyMap & bodyMapTest, const std::string & bodyToPropagate, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const double timeOffset = 0.0)
Definition at line 88 of file lowThrustLeg.cpp.
References tudat::simulation_setup::createThrustAcceleratioModel(), and getLowThrustAccelerationSettings().
Referenced by computeCurrentMass(), tudat::shape_based_methods::ShapeBasedMethod::retrieveLowThrustAccelerationMap(), and ~LowThrustLeg().
retrieveLowThrustAccelerationMap()
virtual basic_astrodynamics::AccelerationMap tudat::low_thrust_trajectories::LowThrustLeg::retrieveLowThrustAccelerationMap (const simulation_setup::NamedBodyMap & bodyMapTest, const std::string & bodyToPropagate, const std::string & centralBody, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings) pure virtual
Implemented in tudat::low_thrust_trajectories::SimsFlanagan, tudat::low_thrust_trajectories::HybridMethod, and tudat::shape_based_methods::ShapeBasedMethod.
Referenced by createLowThrustPropagatorSettings(), and ~LowThrustLeg().
computeCurrentThrustForce()
virtual Eigen::Vector3d tudat::low_thrust_trajectories::LowThrustLeg::computeCurrentThrustForce (double time, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings) pure virtual
Implemented in tudat::low_thrust_trajectories::SimsFlanagan, tudat::low_thrust_trajectories::HybridMethod, and tudat::shape_based_methods::ShapeBasedMethod.
Referenced by getLowThrustAccelerationSettings(), getThrustForceProfile(), and ~LowThrustLeg().
getThrustForceProfile()
void tudat::low_thrust_trajectories::LowThrustLeg::getThrustForceProfile (std::vector< double > & epochsVector, std::map< double, Eigen::VectorXd > & thrustProfile, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings) virtual
Reimplemented in tudat::low_thrust_trajectories::HybridMethod, and tudat::shape_based_methods::ShapeBasedMethod.
Definition at line 198 of file lowThrustLeg.cpp.
References computeCurrentThrustForce().
Referenced by tudat::low_thrust_trajectories::SimsFlanagan::getThrustAccelerationProfile(), and ~LowThrustLeg().
computeCurrentThrustAcceleration()
Eigen::Vector3d tudat::low_thrust_trajectories::LowThrustLeg::computeCurrentThrustAcceleration (double time, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Definition at line 221 of file lowThrustLeg.cpp.
References computeCurrentThrustAccelerationDirection(), computeCurrentThrustAccelerationMagnitude(), convertTimeToIndependentVariable(), and getThrustAccelerationProfile().
Referenced by getThrustAccelerationProfile(), and ~LowThrustLeg().
getThrustAccelerationProfile()
void tudat::low_thrust_trajectories::LowThrustLeg::getThrustAccelerationProfile (std::vector< double > & epochsVector, std::map< double, Eigen::VectorXd > & thrustAccelerationProfile, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings) virtual
Reimplemented in tudat::low_thrust_trajectories::SimsFlanagan, and tudat::low_thrust_trajectories::HybridMethod.
Definition at line 232 of file lowThrustLeg.cpp.
References computeCurrentThrustAcceleration().
Referenced by computeCurrentThrustAcceleration(), and ~LowThrustLeg().
computeDeltaV()
virtual double tudat::low_thrust_trajectories::LowThrustLeg::computeDeltaV () pure virtual
Implemented in tudat::low_thrust_trajectories::SimsFlanagan, tudat::low_thrust_trajectories::HybridMethod, tudat::shape_based_methods::HodographicShaping, and tudat::shape_based_methods::SphericalShaping.
Referenced by ~LowThrustLeg().
computeSemiAnalyticalAndFullPropagation()
void tudat::low_thrust_trajectories::LowThrustLeg::computeSemiAnalyticalAndFullPropagation (const simulation_setup::NamedBodyMap & bodyMapTest, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const std::pair< std::shared_ptr< propagators::PropagatorSettings< double > >, std::shared_ptr< propagators::PropagatorSettings< double > > > & propagatorSettings, std::map< double, Eigen::VectorXd > & fullPropagationResults, std::map< double, Eigen::Vector6d > & semiAnalyticalResults, std::map< double, Eigen::VectorXd > & dependentVariablesHistory)
Definition at line 257 of file lowThrustLeg.cpp.
References tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getDependentVariableHistory(), tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getEquationsOfMotionNumericalSolution(), getTrajectory(), and timeOfFlight_.
Referenced by ~LowThrustLeg().
createLowThrustPropagatorSettings()
std::pair< std::shared_ptr< propagators::PropagatorSettings< double > >, std::shared_ptr< propagators::PropagatorSettings< double > > > tudat::low_thrust_trajectories::LowThrustLeg::createLowThrustPropagatorSettings (const simulation_setup::NamedBodyMap & bodyMapTest, const std::string & bodyToPropagate, const std::string & centralBody, const std::function< double(const double) > specificImpulseFunction, const basic_astrodynamics::AccelerationMap perturbingAccelerationsMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > & integratorSettings, const std::shared_ptr< propagators::DependentVariableSaveSettings > & dependentVariablesToSave)
Definition at line 323 of file lowThrustLeg.cpp.
References computeCurrentMass(), createLowThrustTranslationalStatePropagatorSettings(), tudat::simulation_setup::createMassRateModel(), initialMass_, retrieveLowThrustAccelerationMap(), and timeOfFlight_.
Referenced by ~LowThrustLeg().
createLowThrustTranslationalStatePropagatorSettings()
virtual std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > tudat::low_thrust_trajectories::LowThrustLeg::createLowThrustTranslationalStatePropagatorSettings (const std::string & bodyToPropagate, const std::string & centralBody, const basic_astrodynamics::AccelerationMap & accelerationModelMap, const std::shared_ptr< propagators::DependentVariableSaveSettings > dependentVariablesToSave) pure virtual
Implemented in tudat::low_thrust_trajectories::SimsFlanagan, and tudat::shape_based_methods::ShapeBasedMethod.
Referenced by createLowThrustPropagatorSettings(), and ~LowThrustLeg().
computeCurrentMass() [2/2]
double tudat::low_thrust_trajectories::LowThrustLeg::computeCurrentMass (const double timeInitialEpoch, const double timeFinalEpoch, const double massInitialEpoch, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings) protected
Definition at line 108 of file lowThrustLeg.cpp.
References tudat::simulation_setup::createMassRateModel(), tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getEquationsOfMotionNumericalSolution(), and getLowThrustAccelerationModel().
Member Data Documentation
stateAtDeparture_
Eigen::Vector6d tudat::low_thrust_trajectories::LowThrustLeg::stateAtDeparture_ protected
Definition at line 175 of file lowThrustLeg.h.
Referenced by tudat::shape_based_methods::HodographicShaping::computeCurrentPolarAngle(), tudat::low_thrust_trajectories::HybridMethod::computeCurrentStateVector(), tudat::low_thrust_trajectories::SimsFlanagan::createLowThrustTranslationalStatePropagatorSettings(), tudat::shape_based_methods::HodographicShaping::HodographicShaping(), tudat::low_thrust_trajectories::HybridMethod::HybridMethod(), tudat::low_thrust_trajectories::HybridMethod::performOptimisation(), tudat::low_thrust_trajectories::SimsFlanagan::performOptimisation(), tudat::low_thrust_trajectories::SimsFlanagan::SimsFlanagan(), and tudat::shape_based_methods::SphericalShaping::SphericalShaping().
stateAtArrival_
Eigen::Vector6d tudat::low_thrust_trajectories::LowThrustLeg::stateAtArrival_ protected
Definition at line 178 of file lowThrustLeg.h.
Referenced by tudat::low_thrust_trajectories::SimsFlanagan::createLowThrustTranslationalStatePropagatorSettings(), tudat::shape_based_methods::HodographicShaping::HodographicShaping(), tudat::low_thrust_trajectories::HybridMethod::HybridMethod(), tudat::low_thrust_trajectories::HybridMethod::performOptimisation(), tudat::low_thrust_trajectories::SimsFlanagan::performOptimisation(), tudat::low_thrust_trajectories::SimsFlanagan::SimsFlanagan(), and tudat::shape_based_methods::SphericalShaping::SphericalShaping().
timeOfFlight_
double tudat::low_thrust_trajectories::LowThrustLeg::timeOfFlight_ protected
Definition at line 181 of file lowThrustLeg.h.
Referenced by tudat::shape_based_methods::HodographicShaping::computeDeltaV(), tudat::shape_based_methods::HodographicShaping::computeInverseMatrixNormalBoundaries(), tudat::shape_based_methods::HodographicShaping::computeInverseMatrixRadialOrAxialBoundaries(), computeSemiAnalyticalAndFullPropagation(), tudat::shape_based_methods::HodographicShaping::computeThirdFixedCoefficientAxialVelocityFromFinalPolarAngle(), createLowThrustPropagatorSettings(), tudat::shape_based_methods::ShapeBasedMethod::createLowThrustTranslationalStatePropagatorSettings(), tudat::low_thrust_trajectories::HybridMethod::createLowThrustTranslationalStatePropagatorSettings(), tudat::low_thrust_trajectories::SimsFlanagan::createLowThrustTranslationalStatePropagatorSettings(), tudat::shape_based_methods::HodographicShaping::getFinalValueInpendentVariable(), tudat::shape_based_methods::SphericalShaping::getNormalizedRequiredTimeOfFlight(), tudat::low_thrust_trajectories::HybridMethod::HybridMethod(), tudat::low_thrust_trajectories::HybridMethod::performOptimisation(), tudat::low_thrust_trajectories::SimsFlanagan::performOptimisation(), tudat::shape_based_methods::HodographicShaping::satisfyAxialBoundaryConditions(), tudat::shape_based_methods::HodographicShaping::satisfyNormalBoundaryConditions(), tudat::shape_based_methods::HodographicShaping::satisfyRadialBoundaryConditions(), and tudat::low_thrust_trajectories::SimsFlanagan::SimsFlanagan().
initialMass_
double tudat::low_thrust_trajectories::LowThrustLeg::initialMass_ protected
Definition at line 183 of file lowThrustLeg.h.
Referenced by computeCurrentMass(), tudat::shape_based_methods::ShapeBasedMethod::computeCurrentThrustForce(), createLowThrustPropagatorSettings(), getMassProfile(), tudat::low_thrust_trajectories::SimsFlanagan::performOptimisation(), and tudat::low_thrust_trajectories::SimsFlanagan::SimsFlanagan().
legModelIsForceBased_
bool tudat::low_thrust_trajectories::LowThrustLeg::legModelIsForceBased_ protected
Definition at line 185 of file lowThrustLeg.h.
Referenced by getLowThrustAccelerationSettings().
The documentation for this class was generated from the following files:
lowThrustLeg.h
lowThrustLeg.cpp