Tudat: tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping Class Reference
tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping Class Reference
#include <compositeFunctionSphericalShaping.h>
Public Member Functions
CompositeElevationFunctionSphericalShaping (Eigen::VectorXd &compositeFunctionCoefficients)
Constructor.
~CompositeElevationFunctionSphericalShaping ()
Default destructor.
double evaluateCompositeFunction (const double independentVariable)
double evaluateCompositeFunctionFirstDerivative (const double independentVariable)
double evaluateCompositeFunctionSecondDerivative (const double independentVariable)
double evaluateCompositeFunctionThirdDerivative (const double independentVariable)
double getComponentFunctionCurrentValue (const int componentIndex, const double currentTime)
double getComponentFunctionFirstDerivative (const int componentIndex, const double currentTime)
double getComponentFunctionSecondDerivative (const int componentIndex, const double currentTime)
double getComponentFunctionThirdDerivative (const int componentIndex, const double currentTime)
Eigen::VectorXd getCompositeFunctionCoefficients ()
Return coefficients.
void resetCompositeFunctionCoefficients (const Eigen::VectorXd &compositeFunctionCoefficients)
Reset coefficients.
Public Member Functions inherited from tudat::shape_based_methods::CompositeFunctionSphericalShaping
CompositeFunctionSphericalShaping ()
Constructor.
~CompositeFunctionSphericalShaping ()
Default destructor.
double evaluateCompositeFunction (const double independentVariable)
double evaluateCompositeFunctionFirstDerivative (const double independentVariable)
double evaluateCompositeFunctionSecondDerivative (const double independentVariable)
double evaluateCompositeFunctionThirdDerivative (const double independentVariable)
double getComponentFunctionCurrentValue (const int componentIndex, const double currentTime)
double getComponentFunctionFirstDerivative (const int componentIndex, const double currentTime)
double getComponentFunctionSecondDerivative (const int componentIndex, const double currentTime)
double getComponentFunctionThirdDerivative (const int componentIndex, const double currentTime)
std::shared_ptr< BaseFunctionSphericalShaping > getCompositeComponent (int indexComponent)
std::vector< std::shared_ptr< BaseFunctionSphericalShaping > > getCompositeComponents ()
Eigen::VectorXd getCompositeFunctionCoefficients ()
Return coefficients.
void resetCompositeFunctionCoefficients (const Eigen::VectorXd &compositeFunctionCoefficients)
Reset coefficients.
Private Attributes
Eigen::VectorXd compositeFunctionCoefficients_
Vector of coefficients.
std::vector< std::shared_ptr< BaseFunctionSphericalShaping > > compositeFunctionComponents_
Detailed Description
Definition at line 181 of file compositeFunctionSphericalShaping.h.
Constructor & Destructor Documentation
CompositeElevationFunctionSphericalShaping()
tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::CompositeElevationFunctionSphericalShaping (Eigen::VectorXd & compositeFunctionCoefficients) inline
Definition at line 186 of file compositeFunctionSphericalShaping.h.
References tudat::shape_based_methods::CompositeFunctionSphericalShaping::compositeFunctionCoefficients_, tudat::shape_based_methods::CompositeFunctionSphericalShaping::compositeFunctionComponents_, tudat::shape_based_methods::cosineSphericalShaping, tudat::shape_based_methods::createBaseFunctionSphericalShaping(), tudat::shape_based_methods::powerCosineSphericalShaping, tudat::shape_based_methods::powerSineSphericalShaping, and tudat::shape_based_methods::sineSphericalShaping.
~CompositeElevationFunctionSphericalShaping()
tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::~CompositeElevationFunctionSphericalShaping () inline
Default destructor.
Definition at line 204 of file compositeFunctionSphericalShaping.h.
Member Function Documentation
getCompositeFunctionCoefficients()
Eigen::VectorXd tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::getCompositeFunctionCoefficients () inline
Returns coefficients of composite function.
Definition at line 210 of file compositeFunctionSphericalShaping.h.
References tudat::shape_based_methods::CompositeFunctionSphericalShaping::compositeFunctionCoefficients_, tudat::shape_based_methods::CompositeFunctionSphericalShaping::evaluateCompositeFunction(), tudat::shape_based_methods::CompositeFunctionSphericalShaping::evaluateCompositeFunctionFirstDerivative(), tudat::shape_based_methods::CompositeFunctionSphericalShaping::evaluateCompositeFunctionSecondDerivative(), tudat::shape_based_methods::CompositeFunctionSphericalShaping::evaluateCompositeFunctionThirdDerivative(), tudat::shape_based_methods::CompositeFunctionSphericalShaping::getComponentFunctionCurrentValue(), tudat::shape_based_methods::CompositeFunctionSphericalShaping::getComponentFunctionFirstDerivative(), tudat::shape_based_methods::CompositeFunctionSphericalShaping::getComponentFunctionSecondDerivative(), tudat::shape_based_methods::CompositeFunctionSphericalShaping::getComponentFunctionThirdDerivative(), tudat::propagators::independentVariable, and tudat::shape_based_methods::CompositeFunctionSphericalShaping::resetCompositeFunctionCoefficients().
resetCompositeFunctionCoefficients()
void tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::resetCompositeFunctionCoefficients (const Eigen::VectorXd & compositeFunctionCoefficients)
Resets the coefficients of the composite function.
Definition at line 139 of file compositeFunctionSphericalShaping.cpp.
References tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::compositeFunctionCoefficients_, and tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::compositeFunctionComponents_.
evaluateCompositeFunction()
double tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::evaluateCompositeFunction (const double independentVariable)
Definition at line 156 of file compositeFunctionSphericalShaping.cpp.
References tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::compositeFunctionCoefficients_, and tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::compositeFunctionComponents_.
evaluateCompositeFunctionFirstDerivative()
double tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::evaluateCompositeFunctionFirstDerivative (const double independentVariable)
Definition at line 167 of file compositeFunctionSphericalShaping.cpp.
References tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::compositeFunctionCoefficients_, and tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::compositeFunctionComponents_.
evaluateCompositeFunctionSecondDerivative()
double tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::evaluateCompositeFunctionSecondDerivative (const double independentVariable)
Definition at line 178 of file compositeFunctionSphericalShaping.cpp.
References tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::compositeFunctionCoefficients_, and tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::compositeFunctionComponents_.
evaluateCompositeFunctionThirdDerivative()
double tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::evaluateCompositeFunctionThirdDerivative (const double independentVariable)
Definition at line 188 of file compositeFunctionSphericalShaping.cpp.
References tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::compositeFunctionCoefficients_, and tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::compositeFunctionComponents_.
getComponentFunctionCurrentValue()
double tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::getComponentFunctionCurrentValue (const int componentIndex, const double currentTime)
Definition at line 198 of file compositeFunctionSphericalShaping.cpp.
References tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::compositeFunctionComponents_.
getComponentFunctionFirstDerivative()
double tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::getComponentFunctionFirstDerivative (const int componentIndex, const double currentTime)
Definition at line 205 of file compositeFunctionSphericalShaping.cpp.
References tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::compositeFunctionComponents_.
getComponentFunctionSecondDerivative()
double tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::getComponentFunctionSecondDerivative (const int componentIndex, const double currentTime)
Definition at line 211 of file compositeFunctionSphericalShaping.cpp.
References tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::compositeFunctionComponents_.
getComponentFunctionThirdDerivative()
double tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::getComponentFunctionThirdDerivative (const int componentIndex, const double currentTime)
Definition at line 217 of file compositeFunctionSphericalShaping.cpp.
References tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::compositeFunctionComponents_.
Member Data Documentation
compositeFunctionComponents_
std::vector< std::shared_ptr< BaseFunctionSphericalShaping > > tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::compositeFunctionComponents_ private
Definition at line 247 of file compositeFunctionSphericalShaping.h.
compositeFunctionCoefficients_
Eigen::VectorXd tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::compositeFunctionCoefficients_ private
VectorXd containing coefficients corresponding to components of the composite function.
Definition at line 253 of file compositeFunctionSphericalShaping.h.
The documentation for this class was generated from the following files:
Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/compositeFunctionSphericalShaping.h
Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/compositeFunctionSphericalShaping.cpp