Tudat: tudat::electro_magnetism::PanelledRadiationPressureAcceleration Class Reference
tudat::electro_magnetism::PanelledRadiationPressureAcceleration Class Reference
Class for calculating the radiation pressure acceleration on a panelled body.
#include <panelledRadiationPressure.h>
Public Member Functions
PanelledRadiationPressureAcceleration (const std::function< Eigen::Vector3d() > sourcePositionFunction, const std::function< Eigen::Vector3d() > acceleratedBodyPositionFunction, const std::vector< std::function< double() > > &panelEmissivittyFunctions, const std::vector< std::function< double() > > &panelDiffuseReflectionCoefficientFunctions, const std::vector< std::function< Eigen::Vector3d() > > &panelSurfaceNormalFunctions, const std::vector< std::function< double() > > &panelAreaFunctions, const std::function< double() > radiationPressureFunction, const std::function< double() > massFunction)
Constructor for setting up the acceleration model, with separate input variables for all required data.
PanelledRadiationPressureAcceleration (const std::shared_ptr< PanelledRadiationPressureInterface > radiationPressureInterface, const std::function< double() > massFunction)
Constructor for setting up the acceleration model, with input RadiationPressureInterface (and massFunction)
Eigen::Vector3d getAcceleration ()
Get radiation pressure acceleration.
double getCurrentDistanceToSource ()
Returns the current distance from the accelerated body to the source body.
double getCurrentMass ()
Returns the current mass of the accelerated body.
Eigen::Vector3d getCurrentPanelAcceleration (const int panelIndex)
Returns the current acceleration due to the radiation pressure on a single panel.
Eigen::Vector3d getCurrentPanelSurfaceNormalInPropagationFrame (const int panelIndex)
Returns the current surface normal in propagation frame of a single panel.
double getCurrentRadiationPressure ()
Returns the current radiation pressure at the accelerated body.
Eigen::Vector3d getCurrentVectorToSource ()
Returns the current normalized vector from the accelerated body to the source body.
std::function< double() > getMassFunction ()
Returns the function returning the current mass of the body being accelerated.
void updateMembers (const double currentTime=TUDAT_NAN)
Update member variables used by the radiation pressure acceleration model.
Public Member Functions inherited from tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >
AccelerationModel ()
Constructor.
virtual ~AccelerationModel ()
Virtual destructor.
virtual void resetTime (const double currentTime=TUDAT_NAN)
Function to reset the current time.
Private Attributes
std::function< Eigen::Vector3d() > acceleratedBodyPositionFunction_
Function pointer returning position of accelerated body.
Eigen::Vector3d currentAcceleration_
Current total acceleration due to radiation pressure on set of modelled panels.
double currentDistanceToSource_
The current distance from the accelerated body to the source body.
double currentMass_
Current mass of accelerated body.
Eigen::Vector3d currentNormalizedVectorToSource_
Current vector from accelerated body to source.
std::vector< Eigen::Vector3d > currentPanelAccelerations_
The current accelerations due to the radiation pressure on all single panel.
double currentRadiationPressure_
Current radiation pressure.
std::function< double() > massFunction_
Function pointer returning mass of accelerated body.
int numberOfPanels_
Number of panels used in acceleration model.
std::vector< std::function< double() > > panelAreaFunctions_
Vector of functions returning areas for all panels.
std::vector< std::function< double() > > panelDiffuseReflectionCoefficientFunctions_
Vector of functions returning diffuse reflection coefficients for all panels.
std::vector< std::function< double() > > panelEmissivittyFunctions_
Vector of functions returning emissivities for all panels.
std::vector< std::function< Eigen::Vector3d() > > panelSurfaceNormalFunctions_
Vector of functions returning panel surface normal functions.
std::function< double() > radiationPressureFunction_
Function pointer returning radiation pressure.
std::function< Eigen::Vector3d() > sourcePositionFunction_
Function pointer returning position of source.
Additional Inherited Members
Protected Attributes inherited from tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >
double currentTime_
Previous time to which acceleration model was updated.
Detailed Description
Class for calculating the radiation pressure acceleration on a panelled body, with the force due to each panel calculated from its area, orientation and emissivity. The emissivity determines the fraction that is absorbed (modelled as a force in line with the vector to th source) and one from reflection (modelled as a force normal to the panel).
Definition at line 54 of file panelledRadiationPressure.h.
Constructor & Destructor Documentation
PanelledRadiationPressureAcceleration() [1/2]
tudat::electro_magnetism::PanelledRadiationPressureAcceleration::PanelledRadiationPressureAcceleration (const std::function< Eigen::Vector3d() > sourcePositionFunction, const std::function< Eigen::Vector3d() > acceleratedBodyPositionFunction, const std::vector< std::function< double() > > & panelEmissivittyFunctions, const std::vector< std::function< double() > > & panelDiffuseReflectionCoefficientFunctions, const std::vector< std::function< Eigen::Vector3d() > > & panelSurfaceNormalFunctions, const std::vector< std::function< double() > > & panelAreaFunctions, const std::function< double() > radiationPressureFunction, const std::function< double() > massFunction) inline
Constructor for setting up the acceleration model, with separate input variables for all required data.
Parameters
sourcePositionFunction Function providing current position for the source body (i.e. the body from which the radiation originates)
acceleratedBodyPositionFunction Function providing current position for the body on which the force is acting
panelEmissivittyFunctions Vector of functions returning emissivities for all panels
panelDiffuseReflectionCoefficientFunctions Vector of functions returning diffuse reflection coefficients for all panels
panelSurfaceNormalFunctions Vector of functions returning panel surface normal function, in the same frame as the position functions of the accelerated and radiating bodies.
panelAreaFunctions Vector of functions returning areas for all panels
radiationPressureFunction Function returning the current radiation pressure (i.e. incident flux, in W/m^2, divided by speed of light)
massFunction Function returning the current mass of the body being accelerated
Definition at line 74 of file panelledRadiationPressure.h.
References currentPanelAccelerations_, numberOfPanels_, and panelEmissivittyFunctions_.
PanelledRadiationPressureAcceleration() [2/2]
tudat::electro_magnetism::PanelledRadiationPressureAcceleration::PanelledRadiationPressureAcceleration (const std::shared_ptr< PanelledRadiationPressureInterface > radiationPressureInterface, const std::function< double() > massFunction)
Constructor for setting up the acceleration model, with input RadiationPressureInterface (and massFunction). The massFunction is only used to convert force to acceleration. All radiation pressure properties are taken from the RadiationPressureInterface object.
Parameters
radiationPressureInterface Object in which radiation pressure properties of accelerated body due to radiation from body causing acceleration is stored.
massFunction Function returning the current mass of the body being accelerated
Definition at line 35 of file panelledRadiationPressure.cpp.
References acceleratedBodyPositionFunction_, currentPanelAccelerations_, tudat::electro_magnetism::RadiationPressureInterface::getArea(), tudat::electro_magnetism::RadiationPressureInterface::getCurrentRadiationPressure(), tudat::electro_magnetism::RadiationPressureInterface::getCurrentSolarVector(), tudat::electro_magnetism::PanelledRadiationPressureInterface::getCurrentSurfaceNormal(), tudat::electro_magnetism::PanelledRadiationPressureInterface::getDiffuseReflectionCoefficient(), tudat::electro_magnetism::PanelledRadiationPressureInterface::getEmissivity(), numberOfPanels_, panelAreaFunctions_, panelDiffuseReflectionCoefficientFunctions_, panelEmissivittyFunctions_, panelSurfaceNormalFunctions_, radiationPressureFunction_, and sourcePositionFunction_.
Member Function Documentation
getAcceleration()
Eigen::Vector3d tudat::electro_magnetism::PanelledRadiationPressureAcceleration::getAcceleration () inline virtual
Returns the panelled radiation pressure acceleration. No arguments are passed to this function. Instead, all data required for computation is to be obtained from pointers to functions/ classes/structs, etc which are to be set in a derived class and evaluated by the updateMembers() function below.
Returns
acceleration.
Implements tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >.
Definition at line 118 of file panelledRadiationPressure.h.
References currentAcceleration_.
updateMembers()
void tudat::electro_magnetism::PanelledRadiationPressureAcceleration::updateMembers (const double currentTime = TUDAT_NAN) inline virtual
Updates member variables used by the acceleration model. This function evaluates all dependent variables to the 'current' values of these parameters. Only these current values, not the function-pointers are then used by the getAcceleration() function.
Implements tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >.
Definition at line 130 of file panelledRadiationPressure.h.
References acceleratedBodyPositionFunction_, tudat::electro_magnetism::computeSinglePanelNormalizedRadiationPressureForce(), currentAcceleration_, currentDistanceToSource_, currentMass_, currentNormalizedVectorToSource_, currentPanelAccelerations_, currentRadiationPressure_, tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >::currentTime_, massFunction_, numberOfPanels_, panelAreaFunctions_, panelDiffuseReflectionCoefficientFunctions_, panelEmissivittyFunctions_, panelSurfaceNormalFunctions_, radiationPressureFunction_, and sourcePositionFunction_.
getMassFunction()
std::function< double() > tudat::electro_magnetism::PanelledRadiationPressureAcceleration::getMassFunction () inline
Returns the function returning the current mass of the body being accelerated.
Returns
Function returning the current mass of the body being accelerated.
Definition at line 164 of file panelledRadiationPressure.h.
References massFunction_.
getCurrentVectorToSource()
Eigen::Vector3d tudat::electro_magnetism::PanelledRadiationPressureAcceleration::getCurrentVectorToSource () inline
Returns the current normalized vector from the accelerated body to the source body, as set by the last call to the updateMembers function
Returns
The current normalized vector from the accelerated body to the source body
Definition at line 174 of file panelledRadiationPressure.h.
References currentNormalizedVectorToSource_.
getCurrentDistanceToSource()
double tudat::electro_magnetism::PanelledRadiationPressureAcceleration::getCurrentDistanceToSource () inline
Returns the current distance from the accelerated body to the source body, as set by the last call to the updateMembers function (i.e. norm of the current vector from accelerated body to the source)
Returns
The current distance from the accelerated body to the source body
Definition at line 185 of file panelledRadiationPressure.h.
References currentDistanceToSource_.
getCurrentPanelAcceleration()
Eigen::Vector3d tudat::electro_magnetism::PanelledRadiationPressureAcceleration::getCurrentPanelAcceleration (const int panelIndex) inline
Returns the current acceleration due to the radiation pressure on a single panel, as calculated by the last call to the updateMembers function
Parameters
panelIndex Index of panel for which acceleration is to be retrieved
Returns
The current acceleration due to the radiation pressure on a single panel
Definition at line 197 of file panelledRadiationPressure.h.
References currentPanelAccelerations_.
getCurrentPanelSurfaceNormalInPropagationFrame()
Eigen::Vector3d tudat::electro_magnetism::PanelledRadiationPressureAcceleration::getCurrentPanelSurfaceNormalInPropagationFrame (const int panelIndex) inline
Returns the current surface normal in propagation frame of a single panel, as calculated by the last call to the updateMembers function
Parameters
panelIndex Index of panel for which acceleration is to be retrieved
Returns
The current surface normal in propagation frame of a single panels
Definition at line 209 of file panelledRadiationPressure.h.
References panelSurfaceNormalFunctions_.
getCurrentRadiationPressure()
double tudat::electro_magnetism::PanelledRadiationPressureAcceleration::getCurrentRadiationPressure () inline
Returns the current radiation pressure at the accelerated body, as set by the last call to the updateMembers function (i.e. incident flux, in W/m^2, divided by speed of light)
Returns
The current radiation pressure at the accelerated body
Definition at line 220 of file panelledRadiationPressure.h.
References currentRadiationPressure_.
getCurrentMass()
double tudat::electro_magnetism::PanelledRadiationPressureAcceleration::getCurrentMass () inline
Returns the current mass of the accelerated body, as set by the last call to the updateMembers function
Returns
The current mass of the accelerated body
Definition at line 230 of file panelledRadiationPressure.h.
References currentMass_.
Member Data Documentation
sourcePositionFunction_
std::function< Eigen::Vector3d() > tudat::electro_magnetism::PanelledRadiationPressureAcceleration::sourcePositionFunction_ private
Function pointer returning position of source.
Definition at line 243 of file panelledRadiationPressure.h.
Referenced by PanelledRadiationPressureAcceleration(), and updateMembers().
acceleratedBodyPositionFunction_
std::function< Eigen::Vector3d() > tudat::electro_magnetism::PanelledRadiationPressureAcceleration::acceleratedBodyPositionFunction_ private
Function pointer returning position of accelerated body.
Definition at line 249 of file panelledRadiationPressure.h.
Referenced by PanelledRadiationPressureAcceleration(), and updateMembers().
radiationPressureFunction_
std::function< double() > tudat::electro_magnetism::PanelledRadiationPressureAcceleration::radiationPressureFunction_ private
Function pointer returning radiation pressure.
Definition at line 255 of file panelledRadiationPressure.h.
Referenced by PanelledRadiationPressureAcceleration(), and updateMembers().
panelEmissivittyFunctions_
std::vector< std::function< double() > > tudat::electro_magnetism::PanelledRadiationPressureAcceleration::panelEmissivittyFunctions_ private
Definition at line 258 of file panelledRadiationPressure.h.
Referenced by PanelledRadiationPressureAcceleration(), and updateMembers().
panelDiffuseReflectionCoefficientFunctions_
std::vector< std::function< double() > > tudat::electro_magnetism::PanelledRadiationPressureAcceleration::panelDiffuseReflectionCoefficientFunctions_ private
Definition at line 261 of file panelledRadiationPressure.h.
Referenced by PanelledRadiationPressureAcceleration(), and updateMembers().
panelSurfaceNormalFunctions_
std::vector< std::function< Eigen::Vector3d() > > tudat::electro_magnetism::PanelledRadiationPressureAcceleration::panelSurfaceNormalFunctions_ private
Vector of functions returning panel surface normal function, in the same frame as the position functions of the accelerated and radiating bodies.
Definition at line 268 of file panelledRadiationPressure.h.
Referenced by getCurrentPanelSurfaceNormalInPropagationFrame(), PanelledRadiationPressureAcceleration(), and updateMembers().
panelAreaFunctions_
std::vector< std::function< double() > > tudat::electro_magnetism::PanelledRadiationPressureAcceleration::panelAreaFunctions_ private
Definition at line 271 of file panelledRadiationPressure.h.
Referenced by PanelledRadiationPressureAcceleration(), and updateMembers().
massFunction_
std::function< double() > tudat::electro_magnetism::PanelledRadiationPressureAcceleration::massFunction_ private
Function pointer returning mass of accelerated body.
Definition at line 277 of file panelledRadiationPressure.h.
Referenced by getMassFunction(), and updateMembers().
currentPanelAccelerations_
std::vector< Eigen::Vector3d > tudat::electro_magnetism::PanelledRadiationPressureAcceleration::currentPanelAccelerations_ private
The current accelerations due to the radiation pressure on all single panel, as calculated by the last call to the updateMembers function
Definition at line 284 of file panelledRadiationPressure.h.
Referenced by getCurrentPanelAcceleration(), PanelledRadiationPressureAcceleration(), and updateMembers().
numberOfPanels_
int tudat::electro_magnetism::PanelledRadiationPressureAcceleration::numberOfPanels_ private
Definition at line 287 of file panelledRadiationPressure.h.
Referenced by PanelledRadiationPressureAcceleration(), and updateMembers().
currentRadiationPressure_
double tudat::electro_magnetism::PanelledRadiationPressureAcceleration::currentRadiationPressure_ private
Current radiation pressure, as set by the last call to the updateMembers function
Definition at line 293 of file panelledRadiationPressure.h.
Referenced by getCurrentRadiationPressure(), and updateMembers().
currentNormalizedVectorToSource_
Eigen::Vector3d tudat::electro_magnetism::PanelledRadiationPressureAcceleration::currentNormalizedVectorToSource_ private
Current vector from accelerated body to source, as calculated by the last call to the updateMembers function
Definition at line 299 of file panelledRadiationPressure.h.
Referenced by getCurrentVectorToSource(), and updateMembers().
currentDistanceToSource_
double tudat::electro_magnetism::PanelledRadiationPressureAcceleration::currentDistanceToSource_ private
The current distance from the accelerated body to the source body, as set by the last call to the updateMembers function (i.e. norm of the current vector from accelerated body to the source)
Definition at line 306 of file panelledRadiationPressure.h.
Referenced by getCurrentDistanceToSource(), and updateMembers().
currentMass_
double tudat::electro_magnetism::PanelledRadiationPressureAcceleration::currentMass_ private
Current mass of accelerated body, as set by the last call to the updateMembers function
Definition at line 312 of file panelledRadiationPressure.h.
Referenced by getCurrentMass(), and updateMembers().
currentAcceleration_
Eigen::Vector3d tudat::electro_magnetism::PanelledRadiationPressureAcceleration::currentAcceleration_ private
Current total acceleration due to radiation pressure on set of modelled panels, as calculated by the last call to the updateMembers functio
Definition at line 319 of file panelledRadiationPressure.h.
Referenced by getAcceleration(), and updateMembers().
The documentation for this class was generated from the following files:
Astrodynamics/ElectroMagnetism/panelledRadiationPressure.h
Astrodynamics/ElectroMagnetism/panelledRadiationPressure.cpp