Tudat: tudat::acceleration_partials::InertialTorquePartial Class Reference
tudat::acceleration_partials::InertialTorquePartial Class Reference
Class to compute the partial derivatives of the inertial torque w.r.t. states and parameters.
#include <inertialTorquePartial.h>
Public Member Functions
InertialTorquePartial (const std::function< Eigen::Vector3d() > angularVelocityFunction, const std::function< Eigen::Matrix3d() > inertiaTensorFunction, const std::function< double() > inertiaTensorNormalizationFunction, const std::function< double() > bodyGravitationalParameterFunction, const std::string acceleratedBody)
Constructor.
~InertialTorquePartial ()
std::pair< std::function< void(Eigen::MatrixXd &) >, int > getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function for setting up and retrieving a function returning a partial w.r.t. a double parameter.
std::pair< std::function< void(Eigen::MatrixXd &) >, int > getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function for setting up and retrieving a function returning a partial w.r.t. a vector parameter.
void update (const double currentTime=TUDAT_NAN)
Update partial model to current time.
void wrtOrientationOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the torque w.r.t. the orientation of the accelerated body.
void wrtRotationalVelocityOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=3)
Function for calculating the partial of the torque w.r.t. the angular velocity of the accelerated body.
Public Member Functions inherited from tudat::acceleration_partials::TorquePartial
TorquePartial (const std::string &bodyUndergoingTorque, const std::string &bodyExertingTorque, const basic_astrodynamics::AvailableTorque torqueType)
Base class constructor.
virtual ~TorquePartial ()
Virtual destructor.
std::string getBodyExertingTorque ()
Function to retrieve the name of the body exerting torque.
std::string getBodyUndergoingTorque ()
Function to retrieve the name of the body undergoing torque.
std::pair< std::function< void(Eigen::Block< Eigen::MatrixXd >) >, int > getDerivativeFunctionWrtStateOfIntegratedBody (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function to retrieve the function that returns the partial derivative w.r.t. a propagated state.
basic_astrodynamics::AvailableTorque getTorqueType ()
Function to retrieve the type of torque w.r.t. which partial is taken..
virtual bool isStateDerivativeDependentOnIntegratedAdditionalStateTypes (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function for determining if the torque is dependent on a non-rotational integrated state.
virtual bool isTorquePartialWrtAdditionalBodyNonNull (const std::string &bodyName)
Function to check whether the partial derivative w.r.t. the rotational state of a third body is non-zero.
virtual void wrtNonRotationalStateOfAdditionalBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function for calculating the partial of the torque w.r.t. a non-rotational integrated state.
virtual void wrtOrientationOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Pure virtual function for calculating the partial of the torque w.r.t. the orientation of the body exerting torque.
virtual void wrtOrientationOfAdditionalBody (const std::string &bodyName, Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the torque w.r.t. the orientation of the third body.
void wrtRotationalStateOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function for calculating the partial of the torque w.r.t. the rotational state of the body undergoing torque.
void wrtRotationalStateOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function for calculating the partial of the torque w.r.t. the Cartesian state of the body exerting torque.
void wrtRotationalStateOfAdditionalBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const std::string &bodyName)
Function for calculating the partial of the torque w.r.t. the Cartesian state of the third body.
virtual void wrtRotationalVelocityOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=3)
Function for calculating the partial of the torque w.r.t. the angular velocity of the body exerting torque.
virtual void wrtRotationalVelocityOfAdditionalBody (const std::string &bodyName, Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=3)
Function for calculating the partial of the torque w.r.t. the angular velocity of the third body.
Public Member Functions inherited from tudat::orbit_determination::StateDerivativePartial
StateDerivativePartial (const propagators::IntegratedStateType integratedStateType, const std::pair< std::string, std::string > &integrationReferencePoint)
Constructor.
virtual ~StateDerivativePartial ()
Destructor.
void getCurrentDoubleParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, Eigen::MatrixXd &parameterPartial)
Function to retrieve a partial w.r.t. a double parameter.
void getCurrentParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function to retrieve a partial w.r.t. a double parameter.
void getCurrentParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function to retrieve a partial w.r.t. a vector parameter.
void getCurrentVectorParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, Eigen::MatrixXd &parameterPartial)
Function to retrieve a partial w.r.t. a vector parameter.
propagators::IntegratedStateType getIntegratedStateType ()
Function to get the type of state for which partials are to be computed.
std::pair< std::string, std::string > getIntegrationReferencePoint ()
Function to get the identifier for body/reference point for which propagation is performed.
void resetTime (const double currentTime=TUDAT_NAN)
Function to reset the object to the current time.
virtual int setParameterPartialUpdateFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function to set a dependency of this partial object w.r.t. a given double parameter.
virtual int setParameterPartialUpdateFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function to set a dependency of this partial object w.r.t. a given vector parameter.
void updateParameterPartials ()
Function to update the values partial derivatives to current state and time.
Eigen::MatrixXd wrtParameter (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function to directly compute the partial of the state derivative w.r.t. a double parameter.
Eigen::MatrixXd wrtParameter (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function to directly compute the partial of the state derivative w.r.t. a vector parameter.
Protected Member Functions
void wrtCosineSphericalHarmonicCoefficientsOfCentralBody (Eigen::MatrixXd &sphericalHarmonicCoefficientPartial, const int c20Index, const int c21Index, const int c22Index)
Function to compute partial of torque w.r.t. spherical harmonic cosine coefficients.
void wrtGravitationalParameter (Eigen::MatrixXd &gravitationalParameterPartial)
Function to compute partial of torque w.r.t. gravitational parameter.
void wrtMeanMomentOfInertia (Eigen::MatrixXd &momentOfInertiaPartial)
Function to compute partial of torque w.r.t. mean moment of inertia.
void wrtSineSphericalHarmonicCoefficientsOfCentralBody (Eigen::MatrixXd &sphericalHarmonicCoefficientPartial, const int s21Index, const int s22Index)
Function to compute partial of torque w.r.t. spherical harmonic sine coefficients.
Protected Member Functions inherited from tudat::orbit_determination::StateDerivativePartial
void resetCurrentParameterValues ()
Function to define all current parameter partials as 'not computed'.
virtual void resetTimeOfMemberObjects ()
Function to reset the member object to the current time.
virtual void updateParameterPartialsOfMemberObjects ()
Function to compute parameter partials of member objects.
Protected Attributes
std::function< Eigen::Vector3d() > angularVelocityFunction_
Function returning body angular velocity vector in body fixed frame.
std::function< double() > bodyGravitationalParameterFunction_
Function returning body gravitational parameter.
Eigen::Matrix3d currentAngularVelocityCrossProductMatrix_
Current cross-product matrix from angular velocity vector.
Eigen::Vector3d currentAngularVelocityVector_
Current angular velocity vector.
double currentGravitationalParameter_
Current gravitational parameter.
Eigen::Matrix3d currentInertiaTensor_
Current inertia tensor.
double currentInertiaTensorNormalizationFactor_
Current inertia tensor normalization.
Eigen::Matrix3d currentInverseInertiaTensor_
Current inverse inertia tensor.
Eigen::Matrix3d currentPartialDerivativeWrtAngularVelocity_
Current partial derivative w.r.t. angular velocity vector.
std::function< double() > getInertiaTensorNormalizationFactor_
Function the inertia tensor normalization factor.
std::function< Eigen::Matrix3d() > inertiaTensorFunction_
Function returning body inertia tensor.
Protected Attributes inherited from tudat::acceleration_partials::TorquePartial
std::string bodyExertingTorque_
Name of the body exerting torque.
std::string bodyUndergoingTorque_
Name of the body undergoing torque.
basic_astrodynamics::AvailableTorque torqueType_
Type of torque w.r.t. which partial is taken..
Protected Attributes inherited from tudat::orbit_determination::StateDerivativePartial
int accelerationSize_
Size of the single order state derivative model (i.e. 3 for translational dynamics).
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, Eigen::MatrixXd > currentDoubleParameterPartials_
List of current values of partials w.r.t. double parameter values (emptied at beginning of every time step).
double currentTime_
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, Eigen::MatrixXd > currentVectorParameterPartials_
List of current values of partials w.r.t. double parameter values (emptied at beginning of every time step).
propagators::IntegratedStateType integratedStateType_
Type of state for which partials are to be computed.
std::pair< std::string, std::string > integrationReferencePoint_
Identifier for body/reference point for which propagation is performed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, bool > isCurrentDoubleParameterPartialSet_
List of booleans defining whether the partial w.r.t. the current double parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, bool >::iterator isCurrentDoubleParameterPartialSetIterator_
Iterator for list defining whether the partial w.r.t. the current double parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, bool > isCurrentVectorParameterPartialSet_
List of booleans defining whether the partial w.r.t. the current vector parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, bool >::iterator isCurrentVectorParameterPartialSetIterator_
Iterator for list defining whether the partial w.r.t. the current vector parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::function< void(Eigen::MatrixXd &) > >::iterator parameterDoublePartialFunctionIterator_
Iterator over list of functions to compute values of partials w.r.t. double parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::function< void(Eigen::MatrixXd &) > > parameterDoublePartialFunctions_
List of functions to compute (return by reference) values of partials w.r.t. doule parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::function< void(Eigen::MatrixXd &) > >::iterator parameterVectorPartialFunctionIterator_
Iterator over list of functions to compute values of partials w.r.t. vector parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::function< void(Eigen::MatrixXd &) > > parameterVectorPartialFunctions_
List of functions to compute (return by reference) values of partials w.r.t. vector parameter partials.
Detailed Description
Definition at line 28 of file inertialTorquePartial.h.
Constructor & Destructor Documentation
InertialTorquePartial()
tudat::acceleration_partials::InertialTorquePartial::InertialTorquePartial (const std::function< Eigen::Vector3d() > angularVelocityFunction, const std::function< Eigen::Matrix3d() > inertiaTensorFunction, const std::function< double() > inertiaTensorNormalizationFunction, const std::function< double() > bodyGravitationalParameterFunction, const std::string acceleratedBody) inline
Constructor
Parameters
angularVelocityFunction Function that returns body's body-fixed angular velocity vector
inertiaTensorFunction Function that returns body's inertia tensor
inertiaTensorNormalizationFunction Function the inertia tensor normalization factor
bodyGravitationalParameterFunction Function returning body gravitational parameter
acceleratedBody Name of body undergoing torque
Definition at line 41 of file inertialTorquePartial.h.
~InertialTorquePartial()
tudat::acceleration_partials::InertialTorquePartial::~InertialTorquePartial () inline
Definition at line 53 of file inertialTorquePartial.h.
References getParameterPartialFunction().
Member Function Documentation
getParameterPartialFunction() [1/2]
std::pair< std::function< void(Eigen::MatrixXd &) >, int > tudat::acceleration_partials::InertialTorquePartial::getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter) virtual
Function for setting up and retrieving a function returning a partial w.r.t. a double parameter. Function returns empty function and zero size indicator for parameters with no dependency for current torque.
Parameters
parameter Parameter w.r.t. which partial is to be taken.
Returns
Pair of parameter partial function and number of columns in partial (0 for no dependency, 1 otherwise).
Reimplemented from tudat::orbit_determination::StateDerivativePartial.
Definition at line 23 of file inertialTorquePartial.cpp.
References bodyGravitationalParameterFunction_, tudat::acceleration_partials::TorquePartial::bodyUndergoingTorque_, getInertiaTensorNormalizationFactor_, tudat::estimatable_parameters::gravitational_parameter, tudat::estimatable_parameters::mean_moment_of_inertia, wrtGravitationalParameter(), and wrtMeanMomentOfInertia().
Referenced by ~InertialTorquePartial().
getParameterPartialFunction() [2/2]
std::pair< std::function< void(Eigen::MatrixXd &) >, int > tudat::acceleration_partials::InertialTorquePartial::getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter) virtual
Function for setting up and retrieving a function returning a partial w.r.t. a vector parameter. Function returns empty function and zero size indicator for parameters with no dependency for current torque.
Parameters
parameter Parameter w.r.t. which partial is to be taken.
Returns
Pair of parameter partial function and number of columns in partial (0 for no dependency).
Reimplemented from tudat::orbit_determination::StateDerivativePartial.
Definition at line 65 of file inertialTorquePartial.cpp.
References tudat::acceleration_partials::TorquePartial::bodyUndergoingTorque_, getInertiaTensorNormalizationFactor_, tudat::estimatable_parameters::spherical_harmonics_cosine_coefficient_block, tudat::estimatable_parameters::spherical_harmonics_sine_coefficient_block, wrtCosineSphericalHarmonicCoefficientsOfCentralBody(), and wrtSineSphericalHarmonicCoefficientsOfCentralBody().
wrtOrientationOfAcceleratedBody()
void tudat::acceleration_partials::InertialTorquePartial::wrtOrientationOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 0) inline virtual
Function for calculating the partial of the torque w.r.t. the orientation of the accelerated body and adding it to the existing partial block.
Parameters
partialMatrix Block of partial derivatives of torque w.r.t. Orientation of body undergoing torque where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Implements tudat::acceleration_partials::TorquePartial.
Definition at line 85 of file inertialTorquePartial.h.
wrtRotationalVelocityOfAcceleratedBody()
void tudat::acceleration_partials::InertialTorquePartial::wrtRotationalVelocityOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 3) inline virtual
Function for calculating the partial of the torque w.r.t. the angular velocity of the accelerated body and adding it to the existing partial block.
Parameters
partialMatrix Block of partial derivatives of torque w.r.t. angular velocity of body undergoing torque where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Reimplemented from tudat::acceleration_partials::TorquePartial.
Definition at line 100 of file inertialTorquePartial.h.
References currentPartialDerivativeWrtAngularVelocity_.
update()
void tudat::acceleration_partials::InertialTorquePartial::update (const double currentTime = TUDAT_NAN) inline virtual
Update partial model to current time, retrieving information from consituent functions
Parameters
currentTime Time to which partial is to be updated
Implements tudat::orbit_determination::StateDerivativePartial.
Definition at line 119 of file inertialTorquePartial.h.
References angularVelocityFunction_, bodyGravitationalParameterFunction_, currentAngularVelocityCrossProductMatrix_, currentAngularVelocityVector_, currentGravitationalParameter_, currentInertiaTensor_, currentInertiaTensorNormalizationFactor_, currentInverseInertiaTensor_, currentPartialDerivativeWrtAngularVelocity_, tudat::orbit_determination::StateDerivativePartial::currentTime_, tudat::linear_algebra::getCrossProductMatrix(), getInertiaTensorNormalizationFactor_, inertiaTensorFunction_, wrtCosineSphericalHarmonicCoefficientsOfCentralBody(), wrtGravitationalParameter(), wrtMeanMomentOfInertia(), and wrtSineSphericalHarmonicCoefficientsOfCentralBody().
wrtMeanMomentOfInertia()
void tudat::acceleration_partials::InertialTorquePartial::wrtMeanMomentOfInertia (Eigen::MatrixXd & momentOfInertiaPartial) protected
Function to compute partial of torque w.r.t. mean moment of inertia
Parameters
momentOfInertiaPartial Computed partial of torque w.r.t. mean moment of inertia (returned by reference)
Definition at line 133 of file inertialTorquePartial.cpp.
References currentAngularVelocityCrossProductMatrix_, currentAngularVelocityVector_, currentInertiaTensorNormalizationFactor_, and tudat::acceleration_partials::UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_MEAN_MOMENT.
Referenced by getParameterPartialFunction(), and update().
wrtGravitationalParameter()
void tudat::acceleration_partials::InertialTorquePartial::wrtGravitationalParameter (Eigen::MatrixXd & gravitationalParameterPartial) protected
Function to compute partial of torque w.r.t. gravitational parameter
Parameters
gravitationalParameterPartial Computed partial of torque w.r.t. gravitational parameter (returned by reference)
Definition at line 142 of file inertialTorquePartial.cpp.
References currentAngularVelocityCrossProductMatrix_, currentAngularVelocityVector_, currentGravitationalParameter_, and currentInertiaTensor_.
Referenced by getParameterPartialFunction(), and update().
wrtCosineSphericalHarmonicCoefficientsOfCentralBody()
void tudat::acceleration_partials::InertialTorquePartial::wrtCosineSphericalHarmonicCoefficientsOfCentralBody (Eigen::MatrixXd & sphericalHarmonicCoefficientPartial, const int c20Index, const int c21Index, const int c22Index) protected
Function to compute partial of torque w.r.t. spherical harmonic cosine coefficients
Parameters
sphericalHarmonicCoefficientPartial Computed partial of torque w.r.t. spherical harmonic cosine coefficients (returned by reference)
c20Index for degree=2,order=0 coefficient
c21Index for degree=2,order=1 coefficient
c22Index for degree=2,order=2 coefficient
Definition at line 151 of file inertialTorquePartial.cpp.
References tudat::basic_mathematics::calculateLegendreGeodesyNormalizationFactor(), currentAngularVelocityCrossProductMatrix_, currentAngularVelocityVector_, currentInertiaTensorNormalizationFactor_, tudat::acceleration_partials::UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_C20, tudat::acceleration_partials::UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_C21, and tudat::acceleration_partials::UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_C22.
Referenced by getParameterPartialFunction(), and update().
wrtSineSphericalHarmonicCoefficientsOfCentralBody()
void tudat::acceleration_partials::InertialTorquePartial::wrtSineSphericalHarmonicCoefficientsOfCentralBody (Eigen::MatrixXd & sphericalHarmonicCoefficientPartial, const int s21Index, const int s22Index) protected
Function to compute partial of torque w.r.t. spherical harmonic sine coefficients
Parameters
sphericalHarmonicCoefficientPartial Computed partial of torque w.r.t. spherical harmonic sine coefficients (returned by refe
s21Index for degree=2,order=1 coefficient
s22Index for degree=2,order=2 coefficient)
Definition at line 183 of file inertialTorquePartial.cpp.
References tudat::basic_mathematics::calculateLegendreGeodesyNormalizationFactor(), currentAngularVelocityCrossProductMatrix_, currentAngularVelocityVector_, currentInertiaTensorNormalizationFactor_, tudat::acceleration_partials::UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_S21, and tudat::acceleration_partials::UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_S22.
Referenced by getParameterPartialFunction(), and update().
Member Data Documentation
angularVelocityFunction_
std::function< Eigen::Vector3d() > tudat::acceleration_partials::InertialTorquePartial::angularVelocityFunction_ protected
Definition at line 183 of file inertialTorquePartial.h.
Referenced by update().
inertiaTensorFunction_
std::function< Eigen::Matrix3d() > tudat::acceleration_partials::InertialTorquePartial::inertiaTensorFunction_ protected
Definition at line 186 of file inertialTorquePartial.h.
Referenced by update().
getInertiaTensorNormalizationFactor_
std::function< double() > tudat::acceleration_partials::InertialTorquePartial::getInertiaTensorNormalizationFactor_ protected
Definition at line 189 of file inertialTorquePartial.h.
Referenced by getParameterPartialFunction(), and update().
bodyGravitationalParameterFunction_
std::function< double() > tudat::acceleration_partials::InertialTorquePartial::bodyGravitationalParameterFunction_ protected
Definition at line 192 of file inertialTorquePartial.h.
Referenced by getParameterPartialFunction(), and update().
currentAngularVelocityVector_
Eigen::Vector3d tudat::acceleration_partials::InertialTorquePartial::currentAngularVelocityVector_ protected
Definition at line 195 of file inertialTorquePartial.h.
Referenced by update(), wrtCosineSphericalHarmonicCoefficientsOfCentralBody(), wrtGravitationalParameter(), wrtMeanMomentOfInertia(), and wrtSineSphericalHarmonicCoefficientsOfCentralBody().
currentAngularVelocityCrossProductMatrix_
Eigen::Matrix3d tudat::acceleration_partials::InertialTorquePartial::currentAngularVelocityCrossProductMatrix_ protected
Definition at line 198 of file inertialTorquePartial.h.
Referenced by update(), wrtCosineSphericalHarmonicCoefficientsOfCentralBody(), wrtGravitationalParameter(), wrtMeanMomentOfInertia(), and wrtSineSphericalHarmonicCoefficientsOfCentralBody().
currentInertiaTensor_
Eigen::Matrix3d tudat::acceleration_partials::InertialTorquePartial::currentInertiaTensor_ protected
Definition at line 201 of file inertialTorquePartial.h.
Referenced by update(), and wrtGravitationalParameter().
currentInverseInertiaTensor_
Eigen::Matrix3d tudat::acceleration_partials::InertialTorquePartial::currentInverseInertiaTensor_ protected
Definition at line 204 of file inertialTorquePartial.h.
Referenced by update().
currentPartialDerivativeWrtAngularVelocity_
Eigen::Matrix3d tudat::acceleration_partials::InertialTorquePartial::currentPartialDerivativeWrtAngularVelocity_ protected
Definition at line 207 of file inertialTorquePartial.h.
Referenced by update(), and wrtRotationalVelocityOfAcceleratedBody().
currentInertiaTensorNormalizationFactor_
double tudat::acceleration_partials::InertialTorquePartial::currentInertiaTensorNormalizationFactor_ protected
Definition at line 210 of file inertialTorquePartial.h.
Referenced by update(), wrtCosineSphericalHarmonicCoefficientsOfCentralBody(), wrtMeanMomentOfInertia(), and wrtSineSphericalHarmonicCoefficientsOfCentralBody().
currentGravitationalParameter_
double tudat::acceleration_partials::InertialTorquePartial::currentGravitationalParameter_ protected
Definition at line 213 of file inertialTorquePartial.h.
Referenced by update(), and wrtGravitationalParameter().
The documentation for this class was generated from the following files:
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/OrbitDetermination/RotationalDynamicsPartials/inertialTorquePartial.h
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/OrbitDetermination/RotationalDynamicsPartials/inertialTorquePartial.cpp