Tudat: tudat::electro_magnetism::SolarSailingRadiationPressureInterface Class Reference
tudat::electro_magnetism::SolarSailingRadiationPressureInterface Class Reference
Class in which the properties of a solar sailing radiation pressure acceleration model are stored.
#include <radiationPressureInterface.h>
Public Member Functions
SolarSailingRadiationPressureInterface (const std::function< double() > sourcePower, const std::function< Eigen::Vector3d() > sourcePositionFunction, const std::function< Eigen::Vector3d() > targetPositionFunction, const std::function< Eigen::Vector3d() > targetVelocityFunction, const double area, const std::function< double(const double) > coneAngle, const std::function< double(const double) > clockAngle, const double frontEmissivityCoefficient, const double backEmissivityCoefficient, const double frontLambertianCoefficient, const double backLambertianCoefficient, const double reflectivityCoefficient, const double specularReflectionCoefficient, const std::vector< std::function< Eigen::Vector3d() > > occultingBodyPositions=std::vector< std::function< Eigen::Vector3d() > >(), const std::function< Eigen::Vector3d() > centralBodyVelocity=std::function< Eigen::Vector3d() >(), const std::vector< double > occultingBodyRadii=std::vector< double >(), const double sourceRadius=0.0)
Constructor.
double getBackEmissivityCoefficient () const
Function to return the back emissivity coefficient of the target body.
double getBackLambertianCoefficient () const
Function to return the back Lambertian coefficient of the target body.
std::function< Eigen::Vector3d() > getCentralBodyVelocity ()
Returns the function returning the velocity of the central body.
std::function< double(const double) > getClockAngleFunction () const
Function to return the clock angle function.
std::function< double(const double) > getConeAngleFunction () const
Function to return the cone angle function.
double getCurrentClockAngle () const
Function to return the current clock angle of the target body.
double getCurrentConeAngle () const
Function to return the current cone angle of the target body.
Eigen::Vector3d getCurrentVelocityVector () const
Function to return the current normalised velocity of the target.
double getFrontEmissivityCoefficient () const
Function to return the front emissivity coefficient of the target body.
double getFrontLambertianCoefficient () const
Function to return the front Lambertian coefficient of the target body.
double getReflectivityCoefficient () const
Function to return the reflectivity coefficient of the target body.
double getSpecularReflectionCoefficient () const
Function to return the specular reflection coefficient of the target body.
std::function< Eigen::Vector3d() > getTargetVelocityFunction () const
Function to return the function returning the current normalised velocity of the target body.
void updateInterface (const double currentTime=TUDAT_NAN)
Base class function to update the current properties of the solar sailing radiation pressure acceleration model.
Public Member Functions inherited from tudat::electro_magnetism::RadiationPressureInterface
RadiationPressureInterface (const std::function< double() > sourcePower, const std::function< Eigen::Vector3d() > sourcePositionFunction, const std::function< Eigen::Vector3d() > targetPositionFunction, const double radiationPressureCoefficient, const double area, const std::vector< std::function< Eigen::Vector3d() > > occultingBodyPositions=std::vector< std::function< Eigen::Vector3d() > >(), const std::vector< double > occultingBodyRadii=std::vector< double >(), const double sourceRadius=0.0)
Constructor.
virtual ~RadiationPressureInterface ()
Destructor.
double getArea () const
Function to return the reflecting area of the target body.
double getCurrentRadiationPressure () const
Function to return the current radiation pressure due to source at target (in N/m^2).
Eigen::Vector3d getCurrentSolarVector () const
Function to return the current vector from the target to the source.
double getCurrentTime ()
Function to return the current time of interface (i.e. time of last updateInterface call).
std::vector< std::function< Eigen::Vector3d() > > getOccultingBodyPositions ()
Function to return the list of functions returning the positions of the bodies causing occultations.
std::vector< double > getOccultingBodyRadii ()
Function to return the list of radii of the bodies causing occultations.
double getRadiationPressureCoefficient () const
Function to return the radiation pressure coefficient of the target body.
std::function< Eigen::Vector3d() > getSourcePositionFunction () const
Function to return the function returning the current position of the source body.
std::function< double() > getSourcePowerFunction () const
Function to return the function returning the current total power (in W) emitted by the source body.
double getSourceRadius ()
Function to return the radius of the source body.
std::function< Eigen::Vector3d() > getTargetPositionFunction () const
Function to return the function returning the current position of the target body.
void resetRadiationPressureCoefficient (const double radiationPressureCoefficient)
Function to reset a constant radiation pressure coefficient of the target body.
void resetRadiationPressureCoefficientFunction (const std::function< double(const double) > radiationPressureCoefficientFunction)
Function to reset the function to obtain the radiation pressure coefficient of the target body.
void updateInterfaceBase (const double currentTime)
Base class function to update the current properties of radiation pressure.
Private Attributes
double backEmissivityCoefficient_
Back emissivity coefficient of the target body.
double backLambertianCoefficient_
Back Lambertian coefficient of the target body.
std::function< Eigen::Vector3d() > centralBodyVelocity_
Function returning the velocity of the central body.
std::function< double(const double) > clockAngleFunction_
Function returning the current clock angle of the target body.
std::function< double(const double) > coneAngleFunction_
Function returning the current cone angle of the target body.
double currentClockAngle_
Current clock angle of the body (in rad).
double currentConeAngle_
Current cone angle of the body (in rad).
Eigen::Vector3d currentUnitVelocityVector_
Current vector of the target's normalised velocity.
double frontEmissivityCoefficient_
Front emissivity coefficient of the target body.
double frontLambertianCoefficient_
Front Lambertian coefficient of the target body.
double reflectivityCoefficient_
Reflectivity coefficient of the target body.
double specularReflectionCoefficient_
Specular reflection coefficient of the target body.
std::function< Eigen::Vector3d() > targetVelocityFunction_
Function returning the current position of the source body.
Additional Inherited Members
Protected Attributes inherited from tudat::electro_magnetism::RadiationPressureInterface
double area_
Reflecting area of the target body.
double currentRadiationPressure_
Current radiation pressure due to source at target (in N/m^2).
Eigen::Vector3d currentSolarVector_
Current vector from the target to the source.
double currentTime_
Current time of interface (i.e. time of last updateInterface call).
std::vector< std::function< Eigen::Vector3d() > > occultingBodyPositions_
List of functions returning the positions of the bodies causing occultations.
std::vector< double > occultingBodyRadii_
List of radii of the bodies causing occultations.
double radiationPressureCoefficient_
Radiation pressure coefficient of the target body.
std::function< double(const double) > radiationPressureCoefficientFunction_
Function to reset a constant radiation pressure coefficient of the target body.
std::function< Eigen::Vector3d() > sourcePositionFunction_
Function returning the current position of the source body.
std::function< double() > sourcePower_
Function returning the current total power (in W) emitted by the source body.
double sourceRadius_
Radius of the source body.
std::function< Eigen::Vector3d() > targetPositionFunction_
Function returning the current position of the target body.
Detailed Description
Class in which the properties of a solar sailing radiation pressure acceleration model are stored and in which the current solar sailing radiation pressure is calculated based on the source power and geometry, as well as on the spacecraft solar sail model.
Definition at line 490 of file radiationPressureInterface.h.
Constructor & Destructor Documentation
SolarSailingRadiationPressureInterface()
tudat::electro_magnetism::SolarSailingRadiationPressureInterface::SolarSailingRadiationPressureInterface (const std::function< double() > sourcePower, const std::function< Eigen::Vector3d() > sourcePositionFunction, const std::function< Eigen::Vector3d() > targetPositionFunction, const std::function< Eigen::Vector3d() > targetVelocityFunction, const double area, const std::function< double(const double) > coneAngle, const std::function< double(const double) > clockAngle, const double frontEmissivityCoefficient, const double backEmissivityCoefficient, const double frontLambertianCoefficient, const double backLambertianCoefficient, const double reflectivityCoefficient, const double specularReflectionCoefficient, const std::vector< std::function< Eigen::Vector3d() > > occultingBodyPositions = std::vector< std::function< Eigen::Vector3d() > >(), const std::function< Eigen::Vector3d() > centralBodyVelocity = std::function< Eigen::Vector3d() >(), const std::vector< double > occultingBodyRadii = std::vector< double > (), const double sourceRadius = 0.0) inline
Class constructor for radiation pressure interface (appropriate for solar sail model)
Parameters
sourcePower Function returning the current total power (in W) emitted by the source body.
sourcePositionFunction Function returning the current position of the source body.
targetPositionFunction Function returning the current position of the target body.
targetVelocityFunction Function returning the current velocity of the target body w.r.t. central body.
area Reflecting area of the target body.
coneAngle Function returning the current cone angle of the target body.
clockAngle Function returning the current clock angle of the target body.
frontEmissivityCoefficient Front emissivity coefficient of the target body.
backEmissivityCoefficient Back emissivity coefficient of the target body.
frontLambertianCoefficient Front Lambertian coefficient of the target body.
backLambertianCoefficient Back Lambertian coefficient of the target body.
reflectivityCoefficient Reflectivity coefficient of the target body.
specularReflectionCoefficient Specular reflection coefficient of the target body.
occultingBodyPositions List of functions returning the positions of the bodies causing occultations (default none) NOTE: Multiple concurrent occultations may currently result in slighlty underestimted radiation pressure.
centralBodyVelocity Function returning the current velocity of the central body.
occultingBodyRadii List of radii of the bodies causing occultations (default none).
sourceRadius Radius of the source body (used for occultation calculations) (default 0).
Definition at line 517 of file radiationPressureInterface.h.
Member Function Documentation
updateInterface()
void tudat::electro_magnetism::SolarSailingRadiationPressureInterface::updateInterface (const double currentTime = TUDAT_NAN) inline virtual
Base class function to update the current properties of the solar sailing radiation pressure acceleration model. This function is nominally called by the updateInterface function, which may be overridden by derived classes.
Parameters
currentTime Time at which acceleration model is to be updated.
Reimplemented from tudat::electro_magnetism::RadiationPressureInterface.
Definition at line 557 of file radiationPressureInterface.h.
References tudat::electro_magnetism::RadiationPressureInterface::updateInterfaceBase().
getCurrentVelocityVector()
Eigen::Vector3d tudat::electro_magnetism::SolarSailingRadiationPressureInterface::getCurrentVelocityVector () const inline
Function to return the current normalised velocity of the target.
Returns
Current normalised velocity vector of the target [-].
Definition at line 576 of file radiationPressureInterface.h.
getTargetVelocityFunction()
std::function< Eigen::Vector3d() > tudat::electro_magnetism::SolarSailingRadiationPressureInterface::getTargetVelocityFunction () const inline
Function to return the function returning the current normalised velocity of the target body.
Returns
Function returning the current normalised velocity of the target body.
Definition at line 586 of file radiationPressureInterface.h.
getCurrentConeAngle()
double tudat::electro_magnetism::SolarSailingRadiationPressureInterface::getCurrentConeAngle () const inline
Function to return the current cone angle of the target body.
Returns
Current cone angle of the target body [rad].
Definition at line 596 of file radiationPressureInterface.h.
Referenced by tudat::simulation_setup::createSolarSailAccelerationModel().
getCurrentClockAngle()
double tudat::electro_magnetism::SolarSailingRadiationPressureInterface::getCurrentClockAngle () const inline
Function to return the current clock angle of the target body.
Returns
The current clock angle of the target body.
Definition at line 606 of file radiationPressureInterface.h.
Referenced by tudat::simulation_setup::createSolarSailAccelerationModel().
getConeAngleFunction()
std::function< double(const double) > tudat::electro_magnetism::SolarSailingRadiationPressureInterface::getConeAngleFunction () const inline
Function to return the cone angle function
Returns
Cone angle function.
Definition at line 616 of file radiationPressureInterface.h.
getClockAngleFunction()
std::function< double(const double) > tudat::electro_magnetism::SolarSailingRadiationPressureInterface::getClockAngleFunction () const inline
Function to return the clock angle function
Returns
Clock angle function.
Definition at line 626 of file radiationPressureInterface.h.
getFrontEmissivityCoefficient()
double tudat::electro_magnetism::SolarSailingRadiationPressureInterface::getFrontEmissivityCoefficient () const inline
Function to return the front emissivity coefficient of the target body.
Returns
Front emissivity coefficient of the target body [-].
Definition at line 636 of file radiationPressureInterface.h.
Referenced by tudat::simulation_setup::createSolarSailAccelerationModel().
getBackEmissivityCoefficient()
double tudat::electro_magnetism::SolarSailingRadiationPressureInterface::getBackEmissivityCoefficient () const inline
Function to return the back emissivity coefficient of the target body.
Returns
Back emissivity coefficient of the target body [-].
Definition at line 646 of file radiationPressureInterface.h.
Referenced by tudat::simulation_setup::createSolarSailAccelerationModel().
getFrontLambertianCoefficient()
double tudat::electro_magnetism::SolarSailingRadiationPressureInterface::getFrontLambertianCoefficient () const inline
Function to return the front Lambertian coefficient of the target body.
Returns
Front Lambertian coefficient of the target body [-].
Definition at line 656 of file radiationPressureInterface.h.
Referenced by tudat::simulation_setup::createSolarSailAccelerationModel().
getBackLambertianCoefficient()
double tudat::electro_magnetism::SolarSailingRadiationPressureInterface::getBackLambertianCoefficient () const inline
Function to return the back Lambertian coefficient of the target body.
Returns
Back Lambertian coefficient of the target body [-].
Definition at line 666 of file radiationPressureInterface.h.
Referenced by tudat::simulation_setup::createSolarSailAccelerationModel().
getReflectivityCoefficient()
double tudat::electro_magnetism::SolarSailingRadiationPressureInterface::getReflectivityCoefficient () const inline
Function to return the reflectivity coefficient of the target body.
Returns
Reflectivity coefficient of the target body [-].
Definition at line 676 of file radiationPressureInterface.h.
Referenced by tudat::simulation_setup::createSolarSailAccelerationModel().
getSpecularReflectionCoefficient()
double tudat::electro_magnetism::SolarSailingRadiationPressureInterface::getSpecularReflectionCoefficient () const inline
Function to return the specular reflection coefficient of the target body.
Returns
Specular reflection coefficient of the target body [-].
Definition at line 686 of file radiationPressureInterface.h.
Referenced by tudat::simulation_setup::createSolarSailAccelerationModel().
getCentralBodyVelocity()
std::function< Eigen::Vector3d() > tudat::electro_magnetism::SolarSailingRadiationPressureInterface::getCentralBodyVelocity () inline
Returns the function returning the velocity of the central body.
Returns
Function returning the velocity of the central body.
Definition at line 696 of file radiationPressureInterface.h.
Member Data Documentation
targetVelocityFunction_
std::function< Eigen::Vector3d() > tudat::electro_magnetism::SolarSailingRadiationPressureInterface::targetVelocityFunction_ private
Definition at line 705 of file radiationPressureInterface.h.
coneAngleFunction_
std::function< double(const double) > tudat::electro_magnetism::SolarSailingRadiationPressureInterface::coneAngleFunction_ private
Definition at line 708 of file radiationPressureInterface.h.
clockAngleFunction_
std::function< double(const double) > tudat::electro_magnetism::SolarSailingRadiationPressureInterface::clockAngleFunction_ private
Definition at line 711 of file radiationPressureInterface.h.
currentConeAngle_
double tudat::electro_magnetism::SolarSailingRadiationPressureInterface::currentConeAngle_ private
Definition at line 714 of file radiationPressureInterface.h.
currentClockAngle_
double tudat::electro_magnetism::SolarSailingRadiationPressureInterface::currentClockAngle_ private
Definition at line 717 of file radiationPressureInterface.h.
frontEmissivityCoefficient_
double tudat::electro_magnetism::SolarSailingRadiationPressureInterface::frontEmissivityCoefficient_ private
Definition at line 720 of file radiationPressureInterface.h.
backEmissivityCoefficient_
double tudat::electro_magnetism::SolarSailingRadiationPressureInterface::backEmissivityCoefficient_ private
Definition at line 723 of file radiationPressureInterface.h.
frontLambertianCoefficient_
double tudat::electro_magnetism::SolarSailingRadiationPressureInterface::frontLambertianCoefficient_ private
Definition at line 726 of file radiationPressureInterface.h.
backLambertianCoefficient_
double tudat::electro_magnetism::SolarSailingRadiationPressureInterface::backLambertianCoefficient_ private
Definition at line 729 of file radiationPressureInterface.h.
reflectivityCoefficient_
double tudat::electro_magnetism::SolarSailingRadiationPressureInterface::reflectivityCoefficient_ private
Definition at line 732 of file radiationPressureInterface.h.
specularReflectionCoefficient_
double tudat::electro_magnetism::SolarSailingRadiationPressureInterface::specularReflectionCoefficient_ private
Definition at line 735 of file radiationPressureInterface.h.
centralBodyVelocity_
std::function< Eigen::Vector3d() > tudat::electro_magnetism::SolarSailingRadiationPressureInterface::centralBodyVelocity_ private
Definition at line 738 of file radiationPressureInterface.h.
currentUnitVelocityVector_
Eigen::Vector3d tudat::electro_magnetism::SolarSailingRadiationPressureInterface::currentUnitVelocityVector_ private
Definition at line 741 of file radiationPressureInterface.h.
The documentation for this class was generated from the following file:
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/ElectroMagnetism/radiationPressureInterface.h