Tudat: tudat::shape_based_methods::ScaledExponentialCosineFunctionHodographicShaping Class Reference
tudat::shape_based_methods::ScaledExponentialCosineFunctionHodographicShaping Class Reference
Scaled exponential times cosine function.
#include <baseFunctionsHodographicShaping.h>
Public Member Functions
ScaledExponentialCosineFunctionHodographicShaping (double exponentExponentialFunction, double frequencyCosineFunction, double scaleFactor)
Constructor taking order of the exponential function, frequency of the cosine function, and scaling factor as inputs.
~ScaledExponentialCosineFunctionHodographicShaping ()
Default destructor.
double evaluateDerivative (const double independentVariable)
double evaluateFunction (const double independentVariable)
Function, derivative, and integral of the scaled exponential times cosine function.
double evaluateIntegral (const double independentVariable)
Public Member Functions inherited from tudat::shape_based_methods::BaseFunctionHodographicShaping
BaseFunctionHodographicShaping ()
Default constructor.
virtual ~BaseFunctionHodographicShaping ()
Default destructor.
Private Attributes
double exponentExponentialFunction_
double frequencyCosineFunction_
double scaleFactor_
Detailed Description
Definition at line 313 of file baseFunctionsHodographicShaping.h.
Constructor & Destructor Documentation
ScaledExponentialCosineFunctionHodographicShaping()
tudat::shape_based_methods::ScaledExponentialCosineFunctionHodographicShaping::ScaledExponentialCosineFunctionHodographicShaping (double exponentExponentialFunction, double frequencyCosineFunction, double scaleFactor) inline
Definition at line 318 of file baseFunctionsHodographicShaping.h.
~ScaledExponentialCosineFunctionHodographicShaping()
tudat::shape_based_methods::ScaledExponentialCosineFunctionHodographicShaping::~ScaledExponentialCosineFunctionHodographicShaping () inline
Definition at line 326 of file baseFunctionsHodographicShaping.h.
References tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateDerivative(), tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateFunction(), tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateIntegral(), and tudat::propagators::independentVariable.
Member Function Documentation
evaluateFunction()
double tudat::shape_based_methods::ScaledExponentialCosineFunctionHodographicShaping::evaluateFunction (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 169 of file baseFunctionsHodographicShaping.cpp.
evaluateDerivative()
double tudat::shape_based_methods::ScaledExponentialCosineFunctionHodographicShaping::evaluateDerivative (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 175 of file baseFunctionsHodographicShaping.cpp.
evaluateIntegral()
double tudat::shape_based_methods::ScaledExponentialCosineFunctionHodographicShaping::evaluateIntegral (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 182 of file baseFunctionsHodographicShaping.cpp.
Member Data Documentation
exponentExponentialFunction_
double tudat::shape_based_methods::ScaledExponentialCosineFunctionHodographicShaping::exponentExponentialFunction_ private
Definition at line 338 of file baseFunctionsHodographicShaping.h.
frequencyCosineFunction_
double tudat::shape_based_methods::ScaledExponentialCosineFunctionHodographicShaping::frequencyCosineFunction_ private
Definition at line 339 of file baseFunctionsHodographicShaping.h.
scaleFactor_
double tudat::shape_based_methods::ScaledExponentialCosineFunctionHodographicShaping::scaleFactor_ private
Definition at line 340 of file baseFunctionsHodographicShaping.h.
The documentation for this class was generated from the following files:
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/baseFunctionsHodographicShaping.h
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/baseFunctionsHodographicShaping.cpp