Tudat: tudat::shape_based_methods::ScaledPowerCosineFunctionHodographicShaping Class Reference
tudat::shape_based_methods::ScaledPowerCosineFunctionHodographicShaping Class Reference
#include <baseFunctionsHodographicShaping.h>
Public Member Functions
ScaledPowerCosineFunctionHodographicShaping (double exponentPowerFunction, double frequencyCosineFunction, double scaleFactor)
~ScaledPowerCosineFunctionHodographicShaping ()
Default destructor.
double evaluateDerivative (const double independentVariable)
double evaluateFunction (const double independentVariable)
Function, derivative, and integral of scaled power times cosine function.
double evaluateIntegral (const double independentVariable)
Public Member Functions inherited from tudat::shape_based_methods::BaseFunctionHodographicShaping
BaseFunctionHodographicShaping ()
Default constructor.
virtual ~BaseFunctionHodographicShaping ()
Default destructor.
Private Attributes
double exponentPowerFunction_
double frequencyCosineFunction_
double scaleFactor_
Detailed Description
Definition at line 496 of file baseFunctionsHodographicShaping.h.
Constructor & Destructor Documentation
ScaledPowerCosineFunctionHodographicShaping()
tudat::shape_based_methods::ScaledPowerCosineFunctionHodographicShaping::ScaledPowerCosineFunctionHodographicShaping (double exponentPowerFunction, double frequencyCosineFunction, double scaleFactor) inline
Definition at line 500 of file baseFunctionsHodographicShaping.h.
~ScaledPowerCosineFunctionHodographicShaping()
tudat::shape_based_methods::ScaledPowerCosineFunctionHodographicShaping::~ScaledPowerCosineFunctionHodographicShaping () inline
Definition at line 508 of file baseFunctionsHodographicShaping.h.
References tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateDerivative(), tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateFunction(), tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateIntegral(), and tudat::propagators::independentVariable.
Member Function Documentation
evaluateFunction()
double tudat::shape_based_methods::ScaledPowerCosineFunctionHodographicShaping::evaluateFunction (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 373 of file baseFunctionsHodographicShaping.cpp.
evaluateDerivative()
double tudat::shape_based_methods::ScaledPowerCosineFunctionHodographicShaping::evaluateDerivative (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 379 of file baseFunctionsHodographicShaping.cpp.
evaluateIntegral()
double tudat::shape_based_methods::ScaledPowerCosineFunctionHodographicShaping::evaluateIntegral (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 388 of file baseFunctionsHodographicShaping.cpp.
Member Data Documentation
exponentPowerFunction_
double tudat::shape_based_methods::ScaledPowerCosineFunctionHodographicShaping::exponentPowerFunction_ private
Definition at line 520 of file baseFunctionsHodographicShaping.h.
frequencyCosineFunction_
double tudat::shape_based_methods::ScaledPowerCosineFunctionHodographicShaping::frequencyCosineFunction_ private
Definition at line 521 of file baseFunctionsHodographicShaping.h.
scaleFactor_
double tudat::shape_based_methods::ScaledPowerCosineFunctionHodographicShaping::scaleFactor_ private
Definition at line 522 of file baseFunctionsHodographicShaping.h.
The documentation for this class was generated from the following files:
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/baseFunctionsHodographicShaping.h
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/baseFunctionsHodographicShaping.cpp