Tudat: tudat::shape_based_methods::ScaledPowerFunctionHodographicShaping Class Reference
tudat::shape_based_methods::ScaledPowerFunctionHodographicShaping Class Reference
Scaled power function.
#include <baseFunctionsHodographicShaping.h>
Public Member Functions
ScaledPowerFunctionHodographicShaping (double exponent, double scaleFactor)
Constructor taking the exponent and scaling factor as inputs.
~ScaledPowerFunctionHodographicShaping ()
Default destructor.
double evaluateDerivative (const double independentVariable)
double evaluateFunction (const double independentVariable)
Function, derivative, and integral of scaled power function.
double evaluateIntegral (const double independentVariable)
Public Member Functions inherited from tudat::shape_based_methods::BaseFunctionHodographicShaping
BaseFunctionHodographicShaping ()
Default constructor.
virtual ~BaseFunctionHodographicShaping ()
Default destructor.
Private Attributes
double exponent_
double scaleFactor_
Detailed Description
Definition at line 375 of file baseFunctionsHodographicShaping.h.
Constructor & Destructor Documentation
ScaledPowerFunctionHodographicShaping()
tudat::shape_based_methods::ScaledPowerFunctionHodographicShaping::ScaledPowerFunctionHodographicShaping (double exponent, double scaleFactor) inline
Definition at line 380 of file baseFunctionsHodographicShaping.h.
~ScaledPowerFunctionHodographicShaping()
tudat::shape_based_methods::ScaledPowerFunctionHodographicShaping::~ScaledPowerFunctionHodographicShaping () inline
Definition at line 387 of file baseFunctionsHodographicShaping.h.
References tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateDerivative(), tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateFunction(), tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateIntegral(), and tudat::propagators::independentVariable.
Member Function Documentation
evaluateFunction()
double tudat::shape_based_methods::ScaledPowerFunctionHodographicShaping::evaluateFunction (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 211 of file baseFunctionsHodographicShaping.cpp.
evaluateDerivative()
double tudat::shape_based_methods::ScaledPowerFunctionHodographicShaping::evaluateDerivative (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 216 of file baseFunctionsHodographicShaping.cpp.
evaluateIntegral()
double tudat::shape_based_methods::ScaledPowerFunctionHodographicShaping::evaluateIntegral (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 221 of file baseFunctionsHodographicShaping.cpp.
Member Data Documentation
exponent_
double tudat::shape_based_methods::ScaledPowerFunctionHodographicShaping::exponent_ private
Definition at line 399 of file baseFunctionsHodographicShaping.h.
scaleFactor_
double tudat::shape_based_methods::ScaledPowerFunctionHodographicShaping::scaleFactor_ private
Definition at line 400 of file baseFunctionsHodographicShaping.h.
The documentation for this class was generated from the following files:
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/baseFunctionsHodographicShaping.h
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/baseFunctionsHodographicShaping.cpp