Tudat: tudat::shape_based_methods::ExponentialSineFunctionHodographicShaping Class Reference
tudat::shape_based_methods::ExponentialSineFunctionHodographicShaping Class Reference
Exponential times sine function.
#include <baseFunctionsHodographicShaping.h>
Public Member Functions
ExponentialSineFunctionHodographicShaping (double exponentExponentialFunction, double frequencySineFunction)
Constructor taking exponent of the exponential function and frequency of the sine function as inputs.
~ExponentialSineFunctionHodographicShaping ()
Default destructor.
double evaluateDerivative (const double independentVariable)
double evaluateFunction (const double independentVariable)
Function, derivative, and integral of exponential times sine function.
double evaluateIntegral (const double independentVariable)
Public Member Functions inherited from tudat::shape_based_methods::BaseFunctionHodographicShaping
BaseFunctionHodographicShaping ()
Default constructor.
virtual ~BaseFunctionHodographicShaping ()
Default destructor.
Private Attributes
double exponentExponentialFunction_
double frequencySineFunction_
Detailed Description
Definition at line 221 of file baseFunctionsHodographicShaping.h.
Constructor & Destructor Documentation
ExponentialSineFunctionHodographicShaping()
tudat::shape_based_methods::ExponentialSineFunctionHodographicShaping::ExponentialSineFunctionHodographicShaping (double exponentExponentialFunction, double frequencySineFunction) inline
Definition at line 226 of file baseFunctionsHodographicShaping.h.
~ExponentialSineFunctionHodographicShaping()
tudat::shape_based_methods::ExponentialSineFunctionHodographicShaping::~ExponentialSineFunctionHodographicShaping () inline
Definition at line 233 of file baseFunctionsHodographicShaping.h.
References tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateDerivative(), tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateFunction(), tudat::shape_based_methods::BaseFunctionHodographicShaping::evaluateIntegral(), and tudat::propagators::independentVariable.
Member Function Documentation
evaluateFunction()
double tudat::shape_based_methods::ExponentialSineFunctionHodographicShaping::evaluateFunction (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 97 of file baseFunctionsHodographicShaping.cpp.
evaluateDerivative()
double tudat::shape_based_methods::ExponentialSineFunctionHodographicShaping::evaluateDerivative (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 103 of file baseFunctionsHodographicShaping.cpp.
evaluateIntegral()
double tudat::shape_based_methods::ExponentialSineFunctionHodographicShaping::evaluateIntegral (const double independentVariable) virtual
Implements tudat::shape_based_methods::BaseFunctionHodographicShaping.
Definition at line 110 of file baseFunctionsHodographicShaping.cpp.
Member Data Documentation
exponentExponentialFunction_
double tudat::shape_based_methods::ExponentialSineFunctionHodographicShaping::exponentExponentialFunction_ private
Definition at line 246 of file baseFunctionsHodographicShaping.h.
frequencySineFunction_
double tudat::shape_based_methods::ExponentialSineFunctionHodographicShaping::frequencySineFunction_ private
Definition at line 247 of file baseFunctionsHodographicShaping.h.
The documentation for this class was generated from the following files:
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/baseFunctionsHodographicShaping.h
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/baseFunctionsHodographicShaping.cpp