Tudat: tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping Class Reference
tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping Class Reference
#include <compositeFunctionSphericalShaping.h>
Public Member Functions
CompositeRadialFunctionSphericalShaping (Eigen::VectorXd &compositeFunctionCoefficients)
Constructor.
~CompositeRadialFunctionSphericalShaping ()
Default destructor.
double evaluateCompositeFunction (const double independentVariable)
double evaluateCompositeFunctionFirstDerivative (const double independentVariable)
double evaluateCompositeFunctionSecondDerivative (const double independentVariable)
double evaluateCompositeFunctionThirdDerivative (const double independentVariable)
double getComponentFunctionCurrentValue (const int componentIndex, const double currentTime)
double getComponentFunctionFirstDerivative (const int componentIndex, const double currentTime)
double getComponentFunctionSecondDerivative (const int componentIndex, const double currentTime)
double getComponentFunctionThirdDerivative (const int componentIndex, const double currentTime)
Eigen::VectorXd getCompositeFunctionCoefficients ()
Return coefficients.
void resetCompositeFunctionCoefficients (const Eigen::VectorXd &compositeFunctionCoefficients)
Reset coefficients.
Public Member Functions inherited from tudat::shape_based_methods::CompositeFunctionSphericalShaping
CompositeFunctionSphericalShaping ()
Constructor.
~CompositeFunctionSphericalShaping ()
Default destructor.
double evaluateCompositeFunction (const double independentVariable)
double evaluateCompositeFunctionFirstDerivative (const double independentVariable)
double evaluateCompositeFunctionSecondDerivative (const double independentVariable)
double evaluateCompositeFunctionThirdDerivative (const double independentVariable)
double getComponentFunctionCurrentValue (const int componentIndex, const double currentTime)
double getComponentFunctionFirstDerivative (const int componentIndex, const double currentTime)
double getComponentFunctionSecondDerivative (const int componentIndex, const double currentTime)
double getComponentFunctionThirdDerivative (const int componentIndex, const double currentTime)
std::shared_ptr< BaseFunctionSphericalShaping > getCompositeComponent (int indexComponent)
std::vector< std::shared_ptr< BaseFunctionSphericalShaping > > getCompositeComponents ()
Eigen::VectorXd getCompositeFunctionCoefficients ()
Return coefficients.
void resetCompositeFunctionCoefficients (const Eigen::VectorXd &compositeFunctionCoefficients)
Reset coefficients.
Private Attributes
Eigen::VectorXd compositeFunctionCoefficients_
Vector of coefficients.
std::vector< std::shared_ptr< BaseFunctionSphericalShaping > > compositeFunctionComponents_
Detailed Description
Definition at line 101 of file compositeFunctionSphericalShaping.h.
Constructor & Destructor Documentation
CompositeRadialFunctionSphericalShaping()
tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::CompositeRadialFunctionSphericalShaping (Eigen::VectorXd & compositeFunctionCoefficients) inline
Definition at line 106 of file compositeFunctionSphericalShaping.h.
References tudat::shape_based_methods::CompositeFunctionSphericalShaping::compositeFunctionCoefficients_, tudat::shape_based_methods::CompositeFunctionSphericalShaping::compositeFunctionComponents_, tudat::shape_based_methods::constantSphericalShaping, tudat::shape_based_methods::cosineSphericalShaping, tudat::shape_based_methods::createBaseFunctionSphericalShaping(), tudat::shape_based_methods::linearSphericalShaping, tudat::shape_based_methods::powerCosineSphericalShaping, tudat::shape_based_methods::powerSineSphericalShaping, tudat::shape_based_methods::sineSphericalShaping, and tudat::shape_based_methods::squaredSphericalShaping.
~CompositeRadialFunctionSphericalShaping()
tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::~CompositeRadialFunctionSphericalShaping () inline
Default destructor.
Definition at line 127 of file compositeFunctionSphericalShaping.h.
Member Function Documentation
getCompositeFunctionCoefficients()
Eigen::VectorXd tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::getCompositeFunctionCoefficients () inline
Returns coefficients of composite function.
Definition at line 133 of file compositeFunctionSphericalShaping.h.
References tudat::shape_based_methods::CompositeFunctionSphericalShaping::compositeFunctionCoefficients_, tudat::shape_based_methods::CompositeFunctionSphericalShaping::evaluateCompositeFunction(), tudat::shape_based_methods::CompositeFunctionSphericalShaping::evaluateCompositeFunctionFirstDerivative(), tudat::shape_based_methods::CompositeFunctionSphericalShaping::evaluateCompositeFunctionSecondDerivative(), tudat::shape_based_methods::CompositeFunctionSphericalShaping::evaluateCompositeFunctionThirdDerivative(), tudat::shape_based_methods::CompositeFunctionSphericalShaping::getComponentFunctionCurrentValue(), tudat::shape_based_methods::CompositeFunctionSphericalShaping::getComponentFunctionFirstDerivative(), tudat::shape_based_methods::CompositeFunctionSphericalShaping::getComponentFunctionSecondDerivative(), tudat::shape_based_methods::CompositeFunctionSphericalShaping::getComponentFunctionThirdDerivative(), tudat::propagators::independentVariable, and tudat::shape_based_methods::CompositeFunctionSphericalShaping::resetCompositeFunctionCoefficients().
resetCompositeFunctionCoefficients()
void tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::resetCompositeFunctionCoefficients (const Eigen::VectorXd & compositeFunctionCoefficients)
Resets the coefficients of the composite function.
Definition at line 22 of file compositeFunctionSphericalShaping.cpp.
References compositeFunctionCoefficients_, and compositeFunctionComponents_.
evaluateCompositeFunction()
double tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::evaluateCompositeFunction (const double independentVariable)
Definition at line 39 of file compositeFunctionSphericalShaping.cpp.
References compositeFunctionCoefficients_, and compositeFunctionComponents_.
Referenced by evaluateCompositeFunctionFirstDerivative(), evaluateCompositeFunctionSecondDerivative(), and evaluateCompositeFunctionThirdDerivative().
evaluateCompositeFunctionFirstDerivative()
double tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::evaluateCompositeFunctionFirstDerivative (const double independentVariable)
Definition at line 51 of file compositeFunctionSphericalShaping.cpp.
References compositeFunctionCoefficients_, compositeFunctionComponents_, and evaluateCompositeFunction().
Referenced by evaluateCompositeFunctionSecondDerivative(), and evaluateCompositeFunctionThirdDerivative().
evaluateCompositeFunctionSecondDerivative()
double tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::evaluateCompositeFunctionSecondDerivative (const double independentVariable)
Definition at line 62 of file compositeFunctionSphericalShaping.cpp.
References compositeFunctionCoefficients_, compositeFunctionComponents_, evaluateCompositeFunction(), and evaluateCompositeFunctionFirstDerivative().
Referenced by evaluateCompositeFunctionThirdDerivative().
evaluateCompositeFunctionThirdDerivative()
double tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::evaluateCompositeFunctionThirdDerivative (const double independentVariable)
Definition at line 79 of file compositeFunctionSphericalShaping.cpp.
References compositeFunctionCoefficients_, compositeFunctionComponents_, evaluateCompositeFunction(), evaluateCompositeFunctionFirstDerivative(), and evaluateCompositeFunctionSecondDerivative().
getComponentFunctionCurrentValue()
double tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::getComponentFunctionCurrentValue (const int componentIndex, const double currentTime)
Definition at line 113 of file compositeFunctionSphericalShaping.cpp.
References compositeFunctionComponents_.
getComponentFunctionFirstDerivative()
double tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::getComponentFunctionFirstDerivative (const int componentIndex, const double currentTime)
Definition at line 120 of file compositeFunctionSphericalShaping.cpp.
References compositeFunctionComponents_.
getComponentFunctionSecondDerivative()
double tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::getComponentFunctionSecondDerivative (const int componentIndex, const double currentTime)
Definition at line 126 of file compositeFunctionSphericalShaping.cpp.
References compositeFunctionComponents_.
getComponentFunctionThirdDerivative()
double tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::getComponentFunctionThirdDerivative (const int componentIndex, const double currentTime)
Definition at line 132 of file compositeFunctionSphericalShaping.cpp.
References compositeFunctionComponents_.
Member Data Documentation
compositeFunctionComponents_
std::vector< std::shared_ptr< BaseFunctionSphericalShaping > > tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::compositeFunctionComponents_ private
Definition at line 170 of file compositeFunctionSphericalShaping.h.
Referenced by evaluateCompositeFunction(), tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::evaluateCompositeFunction(), evaluateCompositeFunctionFirstDerivative(), tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::evaluateCompositeFunctionFirstDerivative(), evaluateCompositeFunctionSecondDerivative(), tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::evaluateCompositeFunctionSecondDerivative(), evaluateCompositeFunctionThirdDerivative(), tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::evaluateCompositeFunctionThirdDerivative(), getComponentFunctionCurrentValue(), tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::getComponentFunctionCurrentValue(), getComponentFunctionFirstDerivative(), tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::getComponentFunctionFirstDerivative(), getComponentFunctionSecondDerivative(), tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::getComponentFunctionSecondDerivative(), getComponentFunctionThirdDerivative(), tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::getComponentFunctionThirdDerivative(), resetCompositeFunctionCoefficients(), and tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::resetCompositeFunctionCoefficients().
compositeFunctionCoefficients_
Eigen::VectorXd tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::compositeFunctionCoefficients_ private
VectorXd containing coefficients corresponding to components of the composite function.
Definition at line 176 of file compositeFunctionSphericalShaping.h.
Referenced by evaluateCompositeFunction(), tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::evaluateCompositeFunction(), evaluateCompositeFunctionFirstDerivative(), tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::evaluateCompositeFunctionFirstDerivative(), evaluateCompositeFunctionSecondDerivative(), tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::evaluateCompositeFunctionSecondDerivative(), evaluateCompositeFunctionThirdDerivative(), tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::evaluateCompositeFunctionThirdDerivative(), resetCompositeFunctionCoefficients(), and tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::resetCompositeFunctionCoefficients().
The documentation for this class was generated from the following files:
Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/compositeFunctionSphericalShaping.h
Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/compositeFunctionSphericalShaping.cpp