Tudat: tudat::circular_restricted_three_body_problem Namespace Reference
tudat::circular_restricted_three_body_problem Namespace Reference
Classes
class LibrationPoint
Libration point class.
Typedefs
typedef std::shared_ptr< LibrationPoint > LibrationPointPointer
Functions
double computeMassParameter (const double primaryGravitationalParameter, const double secondaryGravitationalParameter)
Compute mass parameter.
Eigen::Vector6d convertCartesianToCorotatingNormalizedCoordinates (const double gravitationalParameterPrimary, const double gravitationalParameterSecondary, const double distancePrimarySecondary, const Eigen::Vector6d &cartesianState, const double time)
Convert inertial cartesian state to co-rotating normalized state.
Eigen::Vector6d convertCorotatingNormalizedToCartesianCoordinates (const double gravitationalParameterPrimary, const double gravitationalParameterSecondary, const double distancePrimarySecondary, const Eigen::Vector6d &normalizedState, const double normalizedTime)
Convert corotating normalized state to inertial cartesian state.
Eigen::VectorXd convertDimensionalCartesianStateToDimensionlessState (const Eigen::Vector6d &dimensionalCartesianState, const double gravitationalParameterOfPrimaryBody, const double gravitationalParameterOfSecondaryBody, const double distanceBetweenPrimaries)
Convert dimensional Cartesian state to dimensionless state.
double convertDimensionalTimeToDimensionlessTime (const double dimensionalTime, const double gravitationalParameterOfPrimaryBody, const double gravitationalParameterOfSecondaryBody, const double distanceBetweenPrimaries)
Convert dimensional time to dimensionless time.
Eigen::VectorXd convertDimensionlessCartesianStateToDimensionalUnits (const Eigen::Vector6d &dimensionlessCartesianState, const double gravitationalParameterOfPrimaryBody, const double gravitationalParameterOfSecondaryBody, const double distanceBetweenPrimaries)
Convert dimensionless Cartesian state to dimensional units.
double convertDimensionlessTimeToDimensionalTime (const double timeInDimensionlessUnits, const double gravitationalParameterOfPrimaryBody, const double gravitationalParameterOfSecondaryBody, const double distanceBetweenPrimaries)
Convert dimensionless time to dimensional units.
Typedef Documentation
LibrationPointPointer
typedef std::shared_ptr< LibrationPoint > tudat::circular_restricted_three_body_problem::LibrationPointPointer
Definition at line 219 of file librationPoint.h.
Function Documentation
computeMassParameter()
double tudat::circular_restricted_three_body_problem::computeMassParameter (const double primaryGravitationalParameter, const double secondaryGravitationalParameter) inline
Computes dimensionless mass parameter for the CRTBP.
Parameters
primaryGravitationalParameter Gravitational parameter of primary body.
secondaryGravitationalParameter Gravitational parameter of secondary body.
Returns
Dimensionless mass parameter.
Definition at line 42 of file librationPoint.h.
Referenced by tudat::propagators::propagateCR3BPFromEnvironment(), and tudat::propagators::setupBodySettingsCR3BP().
convertDimensionlessCartesianStateToDimensionalUnits()
Eigen::VectorXd tudat::circular_restricted_three_body_problem::convertDimensionlessCartesianStateToDimensionalUnits (const Eigen::Vector6d & dimensionlessCartesianState, const double gravitationalParameterOfPrimaryBody, const double gravitationalParameterOfSecondaryBody, const double distanceBetweenPrimaries)
Convert dimensionless Cartesian state to dimensional units.
Parameters
dimensionlessCartesianState Dimensionless Cartesian state vector. Order is important! dimensionlessCartesianState(0) = x-position coordinate, [m] dimensionlessCartesianState(1) = y-position coordinate, [m] dimensionlessCartesianState(2) = z-position coordinate, [m] dimensionlessCartesianState(3) = x-velocity coordinate, [m/s] dimensionlessCartesianState(4) = y-velocity coordinate, [m/s] dimensionlessCartesianState(5) = z-velocity coordinate. [m/s]
gravitationalParameterOfPrimaryBody Gravitational parameter of primary body. [m^3 s^-2]
gravitationalParameterOfSecondaryBody Gravitational parameter of secondary body. [m^3 s^-2]
distanceBetweenPrimaries Distance between primaries. [m]
Returns
Dimensional Cartesian state.
Definition at line 30 of file unitConversionsCircularRestrictedThreeBodyProblem.cpp.
Referenced by convertCorotatingNormalizedToCartesianCoordinates().
convertDimensionlessTimeToDimensionalTime()
double tudat::circular_restricted_three_body_problem::convertDimensionlessTimeToDimensionalTime (const double timeInDimensionlessUnits, const double gravitationalParameterOfPrimaryBody, const double gravitationalParameterOfSecondaryBody, const double distanceBetweenPrimaries)
Convert dimensionless time to dimensional units.
Parameters
timeInDimensionlessUnits Time in normalized units.
gravitationalParameterOfPrimaryBody Gravitational parameter of primary body. [m^3 s^-2]
gravitationalParameterOfSecondaryBody Gravitational parameter of secondary body. [m^3 s^-2]
distanceBetweenPrimaries Distance between primaries. [m]
Returns
Dimensional time. [s]
Definition at line 54 of file unitConversionsCircularRestrictedThreeBodyProblem.cpp.
Referenced by tudat::propagators::propagateCR3BPFromEnvironment().
convertDimensionalCartesianStateToDimensionlessState()
Eigen::VectorXd tudat::circular_restricted_three_body_problem::convertDimensionalCartesianStateToDimensionlessState (const Eigen::Vector6d & dimensionalCartesianState, const double gravitationalParameterOfPrimaryBody, const double gravitationalParameterOfSecondaryBody, const double distanceBetweenPrimaries)
Convert dimensional Cartesian state to dimensionless state.
Parameters
dimensionalCartesianState Dimensional Cartesian state vector [m]. Order is important! dimensionalCartesianState(0) = x-position coordinate [m], dimensionalCartesianState(1) = y-position coordinate [m], dimensionalCartesianState(2) = z-position coordinate [m], dimensionalCartesianState(3) = x-velocity coordinate [m/s], dimensionalCartesianState(4) = y-velocity coordinate [m/s], dimensionalCartesianState(5) = z-velocity coordinate [m/s].
gravitationalParameterOfPrimaryBody Gravitational parameter of primary body [m^3 s^-2].
gravitationalParameterOfSecondaryBody Gravitational parameter of secondary body [m^3 s^-2].
distanceBetweenPrimaries Distance between primaries [m].
Returns
Dimensionless Cartesian state.
Definition at line 65 of file unitConversionsCircularRestrictedThreeBodyProblem.cpp.
Referenced by convertCartesianToCorotatingNormalizedCoordinates().
convertDimensionalTimeToDimensionlessTime()
double tudat::circular_restricted_three_body_problem::convertDimensionalTimeToDimensionlessTime (const double dimensionalTime, const double gravitationalParameterOfPrimaryBody, const double gravitationalParameterOfSecondaryBody, const double distanceBetweenPrimaries)
Convert dimensional time to dimensionless time.
Parameters
dimensionalTime Time in dimensional units [s].
gravitationalParameterOfPrimaryBody Gravitational parameter of primary body [m^3 s^-2].
gravitationalParameterOfSecondaryBody Gravitational parameter of secondary body [m^3 s^-2].
distanceBetweenPrimaries Distance between primaries [m].
Returns
Adimensional time.
Definition at line 91 of file unitConversionsCircularRestrictedThreeBodyProblem.cpp.
Referenced by tudat::propagators::propagateCR3BPFromEnvironment().
convertCorotatingNormalizedToCartesianCoordinates()
Eigen::Vector6d tudat::circular_restricted_three_body_problem::convertCorotatingNormalizedToCartesianCoordinates (const double gravitationalParameterPrimary, const double gravitationalParameterSecondary, const double distancePrimarySecondary, const Eigen::Vector6d & normalizedState, const double normalizedTime)
Convert corotating normalized state to inertial cartesian state
Parameters
gravitationalParameterPrimary Gravitational parameter of primary body [m^3 s^-2].
gravitationalParameterSecondary Gravitational parameter of secondary body [m^3 s^-2].
distancePrimarySecondary Distance between primaries [m].
normalizedState Co-rotating normalized state.
normalizedTime Adimensional time.
Returns
Inertial cartesian state. Order is important! x-position coordinate [m], y-position coordinate [m], z-position coordinate [m], x-velocity coordinate [m/s], y-velocity coordinate [m/s], z-velocity coordinate [m/s].
Definition at line 104 of file unitConversionsCircularRestrictedThreeBodyProblem.cpp.
References convertDimensionlessCartesianStateToDimensionalUnits().
Referenced by tudat::propagators::propagateCR3BPFromEnvironment().
convertCartesianToCorotatingNormalizedCoordinates()
Eigen::Vector6d tudat::circular_restricted_three_body_problem::convertCartesianToCorotatingNormalizedCoordinates (const double gravitationalParameterPrimary, const double gravitationalParameterSecondary, const double distancePrimarySecondary, const Eigen::Vector6d & cartesianState, const double time)
Convert inertial cartesian state to co-rotating normalized state.
Parameters
gravitationalParameterPrimary Gravitational parameter of primary body [m^3 s^-2].
gravitationalParameterSecondary Gravitational parameter of secondary body [m^3 s^-2].
distancePrimarySecondary Distance between primaries [m].
cartesianState Inertial cartesian state (x-position coordinate [m], y-position coordinate [m], z-position coordinate [m], x-velocity coordinate [m/s], y-velocity coordinate [m/s], z-velocity coordinate [m/s]).
time Dimensional time [s].
Returns
Co-rotating normalized state.
Definition at line 142 of file unitConversionsCircularRestrictedThreeBodyProblem.cpp.
References convertDimensionalCartesianStateToDimensionlessState(), and tudat::input_output::field_types::state::meanMotion.
Referenced by tudat::propagators::propagateCR3BPFromEnvironment().