Tudat: tudat::acceleration_partials::ConstantTorquePartial Class Reference
tudat::acceleration_partials::ConstantTorquePartial Class Reference
Class to calculate the partials of the effective torque (if all constituent torques are constant) w.r.t. parameters and states.
#include <constantTorquePartial.h>
Public Member Functions
ConstantTorquePartial (const std::function< Eigen::Vector3d() > angularVelocityFunction, const std::function< Eigen::Matrix3d() > inertiaTensorFunction, const std::function< double() > inertiaTensorNormalizationFunction, const std::function< double() > bodyGravitationalParameterFunction, const basic_astrodynamics::SingleBodyTorqueModelMap &torqueVector, const std::string acceleratedBody)
Constructor.
~ConstantTorquePartial ()
Destructor.
std::pair< std::function< void(Eigen::MatrixXd &) >, int > getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function for setting up and retrieving a function returning a partial w.r.t. a double parameter.
std::pair< std::function< void(Eigen::MatrixXd &) >, int > getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function for setting up and retrieving a function returning a partial w.r.t. a vector parameter.
void update (const double currentTime=TUDAT_NAN)
Update partial model to current time.
void wrtOrientationOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the torque w.r.t. the orientation of the accelerated body.
void wrtRotationalVelocityOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=3)
Function for calculating the partial of the torque w.r.t. the angular velocity of the accelerated body.
Public Member Functions inherited from tudat::acceleration_partials::TorquePartial
TorquePartial (const std::string &bodyUndergoingTorque, const std::string &bodyExertingTorque, const basic_astrodynamics::AvailableTorque torqueType)
Base class constructor.
virtual ~TorquePartial ()
Virtual destructor.
std::string getBodyExertingTorque ()
Function to retrieve the name of the body exerting torque.
std::string getBodyUndergoingTorque ()
Function to retrieve the name of the body undergoing torque.
std::pair< std::function< void(Eigen::Block< Eigen::MatrixXd >) >, int > getDerivativeFunctionWrtStateOfIntegratedBody (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function to retrieve the function that returns the partial derivative w.r.t. a propagated state.
basic_astrodynamics::AvailableTorque getTorqueType ()
Function to retrieve the type of torque w.r.t. which partial is taken..
virtual bool isStateDerivativeDependentOnIntegratedAdditionalStateTypes (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function for determining if the torque is dependent on a non-rotational integrated state.
virtual bool isTorquePartialWrtAdditionalBodyNonNull (const std::string &bodyName)
Function to check whether the partial derivative w.r.t. the rotational state of a third body is non-zero.
virtual void wrtNonRotationalStateOfAdditionalBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function for calculating the partial of the torque w.r.t. a non-rotational integrated state.
virtual void wrtOrientationOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Pure virtual function for calculating the partial of the torque w.r.t. the orientation of the body exerting torque.
virtual void wrtOrientationOfAdditionalBody (const std::string &bodyName, Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the torque w.r.t. the orientation of the third body.
void wrtRotationalStateOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function for calculating the partial of the torque w.r.t. the rotational state of the body undergoing torque.
void wrtRotationalStateOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function for calculating the partial of the torque w.r.t. the Cartesian state of the body exerting torque.
void wrtRotationalStateOfAdditionalBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const std::string &bodyName)
Function for calculating the partial of the torque w.r.t. the Cartesian state of the third body.
virtual void wrtRotationalVelocityOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=3)
Function for calculating the partial of the torque w.r.t. the angular velocity of the body exerting torque.
virtual void wrtRotationalVelocityOfAdditionalBody (const std::string &bodyName, Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=3)
Function for calculating the partial of the torque w.r.t. the angular velocity of the third body.
Public Member Functions inherited from tudat::orbit_determination::StateDerivativePartial
StateDerivativePartial (const propagators::IntegratedStateType integratedStateType, const std::pair< std::string, std::string > &integrationReferencePoint)
Constructor.
virtual ~StateDerivativePartial ()
Destructor.
void getCurrentDoubleParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, Eigen::MatrixXd &parameterPartial)
Function to retrieve a partial w.r.t. a double parameter.
void getCurrentParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function to retrieve a partial w.r.t. a double parameter.
void getCurrentParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function to retrieve a partial w.r.t. a vector parameter.
void getCurrentVectorParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, Eigen::MatrixXd &parameterPartial)
Function to retrieve a partial w.r.t. a vector parameter.
propagators::IntegratedStateType getIntegratedStateType ()
Function to get the type of state for which partials are to be computed.
std::pair< std::string, std::string > getIntegrationReferencePoint ()
Function to get the identifier for body/reference point for which propagation is performed.
void resetTime (const double currentTime=TUDAT_NAN)
Function to reset the object to the current time.
virtual int setParameterPartialUpdateFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function to set a dependency of this partial object w.r.t. a given double parameter.
virtual int setParameterPartialUpdateFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function to set a dependency of this partial object w.r.t. a given vector parameter.
void updateParameterPartials ()
Function to update the values partial derivatives to current state and time.
Eigen::MatrixXd wrtParameter (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function to directly compute the partial of the state derivative w.r.t. a double parameter.
Eigen::MatrixXd wrtParameter (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function to directly compute the partial of the state derivative w.r.t. a vector parameter.
Protected Member Functions
void wrtCosineSphericalHarmonicCoefficientsOfCentralBody (Eigen::MatrixXd &sphericalHarmonicCoefficientPartial, const int c20Index, const int c21Index, const int c22Index)
Function to compute partial of torque w.r.t. spherical harmonic cosine coefficients.
void wrtGravitationalParameter (Eigen::MatrixXd &gravitationalParameterPartial)
Function to compute partial of torque w.r.t. gravitational parameter.
void wrtMeanMomentOfInertia (Eigen::MatrixXd &momentOfInertiaPartial)
Function to compute partial of torque w.r.t. mean moment of inertia.
void wrtSineSphericalHarmonicCoefficientsOfCentralBody (Eigen::MatrixXd &sphericalHarmonicCoefficientPartial, const int s21Index, const int s22Index)
Function to compute partial of torque w.r.t. spherical harmonic sine coefficients.
Protected Member Functions inherited from tudat::orbit_determination::StateDerivativePartial
void resetCurrentParameterValues ()
Function to define all current parameter partials as 'not computed'.
virtual void resetTimeOfMemberObjects ()
Function to reset the member object to the current time.
virtual void updateParameterPartialsOfMemberObjects ()
Function to compute parameter partials of member objects.
Protected Attributes
std::function< Eigen::Vector3d() > angularVelocityFunction_
Function returning body angular velocity vector in body fixed frame.
std::function< double() > bodyGravitationalParameterFunction_
Function returning body gravitational parameter.
Eigen::Vector3d currentAngularVelocityVector_
Current angular velocity vector.
Eigen::Matrix3d currentInertiaTensor_
Current inertia tensor.
double currentInertiaTensorNormalizationFactor_
Current inertia tensor normalization.
Eigen::Matrix3d currentInverseInertiaTensor_
Current inverse inertia tensor.
Eigen::Matrix3d currentPartialDerivativeWrtAngularVelocity_
Current partial derivative w.r.t. angular velocity vector.
Eigen::Vector3d currentTotalTorque_
Current total torque acting on body.
std::function< double() > getInertiaTensorNormalizationFactor_
Function the inertia tensor normalization factor.
std::function< Eigen::Matrix3d() > inertiaTensorFunction_
Function returning body inertia tensor.
basic_astrodynamics::SingleBodyTorqueModelMap torqueVector_
List of torques acting on body.
Protected Attributes inherited from tudat::acceleration_partials::TorquePartial
std::string bodyExertingTorque_
Name of the body exerting torque.
std::string bodyUndergoingTorque_
Name of the body undergoing torque.
basic_astrodynamics::AvailableTorque torqueType_
Type of torque w.r.t. which partial is taken..
Protected Attributes inherited from tudat::orbit_determination::StateDerivativePartial
int accelerationSize_
Size of the single order state derivative model (i.e. 3 for translational dynamics).
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, Eigen::MatrixXd > currentDoubleParameterPartials_
List of current values of partials w.r.t. double parameter values (emptied at beginning of every time step).
double currentTime_
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, Eigen::MatrixXd > currentVectorParameterPartials_
List of current values of partials w.r.t. double parameter values (emptied at beginning of every time step).
propagators::IntegratedStateType integratedStateType_
Type of state for which partials are to be computed.
std::pair< std::string, std::string > integrationReferencePoint_
Identifier for body/reference point for which propagation is performed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, bool > isCurrentDoubleParameterPartialSet_
List of booleans defining whether the partial w.r.t. the current double parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, bool >::iterator isCurrentDoubleParameterPartialSetIterator_
Iterator for list defining whether the partial w.r.t. the current double parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, bool > isCurrentVectorParameterPartialSet_
List of booleans defining whether the partial w.r.t. the current vector parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, bool >::iterator isCurrentVectorParameterPartialSetIterator_
Iterator for list defining whether the partial w.r.t. the current vector parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::function< void(Eigen::MatrixXd &) > >::iterator parameterDoublePartialFunctionIterator_
Iterator over list of functions to compute values of partials w.r.t. double parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::function< void(Eigen::MatrixXd &) > > parameterDoublePartialFunctions_
List of functions to compute (return by reference) values of partials w.r.t. doule parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::function< void(Eigen::MatrixXd &) > >::iterator parameterVectorPartialFunctionIterator_
Iterator over list of functions to compute values of partials w.r.t. vector parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::function< void(Eigen::MatrixXd &) > > parameterVectorPartialFunctions_
List of functions to compute (return by reference) values of partials w.r.t. vector parameter partials.
Detailed Description
Class to calculate the partials of the effective torque (if all constituent torques are constant) w.r.t. parameters and states. Terms in the model are a result of the face that the derivative of angular acceleration is premultiplied by I^-1, for which partial derivatives must be computed
Definition at line 33 of file constantTorquePartial.h.
Constructor & Destructor Documentation
ConstantTorquePartial()
tudat::acceleration_partials::ConstantTorquePartial::ConstantTorquePartial (const std::function< Eigen::Vector3d() > angularVelocityFunction, const std::function< Eigen::Matrix3d() > inertiaTensorFunction, const std::function< double() > inertiaTensorNormalizationFunction, const std::function< double() > bodyGravitationalParameterFunction, const basic_astrodynamics::SingleBodyTorqueModelMap & torqueVector, const std::string acceleratedBody) inline
Constructor
Parameters
angularVelocityFunction Function returning body angular velocity vector in body fixed frame.
inertiaTensorFunction Function returning body inertia tensor
inertiaTensorNormalizationFunction Function the inertia tensor normalization factor
bodyGravitationalParameterFunction Function returning body gravitational parameter
torqueVector List of torques acting on body
acceleratedBody Name of body undergoing torque
Definition at line 48 of file constantTorquePartial.h.
~ConstantTorquePartial()
tudat::acceleration_partials::ConstantTorquePartial::~ConstantTorquePartial () inline
Definition at line 63 of file constantTorquePartial.h.
References getParameterPartialFunction().
Member Function Documentation
getParameterPartialFunction() [1/2]
std::pair< std::function< void(Eigen::MatrixXd &) >, int > tudat::acceleration_partials::ConstantTorquePartial::getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter) virtual
Function for setting up and retrieving a function returning a partial w.r.t. a double parameter. Function returns empty function and zero size indicator for parameters with no dependency for current torque.
Parameters
parameter Parameter w.r.t. which partial is to be taken.
Returns
Pair of parameter partial function and number of columns in partial (0 for no dependency, 1 otherwise).
Reimplemented from tudat::orbit_determination::StateDerivativePartial.
Definition at line 22 of file constantTorquePartial.cpp.
References bodyGravitationalParameterFunction_, tudat::acceleration_partials::TorquePartial::bodyUndergoingTorque_, getInertiaTensorNormalizationFactor_, tudat::estimatable_parameters::gravitational_parameter, tudat::estimatable_parameters::mean_moment_of_inertia, wrtGravitationalParameter(), and wrtMeanMomentOfInertia().
Referenced by ~ConstantTorquePartial().
getParameterPartialFunction() [2/2]
std::pair< std::function< void(Eigen::MatrixXd &) >, int > tudat::acceleration_partials::ConstantTorquePartial::getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter) virtual
Function for setting up and retrieving a function returning a partial w.r.t. a vector parameter. Function returns empty function and zero size indicator for parameters with no dependency for current torque.
Parameters
parameter Parameter w.r.t. which partial is to be taken.
Returns
Pair of parameter partial function and number of columns in partial (0 for no dependency).
Reimplemented from tudat::orbit_determination::StateDerivativePartial.
Definition at line 63 of file constantTorquePartial.cpp.
References tudat::acceleration_partials::TorquePartial::bodyUndergoingTorque_, getInertiaTensorNormalizationFactor_, tudat::estimatable_parameters::spherical_harmonics_cosine_coefficient_block, tudat::estimatable_parameters::spherical_harmonics_sine_coefficient_block, wrtCosineSphericalHarmonicCoefficientsOfCentralBody(), and wrtSineSphericalHarmonicCoefficientsOfCentralBody().
wrtOrientationOfAcceleratedBody()
void tudat::acceleration_partials::ConstantTorquePartial::wrtOrientationOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 0) inline virtual
Function for calculating the partial of the torque w.r.t. the orientation of the accelerated body and adding it to the existing partial block.
Parameters
partialMatrix Block of partial derivatives of torque w.r.t. Orientation of body undergoing torque where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Implements tudat::acceleration_partials::TorquePartial.
Definition at line 95 of file constantTorquePartial.h.
wrtRotationalVelocityOfAcceleratedBody()
void tudat::acceleration_partials::ConstantTorquePartial::wrtRotationalVelocityOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 3) inline virtual
Function for calculating the partial of the torque w.r.t. the angular velocity of the accelerated body and adding it to the existing partial block.
Parameters
partialMatrix Block of partial derivatives of torque w.r.t. angular velocity of body undergoing torque where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Reimplemented from tudat::acceleration_partials::TorquePartial.
Definition at line 110 of file constantTorquePartial.h.
update()
void tudat::acceleration_partials::ConstantTorquePartial::update (const double currentTime = TUDAT_NAN) inline virtual
Update partial model to current time, retrieving information from consituent functions
Parameters
currentTime Time to which partial is to be updated
Implements tudat::orbit_determination::StateDerivativePartial.
Definition at line 120 of file constantTorquePartial.h.
References currentInertiaTensor_, currentInertiaTensorNormalizationFactor_, currentInverseInertiaTensor_, tudat::orbit_determination::StateDerivativePartial::currentTime_, currentTotalTorque_, getInertiaTensorNormalizationFactor_, inertiaTensorFunction_, torqueVector_, wrtCosineSphericalHarmonicCoefficientsOfCentralBody(), wrtGravitationalParameter(), wrtMeanMomentOfInertia(), and wrtSineSphericalHarmonicCoefficientsOfCentralBody().
wrtMeanMomentOfInertia()
void tudat::acceleration_partials::ConstantTorquePartial::wrtMeanMomentOfInertia (Eigen::MatrixXd & momentOfInertiaPartial) protected
Function to compute partial of torque w.r.t. mean moment of inertia
Parameters
momentOfInertiaPartial Computed partial of torque w.r.t. mean moment of inertia (returned by reference)
Definition at line 131 of file constantTorquePartial.cpp.
References currentInertiaTensorNormalizationFactor_, currentInverseInertiaTensor_, currentTotalTorque_, and tudat::acceleration_partials::UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_MEAN_MOMENT.
Referenced by getParameterPartialFunction(), and update().
wrtGravitationalParameter()
void tudat::acceleration_partials::ConstantTorquePartial::wrtGravitationalParameter (Eigen::MatrixXd & gravitationalParameterPartial) protected
Function to compute partial of torque w.r.t. gravitational parameter
Parameters
gravitationalParameterPartial Computed partial of torque w.r.t. gravitational parameter (returned by reference)
Definition at line 140 of file constantTorquePartial.cpp.
References bodyGravitationalParameterFunction_, currentInertiaTensor_, currentInverseInertiaTensor_, and currentTotalTorque_.
Referenced by getParameterPartialFunction(), and update().
wrtCosineSphericalHarmonicCoefficientsOfCentralBody()
void tudat::acceleration_partials::ConstantTorquePartial::wrtCosineSphericalHarmonicCoefficientsOfCentralBody (Eigen::MatrixXd & sphericalHarmonicCoefficientPartial, const int c20Index, const int c21Index, const int c22Index) protected
Function to compute partial of torque w.r.t. spherical harmonic cosine coefficients
Parameters
sphericalHarmonicCoefficientPartial Computed partial of torque w.r.t. spherical harmonic cosine coefficients (returned by reference)
c20Index for degree=2,order=0 coefficient
c21Index for degree=2,order=1 coefficient
c22Index for degree=2,order=2 coefficient
Definition at line 149 of file constantTorquePartial.cpp.
References tudat::basic_mathematics::calculateLegendreGeodesyNormalizationFactor(), currentInertiaTensorNormalizationFactor_, currentInverseInertiaTensor_, currentTotalTorque_, tudat::acceleration_partials::UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_C20, tudat::acceleration_partials::UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_C21, and tudat::acceleration_partials::UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_C22.
Referenced by getParameterPartialFunction(), and update().
wrtSineSphericalHarmonicCoefficientsOfCentralBody()
void tudat::acceleration_partials::ConstantTorquePartial::wrtSineSphericalHarmonicCoefficientsOfCentralBody (Eigen::MatrixXd & sphericalHarmonicCoefficientPartial, const int s21Index, const int s22Index) protected
Function to compute partial of torque w.r.t. spherical harmonic sine coefficients
Parameters
sphericalHarmonicCoefficientPartial Computed partial of torque w.r.t. spherical harmonic sine coefficients (returned by reference)
s21Index for degree=2,order=1 coefficient
s22Index for degree=2,order=2 coefficient
Definition at line 181 of file constantTorquePartial.cpp.
References tudat::basic_mathematics::calculateLegendreGeodesyNormalizationFactor(), currentInertiaTensorNormalizationFactor_, currentInverseInertiaTensor_, currentTotalTorque_, tudat::acceleration_partials::UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_S21, and tudat::acceleration_partials::UNSCALED_INERTIAL_TENSOR_PARTIAL_WRT_S22.
Referenced by getParameterPartialFunction(), and update().
Member Data Documentation
angularVelocityFunction_
std::function< Eigen::Vector3d() > tudat::acceleration_partials::ConstantTorquePartial::angularVelocityFunction_ protected
Definition at line 185 of file constantTorquePartial.h.
inertiaTensorFunction_
std::function< Eigen::Matrix3d() > tudat::acceleration_partials::ConstantTorquePartial::inertiaTensorFunction_ protected
Definition at line 188 of file constantTorquePartial.h.
Referenced by update().
torqueVector_
basic_astrodynamics::SingleBodyTorqueModelMap tudat::acceleration_partials::ConstantTorquePartial::torqueVector_ protected
Definition at line 191 of file constantTorquePartial.h.
Referenced by update().
getInertiaTensorNormalizationFactor_
std::function< double() > tudat::acceleration_partials::ConstantTorquePartial::getInertiaTensorNormalizationFactor_ protected
Definition at line 194 of file constantTorquePartial.h.
Referenced by getParameterPartialFunction(), and update().
bodyGravitationalParameterFunction_
std::function< double() > tudat::acceleration_partials::ConstantTorquePartial::bodyGravitationalParameterFunction_ protected
Definition at line 197 of file constantTorquePartial.h.
Referenced by getParameterPartialFunction(), and wrtGravitationalParameter().
currentTotalTorque_
Eigen::Vector3d tudat::acceleration_partials::ConstantTorquePartial::currentTotalTorque_ protected
Definition at line 200 of file constantTorquePartial.h.
Referenced by update(), wrtCosineSphericalHarmonicCoefficientsOfCentralBody(), wrtGravitationalParameter(), wrtMeanMomentOfInertia(), and wrtSineSphericalHarmonicCoefficientsOfCentralBody().
currentAngularVelocityVector_
Eigen::Vector3d tudat::acceleration_partials::ConstantTorquePartial::currentAngularVelocityVector_ protected
Definition at line 203 of file constantTorquePartial.h.
currentInertiaTensor_
Eigen::Matrix3d tudat::acceleration_partials::ConstantTorquePartial::currentInertiaTensor_ protected
Definition at line 206 of file constantTorquePartial.h.
Referenced by update(), and wrtGravitationalParameter().
currentInverseInertiaTensor_
Eigen::Matrix3d tudat::acceleration_partials::ConstantTorquePartial::currentInverseInertiaTensor_ protected
Definition at line 209 of file constantTorquePartial.h.
Referenced by update(), wrtCosineSphericalHarmonicCoefficientsOfCentralBody(), wrtGravitationalParameter(), wrtMeanMomentOfInertia(), and wrtSineSphericalHarmonicCoefficientsOfCentralBody().
currentPartialDerivativeWrtAngularVelocity_
Eigen::Matrix3d tudat::acceleration_partials::ConstantTorquePartial::currentPartialDerivativeWrtAngularVelocity_ protected
Definition at line 212 of file constantTorquePartial.h.
currentInertiaTensorNormalizationFactor_
double tudat::acceleration_partials::ConstantTorquePartial::currentInertiaTensorNormalizationFactor_ protected
Definition at line 215 of file constantTorquePartial.h.
Referenced by update(), wrtCosineSphericalHarmonicCoefficientsOfCentralBody(), wrtMeanMomentOfInertia(), and wrtSineSphericalHarmonicCoefficientsOfCentralBody().
The documentation for this class was generated from the following files:
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/OrbitDetermination/RotationalDynamicsPartials/constantTorquePartial.h
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/OrbitDetermination/RotationalDynamicsPartials/constantTorquePartial.cpp