Tudat: tudat::observation_partials Namespace Reference
tudat::observation_partials Namespace Reference
Classes
class AngularPositionPartial
Class to compute the partial derivatives of a angular position observation partial.
class AngularPositionScaling
Derived class for scaling three-dimensional position partial to angular position observable partial.
class CartesianPartialWrtBodyFixedPosition
class CartesianStatePartial
Base class for calculating the partial of an inertial position wrt a parameter.
class CartesianStatePartialWrtCartesianState
class CartesianStatePartialWrtRotationMatrixParameter
class DifferencedOneWayRangeRatePartial
Class to compute the partial derivatives of a one-way range-rate (differenced) observation.
class EulerAngleObervationPartialWrtCurrentRotationalState
Class to compute the partial derivatives of a 3-1-3 Euler angle observable.
class FirstOrderRelativisticLightTimeCorrectionPartial
Class for computing the partial derivatives of 1st-order relativistic light-time correction.
class LightTimeCorrectionPartial
Base class for computing the partial derivatives of light-time corrections w.r.t. estimated parameters.
class NWayRangePartial
Class to compute the partial derivatives of an n-way range observation partial.
class NWayRangeScaling
Derived class for scaling three-dimensional position partial to n-way range observable partial.
class ObservationPartial
Base class of partial derivative of an observable w.r.t. an estimated parameter.
class ObservationPartialCreator
Interface class for creating observation partials.
class ObservationPartialCreator< 1, ObservationScalarType, TimeType >
Interface class for creating observation partials for observables of size 1.
class ObservationPartialCreator< 2, ObservationScalarType, TimeType >
Interface class for creating observation partials for observables of size 2.
class ObservationPartialCreator< 3, ObservationScalarType, TimeType >
Interface class for creating observation partials for observables of size 3.
class ObservationPartialCreator< 6, ObservationScalarType, TimeType >
Interface class for creating observation partials for observables of size 3.
class ObservationPartialCreator< Eigen::Dynamic, ObservationScalarType, TimeType >
Interface class for creating observation partials for observables of dynamic sizwe.
class ObservationPartialWrtArcWiseAbsoluteBias
Class for computing the derivative of any observable w.r.t. an arc-wise constant absolute observation bias.
class ObservationPartialWrtArcWiseRelativeBias
Class for computing the derivative of any observable w.r.t. an arc-wise constant relative observation bias.
class ObservationPartialWrtConstantAbsoluteBias
Class for computing the derivative of any observable w.r.t. a constant absolute observation bias.
class ObservationPartialWrtConstantRelativeBias
Class for computing the derivative of any observable w.r.t. a constant relative observation bias.
class OneWayDopplerDirectFirstOrderProperTimeComponentScaling
Class to compute the state partial scaling factors for first-order proper time component of one-way Doppler observables.
class OneWayDopplerPartial
Class to compute the partial derivatives of a one-way doppler observation partial.
class OneWayDopplerProperTimeComponentScaling
Base class to compute the state partial scaling factors for the proper time component of one-way Doppler observables.
class OneWayDopplerScaling
Derived class for scaling three-dimensional position partial to one-way doppler observable partial.
class OneWayRangePartial
Class to compute the partial derivatives of a one-way range observation partial.
class OneWayRangeRateScaling
Derived class for scaling three-dimensional position partial to one-way range-rate (differenced) observable partial.
class OneWayRangeScaling
Derived class for scaling three-dimensional position partial to one-way range observable partial.
class PositionObervationPartial
Class to compute the partial derivatives of a three-dimensional position observable.
class PositionObservationScaling
Derived class for scaling three-dimensional position partial to position observable partial.
class PositionPartialScaling
Base class for scaling position partials to observable partials.
class RotationMatrixPartial
Base class for partial derivatives of rotation matrix from body fixed to inertial frame w.r.t. a parameter.
class RotationMatrixPartialWrtConstantRotationRate
Class to calculate a rotation matrix from a body-fixed to inertial frame w.r.t. a constant rotation rate.
class RotationMatrixPartialWrtCoreFactor
Class to calculate a rotation matrix from a body-fixed to inertial frame w.r.t. the core factor.
class RotationMatrixPartialWrtFreeCoreNutationRate
Class to calculate a rotation matrix from a body-fixed to inertial frame w.r.t. the free core nutation rate.
class RotationMatrixPartialWrtPeriodicSpinVariations
Class to calculate a rotation matrix from a body-fixed to inertial frame w.r.t. the periodic spin variations.
class RotationMatrixPartialWrtPolarMotionAmplitude
Class to calculate a rotation matrix from a body-fixed to inertial frame w.r.t. polar motion amplitudes.
class RotationMatrixPartialWrtPoleOrientation
Class to calculate a rotation matrix from a body-fixed to inertial frame, as computed by the SimpleRotationalEphemeris class, w.r.t.
class RotationMatrixPartialWrtQuaternion
Class to calculate a rotation matrix from a body-fixed to inertial frame w.r.t. the associated quaternion elements.
class RotationMatrixPartialWrtRotationalState
Class to calculate a rotation matrix from a body-fixed to inertial frame w.r.t. the rotational state.
class SynchronousRotationMatrixPartialWrtTranslationalState
Class to calculate a rotation matrix from a body-fixed to inertial frame w.r.t. the translational state for synchronous rotation.
class TwoWayDopplerPartial
Class to compute the partial derivatives of an two-way range observation partial.
class TwoWayDopplerScaling
class VelocityObervationPartial
Class to compute the partial derivatives of a three-dimensional velocity observable.
class VelocityObservationScaling
Derived class for scaling three-dimensional velocity partial to velocity observable partial.
Typedefs
typedef std::map< observation_models::LinkEnds, std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > > > PerLinkEndPerLightTimeSolutionCorrections
Typedef for list of light time corrections for a list of link ends.
typedef std::map< std::pair< estimatable_parameters::EstimatebleParametersEnum, std::string >, std::shared_ptr< observation_partials::RotationMatrixPartial > > RotationMatrixPartialNamedList
Typedef of list of RotationMatrixPartial objects, ordered by parameter.
typedef std::map< std::pair< int, int >, std::shared_ptr< ObservationPartial< 1 > > > SingleLinkObservationPartialList
Typedef for map of observation partials.
typedef std::map< std::pair< int, int >, std::shared_ptr< ObservationPartial< 3 > > > SingleLinkObservationThreePartialList
Typedef for map of observation partials.
typedef std::map< std::pair< int, int >, std::shared_ptr< ObservationPartial< 2 > > > SingleLinkObservationTwoPartialList
Typedef for map of observation partials.
Functions
Eigen::Matrix< double, 2, 3 > calculatePartialOfAngularPositionWrtLinkEndPosition (Eigen::Vector3d relativeRangeVector, const bool isLinkEndReceiver)
Function to compute the derivative of (direct geometric) right ascension and declination w.r.t.
Eigen::Matrix< double, 1, 3 > calculatePartialOfDeclinationWrtLinkEndPosition (Eigen::Vector3d relativeRangeVector, const bool isLinkEndReceiver)
Function to compute the derivative of (direct geometric) declination w.r.t. position of observer or observed object.
Eigen::Matrix3d calculatePartialOfPointPositionWrtBodyFixedPointPosition (const Eigen::Matrix3d &rotationMatrixToInertialFrame)
Function to calculate the partial of position of a point on a body wrt its body-fixed position.
Eigen::Matrix3d calculatePartialOfPointPositionWrtBodyPosition ()
Function to calculate the partial of position of a point on or in a body wrt position of that body.
Eigen::Matrix< double, 1, 3 > calculatePartialOfRightAscensionWrtLinkEndPosition (const Eigen::Vector3d &relativeRangeVector, const bool isLinkEndReceiver)
Function to compute the derivative of (direct geometric) right ascension w.r.t. position of observer or observed object.
Eigen::Matrix3d calculatePartialOfRotationMatrixFromLocalFrameDerivativeWrtConstantRotationRate (const Eigen::Matrix3d currentRotationFromLocalToGlobalFrame, const double rotationRate, const double timeSinceEpoch)
Function to calculate partial of a rotation matrix derivative (body-fixed to inertial) w.r.t. a constant rotation rate.
Eigen::Matrix3d calculatePartialOfRotationMatrixFromLocalFrameDerivativeWrtCoreFactor (const std::shared_ptr< ephemerides::PlanetaryOrientationAngleCalculator > planetaryOrientationCalculator, const Eigen::Quaterniond &rotationFromMeanOrbitToIcrf, const Eigen::Quaterniond &polarMotionRotation, const double ephemerisTime)
Function to calculate a partial of rotation matrix derivative from a body-fixed to inertial frame, as computed by the PlanetaryRotationModel class, w.r.t.
Eigen::Matrix3d calculatePartialOfRotationMatrixFromLocalFrameDerivativeWrtFreeCoreNutationRate (const std::shared_ptr< ephemerides::PlanetaryOrientationAngleCalculator > planetaryOrientationCalculator, const Eigen::Quaterniond &rotationFromMeanOrbitToIcrf, const Eigen::Quaterniond &polarMotionRotation, const double ephemerisTime)
Function to calculate a partial of rotation matrix derivative from a body-fixed to inertial frame, as computed by the PlanetaryRotationModel class, w.r.t.
std::vector< Eigen::Matrix3d > calculatePartialOfRotationMatrixFromLocalFrameDerivativeWrtPeriodicSpinVariations (const std::shared_ptr< ephemerides::PlanetaryOrientationAngleCalculator > planetaryOrientationCalculator, const Eigen::Quaterniond &rotationFromMeanOrbitToIcrf, const Eigen::Quaterniond &polarMotionRotation, const double ephemerisTime)
Function to calculate a partial of rotation matrix derivative from a body-fixed to inertial frame, as computed by the PlanetaryRotationModel class, w.r.t.
std::vector< Eigen::Matrix3d > calculatePartialOfRotationMatrixFromLocalFrameDerivativeWrtPolarMotionAmplitude (const std::shared_ptr< ephemerides::PlanetaryOrientationAngleCalculator > planetaryOrientationCalculator, const Eigen::Quaterniond &rotationFromMeanOrbitToIcrf, const double ephemerisTime)
Function to calculate a partial of rotation matrix derivative from a body-fixed to inertial frame, as computed by the PlanetaryRotationModel class, w.r.t.
std::vector< Eigen::Matrix3d > calculatePartialOfRotationMatrixFromLocalFrameDerivativeWrtPoleOrientation (const Eigen::Vector3d initialOrientationAngles, const double rotationRate, const double timeSinceEpoch)
Function to calculate a partial of rotation matrix derivative from a body-fixed to inertial frame, as computed by the SimpleRotationalEphemeris class, w.r.t.
Eigen::Matrix3d calculatePartialOfRotationMatrixFromLocalFrameWrtConstantRotationRate (const Eigen::Quaterniond initialBodyFixedToIntegrationFrame, const double rotationRate, const double timeSinceEpoch)
Function to calculate a partial of rotation matrix from a body-fixed to inertial frame w.r.t. a constant rotation rate.
Eigen::Matrix3d calculatePartialOfRotationMatrixFromLocalFrameWrtCoreFactor (const std::shared_ptr< ephemerides::PlanetaryOrientationAngleCalculator > planetaryOrientationCalculator, const Eigen::Quaterniond &rotationFromMeanOrbitToIcrf, const Eigen::Quaterniond &polarMotionRotation, const double ephemerisTime)
Function to calculate a partial of rotation matrix from a body-fixed to inertial frame, as computed by the PlanetaryRotationModel class, w.r.t.
Eigen::Matrix3d calculatePartialOfRotationMatrixFromLocalFrameWrtFreeCoreNutationRate (const std::shared_ptr< ephemerides::PlanetaryOrientationAngleCalculator > planetaryOrientationCalculator, const Eigen::Quaterniond &rotationFromMeanOrbitToIcrf, const Eigen::Quaterniond &polarMotionRotation, const double ephemerisTime)
Function to calculate a partial of rotation matrix from a body-fixed to inertial frame, as computed by the PlanetaryRotationModel class, w.r.t.
std::vector< Eigen::Matrix3d > calculatePartialOfRotationMatrixFromLocalFrameWrtPeriodicSpinVariations (const std::shared_ptr< ephemerides::PlanetaryOrientationAngleCalculator > planetaryOrientationCalculator, const Eigen::Quaterniond &rotationFromMeanOrbitToIcrf, const Eigen::Quaterniond &polarMotionRotation, const double ephemerisTime)
Function to calculate a partial of rotation matrix from a body-fixed to inertial frame, as computed by the PlanetaryRotationModel class, w.r.t.
std::vector< Eigen::Matrix3d > calculatePartialOfRotationMatrixFromLocalFrameWrtPolarMotionAmplitude (const std::shared_ptr< ephemerides::PlanetaryOrientationAngleCalculator > planetaryOrientationCalculator, const Eigen::Quaterniond &rotationFromMeanOrbitToIcrf, const Eigen::Quaterniond &rotationFromBodyFixedToIntermediateInertialFrame, const double ephemerisTime)
Function to calculate a partial of rotation matrix from a body-fixed to inertial frame, as computed by the PlanetaryRotationModel class, w.r.t.
std::vector< Eigen::Matrix3d > calculatePartialOfRotationMatrixFromLocalFrameWrtPoleOrientation (const Eigen::Vector3d initialOrientationAngles, const double rotationRate, const double timeSinceEpoch)
Function to calculate a partial of rotation matrix from a body-fixed to inertial frame, as computed by the SimpleRotationalEphemeris class, w.r.t.
double computePartialOfProjectedLinkEndVelocityWrtAssociatedTime (const Eigen::Vector3d &vectorToReceiver, const Eigen::Vector3d &projectedLinkEndVelocity, const Eigen::Vector3d &variableLinkEndVelocity, const Eigen::Vector3d &projectedLinkEndAcceleration, const bool linkEndIsReceiver, const bool projectedLinkEndIsVariableLinkEnd)
Function to computed the derivative of velocity component along line-of-sight vector w.r.t. the observation time.
Eigen::Vector3d computePartialOfUnitVectorWrtLinkEndTime (const Eigen::Vector3d &vectorToReceiver, const Eigen::Vector3d &unitVectorToReceiver, const double linkEndDistance, const Eigen::Vector3d linkEndVelocity)
Function to computed the derivative of the unit vector from transmitter to receiver w.r.t. the observation time.
template<typename ParameterType >
std::pair< std::map< std::pair< int, int >, std::shared_ptr< ObservationPartial< 2 > > >, std::shared_ptr< PositionPartialScaling > > createAngularPositionPartials (const observation_models::LinkEnds angularPositionLinkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > &lightTimeCorrections=std::vector< std::shared_ptr< observation_models::LightTimeCorrection > >())
Function to generate angular position partials and associated scaler for single link end.
template<typename ParameterType >
std::map< observation_models::LinkEnds, std::pair< SingleLinkObservationTwoPartialList, std::shared_ptr< PositionPartialScaling > > > createAngularPositionPartials (const std::vector< observation_models::LinkEnds > linkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const std::map< observation_models::LinkEnds, std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > > > &lightTimeCorrections=std::map< observation_models::LinkEnds, std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > > >())
Function to generate angular position partials for all parameters that are to be estimated, for all sets of link ends.
std::shared_ptr< AngularPositionPartial > createAngularPositionPartialWrtBodyPosition (const observation_models::LinkEnds angularPositionLinkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::string bodyToEstimate, const std::shared_ptr< AngularPositionScaling > angularPositionScaler, const std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > > &lightTimeCorrectionPartialObjects)
Function to generate angular position partial wrt a position of a body.
template<typename ParameterType >
std::shared_ptr< AngularPositionPartial > createAngularPositionPartialWrtParameter (const observation_models::LinkEnds angularPositionLinkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameter< ParameterType > > parameterToEstimate, const std::shared_ptr< AngularPositionScaling > angularPositionScaler, const std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > > &lightTimeCorrectionPartialObjects=std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > >())
Function to generate angular position partial wrt a single parameter.
std::map< observation_models::LinkEndType, std::shared_ptr< CartesianStatePartial > > createCartesianStatePartialsWrtBodyRotationalState (const observation_models::LinkEnds &linkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::string &bodyToEstimate)
Function to return partial(s) of position of ground station(s) w.r.t. rotational state of a single body.
std::map< observation_models::LinkEndType, std::shared_ptr< CartesianStatePartial > > createCartesianStatePartialsWrtBodyState (const observation_models::LinkEnds &linkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::string bodyToEstimate)
Function to return partial(s) of position of ground station(s) w.r.t. state of a single body.
std::map< observation_models::LinkEndType, std::shared_ptr< CartesianStatePartial > > createCartesianStatePartialsWrtParameter (const observation_models::LinkEnds linkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameterToEstimate)
Function to return partial object(s) of position of reference point w.r.t. a (double) parameter.
std::map< observation_models::LinkEndType, std::shared_ptr< CartesianStatePartial > > createCartesianStatePartialsWrtParameter (const observation_models::LinkEnds linkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameterToEstimate)
Function to return partial(s) of position of ground station(s) w.r.t. a (vector) parameter.
template<typename ParameterType >
std::map< observation_models::LinkEnds, std::pair< SingleLinkObservationPartialList, std::shared_ptr< PositionPartialScaling > > > createDifferencedOneWayRangeRatePartials (const std::vector< observation_models::LinkEnds > linkEnds, const simulation_setup::NamedBodyMap bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const PerLinkEndPerLightTimeSolutionCorrections &lightTimeCorrections=PerLinkEndPerLightTimeSolutionCorrections())
Function to generate one-way differenced range partials for all parameters that are to be estimated, for all sets of link ends.
std::shared_ptr< OneWayDopplerProperTimeComponentScaling > createDopplerProperTimePartials (const std::shared_ptr< observation_models::DopplerProperTimeRateInterface > dopplerProperTimeInterface, const observation_models::LinkEnds oneWayDopplerLinkEnds, const observation_models::LinkEndType linkEndAtWhichPartialIsComputed)
Function to create an object that computes the scaling of the state partials to obtain proper time rate partials.
template<typename ParameterType >
std::pair< SingleLinkObservationThreePartialList, std::shared_ptr< PositionPartialScaling > > createEulerAngleObservablePartials (const observation_models::LinkEnds eulerAngleLinkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate)
Function to compute Euler angle observation partial objects for a single set of link ends.
template<typename ParameterType >
std::map< observation_models::LinkEnds, std::pair< SingleLinkObservationThreePartialList, std::shared_ptr< PositionPartialScaling > > > createEulerAngleObservablePartials (const std::vector< observation_models::LinkEnds > linkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate)
Function to compute Euler angle observation partial objects for multiple sets of link ends.
std::shared_ptr< ObservationPartial< 3 > > createEulerAngleObservablePartialWrtCurrentRotationalState (const estimatable_parameters::EstimatebleParameterIdentifier parameterIdentifier)
Function to generate one-way range partial wrt an initial position of a body.
std::vector< std::shared_ptr< LightTimeCorrectionPartial > > createLightTimeCorrectionPartials (const std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > &lightTimeCorrectionList)
Function to create a partial objects from list of light time corrections.
template<typename ParameterType >
std::pair< SingleLinkObservationPartialList, std::shared_ptr< PositionPartialScaling > > createNWayRangePartials (const observation_models::LinkEnds &nWayRangeLinkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > > lightTimeCorrections=std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > >())
Function to generate n-way range partials and associated scaler for single link ends.
template<typename ParameterType >
std::map< observation_models::LinkEnds, std::pair< SingleLinkObservationPartialList, std::shared_ptr< PositionPartialScaling > > > createNWayRangePartials (const std::vector< observation_models::LinkEnds > &linkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const std::map< observation_models::LinkEnds, std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > > > &lightTimeCorrections=std::map< observation_models::LinkEnds, std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > > >())
Function to generate n-way range partials for all parameters that are to be estimated, for all sets of link ends.
template<int ObservationSize>
std::shared_ptr< ObservationPartial< ObservationSize > > createObservationPartialWrtLinkProperty (const observation_models::LinkEnds &linkEnds, const observation_models::ObservableType observableType, const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameterToEstimate, const bool useBiasPartials=true)
Function to create partials of observation w.r.t. a link property.
template<typename ParameterType >
std::pair< SingleLinkObservationPartialList, std::shared_ptr< PositionPartialScaling > > createOneWayDopplerPartials (const observation_models::LinkEnds oneWayDopplerLinkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const std::shared_ptr< observation_models::DopplerProperTimeRateInterface > transmitterDopplerProperTimeInterface, const std::shared_ptr< observation_models::DopplerProperTimeRateInterface > receiverDopplerProperTimeInterface, const std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > &lightTimeCorrections=std::vector< std::shared_ptr< observation_models::LightTimeCorrection > >(), const bool useBiasPartials=true)
Function to generate one-way doppler partials and associated scaler for single link end.
template<typename ObservationScalarType , typename TimeType >
std::map< observation_models::LinkEnds, std::pair< SingleLinkObservationPartialList, std::shared_ptr< PositionPartialScaling > > > createOneWayDopplerPartials (const std::map< observation_models::LinkEnds, std::shared_ptr< observation_models::ObservationModel< 1, ObservationScalarType, TimeType > > > observationModelList, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ObservationScalarType > > parametersToEstimate, const bool useBiasPartials=true)
Function to generate one-way doppler partials for all parameters that are to be estimated, for all sets of link ends.
std::shared_ptr< OneWayDopplerPartial > createOneWayDopplerPartialWrtBodyState (const observation_models::LinkEnds oneWayDopplerLinkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::string bodyToEstimate, const std::shared_ptr< PositionPartialScaling > oneWayDopplerScaler, const std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > > &lightTimeCorrectionPartialObjects)
Function to generate one-way doppler partial wrt an initial position of a body.
template<typename ParameterType >
std::shared_ptr< ObservationPartial< 1 > > createOneWayDopplerPartialWrtParameter (const observation_models::LinkEnds oneWayDopplerLinkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameter< ParameterType > > parameterToEstimate, const std::shared_ptr< OneWayDopplerScaling > oneWayDopplerScaler, const std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > > &lightTimeCorrectionPartialObjects=std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > >())
Function to generate one-way doppler partial wrt a single parameter.
template<typename ParameterType >
std::pair< SingleLinkObservationPartialList, std::shared_ptr< PositionPartialScaling > > createOneWayRangePartials (const observation_models::LinkEnds oneWayRangeLinkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > &lightTimeCorrections=std::vector< std::shared_ptr< observation_models::LightTimeCorrection > >(), const bool useBiasPartials=true)
Function to generate one-way range partials and associated scaler for single link ends.
template<typename ParameterType >
std::map< observation_models::LinkEnds, std::pair< SingleLinkObservationPartialList, std::shared_ptr< PositionPartialScaling > > > createOneWayRangePartials (const std::vector< observation_models::LinkEnds > &linkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const std::map< observation_models::LinkEnds, std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > > > &lightTimeCorrections=std::map< observation_models::LinkEnds, std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > > >(), const bool useBiasPartials=true)
Function to generate one-way range partials for all parameters that are to be estimated, for all sets of link ends.
std::shared_ptr< OneWayRangePartial > createOneWayRangePartialWrtBodyPosition (const observation_models::LinkEnds oneWayRangeLinkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::string bodyToEstimate, const std::shared_ptr< OneWayRangeScaling > oneWayRangeScaler, const std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > > &lightTimeCorrectionPartialObjects)
Function to generate one-way range partial wrt an initial position of a body.
std::shared_ptr< OneWayRangePartial > createOneWayRangePartialWrtBodyRotationalState (const observation_models::LinkEnds oneWayRangeLinkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::string bodyToEstimate, const std::shared_ptr< OneWayRangeScaling > oneWayRangeScaler, const std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > > &lightTimeCorrectionPartialObjects)
Function to generate one-way range partial wrt an initial position of a body.
template<typename ParameterType >
std::shared_ptr< ObservationPartial< 1 > > createOneWayRangePartialWrtParameter (const observation_models::LinkEnds oneWayRangeLinkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameter< ParameterType > > parameterToEstimate, const std::shared_ptr< OneWayRangeScaling > oneWayRangeScaler, const std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > > &lightTimeCorrectionPartialObjects=std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > >())
Function to generate one-way range partial wrt a single parameter.
template<typename ParameterType >
std::pair< SingleLinkObservationThreePartialList, std::shared_ptr< PositionPartialScaling > > createPositionObservablePartials (const observation_models::LinkEnds positionObservableLinkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate)
Function to create a list of objects that compute the partial derivatives of a three-dimensional position observable.
template<typename ParameterType >
std::map< observation_models::LinkEnds, std::pair< SingleLinkObservationThreePartialList, std::shared_ptr< PositionPartialScaling > > > createPositionObservablePartials (const std::vector< observation_models::LinkEnds > linkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate)
Function to create a list of objects that compute the partial derivatives of a list of 3-dimensional position observable.
std::shared_ptr< PositionObervationPartial > createPositionObservablePartialWrtPosition (const observation_models::LinkEnds linkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::string bodyToEstimate, const std::shared_ptr< PositionObservationScaling > positionObservableScaler)
Function to create an objects that computes the partial derivatives of a three-dimensional position observable w.r.t.
template<typename ParameterType >
RotationMatrixPartialNamedList createRotationMatrixPartials (const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const std::string &bodyName, const simulation_setup::NamedBodyMap &bodyMap)
Function to create rotation matrix partial objects for all rotation model parameters of given body in given set of parameters.
std::shared_ptr< RotationMatrixPartial > createRotationMatrixPartialsWrtParameter (const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameterToEstimate)
Function to create partial object(s) of rotation matrix wrt a (double) parameter.
std::shared_ptr< RotationMatrixPartial > createRotationMatrixPartialsWrtParameter (const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameterToEstimate)
Function to create partial object(s) of rotation matrix wrt a (vector) parameter.
template<typename InitialStateParameterType >
std::shared_ptr< RotationMatrixPartial > createRotationMatrixPartialsWrtStateParameter (const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > parameterToEstimate)
Function to create partial object(s) of rotation matrix wrt a state parameter.
std::shared_ptr< RotationMatrixPartial > createRotationMatrixPartialsWrtTranslationalState (const std::shared_ptr< simulation_setup::Body > currentBody)
Function to create partial object(s) of rotation matrix wrt translational state.
template<typename ParameterType , typename TimeType >
std::pair< SingleLinkObservationPartialList, std::shared_ptr< PositionPartialScaling > > createTwoWayDopplerPartials (const observation_models::LinkEnds &twoWayDopplerLinkEnds, const std::shared_ptr< observation_models::TwoWayDopplerObservationModel< ParameterType, TimeType > > twoWayObservationModel, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > > lightTimeCorrections=std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > >())
Function to generate tow-way Doppler partials and associated scaler for single link ends.
template<typename ParameterType , typename TimeType >
std::map< observation_models::LinkEnds, std::pair< SingleLinkObservationPartialList, std::shared_ptr< PositionPartialScaling > > > createTwoWayDopplerPartials (const std::map< observation_models::LinkEnds, std::shared_ptr< observation_models::ObservationModel< 1, ParameterType, TimeType > > > observationModelList, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const std::map< observation_models::LinkEnds, std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > > > &lightTimeCorrections=std::map< observation_models::LinkEnds, std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > > >())
Function to generate two-way Doppler partials for all parameters that are to be estimated, for all sets of link ends.
template<typename ParameterType >
std::pair< SingleLinkObservationThreePartialList, std::shared_ptr< PositionPartialScaling > > createVelocityObservablePartials (const observation_models::LinkEnds velocityObservableLinkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate)
Function to create a list of objects that compute the partial derivatives of a three-dimensional velocity observable.
template<typename ParameterType >
std::map< observation_models::LinkEnds, std::pair< SingleLinkObservationThreePartialList, std::shared_ptr< PositionPartialScaling > > > createVelocityObservablePartials (const std::vector< observation_models::LinkEnds > linkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate)
Function to create a list of objects that compute the partial derivatives of a list of 3-dimensional velocity observable.
std::shared_ptr< VelocityObervationPartial > createVelocityObservablePartialWrtVelocity (const observation_models::LinkEnds linkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::string bodyToEstimate, const std::shared_ptr< VelocityObservationScaling > velocityObservableScaler)
Function to create an objects that computes the partial derivatives of a three-dimensional velocity observable w.r.t.
template<typename ObservationScalarType , typename TimeType , int ObservationSize>
PerLinkEndPerLightTimeSolutionCorrections getLightTimeCorrectionsList (const std::map< observation_models::LinkEnds, std::shared_ptr< observation_models::ObservationModel< ObservationSize, ObservationScalarType, TimeType > > > observationModels)
Function to retrieve a list of light-time corrections per link end from a list of observation models.
std::pair< std::function< LightTimeCorrectionPartial::SingleOneWayRangePartialReturnType(const std::vector< Eigen::Vector6d > &, const std::vector< double > &) >, bool > getLightTimeParameterPartialFunction (const estimatable_parameters::EstimatebleParameterIdentifier parameterId, const std::shared_ptr< LightTimeCorrectionPartial > lightTimeCorrectionPartial)
Function to get the function returning the light-time correction partial for given correction partial and parameter.
double getPartialOfFirstOrderRelativisticLightTimeCorrectionWrtPpnParameterGamma (const double totalLightTimeCorrection, const double ppnParameterGamma)
Function to compute partial derivative of 1st order relativistic correction w.r.t. PPN parameter gamma.
double getPartialOfFirstOrderRelativisticLightTimeCorrectionWrtSingleGravitationalParameter (const double singleBodyLightTimeCorrection, const double bodyGravitationalParameter)
Function to compute partial derivative of 1st order relativistic correction w.r.t. gravitational parameter.
template<int ObservationSize>
void splitObservationPartialsAndScalers (const std::map< observation_models::LinkEnds, std::pair< std::map< std::pair< int, int >, std::shared_ptr< ObservationPartial< ObservationSize > > >, std::shared_ptr< PositionPartialScaling > > > &observationPartialsAndScalers, std::map< observation_models::LinkEnds, std::map< std::pair< int, int >, std::shared_ptr< observation_partials::ObservationPartial< ObservationSize > > > > &observationPartials, std::map< observation_models::LinkEnds, std::shared_ptr< observation_partials::PositionPartialScaling > > &observationPartialScalers)
Function to split observation partials and scaling object (produced by observationPartialsAndScaler function) into separate containers.
std::pair< PerLinkEndPerLightTimeSolutionCorrections, PerLinkEndPerLightTimeSolutionCorrections > splitOneWayRangeRateLightTimeCorrectionsBetweenArcs (const PerLinkEndPerLightTimeSolutionCorrections &combinedCorrections)
Function to split the total list of light-time corrections for one-way differenced range rate into list for either arc.
Variables
std::pair< std::function< LightTimeCorrectionPartial::SingleOneWayRangePartialReturnType(const std::vector< Eigen::Vector6d > &, const std::vector< double > &) >, bool > getLightTimeParameterPartialFunction (const estimatable_parameters::EstimatebleParameterIdentifier parameterId, const std::shared_ptr< LightTimeCorrectionPartial > lightTimeCorrectionPartial)
Function to get the function returning the light-time correction partial for given correction partial and parameter.
Typedef Documentation
SingleLinkObservationPartialList
typedef std::map< std::pair< int, int >, std::shared_ptr< ObservationPartial< 1 > > > tudat::observation_partials::SingleLinkObservationPartialList
Typedef for single observation partial list, with key parameter start index and size.
Typedef for map of observation partials, for an observable of size 1. The key of the map is a pair denoting the start index of the parameter in the list of estimated parameters and the number of indices of the parameter wrt which the current partial (corresponding value in map) is taken.
Definition at line 450 of file observationPartial.h.
SingleLinkObservationTwoPartialList
typedef std::map< std::pair< int, int >, std::shared_ptr< ObservationPartial< 2 > > > tudat::observation_partials::SingleLinkObservationTwoPartialList
Typedef for map of observation partials, for an observable of size 2. The key of the map is a pair denoting the start index of the parameter in the list of estimated parameters and the number of indices of the parameter wrt which the current partial (corresponding value in map) is taken.
Definition at line 459 of file observationPartial.h.
SingleLinkObservationThreePartialList
typedef std::map< std::pair< int, int >, std::shared_ptr< ObservationPartial< 3 > > > tudat::observation_partials::SingleLinkObservationThreePartialList
Typedef for map of observation partials, for an observable of size 3. The key of the map is a pair denoting the start index of the parameter in the list of estimated parameters and the number of indices of the parameter wrt which the current partial (corresponding value in map) is taken.
Definition at line 468 of file observationPartial.h.
RotationMatrixPartialNamedList
typedef std::map< std::pair< estimatable_parameters::EstimatebleParametersEnum, std::string >, std::shared_ptr< RotationMatrixPartial > > tudat::observation_partials::RotationMatrixPartialNamedList
Definition at line 894 of file rotationMatrixPartial.h.
PerLinkEndPerLightTimeSolutionCorrections
typedef std::map< observation_models::LinkEnds, std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > > > tudat::observation_partials::PerLinkEndPerLightTimeSolutionCorrections
Definition at line 30 of file createDifferencedOneWayRangeRatePartials.h.
Function Documentation
getPartialOfFirstOrderRelativisticLightTimeCorrectionWrtSingleGravitationalParameter()
double tudat::observation_partials::getPartialOfFirstOrderRelativisticLightTimeCorrectionWrtSingleGravitationalParameter (const double singleBodyLightTimeCorrection, const double bodyGravitationalParameter)
Function to compute partial derivative of 1st order relativistic correction w.r.t. gravitational parameter.
Parameters
singleBodyLightTimeCorrection Value of light-time correction for which partial is to be evaluated.
bodyGravitationalParameter Value of gravitational parameter
Returns
Partial derivative of 1st order relativistic correction w.r.t. gravitational parameter.
Definition at line 20 of file firstOrderRelativisticPartial.cpp.
Referenced by tudat::observation_partials::FirstOrderRelativisticLightTimeCorrectionPartial::wrtBodyGravitationalParameter().
getPartialOfFirstOrderRelativisticLightTimeCorrectionWrtPpnParameterGamma()
double tudat::observation_partials::getPartialOfFirstOrderRelativisticLightTimeCorrectionWrtPpnParameterGamma (const double totalLightTimeCorrection, const double ppnParameterGamma)
Function to compute partial derivative of 1st order relativistic correction w.r.t. PPN parameter gamma.
Parameters
totalLightTimeCorrection Value of light-time correction for which partial is to be evaluated.
ppnParameterGamma Value of PPN parameter gamma.
Returns
Partial derivative of 1st order relativistic correction w.r.t. PPN parameter gamma.
Definition at line 27 of file firstOrderRelativisticPartial.cpp.
Referenced by tudat::observation_partials::FirstOrderRelativisticLightTimeCorrectionPartial::wrtPpnParameterGamma().
getLightTimeParameterPartialFunction()
std::pair< std::function< LightTimeCorrectionPartial::SingleOneWayRangePartialReturnType(const std::vector< Eigen::Vector6d >&, const std::vector< double >&) >, bool > tudat::observation_partials::getLightTimeParameterPartialFunction (const estimatable_parameters::EstimatebleParameterIdentifier parameterId, const std::shared_ptr< LightTimeCorrectionPartial > lightTimeCorrectionPartial)
Definition at line 26 of file lightTimeCorrectionPartial.cpp.
References tudat::observation_models::first_order_relativistic, tudat::estimatable_parameters::gravitational_parameter, tudat::estimatable_parameters::ppn_parameter_gamma, tudat::observation_partials::FirstOrderRelativisticLightTimeCorrectionPartial::wrtBodyGravitationalParameter(), and tudat::observation_partials::FirstOrderRelativisticLightTimeCorrectionPartial::wrtPpnParameterGamma().
calculatePartialOfRightAscensionWrtLinkEndPosition()
Eigen::Matrix< double, 1, 3 > tudat::observation_partials::calculatePartialOfRightAscensionWrtLinkEndPosition (const Eigen::Vector3d & relativeRangeVector, const bool isLinkEndReceiver)
Function to compute the derivative of (direct geometric) right ascension w.r.t. position of observer or observed object.
Parameters
relativeRangeVector Vector from observer to observed object
isLinkEndReceiver True if the partial is to be computed w.r.t. position of observer, false if it is the observed object
Returns
derivative of (direct geometric) right ascension w.r.t. position of observer or observed object.
Definition at line 20 of file angularPositionPartial.cpp.
Referenced by calculatePartialOfAngularPositionWrtLinkEndPosition().
calculatePartialOfDeclinationWrtLinkEndPosition()
Eigen::Matrix< double, 1, 3 > tudat::observation_partials::calculatePartialOfDeclinationWrtLinkEndPosition (Eigen::Vector3d relativeRangeVector, const bool isLinkEndReceiver)
Function to compute the derivative of (direct geometric) declination w.r.t. position of observer or observed object.
Parameters
relativeRangeVector Vector from observer to observed object
isLinkEndReceiver True if the partial is to be computed w.r.t. position of observer, false if it is the observed object
Returns
derivative of (direct geometric) declination w.r.t. position of observer or observed object.
Definition at line 37 of file angularPositionPartial.cpp.
Referenced by calculatePartialOfAngularPositionWrtLinkEndPosition().
calculatePartialOfAngularPositionWrtLinkEndPosition()
Eigen::Matrix< double, 2, 3 > tudat::observation_partials::calculatePartialOfAngularPositionWrtLinkEndPosition (Eigen::Vector3d relativeRangeVector, const bool isLinkEndReceiver)
Function to compute the derivative of (direct geometric) right ascension and declination w.r.t. position of observer or observed object.
Function to compute the derivative of (direct geometric) right ascension and declination w.r.t. position of observer or observed object.
position of observer or observed object.
Parameters
relativeRangeVector Vector from observer to observed object
isLinkEndReceiver True if the partial is to be computed w.r.t. position of observer, false if it is the observed object
Returns
Derivative of (direct geometric) right ascension and declination w.r.t. position of observer or observed object.
Definition at line 56 of file angularPositionPartial.cpp.
References calculatePartialOfDeclinationWrtLinkEndPosition(), and calculatePartialOfRightAscensionWrtLinkEndPosition().
Referenced by tudat::observation_partials::AngularPositionScaling::update().
createObservationPartialWrtLinkProperty()
template<int ObservationSize> std::shared_ptr< ObservationPartial< ObservationSize > > tudat::observation_partials::createObservationPartialWrtLinkProperty (const observation_models::LinkEnds & linkEnds, const observation_models::ObservableType observableType, const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameterToEstimate, const bool useBiasPartials = true)
Function to create partials of observation w.r.t. a link property, e.g. a parameter that does not influence either link end's dynamics, only the observable itself, such as observation biases and clock parameters.
Parameters
linkEnds Link ends of observable for which partial is to be made.
observableType Type of observable for which partial is to be made.
parameterToEstimate Parameter w.r.t. which the partial is to be taken
useBiasPartials Boolean to denote whether this function should create partials w.r.t. observation bias parameters
Returns
Object that computes the partial of the observation w.r.t. parameterToEstimate (nullptr if no dependency).
Definition at line 482 of file observationPartial.h.
References tudat::estimatable_parameters::arcwise_constant_additive_observation_bias, tudat::estimatable_parameters::arcwise_constant_relative_observation_bias, tudat::estimatable_parameters::constant_additive_observation_bias, and tudat::estimatable_parameters::constant_relative_observation_bias.
computePartialOfUnitVectorWrtLinkEndTime()
Eigen::Vector3d tudat::observation_partials::computePartialOfUnitVectorWrtLinkEndTime (const Eigen::Vector3d & vectorToReceiver, const Eigen::Vector3d & unitVectorToReceiver, const double linkEndDistance, const Eigen::Vector3d linkEndVelocity)
Function to computed the derivative of the unit vector from transmitter to receiver w.r.t. the observation time
Parameters
vectorToReceiver Vector from transmitter to receiver (unnormalized).
unitVectorToReceiver Vector from transmitter to receiver (normalized).
linkEndDistance Distance between transmitter and receiver
linkEndVelocity Velocity of link end at which the time is varied
Returns
Derivative of the unit vector from transmitter to receiver w.r.t. the observation time
Definition at line 20 of file oneWayDopplerPartial.cpp.
Referenced by computePartialOfProjectedLinkEndVelocityWrtAssociatedTime().
computePartialOfProjectedLinkEndVelocityWrtAssociatedTime()
double tudat::observation_partials::computePartialOfProjectedLinkEndVelocityWrtAssociatedTime (const Eigen::Vector3d & vectorToReceiver, const Eigen::Vector3d & projectedLinkEndVelocity, const Eigen::Vector3d & variableLinkEndVelocity, const Eigen::Vector3d & projectedLinkEndAcceleration, const bool linkEndIsReceiver, const bool projectedLinkEndIsVariableLinkEnd = true)
Function to computed the derivative of velocity component along line-of-sight vector w.r.t. the observation time
Parameters
vectorToReceiver Vector from transmitter to receiver (unnormalized).
projectedLinkEndVelocity Velocity vector of link end, projected along line-of-sight vector
variableLinkEndVelocity Velocity of link end at which the time is varied
projectedLinkEndAcceleration Acceleration vector of link end, projected along line-of-sight vector
linkEndIsReceiver Boolean denoting whether the link end at which partial is taken at receiver (if true) or transmitter (if false)
projectedLinkEndIsVariableLinkEnd Boolean denoting whether the link end at which partial is the reference link end for the observation (if false) or not (if true)
Returns
Derivative of velocity component along line-of-sight vector w.r.t. the observation time
Definition at line 31 of file oneWayDopplerPartial.cpp.
References computePartialOfUnitVectorWrtLinkEndTime().
Referenced by tudat::observation_partials::OneWayDopplerScaling::update().
calculatePartialOfPointPositionWrtBodyPosition()
Eigen::Matrix3d tudat::observation_partials::calculatePartialOfPointPositionWrtBodyPosition ()
Function to calculate the partial of position of a point on body wrt position of that body.
Function to calculate the partial of position of a point on body wrt position of that body, with both positions expressed in the same frame.
Returns
Requested partial (3x3 identity matrix)
Definition at line 23 of file positionPartials.cpp.
calculatePartialOfPointPositionWrtBodyFixedPointPosition()
Eigen::Matrix3d tudat::observation_partials::calculatePartialOfPointPositionWrtBodyFixedPointPosition (const Eigen::Matrix3d & rotationMatrixToInertialFrame)
Function to calculate the partial of position of a point on a body (expressed in a non-corotating, non-body fixed frame) wrt its body-fixed position, e.g. the partial of a ground station's inertial position wrt its body-fixed position.
Parameters
rotationMatrixToInertialFrame Rotation matrix from body-fixed to inertial frame.
Returns
Partial of position of a point on a body wrt its body-fixed position
Definition at line 29 of file positionPartials.cpp.
calculatePartialOfRotationMatrixFromLocalFrameWrtConstantRotationRate()
Eigen::Matrix3d tudat::observation_partials::calculatePartialOfRotationMatrixFromLocalFrameWrtConstantRotationRate (const Eigen::Quaterniond inertialBodyFixedToIntegrationFrame, const double rotationRate, const double timeSinceEpoch)
Function to calculate partial of a rotation matrix from a body-fixed to inertial frame w.r.t. a constant rotation rate.
Function to calculate partial of a rotation matrix from a body-fixed to inertial frame, as computed by the SimpleRotationalEphemeris class, w.r.t. the constant rotation rate.
Parameters
inertialBodyFixedToIntegrationFrame Rotation matrix at reference epoch
rotationRate Nominal rotation rate (about local z-axis)
timeSinceEpoch Elapsed time (in seconds) since reference epoch
Returns
Partial derivative of rotation matrix w.r.t. rotation rate.
Definition at line 20 of file rotationMatrixPartial.cpp.
Referenced by tudat::observation_partials::RotationMatrixPartialWrtConstantRotationRate::calculatePartialOfRotationMatrixToBaseFrameWrParameter().
calculatePartialOfRotationMatrixFromLocalFrameDerivativeWrtConstantRotationRate()
Eigen::Matrix3d tudat::observation_partials::calculatePartialOfRotationMatrixFromLocalFrameDerivativeWrtConstantRotationRate (const Eigen::Matrix3d currentRotationFromLocalToGlobalFrame, const double rotationRate, const double timeSinceEpoch)
Function to calculate partial of a rotation matrix derivative from a body-fixed to inertial frame, as computed by the SimpleRotationalEphemeris class, w.r.t. the constant rotation rate.
Parameters
currentRotationFromLocalToGlobalFrame Rotation matrix to inertial frame at reference epoch
rotationRate Nominal rotation rate (about local z-axis)
timeSinceEpoch Elapsed time (in seconds) since reference epoch
Returns
Partial derivative of rotation matrix derivative w.r.t. rotation rate.
Definition at line 37 of file rotationMatrixPartial.cpp.
References tudat::reference_frames::Z_AXIS_ROTATION_MATRIX_DERIVATIVE_PREMULTIPLIER.
Referenced by tudat::observation_partials::RotationMatrixPartialWrtConstantRotationRate::calculatePartialOfRotationMatrixDerivativeToBaseFrameWrParameter().
calculatePartialOfRotationMatrixFromLocalFrameWrtPoleOrientation()
std::vector< Eigen::Matrix3d > tudat::observation_partials::calculatePartialOfRotationMatrixFromLocalFrameWrtPoleOrientation (const Eigen::Vector3d initialOrientationAngles, const double rotationRate, const double timeSinceEpoch)
Function to calculate a partial of rotation matrix from a body-fixed to inertial frame w.r.t. a constant pole right ascension and declination
Function to calculate a partial of rotation matrix from a body-fixed to inertial frame w.r.t. a constant pole right ascension and declination.
a constant pole right ascension and declination.
Parameters
initialOrientationAngles Rotation Euler angles at reference epoch, in order right ascension, declination, prime meridian
rotationRate Rotation rate (about local z-axis)
timeSinceEpoch Elapsed time (in seconds) since reference epoch
Returns
Partial derivatives of rotation matrix w.r.t. right ascension (entry 0) and declination (entry 1) of pole.
Definition at line 48 of file rotationMatrixPartial.cpp.
References tudat::reference_frames::getDerivativeOfXAxisRotationWrtAngle(), tudat::reference_frames::getDerivativeOfZAxisRotationWrtAngle(), and tudat::mathematical_constants::PI.
Referenced by calculatePartialOfRotationMatrixFromLocalFrameDerivativeWrtPoleOrientation(), and tudat::observation_partials::RotationMatrixPartialWrtPoleOrientation::calculatePartialOfRotationMatrixToBaseFrameWrParameter().
calculatePartialOfRotationMatrixFromLocalFrameDerivativeWrtPoleOrientation()
std::vector< Eigen::Matrix3d > tudat::observation_partials::calculatePartialOfRotationMatrixFromLocalFrameDerivativeWrtPoleOrientation (const Eigen::Vector3d initialOrientationAngles, const double rotationRate, const double timeSinceEpoch)
Function to calculate a partial of rotation matrix derivative from a body-fixed to inertial frame w.r.t. a constant pole right ascension and declination.
Function to calculate a partial of rotation matrix derivative from a body-fixed to inertial frame w.r.t. a constant pole right ascension and declination.
a constant pole right ascension and declination.
Parameters
initialOrientationAngles Rotation Euler angles at reference epoch, in order right ascension, declination, prime meridian
rotationRate Rotation rate (about local z-axis)
timeSinceEpoch Elapsed time (in seconds) since reference epoch
Returns
Partial derivatives of rotation matrix w.r.t. right ascension (entry 0) and declination (entry 1) of pole.
Definition at line 85 of file rotationMatrixPartial.cpp.
References calculatePartialOfRotationMatrixFromLocalFrameWrtPoleOrientation(), and tudat::reference_frames::Z_AXIS_ROTATION_MATRIX_DERIVATIVE_PREMULTIPLIER.
Referenced by tudat::observation_partials::RotationMatrixPartialWrtPoleOrientation::calculatePartialOfRotationMatrixDerivativeToBaseFrameWrParameter().
calculatePartialOfRotationMatrixFromLocalFrameWrtPeriodicSpinVariations()
std::vector< Eigen::Matrix3d > tudat::observation_partials::calculatePartialOfRotationMatrixFromLocalFrameWrtPeriodicSpinVariations (const std::shared_ptr< ephemerides::PlanetaryOrientationAngleCalculator > planetaryOrientationCalculator, const Eigen::Quaterniond & rotationFromMeanOrbitToIcrf, const Eigen::Quaterniond & polarMotionRotation, const double ephemerisTime)
Function to calculate a partial of rotation matrix from a body-fixed to inertial frame w.r.t. the periodic spin variations.
Function to calculate a partial of rotation matrix from a body-fixed to inertial frame w.r.t. the periodic spin variations.
the periodic spin variations.
Parameters
planetaryOrientationCalculator pointer to PlanetaryOrientationAngleCalculator,
rotationFromMeanOrbitToIcrf Rotation From Mean Orbit To Icrf (Quaternion),
polarMotionRotation Rotation due to Polar Motion at ephemeris time (Quaternion),
ephemerisTime Time at which partial is to be evaluated.
Returns
Partial derivatives of rotation matrix w.r.t. Phi_cj (entry 0), Phi_sj (entry 1) with j=1,...,4 .
Definition at line 102 of file rotationMatrixPartial.cpp.
Referenced by tudat::observation_partials::RotationMatrixPartialWrtPeriodicSpinVariations::calculatePartialOfRotationMatrixToBaseFrameWrParameter().
calculatePartialOfRotationMatrixFromLocalFrameDerivativeWrtPeriodicSpinVariations()
std::vector< Eigen::Matrix3d > tudat::observation_partials::calculatePartialOfRotationMatrixFromLocalFrameDerivativeWrtPeriodicSpinVariations (const std::shared_ptr< ephemerides::PlanetaryOrientationAngleCalculator > planetaryOrientationCalculator, const Eigen::Quaterniond & rotationFromMeanOrbitToIcrf, const Eigen::Quaterniond & polarMotionRotation, const double ephemerisTime)
Function to calculate a partial of rotation matrix derivative from a body-fixed to inertial frame w.r.t. the periodic spin variations.
Function to calculate a partial of rotation matrix derivative from a body-fixed to inertial frame w.r.t. the periodic spin variations.
the periodic spin variations.
Parameters
planetaryOrientationCalculator pointer to PlanetaryOrientationAngleCalculator,
rotationFromMeanOrbitToIcrf Rotation From Mean Orbit To Icrf (Quaternion),
polarMotionRotation Rotation due to Polar Motion at ephemeris time (Quaternion),
ephemerisTime Time at which partial is to be evaluated.
Returns
Partial derivatives of rotation matrix w.r.t. Phi_cj (entry 0), Phi_sj (entry 1) with j=1,...,4 .
Definition at line 145 of file rotationMatrixPartial.cpp.
References tudat::input_output::field_types::state::meanMotion.
Referenced by tudat::observation_partials::RotationMatrixPartialWrtPeriodicSpinVariations::calculatePartialOfRotationMatrixDerivativeToBaseFrameWrParameter().
calculatePartialOfRotationMatrixFromLocalFrameWrtPolarMotionAmplitude()
std::vector< Eigen::Matrix3d > tudat::observation_partials::calculatePartialOfRotationMatrixFromLocalFrameWrtPolarMotionAmplitude (const std::shared_ptr< ephemerides::PlanetaryOrientationAngleCalculator > planetaryOrientationCalculator, const Eigen::Quaterniond & rotationFromMeanOrbitToIcrf, const Eigen::Quaterniond & rotationFromBodyFixedToIntermediateInertialFrame, const double ephemerisTime)
Function to calculate a partial of rotation matrix from a body-fixed to inertial frame w.r.t. polar motion amplitude.
Function to calculate a partial of rotation matrix derivative from a body-fixed to inertial frame w.r.t. polar motion amplitudes. Function to calculate a partial of rotation matrix from a body-fixed to inertial frame w.r.t. polar motion amplitudes.
polar motion amplitudes.
Parameters
planetaryOrientationCalculator pointer to PlanetaryOrientationAngleCalculator,
rotationFromMeanOrbitToIcrf Rotation From Mean Orbit To Icrf (Quaternion),
rotationFromBodyFixedToIntermediateInertialFrame Rotation From Body Fixed To Intermediate Inertial Frame (Quaternion),
ephemerisTime Time at which partial is to be evaluated.
Returns
Partial derivatives of rotation matrix w.r.t. Phi_cj (entry 0), Phi_sj (entry 1) with j=1,...,4 .
Definition at line 220 of file rotationMatrixPartial.cpp.
Referenced by tudat::observation_partials::RotationMatrixPartialWrtPolarMotionAmplitude::calculatePartialOfRotationMatrixToBaseFrameWrParameter().
calculatePartialOfRotationMatrixFromLocalFrameDerivativeWrtPolarMotionAmplitude()
std::vector< Eigen::Matrix3d > tudat::observation_partials::calculatePartialOfRotationMatrixFromLocalFrameDerivativeWrtPolarMotionAmplitude (const std::shared_ptr< ephemerides::PlanetaryOrientationAngleCalculator > planetaryOrientationCalculator, const Eigen::Quaterniond & rotationFromMeanOrbitToIcrf, const double ephemerisTime)
Function to calculate a partial of rotation matrix derivative from a body-fixed to inertial frame w.r.t. polar motion amplitude.
Function to calculate a partial of rotation matrix derivative from a body-fixed to inertial frame w.r.t. polar motion amplitudes.
polar motion amplitudes.
Parameters
planetaryOrientationCalculator pointer to PlanetaryOrientationAngleCalculator,
rotationFromMeanOrbitToIcrf Rotation From Mean Orbit To Icrf (Quaternion),
ephemerisTime Time at which partial is to be evaluated.
Returns
Partial derivatives of rotation matrix w.r.t. Phi_cj (entry 0), Phi_sj (entry 1) with j=1,...,4 .
Definition at line 293 of file rotationMatrixPartial.cpp.
Referenced by tudat::observation_partials::RotationMatrixPartialWrtPolarMotionAmplitude::calculatePartialOfRotationMatrixDerivativeToBaseFrameWrParameter().
calculatePartialOfRotationMatrixFromLocalFrameWrtCoreFactor()
Eigen::Matrix3d tudat::observation_partials::calculatePartialOfRotationMatrixFromLocalFrameWrtCoreFactor (const std::shared_ptr< ephemerides::PlanetaryOrientationAngleCalculator > planetaryOrientationCalculator, const Eigen::Quaterniond & rotationFromMeanOrbitToIcrf, const Eigen::Quaterniond & polarMotionRotation, const double ephemerisTime)
Function to calculate a partial of rotation matrix from a body-fixed to inertial frame w.r.t. core factor.
Function to calculate a partial of rotation matrix from a body-fixed to inertial frame w.r.t. core factor.
core factor.
Parameters
planetaryOrientationCalculator pointer to PlanetaryOrientationAngleCalculator,
rotationFromMeanOrbitToIcrf Rotation From Mean Orbit To Icrf (Quaternion),
polarMotionRotation Rotation due to Polar Motion at ephemeris time (Quaternion),
ephemerisTime Time at which partial is to be evaluated.
Returns
Partial derivatives of rotation matrix w.r.t. core factor .
Definition at line 375 of file rotationMatrixPartial.cpp.
References tudat::input_output::field_types::state::meanMotion.
Referenced by tudat::observation_partials::RotationMatrixPartialWrtCoreFactor::calculatePartialOfRotationMatrixToBaseFrameWrParameter().
calculatePartialOfRotationMatrixFromLocalFrameDerivativeWrtCoreFactor()
Eigen::Matrix3d tudat::observation_partials::calculatePartialOfRotationMatrixFromLocalFrameDerivativeWrtCoreFactor (const std::shared_ptr< ephemerides::PlanetaryOrientationAngleCalculator > planetaryOrientationCalculator, const Eigen::Quaterniond & rotationFromMeanOrbitToIcrf, const Eigen::Quaterniond & polarMotionRotation, const double ephemerisTime)
Function to calculate a partial of rotation matrix derivative from a body-fixed to inertial frame w.r.t. core factor.
Function to calculate a partial of rotation matrix derivative from a body-fixed to inertial frame w.r.t. core factor.
core factor.
Parameters
planetaryOrientationCalculator pointer to PlanetaryOrientationAngleCalculator,
rotationFromMeanOrbitToIcrf Rotation From Mean Orbit To Icrf (Quaternion),
polarMotionRotation Rotation due to Polar Motion at ephemeris time (Quaternion),
ephemerisTime Time at which partial is to be evaluated.
Returns
Partial derivatives of rotation matrix w.r.t. core factor.
Definition at line 536 of file rotationMatrixPartial.cpp.
References tudat::input_output::field_types::state::meanMotion.
Referenced by tudat::observation_partials::RotationMatrixPartialWrtCoreFactor::calculatePartialOfRotationMatrixDerivativeToBaseFrameWrParameter().
calculatePartialOfRotationMatrixFromLocalFrameWrtFreeCoreNutationRate()
Eigen::Matrix3d tudat::observation_partials::calculatePartialOfRotationMatrixFromLocalFrameWrtFreeCoreNutationRate (const std::shared_ptr< ephemerides::PlanetaryOrientationAngleCalculator > planetaryOrientationCalculator, const Eigen::Quaterniond & rotationFromMeanOrbitToIcrf, const Eigen::Quaterniond & polarMotionRotation, const double ephemerisTime)
Function to calculate a partial of rotation matrix from a body-fixed to inertial frame w.r.t. free core nutation rate.
Function to calculate a partial of rotation matrix from a body-fixed to inertial frame w.r.t. free core nutation.
free core nutation.
Parameters
planetaryOrientationCalculator pointer to PlanetaryOrientationAngleCalculator,
rotationFromMeanOrbitToIcrf Rotation From Mean Orbit To Icrf (Quaternion),
polarMotionRotation Rotation due to Polar Motion at ephemeris time (Quaternion),
ephemerisTime Time at which partial is to be evaluated.
Returns
Partial derivatives of rotation matrix w.r.t. free core nutation.
Definition at line 713 of file rotationMatrixPartial.cpp.
References tudat::input_output::field_types::state::meanMotion.
Referenced by tudat::observation_partials::RotationMatrixPartialWrtFreeCoreNutationRate::calculatePartialOfRotationMatrixToBaseFrameWrParameter().
calculatePartialOfRotationMatrixFromLocalFrameDerivativeWrtFreeCoreNutationRate()
Eigen::Matrix3d tudat::observation_partials::calculatePartialOfRotationMatrixFromLocalFrameDerivativeWrtFreeCoreNutationRate (const std::shared_ptr< ephemerides::PlanetaryOrientationAngleCalculator > planetaryOrientationCalculator, const Eigen::Quaterniond & rotationFromMeanOrbitToIcrf, const Eigen::Quaterniond & polarMotionRotation, const double ephemerisTime)
Function to calculate a partial of rotation matrix derivative from a body-fixed to inertial frame w.r.t. free core nutation rate.
Function to calculate a partial of rotation matrix derivative from a body-fixed to inertial frame w.r.t. free core nutation.
free core nutation.
Parameters
planetaryOrientationCalculator pointer to PlanetaryOrientationAngleCalculator,
rotationFromMeanOrbitToIcrf Rotation From Mean Orbit To Icrf (Quaternion),
polarMotionRotation Rotation due to Polar Motion at ephemeris time (Quaternion),
ephemerisTime Time at which partial is to be evaluated.
Returns
Partial derivatives of rotation matrix w.r.t. core factor.
Definition at line 883 of file rotationMatrixPartial.cpp.
References tudat::input_output::field_types::state::meanMotion.
Referenced by tudat::observation_partials::RotationMatrixPartialWrtFreeCoreNutationRate::calculatePartialOfRotationMatrixDerivativeToBaseFrameWrParameter().
createAngularPositionPartialWrtBodyPosition()
std::shared_ptr< AngularPositionPartial > tudat::observation_partials::createAngularPositionPartialWrtBodyPosition (const observation_models::LinkEnds angularPositionLinkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::string bodyToEstimate, const std::shared_ptr< AngularPositionScaling > angularPositionScaler, const std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > > & lightTimeCorrectionPartialObjects = std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > >())
Function to generate angular position partial wrt a position of a body, for a single link ends (which must contain a transmitter and receiever linkEndType).
Parameters
angularPositionLinkEnds Link ends (transmitter and receiever) for which partials are to be calculated (i.e. for which angular position observation observations are to be processed).
bodyMap List of all bodies, for creating angular position partial.
bodyToEstimate Name of body wrt position of which a partial is to be created.
angularPositionScaler Object scale position partials to angular position partials for current link ends.
lightTimeCorrectionPartialObjects List of light time correction partials to be used (empty by default)
Returns
Angular position partial object wrt a current position of a body (is nullptr if no parameter dependency exists).
Definition at line 26 of file createAngularPositionPartials.cpp.
References createCartesianStatePartialsWrtBodyState(), and tudat::estimatable_parameters::initial_body_state.
Referenced by createAngularPositionPartials().
createAngularPositionPartialWrtParameter()
template<typename ParameterType > std::shared_ptr< AngularPositionPartial > tudat::observation_partials::createAngularPositionPartialWrtParameter (const observation_models::LinkEnds angularPositionLinkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameter< ParameterType > > parameterToEstimate, const std::shared_ptr< AngularPositionScaling > angularPositionScaler, const std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > > & lightTimeCorrectionPartialObjects = std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > >())
Function to generate angular position partial wrt a single parameter, for a single link ends (which must contain a transmitter and receiever linkEndType).
Template Parameters
ParameterType Type of parameter (double for size 1, VectorXd for larger size).
Parameters
angularPositionLinkEnds Link ends (transmitter and receiever) for which angular position partials are to be calculated (i.e. for which angular position observations are to be processed).
bodyMap List of all bodies, for creating angular position partial.
parameterToEstimate Object of current parameter that is to be estimated.
angularPositionScaler Object scale position partials to angular position partials for current link ends.
lightTimeCorrectionPartialObjects List of light time correction partials to be used (empty by default)
Returns
Angular position partial object wrt a single parameter (is nullptr if no parameter dependency exists).
Definition at line 71 of file createAngularPositionPartials.h.
References createCartesianStatePartialsWrtParameter().
Referenced by createAngularPositionPartials().
createAngularPositionPartials() [1/2]
template<typename ParameterType > std::pair< std::map< std::pair< int, int >, std::shared_ptr< ObservationPartial< 2 > > >,std::shared_ptr< PositionPartialScaling > > tudat::observation_partials::createAngularPositionPartials (const observation_models::LinkEnds angularPositionLinkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > & lightTimeCorrections = std::vector< std::shared_ptr< observation_models::LightTimeCorrection > >())
Function to generate angular position partials and associated scaler for all parameters that are to be estimated, for a single link ends. The set of parameters and bodies that are to be estimated, as well as the set of link ends (each of which must contain a transmitter and receiever linkEndType) that are to be used.
Parameters
angularPositionLinkEnds Link ends (transmitter and receiever) for which angular position partials are to be calculated (i.e. for which angular position observations are to be processed).
bodyMap List of all bodies, for creating angular position partials.
parametersToEstimate Set of parameters that are to be estimated (in addition to initial states of requested bodies)
lightTimeCorrections List of light time correction partials to be used (empty by default)
Returns
Set of observation partials with associated indices in complete vector of parameters that are estimated, representing all necessary angular position partials of a single link end, and AngularPositionScaling, object, used for scaling the position partial members of all AngularPositionPartials in link end.
Definition at line 117 of file createAngularPositionPartials.h.
References tudat::observation_models::angular_position, tudat::estimatable_parameters::arc_wise_initial_body_state, createAngularPositionPartialWrtBodyPosition(), createAngularPositionPartialWrtParameter(), createLightTimeCorrectionPartials(), tudat::estimatable_parameters::EstimatableParameter< ParameterType >::getParameterName(), tudat::estimatable_parameters::initial_body_state, and tudat::estimatable_parameters::isParameterObservationLinkProperty().
Referenced by createAngularPositionPartials().
createAngularPositionPartials() [2/2]
template<typename ParameterType > std::map< observation_models::LinkEnds, std::pair< SingleLinkObservationTwoPartialList,std::shared_ptr< PositionPartialScaling > > > tudat::observation_partials::createAngularPositionPartials (const std::vector< observation_models::LinkEnds > linkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const std::map< observation_models::LinkEnds, std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > > > & lightTimeCorrections = std::map< observation_models::LinkEnds, std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > > >())
Function to generate angular position partials for all parameters that are to be estimated, for all sets of link ends. The angular position partials are generated per set of link ends. The set of parameters and bodies that are to be estimated, as well as the set of link ends (each of which must contain a transmitter and receiever linkEndType) that are to be used.
Parameters
linkEnds Vector of all link ends for which angular position partials are to be calculated (i.e. for which one-way angular position observations are to be processed).
bodyMap List of all bodies, for creating angular position partials.
parametersToEstimate Set of parameters that are to be estimated (in addition to initial states of requested bodies)
lightTimeCorrections List of light time correction partials to be used (empty by default)
Returns
Map of SingleLinkObservationPartialList, representing all necessary angular position partials of a single link end, and AngularPositionScaling, object, used for scaling the position partial members of all AngularPositionPartials in link end.
Definition at line 256 of file createAngularPositionPartials.h.
References createAngularPositionPartials(), tudat::observation_models::receiver, and tudat::observation_models::transmitter.
createCartesianStatePartialsWrtBodyState()
std::map< observation_models::LinkEndType, std::shared_ptr< CartesianStatePartial > > tudat::observation_partials::createCartesianStatePartialsWrtBodyState (const observation_models::LinkEnds & linkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::string bodyToEstimate)
Function to return partial(s) of position of reference point w.r.t state of a single body.
Function to return partial(s) of position of reference point w.r.t state of a single body. A set of link ends and the name of the body wrt the position of which the partials are to be created. A map is returned, with the LinkEndType as key and pointer to state partial as value. An entry for the map is created for each link end which corresponds to the body wrt the position of which the partial is to be taken.
Parameters
linkEnds Set of link ends, for each entry of this map, it is checked whether the body corresponds to the requested body and, if so, a partial object is created.
bodyMap Map of body objects, used in the creation of the partials.
bodyToEstimate Name of body wrt the position of which partials are to be created.
Returns
Map of position partial objects, one entry for each link end corresponding to the bodyToEstimate.
Definition at line 22 of file createCartesianStatePartials.cpp.
Referenced by createAngularPositionPartialWrtBodyPosition(), createOneWayDopplerPartialWrtBodyState(), createOneWayRangePartialWrtBodyPosition(), createPositionObservablePartialWrtPosition(), and createVelocityObservablePartialWrtVelocity().
createCartesianStatePartialsWrtBodyRotationalState()
std::map< observation_models::LinkEndType, std::shared_ptr< CartesianStatePartial > > tudat::observation_partials::createCartesianStatePartialsWrtBodyRotationalState (const observation_models::LinkEnds & linkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::string & bodyToEstimate)
Function to return partial(s) of position of reference point w.r.t rotational state of a single body. A set of link ends and the name of the body wrt the position of which the partials are to be created. A map is returned, with the LinkEndType as key and pointer to state partial as value. An entry for the map is created for each link end which corresponds to the body wrt the position of which the partial is to be taken.
Parameters
linkEnds Set of link ends, for each entry of this map, it is checked whether the body corresponds to the requested body and, if so, a partial object is created.
bodyMap Map of body objects, used in the creation of the partials.
bodyToEstimate Name of body wrt the position of which partials are to be created.
Returns
Map of position partial objects, one entry for each link end corresponding to the bodyToEstimate.
Definition at line 51 of file createCartesianStatePartials.cpp.
References tudat::ground_stations::GroundStationState::getCartesianPositionInTime(), tudat::ephemerides::RotationalEphemeris::getRotationToBaseFrame(), and tudat::basic_astrodynamics::JULIAN_DAY_ON_J2000.
Referenced by createOneWayRangePartialWrtBodyRotationalState().
createCartesianStatePartialsWrtParameter() [1/2]
std::map< observation_models::LinkEndType, std::shared_ptr< CartesianStatePartial > > tudat::observation_partials::createCartesianStatePartialsWrtParameter (const observation_models::LinkEnds linkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameterToEstimate)
Function to return partial object(s) of position of reference point w.r.t. a (double) parameter. A set of link ends and parameter object wrt which the partials are to be created. A map is returned, with the LinkEndType as key and pointer to position partial as value. An entry for the map is created for each entry of linkEnds for which there is a direct dependency between its position and the parameter in question.
Parameters
linkEnds Set of link ends, for each entry of this map, it is checked whether a there is a direct dependency between its position and the parameter in question.
bodyMap Map of body objects, used in the creation of the partials.
parameterToEstimate Parameter object wrt which partials are to be calculated.
Returns
Map of position partial objects, one entry for each link end corresponding to the parameterToEstimate.
Definition at line 97 of file createCartesianStatePartials.cpp.
References tudat::estimatable_parameters::constant_drag_coefficient, createRotationMatrixPartialsWrtParameter(), tudat::estimatable_parameters::direct_dissipation_tidal_time_lag, tudat::estimatable_parameters::equivalence_principle_lpi_violation_parameter, tudat::ground_stations::GroundStationState::getCartesianPositionInTime(), tudat::estimatable_parameters::gravitational_parameter, tudat::estimatable_parameters::isParameterRotationMatrixProperty(), tudat::basic_astrodynamics::JULIAN_DAY_ON_J2000, tudat::estimatable_parameters::mean_moment_of_inertia, tudat::estimatable_parameters::ppn_parameter_beta, tudat::estimatable_parameters::ppn_parameter_gamma, and tudat::estimatable_parameters::radiation_pressure_coefficient.
Referenced by createAngularPositionPartialWrtParameter(), createOneWayDopplerPartialWrtParameter(), and createOneWayRangePartialWrtParameter().
createCartesianStatePartialsWrtParameter() [2/2]
std::map< observation_models::LinkEndType, std::shared_ptr< CartesianStatePartial > > tudat::observation_partials::createCartesianStatePartialsWrtParameter (const observation_models::LinkEnds linkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameterToEstimate)
Function to return partial object(s) of position of reference point w.r.t. a (vector) parameter.
Function to return partial object(s) of position of reference point w.r.t. a (vector) parameter. A set of link ends and parameter object wrt which the partials are to be created. A map is returned, with the LinkEndType as key and pointer to position partial as value. An entry for the map is created for each entry of linkEnds for which there is a direct dependency between its position and the parameter in question.
Parameters
linkEnds Set of link ends, for each entry of this map, it is checked whether a there is a direct dependency between its position and the parameter in question.
bodyMap Map of body objects, used in the creation of the partials.
parameterToEstimate Parameter object wrt which partials are to be calculated.
Returns
Map of position partial objects, one entry for each link end corresponding to the parameterToEstimate.
Definition at line 177 of file createCartesianStatePartials.cpp.
References tudat::estimatable_parameters::arc_wise_constant_drag_coefficient, tudat::estimatable_parameters::arc_wise_empirical_acceleration_coefficients, tudat::estimatable_parameters::arc_wise_radiation_pressure_coefficient, tudat::estimatable_parameters::arcwise_constant_additive_observation_bias, tudat::estimatable_parameters::arcwise_constant_relative_observation_bias, tudat::estimatable_parameters::constant_additive_observation_bias, tudat::estimatable_parameters::constant_relative_observation_bias, createRotationMatrixPartialsWrtParameter(), tudat::estimatable_parameters::empirical_acceleration_coefficients, tudat::estimatable_parameters::full_degree_tidal_love_number, tudat::ground_stations::GroundStationState::getCartesianPositionInTime(), tudat::estimatable_parameters::ground_station_position, tudat::estimatable_parameters::isParameterRotationMatrixProperty(), tudat::basic_astrodynamics::JULIAN_DAY_ON_J2000, tudat::estimatable_parameters::single_degree_variable_tidal_love_number, tudat::estimatable_parameters::spherical_harmonics_cosine_coefficient_block, and tudat::estimatable_parameters::spherical_harmonics_sine_coefficient_block.
createRotationMatrixPartialsWrtTranslationalState()
std::shared_ptr< RotationMatrixPartial > tudat::observation_partials::createRotationMatrixPartialsWrtTranslationalState (const std::shared_ptr< simulation_setup::Body > currentBody)
Function to create partial object(s) of rotation matrix wrt a state parameter
Parameters
currentBody Body for which partial is to be created (must have a synchronous rotation model for output to be non-null)
Returns
Rotation matrix partial object
Definition at line 293 of file createCartesianStatePartials.cpp.
Referenced by createRotationMatrixPartials().
createRotationMatrixPartialsWrtParameter() [1/2]
std::shared_ptr< RotationMatrixPartial > tudat::observation_partials::createRotationMatrixPartialsWrtParameter (const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameterToEstimate)
Function to create partial object(s) of rotation matrix from a body-fixed to inertial frame wrt a (double) parameter.
Parameters
bodyMap Map of body objects, used in the creation of the partial.
parameterToEstimate Parameter wrt which rotation matrix partial object is to be created.
Returns
Requested rotation matrix partial object.
Definition at line 308 of file createCartesianStatePartials.cpp.
References tudat::estimatable_parameters::constant_rotation_rate, tudat::estimatable_parameters::core_factor, and tudat::estimatable_parameters::free_core_nutation_rate.
Referenced by createCartesianStatePartialsWrtParameter(), createRotationMatrixPartials(), and createRotationMatrixPartialsWrtStateParameter().
createRotationMatrixPartialsWrtParameter() [2/2]
std::shared_ptr< RotationMatrixPartial > tudat::observation_partials::createRotationMatrixPartialsWrtParameter (const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameterToEstimate)
Function to create partial object(s) of rotation matrix from a body-fixed to inertial frame wrt a (vector) parameter.
Parameters
bodyMap Map of body objects, used in the creation of the partial.
parameterToEstimate Parameter wrt which rotation matrix partial object is to be created.
Returns
Requested rotation matrix partial object.
Definition at line 381 of file createCartesianStatePartials.cpp.
References tudat::estimatable_parameters::periodic_spin_variation, tudat::estimatable_parameters::polar_motion_amplitude, and tudat::estimatable_parameters::rotation_pole_position.
createPositionObservablePartialWrtPosition()
std::shared_ptr< PositionObervationPartial > tudat::observation_partials::createPositionObservablePartialWrtPosition (const observation_models::LinkEnds linkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::string bodyToEstimate, const std::shared_ptr< PositionObservationScaling > positionObservableScaler)
Function to create an objects that computes the partial derivatives of a three-dimensional position observable w.r.t. the position of a body.
Function to create an objects that computes the partial derivatives of a three-dimensional position observable w.r.t. the position of a body.
the position of a body.
Parameters
linkEnds Set of link ends used for observation model of three-dimensional position
bodyMap List of bodies that comprise the environment
bodyToEstimate Name of body w.r.t. the position of which a partial is to be compured
positionObservableScaler Object that scales position partial to observable partial.
Returns
Single object that computes partial of given observable w.r.t. given parameter.
Definition at line 467 of file createCartesianStatePartials.cpp.
References createCartesianStatePartialsWrtBodyState(), and tudat::estimatable_parameters::initial_body_state.
Referenced by createPositionObservablePartials(), and createRotationMatrixPartials().
createVelocityObservablePartialWrtVelocity()
std::shared_ptr< VelocityObervationPartial > tudat::observation_partials::createVelocityObservablePartialWrtVelocity (const observation_models::LinkEnds linkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::string bodyToEstimate, const std::shared_ptr< VelocityObservationScaling > velocityObservableScaler)
Function to create an objects that computes the partial derivatives of a three-dimensional position observable w.r.t. the Velocity of a body.
Function to create an objects that computes the partial derivatives of a three-dimensional velocity observable w.r.t. the velocity of a body.
the velocity of a body.
Parameters
linkEnds Set of link ends used for observation model of three-dimensional velocity
bodyMap List of bodies that comprise the environment
bodyToEstimate Name of body w.r.t. the velocity of which a partial is to be compured
velocityObservableScaler Object that scales velocity partial to observable partial.
Returns
Single object that computes partial of given observable w.r.t. given parameter.
Definition at line 489 of file createCartesianStatePartials.cpp.
References createCartesianStatePartialsWrtBodyState(), and tudat::estimatable_parameters::initial_body_state.
Referenced by createPositionObservablePartials(), and createVelocityObservablePartials().
createRotationMatrixPartialsWrtStateParameter()
template<typename InitialStateParameterType > std::shared_ptr< RotationMatrixPartial > tudat::observation_partials::createRotationMatrixPartialsWrtStateParameter (const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > parameterToEstimate)
Function to create partial object(s) of rotation matrix wrt a state parameter
Parameters
bodyMap Map of body objects, used in the creation of the partials.
parameterToEstimate Parameter object wrt which partials are to be calculated.
Returns
Rotation matrix partial object
Definition at line 120 of file createCartesianStatePartials.h.
References createRotationMatrixPartialsWrtParameter(), and tudat::estimatable_parameters::initial_rotational_body_state.
Referenced by createRotationMatrixPartials().
createRotationMatrixPartials()
template<typename ParameterType > RotationMatrixPartialNamedList tudat::observation_partials::createRotationMatrixPartials (const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const std::string & bodyName, const simulation_setup::NamedBodyMap & bodyMap)
Function to create rotation matrix partial objects for all rotation model parameters of given body in given set of parameters.
All parameter objects of given EstimatableParameterSet are checked whether they are firstly a property of the requested body, and secondly if they represent a property of the rotation from the body-fixed to base frame. If both conditions are met, a partial is created and added to the return list.
Parameters
parametersToEstimate Set of all parameters which are to be estimated.
bodyName Name of body for which to create partials of rotation from body-fixed to base frame
bodyMap Map of body objects, used in the creation of the partials.
Returns
Rotation matrix partial objects for all rotation model parameters of bodyName in parametersToEstimate.
Definition at line 190 of file createCartesianStatePartials.h.
References createPositionObservablePartialWrtPosition(), createRotationMatrixPartialsWrtParameter(), createRotationMatrixPartialsWrtStateParameter(), createRotationMatrixPartialsWrtTranslationalState(), tudat::estimatable_parameters::initial_body_state, and tudat::estimatable_parameters::isParameterRotationMatrixProperty().
Referenced by tudat::simulation_setup::createAnalyticalAccelerationPartial().
createPositionObservablePartials() [1/2]
template<typename ParameterType > std::pair< SingleLinkObservationThreePartialList, std::shared_ptr< PositionPartialScaling > > tudat::observation_partials::createPositionObservablePartials (const observation_models::LinkEnds positionObservableLinkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate)
Function to create a list of objects that compute the partial derivatives of a three-dimensional position observable A single object is created for each parameter w.r.t. whih a partial derivative is to be taken. Note that the three-dimensional position observable is only sensitive to the position of the body under observation.
Parameters
positionObservableLinkEnds Set of link ends used for observation model of three-dimensional position
bodyMap List of bodies that comprise the environment
parametersToEstimate List of parameters that is to be estimated.
Returns
Pair, first entry is map (key is start index and size of parameter; value is partial object), secod entry is scaling object to be used for all partials.
Definition at line 307 of file createCartesianStatePartials.h.
References tudat::estimatable_parameters::arc_wise_initial_body_state, createPositionObservablePartialWrtPosition(), tudat::estimatable_parameters::EstimatableParameter< ParameterType >::getParameterName(), and tudat::estimatable_parameters::initial_body_state.
Referenced by createPositionObservablePartials().
createPositionObservablePartials() [2/2]
template<typename ParameterType > std::map< observation_models::LinkEnds,std::pair< SingleLinkObservationThreePartialList, std::shared_ptr< PositionPartialScaling > > > tudat::observation_partials::createPositionObservablePartials (const std::vector< observation_models::LinkEnds > linkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate)
Function to create a list of objects that compute the partial derivatives of a list of 3-dimensional position observable A single object is created for each parameter w.r.t. whih a partial derivative is to be taken, separately for each set of link ends. Note that the three-dimensional position observable is only sensitive to the position of the body under observation.
Parameters
linkEnds List of sets of link ends used for observation models of three-dimensional position
bodyMap List of bodies that comprise the environment
parametersToEstimate List of parameters that is to be estimated.
Returns
For each set of link ends a single pair, containing: First entry is map (key is start index and size of parameter; value is partial object), secod entry is scaling object to be used for all partials.
Definition at line 372 of file createCartesianStatePartials.h.
References createPositionObservablePartials(), createVelocityObservablePartialWrtVelocity(), and tudat::observation_models::observed_body.
createVelocityObservablePartials() [1/2]
template<typename ParameterType > std::pair< SingleLinkObservationThreePartialList, std::shared_ptr< PositionPartialScaling > > tudat::observation_partials::createVelocityObservablePartials (const observation_models::LinkEnds velocityObservableLinkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate)
Function to create a list of objects that compute the partial derivatives of a three-dimensional velocity observable A single object is created for each parameter w.r.t. whih a partial derivative is to be taken. Note that the three-dimensional velocity observable is only sensitive to the velocity of the body under observation.
Parameters
velocityObservableLinkEnds Set of link ends used for observation model of three-dimensional velocity
bodyMap List of bodies that comprise the environment
parametersToEstimate List of parameters that is to be estimated.
Returns
Pair, first entry is map (key is start index and size of parameter; value is partial object), secod entry is scaling object to be used for all partials.
Definition at line 423 of file createCartesianStatePartials.h.
References createVelocityObservablePartialWrtVelocity().
Referenced by createVelocityObservablePartials().
createVelocityObservablePartials() [2/2]
template<typename ParameterType > std::map< observation_models::LinkEnds,std::pair< SingleLinkObservationThreePartialList, std::shared_ptr< PositionPartialScaling > > > tudat::observation_partials::createVelocityObservablePartials (const std::vector< observation_models::LinkEnds > linkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate)
Function to create a list of objects that compute the partial derivatives of a list of 3-dimensional velocity observable A single object is created for each parameter w.r.t. whih a partial derivative is to be taken, separately for each set of link ends. Note that the three-dimensional velocity observable is only sensitive to the velocity of the body under observation.
Parameters
linkEnds List of sets of link ends used for observation models of three-dimensional velocity
bodyMap List of bodies that comprise the environment
parametersToEstimate List of parameters that is to be estimated.
Returns
For each set of link ends a single pair, containing: First entry is map (key is start index and size of parameter; value is partial object), secod entry is scaling object to be used for all partials.
Definition at line 491 of file createCartesianStatePartials.h.
References createVelocityObservablePartials(), and tudat::observation_models::observed_body.
splitOneWayRangeRateLightTimeCorrectionsBetweenArcs()
std::pair< PerLinkEndPerLightTimeSolutionCorrections, PerLinkEndPerLightTimeSolutionCorrections > tudat::observation_partials::splitOneWayRangeRateLightTimeCorrectionsBetweenArcs (const PerLinkEndPerLightTimeSolutionCorrections & combinedCorrections)
Function to split the total list of light-time corrections for one-way differenced range rate into list for either arc.
Parameters
combinedCorrections Total list of light-time corrections for one-way differenced range rate, per link end. First vector in map entry should always have size two: entry 0 is for arc start, entry 1 for arc end.
Returns
List of light-time corrections for two arcs of one-way differenced range rate.
Definition at line 21 of file createDifferencedOneWayRangeRatePartials.cpp.
Referenced by createDifferencedOneWayRangeRatePartials().
createDifferencedOneWayRangeRatePartials()
template<typename ParameterType > std::map< observation_models::LinkEnds,std::pair< SingleLinkObservationPartialList, std::shared_ptr< PositionPartialScaling > > > tudat::observation_partials::createDifferencedOneWayRangeRatePartials (const std::vector< observation_models::LinkEnds > linkEnds, const simulation_setup::NamedBodyMap bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const PerLinkEndPerLightTimeSolutionCorrections & lightTimeCorrections = PerLinkEndPerLightTimeSolutionCorrections())
Function to generate one-way differenced range partials for all parameters that are to be estimated, for all sets of link ends The one-way differenced range partials are generated per set of link ends, using partials for the range of the arc start and arc end links The set of parameters and bodies that are to be estimated, as well as the set of link ends (each of which must contain a transmitter and receiever linkEndType) that are to be used.
Parameters
linkEnds Vector of all link ends for which partials are to be calculated
bodyMap List of all bodies that consitute the environment
parametersToEstimate Set of parameters that are to be estimated (in addition to initial states of requested bodies)
lightTimeCorrections List of light time correction partials to be used (empty by default)
Returns
Map of SingleLinkObservationPartialList, representing all necessary one-way differenced range partials of a single link end, and scaling, object, used for scaling the position partial members of all partial in link end.
Definition at line 63 of file createDifferencedOneWayRangeRatePartials.h.
References createOneWayRangePartials(), and splitOneWayRangeRateLightTimeCorrectionsBetweenArcs().
createOneWayDopplerPartialWrtBodyState()
std::shared_ptr< OneWayDopplerPartial > tudat::observation_partials::createOneWayDopplerPartialWrtBodyState (const observation_models::LinkEnds oneWayDopplerLinkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::string bodyToEstimate, const std::shared_ptr< PositionPartialScaling > oneWayDopplerScaler, const std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > > & lightTimeCorrectionPartialObjects = std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > >())
Function to generate one-way doppler partial wrt a position of a body.
Function to generate one-way doppler partial wrt a position of a body, for a single link ends (which must contain a transmitter and receiever linkEndType).
Parameters
oneWayDopplerLinkEnds Link ends (transmitter and receiever) for which one-way doppler partials are to be calculated (i.e. for which one-way doppler observations are to be processed).
bodyMap List of all bodies, for creating one-way doppler partial.
bodyToEstimate Name of body wrt position of which a partial is to be created.
oneWayDopplerScaler Object scale position partials to one-way doppler partials for current link ends.
lightTimeCorrectionPartialObjects List of light time correction partials to be used (empty by default)
Returns
One-way doppler partial object wrt a current position of a body (is nullptr if no parameter dependency exists).
Definition at line 28 of file createDopplerPartials.cpp.
References createCartesianStatePartialsWrtBodyState(), and tudat::estimatable_parameters::initial_body_state.
Referenced by createOneWayDopplerPartials(), and createOneWayDopplerPartialWrtParameter().
createDopplerProperTimePartials()
std::shared_ptr< OneWayDopplerProperTimeComponentScaling > tudat::observation_partials::createDopplerProperTimePartials (const std::shared_ptr< observation_models::DopplerProperTimeRateInterface > dopplerProperTimeInterface, const observation_models::LinkEnds oneWayDopplerLinkEnds, const observation_models::LinkEndType linkEndAtWhichPartialIsComputed)
Function to create an object that computes the scaling of the state partials to obtain proper time rate partials. A single scaling object is used for a single link end of the one-way Doppler partials
Parameters
dopplerProperTimeInterface Object that is used to computed proper-time rate in one-way Doppler modelkkl
oneWayDopplerLinkEnds Link ends of observable
linkEndAtWhichPartialIsComputed Link end for which proper-time partials are to be created
Returns
Scaling object for proper-time rate partials
Definition at line 61 of file createDopplerPartials.cpp.
Referenced by createOneWayDopplerPartials(), and createOneWayDopplerPartialWrtParameter().
createOneWayDopplerPartialWrtParameter()
template<typename ParameterType > std::shared_ptr< ObservationPartial< 1 > > tudat::observation_partials::createOneWayDopplerPartialWrtParameter (const observation_models::LinkEnds oneWayDopplerLinkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameter< ParameterType > > parameterToEstimate, const std::shared_ptr< OneWayDopplerScaling > oneWayDopplerScaler, const std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > > & lightTimeCorrectionPartialObjects = std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > >())
Function to generate one-way doppler partial wrt a single parameter, for a single link ends (which must contain a transmitter and receiever linkEndType).
Template Parameters
ParameterType Type of parameter (double for size 1, VectorXd for larger size).
Parameters
oneWayDopplerLinkEnds Link ends (transmitter and receiever) for which one-way doppler partials are to be calculated (i.e. for which one-way doppler observations are to be processed).
bodyMap List of all bodies, for creating one-way doppler partial.
parameterToEstimate Object of current parameter that is to be estimated.
oneWayDopplerScaler Object scale position partials to one-way doppler partials for current link ends.
lightTimeCorrectionPartialObjects List of light time correction partials to be used (empty by default)
Returns
One-way doppler partial object wrt a single parameter (is nullptr if no parameter dependency exists).
Definition at line 55 of file createDopplerPartials.h.
References createCartesianStatePartialsWrtParameter(), createDopplerProperTimePartials(), and createOneWayDopplerPartialWrtBodyState().
Referenced by createOneWayDopplerPartials().
createOneWayDopplerPartials() [1/2]
template<typename ParameterType > std::pair< SingleLinkObservationPartialList, std::shared_ptr< PositionPartialScaling > > tudat::observation_partials::createOneWayDopplerPartials (const observation_models::LinkEnds oneWayDopplerLinkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const std::shared_ptr< observation_models::DopplerProperTimeRateInterface > transmitterDopplerProperTimeInterface, const std::shared_ptr< observation_models::DopplerProperTimeRateInterface > receiverDopplerProperTimeInterface, const std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > & lightTimeCorrections = std::vector< std::shared_ptr< observation_models::LightTimeCorrection > >(), const bool useBiasPartials = true)
Function to generate one-way doppler partials and associated scaler for all parameters that are to be estimated, for a single link ends. The set of parameters and bodies that are to be estimated, as well as the set of link ends (each of which must contain a transmitter and receiever linkEndType) that are to be used.
Parameters
oneWayDopplerLinkEnds Link ends (transmitter and receiever) for which one-way doppler partials are to be calculated (i.e. for which one-way doppler observations are to be processed).
bodyMap List of all bodies, for creating one-way doppler partials.
parametersToEstimate Set of parameters that are to be estimated (in addition to initial states of requested bodies)
transmitterDopplerProperTimeInterface Proper time rate calculator for transmitter
receiverDopplerProperTimeInterface Proper time rate calculator for receiver
lightTimeCorrections List of light time correction partials to be used (empty by default)
useBiasPartials Boolean to denote whether this function should create partials w.r.t. observation bias parameters
Returns
Set of observation partials with associated indices in complete vector of parameters that are estimated, representing all necessary one-way doppler partials of a single link end, and OneWayDopplerScaling, object, used for scaling the position partial members of all OneWayDopplerPartials in link end.
Definition at line 146 of file createDopplerPartials.h.
References tudat::estimatable_parameters::arc_wise_initial_body_state, createDopplerProperTimePartials(), createLightTimeCorrectionPartials(), createOneWayDopplerPartialWrtBodyState(), createOneWayDopplerPartialWrtParameter(), tudat::linear_algebra::evaluateSecondBlockInStateVector(), tudat::estimatable_parameters::EstimatableParameter< ParameterType >::getParameterName(), tudat::estimatable_parameters::initial_body_state, tudat::estimatable_parameters::isParameterObservationLinkProperty(), tudat::observation_models::one_way_doppler, tudat::numerical_derivatives::order8, tudat::observation_models::receiver, and tudat::observation_models::transmitter.
Referenced by createTwoWayDopplerPartials().
createOneWayDopplerPartials() [2/2]
template<typename ObservationScalarType , typename TimeType > std::map< observation_models::LinkEnds, std::pair< SingleLinkObservationPartialList,std::shared_ptr< PositionPartialScaling > > > tudat::observation_partials::createOneWayDopplerPartials (const std::map< observation_models::LinkEnds, std::shared_ptr< observation_models::ObservationModel< 1, ObservationScalarType, TimeType > > > observationModelList, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ObservationScalarType > > parametersToEstimate, const bool useBiasPartials = true)
Function to generate one-way doppler partials for all parameters that are to be estimated, for all sets of link ends. The one-way doppler partials are generated per set of link ends. The set of parameters and bodies that are to be estimated, as well as the set of link ends (each of which must contain a transmitter and receiever linkEndType) that are to be used.
Parameters
observationModelList List of all observation models (must be one-way Doppler) for which partials are to be created, with map key being the link ends
bodyMap List of all bodies, for creating one-way doppler partials.
parametersToEstimate Set of parameters that are to be estimated (in addition to initial states of requested bodies)
useBiasPartials Boolean to denote whether this function should create partials w.r.t. observation bias parameters
Returns
Map of SingleLinkObservationPartialList, representing all necessary one-way doppler partials of a single link end, and OneWayDopplerScaling, object, used for scaling the position partial members of all OneWayDopplerPartials in link end.
Definition at line 306 of file createDopplerPartials.h.
References tudat::observation_models::receiver, and tudat::observation_models::transmitter.
createTwoWayDopplerPartials() [1/2]
template<typename ParameterType , typename TimeType > std::pair< SingleLinkObservationPartialList, std::shared_ptr< PositionPartialScaling > > tudat::observation_partials::createTwoWayDopplerPartials (const observation_models::LinkEnds & twoWayDopplerLinkEnds, const std::shared_ptr< observation_models::TwoWayDopplerObservationModel< ParameterType, TimeType > > twoWayObservationModel, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > > lightTimeCorrections = std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > >())
Function to generate tow-way Doppler partials and associated scaler for all parameters that are to be estimated, for a single link ends set. The set of parameters and bodies that are to be estimated, as well as the set of link ends (each of which must contain a transmitter and receiever linkEndType) that are to be used. The tow-way Doppler partials are built from one-way Doppler partials of the constituent links
Parameters
twoWayDopplerLinkEnds Link ends (transmitter and receiever) for which tow-way Doppler partials are to be calculated (i.e. for which tow-way Doppler observations are to be processed).
twoWayObservationModel Observation model for two-way Doppler for which partials are to be created
bodyMap List of all bodies, for creating tow-way Doppler partials.
parametersToEstimate Set of parameters that are to be estimated (in addition to initial states of requested bodies)
lightTimeCorrections List of light time correction partials to be used (empty by default). First vector entry is index of link in 2-way link ends (up and downlink), second vector is list of light-time corrections.
Returns
Set of observation partials with associated indices in complete vector of parameters that are estimated, representing all necessary two-way Doppler partials of a single link end, and TwoWayDopplerScaling, object, used for scaling the position partial members of all TwoWayDopplerPartials in link end.
Definition at line 379 of file createDopplerPartials.h.
References createOneWayDopplerPartials(), createOneWayRangePartials(), tudat::observation_models::getNWayLinkEnumFromIndex(), tudat::observation_models::getSizeOneObservationFunctionAtDoublePrecisionFromObservationModel(), tudat::estimatable_parameters::isParameterObservationLinkProperty(), tudat::observation_models::receiver, tudat::observation_models::transmitter, and tudat::observation_models::two_way_doppler.
createTwoWayDopplerPartials() [2/2]
template<typename ParameterType , typename TimeType > std::map< observation_models::LinkEnds, std::pair< SingleLinkObservationPartialList, std::shared_ptr< PositionPartialScaling > > > tudat::observation_partials::createTwoWayDopplerPartials (const std::map< observation_models::LinkEnds, std::shared_ptr< observation_models::ObservationModel< 1, ParameterType, TimeType > > > observationModelList, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const std::map< observation_models::LinkEnds, std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > > > & lightTimeCorrections = std::map< observation_models::LinkEnds, std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > > >())
Function to generate two-way Doppler partials for all parameters that are to be estimated, for all sets of link ends. The two-way Doppler partials are generated per set of link ends. The set of parameters and bodies that are to be estimated, as well as the set of link ends (each of which must contain a transmitter and receiever linkEndType) that are to be used. The two-way Doppler partials are built from one-way range partials of the constituent links
Parameters
observationModelList List of all two-way Doppler models (as a function of LinkEnds) for which partials are to be created.
bodyMap List of all bodies, for creating two-way Doppler partials.
parametersToEstimate Set of parameters that are to be estimated (in addition to initial states of requested bodies)
lightTimeCorrections List of light time correction used (empty by default). First vector entry is index of link in 2-way link ends (up and downlink), second vector is list of light-time corrections.
Returns
Map of SingleLinkObservationPartialList, representing all necessary two-way Doppler partials of a single link end, and TwoWayDopplerScaling, object, used for scaling the position partial members of all TwoWayDopplerPartials in link end.
Definition at line 584 of file createDopplerPartials.h.
createEulerAngleObservablePartialWrtCurrentRotationalState()
std::shared_ptr< ObservationPartial< 3 > > tudat::observation_partials::createEulerAngleObservablePartialWrtCurrentRotationalState (const estimatable_parameters::EstimatebleParameterIdentifier parameterIdentifier)
Function to create object that comptes partial derivative of Euler angle observation w.r.t. current rotational state.
Function to create object that comptes partial derivative of Euler angle observation w.r.t. current rotational state
Parameters
parameterIdentifier Type and reference body of parameter to be estimated (initial rotational state)
Returns
Object that comptes partial derivative of Euler angle observation w.r.t. current rotational state
Definition at line 12 of file createEulerAngleObservationPartials.cpp.
Referenced by createEulerAngleObservablePartials().
createEulerAngleObservablePartials() [1/2]
template<typename ParameterType > std::pair< SingleLinkObservationThreePartialList, std::shared_ptr< PositionPartialScaling > > tudat::observation_partials::createEulerAngleObservablePartials (const observation_models::LinkEnds eulerAngleLinkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate)
Function to compute Euler angle observation partial objects for a single set of link ends
Parameters
eulerAngleLinkEnds Link ends (observed_body only) for which Euler angle partials are to be calculated
bodyMap List of all bodies, for creating Euler angle partials.
parametersToEstimate Set of parameters that are to be estimated (in addition to initial states of requested bodies)
Returns
Set of observation partials with associated indices in complete vector of parameters that are estimated, representing all necessary Euler angle partials of a single link end, and a nulptr position scaling pointer.
Definition at line 57 of file createEulerAngleObservationPartials.h.
References createEulerAngleObservablePartialWrtCurrentRotationalState(), and tudat::estimatable_parameters::isParameterRotationMatrixProperty().
Referenced by createEulerAngleObservablePartials().
createEulerAngleObservablePartials() [2/2]
template<typename ParameterType > std::map< observation_models::LinkEnds,std::pair< SingleLinkObservationThreePartialList, std::shared_ptr< PositionPartialScaling > > > tudat::observation_partials::createEulerAngleObservablePartials (const std::vector< observation_models::LinkEnds > linkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate)
Function to compute Euler angle observation partial objects for multiple sets of link ends
Parameters
linkEnds List of link ends (observed_body only) for which Euler angle partials are to be calculated
bodyMap List of all bodies, for creating Euler angle partials.
parametersToEstimate Set of parameters that are to be estimated (in addition to initial states of requested bodies)
Returns
Set of observation partials with associated indices in complete vector of parameters that are estimated, representing all necessary Euler angle partials of a single link end, and a nulptr position scaling pointer.
Definition at line 148 of file createEulerAngleObservationPartials.h.
References createEulerAngleObservablePartials(), and tudat::observation_models::observed_body.
createLightTimeCorrectionPartials()
std::vector< std::shared_ptr< LightTimeCorrectionPartial > > tudat::observation_partials::createLightTimeCorrectionPartials (const std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > & lightTimeCorrectionList)
Function to create a partial objects from list of light time corrections.
Parameters
lightTimeCorrectionList List of light time corrections.
Returns
List of light-time correction partial objects
Definition at line 24 of file createLightTimeCorrectionPartials.cpp.
References tudat::observation_models::first_order_relativistic.
Referenced by createAngularPositionPartials(), createOneWayDopplerPartials(), and createOneWayRangePartials().
createNWayRangePartials() [1/2]
template<typename ParameterType > std::pair< SingleLinkObservationPartialList, std::shared_ptr< PositionPartialScaling > > tudat::observation_partials::createNWayRangePartials (const observation_models::LinkEnds & nWayRangeLinkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > > lightTimeCorrections = std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > >())
Function to generate n-way range partials and associated scaler for all parameters that are to be estimated, for a single link ends set. The set of parameters and bodies that are to be estimated, as well as the set of link ends (each of which must contain a transmitter and receiever linkEndType) that are to be used. The n-way range partials are built from one-way range partials of the constituent links
Parameters
nWayRangeLinkEnds Link ends (transmitter and receiever) for which n-way range partials are to be calculated (i.e. for which n-way range observations are to be processed).
bodyMap List of all bodies, for creating n-way range partials.
parametersToEstimate Set of parameters that are to be estimated (in addition to initial states of requested bodies)
lightTimeCorrections List of light time correction partials to be used (empty by default). First vector entry is index of link in n-way link ends, second vector is list of light-time corrections.
Returns
Set of observation partials with associated indices in complete vector of parameters that are estimated, representing all necessary n-way range partials of a single link end, and NWayRangeScaling, object, used for scaling the position partial members of all NWayRangePartials in link end.
Definition at line 53 of file createNWayRangePartials.h.
References createOneWayRangePartials(), tudat::observation_models::getNWayLinkEnumFromIndex(), tudat::estimatable_parameters::isParameterObservationLinkProperty(), tudat::observation_models::n_way_range, tudat::observation_models::receiver, and tudat::observation_models::transmitter.
createNWayRangePartials() [2/2]
template<typename ParameterType > std::map< observation_models::LinkEnds, std::pair< SingleLinkObservationPartialList, std::shared_ptr< PositionPartialScaling > > > tudat::observation_partials::createNWayRangePartials (const std::vector< observation_models::LinkEnds > & linkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const std::map< observation_models::LinkEnds, std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > > > & lightTimeCorrections = std::map< observation_models::LinkEnds, std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > > >())
Function to generate n-way range partials for all parameters that are to be estimated, for all sets of link ends. The n-way range partials are generated per set of link ends. The set of parameters and bodies that are to be estimated, as well as the set of link ends (each of which must contain a transmitter and receiever linkEndType) that are to be used. The n-way range partials are built from one-way range partials of the constituent links
Parameters
linkEnds List of all n-way link ends sets with observation models for which partials are to be created
bodyMap List of all bodies, for creating n-way range partials.
parametersToEstimate Set of parameters that are to be estimated (in addition to initial states of requested bodies)
lightTimeCorrections List of light time correction partials to be used (empty by default). First vector entry is index of link in n-way link ends, second vector is list of light-time corrections.
Returns
Map of SingleLinkObservationPartialList, representing all necessary n-way range partials of a single link end, and NWayRangeScaling, object, used for scaling the position partial members of all NWayRangePartials in link end.
Definition at line 182 of file createNWayRangePartials.h.
getLightTimeCorrectionsList()
template<typename ObservationScalarType , typename TimeType , int ObservationSize> PerLinkEndPerLightTimeSolutionCorrections tudat::observation_partials::getLightTimeCorrectionsList (const std::map< observation_models::LinkEnds, std::shared_ptr< observation_models::ObservationModel< ObservationSize, ObservationScalarType, TimeType > > > observationModels)
Function to retrieve a list of light-time corrections per link end from a list of observation models.
Parameters
observationModels Map of observation models (may not be of mixed type) with LinkEnds of observable as map key
Returns
Map of light-time corrections, with associated link ends as key.
Definition at line 44 of file createObservationPartials.h.
References tudat::observation_models::angular_position, tudat::observation_models::euler_angle_313_observable, tudat::observation_models::NWayRangeObservationModel< ObservationScalarType, TimeType >::getLightTimeCalculators(), tudat::observation_models::n_way_range, tudat::observation_models::one_way_differenced_range, tudat::observation_models::one_way_doppler, tudat::observation_models::one_way_range, tudat::observation_models::position_observable, tudat::observation_models::two_way_doppler, and tudat::observation_models::velocity_observable.
Referenced by tudat::observation_partials::ObservationPartialCreator< 1, ObservationScalarType, TimeType >::createObservationPartials(), and tudat::observation_partials::ObservationPartialCreator< 2, ObservationScalarType, TimeType >::createObservationPartials().
splitObservationPartialsAndScalers()
template<int ObservationSize> void tudat::observation_partials::splitObservationPartialsAndScalers (const std::map< observation_models::LinkEnds, std::pair< std::map< std::pair< int, int >, std::shared_ptr< ObservationPartial< ObservationSize > > >, std::shared_ptr< PositionPartialScaling > > > & observationPartialsAndScalers, std::map< observation_models::LinkEnds, std::map< std::pair< int, int >, std::shared_ptr< observation_partials::ObservationPartial< ObservationSize > > > > & observationPartials, std::map< observation_models::LinkEnds, std::shared_ptr< observation_partials::PositionPartialScaling > > & observationPartialScalers)
Function to split observation partials and scaling object (produced by observationPartialsAndScaler function) into separate containers
Parameters
observationPartialsAndScalers Combined list of observation partials and scaling objects
observationPartials List of observation partials, per link ends, and per parameter indices (returned by reference)
observationPartialScalers List of position partial scaling objects, per link ends (returned by reference)
Definition at line 194 of file createObservationPartials.h.
Referenced by tudat::observation_models::createObservationManager().
createOneWayRangePartialWrtBodyPosition()
std::shared_ptr< OneWayRangePartial > tudat::observation_partials::createOneWayRangePartialWrtBodyPosition (const observation_models::LinkEnds oneWayRangeLinkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::string bodyToEstimate, const std::shared_ptr< OneWayRangeScaling > oneWayRangeScaler, const std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > > & lightTimeCorrectionPartialObjects = std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > >())
Function to generate one-way range partial wrt a position of a body.
Function to generate one-way range partial wrt a position of a body, for a single link ends (which must contain a transmitter and receiever linkEndType).
Parameters
oneWayRangeLinkEnds Link ends (transmitter and receiever) for which one-way range partials are to be calculated (i.e. for which one-way range observations are to be processed).
bodyMap List of all bodies, for creating one-way range partial.
bodyToEstimate Name of body wrt position of which a partial is to be created.
oneWayRangeScaler Object scale position partials to one-way range partials for current link ends.
lightTimeCorrectionPartialObjects List of light time correction partials to be used (empty by default)
Returns
One-way range partial object wrt a current position of a body (is nullptr if no parameter dependency exists).
Definition at line 27 of file createOneWayRangePartials.cpp.
References createCartesianStatePartialsWrtBodyState(), and tudat::estimatable_parameters::initial_body_state.
Referenced by createOneWayRangePartials(), and createOneWayRangePartialWrtParameter().
createOneWayRangePartialWrtBodyRotationalState()
std::shared_ptr< OneWayRangePartial > tudat::observation_partials::createOneWayRangePartialWrtBodyRotationalState (const observation_models::LinkEnds oneWayRangeLinkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::string bodyToEstimate, const std::shared_ptr< OneWayRangeScaling > oneWayRangeScaler, const std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > > & lightTimeCorrectionPartialObjects)
Function to generate one-way range partial wrt a rotational state of a body.
Function to generate one-way range partial wrt a rotational state of a body, for a single link ends (which must contain a transmitter and receiever linkEndType).
Parameters
oneWayRangeLinkEnds Link ends (transmitter and receiever) for which one-way range partials are to be calculated (i.e. for which one-way range observations are to be processed).
bodyMap List of all bodies, for creating one-way range partial.
bodyToEstimate Name of body wrt rotational state of which a partial is to be created.
oneWayRangeScaler Object scale position partials to one-way range partials for current link ends.
lightTimeCorrectionPartialObjects List of light time correction partials to be used (empty by default)
Returns
One-way range partial object wrt a current rotational state of a body (is nullptr if no parameter dependency exists).
Definition at line 54 of file createOneWayRangePartials.cpp.
References createCartesianStatePartialsWrtBodyRotationalState(), and tudat::estimatable_parameters::initial_body_state.
Referenced by createOneWayRangePartials(), and createOneWayRangePartialWrtParameter().
createOneWayRangePartialWrtParameter()
template<typename ParameterType > std::shared_ptr< ObservationPartial< 1 > > tudat::observation_partials::createOneWayRangePartialWrtParameter (const observation_models::LinkEnds oneWayRangeLinkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameter< ParameterType > > parameterToEstimate, const std::shared_ptr< OneWayRangeScaling > oneWayRangeScaler, const std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > > & lightTimeCorrectionPartialObjects = std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > >())
Function to generate one-way range partial wrt a single parameter, for a single link ends (which must contain a transmitter and receiever linkEndType).
Template Parameters
ParameterType Type of parameter (double for size 1, VectorXd for larger size).
Parameters
oneWayRangeLinkEnds Link ends (transmitter and receiever) for which one-way range partials are to be calculated (i.e. for which one-way range observations are to be processed).
bodyMap List of all bodies, for creating one-way range partial.
parameterToEstimate Object of current parameter that is to be estimated.
oneWayRangeScaler Object scale position partials to one-way range partials for current link ends.
lightTimeCorrectionPartialObjects List of light time correction partials to be used (empty by default)
Returns
One-way range partial object wrt a single parameter (is nullptr if no parameter dependency exists).
Definition at line 52 of file createOneWayRangePartials.h.
References createCartesianStatePartialsWrtParameter(), createOneWayRangePartialWrtBodyPosition(), and createOneWayRangePartialWrtBodyRotationalState().
Referenced by createOneWayRangePartials().
createOneWayRangePartials() [1/2]
template<typename ParameterType > std::pair< SingleLinkObservationPartialList, std::shared_ptr< PositionPartialScaling > > tudat::observation_partials::createOneWayRangePartials (const observation_models::LinkEnds oneWayRangeLinkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > & lightTimeCorrections = std::vector< std::shared_ptr< observation_models::LightTimeCorrection > >(), const bool useBiasPartials = true)
Function to generate one-way range partials and associated scaler for all parameters that are to be estimated, for a single link ends set. The set of parameters and bodies that are to be estimated, as well as the set of link ends (each of which must contain a transmitter and receiever linkEndType) that are to be used.
Parameters
oneWayRangeLinkEnds Link ends (transmitter and receiever) for which one-way range partials are to be calculated (i.e. for which one-way range observations are to be processed).
bodyMap List of all bodies, for creating one-way range partials.
parametersToEstimate Set of parameters that are to be estimated
lightTimeCorrections List of light time correction partials to be used (empty by default)
useBiasPartials Boolean to denote whether this function should create partials w.r.t. observation bias parameters
Returns
Set of observation partials with associated indices in complete vector of parameters that are estimated, representing all necessary one-way range partials of a single link end, and OneWayRangeScaling, object, used for scaling the position partial members of all OneWayRangePartials in link end.
Definition at line 139 of file createOneWayRangePartials.h.
References tudat::estimatable_parameters::arc_wise_initial_body_state, createLightTimeCorrectionPartials(), createOneWayRangePartialWrtBodyPosition(), createOneWayRangePartialWrtBodyRotationalState(), createOneWayRangePartialWrtParameter(), tudat::estimatable_parameters::EstimatableParameter< ParameterType >::getParameterName(), tudat::estimatable_parameters::initial_body_state, tudat::estimatable_parameters::initial_rotational_body_state, tudat::estimatable_parameters::isParameterObservationLinkProperty(), and tudat::observation_models::one_way_range.
Referenced by createDifferencedOneWayRangeRatePartials(), createNWayRangePartials(), and createTwoWayDopplerPartials().
createOneWayRangePartials() [2/2]
template<typename ParameterType > std::map< observation_models::LinkEnds, std::pair< SingleLinkObservationPartialList,std::shared_ptr< PositionPartialScaling > > > tudat::observation_partials::createOneWayRangePartials (const std::vector< observation_models::LinkEnds > & linkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const std::map< observation_models::LinkEnds, std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > > > & lightTimeCorrections = std::map< observation_models::LinkEnds, std::vector< std::vector< std::shared_ptr< observation_models::LightTimeCorrection > > > >(), const bool useBiasPartials = true)
Function to generate one-way range partials for all parameters that are to be estimated, for all sets of link ends. The one-way range partials are generated per set of link ends. The set of parameters and bodies that are to be estimated, as well as the set of link ends (each of which must contain a transmitter and receiever linkEndType) that are to be used.
Parameters
linkEnds Vector of all link ends for which one-way range partials are to be calculated (i.e. for which one-way range observations are to be processed).
bodyMap List of all bodies, for creating one-way range partials.
parametersToEstimate Set of parameters that are to be estimated (in addition to initial states of requested bodies)
lightTimeCorrections List of light time correction partials to be used (empty by default)
useBiasPartials Boolean to denote whether this function should create partials w.r.t. observation bias parameters
Returns
Map of SingleLinkObservationPartialList, representing all necessary one-way range partials of a single link end, and OneWayRangeScaling, object, used for scaling the position partial members of all OneWayRangePartials in link end.
Definition at line 293 of file createOneWayRangePartials.h.
References tudat::observation_models::receiver, and tudat::observation_models::transmitter.
Variable Documentation
getLightTimeParameterPartialFunction
std::pair< std::function< LightTimeCorrectionPartial::SingleOneWayRangePartialReturnType(const std::vector< Eigen::Vector6d >&, const std::vector< double >&) >, bool > tudat::observation_partials::getLightTimeParameterPartialFunction(const estimatable_parameters::EstimatebleParameterIdentifier parameterId, const std::shared_ptr< LightTimeCorrectionPartial > lightTimeCorrectionPartial)
Function to get the function returning the light-time correction partial for given correction partial and parameter.
Parameters
parameterId Parameter for which partial derivative is to be computed.
lightTimeCorrectionPartial Partial object from which partial function is to be retrieved.
Returns
Pair (with second entry boolean which is true if the partial is non-zero). First entry of pair gives partial and associated time as a function of link-end states and times.
Definition at line 82 of file lightTimeCorrectionPartial.h.
Referenced by tudat::observation_partials::AngularPositionPartial::AngularPositionPartial(), tudat::observation_partials::OneWayDopplerPartial::OneWayDopplerPartial(), and tudat::observation_partials::OneWayRangePartial::OneWayRangePartial().