Tudat: tudat::numerical_quadrature Namespace Reference
tudat::numerical_quadrature Namespace Reference
Classes
class GaussianQuadrature
Gaussian numerical quadrature wrapper class.
class GaussianQuadratureSettings
Class to define settings of gaussian quadrature.
struct GaussQuadratureNodesAndWeights
Container object for Gauss quadrature nodes and weights (templated by data variable type, e.g. float, double, long double)
class NumericalQuadrature
Base class for numerical quadrature.
class QuadratureSettings
Class to define settings of numerical quadrature.
class TrapezoidNumericalQuadrature
Trapezoid numerical quadrature wrapper class.
class TrapezoidQuadratureSettings
Class to define settings of trapezoid quadrature.
Typedefs
typedef std::shared_ptr< TrapezoidNumericalQuadrature< double, double > > TrapezoidNumericalIntegratorPointerd
Typede for trapezoidal quadrature with double (in)dependent variables.
Enumerations
enum AvailableQuadratures { trapezoidal, gaussian }
Enum to define available numerical quadratures.
Functions
template<typename IndependentVariableType , typename DependentVariableType >
std::shared_ptr< numerical_quadrature::NumericalQuadrature< IndependentVariableType, DependentVariableType > > createQuadrature (std::function< DependentVariableType(const IndependentVariableType) > derivativeFunction, std::shared_ptr< QuadratureSettings< IndependentVariableType > > quadratureSettings, IndependentVariableType finalIndependentVariable=TUDAT_NAN)
Function to create a numerical quadrature.
template<typename IndependentVariableType >
std::shared_ptr< GaussQuadratureNodesAndWeights< IndependentVariableType > > getGaussQuadratureNodesAndWeights ()
Function to create Gauss quadrature node/weight container.
template<>
std::shared_ptr< GaussQuadratureNodesAndWeights< long double > > getGaussQuadratureNodesAndWeights ()
Function to create Gauss quadrature node/weight container with long double precision.
template<>
std::shared_ptr< GaussQuadratureNodesAndWeights< double > > getGaussQuadratureNodesAndWeights ()
Function to create Gauss quadrature node/weight container with double precision.
template<>
std::shared_ptr< GaussQuadratureNodesAndWeights< float > > getGaussQuadratureNodesAndWeights ()
Function to create Gauss quadrature node/weight container with float precision.
template<typename IndependentVariableType , typename DependentVariableType >
DependentVariableType performExtendedSimpsonsQuadrature (const IndependentVariableType constantIndependentVariableStep, const std::vector< DependentVariableType > &dependentVariables)
Function to perform numerical quadrature using the extended Simpson's method.
template<typename IndependentVariableType , typename DependentVariableType >
DependentVariableType performTrapezoidalQuadrature (const std::vector< IndependentVariableType > &independentVariables, const std::vector< DependentVariableType > &dependentVariables)
Function to perform numerical quadrature using the trapezoidal method.
template<typename IndependentVariableType >
void readGaussianQuadratureNodes (std::map< unsigned int, Eigen::Array< IndependentVariableType, Eigen::Dynamic, 1 > > &gaussQuadratureNodes)
Read Gaussian nodes from text file.
template<typename IndependentVariableType >
void readGaussianQuadratureWeights (std::map< unsigned int, Eigen::Array< IndependentVariableType, Eigen::Dynamic, 1 > > &gaussQuadratureWeights)
Read Gaussian weight factors from text file.
Variables
static const std::shared_ptr< GaussQuadratureNodesAndWeights< double > > doubleGaussQuadratureNodesAndWeights
Object containing nodes/weights for double Gauss quadrature.
static const std::shared_ptr< GaussQuadratureNodesAndWeights< float > > floatGaussQuadratureNodesAndWeights
Object containing nodes/weights for float Gauss quadrature.
static const std::shared_ptr< GaussQuadratureNodesAndWeights< long double > > longDoubleGaussQuadratureNodesAndWeights
Object containing nodes/weights for long double Gauss quadrature.
Typedef Documentation
TrapezoidNumericalIntegratorPointerd
typedef std::shared_ptr< TrapezoidNumericalQuadrature< double, double > > tudat::numerical_quadrature::TrapezoidNumericalIntegratorPointerd
Definition at line 188 of file trapezoidQuadrature.h.
Enumeration Type Documentation
AvailableQuadratures
enum tudat::numerical_quadrature::AvailableQuadratures
Enumerator
trapezoidal
gaussian
Definition at line 29 of file createNumericalQuadrature.h.
Function Documentation
createQuadrature()
template<typename IndependentVariableType , typename DependentVariableType > std::shared_ptr< numerical_quadrature::NumericalQuadrature< IndependentVariableType, DependentVariableType > > tudat::numerical_quadrature::createQuadrature (std::function< DependentVariableType(const IndependentVariableType) > derivativeFunction, std::shared_ptr< QuadratureSettings< IndependentVariableType > > quadratureSettings, IndependentVariableType finalIndependentVariable = TUDAT_NAN)
Function to create a numerical quadrature from given quadrature settings, and derivative function.
Parameters
derivativeFunction Function returning the derivative from current independent variable.
quadratureSettings Settings for numerical quadrature.
finalIndependentVariable Final independent variable of numerical quadrature.
Returns
Numerical quadrature object.
Definition at line 151 of file createNumericalQuadrature.h.
References gaussian, tudat::numerical_quadrature::TrapezoidQuadratureSettings< IndependentVariableType >::independentVariables_, and trapezoidal.
Referenced by tudat::shape_based_methods::HodographicShaping::computeCurrentPolarAngle(), tudat::shape_based_methods::SphericalShaping::computeCurrentTimeFromAzimuthAngle(), tudat::shape_based_methods::SphericalShaping::computeDeltaV(), tudat::low_thrust_trajectories::HybridMethodModel::computeDeltaV(), tudat::shape_based_methods::HodographicShaping::computeDeltaV(), tudat::shape_based_methods::SphericalShaping::computeNormalizedTimeOfFlight(), tudat::shape_based_methods::HodographicShaping::computeThirdFixedCoefficientAxialVelocityFromFinalPolarAngle(), and tudat::shape_based_methods::SphericalShaping::convertIndependentVariableToTime().
getGaussQuadratureNodesAndWeights() [1/4]
template<typename IndependentVariableType > std::shared_ptr< GaussQuadratureNodesAndWeights< IndependentVariableType > > tudat::numerical_quadrature::getGaussQuadratureNodesAndWeights ()
Function to create Gauss quadrature node/weight container, templated by independent variable type
Returns
Gauss quadrature node/weight container
Definition at line 12 of file gaussianQuadrature.cpp.
getGaussQuadratureNodesAndWeights() [2/4]
template<> std::shared_ptr< GaussQuadratureNodesAndWeights< long double > > tudat::numerical_quadrature::getGaussQuadratureNodesAndWeights ()
Function to create Gauss quadrature node/weight container with long double precision.
Returns
Gauss quadrature node/weight container
Definition at line 20 of file gaussianQuadrature.cpp.
References longDoubleGaussQuadratureNodesAndWeights.
getGaussQuadratureNodesAndWeights() [3/4]
template<> std::shared_ptr< GaussQuadratureNodesAndWeights< double > > tudat::numerical_quadrature::getGaussQuadratureNodesAndWeights ()
Function to create Gauss quadrature node/weight container with double precision.
Returns
Gauss quadrature node/weight container
Definition at line 28 of file gaussianQuadrature.cpp.
References doubleGaussQuadratureNodesAndWeights.
getGaussQuadratureNodesAndWeights() [4/4]
template<> std::shared_ptr< GaussQuadratureNodesAndWeights< float > > tudat::numerical_quadrature::getGaussQuadratureNodesAndWeights ()
Function to create Gauss quadrature node/weight container with float precision.
Returns
Gauss quadrature node/weight container
Definition at line 36 of file gaussianQuadrature.cpp.
References floatGaussQuadratureNodesAndWeights.
readGaussianQuadratureNodes()
template<typename IndependentVariableType > void tudat::numerical_quadrature::readGaussianQuadratureNodes (std::map< unsigned int, Eigen::Array< IndependentVariableType, Eigen::Dynamic, 1 > > & gaussQuadratureNodes)
Read Gaussian nodes from text file, file name is hard-coded into this function, read nodes are returned by reference
Parameters
gaussQuadratureNodes Gauss quadrature nodes that are read from the file. Map key denotes the order, map value the list of nodes for that order.
Definition at line 42 of file gaussianQuadrature.h.
References tudat::input_output::getTudatRootPath().
readGaussianQuadratureWeights()
template<typename IndependentVariableType > void tudat::numerical_quadrature::readGaussianQuadratureWeights (std::map< unsigned int, Eigen::Array< IndependentVariableType, Eigen::Dynamic, 1 > > & gaussQuadratureWeights)
Read Gaussian weight factors from text file, file name is hard-coded into this function, read nodes are returned by reference
Parameters
gaussQuadratureWeights Gauss quadrature weights that are read from the file. Map key denotes the order, map value the list of weights for that order.
Definition at line 59 of file gaussianQuadrature.h.
References tudat::input_output::getTudatRootPath().
performTrapezoidalQuadrature()
template<typename IndependentVariableType , typename DependentVariableType > DependentVariableType tudat::numerical_quadrature::performTrapezoidalQuadrature (const std::vector< IndependentVariableType > & independentVariables, const std::vector< DependentVariableType > & dependentVariables)
Function to perform numerical quadrature using the trapezoidal method.
Parameters
independentVariables Values of independent variables at which dependentVariables are given.
dependentVariables Values of function for which the numerical quadrature is to be computed, given at independentVariables.
Returns
Numerical quadrature (integral) of the data provided as input.
Definition at line 42 of file trapezoidQuadrature.h.
Referenced by tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::performQuadrature().
performExtendedSimpsonsQuadrature()
template<typename IndependentVariableType , typename DependentVariableType > DependentVariableType tudat::numerical_quadrature::performExtendedSimpsonsQuadrature (const IndependentVariableType constantIndependentVariableStep, const std::vector< DependentVariableType > & dependentVariables)
Function to perform numerical quadrature using the extended Simpson's method (Press et al., 1992). Note that the spacing of the (in)dependent needs to be constant.
Parameters
constantIndependentVariableStep Constant independent variable step size.
dependentVariables Values of function for which the numerical quadrature is to be computed, given at independentVariables.
Returns
Numerical quadrature (integral) of the data provided as input.
Definition at line 66 of file trapezoidQuadrature.h.
Variable Documentation
longDoubleGaussQuadratureNodesAndWeights
const std::shared_ptr< GaussQuadratureNodesAndWeights< long double > > tudat::numerical_quadrature::longDoubleGaussQuadratureNodesAndWeights static
Initial value:
=
        std::make_shared< GaussQuadratureNodesAndWeights< long double > >( )
Definition at line 193 of file gaussianQuadrature.h.
Referenced by getGaussQuadratureNodesAndWeights().
doubleGaussQuadratureNodesAndWeights
const std::shared_ptr< GaussQuadratureNodesAndWeights< double > > tudat::numerical_quadrature::doubleGaussQuadratureNodesAndWeights static
Initial value:
=
        std::make_shared< GaussQuadratureNodesAndWeights< double > >( )
Definition at line 197 of file gaussianQuadrature.h.
Referenced by getGaussQuadratureNodesAndWeights().
floatGaussQuadratureNodesAndWeights
const std::shared_ptr< GaussQuadratureNodesAndWeights< float > > tudat::numerical_quadrature::floatGaussQuadratureNodesAndWeights static
Initial value:
=
        std::make_shared< GaussQuadratureNodesAndWeights< float > >( )
Definition at line 201 of file gaussianQuadrature.h.
Referenced by getGaussQuadratureNodesAndWeights().