Tudat: tudat::circular_restricted_three_body_problem::LibrationPoint Class Reference
tudat::circular_restricted_three_body_problem::LibrationPoint Class Reference
Libration point class.
#include <librationPoint.h>
Public Types
enum LagrangeLibrationPoints {
l1, l2, l3, l4,
l5
}
Lagrange libration points.
Public Member Functions
LibrationPoint (const double aPrimaryGravitationalParameter, const double aSecondaryGravitationalParameter, const root_finders::RootFinderPointer aRootFinder)
Default constructor.
LibrationPoint (const double aMassParameter, const root_finders::RootFinderPointer aRootFinder)
Default constructor.
void computeLocationOfLibrationPoint (LagrangeLibrationPoints lagrangeLibrationPoint)
Compute location of Lagrange libration point.
Eigen::Vector3d getLocationOfLagrangeLibrationPoint ()
Get location of Lagrange libration point.
double getMassParameter ()
Get dimensionless mass parameter.
Private Member Functions
double computeL1FirstDerivativeLocationFunction (const double xLocationEstimate)
Compute derivative of equation of motion for location of L1 libration point.
double computeL1LocationFunction (const double xLocationEstimate)
Compute equation of motion for location of L1 libration point.
double computeL2FirstDerivativeLocationFunction (const double xLocationEstimate)
Compute derivative of equation of motion for location of L2 libration point.
double computeL2LocationFunction (const double xLocationEstimate)
Compute equation of motion for location of L2 libration point.
double computeL3FirstDerivativeLocationFunction (const double xLocationEstimate)
Compute derivative of equation of motion for location of L3 libration point.
double computeL3LocationFunction (const double xLocationEstimate)
Compute equation of motion for location of L3 libration point.
Private Attributes
const double massParameter
Dimensionless mass parameter.
Eigen::Vector3d positionOfLibrationPoint_
Cartesian position elements of a Lagrange libration point.
const root_finders::RootFinderPointer rootFinder
Shared pointer to the rootfinder.
Detailed Description
This class includes functions to compute the location of Lagrange libration points in the CRTBP.
Definition at line 53 of file librationPoint.h.
Member Enumeration Documentation
LagrangeLibrationPoints
enum tudat::circular_restricted_three_body_problem::LibrationPoint::LagrangeLibrationPoints
Enumerator
l1
l2
l3
l4
l5
Definition at line 59 of file librationPoint.h.
Constructor & Destructor Documentation
LibrationPoint() [1/2]
tudat::circular_restricted_three_body_problem::LibrationPoint::LibrationPoint (const double aPrimaryGravitationalParameter, const double aSecondaryGravitationalParameter, const root_finders::RootFinderPointer aRootFinder) inline
Definition at line 62 of file librationPoint.h.
LibrationPoint() [2/2]
tudat::circular_restricted_three_body_problem::LibrationPoint::LibrationPoint (const double aMassParameter, const root_finders::RootFinderPointer aRootFinder) inline
Default constructor.
Parameters
aMassParameter Dimensionless mass parameter of the smaller of the massive bodies in the CRTBP.
aRootFinder Shared pointer to the rootfinder which is used for finding the L1, L2 and L3 libration points. The rootfinder contains termination conditions inside.
Definition at line 77 of file librationPoint.h.
Member Function Documentation
getMassParameter()
double tudat::circular_restricted_three_body_problem::LibrationPoint::getMassParameter () inline
Returns the dimensionless mass parameter based on the gravitational parameters of the primary and secondary bodies.
Returns
Dimensionless mass parameter.
Definition at line 89 of file librationPoint.h.
References massParameter.
getLocationOfLagrangeLibrationPoint()
Eigen::Vector3d tudat::circular_restricted_three_body_problem::LibrationPoint::getLocationOfLagrangeLibrationPoint () inline
Returns the position vector in Cartesian elements of a Lagrange libration point. The libration point is selected when the computeLocationOfLibrationPoint() function is called.
Returns
Cartesian position elements of Lagrange libration point.
Definition at line 98 of file librationPoint.h.
References computeLocationOfLibrationPoint(), and positionOfLibrationPoint_.
computeLocationOfLibrationPoint()
void tudat::circular_restricted_three_body_problem::LibrationPoint::computeLocationOfLibrationPoint (LagrangeLibrationPoints lagrangeLibrationPoint)
Computes the location as a position vector in Cartesian elements of a given Lagrange libration point.
Parameters
lagrangeLibrationPoint Lagrange libration point.
Definition at line 40 of file librationPoint.cpp.
References computeL1LocationFunction(), computeL2LocationFunction(), and computeL3LocationFunction().
Referenced by getLocationOfLagrangeLibrationPoint().
computeL1LocationFunction()
double tudat::circular_restricted_three_body_problem::LibrationPoint::computeL1LocationFunction (const double xLocationEstimate) inline private
Computes equation of motion, whose root is the x-location in dimensionless coordinates of colinear libration point L1 in the CRTBP (van der Ham, 2012).
Parameters
xLocationEstimate Estimate of x-location of L1 libration point.
Returns
Value of location function.
Definition at line 140 of file librationPoint.h.
References massParameter.
Referenced by computeLocationOfLibrationPoint().
computeL1FirstDerivativeLocationFunction()
double tudat::circular_restricted_three_body_problem::LibrationPoint::computeL1FirstDerivativeLocationFunction (const double xLocationEstimate) inline private
Computes derivative of equation of motion, whose root is the x-location in dimensionless coordinates of colinear libration point L1 in the CRTBP (van der Ham, 2012).
Parameters
xLocationEstimate Estimate of x-location of L1 libration point.
Returns
Value of first derivative of location function.
Definition at line 154 of file librationPoint.h.
References massParameter.
computeL2LocationFunction()
double tudat::circular_restricted_three_body_problem::LibrationPoint::computeL2LocationFunction (const double xLocationEstimate) inline private
Computes equation of motion, whose root is the x-location in dimensionless coordinates of colinear libration point L2 in the CRTBP (van der Ham, 2012).
Parameters
xLocationEstimate Estimate of x-location of L2 libration point.
Returns
Value of location function.
Definition at line 168 of file librationPoint.h.
References massParameter.
Referenced by computeLocationOfLibrationPoint().
computeL2FirstDerivativeLocationFunction()
double tudat::circular_restricted_three_body_problem::LibrationPoint::computeL2FirstDerivativeLocationFunction (const double xLocationEstimate) inline private
Computes derivative of equation of motion, whose root is the x-location in dimensionless coordinates of colinear libration point L2 in the CRTBP (van der Ham, 2012).
Parameters
xLocationEstimate Estimate of x-location of L2 libration point.
Returns
Value of first derivative of location function.
Definition at line 182 of file librationPoint.h.
References massParameter.
computeL3LocationFunction()
double tudat::circular_restricted_three_body_problem::LibrationPoint::computeL3LocationFunction (const double xLocationEstimate) inline private
Computes equation of motion, whose root is the x-location in dimensionless coordinates of colinear libration point L3 in the CRTBP (van der Ham, 2012).
Parameters
xLocationEstimate Estimate of x-location of L3 libration point.
Returns
Value of location function.
Definition at line 196 of file librationPoint.h.
References massParameter.
Referenced by computeLocationOfLibrationPoint().
computeL3FirstDerivativeLocationFunction()
double tudat::circular_restricted_three_body_problem::LibrationPoint::computeL3FirstDerivativeLocationFunction (const double xLocationEstimate) inline private
Computes derivative of equation of motion, whose root is the x-location in dimensionless coordinates of colinear libration point L3 in the CRTBP (van der Ham, 2012).
Parameters
xLocationEstimate Estimate of x-location of L3 libration point.
Returns
Value of first derivative of location function.
Definition at line 210 of file librationPoint.h.
References massParameter.
Member Data Documentation
massParameter
const double tudat::circular_restricted_three_body_problem::LibrationPoint::massParameter private
Dimensionless mass parameter of the smaller of the massive bodies in the CRTBP.
Definition at line 119 of file librationPoint.h.
Referenced by computeL1FirstDerivativeLocationFunction(), computeL1LocationFunction(), computeL2FirstDerivativeLocationFunction(), computeL2LocationFunction(), computeL3FirstDerivativeLocationFunction(), computeL3LocationFunction(), and getMassParameter().
rootFinder
const root_finders::RootFinderPointer tudat::circular_restricted_three_body_problem::LibrationPoint::rootFinder private
Shared pointer to the rootfinder. The rootfinder contains termination conditions inside.
Definition at line 125 of file librationPoint.h.
positionOfLibrationPoint_
Eigen::Vector3d tudat::circular_restricted_three_body_problem::LibrationPoint::positionOfLibrationPoint_ private
Cartesian position elements of a Lagrange libration point.
Definition at line 131 of file librationPoint.h.
Referenced by getLocationOfLagrangeLibrationPoint().
The documentation for this class was generated from the following files:
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/Gravitation/librationPoint.h
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/Gravitation/librationPoint.cpp