Tudat: tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType > Class Template Reference
tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType > Class Template Reference
Class to manage and execute the numerical integration of variational equations of a dynamical system, in addition to the dynamics itself, in a combination of single and multiple arcs.
#include <variationalEquationsSolver.h>
Public Types
typedef Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > MatrixType
typedef Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > VectorType
Public Types inherited from tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >
typedef Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > MatrixType
typedef Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > VectorType
Public Member Functions
HybridArcVariationalEquationsSolver (const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const std::shared_ptr< PropagatorSettings< StateScalarType > > propagatorSettings, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate, const std::vector< double > arcStartTimes, const bool integrateDynamicalAndVariationalEquationsConcurrently=true, const bool clearNumericalSolution=true, const bool integrateEquationsOnCreation=false)
Constructor.
HybridArcVariationalEquationsSolver (const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > singleArcIntegratorSettings, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > multiArcIntegratorSettings, const std::shared_ptr< PropagatorSettings< StateScalarType > > propagatorSettings, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate, const std::vector< double > arcStartTimes, const bool integrateDynamicalAndVariationalEquationsConcurrently=true, const bool clearNumericalSolution=true, const bool integrateEquationsOnCreation=false)
~HybridArcVariationalEquationsSolver ()
Destructor.
virtual std::shared_ptr< DynamicsSimulator< StateScalarType, TimeType > > getDynamicsSimulatorBase ()
Function to retrieve the dynamics simulator object (as base-class pointer)
std::shared_ptr< MultiArcVariationalEquationsSolver< StateScalarType, TimeType > > getMultiArcSolver ()
std::shared_ptr< HybridArcPropagatorSettings< StateScalarType > > getPropagatorSettings ()
Function to retrieve propagator settings used for equations of motion.
std::shared_ptr< SingleArcVariationalEquationsSolver< StateScalarType, TimeType > > getSingleArcSolver ()
Object to solve single-arc variational equations.
void initializeHybridArcVariationalEquationsSolver (const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< PropagatorSettings< StateScalarType > > propagatorSettings, const bool integrateDynamicalAndVariationalEquationsConcurrently, const bool integrateEquationsOnCreation)
void integrateDynamicalEquationsOfMotionOnly (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &initialStateEstimate)
Function to integrate equations of motion only.
void integrateVariationalAndDynamicalEquations (const VectorType &initialStateEstimate, const bool integrateEquationsConcurrently)
Function to integrate variational equations and equations of motion.
void resetParameterEstimate (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > newParameterEstimate, const bool areVariationalEquationsToBeIntegrated=true)
Function to reset parameter estimate and re-integrate equations of motion and, if desired, variational equations.
Public Member Functions inherited from tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >
VariationalEquationsSolver (const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate, const bool clearNumericalSolution=1)
Constructor.
virtual ~VariationalEquationsSolver ()
Destructor.
std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > getParametersToEstimate ()
Function to get the list of objects representing the parameters that are to be integrated.
std::shared_ptr< CombinedStateTransitionAndSensitivityMatrixInterface > getStateTransitionMatrixInterface ()
Function to get the state transition matric interface object.
Protected Member Functions
void copyExtendedMultiArcInitialStatesToOriginalSettins ()
Update original propagator settings.
void removeSingleArcBodiesFromMultiArcSolultion (std::vector< std::map< TimeType, VectorType > > &numericalMultiArcSolution)
Function that removes the single-arc body data from propagation results before processing data.
void resetMultiArcInitialStates (const VectorType &manualMultiArcStates)
Function to reset the initial multi-arc states.
void setExtendedMultiArcParameters (const std::vector< double > &arcStartTimes)
Function to set and process the arc start times of the multi-arc propagation.
Protected Member Functions inherited from tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >
MatrixType createInitialConditions (const VectorType initialStateEstimate)
Create initial matrix of numerical soluation to variational + dynamical equations.
Eigen::MatrixXd createInitialVariationalEquationsSolution ()
Create initial matrix of numerical soluation to variational equations.
Protected Attributes
std::vector< double > arcStartTimes_
Times at which arcs for multi-arc solution start.
std::function< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > const double) > initialStatesFromSingleArcPropagation_
Function that retrieves the single-arc bodies' initial states as a function of time.
int multiArcDynamicsSingleArcSize_
Total size of extended estimated multi-arc dynamical parameters.
int multiArcDynamicsSize_
Size of single arc of extended estimated multi-arc dynamical parameters.
std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > multiArcIntegratorSettings_
std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > multiArcParametersToEstimate_
Estimated parameter set with extended multi-arc dynamical parameters only.
std::shared_ptr< MultiArcVariationalEquationsSolver< StateScalarType, TimeType > > multiArcSolver_
Object to solve multi-arc variational equations (single- and multi-arc bodies).
int originalMultiArcDynamicsSingleArcSize_
Size of single arc of original estimated multi-arc dynamical parameters.
int originalMultiArcDynamicsSize_
Total size of original estimated multi-arc dynamical parameters.
std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > originalMultiArcParametersToEstimate_
Estimated parameter set with original multi-arc dynamical parameters only.
std::shared_ptr< MultiArcVariationalEquationsSolver< StateScalarType, TimeType > > originalMultiArcSolver_
Object to solve multi-arc variational equations (multi-arc bodies only).
std::shared_ptr< HybridArcPropagatorSettings< StateScalarType > > originalPopagatorSettings_
Propagator settings, with single- and multi-arc separately.
std::shared_ptr< HybridArcPropagatorSettings< StateScalarType > > propagatorSettings_
Propagator settings, with single-arc bodies added to multi-arc list.
int singleArcDynamicsSize_
Size of estimated single-arc dynamical parameters.
double singleArcInitialTime_
std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > singleArcIntegratorSettings_
Settings to be used for integrator.
std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > singleArcParametersToEstimate_
Estimated parameter set with single-arc dynamical parameters only.
std::shared_ptr< SingleArcVariationalEquationsSolver< StateScalarType, TimeType > > singleArcSolver_
Object to solve single-arc variational equations.
Protected Attributes inherited from tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >
simulation_setup::NamedBodyMap bodyMap_
Map of bodies (with names) of all bodies in integration.
bool clearNumericalSolution_
Boolean to determine whether to clear the raw numerical solution member variables after propagation.
std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate_
Object containing all parameters that are to be estimated and their current settings and values.
int parameterVectorSize_
Number of rows in sensitivity matrix.
std::shared_ptr< CombinedStateTransitionAndSensitivityMatrixInterface > stateTransitionInterface_
Object used for interpolating numerical results of state transition and sensitivity matrix.
int stateTransitionMatrixSize_
Size (rows and columns are equal) of state transition matrix.
Detailed Description
template<typename StateScalarType = double, typename TimeType = double>
class tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >
Class to manage and execute the numerical integration of variational equations of a dynamical system in a combination of single and multiple arcs
In this class, the governing equations are set once, but can be re-integrated for different initial conditions using the same instance of the class.
Definition at line 1610 of file variationalEquationsSolver.h.
Member Typedef Documentation
MatrixType
template<typename StateScalarType = double, typename TimeType = double> typedef Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::MatrixType
Definition at line 1614 of file variationalEquationsSolver.h.
VectorType
template<typename StateScalarType = double, typename TimeType = double> typedef Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::VectorType
Definition at line 1615 of file variationalEquationsSolver.h.
Constructor & Destructor Documentation
HybridArcVariationalEquationsSolver() [1/2]
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::HybridArcVariationalEquationsSolver (const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const std::shared_ptr< PropagatorSettings< StateScalarType > > propagatorSettings, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate, const std::vector< double > arcStartTimes, const bool integrateDynamicalAndVariationalEquationsConcurrently = true, const bool clearNumericalSolution = true, const bool integrateEquationsOnCreation = false) inline
Constructor, sets up object for automatic evaluation and numerical integration of variational equations and equations of motion.
Parameters
bodyMap Map of bodies (with names) of all bodies in integration.
integratorSettings Settings for numerical integrator.
propagatorSettings Settings for propagator.
parametersToEstimate Object containing all parameters that are to be estimated and their current settings and values.
arcStartTimes Start times for separate arcs
integrateDynamicalAndVariationalEquationsConcurrently Boolean defining whether variational and dynamical equations are to be propagated concurrently (if true) or sequentially (of false)
clearNumericalSolution Boolean to determine whether to clear the raw numerical solution member variables (default true) after propagation and resetting of state transition interface.
integrateEquationsOnCreation Boolean to denote whether equations should be integrated immediately at the end of this contructor.
Definition at line 1638 of file variationalEquationsSolver.h.
HybridArcVariationalEquationsSolver() [2/2]
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::HybridArcVariationalEquationsSolver (const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > singleArcIntegratorSettings, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > multiArcIntegratorSettings, const std::shared_ptr< PropagatorSettings< StateScalarType > > propagatorSettings, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate, const std::vector< double > arcStartTimes, const bool integrateDynamicalAndVariationalEquationsConcurrently = true, const bool clearNumericalSolution = true, const bool integrateEquationsOnCreation = false) inline
Definition at line 1657 of file variationalEquationsSolver.h.
~HybridArcVariationalEquationsSolver()
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::~HybridArcVariationalEquationsSolver () inline
Definition at line 1769 of file variationalEquationsSolver.h.
Member Function Documentation
initializeHybridArcVariationalEquationsSolver()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::initializeHybridArcVariationalEquationsSolver (const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< PropagatorSettings< StateScalarType > > propagatorSettings, const bool integrateDynamicalAndVariationalEquationsConcurrently, const bool integrateEquationsOnCreation) inline
Definition at line 1677 of file variationalEquationsSolver.h.
References tudat::propagators::createFrameManager(), tudat::propagators::getExtendedMultiPropagatorSettings(), and tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType, std::enable_if< is_state_scalar_and_time_type< StateScalarType, TimeType >::value, int >::type >::integrateVariationalAndDynamicalEquations().
integrateVariationalAndDynamicalEquations()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations (const VectorType & initialStateEstimate, const bool integrateEquationsConcurrently) inline virtual
Function to integrate variational equations and equations of motion. At the end of this function, the stateTransitionInterface_ is reset with the new state transition and sensitivity matrices. If dynamical solution is to be processed, the environment is also updated to the new solution.
Parameters
initialStateEstimate Initial statez of the equations of motion that is to be used (in same order as in parametersToEstimate_). The initial states of single and multi-arcs propagations are concatenated into a single vector.
integrateEquationsConcurrently Variable determining whether the equations of motion are to be propagated concurrently with variational equations of motion (if true), or before variational equations (if false).
Implements tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >.
Definition at line 1782 of file variationalEquationsSolver.h.
References tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType, std::enable_if< is_state_scalar_and_time_type< StateScalarType, TimeType >::value, int >::type >::stateTransitionInterface_.
integrateDynamicalEquationsOfMotionOnly()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateDynamicalEquationsOfMotionOnly (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > & initialStateEstimate) inline virtual
Function to integrate equations of motion only. If dynamical solution is to be processed, the environment is also updated to the new solution.
Parameters
initialStateEstimate Initial state of the equations of motion that is to be used (in same order as in parametersToEstimate_). The initial states of single and multi-arcs propagations are concatenated into a single vector.
Implements tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >.
Definition at line 1852 of file variationalEquationsSolver.h.
resetParameterEstimate()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::resetParameterEstimate (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > newParameterEstimate, const bool areVariationalEquationsToBeIntegrated = true) inline virtual
Function to reset parameter estimate and re-integrate equations of motion and, if desired, variational equations using the new physical parameters/body initial states.
Parameters
newParameterEstimate New estimate of parameters that are to be estimated, in same order as defined in parametersToEstimate_ member.
areVariationalEquationsToBeIntegrated Boolean defining whether the variational equations are to be reintegrated with the new parameter values.
Implements tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >.
Definition at line 1894 of file variationalEquationsSolver.h.
References tudat::estimatable_parameters::getInitialStateVectorOfBodiesToEstimate(), tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType, std::enable_if< is_state_scalar_and_time_type< StateScalarType, TimeType >::value, int >::type >::integrateDynamicalEquationsOfMotionOnly(), tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType, std::enable_if< is_state_scalar_and_time_type< StateScalarType, TimeType >::value, int >::type >::integrateVariationalAndDynamicalEquations(), and tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType, std::enable_if< is_state_scalar_and_time_type< StateScalarType, TimeType >::value, int >::type >::parametersToEstimate_.
getPropagatorSettings()
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< HybridArcPropagatorSettings< StateScalarType > > tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::getPropagatorSettings () inline
Function to retrieve propagator settings used for equations of motion
Returns
Propagator settings used for equations of motion
Definition at line 1937 of file variationalEquationsSolver.h.
getDynamicsSimulatorBase()
template<typename StateScalarType = double, typename TimeType = double> virtual std::shared_ptr< DynamicsSimulator< StateScalarType, TimeType > > tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::getDynamicsSimulatorBase () inline virtual
Function to retrieve the dynamics simulator object (as base-class pointer). This function is not yet implemented in hybric-arc model, as no single DynamicsSimulator model is used. Calling this function throws an error
Returns
Dynamics simulator object (as base-class pointer)
Implements tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >.
Definition at line 1948 of file variationalEquationsSolver.h.
getMultiArcSolver()
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< MultiArcVariationalEquationsSolver< StateScalarType, TimeType > > tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::getMultiArcSolver () inline
Definition at line 1954 of file variationalEquationsSolver.h.
getSingleArcSolver()
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< SingleArcVariationalEquationsSolver< StateScalarType, TimeType > > tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::getSingleArcSolver () inline
Definition at line 1960 of file variationalEquationsSolver.h.
setExtendedMultiArcParameters()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::setExtendedMultiArcParameters (const std::vector< double > & arcStartTimes) inline protected
Function to set and process the arc start times of the multi-arc propagation
Parameters
arcStartTimes Arc start times of the multi-arc propagation
Definition at line 1972 of file variationalEquationsSolver.h.
References tudat::estimatable_parameters::createEstimatableParameterSetArcSubSet(), tudat::simulation_setup::getAssociatedMultiArcParameter(), and tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType, std::enable_if< is_state_scalar_and_time_type< StateScalarType, TimeType >::value, int >::type >::parametersToEstimate_.
resetMultiArcInitialStates()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::resetMultiArcInitialStates (const VectorType & manualMultiArcStates) inline protected
Function to reset the initial multi-arc states
Parameters
manualMultiArcStates New multi-arc states
Definition at line 2012 of file variationalEquationsSolver.h.
removeSingleArcBodiesFromMultiArcSolultion()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::removeSingleArcBodiesFromMultiArcSolultion (std::vector< std::map< TimeType, VectorType > > & numericalMultiArcSolution) inline protected
Function that removes the single-arc body data from propagation results before processing data
Parameters
numericalMultiArcSolution Full numerical solution of single and multi-arc bodies.
Definition at line 2041 of file variationalEquationsSolver.h.
copyExtendedMultiArcInitialStatesToOriginalSettins()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::copyExtendedMultiArcInitialStatesToOriginalSettins () inline protected
Definition at line 2058 of file variationalEquationsSolver.h.
Member Data Documentation
originalMultiArcSolver_
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< MultiArcVariationalEquationsSolver< StateScalarType, TimeType > > tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::originalMultiArcSolver_ protected
Definition at line 2075 of file variationalEquationsSolver.h.
singleArcSolver_
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< SingleArcVariationalEquationsSolver< StateScalarType, TimeType > > tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::singleArcSolver_ protected
Definition at line 2078 of file variationalEquationsSolver.h.
multiArcSolver_
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< MultiArcVariationalEquationsSolver< StateScalarType, TimeType > > tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::multiArcSolver_ protected
Definition at line 2081 of file variationalEquationsSolver.h.
originalPopagatorSettings_
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< HybridArcPropagatorSettings< StateScalarType > > tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::originalPopagatorSettings_ protected
Definition at line 2084 of file variationalEquationsSolver.h.
propagatorSettings_
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< HybridArcPropagatorSettings< StateScalarType > > tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::propagatorSettings_ protected
Definition at line 2087 of file variationalEquationsSolver.h.
singleArcIntegratorSettings_
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::singleArcIntegratorSettings_ protected
Definition at line 2090 of file variationalEquationsSolver.h.
multiArcIntegratorSettings_
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::multiArcIntegratorSettings_ protected
Definition at line 2092 of file variationalEquationsSolver.h.
singleArcDynamicsSize_
template<typename StateScalarType = double, typename TimeType = double> int tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::singleArcDynamicsSize_ protected
Definition at line 2095 of file variationalEquationsSolver.h.
originalMultiArcDynamicsSingleArcSize_
template<typename StateScalarType = double, typename TimeType = double> int tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::originalMultiArcDynamicsSingleArcSize_ protected
Definition at line 2098 of file variationalEquationsSolver.h.
originalMultiArcDynamicsSize_
template<typename StateScalarType = double, typename TimeType = double> int tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::originalMultiArcDynamicsSize_ protected
Definition at line 2101 of file variationalEquationsSolver.h.
multiArcDynamicsSize_
template<typename StateScalarType = double, typename TimeType = double> int tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::multiArcDynamicsSize_ protected
Definition at line 2104 of file variationalEquationsSolver.h.
multiArcDynamicsSingleArcSize_
template<typename StateScalarType = double, typename TimeType = double> int tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::multiArcDynamicsSingleArcSize_ protected
Definition at line 2107 of file variationalEquationsSolver.h.
singleArcParametersToEstimate_
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::singleArcParametersToEstimate_ protected
Definition at line 2110 of file variationalEquationsSolver.h.
originalMultiArcParametersToEstimate_
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::originalMultiArcParametersToEstimate_ protected
Definition at line 2113 of file variationalEquationsSolver.h.
multiArcParametersToEstimate_
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::multiArcParametersToEstimate_ protected
Definition at line 2116 of file variationalEquationsSolver.h.
arcStartTimes_
template<typename StateScalarType = double, typename TimeType = double> std::vector< double > tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::arcStartTimes_ protected
Definition at line 2119 of file variationalEquationsSolver.h.
initialStatesFromSingleArcPropagation_
template<typename StateScalarType = double, typename TimeType = double> std::function< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > const double) > tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::initialStatesFromSingleArcPropagation_ protected
Function that retrieves the single-arc bodies' initial states as a function of time, is used to update the multi-arc initial states after the single-arc propagation
Definition at line 2126 of file variationalEquationsSolver.h.
singleArcInitialTime_
template<typename StateScalarType = double, typename TimeType = double> double tudat::propagators::HybridArcVariationalEquationsSolver< StateScalarType, TimeType >::singleArcInitialTime_ protected
Definition at line 2128 of file variationalEquationsSolver.h.
The documentation for this class was generated from the following file:
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/SimulationSetup/EstimationSetup/variationalEquationsSolver.h