Tudat: tudat::low_thrust_trajectories::SimsFlanagan Class Reference
tudat::low_thrust_trajectories::SimsFlanagan Class Reference
#include <simsFlanagan.h>
Public Member Functions
SimsFlanagan (const Eigen::Vector6d &stateAtDeparture, const Eigen::Vector6d &stateAtArrival, const double centralBodyGravitationalParameter, const double initialSpacecraftMass, const double maximumThrust, const std::function< double(const double) > specificImpulseFunction, const int numberSegments, const double timeOfFlight, std::shared_ptr< simulation_setup::OptimisationSettings > optimisationSettings)
Constructor.
~SimsFlanagan ()
Default destructor.
Eigen::Vector6d computeCurrentStateVector (const double currentTime)
Compute current cartesian state.
Eigen::Vector3d computeCurrentThrustAccelerationDirection (double currentTime, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute direction thrust acceleration in cartesian coordinates.
double computeCurrentThrustAccelerationMagnitude (double currentTime, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute magnitude thrust acceleration.
Eigen::Vector3d computeCurrentThrustForce (double time, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute current thrust vector.
double computeDeltaV ()
Compute DeltaV.
double convertIndependentVariableToTime (const double independentVariable)
Convert independent variable to time.
double convertTimeToIndependentVariable (const double time)
Convert time to independent variable.
std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > createLowThrustTranslationalStatePropagatorSettings (const std::string &bodyToPropagate, const std::string &centralBody, const basic_astrodynamics::AccelerationMap &accelerationModelMap, const std::shared_ptr< propagators::DependentVariableSaveSettings > dependentVariablesToSave)
Define appropriate translational state propagator settings for the full propagation.
std::vector< double > getBestIndividual ()
Return best individual.
std::vector< double > getBestIndividualFitness ()
Return fitness of best individual.
std::shared_ptr< SimsFlanaganModel > getOptimalSimsFlanaganModel ()
Return best Sims-Flanagan leg after optimisation.
void getThrustAccelerationProfile (std::vector< double > &epochsVector, std::map< double, Eigen::VectorXd > &thrustAccelerationProfile, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Return thrust acceleration profile.
void getTrajectory (std::vector< double > &epochsVector, std::map< double, Eigen::Vector6d > &propagatedTrajectory)
Compute state history.
std::pair< std::vector< double >, std::vector< double > > performOptimisation ()
Perform optimisation.
basic_astrodynamics::AccelerationMap retrieveLowThrustAccelerationMap (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::string &centralBody, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Retrieve acceleration map (thrust and central gravity accelerations).
Public Member Functions inherited from tudat::low_thrust_trajectories::LowThrustLeg
LowThrustLeg (const Eigen::Vector6d &stateAtDeparture, const Eigen::Vector6d &stateAtArrival, const double timeOfFlight, const double initialMass, const bool legModelIsForceBased)
Constructor with immediate definition of parameters.
virtual ~LowThrustLeg ()
double computeCurrentMass (const double independentVariable, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute current mass of the spacecraft.
Eigen::Vector3d computeCurrentThrustAcceleration (double time, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute current thrust vector.
void computeSemiAnalyticalAndFullPropagation (const simulation_setup::NamedBodyMap &bodyMapTest, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const std::pair< std::shared_ptr< propagators::PropagatorSettings< double > >, std::shared_ptr< propagators::PropagatorSettings< double > > > &propagatorSettings, std::map< double, Eigen::VectorXd > &fullPropagationResults, std::map< double, Eigen::Vector6d > &semiAnalyticalResults, std::map< double, Eigen::VectorXd > &dependentVariablesHistory)
Full propagation.
std::pair< std::shared_ptr< propagators::PropagatorSettings< double > >, std::shared_ptr< propagators::PropagatorSettings< double > > > createLowThrustPropagatorSettings (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::string &centralBody, const std::function< double(const double) > specificImpulseFunction, const basic_astrodynamics::AccelerationMap perturbingAccelerationsMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > &integratorSettings, const std::shared_ptr< propagators::DependentVariableSaveSettings > &dependentVariablesToSave)
Define appropriate propagator settings for the full propagation.
std::shared_ptr< propulsion::ThrustAcceleration > getLowThrustAccelerationModel (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const double timeOffset=0.0)
Retrieve acceleration model (thrust).
std::shared_ptr< simulation_setup::ThrustAccelerationSettings > getLowThrustAccelerationSettings (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const double timeOffset=0.0)
Retrieve acceleration model (thrust).
void getMassProfile (const std::vector< double > &epochsVector, std::map< double, Eigen::VectorXd > &massProfile, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Return mass profile.
virtual void getThrustForceProfile (std::vector< double > &epochsVector, std::map< double, Eigen::VectorXd > &thrustProfile, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Return thrust profile.
Protected Member Functions
int convertTimeToLegSegment (double currentTime)
Protected Member Functions inherited from tudat::low_thrust_trajectories::LowThrustLeg
double computeCurrentMass (const double timeInitialEpoch, const double timeFinalEpoch, const double massInitialEpoch, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute current mass of the spacecraft between two epochs.
Private Attributes
double centralBodyGravitationalParameter_
std::vector< double > championDesignVariables_
Design variables vector corresponding to the optimisation best individual.
std::vector< double > championFitness_
Fitness vector of the optimisation best individual.
std::pair< std::vector< double >, double > initialGuessThrustModel_
double maximumThrust_
Maximum allowed thrust.
int numberSegments_
Number of segments into which the leg is subdivided.
int numberSegmentsBackwardPropagation_
Number of segments for the backward propagation from arrival to match point.
int numberSegmentsForwardPropagation_
Number of segments for the forward propagation from departure to match point.
std::shared_ptr< simulation_setup::OptimisationSettings > optimisationSettings_
Optimisation settings.
std::shared_ptr< SimsFlanaganModel > simsFlanaganModel_
Sims-Flanagan leg corresponding to the best optimisation output.
std::function< double(const double) > specificImpulseFunction_
Additional Inherited Members
Protected Attributes inherited from tudat::low_thrust_trajectories::LowThrustLeg
double initialMass_
bool legModelIsForceBased_
Eigen::Vector6d stateAtArrival_
Cartesian state at arrival.
Eigen::Vector6d stateAtDeparture_
Cartesian state at departure.
double timeOfFlight_
Time of flight of the trajectory leg.
Detailed Description
Definition at line 46 of file simsFlanagan.h.
Constructor & Destructor Documentation
SimsFlanagan()
tudat::low_thrust_trajectories::SimsFlanagan::SimsFlanagan (const Eigen::Vector6d & stateAtDeparture, const Eigen::Vector6d & stateAtArrival, const double centralBodyGravitationalParameter, const double initialSpacecraftMass, const double maximumThrust, const std::function< double(const double) > specificImpulseFunction, const int numberSegments, const double timeOfFlight, std::shared_ptr< simulation_setup::OptimisationSettings > optimisationSettings) inline
Definition at line 51 of file simsFlanagan.h.
References centralBodyGravitationalParameter_, championDesignVariables_, championFitness_, initialGuessThrustModel_, tudat::low_thrust_trajectories::LowThrustLeg::initialMass_, maximumThrust_, numberSegments_, numberSegmentsBackwardPropagation_, numberSegmentsForwardPropagation_, optimisationSettings_, performOptimisation(), simsFlanaganModel_, specificImpulseFunction_, tudat::low_thrust_trajectories::LowThrustLeg::stateAtArrival_, tudat::low_thrust_trajectories::LowThrustLeg::stateAtDeparture_, and tudat::low_thrust_trajectories::LowThrustLeg::timeOfFlight_.
~SimsFlanagan()
tudat::low_thrust_trajectories::SimsFlanagan::~SimsFlanagan () inline
Definition at line 116 of file simsFlanagan.h.
Member Function Documentation
convertTimeToIndependentVariable()
double tudat::low_thrust_trajectories::SimsFlanagan::convertTimeToIndependentVariable (const double time) inline virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 119 of file simsFlanagan.h.
convertIndependentVariableToTime()
double tudat::low_thrust_trajectories::SimsFlanagan::convertIndependentVariableToTime (const double independentVariable) inline virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 125 of file simsFlanagan.h.
References tudat::propagators::independentVariable, and performOptimisation().
performOptimisation()
std::pair< std::vector< double >, std::vector< double > > tudat::low_thrust_trajectories::SimsFlanagan::performOptimisation ()
Definition at line 124 of file simsFlanagan.cpp.
References centralBodyGravitationalParameter_, championDesignVariables_, championFitness_, initialGuessThrustModel_, tudat::low_thrust_trajectories::LowThrustLeg::initialMass_, maximumThrust_, numberSegments_, optimisationSettings_, specificImpulseFunction_, tudat::low_thrust_trajectories::LowThrustLeg::stateAtArrival_, tudat::low_thrust_trajectories::LowThrustLeg::stateAtDeparture_, and tudat::low_thrust_trajectories::LowThrustLeg::timeOfFlight_.
Referenced by convertIndependentVariableToTime(), and SimsFlanagan().
computeDeltaV()
double tudat::low_thrust_trajectories::SimsFlanagan::computeDeltaV () inline virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 134 of file simsFlanagan.h.
References computeCurrentStateVector(), and simsFlanaganModel_.
computeCurrentStateVector()
Eigen::Vector6d tudat::low_thrust_trajectories::SimsFlanagan::computeCurrentStateVector (const double currentTime) virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 243 of file simsFlanagan.cpp.
References getTrajectory().
Referenced by computeDeltaV().
getTrajectory()
void tudat::low_thrust_trajectories::SimsFlanagan::getTrajectory (std::vector< double > & epochsVector, std::map< double, Eigen::Vector6d > & propagatedTrajectory) inline virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 143 of file simsFlanagan.h.
References computeCurrentThrustAccelerationDirection(), computeCurrentThrustAccelerationMagnitude(), computeCurrentThrustForce(), getThrustAccelerationProfile(), and simsFlanaganModel_.
Referenced by computeCurrentStateVector().
computeCurrentThrustForce()
Eigen::Vector3d tudat::low_thrust_trajectories::SimsFlanagan::computeCurrentThrustForce (double time, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings) virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 201 of file simsFlanagan.cpp.
References convertTimeToLegSegment(), maximumThrust_, and simsFlanaganModel_.
Referenced by computeCurrentThrustAccelerationDirection(), computeCurrentThrustAccelerationMagnitude(), and getTrajectory().
computeCurrentThrustAccelerationDirection()
Eigen::Vector3d tudat::low_thrust_trajectories::SimsFlanagan::computeCurrentThrustAccelerationDirection (double currentTime, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings) virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 177 of file simsFlanagan.cpp.
References computeCurrentThrustForce().
Referenced by getTrajectory().
computeCurrentThrustAccelerationMagnitude()
double tudat::low_thrust_trajectories::SimsFlanagan::computeCurrentThrustAccelerationMagnitude (double currentTime, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings) virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 187 of file simsFlanagan.cpp.
References computeCurrentThrustForce(), and tudat::low_thrust_trajectories::LowThrustLeg::getMassProfile().
Referenced by getTrajectory().
getThrustAccelerationProfile()
void tudat::low_thrust_trajectories::SimsFlanagan::getThrustAccelerationProfile (std::vector< double > & epochsVector, std::map< double, Eigen::VectorXd > & thrustAccelerationProfile, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings) virtual
Reimplemented from tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 213 of file simsFlanagan.cpp.
References tudat::low_thrust_trajectories::LowThrustLeg::getMassProfile(), and tudat::low_thrust_trajectories::LowThrustLeg::getThrustForceProfile().
Referenced by getTrajectory().
getBestIndividual()
std::vector< double > tudat::low_thrust_trajectories::SimsFlanagan::getBestIndividual () inline
Definition at line 172 of file simsFlanagan.h.
References championDesignVariables_.
getBestIndividualFitness()
std::vector< double > tudat::low_thrust_trajectories::SimsFlanagan::getBestIndividualFitness () inline
Definition at line 178 of file simsFlanagan.h.
References championFitness_.
getOptimalSimsFlanaganModel()
std::shared_ptr< SimsFlanaganModel > tudat::low_thrust_trajectories::SimsFlanagan::getOptimalSimsFlanaganModel () inline
Definition at line 185 of file simsFlanagan.h.
References createLowThrustTranslationalStatePropagatorSettings(), retrieveLowThrustAccelerationMap(), and simsFlanaganModel_.
retrieveLowThrustAccelerationMap()
basic_astrodynamics::AccelerationMap tudat::low_thrust_trajectories::SimsFlanagan::retrieveLowThrustAccelerationMap (const simulation_setup::NamedBodyMap & bodyMapTest, const std::string & bodyToPropagate, const std::string & centralBody, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings) virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 257 of file simsFlanagan.cpp.
References simsFlanaganModel_.
Referenced by getOptimalSimsFlanaganModel().
createLowThrustTranslationalStatePropagatorSettings()
std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > tudat::low_thrust_trajectories::SimsFlanagan::createLowThrustTranslationalStatePropagatorSettings (const std::string & bodyToPropagate, const std::string & centralBody, const basic_astrodynamics::AccelerationMap & accelerationModelMap, const std::shared_ptr< propagators::DependentVariableSaveSettings > dependentVariablesToSave) virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 273 of file simsFlanagan.cpp.
References tudat::propagators::cowell, numberSegmentsBackwardPropagation_, numberSegmentsForwardPropagation_, simsFlanaganModel_, tudat::low_thrust_trajectories::LowThrustLeg::stateAtArrival_, tudat::low_thrust_trajectories::LowThrustLeg::stateAtDeparture_, and tudat::low_thrust_trajectories::LowThrustLeg::timeOfFlight_.
Referenced by getOptimalSimsFlanaganModel().
convertTimeToLegSegment()
int tudat::low_thrust_trajectories::SimsFlanagan::convertTimeToLegSegment (double currentTime) inline protected
Definition at line 211 of file simsFlanagan.h.
References simsFlanaganModel_.
Referenced by computeCurrentThrustForce().
Member Data Documentation
centralBodyGravitationalParameter_
double tudat::low_thrust_trajectories::SimsFlanagan::centralBodyGravitationalParameter_ private
Definition at line 218 of file simsFlanagan.h.
Referenced by performOptimisation(), and SimsFlanagan().
maximumThrust_
double tudat::low_thrust_trajectories::SimsFlanagan::maximumThrust_ private
Definition at line 221 of file simsFlanagan.h.
Referenced by computeCurrentThrustForce(), performOptimisation(), and SimsFlanagan().
specificImpulseFunction_
std::function< double (const double) > tudat::low_thrust_trajectories::SimsFlanagan::specificImpulseFunction_ private
Definition at line 223 of file simsFlanagan.h.
Referenced by performOptimisation(), and SimsFlanagan().
numberSegments_
int tudat::low_thrust_trajectories::SimsFlanagan::numberSegments_ private
Definition at line 226 of file simsFlanagan.h.
Referenced by performOptimisation(), and SimsFlanagan().
initialGuessThrustModel_
std::pair< std::vector< double >, double > tudat::low_thrust_trajectories::SimsFlanagan::initialGuessThrustModel_ private
Initial guess for the optimisation. The first element contains the thrust throttles corresponding to the initial guess for the thrust model. The second element defines the bounds around the initial time (in percentage).
Definition at line 231 of file simsFlanagan.h.
Referenced by performOptimisation(), and SimsFlanagan().
optimisationSettings_
std::shared_ptr< simulation_setup::OptimisationSettings > tudat::low_thrust_trajectories::SimsFlanagan::optimisationSettings_ private
Definition at line 234 of file simsFlanagan.h.
Referenced by performOptimisation(), and SimsFlanagan().
championFitness_
std::vector< double > tudat::low_thrust_trajectories::SimsFlanagan::championFitness_ private
Definition at line 237 of file simsFlanagan.h.
Referenced by getBestIndividualFitness(), performOptimisation(), and SimsFlanagan().
championDesignVariables_
std::vector< double > tudat::low_thrust_trajectories::SimsFlanagan::championDesignVariables_ private
Definition at line 240 of file simsFlanagan.h.
Referenced by getBestIndividual(), performOptimisation(), and SimsFlanagan().
numberSegmentsForwardPropagation_
int tudat::low_thrust_trajectories::SimsFlanagan::numberSegmentsForwardPropagation_ private
Definition at line 243 of file simsFlanagan.h.
Referenced by createLowThrustTranslationalStatePropagatorSettings(), and SimsFlanagan().
numberSegmentsBackwardPropagation_
int tudat::low_thrust_trajectories::SimsFlanagan::numberSegmentsBackwardPropagation_ private
Definition at line 246 of file simsFlanagan.h.
Referenced by createLowThrustTranslationalStatePropagatorSettings(), and SimsFlanagan().
simsFlanaganModel_
std::shared_ptr< SimsFlanaganModel > tudat::low_thrust_trajectories::SimsFlanagan::simsFlanaganModel_ private
Definition at line 249 of file simsFlanagan.h.
Referenced by computeCurrentThrustForce(), computeDeltaV(), convertTimeToLegSegment(), createLowThrustTranslationalStatePropagatorSettings(), getOptimalSimsFlanaganModel(), getTrajectory(), retrieveLowThrustAccelerationMap(), and SimsFlanagan().
The documentation for this class was generated from the following files:
Astrodynamics/LowThrustTrajectories/simsFlanagan.h
Astrodynamics/LowThrustTrajectories/simsFlanagan.cpp