Tudat: /home/runner/work/tudatDoxy/tudatDoxy/Tudat/JsonInterface/jsonInterfaceExecute.cpp File Reference
jsonInterfaceExecute.cpp File Reference
#include <getopt.h>
#include "Tudat/JsonInterface/jsonInterface.h"
Functions
int main (int argumentCount, char *arguments[])
Execute propagation of orbit of Asterix around the Earth.
void printHelp ()
Function Documentation
printHelp()
void printHelp ()
Definition at line 15 of file jsonInterfaceExecute.cpp.
Referenced by main().
main()
int main (int argumentCount, char * arguments[])
Definition at line 32 of file jsonInterfaceExecute.cpp.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::exportResults(), printHelp(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::runPropagation(), and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::updateSettings().