Tudat: tudat::low_thrust_trajectories::SimsFlanaganModel Class Reference
tudat::low_thrust_trajectories::SimsFlanaganModel Class Reference
#include <simsFlanaganModel.h>
Public Member Functions
SimsFlanaganModel (const Eigen::Vector6d &stateAtDeparture, const Eigen::Vector6d &stateAtArrival, const double centralBodyGravitationalParameter, const double initialSpacecraftMass, const double maximumThrust, const std::function< double(const double) > specificImpulseFunction, const double timeOfFlight, std::vector< Eigen::Vector3d > &throttles)
Constructor.
~SimsFlanaganModel ()
Default destructor.
int convertTimeToLegSegment (double currentTime)
basic_astrodynamics::AccelerationMap getLowThrustTrajectoryAccelerationMap (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::string &centralBody)
double getMassAtSegment (const int segment)
double getMaximumThrustValue ()
Returns maximum allowed thrust.
int getNumberOfSegments ()
Returns number of segments into which the leg is subdivided.
Eigen::VectorXd getStateAtLegArrival ()
Returns final state at leg arrival.
Eigen::VectorXd getStateAtLegDeparture ()
Returns initial state at leg departure.
Eigen::Vector6d getStateAtMatchPointBackwardPropagation ()
Return state vector at match point from backward propagation.
Eigen::Vector6d getStateAtMatchPointForwardPropagation ()
Return state vector at match point from forward propagation.
std::vector< Eigen::Vector3d > getThrottles ()
Return vector of throttles.
std::shared_ptr< simulation_setup::ThrustAccelerationSettings > getThrustAccelerationSettingsFullLeg (const simulation_setup::NamedBodyMap &bodyMapTest)
double getTimeOfFlight ()
Returns time of flight.
double getTotalDeltaV ()
Return total deltaV required by the trajectory.
void propagateBackwardFromArrivalToMatchPoint ()
Propagate the spacecraft trajectory from arrival to match point (backward propagation).
void propagateForwardFromDepartureToMatchPoint ()
Propagate the spacecraft trajectory from departure to match point (forward propagation).
Eigen::Vector6d propagateInsideBackwardSegment (double initialTime, double finalTime, double segmentDuration, Eigen::Vector6d initialState)
Propagate the trajectory inside one segment.
Eigen::Vector6d propagateInsideForwardSegment (double initialTime, double finalTime, double segmentDuration, Eigen::Vector6d initialState)
Propagate the trajectory inside one segment.
void propagateMassToSegments ()
Propagate the mass from departure to a given segment.
void propagateTrajectory (std::vector< double > epochs, std::map< double, Eigen::Vector6d > &propagatedTrajectory)
Propagate the trajectory to set of epochs.
Eigen::Vector6d propagateTrajectoryBackward (double initialTime, double finalTime, Eigen::Vector6d initialState, double segmentDuration)
Propagate the trajectory to given time.
std::map< double, Eigen::Vector6d > propagateTrajectoryBackward (std::vector< double > epochs, std::map< double, Eigen::Vector6d > &propagatedTrajectory, double segmentDuration)
Propagate the trajectory to set of epochs (backward propagation).
Eigen::Vector6d propagateTrajectoryForward (double initialTime, double finalTime, Eigen::Vector6d initialState, double segmentDuration)
Propagate the trajectory to given time.
std::map< double, Eigen::Vector6d > propagateTrajectoryForward (std::vector< double > epochs, std::map< double, Eigen::Vector6d > &propagatedTrajectory, double segmentDuration)
Propagate the trajectory to set of epochs (forward propagation).
Protected Member Functions
basic_astrodynamics::AccelerationMap getAccelerationModelPerSegment (const unsigned int indexSegment, const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::string &centralBody)
std::shared_ptr< simulation_setup::ThrustAccelerationSettings > getConstantThrustAccelerationSettingsPerSegment (unsigned int indexSegment)
Private Attributes
double centralBodyGravitationalParameter_
Gravitational parameter of the central body of the 2-body problem.
double initialSpacecraftMass_
double maximumThrust_
Maximum allowed thrust.
int numberSegments_
Number of segments into which the leg is subdivided.
int numberSegmentsBackwardPropagation_
Number of segments for the backward propagation from arrival to match point.
int numberSegmentsForwardPropagation_
Number of segments for the forward propagation from departure to match point.
double segmentDurationBackwardPropagation_
Segment duration for backward propagation.
double segmentDurationForwardPropagation_
Segment duration for forward propagation.
std::vector< double > segmentMasses_
std::function< double(const double) > specificImpulseFunction_
Specific impulse.
Eigen::Vector6d stateAtArrival_
State vector of the vehicle at the leg arrival.
Eigen::Vector6d stateAtDeparture_
State vector of the vehicle at the leg departure.
Eigen::Vector6d stateAtMatchPointFromBackwardPropagation_
State at match point from backward propagation.
Eigen::Vector6d stateAtMatchPointFromForwardPropagation_
State at match point from forward propagation.
std::vector< Eigen::Vector3d > throttles_
Vector of throttles for each segment of the leg.
double timeAtMatchPoint_
Time defining the match point (half of the time of flight).
double timeOfFlight_
Time of flight for the leg.
std::vector< double > timesAtNodes_
Vector containing the time associated to each node of the leg.
double totalDeltaV_
Total deltaV.
Detailed Description
Definition at line 25 of file simsFlanaganModel.h.
Constructor & Destructor Documentation
SimsFlanaganModel()
tudat::low_thrust_trajectories::SimsFlanaganModel::SimsFlanaganModel (const Eigen::Vector6d & stateAtDeparture, const Eigen::Vector6d & stateAtArrival, const double centralBodyGravitationalParameter, const double initialSpacecraftMass, const double maximumThrust, const std::function< double(const double) > specificImpulseFunction, const double timeOfFlight, std::vector< Eigen::Vector3d > & throttles) inline
Definition at line 30 of file simsFlanaganModel.h.
References numberSegments_, numberSegmentsBackwardPropagation_, numberSegmentsForwardPropagation_, propagateMassToSegments(), segmentDurationBackwardPropagation_, segmentDurationForwardPropagation_, throttles_, timeAtMatchPoint_, timeOfFlight_, timesAtNodes_, and totalDeltaV_.
~SimsFlanaganModel()
tudat::low_thrust_trajectories::SimsFlanaganModel::~SimsFlanaganModel () inline
Definition at line 77 of file simsFlanaganModel.h.
References propagateBackwardFromArrivalToMatchPoint(), and propagateForwardFromDepartureToMatchPoint().
Member Function Documentation
propagateForwardFromDepartureToMatchPoint()
void tudat::low_thrust_trajectories::SimsFlanaganModel::propagateForwardFromDepartureToMatchPoint ()
Definition at line 234 of file simsFlanaganModel.cpp.
References numberSegmentsForwardPropagation_, propagateTrajectoryForward(), stateAtDeparture_, stateAtMatchPointFromForwardPropagation_, and timeAtMatchPoint_.
Referenced by tudat::low_thrust_trajectories::SimsFlanaganProblem::fitness(), and ~SimsFlanaganModel().
propagateBackwardFromArrivalToMatchPoint()
void tudat::low_thrust_trajectories::SimsFlanaganModel::propagateBackwardFromArrivalToMatchPoint ()
Definition at line 247 of file simsFlanaganModel.cpp.
References numberSegmentsBackwardPropagation_, propagateTrajectoryBackward(), stateAtArrival_, stateAtMatchPointFromBackwardPropagation_, timeAtMatchPoint_, and timeOfFlight_.
Referenced by tudat::low_thrust_trajectories::SimsFlanaganProblem::fitness(), and ~SimsFlanaganModel().
getStateAtLegDeparture()
Eigen::VectorXd tudat::low_thrust_trajectories::SimsFlanaganModel::getStateAtLegDeparture () inline
Definition at line 86 of file simsFlanaganModel.h.
References stateAtDeparture_.
getStateAtLegArrival()
Eigen::VectorXd tudat::low_thrust_trajectories::SimsFlanaganModel::getStateAtLegArrival () inline
Definition at line 92 of file simsFlanaganModel.h.
References stateAtArrival_.
getMaximumThrustValue()
double tudat::low_thrust_trajectories::SimsFlanaganModel::getMaximumThrustValue () inline
Definition at line 98 of file simsFlanaganModel.h.
References maximumThrust_.
getNumberOfSegments()
int tudat::low_thrust_trajectories::SimsFlanaganModel::getNumberOfSegments () inline
Definition at line 104 of file simsFlanaganModel.h.
References numberSegments_.
getTimeOfFlight()
double tudat::low_thrust_trajectories::SimsFlanaganModel::getTimeOfFlight () inline
Definition at line 110 of file simsFlanaganModel.h.
References timeOfFlight_.
getThrottles()
std::vector< Eigen::Vector3d > tudat::low_thrust_trajectories::SimsFlanaganModel::getThrottles () inline
Definition at line 116 of file simsFlanaganModel.h.
References throttles_.
getStateAtMatchPointForwardPropagation()
Eigen::Vector6d tudat::low_thrust_trajectories::SimsFlanaganModel::getStateAtMatchPointForwardPropagation () inline
Definition at line 122 of file simsFlanaganModel.h.
References stateAtMatchPointFromForwardPropagation_.
Referenced by tudat::low_thrust_trajectories::SimsFlanaganProblem::fitness().
getStateAtMatchPointBackwardPropagation()
Eigen::Vector6d tudat::low_thrust_trajectories::SimsFlanaganModel::getStateAtMatchPointBackwardPropagation () inline
Definition at line 128 of file simsFlanaganModel.h.
References convertTimeToLegSegment(), getLowThrustTrajectoryAccelerationMap(), getThrustAccelerationSettingsFullLeg(), getTotalDeltaV(), propagateInsideBackwardSegment(), propagateInsideForwardSegment(), propagateMassToSegments(), propagateTrajectory(), propagateTrajectoryBackward(), propagateTrajectoryForward(), and stateAtMatchPointFromBackwardPropagation_.
Referenced by tudat::low_thrust_trajectories::SimsFlanaganProblem::fitness().
getTotalDeltaV()
double tudat::low_thrust_trajectories::SimsFlanaganModel::getTotalDeltaV ()
Definition at line 169 of file simsFlanaganModel.cpp.
References maximumThrust_, numberSegments_, numberSegmentsForwardPropagation_, segmentDurationBackwardPropagation_, segmentDurationForwardPropagation_, segmentMasses_, throttles_, and totalDeltaV_.
Referenced by tudat::low_thrust_trajectories::SimsFlanaganProblem::fitness(), and getStateAtMatchPointBackwardPropagation().
getLowThrustTrajectoryAccelerationMap()
basic_astrodynamics::AccelerationMap tudat::low_thrust_trajectories::SimsFlanaganModel::getLowThrustTrajectoryAccelerationMap (const simulation_setup::NamedBodyMap & bodyMapTest, const std::string & bodyToPropagate, const std::string & centralBody)
Definition at line 142 of file simsFlanaganModel.cpp.
References tudat::basic_astrodynamics::central_gravity, tudat::simulation_setup::createAccelerationModelsMap(), and getThrustAccelerationSettingsFullLeg().
Referenced by getStateAtMatchPointBackwardPropagation().
propagateTrajectoryForward() [1/2]
Eigen::Vector6d tudat::low_thrust_trajectories::SimsFlanaganModel::propagateTrajectoryForward (double initialTime, double finalTime, Eigen::Vector6d initialState, double segmentDuration)
Propagate the trajectory forward to given time.
Definition at line 391 of file simsFlanaganModel.cpp.
References convertTimeToLegSegment(), propagateInsideForwardSegment(), and timesAtNodes_.
Referenced by getStateAtMatchPointBackwardPropagation(), propagateForwardFromDepartureToMatchPoint(), propagateTrajectory(), and propagateTrajectoryForward().
propagateTrajectoryBackward() [1/2]
Eigen::Vector6d tudat::low_thrust_trajectories::SimsFlanaganModel::propagateTrajectoryBackward (double initialTime, double finalTime, Eigen::Vector6d initialState, double segmentDuration)
Propagate the trajectory backward to given time.
Definition at line 452 of file simsFlanaganModel.cpp.
References convertTimeToLegSegment(), propagateInsideBackwardSegment(), and timesAtNodes_.
Referenced by getStateAtMatchPointBackwardPropagation(), propagateBackwardFromArrivalToMatchPoint(), propagateTrajectory(), and propagateTrajectoryBackward().
propagateTrajectoryForward() [2/2]
std::map< double, Eigen::Vector6d > tudat::low_thrust_trajectories::SimsFlanaganModel::propagateTrajectoryForward (std::vector< double > epochs, std::map< double, Eigen::Vector6d > & propagatedTrajectory, double segmentDuration)
Propagate the trajectory to set of epochs.
Definition at line 510 of file simsFlanaganModel.cpp.
References propagateTrajectoryForward(), stateAtDeparture_, and timeOfFlight_.
propagateTrajectoryBackward() [2/2]
std::map< double, Eigen::Vector6d > tudat::low_thrust_trajectories::SimsFlanaganModel::propagateTrajectoryBackward (std::vector< double > epochs, std::map< double, Eigen::Vector6d > & propagatedTrajectory, double segmentDuration)
Propagate the trajectory to set of epochs.
Definition at line 558 of file simsFlanaganModel.cpp.
References propagateTrajectoryBackward(), stateAtArrival_, and timeOfFlight_.
propagateTrajectory()
void tudat::low_thrust_trajectories::SimsFlanaganModel::propagateTrajectory (std::vector< double > epochs, std::map< double, Eigen::Vector6d > & propagatedTrajectory)
Definition at line 603 of file simsFlanaganModel.cpp.
References propagateTrajectoryBackward(), propagateTrajectoryForward(), segmentDurationBackwardPropagation_, segmentDurationForwardPropagation_, and timeOfFlight_.
Referenced by getStateAtMatchPointBackwardPropagation().
propagateInsideForwardSegment()
Eigen::Vector6d tudat::low_thrust_trajectories::SimsFlanaganModel::propagateInsideForwardSegment (double initialTime, double finalTime, double segmentDuration, Eigen::Vector6d initialState)
Definition at line 261 of file simsFlanaganModel.cpp.
References centralBodyGravitationalParameter_, tudat::orbital_element_conversions::convertCartesianToKeplerianElements(), tudat::orbital_element_conversions::convertKeplerianToCartesianElements(), convertTimeToLegSegment(), maximumThrust_, tudat::orbital_element_conversions::propagateKeplerOrbit(), segmentMasses_, throttles_, and timesAtNodes_.
Referenced by getStateAtMatchPointBackwardPropagation(), and propagateTrajectoryForward().
propagateInsideBackwardSegment()
Eigen::Vector6d tudat::low_thrust_trajectories::SimsFlanaganModel::propagateInsideBackwardSegment (double initialTime, double finalTime, double segmentDuration, Eigen::Vector6d initialState)
Definition at line 326 of file simsFlanaganModel.cpp.
References centralBodyGravitationalParameter_, tudat::orbital_element_conversions::convertCartesianToKeplerianElements(), tudat::orbital_element_conversions::convertKeplerianToCartesianElements(), convertTimeToLegSegment(), maximumThrust_, tudat::orbital_element_conversions::propagateKeplerOrbit(), segmentMasses_, throttles_, and timesAtNodes_.
Referenced by getStateAtMatchPointBackwardPropagation(), and propagateTrajectoryBackward().
propagateMassToSegments()
void tudat::low_thrust_trajectories::SimsFlanaganModel::propagateMassToSegments ()
Definition at line 194 of file simsFlanaganModel.cpp.
References initialSpacecraftMass_, maximumThrust_, numberSegments_, numberSegmentsBackwardPropagation_, numberSegmentsForwardPropagation_, tudat::physical_constants::SEA_LEVEL_GRAVITATIONAL_ACCELERATION, segmentMasses_, specificImpulseFunction_, throttles_, timeAtMatchPoint_, and timesAtNodes_.
Referenced by getStateAtMatchPointBackwardPropagation(), and SimsFlanaganModel().
convertTimeToLegSegment()
int tudat::low_thrust_trajectories::SimsFlanaganModel::convertTimeToLegSegment (double currentTime)
Definition at line 22 of file simsFlanaganModel.cpp.
References numberSegments_, numberSegmentsBackwardPropagation_, numberSegmentsForwardPropagation_, timeAtMatchPoint_, and timeOfFlight_.
Referenced by getStateAtMatchPointBackwardPropagation(), getThrustAccelerationSettingsFullLeg(), propagateInsideBackwardSegment(), propagateInsideForwardSegment(), propagateTrajectoryBackward(), and propagateTrajectoryForward().
getThrustAccelerationSettingsFullLeg()
std::shared_ptr< simulation_setup::ThrustAccelerationSettings > tudat::low_thrust_trajectories::SimsFlanaganModel::getThrustAccelerationSettingsFullLeg (const simulation_setup::NamedBodyMap & bodyMapTest)
Definition at line 108 of file simsFlanaganModel.cpp.
References convertTimeToLegSegment(), maximumThrust_, specificImpulseFunction_, and throttles_.
Referenced by getLowThrustTrajectoryAccelerationMap(), and getStateAtMatchPointBackwardPropagation().
getMassAtSegment()
double tudat::low_thrust_trajectories::SimsFlanaganModel::getMassAtSegment (const int segment) inline
Definition at line 173 of file simsFlanaganModel.h.
References getAccelerationModelPerSegment(), getConstantThrustAccelerationSettingsPerSegment(), and segmentMasses_.
getConstantThrustAccelerationSettingsPerSegment()
std::shared_ptr< simulation_setup::ThrustAccelerationSettings > tudat::low_thrust_trajectories::SimsFlanaganModel::getConstantThrustAccelerationSettingsPerSegment (unsigned int indexSegment) protected
Definition at line 45 of file simsFlanaganModel.cpp.
References maximumThrust_, specificImpulseFunction_, and throttles_.
Referenced by getAccelerationModelPerSegment(), and getMassAtSegment().
getAccelerationModelPerSegment()
basic_astrodynamics::AccelerationMap tudat::low_thrust_trajectories::SimsFlanaganModel::getAccelerationModelPerSegment (const unsigned int indexSegment, const simulation_setup::NamedBodyMap & bodyMapTest, const std::string & bodyToPropagate, const std::string & centralBody) protected
Definition at line 78 of file simsFlanaganModel.cpp.
References tudat::basic_astrodynamics::central_gravity, tudat::simulation_setup::createAccelerationModelsMap(), and getConstantThrustAccelerationSettingsPerSegment().
Referenced by getMassAtSegment().
Member Data Documentation
stateAtDeparture_
Eigen::Vector6d tudat::low_thrust_trajectories::SimsFlanaganModel::stateAtDeparture_ private
Definition at line 192 of file simsFlanaganModel.h.
Referenced by getStateAtLegDeparture(), propagateForwardFromDepartureToMatchPoint(), and propagateTrajectoryForward().
stateAtArrival_
Eigen::Vector6d tudat::low_thrust_trajectories::SimsFlanaganModel::stateAtArrival_ private
Definition at line 195 of file simsFlanaganModel.h.
Referenced by getStateAtLegArrival(), propagateBackwardFromArrivalToMatchPoint(), and propagateTrajectoryBackward().
centralBodyGravitationalParameter_
double tudat::low_thrust_trajectories::SimsFlanaganModel::centralBodyGravitationalParameter_ private
Definition at line 198 of file simsFlanaganModel.h.
Referenced by propagateInsideBackwardSegment(), and propagateInsideForwardSegment().
initialSpacecraftMass_
double tudat::low_thrust_trajectories::SimsFlanaganModel::initialSpacecraftMass_ private
Definition at line 200 of file simsFlanaganModel.h.
Referenced by propagateMassToSegments().
maximumThrust_
double tudat::low_thrust_trajectories::SimsFlanaganModel::maximumThrust_ private
Definition at line 203 of file simsFlanaganModel.h.
Referenced by getConstantThrustAccelerationSettingsPerSegment(), getMaximumThrustValue(), getThrustAccelerationSettingsFullLeg(), getTotalDeltaV(), propagateInsideBackwardSegment(), propagateInsideForwardSegment(), and propagateMassToSegments().
specificImpulseFunction_
std::function< double (const double) > tudat::low_thrust_trajectories::SimsFlanaganModel::specificImpulseFunction_ private
Definition at line 206 of file simsFlanaganModel.h.
Referenced by getConstantThrustAccelerationSettingsPerSegment(), getThrustAccelerationSettingsFullLeg(), and propagateMassToSegments().
numberSegments_
int tudat::low_thrust_trajectories::SimsFlanaganModel::numberSegments_ private
Definition at line 209 of file simsFlanaganModel.h.
Referenced by convertTimeToLegSegment(), getNumberOfSegments(), getTotalDeltaV(), propagateMassToSegments(), and SimsFlanaganModel().
timeOfFlight_
double tudat::low_thrust_trajectories::SimsFlanaganModel::timeOfFlight_ private
Definition at line 212 of file simsFlanaganModel.h.
Referenced by convertTimeToLegSegment(), getTimeOfFlight(), propagateBackwardFromArrivalToMatchPoint(), propagateTrajectory(), propagateTrajectoryBackward(), propagateTrajectoryForward(), and SimsFlanaganModel().
throttles_
std::vector< Eigen::Vector3d > tudat::low_thrust_trajectories::SimsFlanaganModel::throttles_ private
Definition at line 215 of file simsFlanaganModel.h.
Referenced by getConstantThrustAccelerationSettingsPerSegment(), getThrottles(), getThrustAccelerationSettingsFullLeg(), getTotalDeltaV(), propagateInsideBackwardSegment(), propagateInsideForwardSegment(), propagateMassToSegments(), and SimsFlanaganModel().
segmentMasses_
std::vector< double > tudat::low_thrust_trajectories::SimsFlanaganModel::segmentMasses_ private
Definition at line 217 of file simsFlanaganModel.h.
Referenced by getMassAtSegment(), getTotalDeltaV(), propagateInsideBackwardSegment(), propagateInsideForwardSegment(), and propagateMassToSegments().
numberSegmentsForwardPropagation_
int tudat::low_thrust_trajectories::SimsFlanaganModel::numberSegmentsForwardPropagation_ private
Definition at line 221 of file simsFlanaganModel.h.
Referenced by convertTimeToLegSegment(), getTotalDeltaV(), propagateForwardFromDepartureToMatchPoint(), propagateMassToSegments(), and SimsFlanaganModel().
numberSegmentsBackwardPropagation_
int tudat::low_thrust_trajectories::SimsFlanaganModel::numberSegmentsBackwardPropagation_ private
Definition at line 224 of file simsFlanaganModel.h.
Referenced by convertTimeToLegSegment(), propagateBackwardFromArrivalToMatchPoint(), propagateMassToSegments(), and SimsFlanaganModel().
segmentDurationForwardPropagation_
double tudat::low_thrust_trajectories::SimsFlanaganModel::segmentDurationForwardPropagation_ private
Definition at line 227 of file simsFlanaganModel.h.
Referenced by getTotalDeltaV(), propagateTrajectory(), and SimsFlanaganModel().
segmentDurationBackwardPropagation_
double tudat::low_thrust_trajectories::SimsFlanaganModel::segmentDurationBackwardPropagation_ private
Definition at line 230 of file simsFlanaganModel.h.
Referenced by getTotalDeltaV(), propagateTrajectory(), and SimsFlanaganModel().
timeAtMatchPoint_
double tudat::low_thrust_trajectories::SimsFlanaganModel::timeAtMatchPoint_ private
Definition at line 233 of file simsFlanaganModel.h.
Referenced by convertTimeToLegSegment(), propagateBackwardFromArrivalToMatchPoint(), propagateForwardFromDepartureToMatchPoint(), propagateMassToSegments(), and SimsFlanaganModel().
stateAtMatchPointFromForwardPropagation_
Eigen::Vector6d tudat::low_thrust_trajectories::SimsFlanaganModel::stateAtMatchPointFromForwardPropagation_ private
Definition at line 236 of file simsFlanaganModel.h.
Referenced by getStateAtMatchPointForwardPropagation(), and propagateForwardFromDepartureToMatchPoint().
stateAtMatchPointFromBackwardPropagation_
Eigen::Vector6d tudat::low_thrust_trajectories::SimsFlanaganModel::stateAtMatchPointFromBackwardPropagation_ private
Definition at line 239 of file simsFlanaganModel.h.
Referenced by getStateAtMatchPointBackwardPropagation(), and propagateBackwardFromArrivalToMatchPoint().
totalDeltaV_
double tudat::low_thrust_trajectories::SimsFlanaganModel::totalDeltaV_ private
Definition at line 242 of file simsFlanaganModel.h.
Referenced by getTotalDeltaV(), and SimsFlanaganModel().
timesAtNodes_
std::vector< double > tudat::low_thrust_trajectories::SimsFlanaganModel::timesAtNodes_ private
Definition at line 245 of file simsFlanaganModel.h.
Referenced by propagateInsideBackwardSegment(), propagateInsideForwardSegment(), propagateMassToSegments(), propagateTrajectoryBackward(), propagateTrajectoryForward(), and SimsFlanaganModel().
The documentation for this class was generated from the following files:
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/simsFlanaganModel.h
/home/runner/work/tudatDoxy/tudatDoxy/Tudat/Astrodynamics/LowThrustTrajectories/simsFlanaganModel.cpp