Tudat: tudat::shape_based_methods Namespace Reference
tudat::shape_based_methods Namespace Reference
Classes
class BaseFunctionHodographicShaping
Base class for shaping functions to be used in the hodographic shaping method.
class BaseFunctionHodographicShapingSettings
Settings class for hodographic shaping base functions.
class BaseFunctionSphericalShaping
Base class for shaping functions to be used in the spherical shaping method.
class CompositeElevationFunctionSphericalShaping
class CompositeFunctionHodographicShaping
class CompositeFunctionSphericalShaping
class CompositeRadialFunctionSphericalShaping
class ConstantFunctionHodographicShaping
Constant function.
class ConstantFunctionSphericalShaping
Constant function.
class CosineFunctionHodographicShaping
Cosine function.
class CosineFunctionSphericalShaping
cosine function.
class ExponentialCosineFunctionHodographicShaping
Exponential times cosine function.
class ExponentialFunctionHodographicShaping
Exponential function.
class ExponentialFunctionHodographicShapingSettings
Settings class for hodographic shaping exponential function.
class ExponentialSineFunctionHodographicShaping
Exponential times sine function.
class ExponentialTimesTrigonometricFunctionHodographicShapingSettings
Settings class for hodographic shaping exponential times trigonometric function.
struct FixedTimeHodographicShapingOptimisationProblem
Test function for a new low-thrust trajectory class in Tudat.
class HodographicShaping
struct HodographicShapingOptimisationProblem
Test function for a new low-thrust trajectory class in Tudat.
class LinearFunctionSphericalShaping
Linear function.
class PowerCosineFunctionHodographicShaping
Power times cosine function.
class PowerCosineFunctionSphericalShaping
Power cosine function.
class PowerFunctionHodographicShaping
Power function.
class PowerFunctionHodographicShapingSettings
Settings class for hodographic shaping power function.
class PowerSineFunctionHodographicShaping
Power times sine function.
class PowerSineFunctionSphericalShaping
Power times sine function.
class PowerTimesTrigonometricFunctionHodographicShapingSettings
Settings class for hodographic shaping power times trigonometric function.
class ScaledExponentialCosineFunctionHodographicShaping
Scaled exponential times cosine function.
class ScaledExponentialFunctionHodographicShaping
Scaled exponential function.
class ScaledExponentialSineFunctionHodographicShaping
Scaled exponential times sine function.
class ScaledPowerCosineFunctionHodographicShaping
class ScaledPowerFunctionHodographicShaping
Scaled power function.
class ScaledPowerSineFunctionHodographicShaping
class ShapeBasedMethod
class SineFunctionHodographicShaping
Sine function.
class SineFunctionSphericalShaping
Sine function.
class SphericalShaping
class SquaredFunctionSphericalShaping
x^2 function.
class TrigonometricFunctionHodographicShapingSettings
Settings class for hodographic shaping trigonometric function (either sine or cosine).
Enumerations
enum baseFunctionHodographicShapingType {
constant, sine, cosine, exponential,
scaledExponential, exponentialSine, scaledExponentialSine, exponentialCosine,
scaledExponentialCosine, power, scaledPower, powerCosine,
scaledPowerCosine, powerSine, scaledPowerSine
}
enum baseFunctionSphericalShapingType {
constantSphericalShaping, linearSphericalShaping, squaredSphericalShaping, cosineSphericalShaping,
powerCosineSphericalShaping, sineSphericalShaping, powerSineSphericalShaping
}
Functions
std::shared_ptr< BaseFunctionHodographicShaping > createBaseFunctionHodographicShaping (const baseFunctionHodographicShapingType baseFunctionType, const std::shared_ptr< BaseFunctionHodographicShapingSettings > baseFunctionSettings)
Function to create a base function for hodographic shaping.
std::shared_ptr< shape_based_methods::BaseFunctionHodographicShaping > createBaseFunctionHodographicShaping (const shape_based_methods::baseFunctionHodographicShapingType baseFunctionType, const std::shared_ptr< shape_based_methods::BaseFunctionHodographicShapingSettings > baseFunctionSettings)
Function to create a base function for hodographic shaping.
std::shared_ptr< BaseFunctionSphericalShaping > createBaseFunctionSphericalShaping (const baseFunctionSphericalShapingType baseFunctionType)
void getRecommendedAxialVelocityBaseFunctions (std::vector< std::shared_ptr< shape_based_methods::BaseFunctionHodographicShaping > > &axialVelocityFunctionComponents, Eigen::VectorXd &freeCoefficientsAxialVelocityFunction, const double timeOfFlight, const int numberOfRevolutions)
void getRecommendedBaseFunctions (std::vector< std::shared_ptr< shape_based_methods::BaseFunctionHodographicShaping > > &radialVelocityFunctionComponents, std::vector< std::shared_ptr< shape_based_methods::BaseFunctionHodographicShaping > > &normalVelocityFunctionComponents, std::vector< std::shared_ptr< shape_based_methods::BaseFunctionHodographicShaping > > &axialVelocityFunctionComponents, Eigen::VectorXd &freeCoefficientsRadialVelocityFunction, Eigen::VectorXd &freeCoefficientsNormalVelocityFunction, Eigen::VectorXd &freeCoefficientsAxialVelocityFunction, const double timeOfFlight, const int numberOfRevolutions)
void getRecommendedNormalAxialBaseFunctions (std::vector< std::shared_ptr< shape_based_methods::BaseFunctionHodographicShaping > > &normalVelocityFunctionComponents, Eigen::VectorXd &freeCoefficientsNormalVelocityFunction, const double timeOfFlight)
void getRecommendedRadialVelocityBaseFunctions (std::vector< std::shared_ptr< shape_based_methods::BaseFunctionHodographicShaping > > &radialVelocityFunctionComponents, Eigen::VectorXd &freeCoefficientsRadialVelocityFunction, const double timeOfFlight)
Enumeration Type Documentation
baseFunctionHodographicShapingType
enum tudat::shape_based_methods::baseFunctionHodographicShapingType
Enumerator
constant
sine
cosine
exponential
scaledExponential
exponentialSine
scaledExponentialSine
exponentialCosine
scaledExponentialCosine
power
scaledPower
powerCosine
scaledPowerCosine
powerSine
scaledPowerSine
Definition at line 23 of file baseFunctionsHodographicShaping.h.
baseFunctionSphericalShapingType
enum tudat::shape_based_methods::baseFunctionSphericalShapingType
Enumerator
constantSphericalShaping
linearSphericalShaping
squaredSphericalShaping
cosineSphericalShaping
powerCosineSphericalShaping
sineSphericalShaping
powerSineSphericalShaping
Definition at line 23 of file baseFunctionsSphericalShaping.h.
Function Documentation
createBaseFunctionSphericalShaping()
std::shared_ptr< BaseFunctionSphericalShaping > tudat::shape_based_methods::createBaseFunctionSphericalShaping (const baseFunctionSphericalShapingType baseFunctionType)
Definition at line 22 of file baseFunctionsSphericalShaping.cpp.
References constantSphericalShaping, cosineSphericalShaping, linearSphericalShaping, powerCosineSphericalShaping, powerSineSphericalShaping, sineSphericalShaping, and squaredSphericalShaping.
Referenced by tudat::shape_based_methods::CompositeElevationFunctionSphericalShaping::CompositeElevationFunctionSphericalShaping(), tudat::shape_based_methods::CompositeRadialFunctionSphericalShaping::CompositeRadialFunctionSphericalShaping(), and tudat::shape_based_methods::PowerSineFunctionSphericalShaping::evaluateThirdDerivative().
createBaseFunctionHodographicShaping() [1/2]
std::shared_ptr< BaseFunctionHodographicShaping > tudat::shape_based_methods::createBaseFunctionHodographicShaping (const baseFunctionHodographicShapingType baseFunctionType, const std::shared_ptr< BaseFunctionHodographicShapingSettings > baseFunctionSettings)
Definition at line 23 of file createBaseFunctionHodographicShaping.cpp.
References constant, cosine, exponential, exponentialCosine, exponentialSine, power, powerCosine, powerSine, scaledExponential, scaledExponentialCosine, scaledExponentialSine, scaledPower, scaledPowerCosine, scaledPowerSine, and sine.
Referenced by getRecommendedAxialVelocityBaseFunctions(), getRecommendedBaseFunctions(), getRecommendedNormalAxialBaseFunctions(), and getRecommendedRadialVelocityBaseFunctions().
createBaseFunctionHodographicShaping() [2/2]
std::shared_ptr< shape_based_methods::BaseFunctionHodographicShaping > tudat::shape_based_methods::createBaseFunctionHodographicShaping (const shape_based_methods::baseFunctionHodographicShapingType baseFunctionType, const std::shared_ptr< shape_based_methods::BaseFunctionHodographicShapingSettings > baseFunctionSettings)
getRecommendedBaseFunctions()
void tudat::shape_based_methods::getRecommendedBaseFunctions (std::vector< std::shared_ptr< shape_based_methods::BaseFunctionHodographicShaping > > & radialVelocityFunctionComponents, std::vector< std::shared_ptr< shape_based_methods::BaseFunctionHodographicShaping > > & normalVelocityFunctionComponents, std::vector< std::shared_ptr< shape_based_methods::BaseFunctionHodographicShaping > > & axialVelocityFunctionComponents, Eigen::VectorXd & freeCoefficientsRadialVelocityFunction, Eigen::VectorXd & freeCoefficientsNormalVelocityFunction, Eigen::VectorXd & freeCoefficientsAxialVelocityFunction, const double timeOfFlight, const int numberOfRevolutions)
Definition at line 8 of file getRecommendedBaseFunctionsHodographicShaping.cpp.
References constant, cosine, createBaseFunctionHodographicShaping(), tudat::mathematical_constants::PI, scaledPower, scaledPowerCosine, and scaledPowerSine.
getRecommendedRadialVelocityBaseFunctions()
void tudat::shape_based_methods::getRecommendedRadialVelocityBaseFunctions (std::vector< std::shared_ptr< shape_based_methods::BaseFunctionHodographicShaping > > & radialVelocityFunctionComponents, Eigen::VectorXd & freeCoefficientsRadialVelocityFunction, const double timeOfFlight)
Definition at line 87 of file getRecommendedBaseFunctionsHodographicShaping.cpp.
References constant, createBaseFunctionHodographicShaping(), and scaledPower.
getRecommendedNormalAxialBaseFunctions()
void tudat::shape_based_methods::getRecommendedNormalAxialBaseFunctions (std::vector< std::shared_ptr< shape_based_methods::BaseFunctionHodographicShaping > > & normalVelocityFunctionComponents, Eigen::VectorXd & freeCoefficientsNormalVelocityFunction, const double timeOfFlight)
Definition at line 117 of file getRecommendedBaseFunctionsHodographicShaping.cpp.
References constant, createBaseFunctionHodographicShaping(), and scaledPower.
getRecommendedAxialVelocityBaseFunctions()
void tudat::shape_based_methods::getRecommendedAxialVelocityBaseFunctions (std::vector< std::shared_ptr< shape_based_methods::BaseFunctionHodographicShaping > > & axialVelocityFunctionComponents, Eigen::VectorXd & freeCoefficientsAxialVelocityFunction, const double timeOfFlight, const int numberOfRevolutions)
Definition at line 147 of file getRecommendedBaseFunctionsHodographicShaping.cpp.
References cosine, createBaseFunctionHodographicShaping(), tudat::mathematical_constants::PI, scaledPowerCosine, and scaledPowerSine.