name: UpdateDoxygen
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Make a directory for the build
      run: |
        mkdir build
        cp Doxyfile.in build

    - name: Build doxygen docs
      uses: mattnotmitt/doxygen-action@v1
      with:
        working-directory: 'build/'
        doxyfile-path: '.'

    - name: Check output
      run: |
        ls -l
        ls -l build

    - name: Push to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/html
