name: UpdateDoxygen
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

#   - name: Build doxygen docs
#     uses: mattnotmitt/doxygen-action@v1
#     with:
#       working-directory: 'Tudat/'
#       doxyfile-path: '.'

    - name: Install doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    - name: Run doxygen
      run: |
        doxygen Doxyfile.in

    - name: Check output
      run: |
        ls -l
        ls -l Tudat
        ls -l Tudat/Documentation

    - name: Push to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Tudat/Documentation/html
        publish_branch: gh-pages
