name: UpdateDoxygen
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Build doxygen docs
      uses: mattnotmitt/doxygen-action@v1
      with:
        working-directory: '.'
        doxyfile-path: '.'
        # working-directory: 'Tudat/'

    - name: Check output
      run: |
        ls -l
        ls -l Tudat

    - name: Push to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Tudat/html
