Tudat: tudat::shape_based_methods::ShapeBasedMethod Class Reference
tudat::shape_based_methods::ShapeBasedMethod Class Reference abstract
#include <shapeBasedMethod.h>
Public Member Functions
ShapeBasedMethod (const Eigen::Vector6d &stateAtDeparture, const Eigen::Vector6d &stateAtArrival, const double timeOfFlight, const double initialBodyMass=TUDAT_NAN)
Empty constructor.
virtual ~ShapeBasedMethod ()
Default destructor.
Eigen::Vector3d computeCurrentThrustForce (double time, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute current thrust vector.
std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > createLowThrustTranslationalStatePropagatorSettings (const std::string &bodyToPropagate, const std::string &centralBody, const basic_astrodynamics::AccelerationMap &accelerationModelMap, const std::shared_ptr< propagators::DependentVariableSaveSettings > dependentVariablesToSave)
Define appropriate translational state propagator settings for the full propagation.
virtual double getFinalValueInpendentVariable ()=0
Returns final value of the independent variable.
virtual double getInitialValueInpendentVariable ()=0
Returns initial value of the independent variable.
void getThrustForceProfile (std::vector< double > &epochsVector, std::map< double, Eigen::VectorXd > &thrustProfile, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Return thrust profile.
void getTrajectory (std::vector< double > &epochsVector, std::map< double, Eigen::Vector6d > &propagatedTrajectory)
Returns state history.
basic_astrodynamics::AccelerationMap retrieveLowThrustAccelerationMap (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::string &centralBody, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Retrieve acceleration map (thrust and central gravity accelerations).
Public Member Functions inherited from tudat::low_thrust_trajectories::LowThrustLeg
LowThrustLeg (const Eigen::Vector6d &stateAtDeparture, const Eigen::Vector6d &stateAtArrival, const double timeOfFlight, const double initialMass, const bool legModelIsForceBased)
Constructor with immediate definition of parameters.
virtual ~LowThrustLeg ()
double computeCurrentMass (const double independentVariable, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute current mass of the spacecraft.
virtual Eigen::Vector6d computeCurrentStateVector (const double currentTime)=0
Compute current cartesian state.
Eigen::Vector3d computeCurrentThrustAcceleration (double time, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute current thrust vector.
virtual Eigen::Vector3d computeCurrentThrustAccelerationDirection (double currentTime, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)=0
Compute direction thrust acceleration in cartesian coordinates.
virtual double computeCurrentThrustAccelerationMagnitude (double currentTime, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)=0
Compute magnitude thrust acceleration.
virtual double computeDeltaV ()=0
Compute total deltaV.
void computeSemiAnalyticalAndFullPropagation (const simulation_setup::NamedBodyMap &bodyMapTest, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const std::pair< std::shared_ptr< propagators::PropagatorSettings< double > >, std::shared_ptr< propagators::PropagatorSettings< double > > > &propagatorSettings, std::map< double, Eigen::VectorXd > &fullPropagationResults, std::map< double, Eigen::Vector6d > &semiAnalyticalResults, std::map< double, Eigen::VectorXd > &dependentVariablesHistory)
Full propagation.
virtual double convertIndependentVariableToTime (const double independentVariable)=0
Convert independent variable to time.
virtual double convertTimeToIndependentVariable (const double time)=0
Convert time to independent variable.
std::pair< std::shared_ptr< propagators::PropagatorSettings< double > >, std::shared_ptr< propagators::PropagatorSettings< double > > > createLowThrustPropagatorSettings (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::string &centralBody, const std::function< double(const double) > specificImpulseFunction, const basic_astrodynamics::AccelerationMap perturbingAccelerationsMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > &integratorSettings, const std::shared_ptr< propagators::DependentVariableSaveSettings > &dependentVariablesToSave)
Define appropriate propagator settings for the full propagation.
std::shared_ptr< propulsion::ThrustAcceleration > getLowThrustAccelerationModel (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const double timeOffset=0.0)
Retrieve acceleration model (thrust).
std::shared_ptr< simulation_setup::ThrustAccelerationSettings > getLowThrustAccelerationSettings (const simulation_setup::NamedBodyMap &bodyMapTest, const std::string &bodyToPropagate, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings, const double timeOffset=0.0)
Retrieve acceleration model (thrust).
void getMassProfile (const std::vector< double > &epochsVector, std::map< double, Eigen::VectorXd > &massProfile, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Return mass profile.
virtual void getThrustAccelerationProfile (std::vector< double > &epochsVector, std::map< double, Eigen::VectorXd > &thrustAccelerationProfile, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Return thrust acceleration profile.
Protected Attributes
std::shared_ptr< numerical_quadrature::QuadratureSettings< double > > quadratureSettings_
Numerical quadrature settings, required to compute the time of flight and total deltaV.
Protected Attributes inherited from tudat::low_thrust_trajectories::LowThrustLeg
double initialMass_
bool legModelIsForceBased_
Eigen::Vector6d stateAtArrival_
Cartesian state at arrival.
Eigen::Vector6d stateAtDeparture_
Cartesian state at departure.
double timeOfFlight_
Time of flight of the trajectory leg.
Additional Inherited Members
Protected Member Functions inherited from tudat::low_thrust_trajectories::LowThrustLeg
double computeCurrentMass (const double timeInitialEpoch, const double timeFinalEpoch, const double massInitialEpoch, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings)
Compute current mass of the spacecraft between two epochs.
Detailed Description
Definition at line 32 of file shapeBasedMethod.h.
Constructor & Destructor Documentation
ShapeBasedMethod()
tudat::shape_based_methods::ShapeBasedMethod::ShapeBasedMethod (const Eigen::Vector6d & stateAtDeparture, const Eigen::Vector6d & stateAtArrival, const double timeOfFlight, const double initialBodyMass = TUDAT_NAN) inline
Definition at line 37 of file shapeBasedMethod.h.
~ShapeBasedMethod()
virtual tudat::shape_based_methods::ShapeBasedMethod::~ShapeBasedMethod () inline virtual
Definition at line 44 of file shapeBasedMethod.h.
Member Function Documentation
getInitialValueInpendentVariable()
virtual double tudat::shape_based_methods::ShapeBasedMethod::getInitialValueInpendentVariable () pure virtual
Implemented in tudat::shape_based_methods::HodographicShaping, and tudat::shape_based_methods::SphericalShaping.
getFinalValueInpendentVariable()
virtual double tudat::shape_based_methods::ShapeBasedMethod::getFinalValueInpendentVariable () pure virtual
Implemented in tudat::shape_based_methods::HodographicShaping, and tudat::shape_based_methods::SphericalShaping.
getTrajectory()
void tudat::shape_based_methods::ShapeBasedMethod::getTrajectory (std::vector< double > & epochsVector, std::map< double, Eigen::Vector6d > & propagatedTrajectory) virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 51 of file shapeBasedMethod.cpp.
References tudat::low_thrust_trajectories::LowThrustLeg::computeCurrentStateVector(), and tudat::low_thrust_trajectories::LowThrustLeg::convertTimeToIndependentVariable().
computeCurrentThrustForce()
Eigen::Vector3d tudat::shape_based_methods::ShapeBasedMethod::computeCurrentThrustForce (double time, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings) virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 72 of file shapeBasedMethod.cpp.
References tudat::low_thrust_trajectories::LowThrustLeg::computeCurrentMass(), tudat::low_thrust_trajectories::LowThrustLeg::computeCurrentThrustAccelerationDirection(), tudat::low_thrust_trajectories::LowThrustLeg::computeCurrentThrustAccelerationMagnitude(), tudat::low_thrust_trajectories::LowThrustLeg::convertTimeToIndependentVariable(), tudat::propagators::independentVariable, and tudat::low_thrust_trajectories::LowThrustLeg::initialMass_.
getThrustForceProfile()
void tudat::shape_based_methods::ShapeBasedMethod::getThrustForceProfile (std::vector< double > & epochsVector, std::map< double, Eigen::VectorXd > & thrustProfile, std::function< double(const double) > specificImpulseFunction, std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings) virtual
Reimplemented from tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 87 of file shapeBasedMethod.cpp.
References tudat::low_thrust_trajectories::LowThrustLeg::computeCurrentThrustAccelerationDirection(), tudat::low_thrust_trajectories::LowThrustLeg::computeCurrentThrustAccelerationMagnitude(), tudat::low_thrust_trajectories::LowThrustLeg::convertTimeToIndependentVariable(), createLowThrustTranslationalStatePropagatorSettings(), tudat::low_thrust_trajectories::LowThrustLeg::getMassProfile(), and tudat::propagators::independentVariable.
retrieveLowThrustAccelerationMap()
basic_astrodynamics::AccelerationMap tudat::shape_based_methods::ShapeBasedMethod::retrieveLowThrustAccelerationMap (const simulation_setup::NamedBodyMap & bodyMapTest, const std::string & bodyToPropagate, const std::string & centralBody, const std::function< double(const double) > specificImpulseFunction, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > integratorSettings) virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 20 of file shapeBasedMethod.cpp.
References tudat::basic_astrodynamics::central_gravity, tudat::simulation_setup::createAccelerationModelsMap(), and tudat::low_thrust_trajectories::LowThrustLeg::getLowThrustAccelerationModel().
createLowThrustTranslationalStatePropagatorSettings()
std::pair< std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > >, std::shared_ptr< propagators::TranslationalStatePropagatorSettings< double > > > tudat::shape_based_methods::ShapeBasedMethod::createLowThrustTranslationalStatePropagatorSettings (const std::string & bodyToPropagate, const std::string & centralBody, const basic_astrodynamics::AccelerationMap & accelerationModelMap, const std::shared_ptr< propagators::DependentVariableSaveSettings > dependentVariablesToSave) virtual
Implements tudat::low_thrust_trajectories::LowThrustLeg.
Definition at line 120 of file shapeBasedMethod.cpp.
References tudat::low_thrust_trajectories::LowThrustLeg::computeCurrentStateVector(), tudat::low_thrust_trajectories::LowThrustLeg::convertTimeToIndependentVariable(), tudat::propagators::cowell, and tudat::low_thrust_trajectories::LowThrustLeg::timeOfFlight_.
Referenced by getThrustForceProfile().
Member Data Documentation
quadratureSettings_
std::shared_ptr< numerical_quadrature::QuadratureSettings< double > > tudat::shape_based_methods::ShapeBasedMethod::quadratureSettings_ protected
Definition at line 88 of file shapeBasedMethod.h.
Referenced by tudat::shape_based_methods::HodographicShaping::computeCurrentPolarAngle(), tudat::shape_based_methods::SphericalShaping::computeCurrentTimeFromAzimuthAngle(), tudat::shape_based_methods::SphericalShaping::computeDeltaV(), tudat::shape_based_methods::HodographicShaping::computeDeltaV(), tudat::shape_based_methods::SphericalShaping::computeNormalizedTimeOfFlight(), tudat::shape_based_methods::HodographicShaping::computeThirdFixedCoefficientAxialVelocityFromFinalPolarAngle(), tudat::shape_based_methods::SphericalShaping::convertIndependentVariableToTime(), tudat::shape_based_methods::HodographicShaping::HodographicShaping(), and tudat::shape_based_methods::SphericalShaping::SphericalShaping().
The documentation for this class was generated from the following files:
Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/shapeBasedMethod.h
Astrodynamics/LowThrustTrajectories/ShapeBasedMethods/shapeBasedMethod.cpp