Tudat: tudat::basic_astrodynamics::DissipativeTorqueModel Class Reference
tudat::basic_astrodynamics::DissipativeTorqueModel Class Reference
Class to compute a phenomenological dissipative torque model.
#include <dissipativeTorqueModel.h>
Public Member Functions
DissipativeTorqueModel (const std::function< Eigen::Vector3d() > &bodyFixedRotationVectorFunction, const std::function< Eigen::Matrix3d() > &dampingMatrixFunction, const double bodyMeanRotationRate)
Constructor.
~DissipativeTorqueModel ()
Destructor.
Eigen::Vector3d getTorque ()
Get dissipative torque.
void setDampingMatrixFunction (const Eigen::Matrix3d &dampingMatrix)
Function to modify the damping matrix.
void updateMembers (const double currentTime)
Update member variables used by the torque model.
Public Member Functions inherited from tudat::basic_astrodynamics::TorqueModel
TorqueModel ()
Constructor.
virtual ~TorqueModel ()
Destructor.
virtual void resetTime (const double currentTime=TUDAT_NAN)
Function to reset the current time.
Private Attributes
std::function< Eigen::Vector3d() > bodyFixedRotationVectorFunction_
tion that returns body-fixed angular velocity vector of body
double bodyMeanRotationRate_
Mean angular velocity vector about z-axis (w.r.t. which the deviation is computed)
Eigen::Vector3d currentBodyRotationPerturbationVector_
Current deviation of angular velocity vector from nominal rotation.
Eigen::Vector3d currentTorque_
Current torque, as computed by last call to updateMembers function.
std::function< Eigen::Matrix3d() > dampingMatrixFunction_
Function that returns the damping matrix that defines the dissipation strength.
Additional Inherited Members
Protected Attributes inherited from tudat::basic_astrodynamics::TorqueModel
double currentTime_
Last time at which the updateMembers was evaluated (or NaN if next call is to recompute torque).
Detailed Description
Class to compute a phenomenological dissipative torque model, with the torque proportional to the angular velocity deviation w.r.t. the mean rotation (about body-fixed z-axis).
Definition at line 22 of file dissipativeTorqueModel.h.
Constructor & Destructor Documentation
DissipativeTorqueModel()
tudat::basic_astrodynamics::DissipativeTorqueModel::DissipativeTorqueModel (const std::function< Eigen::Vector3d() > & bodyFixedRotationVectorFunction, const std::function< Eigen::Matrix3d() > & dampingMatrixFunction, const double bodyMeanRotationRate) inline
Constructor
Parameters
bodyFixedRotationVectorFunction Function that returns body-fixed angular velocity vector of body
dampingMatrixFunction Function that returns the damping matrix that defines the dissipation strength
bodyMeanRotationRate Mean angular velocity vector about z-axis (w.r.t. which the deviation is computed)
Definition at line 33 of file dissipativeTorqueModel.h.
~DissipativeTorqueModel()
tudat::basic_astrodynamics::DissipativeTorqueModel::~DissipativeTorqueModel () inline
Definition at line 42 of file dissipativeTorqueModel.h.
Member Function Documentation
getTorque()
Eigen::Vector3d tudat::basic_astrodynamics::DissipativeTorqueModel::getTorque () inline virtual
Returns the dissipative torque.
Returns
Dissipative torque.
Implements tudat::basic_astrodynamics::TorqueModel.
Definition at line 49 of file dissipativeTorqueModel.h.
References currentTorque_.
updateMembers()
void tudat::basic_astrodynamics::DissipativeTorqueModel::updateMembers (const double currentTime) inline virtual
Updates member variables used by the torque model. Function pointers to retrieve the current values of quantities from which the torque is to be calculated are set by constructor. This function calls them to update the associated variables to their current state.
Parameters
currentTime Time at which torque model is to be updated.
Implements tudat::basic_astrodynamics::TorqueModel.
Definition at line 63 of file dissipativeTorqueModel.h.
References bodyFixedRotationVectorFunction_, bodyMeanRotationRate_, currentBodyRotationPerturbationVector_, currentTorque_, and dampingMatrixFunction_.
setDampingMatrixFunction()
void tudat::basic_astrodynamics::DissipativeTorqueModel::setDampingMatrixFunction (const Eigen::Matrix3d & dampingMatrix) inline
Function to modify the damping matrix
Parameters
dampingMatrix New damping matrix
Definition at line 75 of file dissipativeTorqueModel.h.
References dampingMatrixFunction_.
Member Data Documentation
bodyFixedRotationVectorFunction_
std::function< Eigen::Vector3d() > tudat::basic_astrodynamics::DissipativeTorqueModel::bodyFixedRotationVectorFunction_ private
Definition at line 85 of file dissipativeTorqueModel.h.
Referenced by updateMembers().
dampingMatrixFunction_
std::function< Eigen::Matrix3d() > tudat::basic_astrodynamics::DissipativeTorqueModel::dampingMatrixFunction_ private
Definition at line 88 of file dissipativeTorqueModel.h.
Referenced by setDampingMatrixFunction(), and updateMembers().
bodyMeanRotationRate_
double tudat::basic_astrodynamics::DissipativeTorqueModel::bodyMeanRotationRate_ private
Definition at line 91 of file dissipativeTorqueModel.h.
Referenced by updateMembers().
currentBodyRotationPerturbationVector_
Eigen::Vector3d tudat::basic_astrodynamics::DissipativeTorqueModel::currentBodyRotationPerturbationVector_ private
Definition at line 94 of file dissipativeTorqueModel.h.
Referenced by updateMembers().
currentTorque_
Eigen::Vector3d tudat::basic_astrodynamics::DissipativeTorqueModel::currentTorque_ private
Definition at line 97 of file dissipativeTorqueModel.h.
Referenced by getTorque(), and updateMembers().
The documentation for this class was generated from the following file:
Astrodynamics/BasicAstrodynamics/dissipativeTorqueModel.h